### ISSUE TITLE
RHEL CentOS update breaks certain gnome plugins (including Dash to Panel)

### ISSUE THREAD

**Issue by jjbankert** [home-sweet-gnome/dash-to-panel#1000]
**Describe the bug**
Basically this bug: https://bugzilla.redhat.com/show_bug.cgi?id=1762048 but I ran into it on CentOS like this report: https://bugs.centos.org/view.php?id=17311 which provides some of the Dash to Panel specific exceptions

**tl;dr**: Dash to Panel fails to load because a RHEL updated has changed `hasOverview` in `/usr/share/gnome-shell/modes/classic.json` from `true` to `false`.
Reverting from `false` to `true` solves the problem (and vice versa reproduces the problem).

**Linux distribution and version**
CentOS 7, Linux 3.10.0-1127.el7.x86_64

**GNOME Shell version**
GNOME Shell 3.28.3

**Dash-to-Panel version**
23

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Comment by charlesg99** [comment]
Hello, thank you for reporting this, we've seen this in #985. I personally never thought about supporting the classic mode, especially not on modified old gnome-shell version sessions. @jderose9 I leave this one to you, but I would close this. Thanks!

**Comment by jderose9** [comment]
It seems realistic to me that we don't/can't support Classic Mode. It forcefully enables a number of conflicting extensions that can't be disabled by the user, such as Window List. As far as I know, any distro with Classic Mode also has a regular Gnome session that can be used, and I don't see any benefit of using Classic Mode with dash-to-panel?

I can add add something to the README if you agree with that, @charlesg99?

**Comment by charlesg99** [comment]
@jderose9 Sounds good!
