### ISSUE TITLE
Add an option for the "show desktop" buttom to work as a "show activities" buttom

### ISSUE THREAD

**Issue by evertonstz** [home-sweet-gnome/dash-to-panel#1001]
Currently the "show activities" can be accessed via the top-left hot corner, I'm not a huge fan of hot corners due to accidental triggers in my low-dpi laptop screen. The "show desktop" button, in the other hand, mimics the same feature in windows, I'm sure a lot of people have uses for this feature, I don't, so the button is just kinda there, the "activities" menu in the other hand I use very often. 

I'm here to ask for a toggle to actually make the "show desktop" button trigger the activities instead of showing the desktop. I'm not sure if demand is there for this, but I'm sure at least some people in the low-dpi demography could have a use for this.
Cheers!

**Comment by charlesg99** [comment]
Hello evertonstz, thanks for the suggestion, but I wonder why don't you simply use the activities button?

**Comment by evertonstz** [comment]
Hi!
I don't use the Activities button for two reasons: fist one, and not related with dash to panel, is that I already use Arc Menu, so the Activities button won't actually show up, second and the real reason is that I don't want Activities as my main "start menu", I want to use it mainly for selecting windows when my desktop is kinda crowded, so having it in a primary location isn't really interesting, since I would use Arc Menu way more during the day.
Like I said, pretty niche use case, probably for people with lo-DPI screens, could be one feature to populate that "advanced features" menu in the future.

**Comment by charlesg99** [comment]
Hello, please install the master branch, the Activities button can now be used on every monitor and is independent from Arc-Menu. You can also position it anywhere you like, so this is a lot less hacky than converting the Show Desktop button. Thanks!
