### ISSUE TITLE
"No data received" error message after suspension

### ISSUE THREAD

**Issue by amivaleo** [home-sweet-gnome/dash-to-panel#1003]
Hi!

I'm using version 37 of this extension, on Fedora 32, gnome-shell 3.36.2.

I noticed that I get this error message after recovering from a suspension:
![Schermata da 2020-05-14 15-29-11](https://user-images.githubusercontent.com/24316547/81940556-01a15600-95f8-11ea-9882-1428d3cb7291.png)

What is that?

**Comment by charlesg99** [comment]
Hello, this is the update check mechanism that seems to be unable to connect to Github to look if a new version is available. Maybe the network interface is not yet ready when the check is made, not sure. If you want, you can disable the auto-check in the About tab of the settings dialog. Thanks!

**Comment by amivaleo** [comment]
Oh, I see.

Well, I go back to the classic way of installing extension: from the website.

Thank you!
