### ISSUE TITLE
Please add option to show clock and appview button at leftmost of panel 

### ISSUE THREAD

**Issue by toanphuong** [home-sweet-gnome/dash-to-panel#1004]
Dash to panel is a Great Gnome extension!
Please add an option to show clock and/or appview button at leftmost of the panel - the same as position of Start button in Windows 10 OS. :)

Thank you so much!

**Comment by jderose9** [comment]
@toanphuong Check this out - you will soon be able to reorder all of the panel elements:

https://github.com/home-sweet-gnome/dash-to-panel/issues/822

Thanks!
