### ISSUE TITLE
disable application menu not working on POP! _OS 20.04

### ISSUE THREAD

**Issue by nathanmiguel123** [home-sweet-gnome/dash-to-panel#1005]
**Describe the bug**
I like to use this extension together with the arc menu, however the option shows applications is not working correctly. the first time you disable it it closes, after you try it again it just shows and hide the extension icon.

**Linux distribution and version**
POP!_OS 20.04

**GNOME Shell version**
3.36

**Dash-to-Panel version**
V37

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
![Captura de tela de 2020-05-14 12-42-50](https://user-images.githubusercontent.com/29849613/81955669-c6dff380-95e0-11ea-9ea9-fea98b71c64a.png)
![Captura de tela de 2020-05-14 12-43-25](https://user-images.githubusercontent.com/29849613/81955685-cb0c1100-95e0-11ea-9998-c6d06e934ce1.png)

**Additional Info**

**Comment by charlesg99** [comment]
Hello, I don't understand the problem, on your screenshots you are toggling the application menu, which is what appears in the middle of your panel when enabled. Could you elaborate? Thanks!

**Comment by ishan9299** [comment]
Its Not a BUG you have your settings messed up.You have both arc menu (under extensions) and show applications icon (under dash to panel settings) enabled that's why you have 2 menu's. Disable any one of them.

**Comment by charlesg99** [comment]
> Its Not a BUG you have your settings messed up.

What?

> Disable any one of them.

You mean like this?

![Peek 2020-05-18 10-25](https://user-images.githubusercontent.com/33044886/82224644-19c3ee80-98f2-11ea-9bab-c2b472f7035e.gif)
