### ISSUE TITLE
Menu launcher missing

### ISSUE THREAD

**Issue by reywdboy** [home-sweet-gnome/dash-to-panel#1008]
**Bug description**
The menu launcher is missing .. see attached pic

![missing_menu_launcher](https://user-images.githubusercontent.com/20494775/82052553-b9e00480-96b3-11ea-917a-55f3c94a4b62.png)

**Linux distribution and version**
Ubuntu 20.04

**GNOME Shell version**
3.36.1

**Dash-to-Panel version**
version 37

**Dash-to-Panel installed**
The GNOME extensions website

**Additional Info**
Recently upgraded from 19.10 to 20.04

**Comment by charlesg99** [comment]
Hello reywdboy, what is the problem here? Did you enable the show applications button option in the settings? Thanks!

**Comment by reywdboy** [comment]
thanks..  see that now. dont remember having to activate that setting before. thanks for the reply

**Comment by reywdboy** [comment]
not a bug. activate the show applications button option in settings. doh
