### ISSUE TITLE
Mouse selection of workspace ignore natural scrolling settings

### ISSUE THREAD

**Issue by timrichardson** [home-sweet-gnome/dash-to-panel#1011]
**Describe the bug**
When I hover over the Panel and scroll the mouse wheel to change workspace, it is "backwards"; I have natural scrolling set, so I expect that moving the wheel "up" would push me to a high workspace. Instead, I go down. 

**Linux distribution and version**
pop 20.04

**GNOME Shell version**
Run `gnome-shell --version` from the command line to get this

GNOME Shell 3.36.1

**Dash-to-Panel version**
version: 37

**Where was Dash-to-Panel installed from?**
The GNOME extensions website,

**Comment by timrichardson** [comment]
The mouse direction reported to the extension is adjusting for the natural scrolling setting. When I turn natural scrolling off, then pushing "up" on the wheel moves my workspace selection up. 
So the logic of the mouse direction seems wrong to me. I think of the current workspace like the part of the webpage I am on. I expect that the same mouse action which moves me towards to the top of the web page in my browser moves me towards the highest workspace.

**Comment by charlesg99** [comment]
Hello timrichardson, yes, this behavior is consistent with other gnome-shell elements related to workspaces, including the official "Workspace Indicator" extension. As an example, go into the activities overview by pressing <kbd>Super</kbd> and compare changing workspaces while scrolling on the panel and anywhere else on the screen. The same direction is applied when switching workspaces. If scrolling on the panel would yield a different result than scrolling anywhere else on the screen, now that would be confusing! 

Ultimately I guess this is subjective, but we'll leave it as it is to match what gnome-shell does. Thanks!

**Comment by timrichardson** [comment]
thank you, that makes perfect sense. Definitely should be consistent. I hadn't moused over the Activities workspace selector before and I can see your point 100%. Thanks for responding.
