### ISSUE TITLE
Move extension to second screen ?

### ISSUE THREAD

**Issue by nathan30** [home-sweet-gnome/dash-to-panel#1012]
Hi,

Is there any option to put extension into the panel in the second screen ?
And is it possible to have different configuration by screen ? Like having smaller icon on the second screen

thanks

**Comment by jderose9** [comment]
Yes, please right click on panel and click Dash-to-Panel Settings, then pick "Display panels on all monitors".

![image](https://user-images.githubusercontent.com/2118702/82445535-fd02f480-9a72-11ea-8277-538ec45b0549.png)

It is not possible to have separate configurations per monitor at this time.

**Comment by nathan30** [comment]
Thanks for your answers.

But what about  choosing to put extensions into main or second screen ?

**Comment by jderose9** [comment]
@nathan30 Oh, by extensions, I think you mean icons added by other extensions? They add themselves to the panel, so we can't really duplicate them to a 2nd monitor in a reliable manner. However, you can choose which monitor they appear on by setting the primary monitor in the dash-to-panel settings.

That said, in your screenshot, things are not as expected. Have you tried adjusting the Taskbar Position setting?

What are these icons from?

![image](https://user-images.githubusercontent.com/2118702/82735332-ec5eb280-9cee-11ea-9893-678701f04ef6.png)

**Comment by nathan30** [comment]
For the two icons, I failed a little bit my screenshot. It's the Arc Menu icon and Vivaldi from the second screen)

Ok too bad, I wanted to set specific extensions on specific screen. I manage to do this a little bit using Multi Monitor Add-On but it put extension on a top bar and not on Dash-To-Panel bar.

Maybe a future update of Dash-To-Panel ?
