### ISSUE TITLE
Landscape + Portrait panel position

### ISSUE THREAD

**Issue by kevinhwang91** [home-sweet-gnome/dash-to-panel#1015]
I use two monitors, one's orientation is the landscape and set it to be primary display, the other's orientation is the portrait.

I have made the `Panel screen position` option to  Left and the panel at the primary display is on the left side. I also want to show the panel in the second display whose orientation is the portrait on the top or bottom side.

I found Windows 10 had this feature by the way.

**Comment by charlesg99** [comment]
Thanks for the suggestion kevinhwang91.

@jderose9 while we're at it, do you think it would be worthwhile to include the panel position itself as a "per monitor" setting in the current element positions refactoring?

**Comment by charlesg99** [comment]
Hello kevinhwang91, the option to set the panel position per monitor was added on branch `feature-panel-positions`, please try it out! Thanks!

**Comment by kevinhwang91** [comment]
Thanks, it works for me!
