### ISSUE TITLE
Dash failed to show, Error trying to open the extension settings.

### ISSUE THREAD

**Issue by lemon-bean** [home-sweet-gnome/dash-to-panel#1016]
**Describe the bug**
After left the computer along for about a hour, the screen was black. When I logged in it again, the dash failed to show. Then I went to the "Ubuntu Software" app trying to reset the settings of Dash-to-Panel. But what I got is this

![image](https://user-images.githubusercontent.com/62434637/82513654-a1bc1b00-9ae1-11ea-8933-ddb00176a48c.png)

**Linux distribution and version**
Ubuntu 19.10

**GNOME Shell version**
GNOME Shell 3.34.3

**Dash-to-Panel version**
37

**Where was Dash-to-Panel installed from?**
Ubuntu Software App

**Screenshots / Video captures**
As above

**Additional Info**

**Comment by charlesg99** [comment]
Hello, I'm afraid this isn't a dash to panel issue as gnome-shell can't even load the extension. Does the panel comes back if you restart gnome-shell? Thanks!

**Comment by lemon-bean** [comment]
Thank you for your reply! After several times of shutdown and reboot the problem is still there. Since I am new to Ubuntu, I don't know much what is gnome-shell and how it works, and I don't have much time to learn it now. So I just left it there now. Anyway your app is so cool, I like it, and thank you for your reply!
