### ISSUE TITLE
Tray icons become smaller after 20.04 update

### ISSUE THREAD

**Issue by 1v** [home-sweet-gnome/dash-to-panel#1017]
Before update (19.10):
![pic1](https://user-images.githubusercontent.com/6566370/82543184-d371c800-9b5b-11ea-8ab7-255e1280c788.png)
After update (20.04):
![pic2](https://user-images.githubusercontent.com/6566370/82543681-9eb24080-9b5c-11ea-80bc-86050e081cc0.png)
No option to change size.

**Comment by charlesg99** [comment]
Hello, please bring this to the Ubuntu appindicator extension, as we don't control the size of the tray icons. Have a look here: https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/215, https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/211. Thanks!

**Comment by 1v** [comment]
I don't understand. Is gnome-shell-extension-appindicator dependency of this extension or included in gnome by default? Because I don't have this extension installed.

**Comment by charlesg99** [comment]
It is pre-installed on Ubuntu, you can see in the "Extensions" app:

![image](https://user-images.githubusercontent.com/33044886/82560312-3012ba00-9b3f-11ea-8a8b-427938c76087.png)

Thanks!

**Comment by 1v** [comment]
Ok thanks.
