### ISSUE TITLE
Lock screen is broken half the time.

### ISSUE THREAD

**Issue by briangzimmerman** [home-sweet-gnome/dash-to-panel#1019]
**Describe the bug**
50% of the time when my laptop resumes from suspend or I just lock the screen. The lock screen doesn't show. It goes right to the desktop. It goes back and forth - the lock screen works, the lock screen doesn't work. Disabling Dash-to-Panel fixes the problem, but I'd like to find a solution and continue using it.

**Linux distribution and version**
Ubnuntu 20.04

**GNOME Shell version**
GNOME Shell 3.36.2

**Dash-to-Panel version**
37

**Where was Dash-to-Panel installed from?**
The GNOME extensions website.

**Comment by charlesg99** [comment]
Hello briangzimmerman, thank you for the report! Yes, gnome-shell made some changes to optimize the ST styling and they're still working on fixing the fallout. See #976, #981, #996, #1002, please try searching existing issues before creating a new one. Thanks!
