### ISSUE TITLE
No signal 'allocation-changed' on object 'MetaWindowActorX11'

### ISSUE THREAD

**Issue by AlbinoGeek** [home-sweet-gnome/dash-to-panel#1021]
### journalctl

```
$ JS ERROR: Error: No signal 'allocation-changed' on object 'MetaWindowActorX11'
_setFocusedWindow@~/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/proximity.js:153:75
_bindSignals/<@~/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/proximity.js:129:26

JS WARNING: [~/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panel.js 710]: Too many arguments to method Clutter.Actor.set_allocation: expected 1, got 2
JS WARNING: [~/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panel.js 781]: Too many arguments to method Clutter.Actor.allocate: expected 1, got 2
... snip repeats basically ever 5 seconds ...
```

**Things to do first**
- Yes, Fedora 32 uses only X11 now (used to use Wayland, then they reneged.)

- The issue only happens in this extension, and happens when this is the only extension too.

- Yes, there is an extensive JavaScript error in the Allocator seen above.

- I could not find a similar issue posted (googling the error in question shows lots of FAQ on beginners trying to make their own Gnome Extensions, did not seem relevant to a known-working extension breaking.

![image](https://user-images.githubusercontent.com/1910461/82762191-79b80a80-9db4-11ea-8ca1-edb4bcabf27d.png)

**Describe the bug**
Gnome Extensions and Gnome Tweaks show **ERROR** for the load status of this extension. Installing the extension shows "ON" but does not show the bar (already configured, was working before a MINOR gnome update...) Instead, I see the default "Activities" and "Clock", but otherwise empty top bar that Gnome on Fedora presents.

**Linux distribution and version**
Fedora 32 Workstation

**GNOME Shell version**
GNOME Shell 3.36.2
**Specifically**: gnome-shell-3.36.2-201.fc32.pp3345.x86_64

**Dash-to-Panel version**
The latest stable/approved version, 37.

**Where was Dash-to-Panel installed from?**
Gnome extensions website.

**Screenshots / Video captures**
The default bar is shown regardless of if Dash-to-panel is installed or not, after this error.
![image](https://user-images.githubusercontent.com/1910461/82762062-addefb80-9db3-11ea-805b-7e76537230d0.png)

**Additional Info**
It worked before updating to Gnome 3.36.2 ... I am very sure I was a 3.36.x before reboot, but after the system update, Dash-to-panel prevented me from logging in to my session (e.g: Gnome took some 2 minutes to load, as it was repeatedly trying to enable my extensions, which failed.)

I logged into a new user, disabled all extensions in my first user's Gnome profile, then was able to login properly. After re-installing dash-to-panel, it still doesn't work whatsoever anymore.

My dash-to-panel settings are shown below for reference (although, no changes between when it worked, and when it did not. No changes to hardware or system installed software either (only a `dnf update` causing Gnome to increment up.)

**Dash to Panel Settings**

![image](https://user-images.githubusercontent.com/1910461/82762308-0cf14000-9db5-11ea-928d-5783149309c8.png)
![image](https://user-images.githubusercontent.com/1910461/82762316-1aa6c580-9db5-11ea-8806-50af177ec437.png)
![image](https://user-images.githubusercontent.com/1910461/82762319-21cdd380-9db5-11ea-9e3a-d56085234e76.png)
![image](https://user-images.githubusercontent.com/1910461/82762325-2abea500-9db5-11ea-9988-dc7c553c75dc.png)

**Comment by charlesg99** [comment]
Hello AlbinoGeek, seems like something prevents the extension to be loaded correctly. Could you provide a log from the moment gnome-shell starts (a line like `GNOME Shell started at Mon May 25 2020 19:46:40 GMT-0400 (Eastern Daylight Time)`) to the first dash to panel error `No signal 'allocation-changed' on object 'MetaWindowActorX11'`? Thanks!
