### ISSUE TITLE
Uninstall by Gnome extensions website or Gnome tweaks not removing extensions files correctly

### ISSUE THREAD

**Issue by AlbinoGeek** [home-sweet-gnome/dash-to-panel#1022]
When investigating https://github.com/home-sweet-gnome/dash-to-panel/issues/1021 (thus, identical system information and other details regarding the issue, copy-pasted below for template sake.)

**Describe the bug**
Using Gnome Extensions website or Gnome tweaks to remove Dash-to-panel does not actually remove it. Even after doing Alt+F2r and restarting gnome, or relogging from my session, the allocator errors specified in that thread are still being spewed. Clearly the JS files were not deleted if they are still being executed and have the same filepaths...

---

Template sake:

**Things to do first**
- Yes, Fedora 32 uses only X11 now (used to use Wayland, then they reneged.)

- The issue only happens in this extension, and happens when this is the only extension too.

- Yes, there is an extensive JavaScript error in the Allocator seen above.

- I could not find a similar issue posted.

**Linux distribution and version**
Fedora 32 Workstation

**GNOME Shell version**
GNOME Shell 3.36.2
**Specifically**: gnome-shell-3.36.2-201.fc32.pp3345.x86_64

**Dash-to-Panel version**
The latest stable/approved version, 37.

**Where was Dash-to-Panel installed from?**
Gnome extensions website.

**Comment by AlbinoGeek** [comment]
Restarting the computer with no extensions "installed" presents the following message when doing Alt+F2r to reload the Gnome Shell, while watching journalctl

```
GNOME Shell started at Sun May 24 2020 11:56:50 GMT-0700 (Pacific Daylight Time)                                                    
Registering session with GDM                                                                                                                      
Window manager warning: last_user_time (1788868) is greater than comparison timestamp (1787266).  This most likely represents a buggy client sendi
ng inaccurate timestamps in messages such as _NET_ACTIVE_WINDOW.  Trying to work around...
Window manager warning: 0x200003b appears to be one of the offending windows with a timestamp of 1788868.  Working around...
```

If I manually delete all files left over by the lack of dash-to-panel uninstallation, then did Alt+F2r again, this specific warning did not show.

**Comment by AlbinoGeek** [comment]
And to rule out permission issues:
```
$ ls -Al ~/.local/share/gnome-shell/extensions/
total 1
drwxr-xr-x. 5 damon damon 4096 May 24 11:52 dash-to-panel@jderose9.github.com

$ ls -Al ~/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/
total 964
-rw-rw-r--.  1 damon damon  75163 Apr 27 04:51 appIcons.js
-rw-rw-r--.  1 damon damon   3342 Apr 27 04:51 convenience.js
-rw-rw-r--.  1 damon damon  17993 Apr 27 04:51 COPYING
-rw-rw-r--.  1 damon damon   5166 Apr 27 04:51 extension.js
drwxrwxr-x.  2 damon damon    106 Apr 27 04:51 img
-rw-rw-r--.  1 damon damon  14357 Apr 27 04:51 intellihide.js
drwxrwxr-x. 18 damon damon    175 Apr 27 04:51 locale
-rw-------.  1 damon damon   1027 Apr 27 11:51 metadata.json
-rw-rw-r--.  1 damon damon  13749 Apr 27 04:51 overview.js
-rw-rw-r--.  1 damon damon  50855 Apr 27 04:51 panel.js
-rwxrwxr-x.  1 damon damon  30102 Apr 27 04:51 panelManager.js
-rw-rw-r--.  1 damon damon  12747 Apr 27 04:51 panelStyle.js
-rw-rw-r--.  1 damon damon 106959 Apr 27 04:51 prefs.js
-rw-rw-r--.  1 damon damon  18565 Apr 27 04:51 progress.js
-rw-rw-r--.  1 damon damon   8288 Apr 27 04:51 proximity.js
-rw-rw-r--.  1 damon damon   9236 Apr 27 04:51 README.md
drwxrwxr-x.  2 damon damon     91 Apr 27 04:51 schemas
-rw-rw-r--.  1 damon damon 431778 Apr 27 04:51 Settings.ui
-rw-rw-r--.  1 damon damon   3548 Apr 27 04:51 stylesheet.css
-rw-rw-r--.  1 damon damon  50354 Apr 27 04:51 taskbar.js
-rw-rw-r--.  1 damon damon   9979 Apr 27 04:51 transparency.js
-rw-rw-r--.  1 damon damon   1662 Apr 27 04:51 update.js
-rw-rw-r--.  1 damon damon  28781 Apr 27 04:51 utils.js
-rw-rw-r--.  1 damon damon  40654 Apr 27 04:51 windowPreview.js
```

**Comment by charlesg99** [comment]
Hello AlbinoGeek, the install/uninstall from the e.g.o. website is handled by gnome-shell itself, so I would suggest to open an issue on their Gitlab repo. The only install in which we have a hand in is if you install from Github and run the make command. Thanks!
