### ISSUE TITLE
Group running apps to left or right of the panel.

### ISSUE THREAD

**Issue by LucasPB710** [home-sweet-gnome/dash-to-panel#1025]
It would be great if the applications running were grouped on one side of the panel. Or if we have an option to toggle this on/off.

![painel1 1](https://user-images.githubusercontent.com/65160454/83016966-2e426e00-9ff9-11ea-880d-1d486a4de948.png)
The normal panel.

![painel 2](https://user-images.githubusercontent.com/65160454/83016865-09e69180-9ff9-11ea-9f9c-6a2056d7cda5.png)
Running apps in the right side.

![painel 3](https://user-images.githubusercontent.com/65160454/83016867-0b17be80-9ff9-11ea-9690-e0c6c465c0f5.png) 
Running apps in the left side.

**Comment by charlesg99** [comment]
Hello LucasPB710, thank you for the suggestion. I'm not sure I understand what should happen with the favorite icons in this scenario. Running apps that aren't favorites already are grouped to the right of the taskbar, but if you start an instance of one of your favorites, what would happen to its icon? Would you see 2 icons (one for the favorite and one for its running instance), or would you have the favorite icon "moved" to the side with the running applications? Thanks!

**Comment by LucasPB710** [comment]
I think they should move, while they are running, to the left or right, independent of being a favorite, and when the app is closed, the app returns to it original position. But as this changes the position of favorite apps, I think it should be an optional feature.
