### ISSUE TITLE
Lock screen is broken after lock or suspend

### ISSUE THREAD

**Issue by ConeyIsland** [home-sweet-gnome/dash-to-panel#1026]
**Describe the bug**
Lock screen is broken after lock or suspend (no matter from keyboard or menu item click)

**Linux distribution and version**
Ubuntu 20.04 LTS (focal)

**GNOME Shell version**
GNOME Shell 3.36.2

**Dash-to-Panel version**
37

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Comment by talesgomes27** [comment]
Same thing happened on Pop!_OS 20.04. Lock Screen is broken and gnome-shell got a segmentation fault.

**Comment by charlesg99** [comment]
Yes, gnome-shell made some changes to optimize the ST styling and they're still working on fixing the fallout. See #976, #981, #996, #1002, #1019, #1020.

Let's leave this one opened until Ubuntu pushes the gnome-shell fix, as people clearly don't look at closed issues before posting. Thanks!

**Comment by yuriw** [comment]
this seems to be the same as this https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1880337

**Comment by theo-mazars** [comment]
I'm having this error :
`JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js 694]: reference to undefined property "_tweeningToSize"`
from `gnome-shell` when trying to lock my screen with dash to panel extension enabled

Maybe this could help :
When enabling intellihide, if the panel is hide the lock screen is working perfectly.

So as a temporary fix you can enable intellihide and lock your screen when the panel is not shown

**Comment by mcajina74** [comment]
> Maybe this could help :
> When enabling intellihide, if the panel is hide the lock screen is working perfectly.
> 
> So as a temporary fix you can enable intellihide and lock your screen when the panel is not shown

I can confirm that this workaround works. I enabled Intellihide, and enabled "Require pressure at the edge of the screen to reveal the panel" option. Now, the screen locks after my 15 min interval.

**Comment by marceloortolani** [comment]
> I'm having this error :
> `JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js 694]: reference to undefined property "_tweeningToSize"`
> from `gnome-shell` when trying to lock my screen with dash to panel extension enabled
> 
> Maybe this could help :
> When enabling intellihide, if the panel is hide the lock screen is working perfectly.
> 
> So as a temporary fix you can enable intellihide and lock your screen when the panel is not shown

Thanks a lot!!! You solved the problem.

You are right. There is a bug related to Intellihide.

In Gnome Tweak tool, inside "Dash to panel" settings, I enabled Intellihide, then the screen lock (Super+L shortcut) worked! Then I disabled Intellihide...and the screen lock still works for me!

(tested on Ubuntu 20.04 LTS)

**Comment by AykutCevik** [comment]
@marceloortolani unfortunately I can't confirm this. Still have the problem.

**Comment by theo-mazars** [comment]
I've juste installed the last version of the project `7eb8ae22c2e4f15644dca649059ff3b37fe79caa`

The lockscreen is working perfectly on Gnome 3.36.2

You can : 
1. Wait for an update from apt
2. Clone this repository and compile it in `$HOME/.local/share/gnome-shell/extensions` or `/usr/share/gnome-shell/extensions`

**Comment by yuriw** [comment]
@theo-mazars is it enough to clone master and run `make install`?
so far I don't see it fixed.

**Comment by theo-mazars** [comment]
@yuriw I removed the apt packet, then installed the cloned repository in my home folder.
Then run `Alt + f2` and type `r`
This should work.

If it doesn't work, verify where the extension has been compiled and if it's activated.
My computer runs Ubuntu 20.04 with Gnome 3.36.2. Maybe it helps idk..

**Comment by marceloortolani** [comment]
> @marceloortolani unfortunately I can't confirm this. Still have the problem.

I enable Intellihide, wait for the panel to hide. Then I can lock the screen without problems! If I disable Intellihide, I can lock the screen as well...until next reboot! Unfortunately, today I found that I need to do this trick at least one time after a reboot (or session restart). Anyway it's a just workaround for now, while the bug isn't fixed by the developers.

**Comment by marceloortolani** [comment]
> I've juste installed the last version of the project (`7eb8ae22c2e4f15644dca649059ff3b37fe79caa`)
> 
> The lockscreen is working perfectly on Gnome 3.36.2
> 
> You can :
> 
>     1. Wait for an update from apt
> 
>     2. Clone this repository and compile it in `$HOME/.local/share/gnome-shell/extensions` or `/usr/share/gnome-shell/extensions`

After this installation, does lockscreen still work even after reboot and without Intellihide?

**Comment by theo-mazars** [comment]
I don't have problems after reboot or multiple lock.
My lockscreen is working perfectly

**Comment by yuriw** [comment]
no luck :(

**Comment by harshakp06** [comment]
It works fine now.
I had disabled all the extensions and done `update && upgrade`.
Enable extension and run `Alt + f2` and `r` for all the disable extensions.

**Comment by spxak1** [comment]
Compiling from source doesn't work for me either. 
Steps:

1. Clone git
2. Compile (make, make install)
3. Restart shell (Alt+F2 , r)
4. Extension appears on extension app, enable
5. Super+Escape locks screen (very promising, this is where shell crashes).
6. Reboot
7. Super+Escape, shell crashes.
8. Remove dash-to-panel, back to dash-to-dock.

**Comment by rached-97** [comment]
> It works fine now.
> I had disabled all the extensions and done `update && upgrade`.
> Enable extension and run `Alt + f2` and `r` for all the disable extensions.

I've attempted this before. The problem emerged again following system restart.
For now, enabling intellihide has been the easiest workaround.

**Comment by yuriw** [comment]
`enabling intellihide` does not for for me and seems like has an undesirable side-effect - my windows stopped being able to move between multiple monitors when enabled, maybe an unrelated bug.

**Comment by ThatCoderMan69** [comment]
Can confirm, this issue is happening to me as well on Pop!_OS 20.04 with Gnome 3.36.2. I tested this with kernel 5.4, and 5.6. This issue occurs on both these kernels, and I am assuming all other kernels as well.

This is a major bug, and security risk since this bug completely overrides the lock screen, and allows anyone to use the computer without a password.

Hopefully this bug can be fixed in a timely manner.

Unfortunately, enabling _intellihide_ does not solve this issue. Until this issue is fixed, I cannot use Dash to Panel as the security risk is to great.

**Comment by santiagoanaya** [comment]
Hi! I've been trying to resolve this issue for a long time cause I want to support this amazing extension and help the community. I made many tests (cause every change has to be alongside a reboot, because the lock is tricky and it seems to work from time to time.)

So I couldn't get to understad the option of installing it like a github repo (I tried installing it with `apt` but without success on the lockscreen issue) and my working solution was enabling the "Require Pressure" option inside of the "Intellihide" configuration.
I can confirm that I rebooted my computer and is still locking with `Super+L` and with the automatic lock.

Hope it helps somebody else.

(I set the pressure to 50px and 500ms to make it more confortable)

Ubuntu 20.04 with Gnome 3.36.2

**Comment by jozso39** [comment]
also got Pop_OS 20.04. Unfortunately Intellihide (even with "Require pressure") or Dash to panel installed from GitHub doesnt work for me :(
Only disabling the extention by `gnome-extensions disable "dash-to-panel@jderose9.github.com"` works. I hope devs will fix it soon

**Comment by rmkimathi** [comment]
Oh No! My one and only must have extension is botched? IMHO the dash and panel at the bottom gives the best workspace real estate. .... Dash-to-Panel extension should be integrated into the main Ubuntu development channels!

**Comment by 4ndt3s** [comment]
On Ubuntu 20.04 the problem started when updating gnome-shell to 3.36.2-1ubuntu1, then you could downgrade:

`sudo apt install gnome-shell=3.36.1-5ubuntu1 gnome-shell-common=3.36.1-5ubuntu1`

Do it at your own risk.

**Comment by jozso39** [comment]
**I found another workaround:**
1. install gnome-screensaver if you dont have it
`sudo apt install gnome-screensaver`
2. for locking, use command `gnome-screensaver-command -l`
3. map this command to your usual lock screen keyboard shortcut (for me its Super+L)

**Comment by MindPhaser34** [comment]
> **I found another workaround:**
> I use it on Pop OS 20.04 LTS
> 
> 1. install gnome-screensaver if you dont have it
>    `sudo apt install gnome-screensaver`
> 2. for locking, use command `gnome-screensaver-command -l`
> 3. map this command to your usual lock screen keyboard shortcut (for me its Super+L)

it didn't work for me (Pop!_OS 20.04 LTS, Gnome 3.36.2)

**Comment by charlesg99** [comment]
The only workaround that will work is to downgrade to gnome-shell 3.36.1 (as mentioned by @4ndt3s) until [3.36.3](https://wiki.gnome.org/ThreePointThirtyseven/) is released and pushed by Ubuntu. It was due on May 30th, but [it isn't tagged](https://gitlab.gnome.org/GNOME/gnome-shell/-/tags) yet, so soon hopefully.

This is a fixed gnome-shell (ST) bug, not a dash to panel one and many extensions are affected. Sorry about the inconvenience, but aside from removing our stylesheet, we can't do much unfortunately.

**Comment by hengsin** [comment]
this workaround works for me - after restart, goes into gnome tweak tool, turn on and off the dash to panel extension.

**Comment by spxak1** [comment]
> this workaround works for me - after restart, goes into gnome tweak tool, turn off and on the dash to panel extension.

This does not persist after reboot (or even after reloading the shell.  Similarly the lock screen works if you don't reboot/restart the shell after first installation.

It does add up to the complexity of the issue.

**Comment by spxak1** [comment]
The problem  stops if you also run Dash to dock! So keep dash to dock hidden. This persists after reboot and shell restart.

**Comment by xnosek00** [comment]
Hi, I can confirm the issue. The same problem in Ubuntu 20.04. Here is also reported and described issue: https://gitlab.gnome.org/World/ShellExtensions/desktop-icons/-/issues/201

**Comment by BNolet** [comment]
@spxak1 it initially worked but after a few locks it breaks again. Thanks for the suggestion though!

**Comment by BNolet** [comment]
Temporary fix until newer version is released for either D2P or gnome-shell 3.36.3, you can downgrade to 3.36.1 of gnome-shell. I did it like this:

`sudo apt install gnome-shell=3.36.1-5ubuntu1 gnome-shell-common=3.36.1-5ubuntu1` 

Your downgrade version name for 3.36.1 may be different, you can use `sudo apt-cache madison gnome-shell` to find the corresponding versions for your install.

**Comment by rmkimathi** [comment]
https://itsfoss.com/prevent-package-update-ubuntu/

**Comment by BNolet** [comment]
I manually downloaded and installed the debs for the updated package, the issue seems to be fixed. Logged out and logged in, locking works with D2P active

**Comment by gjwgit** [comment]
Similarly, I compiled it on my focal machine to create a Debian package of gnome-shell_3.36.3-1ubuntu2_amd64.deb. I installed and it works just fine now. No more gnome-shell crash on locking the screen with dash-to-panel installed. Either wait for focal to update or else, at your own risk, something like:

```
    $ wajig builddeps gnome-shell
    $ wget http://archive.ubuntu.com/ubuntu/pool/main/g/gnome-shell/gnome-shell_3.36.3.orig.tar.xz
    $ wget http://archive.ubuntu.com/ubuntu/pool/main/g/gnome-shell/gnome-shell_3.36.3-1ubuntu2.debian.tar.xz
    $ tar xvf gnome-shell_3.36.3.orig.tar.xz
    $ cd gnome-shell_3.36.3
    $ tar xvf ../gnome-shell_3.36.3-1ubuntu2.debian.tar.xz
    $ dpkg-buildpackage -us -uc -nc
    $ cd ..
    $ wajig install gnome-shell_3.36.3-1ubuntu2_amd64.deb gnome-shell-common_3.36.3-1ubuntu2_all.deb  gnome-shell-extension-prefs_3.36.3-1ubuntu2_amd64.deb

```

**Comment by BNolet** [comment]
Or manually download the debs using the link provided above... :P

**Comment by spxak1** [comment]
> Similarly, I compiled it on my focal machine to create a Debian package of the update. I installed and it works just fine now. No more gnome-shell crash on locking the screen with dash-to-panel installed. Either wait for focal to update or else:
> 
> ```
>     $ wajig builddeps gnome-shell
>     $ wget http://archive.ubuntu.com/ubuntu/pool/main/g/gnome-shell/gnome-shell_3.36.3.orig.tar.xz
>     $ wget http://archive.ubuntu.com/ubuntu/pool/main/g/gnome-shell/gnome-shell_3.36.3-1ubuntu2.debian.tar.xz
>     $ tar xvf gnome-shell_3.36.3.orig.tar.xz
>     $ cd gnome-shell_3.36.3
>     $ tar xvf ../gnome-shell_3.36.3-1ubuntu2.debian.tar.xz
>     $ dpkg-buildpackage -us -uc -nc
>     $ cd ..
>     $ wajig install gnome-shell_3.36.3-1ubuntu2_amd64.deb gnome-shell-common_3.36.3-1ubuntu2_all.deb  gnome-shell-extension-prefs_3.36.3-1ubuntu2_amd64.deb
> ```
> 
> Then `Alt-F2 r` (restart gnome-shell) and test with `Meta-L` (Lockscreen)

Thanks, this worked great.

**Comment by MindPhaser34** [comment]
> Similarly, I compiled it on my focal machine to create a Debian package of the update. I installed and it works just fine now. No more gnome-shell crash on locking the screen with dash-to-panel installed. Either wait for focal to update or else:
> 
> ```
>     $ wajig builddeps gnome-shell
>     $ wget http://archive.ubuntu.com/ubuntu/pool/main/g/gnome-shell/gnome-shell_3.36.3.orig.tar.xz
>     $ wget http://archive.ubuntu.com/ubuntu/pool/main/g/gnome-shell/gnome-shell_3.36.3-1ubuntu2.debian.tar.xz
>     $ tar xvf gnome-shell_3.36.3.orig.tar.xz
>     $ cd gnome-shell_3.36.3
>     $ tar xvf ../gnome-shell_3.36.3-1ubuntu2.debian.tar.xz
>     $ dpkg-buildpackage -us -uc -nc
>     $ cd ..
>     $ wajig install gnome-shell_3.36.3-1ubuntu2_amd64.deb gnome-shell-common_3.36.3-1ubuntu2_all.deb  gnome-shell-extension-prefs_3.36.3-1ubuntu2_amd64.deb
> ```
> 
> Then `Alt-F2 r` (restart gnome-shell) and test with `Meta-L` (Lockscreen)

Is it work on Pop_OS 20.04?

**Comment by spxak1** [comment]
> Is it work on Pop_OS 20.04?

@MindPhaser34 
Pop 20.04 here. The instructions above work fine to compile 3.36.3. Go ahead.

**Comment by yuriw** [comment]
> Or manually download and install the debs: http://launchpadlibrarian.net/483004869/gnome-shell_3.36.3-1ubuntu2_amd64.deb http://launchpadlibrarian.net/483004865/gnome-shell-common_3.36.3-1ubuntu2_all.deb http://launchpadlibrarian.net/483004868/gnome-shell-extension-prefs_3.36.3-1ubuntu2_amd64.deb

@BNolet 
What is the correct way to apply these ?

I installed in random order and actually saw the problem fixed (:+1: ), but then my Software Updater was not happy and and had to run `sudo apt-get install -f` and then reinstall gnome and the extensions prefs.  Assuming I did something wrong :(

**Comment by BNolet** [comment]
@yuriw I don't believe there's a specific order but what I did was `sudo apt install ~/Downloads/gnome-shell*.deb` and this installed them all at once (be careful that there are no other files that match that glob in the same path as these debs, to prevent the wrong ones from installing)

The need for running `sudo apt-get install -f` may have been something from before installing the packages. I did not encounter the same error so I can't really say for sure what caused it.

**Comment by yuriw** [comment]
@BNolet 
hmm I used `sudo dpkg -i ...`
and you used `sudo apt install ~/Downloads/gnome-shell*.deb` ?

**Comment by BNolet** [comment]
That may be the problem. Apt will automatically install any dependencies
necessary if available.

**Comment by yuriw** [comment]
@BNolet that actually worked perfectly, thx
And my screen lock is back working !

**Comment by arxeiss** [comment]
> @BNolet
> hmm I used `sudo dpkg -i ...`
> and you used `sudo apt install ~/Downloads/gnome-shell*.deb` ?

I also used `sudo dpkg install` and it works for me well on both of my computers

**Comment by hfs** [comment]
For Ubuntu 20.04 the fixed gnome-shell 3.36.3 is now available in the -proposed repository (see [Bug #1877774, #19](https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1877774/comments/19)).

**Comment by krulkrul** [comment]
The proposed version gnome-shell 3.36.3 fixes it for me. Good stuff!

**Comment by cguertin14** [comment]
> Or manually download and install the debs: http://launchpadlibrarian.net/483004869/gnome-shell_3.36.3-1ubuntu2_amd64.deb http://launchpadlibrarian.net/483004865/gnome-shell-common_3.36.3-1ubuntu2_all.deb http://launchpadlibrarian.net/483004868/gnome-shell-extension-prefs_3.36.3-1ubuntu2_amd64.deb

this works perfectly using: `sudo dpkg -i ./*.dev`.

**Comment by daviddostal** [comment]
For anybody looking for a simple temporary "solution", if I disable and then reenable dash-to-panel, the lockscreen starts working until the next restart.

**Comment by slavoroi** [comment]
Installing pre-released versions fixed it for me (one of the updates was gnome-shell 3.36.3)
 :)
![image](https://user-images.githubusercontent.com/13114384/85232381-26fb5e00-b407-11ea-9095-0e076aff8918.png)

**Comment by Abdelwahab07** [comment]
Updated to "gnome-shell 3.36.3" and this issue has been fixed.

**Comment by rmkimathi** [comment]
> Installing pre-released versions fixed it for me (one of the updates was gnome-shell 3.36.3)
> :)
> ![image](https://user-images.githubusercontent.com/13114384/85232381-26fb5e00-b407-11ea-9095-0e076aff8918.png)

Excellent!

**Comment by Santho07** [comment]
If I enable pre - released updates then run ` $ sudo apt update` it shows 123 packages are upgradable. 

But I only want to update the gnome shell pre-released version  3.36.3-1ubuntu2. How can I do so?

**Comment by 4ndt3s** [comment]
Read @krulkrul comment.

**Comment by charlesg99** [comment]
3.36.3 has finally been released by Ubuntu.

**Comment by brunofunnie** [comment]
Yeah confirmed that with Gnome 3.36.3 with Dash-to-Panel v37 it's fixed. Just "sudo apt upgrade" and "alt + f2" hit "r" to restart the Shell or even reboot your machine.

**Comment by diego-G** [comment]
I still have the same problem with `GNOME Shell 3.36.3`. Could anyone help me out?

**Comment by brunofunnie** [comment]
> I still have the same problem with `GNOME Shell 3.36.3`. Could anyone help me out?

My best guess would be to remove all extensions and test it one by one or even reinstalling Dash to Panel, I've just installed Ubuntu 20.04 on a VM and it's working out of the box (running `sudo apt update; sudo apt upgrade` first). So I think it can be something that is in conflict with the extension.

**Comment by diego-G** [comment]
I've fixed it installing dconf-editor and modifying `/org/gnome/desktop/lockdown` value to disable.

**Comment by rmkimathi** [comment]
D2P cured my "distro hopping". Rock solid after gnome-shell 3.36.3 fix. ... The only extension I install on Ubuntu.

![d2p](https://user-images.githubusercontent.com/13484308/86899048-23a7e800-c112-11ea-975f-bac45f655903.png)
