### ISSUE TITLE
Window peeking mode does not revert window stack

### ISSUE THREAD

**Issue by l3nn4rt** [home-sweet-gnome/dash-to-panel#1031]
#### Describe the bug
When exiting peek mode without clicking any preview, the last hovered window remains visible on top of the stack (even if it was minimized).

#### Linux distribution and version
Arch

#### GNOME Shell version
3.36.2

#### Dash-to-Panel version
37

#### Where was Dash-to-Panel installed from?
directly from github master branch.

#### Screenshots / Video captures
Dash to Panel settings is focused but not on top:
![screenshot](https://user-images.githubusercontent.com/20030650/83335566-16dfdb00-a2ae-11ea-8040-0a98c36f18c8.png)

#### Additional Info
It happens both under Xorg and Wayland.

**Comment by charlesg99** [comment]
Thank you for the report @l3nn4rt! You are correct, this is unintended and I could reproduce the issue. A fix for it was added to the master branch, could you please install it and report back? Thanks!

**Comment by l3nn4rt** [comment]
Yes, can confirm that ef3120c solved this. Thank you!
