### ISSUE TITLE
Add unified window list that spans across multiple displays

### ISSUE THREAD

**Issue by JayBeeDe** [home-sweet-gnome/dash-to-panel#1032]
### Context
Dash to Panel is a nice project.
I am actually using it in a dual display configuration.
Here is how it actually looks like
![orig](https://user-images.githubusercontent.com/17429937/83350356-d62ea300-a33b-11ea-8a46-f63de35134c7.png)
FYI: In this example, I'm using another extension for the start menu: Arc Start Menu. Anyway keep it simple and suppose I'm using the start menu provided by dash to panel...

### Idea
The main feature I would like is a single window list (that gathers all applications of all screens), but that spans across displays : 2 or more. No matter whether is screen is primary, secondary, or whether screens are extended and correctly aligned horizontally.
Here is an overview of how it could looks like:
![new](https://user-images.githubusercontent.com/17429937/83350450-813f5c80-a33c-11ea-9bc5-bec3ce1e0f7a.png)

### Integration ideas

![Selection_010](https://user-images.githubusercontent.com/17429937/83351070-3f64e500-a341-11ea-9367-fe2a2ac75313.png)
In the settings, when the "Display panels on all monitors" is enabled, in the (existing) "Multi-monitors options" sub menu, add a setting switch "Span panel across all monitors".
![Selection_011](https://user-images.githubusercontent.com/17429937/83351240-7c7da700-a342-11ea-9f97-6362162d89ae.png)
When enabled, all other (existing) settings in the "Multi-monitors options" window are grayed out and the panel behaves as if the system has a single and wide screen monitor.

**Comment by charlesg99** [comment]
Cool idea, most of it should be covered by the incoming new position options, but the unified window list isn't. Not sure how (easily) feasible it is, especially with ungrouped applications filling up the taskbar on one panel. Thanks for the suggestion!
