### ISSUE TITLE
Some apps draw under the panel

### ISSUE THREAD

**Issue by soslan** [home-sweet-gnome/dash-to-panel#1033]
Sublime text draws context menu under the panel.

Noticed on Fedora 32.

GNOME Shell 3.36.2

**Dash-to-Panel version**
37

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
![Screenshot from 2020-05-31 18-29-39](https://user-images.githubusercontent.com/1307557/83356301-fbd4a000-a36d-11ea-9829-fcd91dd8fafc.png)

**Comment by charlesg99** [comment]
Hello soslan! Seems to be working correctly over here. Are you using the intellihide feature?

![Peek 2020-05-31 12-18](https://user-images.githubusercontent.com/33044886/83357256-4f78c680-a339-11ea-8f3f-681afb40e064.gif)


Also, could you try with another extension that adds a GUI element at the bottom of the screen, say [Window list](https://extensions.gnome.org/extension/602/window-list/) and see if you get the same issue? Most likely is a problem with Sublime's toolkit. 

Thanks!

**Comment by soslan** [comment]
@charlesg99  This issue has been fixed by recent Fedora 32 system update. I posted it here because I thought DtP might be improperly configuring drawable boundaries. Anyway, thank you for your response, and thank you for making this extension!
