### ISSUE TITLE
Panel intellihide ignores the require pressure

### ISSUE THREAD

**Issue by luis-dafonseca** [home-sweet-gnome/dash-to-panel#1035]
Even with the require pressure set to its maximum value of 5000 the panel shows immediately when the mouse hovers near the edge of the screen.

I  am running a newly installed Ubuntu 20.04, GNOME Shell version 3.36.2 and Dash-to-Panel version 37.

The Dash-to-Panel was installed from the extensions website using Chrome web browser.

This seems to be similar to issue: Panel intellihide require pressure works only for bottom placement #824. But is happening systematically and with the panel on any position.

**Comment by charlesg99** [comment]
Hello, thank you for pointing that out. The problem was that the setting change wasn't immediately applied, it needed a gnome-shell restart. The pressure settings should now be applied right away on the master branch. Thanks!

**Comment by ErikSteiner** [comment]
I noticed with V40, that this setting does nothing on my end. I combined that feature with "Hide bar only when it overlaps with windows." I already restarted my PC. The only thing that I noticed is, that the bar remains hidden if I increase the needed pressure to 200.
