### ISSUE TITLE
Panel shadow

### ISSUE THREAD

**Issue by arngo** [home-sweet-gnome/dash-to-panel#1036]
Hi, with gnome's regular panel I am able to add a shadow using the following CSS rule in my shell theme:

`#panel { box-shadow: 0px 7px 10px -10px rgba(0, 0, 0, 0.7); }`

Which results in this:
![image](https://user-images.githubusercontent.com/27396817/83805261-8e7e8300-a67d-11ea-8ae1-863ee0c67ebb.png)

However, this doesn't apply when this extension is enabled. How can I make this work with dash to panel?

**Comment by charlesg99** [comment]
Hello arngo, yes our container hierarchy differs from the vanilla gnome-shell's panel. Which theme are you using?

**Comment by arngo** [comment]
I am using Materia but the shadow, colour, and height of the panel are my own additions.

**Comment by liferooter** [comment]
Well, it will be good to have panel shadow as setting

**Comment by idkman2021** [comment]
how to fix

**Comment by idkman2021** [comment]
i have same issue how to fix
