### ISSUE TITLE
The difference in "Panel Size" and "Panel Compactness".

### ISSUE THREAD

**Issue by PranavBhattarai** [home-sweet-gnome/dash-to-panel#1038]
Currently, we can decrease panel size using the **Panel Size** option. But the problem is, the decrease in "size" is focused more (actually completely) on a decrease in its height.
 
![Screenshot from 2020-06-06 22-20-30](https://user-images.githubusercontent.com/32763112/83949511-f4b50280-a843-11ea-99e4-ec697318de05.png)

What I am thinking is, "what about the decrease in the distance" aka compactness.
There is certain blank space allocated in Menu Bars items. I think there should be a way to decrease(/increase) this distance.  
![Screenshot from 2020-06-06 22-27-31](https://user-images.githubusercontent.com/32763112/83949673-f03d1980-a844-11ea-91b4-4543bf77a84c.png)
Sadly none of the **Style** option of **Dash to Panel** fulfills that yet. Maybe, there should be an option focused more toward panel compactness. Technically, **Panel Size** option should have fulfilled that but it doesn't work like that. Its completely focused on Panel's height.

It would have been great if we can remove that unnecessary space between the menu bar items.

**Comment by charlesg99** [comment]
Hello PranavBhattarai, use those settings:
 
![image](https://user-images.githubusercontent.com/33044886/84452587-33700180-ac24-11ea-885e-96550818190f.png)

**Comment by PranavBhattarai** [comment]
@charlesg99 Thanks a lot. I wonder how can I not see it when I have been using Dash To Panel for over a year. 
I used to use another extension to have this. This is so cool. Thanks.
