### ISSUE TITLE
Window peeking shows windows from every work space

### ISSUE THREAD

**Issue by RailRanger** [home-sweet-gnome/dash-to-panel#1041]
This is an interesting bug, but what happens is:
1. You have windows on other work spaces
2. You hover over an application, so that the window peeking shows up.
3. You then move your mouse back to the desktop.
4. Now every window from every workspace appears on your current workspace. 
5. You can't click on them, but you click the window titlebars.
6. The only way to make the windows go back is to switch a different work space, then back to your current one.

A video is probably the most helpful for explaining this:
https://imgur.com/S1A3brm
better quality if you need more detail: https://www.3dslice.net/public/misc/videos/dashtopanel.webm 
I am on Ubuntu 20.04, gnome 3.36.2, rx5700, wayland

**Comment by charlesg99** [comment]
Hello RailRanger, please have a look at #1031. Thanks!
