### ISSUE TITLE
Integration with desktop icons and desktop icons ng

### ISSUE THREAD

**Issue by rastersoft** [home-sweet-gnome/dash-to-panel#1046]
Hello:

As you maybe know, there is a problem with desktop icons and dash-to-panel when it is used with the intelligent hide mode, because since desktop icons can't know that the panel occupies part of the screen, it can add in that zone new icons, which would be always hidden under the panel or under a window. The same happens with DING (Desktop Icons NG).

I'm working in a solution for this, but of course I want to ensure that it is a good solution for all (which includes also dash-to-dock at least). For this, I created a patch for gnome shell that adds a new class where any dynamic element can register "margins" that are used by them, allowing other extensions (like desktop icons) to know which parts of the screen are "safe".

I'm starting a discussion for it in gnome shell. The MR is at https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1314 Can you check it and give your opinion, and what you would change?

Thanks.

**Comment by charlesg99** [comment]
Hello, this sounds like a good idea and I think you should have pursued the gnome-shell MR as it would be much better than checking/waiting for specific desktop icons extension (or any other that needs this information, for that matter). Let us know if you continue with it and I'll register our dimensions in the SafeDesktopArea. Thanks!
