### ISSUE TITLE
Tray icons get vertically cut-off on slim panel

### ISSUE THREAD

**Issue by SoumenDass** [home-sweet-gnome/dash-to-panel#1047]
**Describe the bug**
Tray icons get vertically cut-off when panel size is reduced to less than 32.

**Linux distribution and version**
Pop!_OS 20.04 LTS

**GNOME Shell version**
gnome-shell --version

**Dash-to-Panel version**
37

**Where was Dash-to-Panel installed from?**
The GNOME extensions website (https://extensions.gnome.org/extension/1160/dash-to-panel/)

**Screenshots / Video captures**
Screenshot attached.

**Additional Info**
Screenshot and dash to panel settings exported and attached.

![dash_to_panel_vertical_alignment_problem](https://user-images.githubusercontent.com/576199/84792737-cfd04480-b026-11ea-97d1-074596f40041.jpg)

[dash_to_panel_tray_vertical_alignment_problem_settings_export.txt](https://github.com/home-sweet-gnome/dash-to-panel/files/4787408/dash_to_panel_tray_vertical_alignment_problem_settings_export.txt)

**Comment by charlesg99** [comment]
Hello, what theme are you using? Seems to be working fine with the default theme:

![image](https://user-images.githubusercontent.com/33044886/84801755-90c1d500-afcd-11ea-9ba1-2ad56c92d420.png)

**Comment by SoumenDass** [comment]
I'm using Pop's default theme:

![image](https://user-images.githubusercontent.com/576199/84802010-871e8880-b032-11ea-8c18-182d31ebf458.png)

**Comment by SoumenDass** [comment]
Update: I was toggling the extensions one by one to troubleshoot which extension could be affecting this (if any) and accidentally turned-off dash to panel. Once I turned it back on, the error went away. Still not sure what could have caused it though.

**Comment by charlesg99** [comment]
Good, when disabling extensions to find the culprit, remember to restart gnome-shell after disabling each extension.
