### ISSUE TITLE
Crash on blank screen

### ISSUE THREAD

**Issue by Equanimaster** [home-sweet-gnome/dash-to-panel#1050]
Setup:
ubuntu 20.04;
extension installed from latest firefox;
blank screen setup to 5 min;
lock on blank is off;

after reboot, when screen tries to go blank,
shell crashes and relaunches.
and so on, it loops.

**Comment by Equanimaster** [comment]
off/on extention from firefox fixes the problem but for one session only.

**Comment by charlesg99** [comment]
Hello, have a look at #1026, thanks!
