### ISSUE TITLE
Cycle ungrouped applications by keyboard

### ISSUE THREAD

**Issue by varsop** [home-sweet-gnome/dash-to-panel#1053]
Assume I have ungrouped my running applications via dash to panel. Then I would like to cycle running applications by keyboard as in the order shown in the panel. This could be a replacement for alt-tab. I can already use hotkeys to activate apps, but I am not able to cycle apps from keyboard by dash to panel.

Sometimes I find the behavior of switching apps distracting and would prefer an already built-in solution from dash to panel. Because if applications are ungrouped, then I have already the information of running apps displayed in the panel. This could tell me how often I would need to hit alt-tab to reach the desired running app. The goal is to achieve that running applications are treated like open tabs in the panel and one could move e.g. by "Alt + left arrow" to the left in the panel and by "Alt + right arrow" in the right direction of the panel.

**Comment by charlesg99** [comment]
Thanks for pointing that out, it is a bug... Normally, using the hotkeys to show previews should activate the selected window when releasing the Super key. Seems like, for whatever reason and without warning, Clutter decided to change their key constant's name. It should now be fixed on the master branch if you want to check it out. Thanks!

**Comment by varsop** [comment]
Ok, I think I have unintentional highlighted a bug. It is good to know that you have fixed this. 

As far as I understand the behavior of dash to panel I can activate apps by hotkeys + number. But it would be good to cycle through the running ungrouped apps by keyboard. For instance, assume I have activated "show number overlay" and I have focused an app, which has number "3" as indicator. Now I want to switch to the app with indicator number "5". Instead of hitting "hotkey + 5" I would like to cycle to app with indicator number "5" for example by pressing "hotkey + right arrow" and "hotkey + right arrow" once again. It is like I would cycle through the running apps by "hotkey + right arrow" and "hotkey + left arrow". I know I could also have pressed "hotkey + 5", but sometimes I am lazy and just cycle to the running app and I would like to do this by keyboard and the information displayed in the panel. I could also do this by alt + tab, but most realizations of alt + tab are too distracting for me.

**Comment by philippotto** [comment]
Hi varsop,

a few weeks ago, I had the exact same idea (and the motivation behind it) you described above. I implemented that feature for myself and use it on a daily basis. I mapped `Super + Comma/Period` to cycle through all open windows in the panel. While the Super key is pressed down, the highlighted window is previewed similarly to the peek functionality (the opacity of all other windows is reduced) and when the shortcut is released, the opacities are restored back to normal.

I hacked this feature together in a fork of this repository (quite quick&dirty, though). If the maintainer(s) are interested in integrating this feature, I could clean this up and open a PR.

Feel free to check out my fork: https://github.com/philippotto/dash-to-panel
Running `make install` and restarting the shell via `Alt + F2`, `r` and `Enter` should make it live.

Here's a demo GIF where I just cycle between different windows:
![cycle-demo](https://user-images.githubusercontent.com/2486553/86160315-da510a80-bb0b-11ea-86c6-7b574f7ee71f.gif)

**Comment by varsop** [comment]
Hi Philipp,

thank you very much for pointing this out. Your demo looks very promising to me. Unfortunately I do not use d2p any longer and instead use [material shell](https://github.com/material-shell/material-shelll), which comes with the exact desired behavior of switching open windows in a current workspace. In case I want to switch back to d2p I will definitely consider your fork, since I am getting used to and in particular prefer this kind of windows switching.

**Comment by charlesg99** [comment]
Maybe using Ctrl-Alt-Tab in conjunction to using the previews on hotkey would be sufficient?

**Comment by philippotto** [comment]
> Maybe using Ctrl-Alt-Tab in conjunction to using the previews on hotkey would be sufficient?

At least for me, this is not a good alternative, since it requires an additional shortcut at the beginning and another keystroke when exiting the cycling action. For me, it's important to be able to switch fast between the windows which is why I wanted the "keystroke count" to be equal to the alt-tab-functionality.

However, I understand that this feature might not be interesting for everyone. I'm fine with using my fork for now (:
