### ISSUE TITLE
Scale window titles according to gnome tweaks scaling factor

### ISSUE THREAD

**Issue by gkowzan** [home-sweet-gnome/dash-to-panel#1055]
All text elements of gnome shell are scaled according to the font scaling factor set in gnome tweaks. dash-to-panel with ungrouped applications does not respect this setting and the window titles on the panel and in window previews are smaller than the rest of the interface. One can manually change the font size in pixels in dash-to-panel settings, but I don't see any good reason why it shouldn't be scaled automatically.  Is this behaviour a bug or is it by design?

**Comment by charlesg99** [comment]
Hello gkowzan, thank you for pointing that out! This is an oversight, a fix for it was just added to the master branch. The app icons text should now respect the scaling factor, could you confirm that it works for you as well? Thanks!
