### ISSUE TITLE
Option for indicator position of elements other than app indicators

### ISSUE THREAD

**Issue by afraidofmusic** [home-sweet-gnome/dash-to-panel#1056]
Currently, if the panel is placed in the left or the right edges, the indicators of things such as clock, status icons, etc. An option to change the position of their indicators would be useful while using vertical bar.

![Screenshot from 2020-06-25 19-16-34](https://user-images.githubusercontent.com/25895258/85759389-966f9700-b700-11ea-84a6-b06db564d854.png)

**Comment by charlesg99** [comment]
Hello afraidofmusic, unfortunately this needs to be addressed by the theme creators as we can't override every possible styles. Dash to panel already provides css class to indicate the panel orientation and position which can be used by the themes to style the indicators accordingly. As an example, here are the css classes of the panel when set to the left position:

`#panel.dashtopanelLeft.vertical`

So, to be more specific and address the indicator in your screenshot, themes could provide a specific style for the panel-button, like so:

`#panel.dashtopanelLeft.vertical .panel-button:active { /* specific indicator style for left panel */ }`

Thanks!
