### ISSUE TITLE
Distorted icons for running apps

### ISSUE THREAD

**Issue by davidxujiayang** [home-sweet-gnome/dash-to-panel#1057]
**Things to do first**
- Confirm that the problem persists when Dash-to-Panel is the only enabled extension. To do so, disable every other extension, then restart gnome-shell by running the `r` command from the prompt that appears when pressing Alt+F2 on an X.org session, or by logging out/in on a Wayland session.
- Look for Dash-to-Panel errors in your log. To do so, run the `journalctl /usr/bin/gnome-shell -f -o cat &` command and reproduce the problem.
- Search existing opened and closed issues to see if the problem has already been reported.

**Describe the bug**
Icons for running apps get distorted (see attached picture), all icons were close to 1:1 aspect ratio in Ubuntu 18.04.

**Linux distribution and version**
Ubuntu 20.04

**GNOME Shell version**
3.36.2

**Dash-to-Panel version**
37

**Where was Dash-to-Panel installed from?**
Was installed from the GNOME extensions website when the system was running ubuntu 18.04. And retained in the system after upgrading to 20.04.

**Screenshots / Video captures**
![Screenshot from 2020-06-25 13-16-11](https://user-images.githubusercontent.com/24285886/85767500-12101a80-b6e6-11ea-9165-9318c1207708.png)

**Additional Info**

**Comment by charlesg99** [comment]
Please see https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/227, #951, #998, #1051
