### ISSUE TITLE
Toggle Panel Visibility

### ISSUE THREAD

**Issue by AethanFoot** [home-sweet-gnome/dash-to-panel#1060]
**Describe the idea or feature you'd like**
Just a hotkey you can set to toggle the visibility of the panel without requiring intellihide to be activated. I would also be nice if intellihide was expanded to have different rules per application.

**Comment by charlesg99** [comment]
Hello,

> Just a hotkey you can set to toggle the visibility of the panel without requiring intellihide to be activated

Why? We already have that feature in intellihide, which serve that very purpose; hide the panel... Why would we add another method to hide the panel that isn't part of intellihide?

> I would also be nice if intellihide was expanded to have different rules per application

Could you be more specific?

Thanks!

**Comment by AethanFoot** [comment]
Well I found myself wanting to hide the panel but didn't want to have intellihide activated, e.g. if I was coding I'd want as much screen as possible but wouldn't want the panel disappearing with every application. This could also solved with the other feature, which is be able to create a white/black list of applications you'd want the panel to hide with, this then could be expanded to allow users to set different appearance and behavioral settings for certain applications.

**Comment by jderose9** [comment]
Going to close this as a dupe of #815 . If that gets implemented we would to configure default state (visible/hidden).
