### ISSUE TITLE
Dual screen, Taskbar Hovering over full screen apps when other screen is used

### ISSUE THREAD

**Issue by DIDIK3V1** [home-sweet-gnome/dash-to-panel#1061]
I like to have to search with the mouse for the panel to show. To me, it doesn't make any sense not to use the whole screen of your computer. But I have a problem, when I am using an app to my primary screen and having a another app on the other screen, maximimized or in full screen where normally the dock would not appear, it is apearing, masking for exemple the youtube controls or the lasts lines of a text on a website and I despise this, i don't know if this is a bug or a feature but I hate it anyway.

PS: sorry for my english, i'm french i hope i'm clear.

![dash to panel bug](https://user-images.githubusercontent.com/54941168/86394778-62b3e480-bc9f-11ea-9b5f-0d0fdb0db308.png)

**Comment by charlesg99** [comment]
Hello, just disable the first intellihide setting, or set it to hide from all windows.

![image](https://user-images.githubusercontent.com/33044886/86418900-adcdf780-bc9f-11ea-971c-e5830eb974c6.png)

Thanks!
