### ISSUE TITLE
Rounded corners

### ISSUE THREAD

**Issue by enzosanchezewe** [home-sweet-gnome/dash-to-panel#1062]
You could make a rounded corner option like chrome os and also allow to make it roundless when a window approaches 
Also you could add the option to show the "all apps" button at different places instead of attaching it to the favorite/running apps bar

**Comment by charlesg99** [comment]
The Show applications button can now be positioned anywhere in the panel, please install the master branch. Also for the rounded corner let's keep the discussion with the dock request #726. Thanks!

**Comment by enzosanchezewe** [comment]
I don't have the option to move "all apps". I upgraded it and it doesn't allow me to

**Comment by charlesg99** [comment]
> please install the master branch

https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github

**Comment by enzosanchezewe** [comment]
i did that and it thows me error. i have gnome 3.36.2 and ubuntu 20.04

**Comment by enzosanchezewe** [comment]
GLib.FileError: Falló al abrir el archivo «/home/enzo/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/schemas/gschemas.compiled»: open() falló: No existe el archivo o el directorio

**Comment by enzosanchezewe** [comment]
thanks. sorry if i bothered you
