### ISSUE TITLE
Add active state to custom Show Applications icon

### ISSUE THREAD

**Issue by CiscoDeTours** [home-sweet-gnome/dash-to-panel#1063]
![OFFvsON](https://user-images.githubusercontent.com/67841579/86522502-dafbe080-be2c-11ea-84fe-bcb7f5262874.png)

As the title summarizes, it would be great if DTP allowed users to change the app drawer icon binaryally: at rest and in use (Click/Pulse). The image graphs the current situation.

Keep up the good work!

**Comment by charlesg99** [comment]
Hello CiscoDeTours, sorry but I don't understand your screenshot or what you mean. Could you please elaborate? Thanks!

**Comment by CiscoDeTours** [comment]
Hi, Charles. I changed the app drawer icon using the same background color of the bar as you can verify bellow.

![DTPvActual](https://user-images.githubusercontent.com/67841579/86535925-b85fdb00-beb1-11ea-8e68-11c1d560817a.png)

My proposal aims for the customization panel to accept two changes: one for the button in inactive state; another when this button is pressed/clicked:

![DTPvNEW](https://user-images.githubusercontent.com/67841579/86535946-e6ddb600-beb1-11ea-99b3-cc45f08e2ba3.png)

In this way, the button will be fully customizable accepting infinite combinations.

![DTPvBinary](https://user-images.githubusercontent.com/67841579/86536099-f14c7f80-beb2-11ea-9f86-842c1bfd80b5.png)
