### ISSUE TITLE
System icons size follow dashtopanel settings only after hover

### ISSUE THREAD

**Issue by ubluish** [home-sweet-gnome/dash-to-panel#1064]
**Describe the bug**
I'm using font scaling 1.25, also i set dash-to-panel (tray font size and leftbox font size ) to 16px, when lockscreen activated or disable and enable dashtopanel extension, Image 1 appear "the icon size follow the font scaling and ignore the extensions settings" i have to hover on it, it rescales to extension settings 16px,

**Linux distribution and version**
Fedora SilverBlue 32

**GNOME Shell version**
GNOME Shell 3.36.3

**Dash-to-Panel version**
latest git

**Where was Dash-to-Panel installed from?**
 directly from github

**Screenshots / Video captures**
after lockscreen
![1](https://user-images.githubusercontent.com/21042432/86535578-9c742d80-bee1-11ea-8223-d5b9190ec681.png)\
after hover
![2](https://user-images.githubusercontent.com/21042432/86535585-ac8c0d00-bee1-11ea-9233-f802d049dcac.png)

**Comment by charlesg99** [comment]
Hello, I can't reproduce this on gnome-shell 3.36.3 (X.org) using the latest master. There is a long standing gnome-shell bug about this, so please chime in over there so it gets more attention. See:

https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/1708
https://github.com/home-sweet-gnome/dash-to-panel/issues/739

Thanks!
