### ISSUE TITLE
Disabling 'Display panels on all monitors' causes alignment with applications, favourites and taskbar icons (git version)

### ISSUE THREAD

**Issue by craigacgomez** [home-sweet-gnome/dash-to-panel#1066]
**Issue description**
After initial dash to panel setup, turn off the option to 'Display panels on all monitors'.
Restart Gnome session/logout-login/reboot
Applications icon, favourites icons and taskbar icons (running apps) appear misaligned
Each hover over these causes them to "bounce" up and down (screenshots attached)
No way to recover from this unless you use "reset" all gsettings for dash to panel and make sure you don't uncheck the 'Display panels on all monitors' option.

**Linux distribution and version**
Arch Linux

**GNOME Shell version**
GNOME Shell Verion: 3.36.3
XDG Session Type: X11

**Dash-to-Panel version**
version: 37 (dd67b42c22c2580ee291d0c293c21c112fa9fc9c)

**Where was Dash-to-Panel installed from?**
AUR (https://aur.archlinux.org/packages/gnome-shell-extension-dash-to-panel-git)

**Screenshots / Video captures**
![Screenshot from 2020-07-06 11-47-48](https://user-images.githubusercontent.com/1096710/86628971-35767780-bfba-11ea-8da0-6b076c95f9b7.png)
![Screenshot from 2020-07-06 11-48-52](https://user-images.githubusercontent.com/1096710/86628984-3c9d8580-bfba-11ea-80c0-1a7d60ca46d0.png)

**Additional Info (Journal Log)**
[dashtopanel-journal-log-issue1066.log](https://github.com/home-sweet-gnome/dash-to-panel/files/4880813/dashtopanel-journal-log-issue1066.log)

**Comment by charlesg99** [comment]
Hello craigacgomez, thank you for your report, I didn't encountered this issue since I don't use the Activities hot corner :( 

It should now be fixed on the master branch, could you please pull/install again to confirm? Thanks!

**Comment by craigacgomez** [comment]
@charlesg99, thank you for the quick resolution. I can confirm that the latest git version 37 (8fffe0edbb3e48d45413683123c40ce63f25553b) has fixed this issue

**Comment by charlesg99** [comment]
Great!
