### ISSUE TITLE
dash to panel isnt working on gnome 3.38 fedora rawhide aka 33

### ISSUE THREAD

**Issue by adrian-gluu** [home-sweet-gnome/dash-to-panel#1067]
in gnome 3.38 at fedora rawhide aka fedora 33 extensions fails, no clue how to debug it but isn't working not only from extension site also from sources

**Comment by charlesg99** [comment]
Hello, let's keep the discussion about the unsupported/unreleased 3.38 here for now: #1034. Thanks!
