### ISSUE TITLE
Problems with new version of Gnome 3.36.4

### ISSUE THREAD

**Issue by ningacoding** [home-sweet-gnome/dash-to-panel#1070]
**Things to do first** DONE 
- Confirm that the problem persists when Dash-to-Panel is the only enabled extension. To do so, disable every other extension, then restart gnome-shell by running the `r` command from the prompt that appears when pressing Alt+F2 on an X.org session, or by logging out/in on a Wayland session.
- Look for Dash-to-Panel errors in your log. To do so, run the `journalctl /usr/bin/gnome-shell -f -o cat &` command and reproduce the problem.
- Search existing opened and closed issues to see if the problem has already been reported.

**Describe the bug**
When i enable the extension, overview applications crashes and the Desktop Environment stops to work.

**Linux distribution and version**
OS Arch Linux x86_64, Kernel 5.7.7-arch1-1 

**GNOME Shell version**
3.36.4

**Dash-to-Panel version**
37

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
If applicable, add screenshots or a link to a video capture to help explain your problem.
I really don't want to break my DE again.

**Additional Info**

**Comment by charlesg99** [comment]
#1069

**Comment by ningacoding** [comment]
@charlesg99 The extension latest update is not available on the official gnome shell extensions page, plus extension's config section does nothing, does not allow to update via Github.

![Peek 08-07-2020 13-26](https://user-images.githubusercontent.com/17342546/86956644-088fa500-c11f-11ea-98e4-42c43dc36221.gif)

**Comment by ningacoding** [comment]
I've updated vía `yay gnome-shell-extension-dash-to-panel` since package is available via AUR, thanks.
