### ISSUE TITLE
 [Error][Overview]Dash To Panel Breaks the Overview with Gnome 3.36.4

### ISSUE THREAD

**Issue by ycherrak** [home-sweet-gnome/dash-to-panel#1071]
**Things to do first**
- Confirm that the problem persists when Dash-to-Panel is the only enabled extension. To do so, disable every other extension, then restart gnome-shell by running the `r` command from the prompt that appears when pressing Alt+F2 on an X.org session, or by logging out/in on a Wayland session. (Done)
- Look for Dash-to-Panel errors in your log. To do so, run the `journalctl /usr/bin/gnome-shell -f -o cat &` command and reproduce the problem. (Done)
- Search existing opened and closed issues to see if the problem has already been reported. (A small report on the extension but nothing in the Defect list)

**Describe the bug**
Since the upgrade to gnome-shell 3.36.4 the overview is broken when we activate Dash To Panel and works fine when it is not activated.

**Linux distribution and version**
Archlinux (06-08-2020 update)

**GNOME Shell version**
GNOME Shell 3.36.4

**Dash-to-Panel version**
Version: 37

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
Impossible as the screen-cast is blocked by the bug

**Additional Info**
Type of Bug: Systematic

How to reproduce:
1. Update the Gnome-desktop to the version 3.36.4
2. Activate the Dash To Panel Extension
3. Click on mod4 key
Expected Behaviour: The overview is activated
Actual Behaviour: The overview is locked and we cannot go out of it.
                                     The layout around the applications seems broken too and the close button is at the top left of the screen.
                                     The expose mode is not activated and we cannot click on the windows.

Workaround: By restarting the gnome session (Alt+F2 r+Enter on Xorg) the overview is canceled and the screen is not locked anymore.

Logs: 
~ $ › journalctl /usr/bin/gnome-shell -f -o cat &
[1] 15779
~ $ › setup_framebuffers: assertion 'width > 0' failed
setup_framebuffers: assertion 'width > 0' failed
setup_framebuffers: assertion 'width > 0' failed
setup_framebuffers: assertion 'width > 0' failed
setup_framebuffers: assertion 'width > 0' failed
setup_framebuffers: assertion 'width > 0' failed
setup_framebuffers: assertion 'width > 0' failed
setup_framebuffers: assertion 'width > 0' failed
setup_framebuffers: assertion 'width > 0' failed
setup_framebuffers: assertion 'width > 0' failed
JS ERROR: TypeError: this._updateWorkspacesFullGeometry is not a function
_newUpdateWorkspacesViews@/home/lei/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:527:14
show@resource:///org/gnome/shell/ui/workspacesView.js:613:14
show@resource:///org/gnome/shell/ui/viewSelector.js:276:33
_animateVisible@resource:///org/gnome/shell/ui/overview.js:580:27
show@resource:///org/gnome/shell/ui/overview.js:566:14
toggle@resource:///org/gnome/shell/ui/overview.js:689:18
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:220:22

JS ERROR: TypeError: area is null
padArea@resource:///org/gnome/shell/ui/workspace.js:1101:9
_updateWindowPositions@resource:///org/gnome/shell/ui/workspace.js:1334:20
_realRecalculateWindowPositions@resource:///org/gnome/shell/ui/workspace.js:1311:14
_recalculateWindowPositions/this._positionWindowsId<@resource:///org/gnome/shell/ui/workspace.js:1286:18

Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Object .Gjs_ui_workspace_WindowClone (0x55bac9468440), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x55bac56b76b0 ==
#0   55bac6ad66a0 i   resource:///org/gnome/shell/ui/workspace.js:281 (297bce075e20 @ 50)
#1   7ffce291a020 b   self-hosted:1003 (397404f408f8 @ 423)
#2   55bac6ad6618 i   resource:///org/gnome/shell/ui/main.js:233 (1b4bb56d5cb8 @ 12)
== Stack trace for context 0x55bac56b76b0 ==
#0   55bac6ad66a0 i   resource:///org/gnome/shell/ui/workspace.js:294 (297bce075e20 @ 151)
#1   7ffce291a020 b   self-hosted:1003 (397404f408f8 @ 423)
#2   55bac6ad6618 i   resource:///org/gnome/shell/ui/main.js:233 (1b4bb56d5cb8 @ 12)
== Stack trace for context 0x55bac56b76b0 ==
#0   55bac6ad6738 i   resource:///org/gnome/shell/ui/workspace.js:281 (297bce075e20 @ 50)
#1   55bac6ad66a0 i   resource:///org/gnome/shell/ui/workspace.js:353 (297bce07c268 @ 17)
#2   7ffce291a020 b   self-hosted:1003 (397404f408f8 @ 423)
#3   55bac6ad6618 i   resource:///org/gnome/shell/ui/main.js:233 (1b4bb56d5cb8 @ 12)
== Stack trace for context 0x55bac56b76b0 ==
#0   55bac6ad6738 i   resource:///org/gnome/shell/ui/workspace.js:294 (297bce075e20 @ 151)
#1   55bac6ad66a0 i   resource:///org/gnome/shell/ui/workspace.js:353 (297bce07c268 @ 17)
clutter_container_get_children: assertion 'CLUTTER_IS_CONTAINER (container)' failed
#2   7ffce291a020 b   self-hosted:1003 (397404f408f8 @ 423)
#3   55bac6ad6618 i   resource:///org/gnome/shell/ui/main.js:233 (1b4bb56d5cb8 @ 12)
== Stack trace for context 0x55bac56b76b0 ==
#0   55bac6ad66a0 i   resource:///org/gnome/shell/ui/workspace.js:354 (297bce07c268 @ 37)
#1   7ffce291a020 b   self-hosted:1003 (397404f408f8 @ 423)
#2   55bac6ad6618 i   resource:///org/gnome/shell/ui/main.js:233 (1b4bb56d5cb8 @ 12)
Object .Gjs_ui_workspace_WindowClone (0x55bac9468440), has been already deallocated — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Object .Gjs_ui_workspace_WindowClone (0x55bac9468440), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
clutter_container_get_children: assertion 'CLUTTER_IS_CONTAINER (container)' failed
Object .Gjs_ui_workspace_WindowClone (0x55bac9468440), has been already deallocated — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Object .Gjs_ui_workspace_WindowClone (0x55bac9468440), has been already deallocated — impossible to emit any signal on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Object .Gjs_ui_workspace_WindowClone (0x55bac67fcf80), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x55bac56b76b0 ==
#0   55bac6ad66a0 i   resource:///org/gnome/shell/ui/workspace.js:281 (297bce075e20 @ 50)
#1   7ffce291a020 b   self-hosted:1003 (397404f408f8 @ 423)
#2   55bac6ad6618 i   resource:///org/gnome/shell/ui/main.js:233 (1b4bb56d5cb8 @ 12)
== Stack trace for context 0x55bac56b76b0 ==
#0   55bac6ad66a0 i   resource:///org/gnome/shell/ui/workspace.js:294 (297bce075e20 @ 151)
#1   7ffce291a020 b   self-hosted:1003 (397404f408f8 @ 423)
#2   55bac6ad6618 i   resource:///org/gnome/shell/ui/main.js:233 (1b4bb56d5cb8 @ 12)
clutter_container_get_children: assertion 'CLUTTER_IS_CONTAINER (container)' failed
== Stack trace for context 0x55bac56b76b0 ==
#0   55bac6ad6738 i   resource:///org/gnome/shell/ui/workspace.js:281 (297bce075e20 @ 50)
#1   55bac6ad66a0 i   resource:///org/gnome/shell/ui/workspace.js:353 (297bce07c268 @ 17)
#2   7ffce291a020 b   self-hosted:1003 (397404f408f8 @ 423)
#3   55bac6ad6618 i   resource:///org/gnome/shell/ui/main.js:233 (1b4bb56d5cb8 @ 12)
Object .Gjs_ui_workspace_WindowClone (0x55bac67fcf80), has been already deallocated — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x55bac56b76b0 ==
#0   55bac6ad6738 i   resource:///org/gnome/shell/ui/workspace.js:294 (297bce075e20 @ 151)
#1   55bac6ad66a0 i   resource:///org/gnome/shell/ui/workspace.js:353 (297bce07c268 @ 17)
#2   7ffce291a020 b   self-hosted:1003 (397404f408f8 @ 423)
#3   55bac6ad6618 i   resource:///org/gnome/shell/ui/main.js:233 (1b4bb56d5cb8 @ 12)
== Stack trace for context 0x55bac56b76b0 ==
#0   55bac6ad66a0 i   resource:///org/gnome/shell/ui/workspace.js:354 (297bce07c268 @ 37)
Object .Gjs_ui_workspace_WindowClone (0x55bac67fcf80), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
#1   7ffce291a020 b   self-hosted:1003 (397404f408f8 @ 423)
#2   55bac6ad6618 i   resource:///org/gnome/shell/ui/main.js:233 (1b4bb56d5cb8 @ 12)
clutter_container_get_children: assertion 'CLUTTER_IS_CONTAINER (container)' failed
Object .Gjs_ui_workspace_WindowClone (0x55bac67fcf80), has been already deallocated — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Object .Gjs_ui_workspace_WindowClone (0x55bac67fcf80), has been already deallocated — impossible to emit any signal on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Window manager warning: META_CURRENT_TIME used to choose focus window; focus window may not be correct.
Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
Will monitor session 14
Failed to launch ibus-daemon: Failed to execute child process “ibus-daemon” (No such file or directory)
Telepathy is not available, chat integration will be disabled.
JS ERROR: Could not load extension cast-to-tv@rafostar.github.com: Error: Missing metadata.json
createExtensionObject@resource:///org/gnome/shell/ui/extensionSystem.js:280:19
_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:585:34
collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:569:19
_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:599:18
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:630:18
init@resource:///org/gnome/shell/ui/extensionSystem.js:55:14
_initializeUI@resource:///org/gnome/shell/ui/main.js:254:22
start@resource:///org/gnome/shell/ui/main.js:143:5
@<main>:1:47

loading user theme: /home/lei/.themes/ChromeOS-dark/gnome-shell/gnome-shell.css
Usage of object.actor is deprecated for ClipboardIndicator
get@resource:///org/gnome/shell/ui/environment.js:287:29
_init@/home/lei/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/extension.js:88:9
wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
enable@/home/lei/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/extension.js:860:26
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:166:32
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:348:26
_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:590:18
collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:569:19
_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:599:18
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:630:18
init@resource:///org/gnome/shell/ui/extensionSystem.js:55:14
_initializeUI@resource:///org/gnome/shell/ui/main.js:254:22
start@resource:///org/gnome/shell/ui/main.js:143:5
@<main>:1:47

Error loading calendars: Error calling StartServiceByName for org.gnome.Shell.CalendarServer: Process org.gnome.Shell.CalendarServer exited with status 127
Some code tried to set a deprecated GObject property.
0 _patchContainerClass/containerClass.prototype.child_set() ["resource:///org/gnome/shell/ui/environment.js":34:12]
1 _patchContainerClass/containerClass.prototype.add() ["resource:///org/gnome/shell/ui/environment.js":43:17]
2 _buildMenu/<() ["/home/lei/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/extension.js":133:34]
3 readRegistry/</<() ["/home/lei/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/utils.js":127:16]

Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
JS ERROR: Exception in callback for signal: hide: Error: Impossible to remove untracked message
removeMessage@resource:///org/gnome/shell/ui/messageList.js:677:19
_addPlayer/<@resource:///org/gnome/shell/ui/mpris.js:278:18
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
_updateState@resource:///org/gnome/shell/ui/mpris.js:236:22
_onPlayerProxyReady@resource:///org/gnome/shell/ui/mpris.js:186:14
_makeProxyWrapper/</<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:262:21

NOTE: Not using GLX TFP!

NOTE: Not using GLX TFP!

NOTE: Not using GLX TFP!

NOTE: Not using GLX TFP!

NOTE: Not using GLX TFP!

NOTE: Not using GLX TFP!

Window manager warning: Overwriting existing binding of keysym 76 with keysym 76 (keycode 37).
GNOME Shell started at Wed Jul 08 2020 20:09:20 GMT+0200 (Central European Summer Time)
Registering session with GDM
NOTE: Not using GLX TFP!

Ignoring length property that isn't a number at line 1458, col 24
setup_framebuffers: assertion 'width > 0' failed
NOTE: Not using GLX TFP!

The list of Gnome 3.36.4 changes don't reflect anything related to the GLX TFP but I didn't check the commits
https://www.linuxcompatible.org/story/gnome-shell-3364-released/

Hope it helps
Cheers

**Comment by charlesg99** [comment]
Thanks for the report, you forgot to look in the closed issues #1069 #1070

**Comment by ycherrak** [comment]
Oooops my bad I will look at the closed one too next time
Thanks :)
