### ISSUE TITLE
Windows Title And Close Button on Overview Stuck

### ISSUE THREAD

**Issue by ixenatt** [home-sweet-gnome/dash-to-panel#1072]
You can read the log at https://pastebin.com/yjJ4d1nv

**Describe the bug**
Every things work normaly until I access to Overview Windows Title And Close Button Always on top of screen stuck on right or left coner. Only way Can did was Log out

**Linux distribution and version**
Arch

**GNOME Shell version**
3.36.4

**Dash-to-Panel version**
37

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
![Screenshot from 2020-07-09 06-20-17](https://user-images.githubusercontent.com/67907492/86981548-142bac00-c1b1-11ea-84fc-8e236b0fbfd6.png)
![Screenshot from 2020-07-09 06-24-43](https://user-images.githubusercontent.com/67907492/86981553-15f56f80-c1b1-11ea-8a51-10856973299e.png)
![Screenshot from 2020-07-09 06-25-19](https://user-images.githubusercontent.com/67907492/86981558-1857c980-c1b1-11ea-972d-67623ce674f1.png)

**Additional Info**

**Comment by sommd** [comment]
Experiencing this too. Downgrading gnome-shell to 3.36.3 fixes the problem, so it must be a change in 3.36.4.

It also seems to affect the "Show Application" menu, which refuses to close after opening and doesn't display applications properly.

**Comment by charlesg99** [comment]
Please install the master branch for now, or the `gnome-shell-extension-dash-to-panel-git` package from the AUR. Also don't forget to look for similar issues (opened **and closed**) before creating a new one, see #1069 #1070 #1071. Thanks!

**Comment by ixenatt** [comment]
I tried both AUR Before it Error.

ในวันที่ พฤ. 9 ก.ค. 2020 09:10 น. Charles Gagnon <notifications@github.com>
เขียนว่า:

**Comment by k0ste** [comment]
@charlesg99 may be it's time for new release?

**Comment by ixenatt** [comment]
Air version git work but have to log out and log in before enable extension.

ในวันที่ พฤ. 9 ก.ค. 2020 11:12 น. Konstantin Shalygin <
notifications@github.com> เขียนว่า:
