### ISSUE TITLE
Error pressing Windows key

### ISSUE THREAD

**Issue by zapisanchez** [home-sweet-gnome/dash-to-panel#1073]
pressing windows key (for launch new program) keeps freezing in that view and it's impossible to come back.

Attach possible log (i don't know if it is related):

JS ERROR: 
TypeError: this._updateWorkspacesFullGeometry is not a function
_newUpdateWorkspacesViews@/home/user/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:527:14
show@resource:///org/gnome/shell/ui/workspacesView.js:613:14
show@resource:///org/gnome/shell/ui/viewSelector.js:276:33
_animateVisible@resource:///org/gnome/shell/ui/overview.js:580:27
show@resource:///org/gnome/shell/ui/overview.js:566:14
toggle@resource:///org/gnome/shell/ui/overview.js:689:18
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:220:22

**Comment by Austaras** [comment]
same here

**Comment by charlesg99** [comment]
Please install the master branch for now, or the gnome-shell-extension-dash-to-panel-git package from the AUR. Also don't forget to look for similar issues (opened **and closed**) before creating a new one, see #1069 #1070 #1071 #1072. Thanks!
