### ISSUE TITLE
Freeze on GNOME Shell 3.36.4 Overview

### ISSUE THREAD

**Issue by neptu39701** [home-sweet-gnome/dash-to-panel#1074]
**Describe the bug**

When the dash to panel extension is enabled, randomly my screen freezes (whenever I try to reach applications view where all running applications are visible), I have to restart shell to do something, when I disable the dash to panel everything is back to normal 

**here is the log : **
https://paste.ubuntu.com/p/pmnRFqDgWT

**Linux distribution and version**
Archlinux 

**GNOME Shell version**
GNOME Shell 3.36.4

**Dash-to-Panel version**
37

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Comment by charlesg99** [comment]
#1069 #1070 #1071 #1072 #1073

Please install from Github until v38 is released on e.g.o.

**Comment by jderose9** [comment]
v38 has been submitted to extensions.gnome.org... just waiting on approval.

**Comment by charlesg99** [comment]
Aaaaand gnome-shell is about to revert the breaking change, which will break us again on 3.36.5:

https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2971
https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1361

fun

**Comment by jderose9** [comment]
ugh
