### ISSUE TITLE
Gsettings and schema error

### ISSUE THREAD

**Issue by bankerclaw** [home-sweet-gnome/dash-to-panel#1075]
**Describe the bug**
Install from git latest. Getting error below
Error: GSettings key available-monitors not found in schema org.gnome.shell.extensions.dash-to-panel

Leads to no go with command below
gnome-extensions enable "dash-to-panel@jderose9.github.com";
busctl --user call "org.gnome.Shell" "/org/gnome/Shell" "org.gnome.Shell" "Eval" "s" 'Meta.restart("Restarting…")';
bs true ""

**Linux distribution and version**
Fedora Workstation 32
**GNOME Shell version**
3.36.4
**Dash-to-Panel version**
latest from github as of today
**Where was Dash-to-Panel installed from?**
github

**Comment by charlesg99** [comment]
Hello bankerclaw, seems like an installation issue on your end as the gsettings schema wasn't compiled/installed. Please follow the instructions [here](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation) and try the following sequence: install, restart gnome-shell then enable the extension. Thanks!
