### ISSUE TITLE
Huge font

### ISSUE THREAD

**Issue by imirzov** [home-sweet-gnome/dash-to-panel#1076]
Confirm that the problem persists when Dash-to-Panel is the only enabled extension.

Log: 
#2 0x7fffd6a3f020 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fde481b5de0 @ 71)
#3 0x7fffd6a3f0e0 b   self-hosted:916 (0x7fde481f12b8 @ 367)
#4 0x7fffd6a3f1d0 b   resource:///org/gnome/gjs/modules/signals.js:128 (0x7fde481d2230 @ 386)
#5 0x55e0c47ed958 i   /usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:190 (0x7fde280c6de0 @ 22)
#6 0x7fffd6a3fe20 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fde481b5de0 @ 71)
#7 0x55e0c47ed8b0 i   /usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/statusNotifierWatcher.js:176 (0x7fde280c6120 @ 26)
#8 0x7fffd6a40a00 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fde481b5de0 @ 71)
#9 0x55e0c47ed810 i   /usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/statusNotifierWatcher.js:170 (0x7fde280c6098 @ 68)
#10 0x7fffd6a415f0 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fde481b5de0 @ 71)
#11 0x7fffd6a416c0 b   self-hosted:918 (0x7fde481f12b8 @ 394)

**Describe the bug**
Huge font. See attachment. "Fine-Tune -> LeftBox" Font Size doesn't work.

Ubuntu 18.04
GNOME Shell 3.28.4
Dash-to-Panel version 38
Installed from the GNOME extensions website
![huge_font](https://user-images.githubusercontent.com/4652710/87218887-44ad4a80-c357-11ea-8e1c-5bc758c79369.png)

**Comment by charlesg99** [comment]
Hello, the taskbar isnt located in the "LeftBox" and the only novelty with v38 is that the window labels are now affected by the system font scaling factor. So the font size is controlled by the combination of the following values:

![image](https://user-images.githubusercontent.com/33044886/87223048-99e16000-c347-11ea-9e87-105a35eed3a1.png)

I tested on Ubuntu 18.04 and the font is sized correctly for me, so try playing with those values. Thanks!

**Comment by imirzov** [comment]
Thank you so much! Fixed!
