### ISSUE TITLE
Autoupdate doesnt work on 20.04 

### ISSUE THREAD

**Issue by seredniy** [home-sweet-gnome/dash-to-panel#1077]
**Describe the bug**
After last update  of extention  it stop workinng. Couple of similar comments from users of ubuntu 20.04 have the same issue too.

problim is in autoupdate. Because after reboot system all is ok.

**Linux distribution and version**
Ubuntu 20.04, Fedora

**GNOME Shell version**
Shell 3.36.3

**Dash-to-Panel version**
38

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots*

![image](https://user-images.githubusercontent.com/11270429/87223130-17769180-c383-11ea-9e8f-73d9045f89b7.png)

**Comment by seredniy** [comment]
Sorry! After reboot all is ok. But auto update is broken, issue open...

**Comment by charlesg99** [comment]
Hello, yeah gnome-shell itself is responsible for the auto update mechanism and it is always recommended to logout/login after an upgrade. Thanks!
