### ISSUE TITLE
Problem with window preview on hover

### ISSUE THREAD

**Issue by danielhuang** [home-sweet-gnome/dash-to-panel#1079]
**Describe the bug**
Sometimes, when an application has 2 windows, the hover preview only displays one of the two.

**Steps to reproduce:**
Start an application with one window, and another with 2 windows.

Place the applications adjacently on the taskbar:
![image](https://user-images.githubusercontent.com/24739403/87235020-3ede5600-c3a5-11ea-8b10-6bee5ba69fa2.png)

Hover over the application on the right, then quickly move the mouse to the left and back.

The window preview only shows one of the 2 windows of the second application.

**Linux distribution and version**
Arch

**GNOME Shell version**
3.36.4

**Dash-to-Panel version**
38

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Comment by charlesg99** [comment]
Hello danielhuang, thank you very much for pointing that out, I could reproduce the issue! A fix for it has been added to the master branch, could you please install it to confirm that the window previews now behave as they should? Thanks!

**Comment by danielhuang** [comment]
I installed the latest version and the issue has been fixed. Thanks for the support.
