### ISSUE TITLE
Show Applications button doesn't open applications overview with touch

### ISSUE THREAD

**Issue by smithfred** [home-sweet-gnome/dash-to-panel#108]
Using a tablet with pen and touch, the Show Applications button doesn't open the applications overview using touch. Mouse/pen activation work fine, and exiting the overview works when using the button with all three input methods. All other panel items work fine (launchers, clock, system menu, keyboard layout switcher etc.)

**Comment by jderose9** [comment]
I don't have a touchscreen device running Gnome to reproduce this with, so hopefully someone else can.

**Comment by AlexGluck** [comment]
Asus transformer book tl300lj, fedora 26, freeze not detected. Gnome tweak and gnome settings laged, but othing else happen.

**Comment by smithfred** [comment]
It's actually an X11-only problem - On GNOME Wayland it works fine.

That said, GNOME Wayland is still not usable for touch screens (at least on a Surface Pro 3) - windows with server-side decorations can't be dragged via the title bar. So X11 is still necessary when using a touch screen unfortunately.

On X11 tapping the "Show Applications" icon gives it a "moused-over" highlight, and the tooltip appears. I'm not seeing any freezing however.

**Comment by AlexGluck** [comment]
Forgeted say, i disable fully wayland. For me wayland causes many other problems. Did you mean, you have problem with wayland? If i right, you need create bug record in wayland bugtracker.

**Comment by smithfred** [comment]
No, the problem is with Dash to Panel on X11.

**Comment by AlexGluck** [comment]
@smithfred how i say freeze not detected.
