### ISSUE TITLE
Date Menu item is cut off in vertical panel?

### ISSUE THREAD

**Issue by bmccorm2** [home-sweet-gnome/dash-to-panel#1080]
Hi all - firstly i love the extension so thanks so much.  I had a question about my date menu item in a vertical panel.  Thanks again!

**Describe the bug**
On my vertical panel i have the "date menu" item on there.  It used to display the date/time but now it is just cut off. (screenshot below)

**Linux distribution and version**
Arch

**GNOME Shell version**
3.36.4

**Dash-to-Panel version**
9999

**Where was Dash-to-Panel installed from?**
Arch AUR

**Screenshots / Video captures**
![image](https://user-images.githubusercontent.com/11781610/87235622-31bc6980-c39b-11ea-8249-1033f5142849.png)

**Comment by charlesg99** [comment]
Thank you for reporting this bmccorm2, I could reproduce the issue. This was indeed [broken by 3.36.4](https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1327) and it should now be fixed on our master branch. Could you please install it and confirm that the clock is now displayed correctly for you as well? Thanks!

**Comment by bmccorm2** [comment]
Thanks that was so fast!  It works great now :)

**Comment by branchus** [comment]
I had the same issue and was going to report, and then find it has been fixed in the master branch

Thanks

**Comment by charlesg99** [comment]
Great, thanks for the feedback!

**Comment by bmccorm2** [comment]
Just curious is there any timeline to push this out to repos? (specifically arch aur?)
