### ISSUE TITLE
End of Plano-theme compatibility in Dash-to-Panel starting V38. We need a native option which can show Date/SystemMenu/Time in dark panel leaving rest of the area transparent.

### ISSUE THREAD

**Issue by PranavBhattarai** [home-sweet-gnome/dash-to-panel#1082]
With Plano-theme and Dash-To-Panel, I was able to achieve a working transparent taskbar which is not disturbing whether if you are using an application that is white (or any color).

After the new Dash-to-Panel, things seem impossible [as mentioned by Plano-theme maintainer](https://github.com/lassekongo83/plano-theme/issues/53#issuecomment-657188039). 

Now, without Plano-theme, I can't utilize maximum screen. 
As u can see the problem here, its not much of "Dynamic transparent" if it hide important details like Date/Time/SystemMenu.
![Screenshot from 2020-07-12 20-21-39](https://user-images.githubusercontent.com/32763112/87249199-54bf4a00-c47d-11ea-9164-77ec3ea05ce6.png)

Unless u are viewing something "black", then only rest of the area visible.
![Screenshot from 2020-07-12 20-21-17](https://user-images.githubusercontent.com/32763112/87249201-56890d80-c47d-11ea-8caa-23d94bd9573a.png)

Plano used to solve this issue, by making those areas black always. By doing this, we can see vital information without having to lose a centimeter of screen space.

**Comment by charlesg99** [comment]
Hello Pranav, at this point it is something that can easily be customized locally, but would be quite inconvenient to generalize in our settings. The goal of v38 is to allow independent placements of the panel elements, so to keep it consistent we would need to allow changing the background color of every elements and make the dynamic opacity work with this. Since this is a pretty niche request, I feel like your best bet is to set it to your liking by modifying your theme's css. 

Here is an example :
```
.dashtopanelMainPanel Gjs_ui_panel_AggregateMenu,
.dashtopanelMainPanel Gjs_ui_dateMenu_DateMenuButton {
	background-color: darkblue;
}
```

Which gives:

![image](https://user-images.githubusercontent.com/33044886/87250757-39c8e780-c435-11ea-8624-ad23ca93e330.png)

Gonna close this, but let us know if you need help to get the result you want. Thanks!

**Comment by PranavBhattarai** [comment]
> set it to your liking by modifying your theme's CSS.

@charlesg99 
(noob here) Where I can find my theme's CSS? 
I tried for searching "theme.css" file in Plano-theme, I can't seems to find it.

**Comment by charlesg99** [comment]
Not sure how you installed the plano theme, but on my system the css rules are in this file `~/.themes/plano-theme/gnome-shell/gnome-shell.css`. They might also be in `/usr/share/themes/Plano/gnome-shell/gnome-shell.css`

Just make sure to keep a backup of your custom css rules somewhere else as updating the theme will overwrite your changes. Thanks!

**Comment by PranavBhattarai** [comment]
I don't think there is any gnome-shell.css in `~/.themes/plano-theme/gnome-shell/gnome-shell.css` directory. 
But I do find that file in `~/.themes/plano-theme/gnome-shell/src` and `/usr/share/themes/Plano/gnome-shell/gnome-shell.css` directory as you can see it [here](https://imgur.com/HRZOfEb). 
I don't think there is any line which says:
```
.dashtopanelMainPanel Gjs_ui_panel_AggregateMenu,
.dashtopanelMainPanel Gjs_ui_dateMenu_DateMenuButton {
	background-color: darkblue;
}
```
Does that mean are u suggesting add this piece of code inside **gnome-shell.css** file?
But judging by coding similarities inside that file, I see almost all line starting with the word **#panel** like [this](https://imgur.com/1OxA8py):
`#panel.dashtopanelMainPanel.dashtopanelTop .dash-item-container .show-apps:overview { background-image: url("d2p-activities-active.svg"); background-color: rgba(0, 0, 0, 0.8); }
`
My question is, does the code you gave me works/correct?! (sorry if I'm annoying too much. #noob)
Another question, if I edit one gnome-shell.css file from `~./themes/plano-themes/gnome-shell/src` then do I can to make the same changes in `/usr/share/themes/Plano/gnome-shell/gnome-shell.css`

**Comment by charlesg99** [comment]
Yes you need to add those lines in the `/usr/share/themes/Plano/gnome-shell/gnome-shell.css` file, then restart gnome-shell for the changes to take effect (or reload the theme by changing it in Tweaks).

`~./themes/plano-themes/gnome-shell/src` is the "source" code and isn't used by gnome-shell, but it is copied/overwrite to `/usr/share/themes/Plano/gnome-shell/gnome-shell.css` when you build the project (meson/ninja).

**Comment by PranavBhattarai** [comment]
Thanks a lot, it solved some part of the problem. But there are still some issues, like this:
Problem 1:
![Problem 1](https://user-images.githubusercontent.com/32763112/87421339-7e4fb100-c5f6-11ea-81e3-6d7cfe534673.png)

Problem is, I cannot see extensions icons like **Caffeine** anymore if I am in white zone/area. How can I make that area black too?!

Problem 2:
![Screenshot from 2020-07-14 17-23-47](https://user-images.githubusercontent.com/32763112/87421932-76dcd780-c5f7-11ea-8a83-c4e9f08f40e6.png)
If I hover my mouse above them then it will become white, and if I am using a software/app with a white background then it makes "white on white" effect which will things invisible. 

The hover color is "white". Where can I find this hover color?!
