### ISSUE TITLE
Gnome Looking Glass is broken

### ISSUE THREAD

**Issue by nebrelbug** [home-sweet-gnome/dash-to-panel#1084]
**Things to do first**
- [x] Confirm that the problem persists when Dash-to-Panel is the only enabled extension. To do so, disable every other extension, then restart gnome-shell by running the `r` command from the prompt that appears when pressing Alt+F2 on an X.org session, or by logging out/in on a Wayland session.
- [x] Look for Dash-to-Panel errors in your log. To do so, run the `journalctl /usr/bin/gnome-shell -f -o cat &` command and reproduce the problem.
- [x] Search existing opened and closed issues to see if the problem has already been reported.

**Describe the bug**
Press ALT+F2, enter the "lg" command, then press Enter. The looking glass panel is pushed way past the top of the monitor -- only the bottom half-inch or so is visible. 

**Linux distribution and version**
Ubuntu (Pop!_OS) 20.04

**GNOME Shell version**
GNOME Shell 3.36.3

**Dash-to-Panel version**
38

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
If applicable, add screenshots or a link to a video capture to help explain your problem.

**Additional Info**

**Comment by charlesg99** [comment]
Hello nebrelbug, thank you very much for the report, I could reproduce the issue with the panel at the top position. A fix for it was added to the master branch, could you install it and confirm that the looking glass is correctly positioned for you as well? Thanks!

**Comment by nebrelbug** [comment]
@charlesg99 sure! What's the best way to temporarily install from GitHub, but keep as my main install the extension from `extensions.gnome.org`?

Also, random question: is there any way to disable the rounded corners on the top panel? Looks like those returned in the  most recent release.

**Comment by charlesg99** [comment]
You can safely [install from Github](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github), this won't affect the update mechanism from e.g.o. which will correctly update when v39 is out. Yes there recently was an issue about the missing rounded corner (#991), so we added them back. I think your best bet to remove them is to use another theme, or use this extension maybe: https://extensions.gnome.org/extension/448/remove-rounded-corners/

 Thanks!

**Comment by nebrelbug** [comment]
@charlesg99 I can confirm that the looking glass issue is fixed from GitHub!

I'm running into some more problems with rounded corners:

- The extension you linked works on install but rounded corners return after visiting the GNOME dash
- Rounded corners don't work correctly with panel transparency -- the rest of the panel is transparent and the corners are a light gray
- Dash-to-panel uses a different corner radius than the default GNOME top panel

Should I open a new issue? I'm thinking it would be really nice to have an option to disable rounded corners altogether.

**Comment by charlesg99** [comment]
Glad to hear about the looking glass. As for the corners I'm not sure about the extension I linked, I'm not using it as I use the Arc theme and it removes the corners.

As for the other issues you mentioned, I'm not sure what you mean, is this not what you're seeing?

![image](https://user-images.githubusercontent.com/33044886/87420131-b75e3600-c5a2-11ea-9d0e-026b5b553f51.png)

The corner radius is dictated by the theme but it should be the same as the default panel:

![image](https://user-images.githubusercontent.com/33044886/87420220-e5dc1100-c5a2-11ea-9f1f-3b7e40f059f3.png)

The only thing I can think of about the opacity is if you have a maximized window, this way the corners of the windows would blend with the panel corners and make it look different. This doesn't happen on the default panel as it is completely opaque. e.g.

Gonna close this as the looking glass issue is resolved, feel free to open a new one about the corners. Thanks!
