### ISSUE TITLE
"TypeError : parent is null" on lg with the last commit

### ISSUE THREAD

**Issue by Amathadius** [home-sweet-gnome/dash-to-panel#1086]
With the last commit, extension doesn't work. Lg shows me the "TypeError : parent is null" 

**GNOME Shell version**
GNOME Shell 3.36.4

**Dash-to-Panel version**
38.r8.g9b8d402-1

**Where was Dash-to-Panel installed from?**
git with yay

**Comment by charlesg99** [comment]
Hello Mathieu, thank you for your report! That error would means that one of the following isn't present on the original gnome-shell panel: Activities button, System menu or Date menu. Do you see how that can happen on your system? I'll fix it but I'd like to reproduce it first if possible. Thanks!

**Comment by Amathadius** [comment]
I've gone back a few commits and it's working fine. For the missing element, could it be related to the arc-menu that removes the Activities button?

**Comment by Amathadius** [comment]
It actually looks like it's related to arc-menu because if I activate dash-to-dock before arc-menu and then activate arc-menu afterwards, it's fine.

But I'd just like to mention that dash-to-dock normally works by going back a few versions.

**Comment by charlesg99** [comment]
Yes you are correct, this happens when Arc-Menu is loaded before dash to panel. I could reproduce the issue and it should now be fixed on the latest commit. Thanks!
