### ISSUE TITLE
dash-to-panel fails to load because of metadata.json file permissions

### ISSUE THREAD

**Issue by zamzom** [home-sweet-gnome/dash-to-panel#1088]
**Things to do first**
- Confirm that the problem persists when Dash-to-Panel is the only enabled extension. 
Yes
- Look for Dash-to-Panel errors in your log. To do so, run the `journalctl /usr/bin/gnome-shell -f -o cat &` command and reproduce the problem.
Yes

- Search existing opened and closed issues to see if the problem has already been reported.
No

**Describe the bug**
After unzipping the dash-to-panel archive, I was unable to activate the extension. Starting the shell with journalctl indicated an error in reading metadata.json file. When I enabled file read permission for everyone, the extension was loaded successfully.
```
[root@localhost extensions]# journalctl /usr/bin/gnome-shell -f
-- Logs begin at Thu 2020-07-16 09:36:25 PDT. --
Jul 16 14:37:03 localhost gnome-shell[3871]: JS ERROR: Could not load extension dash-to-panel@jderose9.github.com: Error: Failed to load metadata.json: Gio.IOErrorEnum: Error opening file /usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/metadata.json: Permission denied

root@localhost dash-to-panel@jderose9.github.com]# ll ../dash-to-panel@jderose9.github.com/
total 964
-rw-rw-r--  1 root root  76236 Jul  9 19:57 appIcons.js
-rw-rw-r--  1 root root   3342 Jul  9 19:57 convenience.js
-rw-rw-r--  1 root root  17993 Jul  9 19:57 COPYING
-rw-rw-r--  1 root root   5144 Jul  9 19:57 extension.js
drwxrwxr-x  2 root root    106 Jul  9 19:57 img
-rw-rw-r--  1 root root  14550 Jul  9 19:57 intellihide.js
drwxrwxr-x 18 root root    175 Jul  9 19:57 locale
-rw-------  1 root root   1027 Jul 10 11:42 metadata.json    <<< GROUP AND OTHER PERMISSIONS DISABLED
-rw-rw-r--  1 root root  14028 Jul  9 19:57 overview.js
-rw-rw-r--  1 root root  59789 Jul  9 19:57 panel.js
-rwxrwxr-x  1 root root  32505 Jul  9 19:57 panelManager.js
-rw-rw-r--  1 root root   2434 Jul  9 19:57 panelPositions.js
-rw-rw-r--  1 root root  13039 Jul  9 19:57 panelStyle.js
-rw-rw-r--  1 root root 110586 Jul  9 19:57 prefs.js
-rw-rw-r--  1 root root  18531 Jul  9 19:57 progress.js
-rw-rw-r--  1 root root   8416 Jul  9 19:57 proximity.js
-rw-rw-r--  1 root root   9364 Jul  9 19:57 README.md
drwxrwxr-x  2 root root     91 Jul  9 19:57 schemas
-rw-rw-r--  1 root root 416959 Jul  9 19:57 Settings.ui
-rw-rw-r--  1 root root   3699 Jul  9 19:57 stylesheet.css
-rw-rw-r--  1 root root  51235 Jul  9 19:57 taskbar.js
-rw-rw-r--  1 root root   9975 Jul  9 19:57 transparency.js
-rw-rw-r--  1 root root   1662 Jul  9 19:57 update.js
-rw-rw-r--  1 root root  29105 Jul  9 19:57 utils.js
-rw-rw-r--  1 root root  41441 Jul  9 19:57 windowPreview.js
```

**Linux distribution and version**
CentOS 7.8

**GNOME Shell version**
3.28.2

**Dash-to-Panel version**
38

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
If applicable, add screenshots or a link to a video capture to help explain your problem.

**Additional Info**

**Comment by charlesg99** [comment]
Hello zamzom, thank you for pointing this out. You are correct, seems like the metadata.json file was added with the wrong permissions to the zip file. The install from e.g.o. is working, but manually downloading/unzipping yields the error you mentioned. e.g. `mkdir dtp_temp && cd dtp_temp && curl -L https://extensions.gnome.org/download-extension/dash-to-panel%40jderose9.github.com.shell-extension.zip\?version_tag\=17893 -o dtp_38.zip && unzip dtp_38.zip && ls -la`

@jderose9 This doesn't feel critical to me, but is it possible to replace the zip on e.g.o. (once reviewed) or do we need to release a new version?

**Comment by zamzom** [comment]
Thanks @charlesg99 for looking into this issue. Unfortunately my e.g.o is not working properly with Firefox on CentOS 7.8, so my only option was to manually install the extension. Looking forward for the fix in the upcoming release.

**Comment by jderose9** [comment]
@charlesg99 I think this one will have to get filed with GNOME. The metadata.json gets replaced by a generated version when I upload the extension bundle.

https://gitlab.gnome.org/Infrastructure/extensions-web/-/blob/master/sweettooth/extensions/models.py#L365-386

**Comment by charlesg99** [comment]
Ha yes, makes sense. Should've thought of that :sweat_smile: 

Let's close this then. @zamzom please feel free to open a new issue [over there](https://gitlab.gnome.org/Infrastructure/extensions-web/-/issues). Thanks!
