### ISSUE TITLE
Version 38 places Arc Menu at the right side of Show Applications

### ISSUE THREAD

**Issue by kbn00** [home-sweet-gnome/dash-to-panel#1089]
It used to place Arc Menu at the left side but after upgrading to the version 38, it places Arc Menu at the right side of Show Applications.

Ubuntu 20.04 LTS

GNOME Shell 3.36.3

Dash to Panel version 38

Arc Menu version 47

Both extensions installed from extensions.gnome.org

**Comment by charlesg99** [comment]
![Peek 2020-07-17 07-27](https://user-images.githubusercontent.com/33044886/87781658-16b88200-c7ff-11ea-8152-ecd231515ddb.gif)
