### ISSUE TITLE
"Show Desktop" button is indistinguishable from panel when using light themes on the panel.

### ISSUE THREAD

**Issue by M4D7174N** [home-sweet-gnome/dash-to-panel#1090]
It is not visible with Light theme.
![image](https://user-images.githubusercontent.com/62345208/87852679-ab1b0580-c921-11ea-985d-5e16409de694.png)

Dark theme, working good.
![image](https://user-images.githubusercontent.com/62345208/87852682-b706c780-c921-11ea-9c17-dfb7ab2dd09c.png)

**Comment by M4D7174N** [comment]
Actually in the screenshot, it has a different shade, but it will be helpful if it is having a userdefined separator width (starting from 0)

**Comment by hlechner** [comment]
the PR #1108 was merged, could you give it a try @M4D7174N ?

**Comment by M4D7174N** [comment]
> the PR #1108 was merged, could you give it a try @M4D7174N ?

Sweet, It is just like the new windows 10, Also Bonus, Darken on hover.

Thank you very much.
