### ISSUE TITLE
V38 prevents other extensions to place windows buttons on the right of the system menu

### ISSUE THREAD

**Issue by arthur25000** [home-sweet-gnome/dash-to-panel#1091]
**Describe the bug**
Extensions for displaying title bar in the bash panel cannot place windows buttons on the right of the system menu anymore (confirmed with "Not title bar" and "Unite" extensions).

**Linux distribution and version**
Ubuntu 20.04

**GNOME Shell version**
GNOME Shell 3.36.3

**Dash-to-Panel version**
V38

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**

With V37 :
![Capture d’écran de 2020-07-17 13-45-08](https://user-images.githubusercontent.com/63848959/87909500-a319ad80-ca68-11ea-9021-2f2dd09d0dc1.png)

With V38:
![Capture d’écran de 2020-07-17 09-40-02](https://user-images.githubusercontent.com/63848959/87909294-49b17e80-ca68-11ea-8346-adb45e27ff6a.png)

**Comment by charlesg99** [comment]
![Peek 2020-07-20 07-06](https://user-images.githubusercontent.com/33044886/87931373-b40df300-ca57-11ea-9017-1e560f20e221.gif)

**Comment by thomas-wach** [comment]
Moving "Right box" to last position is perhaps a (very) suboptimal workaround.
But it does not resolve the misbehaviour from my point of view.
I do not want to change the sequence of boxes, because I like them the way they are.

**Comment by charlesg99** [comment]
There is no misbehavior from my point of view. The right box is now empty so the Unite's window buttons truly are the "last" element in it. The right box normally contains the date and system menu, but we removed them to allow users to place/order them in any way on the panel. How is that "suboptimal"?

**Comment by thomas-wach** [comment]
Because "Right box" is not empty at all. Right box contains keyboard layout, system-monitor and tray icons ...
Moving that all to right lead to system menu and date placed far far away from original position.
If right box would be empty, you would be right, but it isn't, sadly
<a href="https://ibb.co/L8wmKWp"><img src="https://i.ibb.co/MsTrd4N/Bildschirmfoto-von-2020-08-02-14-09-37.png" alt="Bildschirmfoto-von-2020-08-02-14-09-37" border="0"></a>

**Comment by simurgh9** [comment]
Why was this closed? The issue still seems to exist.
