### ISSUE TITLE
Regression: No Time in vertical view

### ISSUE THREAD

**Issue by Henry78** [home-sweet-gnome/dash-to-panel#1092]
**Things to do first**
No other extensions, nothing in the logs

**Describe the bug**
Prior to Gnome 3.36.4 the clock in vertical view showed date and (below) the time. No (and after #1080 fixed the cut off), I only see the date, but the time is missing.

**Linux distribution and version**
Arch

**GNOME Shell version**
GNOME Shell 3.36.4

**Dash-to-Panel version**
version: 38

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
![Screenshot from 2020-07-20 12-51-33](https://user-images.githubusercontent.com/1314735/87930265-0a932580-ca88-11ea-8cc2-ab8de0b35d90.png)

**Additional Info**

**Comment by charlesg99** [comment]
Hello Henry78, seems to work fine here:

![image](https://user-images.githubusercontent.com/33044886/87932270-3cd95e80-ca59-11ea-872d-06a77b125dcc.png)

Do you see the time if you make the panel wider? Are you sure you applied the fix from #1080? Thanks!

**Comment by 4javier** [comment]
After last Gnome upgrade on Arch there are strange behaviours even on horizontal placement, not only for date menu but for every element. It seems almost that the panel gets
![Schermata da 2020-07-21 13-10-27](https://user-images.githubusercontent.com/459381/88048556-d1c08280-cb53-11ea-81e8-f226489f9ca4.png)
 wrong display size.
![Schermata da 2020-07-21 13-06-02](https://user-images.githubusercontent.com/459381/88048240-43e49780-cb53-11ea-956e-e561579f4d11.png)

**Comment by Henry78** [comment]
Jep, the clock is shown if I increase panel size, so ellipsizeing doesn't work. I checked again and the patch https://github.com/home-sweet-gnome/dash-to-panel/commit/2a465514141c86d8de4a78e8c488c806e677a21f is applied. But I'll uninstall and reinstall the extension later this day in case I ~f**~ mixed anything up.

**Comment by charlesg99** [comment]
@4javier Thanks for the screenshot, I could reproduce the issue and it should now be fixed on the latest master.

@Henry78 Thanks let us know. If you still see the issue after re installation, please provide your system locale.

**Comment by Henry78** [comment]
Reinstalled from GIT, now works. Seems I failed in patching. Sorry for the noise.

**Comment by 4javier** [comment]
@charlesg99 
Unfortunately the fix seems to not stand a sleep/resume cycle. After that, date is always positioned to the right of right-box, and flickers on every re-rendering of any dash element.
Terminate and restart the session fix the problem until next sleep.

**Comment by charlesg99** [comment]
@4javier Try disabling your other extensions, then restart gnome-shell. Does the problem still happens then? I can't reproduce it so it must be one of your other extension erroring out on disable. Thanks!

**Comment by 4javier** [comment]
@charlesg99 
You were right.
Culprit seems to be https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet.
I'll open an issue on its bugtracker and link this ticket.
Thanks for your time and your willingness.
