### ISSUE TITLE
Automagic import of settings from file

### ISSUE THREAD

**Issue by leier69** [home-sweet-gnome/dash-to-panel#1093]
Not exactly a problem, but I was wondering if it is possible to import a style from a file in a bash script. I would really like to have a way to import my settings in my script as appose to doing it manually when the install is done. 

Is this possible?

**Comment by charlesg99** [comment]
Hello, yes this is already possible, have a look in the settings:

![image](https://user-images.githubusercontent.com/33044886/88283564-9e980380-ccb9-11ea-989d-2165e68d19b6.png)

Thanks!

**Comment by charlesg99** [comment]
From a bash script: `dconf load /org/gnome/shell/extensions/dash-to-panel/ < my_exported_settings_file`

**Comment by leier69** [comment]
Ohhh thats fucking wonderfull! thank you for quick answer :)

I wish you the best of days @charlesg99
