### ISSUE TITLE
left box and system tray position 

### ISSUE THREAD

**Issue by omune-hm** [home-sweet-gnome/dash-to-panel#1095]
if you have an ultra wide, super-ultra wide or just a gigantic display having the panel float between the edges(like the dock with panel mode disabled),Or an option to move the left box and the system tray away from the ends of the panel and closer to the center, would save one a lot of eye strain and neck strain.
what do you think

**Comment by charlesg99** [comment]
Taskbar centered and both menus stacked to its left:

![image](https://user-images.githubusercontent.com/33044886/88408686-e72aec00-cda1-11ea-81fd-20ec2274371c.png)

Taskbar and both menus centered:

![image](https://user-images.githubusercontent.com/33044886/88408785-0590e780-cda2-11ea-84a4-7167d63b52f1.png)
