### ISSUE TITLE
After Update, Extension Non-Functional

### ISSUE THREAD

**Issue by Draco18s** [home-sweet-gnome/dash-to-panel#1096]
**Describe the bug**
Updated from an older version (which, I am not sure, but about 4-5 months ago was the last time I updated extensions).

**Linux distribution and version**
NAME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.10"
VERSION_ID="19.10"

**GNOME Shell version**
3.34.3

**Dash-to-Panel version**
38

**Where was Dash-to-Panel installed from?**
https://extensions.gnome.org/

**Screenshots / Video captures**
If applicable, add screenshots or a link to a video capture to help explain your problem.
![image](https://user-images.githubusercontent.com/1750680/88448200-b5953d80-ce00-11ea-9116-ec1e49677a60.png)

(1) Panel screen position dialog does not reflect current dock location (setting says bottom, dock is at top).
(2) Radio buttons cannot be used at all
(3) Every other setting I attempted to fiddle with also did nothing I could observe

**Comment by charlesg99** [comment]
Please see #1078

![Peek 2020-07-25 07-49](https://user-images.githubusercontent.com/33044886/88456386-6294a800-ce4b-11ea-9d65-209fa1d31227.gif)
