### ISSUE TITLE
Error this._overview is undefined 

### ISSUE THREAD

**Issue by Ferdous123** [home-sweet-gnome/dash-to-panel#1097]
**Describe the bug**
With Alt +F2 then input lg ，show error: this._overview is undefined
Tried when Dash-to-Panel was the only enabled extension with gnome shell restart after every step.

**Linux distribution and version**
Ubuntu 20.04

**GNOME Shell version**
3.36.3

**Dash-to-Panel version**
9999

**Where was Dash-to-Panel installed from?**
The GNOME extensions website; distribution's package manager(Tried both after uninstalling previous one from terminal)

**Screenshots / Video captures**
![ff](https://user-images.githubusercontent.com/38389751/88450509-515e9200-ce71-11ea-9dd0-920070800c84.png)
![uh](https://user-images.githubusercontent.com/38389751/88450512-56234600-ce71-11ea-906e-95a4f18b52a2.png)

**Comment by charlesg99** [comment]
Hello, working fine for me on Ubuntu 20.04, please see #1078. Also, not sure how you installed, but 'version 9999' have me believe that the installation was done incorrectly. Thanks!

**Comment by Ferdous123** [comment]
I reinstalled Ubuntu & installed this at first. It worked flawlessly but the version is still 9999. And openweather doesn't work with it. 

The issue was, my left panel wasn't coming in my previous ubunu(corrupted or some internal issues). After a fresh install it's working now. Hats-off. Awesome Rxtension.Really love it

**Comment by charlesg99** [comment]
Glad it is working now. Not sure exactly how you end up with version 9999, I just tried installing from e.g.o. and I ended up with version 38. Also, FWIW I use openweather as well and it is working fine over here:

![image](https://user-images.githubusercontent.com/33044886/88478059-3d6b6c80-cf13-11ea-94c9-326f246f50b8.png)

Thanks for the feedback!

**Comment by Ferdous123** [comment]
Can you kindly tell me the installation process? I'm new to Ubuntu. What's
e.g.o?

**Comment by Ferdous123** [comment]
I cloned from the git & followed the instructions. it gives me the
following error...

Now type `make' to compile gnome-shell-extension-openweather
Making all in src
make[1]: Entering directory
'/home/ferdous/gnome-shell-extension-openweather/src'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory
'/home/ferdous/gnome-shell-extension-openweather/src'
Making all in data
make[1]: Entering directory
'/home/ferdous/gnome-shell-extension-openweather/data'
Makefile:536: *** missing separator.  Stop.
make[1]: Leaving directory
'/home/ferdous/gnome-shell-extension-openweather/data'
make: *** [Makefile:384: all-recursive] Error 1

**Comment by Ferdous123** [comment]
I asked about the OpenWeather actually
