### ISSUE TITLE
Running indicator style do not change the style when Ungroup Applications is on

### ISSUE THREAD

**Issue by hlechner** [home-sweet-gnome/dash-to-panel#1102]
**Describe the bug**
The options to change the _**Running indicator style**_ only applies when the option _**Ungroup applications**_ is turned off.

Running indicator style options:
![image](https://user-images.githubusercontent.com/11244067/88554088-72072300-cffc-11ea-97d1-87325f24f732.png)
Ungroup applications option:
![image](https://user-images.githubusercontent.com/11244067/88554164-8fd48800-cffc-11ea-856e-05d96b2e00e6.png)

However looking at the code it seems this was intentional, in this case I was thinking of:
- creating a label below the running indicator style options with something to advice it only applies when the Ungroup applications is off
- and also disable the GtkComboBoxText for the two options when the Ungroup applications is turned on.

**Linux distribution and version**
Arch Linux ``Linux archlinux 5.7.9-arch1-1``

**GNOME Shell version**
GNOME Shell 3.36.4

**Dash-to-Panel version**
Running the latest git version [v38] (commit: f32055034f4341f69c8cb9a68e61795e47de794d)

**Where was Dash-to-Panel installed from?**
Github

**Screenshots / Video captures**
"Ungroup applications" turned off:
![image](https://user-images.githubusercontent.com/11244067/88555352-15a50300-cffe-11ea-82b3-c57aa5dba50d.png)
"Ungroup applications" turned on:
![image](https://user-images.githubusercontent.com/11244067/88555462-41c08400-cffe-11ea-8e49-12b7719a1ebf.png)

**Additional Info**
What do you think? Should I try something or better keep the way it is right now?

**Comment by jderose9** [comment]
@hlechner 
I definitely can see this being confusing. Normally, we just disable any inapplicable settings when their pre-requisite setting changes, but this one is a little less obvious since it's on a different tab. It's probably important to note that the settings inside the gear are actually still used even when Ungrouped.

I'm wondering if many people use ungrouped without labels - and if so, should we actually should be completely ignoring the running indicator setting in Ungrouped mode. It doesn't make a lot of sense with the labels, but without labels, using the dots or dashes may be preferred to look more like Mac or ChromeOS.

**Comment by hlechner** [comment]
In my case I was using it because I like the metro/windows 10 style however even on 2020 I still don't like the grouping feature very much, well maybe I should start to get used to it

**Comment by charlesg99** [comment]
Maybe we could simply remove the unavailable options when the applications are ungrouped? As Jason mentioned, not sure if many people are using the ungrouped feature without the labels.

**Comment by charlesg99** [comment]
Also this seems like a duplicate of #703

**Comment by hlechner** [comment]
Apologies about the duplication, 

Since I figured out what was going on, so I disabled the ungroup feature still with this disables.

To me what ever you guys think is the best for this case I can try to implement, if possible to have a way to have the styles without grouping would be nice, but not necessary

**Comment by jderose9** [comment]
I think it's confusing to only disable them since the setting to re-enable is on another tab. Some description would be helpful.

**Comment by zacaj** [comment]
Very annoying, the ungrouped style doesn't look good at all; doesn't make sense that it doesn't use the same settings as everything else
