### ISSUE TITLE
Gradient color on dash-to-panel.

### ISSUE THREAD

**Issue by adaoduque** [home-sweet-gnome/dash-to-panel#1105]
First of all, thanks for the useful extension.

I currently use version 38 of the extension with 2 screens.
In screen 1, the panel has a "gradient color", which has not been configured, but the problem only happens when any window is touching the panel.
This only happens on screen 1, screen 2, the behavior is as expected.

Information about my system and just below the printscreens:

```sh
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

$ gnome-shell --version
GNOME Shell 3.28.4

Dash-to-Panel version: 38
```

Screen 1
![Print](https://drive.google.com/uc?export=view&id=1_VXd2xgMRQioZ8F4CgTpolo1Gi6qB4PX)
![Print](https://drive.google.com/uc?export=view&id=19i7Tjm8Cg9CYLYfLKMlIBK2PYyCrrEuD)
![Print](https://drive.google.com/uc?export=view&id=1OTBkWIHKDuV5Zq1obTQbdxtSGSQBLL15)

Screen 2
![Print](https://drive.google.com/uc?export=view&id=1iX7FNAHXUqT9LzVUmh5Ii6Ca5rrGSjnl)
![Print](https://drive.google.com/uc?export=view&id=1ubvzCEdZelzjCMEl6XJucWRjJwhBZ2LC)

Thanks in advance

**Comment by charlesg99** [comment]
Could you please try to override the gradient and set it to transparent? Some themes add a gradient on the default gnome-shell panel and our gradient setting was primarily introduced to remove those:

![image](https://user-images.githubusercontent.com/33044886/88848734-dff74a00-d1b6-11ea-9997-c02b65ae6676.png)

Thanks!

**Comment by adaoduque** [comment]
Thank you.
Solved with Overide panel theme gradiente.
