### ISSUE TITLE
show-showdesktop-button setting is unused.

### ISSUE THREAD

**Issue by dseomn** [home-sweet-gnome/dash-to-panel#1107]
`schemas/org.gnome.shell.extensions.dash-to-panel.gschema.xml` has a setting `show-showdesktop-button` that appears to be unused. I think its functionality was moved to a different setting in e79d0da8c9856764e32e9cab7cd6a1802677650e, but I haven't looked into it very closely.

**Comment by charlesg99** [comment]
Thanks a bunch! You're right, I forgot to remove that during the recent position refactoring! It is now removed on the master branch.
