### ISSUE TITLE
I want an extension to show on the bar of both the main and secondary monitor, is there a way to do that? 

### ISSUE THREAD

**Issue by numeroflip** [home-sweet-gnome/dash-to-panel#1109]
I have an extension called simple task bar, which I modified a little bit styling-wise. 
It shows fine on my main monitor's bar, but not on the secondary monitor's bar.

[The extension](https://github.com/fthx/simple-task-bar) 

**The issue:**
main monitor:
![image](https://user-images.githubusercontent.com/46031874/88901155-bb4fb080-d250-11ea-87b3-ed3cb30feea0.png)

secondary monitor: 
![image](https://user-images.githubusercontent.com/46031874/88901215-cf93ad80-d250-11ea-9b04-c0918380eb18.png)

I know some javascript, but I don't know the gnome shell ecosystem at all... I would think it is easily achievable with some lines of code I guess.

**Comment by charlesg99** [comment]
Hello, unfortunately this isn't something that we can do, you'll have to ask the simple task bar developer to add support for multiple panels. Also, please see https://github.com/home-sweet-gnome/dash-to-panel/issues/794#issuecomment-549203917. Thanks!
