### ISSUE TITLE
[Feature Request?] Replace 'Show Applications' Action

### ISSUE THREAD

**Issue by tmfksoft** [home-sweet-gnome/dash-to-panel#1111]
**Describe the idea or feature you'd like**
It'd be really useful to replace the action the Show Applications button performs.
To be more specific, I have "Applications Menu" installed which has a really nice category menu for applications, I don't really like the fullscreen Application menu built into Ubuntu. In Fine-Tune I can disable the original gnome-shell top panel to force the "Applications" menu onto the panel but it takes up a lot of room as it's using text rather than an Icon.

Is it possible to do something like this already, if not could this be added somehow?

Here's an example showing the Applications Menu when forced into the panel by disabling the gnome-shell top panel.
![app_menu](https://user-images.githubusercontent.com/4118296/89017398-27deb400-d312-11ea-86a6-b23d18c927c7.png)

**Is your feature request related to a problem? Please describe.**
No real problem, would be convenient to have.

**Additional context**
Add any other context or mock-ups for requested feature here.

**Comment by hlechner** [comment]
I'm not a member of dash to panel but trying to help anyway.

Not sure if I understand what do you mean by `Replace 'Show Applications' Action`.

But if you want a menu with a icon instead of text maybe you should try the `Arc Menu` extension instead, there are many layouts available on it's configuration and also you can modify the icon, then you can disable the `Show Applications` (on dash to panel settings) if you dislike it's behavior.

**Comment by tmfksoft** [comment]
> I'm not a member of dash to panel but trying to help anyway.
> 
> Not sure if I understand what do you mean by `Replace 'Show Applications' Action`.
> 
> But if you want a menu with a icon instead of text maybe you should try the `Arc Menu` extension instead, there are many layouts available on it's configuration and also you can modify the icon, then you can disable the `Show Applications` (on dash to panel settings) if you dislike it's behavior.

Yup, you've nailed exactly what I mean. Just need to have it to the left of the Activities button >_>
But yes, this is spot on what I'm after.

**Comment by charlesg99** [comment]
Hello Thomas!

> Just need to have it to the left of the Activities button >_>

https://github.com/home-sweet-gnome/dash-to-panel/issues/1089#issuecomment-660055637

**Comment by tmfksoft** [comment]
*facepalm*
I forgot that existed, it's been a warm day in the UK. That's my excuse!

All that's needed now is https://github.com/home-sweet-gnome/dash-to-panel/issues/400 :D!

I'll close this, hopefully it'll be of good reference to someone running away from Windows in future ;)
