### ISSUE TITLE
Undesired behavior of left-/right-clicking on Show Applications button, in case of scrolling is enabled for a long taskbar

### ISSUE THREAD

**Issue by ytx21cn** [home-sweet-gnome/dash-to-panel#1113]
### Things to do first
- Confirm that the problem persists when Dash-to-Panel is the only enabled extension. To do so, disable every other extension, then restart gnome-shell by running the `r` command from the prompt that appears when pressing Alt+F2 on an X.org session, or by logging out/in on a Wayland session.
- Look for Dash-to-Panel errors in your log. To do so, run the `journalctl /usr/bin/gnome-shell -f -o cat &` command and reproduce the problem.
- Search existing opened and closed issues to see if the problem has already been reported.

### Describe the bug
I have just migrated from the Ubuntu Dock to the Dash to Panel extension.

I have a somewhat long list of applications being pinned, causing it to scroll when I use Dash to Panel.

I have spotted some undesired behavior of using the **Show application** button with left or right click, **when the application icons is not at the leftmost position**:
- When I left-click the **Show applications** button, it does NOT pop up the applications view (full-screen). Instead, it opens a **random application** on the left, whose icon is not visible when I have scrolled to the right.
- When I right-click the **Show applications** button, it does NOT show the menu for the **Show applications** button either. Instead, it shows up the menu for a **random application** on the left, and scrolls to the left until that application is visible on the task bar.

**Expected behavior:**
Regardless of where the application list has been scrolled to, it shall always perform the behavior when I left-/right-click the **Show applications** button.

### Linux distribution and version
Ubuntu 20.04 LTS

### GNOME Shell version
3.36.3

### Dash-to-Panel version
9999

### Where was Dash-to-Panel installed from?
```
sudo apt install gnome-shell-extension-dash-to-panel
```

### Screenshots / Video captures
![Screenshot from 2020-07-31 14-25-15](https://user-images.githubusercontent.com/5900105/89078966-4fe20d80-d33a-11ea-9758-0005ba267ef2.png)

### Additional Info
N/A

**Comment by charlesg99** [comment]
Hello, I can't reproduce that so far on Ubuntu 2.04, could you post a screenshot of your exact position settings?

**Comment by ytx21cn** [comment]
> Hello, I can't reproduce that so far on Ubuntu 2.04, could you post a screenshot of your exact position settings?

![Screenshot from 2020-08-01 10-28-20](https://user-images.githubusercontent.com/5900105/89106815-bf5f0800-d3e1-11ea-8572-e624d8d67f22.png)

**Comment by charlesg99** [comment]
Please install the latest version of the extension.

**Comment by ytx21cn** [comment]
> Please install the latest version of the extension.

Solved. Thanks!
