### ISSUE TITLE
Together with shell-extension "Unite" top bar window buttons position "Last" is not last anymore.

### ISSUE THREAD

**Issue by thomas-wach** [home-sweet-gnome/dash-to-panel#1115]
Using hardpixel/unite-shell in combination with dash-to-panel, top bar window buttons are now placed into "right" bar, not last bar anymore, even if selected "Last" in unite.

Disabling dash-to-panel, unite-shell correctly distinguishes correctly between "right" and "last".
With dash-to-panel enabled it does not anymore,

<a href="https://imgbb.com/"><img src="https://i.ibb.co/Fm9d4f5/screen.png" alt="screen" border="0"></a>

Arch-Linux
GNOME Shell 3.36.4
Linux evolution-01 5.7.10-arch1-1 #1 SMP PREEMPT Wed, 22 Jul 2020 19:57:42 +0000 x86_64 GNU/Linux

"Right" and "Last" (should be most right) aren't honored correctly with dash-to-panel activated.
"Last" is used in the same manner as "Right".

Link to same issue in unite-shell: [https://github.com/hardpixel/unite-shell/issues/189](https://github.com/hardpixel/unite-shell/issues/189)

**Comment by charlesg99** [comment]
Please see #1091
