### ISSUE TITLE
"Show Application"-button not working

### ISSUE THREAD

**Issue by tejfoon** [home-sweet-gnome/dash-to-panel#1116]
When pressing the "show application"-button, it only shows the following in the top left corner of the screen: 

https://imgur.com/a/I6bC2K6

After pressing it again the closing animation starts, where all app icons in the middle of the application screen move to the buttom left corner. After that I see a preview of all active windows, but I am stuck there and the only way out is to restart gnome.

Distribution: the latest pop_OS
GNOME Shell version: 3.36.4
Dash-to-Panel version: 9999 (?) Installed from the extension webside

Edit: I now installed it  from github (v38) and it works just fine.

**Comment by dioio-io** [comment]
I have same issue

**Comment by charlesg99** [comment]
Yes, not sure what's up with this "version 9999" but this isn't correct ("9999" is a placeholder for the version that is replaced when the extension is correctly "built" using the make command), safer to install from e.g.o. or Github for now. Thanks!
