### ISSUE TITLE
Miniscule application icons after resume with multiple monitors on Ubuntu 20.04

### ISSUE THREAD

**Issue by jlundan** [home-sweet-gnome/dash-to-panel#1120]
Hey,

First of all: thanks for the extension! This finally lets me have my Ubuntu desktop as I want it. =)

Noticed that the app icons are really small (and in wrong monitor) after resuming from suspend. I attached couple of images. First one is after I clicked "Show Applications" right after resuming from suspend:
![Screenshot from 2020-08-06 23-48-48](https://user-images.githubusercontent.com/1215642/89582166-d61db880-d840-11ea-8369-3b5b11eb4583.png)
The second one is after I executed
```
/usr/bin/dconf write /org/gnome/shell/extensions/dash-to-panel/panel-size 49
```
![Screenshot from 2020-08-06 23-49-36](https://user-images.githubusercontent.com/1215642/89582393-3ca2d680-d841-11ea-8cf2-07529cbb811a.png)

This is also what the applications list looks like right after reboot. So:

- Everything works nicely until I suspend and resume the machine
- Changing the panel-size (either via dconf or via the extension's settings dialog) fixes the issue (needs to change the value, my default panel-size is 48)
- Happens systematically on every resume
- I am running Ubuntu 20.04
- My gnome shell version is GNOME Shell 3.36.3
- I installed the extension using `sudo apt install gnome-shell-extension-dash-to-panel`. If I click "Check now" from the extension settings about tab, I get a notification that says that I am up to date. 

apt-cache output:
```
➜  ~ apt-cache show gnome-shell-extension-dash-to-panel
Package: gnome-shell-extension-dash-to-panel
Architecture: all
Version: 31-1
Priority: optional
Section: universe/gnome
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Jonathan Carter <jcc@debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 1413
Depends: dconf-gsettings-backend | gsettings-backend, gnome-shell (>= 3.18)
Filename: pool/universe/g/gnome-shell-extension-dash-to-panel/gnome-shell-extension-dash-to-panel_31-1_all.deb
Size: 156564
MD5sum: f4a18f9bf2bb03f61e08cb5d6eaba788
SHA1: 8e9ca3ad2d848f093958697363a05a23278cde50
SHA256: 0c59563c808eb9c3870056eff59e665405fef3c804aac390a73d01cdb5df2b08
Homepage: https://github.com/jderose9/dash-to-panel
Description-en: combines the dash and the GNOME main panel into a single panel
 Moves the dash into the GNOME main panel so that the application launchers
 and system tray are combined into a single panel, similar to that found
 in KDE Plasma and Windows 7+.
 .
 A separate dock is no longer needed for easy access to running and
 favorited applications.
Description-md5: 63e193d0ba2fcbd880f805d69b871251
```
My settings export file is also attached:
[dtp-export.txt](https://github.com/home-sweet-gnome/dash-to-panel/files/5038015/dtp-export.txt)

Running  `journalctl --since today /usr/bin/gnome-shell -o cat > gs.txt` yields:
[gs.txt](https://github.com/home-sweet-gnome/dash-to-panel/files/5038145/gs.txt)
(I limited the time window since the last resume was just moments ago today, and it is now bit over midnight here.)

The extension is the only enabled extension. I have multiple extensions installed, but I disabled all of them.

**Comment by mattgcc** [comment]
I'm not using multiple monitors but I'm also experiencing this issue.

**Comment by jlundan** [comment]
Found out that sending HUP signal to gnome-shell fixes this too (since gnome-shell restarts after that, and restart fixes the issue too). So wrote a small workaround for myself. It is not pretty, but at least fixes the issue for me. Thought I would share it here too. Disclaimer: this is a somewhat dirty hack, and your mileage might vary. Use at your own risk. :)

Basically I wrote a script that I hooked in to the screen unlock event. Quick steps how to implement the fix:

Create file (`sudo vim /usr/local/bin/start-gnome-restart-daemon.sh`) with following contents
```
#!/bin/bash
set -o nounset                # good practice, exit if unset variable used

pidfile=/tmp/lastauth.pid     # lock file path

cleanup() {                   # when cleaning up:
    rm -f $pidfile            # * remove the lock file
    trap - INT TERM EXIT      # * reset kernel signal catching
    exit                      # * stop the daemon
}

if [ -e "$pidfile" ]; then    # if lock file exists, exit
    log $0 already running...
    exit
fi

trap cleanup INT TERM EXIT    # call cleanup() if e.g. killed

echo $$ > $pidfile            # create lock file with own PID inside

expr='type=signal,interface=org.gnome.ScreenSaver' # DBus watch expression here

dbus-monitor --session "$expr" | \
    while read line; do
        case "$line" in
            *"boolean false"*) killall -1 gnome-shell ;;
        esac
    done

cleanup # let's not leave orphaned lock file when the loop ends (e.g. dbus dies
```
(script is modified from an answer at https://unix.stackexchange.com/questions/28181/how-to-run-a-script-on-screen-lock-unlock)

Then create systemd unit to run the script
```
mkdir -p ~/.local/share/systemd/user
vim ~/.local/share/systemd/user/gnome-restart-daemon.service
```
Insert contents:
```
[Unit]
After=network.service

[Service]
ExecStart=/usr/local/bin/start-gnome-restart-daemon.sh

[Install]
WantedBy=default.target
```

Then enable it:
```
sudo chmod 744 /usr/local/bin/start-gnome-restart-daemon.sh
chmod 644 ~/.local/share/systemd/user/gnome-restart-daemon.service
systemctl --user enable gnome-restart-daemon.service
```
And reboot your machine. The script starts when you log in and restarts gnome every time you unlock your screen.

I tested this on my own computer (I am using it currently) and it seems to work. The unlock process is bit uglier now, since gnome restarts, but at least my app menu always looks as it should. I did not test this anywhere else, so it might have bugs or unforeseen consequences. Anyways, hopefully this might help people with the same issue until the issue itself is resolved.

**Comment by charlesg99** [comment]
Hello, please install the latest version of the extension from [e.g.o.](https://extensions.gnome.org/extension/1160/dash-to-panel/) or from [Github](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation). This should solve the issue as it looks like Ubuntu's `gnome-shell-extension-dash-to-panel` wasn't packaged properly and is out of date. Thanks!

**Comment by jlundan** [comment]
Thanks! Can confirm that latest version from extensions.gnome.org works.
