### ISSUE TITLE
Undesired behavior: small icons, GNOME Dash disabling is ignored, empty taskbar, et cetera

### ISSUE THREAD

**Issue by mattgcc** [home-sweet-gnome/dash-to-panel#1121]
**Describe the bug**
Not desired behavior:
1. The taskbar doesn't show opened apps time from time, conversely it shows apps that aren't open as open.
2. The taskbar displays really small icons after turning on the computer, logging out logging in, locking the screen and unlocking it.
![image](https://user-images.githubusercontent.com/28257966/89588114-a922d300-d84b-11ea-9b68-fb6ca3d3f32f.png)
3. The GNOME dash persists even though I disabled it in settings of the addon
**Linux distribution and version**
Solus 4.1 Fortitude 
**GNOME Shell version**
3.36.4

**Dash-to-Panel version**
38
**Where was Dash-to-Panel installed from?**
The GNOME extensions website.

**Screenshots / Video captures**
If applicable, add screenshots or a link to a video capture to help explain your problem.
After changing the panel size to anything, the taskbar reappears, but closed windows are still displayed in the taskbar. See:
![image](https://user-images.githubusercontent.com/28257966/89588763-f8b5ce80-d84c-11ea-9616-737c0cc5f161.png)

**Additional Info**
I get these error messages:
https://gist.github.com/mattgcc/e49d86bb4e90012f69b4687bf8f8db67

**Comment by charlesg99** [comment]
Hello, the errors you're reporting are coming from dash to **dock**, please follow this:

**Things to do first**
- Confirm that the problem persists when Dash-to-Panel is the only enabled extension. To do so, disable every other extension, then restart gnome-shell by running the `r` command from the prompt that appears when pressing Alt+F2 on an X.org session, or by logging out/in on a Wayland session.
- Look for Dash-to-Panel errors in your log. To do so, run the `journalctl /usr/bin/gnome-shell -f -o cat &` command and reproduce the problem.
- Search existing opened and closed issues to see if the problem has already been reported.

**Comment by mattgcc** [comment]
> Hello, the errors you're reporting are coming from dash to **dock**, please follow this:
> 
> **Things to do first**
> 
> * Confirm that the problem persists when Dash-to-Panel is the only enabled extension. To do so, disable every other extension, then restart gnome-shell by running the `r` command from the prompt that appears when pressing Alt+F2 on an X.org session, or by logging out/in on a Wayland session.
> * Look for Dash-to-Panel errors in your log. To do so, run the `journalctl /usr/bin/gnome-shell -f -o cat &` command and reproduce the problem.
> * Search existing opened and closed issues to see if the problem has already been reported.

Hello,

Are they? I'm using Dash to Panel but also have Dash to Dock installed (which was disabled at the time of reporting). For now the issue seems to have to disappeared and I cannot really reproduce it... I'll keep a look at it.

**Comment by charlesg99** [comment]
Glad it's working now, we can re open the issue if we get to a point where it is reproducible using only dash to panel. Thanks!
