### ISSUE TITLE
Empty dash-to-panel after cold login

### ISSUE THREAD

**Issue by makayjozsef** [home-sweet-gnome/dash-to-panel#1122]
Dash-to-Panel 38 doens't show panel elements (except some plugins clipboard, screenshot) after cold login on Ubuntu 20.04 with GNOME 3.36.3

When I restart the DE with Alt+F2 / r the Dash-to-Panel is restart too and this step solves the problem until the next cold login.

**Comment by charlesg99** [comment]
**Things to do first**
- Confirm that the problem persists when Dash-to-Panel is the only enabled extension. To do so, disable every other extension, then restart gnome-shell by running the `r` command from the prompt that appears when pressing Alt+F2 on an X.org session, or by logging out/in on a Wayland session.
- Look for Dash-to-Panel errors in your log. To do so, run the `journalctl /usr/bin/gnome-shell -f -o cat &` command and reproduce the problem.
- Search existing opened and closed issues to see if the problem has already been reported.

**Comment by makayjozsef** [comment]
I found the root cause: Dash-to-Panel is incompatible with Multi Monitors Add-On extension. That blocked the component loading. When I removed that extension the problem was solved.
