### ISSUE TITLE
Show applications button not working even though enabled in settings

### ISSUE THREAD

**Issue by HasanQZ** [home-sweet-gnome/dash-to-panel#1123]
Show applications button is not showing up even though enabled in settings.

When set to have the button centered in the middle of the panel, nothing shows up and half the panel is blank.

![missing show applications button](https://user-images.githubusercontent.com/59009269/89684854-c195fa80-d8ea-11ea-9ec6-9fd3ae6f9f20.png)

OS: Manjaro 
Dash to Panel version: 38

I tried resetting all settings in gnome-tweaks and dash to panel to default but this did not fix the issue.

The button showed up on older versions of dash to panel.

Thanks

**Comment by HasanQZ** [comment]
Turns out you need another extension to make this work that i was not aware of.

https://extensions.gnome.org/extension/812/show-applications/

**Comment by hlechner** [comment]
I can't reproduce it here, but could you try to change the gnome-shell theme and see if still the same?

There is a tool to diagnose extensions called looking glass, to open it press Alt-F2 and type: `lg` when you hit enter, on the top left corner of the looking glass window there is a color picker icon, click on it and go with your cursor other your panel over the edge of the panel (where the show applications should have been) and see if it will show something like this in the center of your screen:

> ![image](https://user-images.githubusercontent.com/11244067/89719884-3298e900-d9a3-11ea-9cba-9d6d5ff5281f.png)

the `StButton.show-apps` is the show application button, if it's too small like 1px you can still see it using the looking glass

Btw: I'm not a dash-to-panel member, just another user

**Comment by HasanQZ** [comment]
> I can't reproduce it here, but could you try to change the gnome-shell theme and see if still the same?
> 
> There is a tool to diagnose extensions called looking glass, to open it press Alt-F2 and type: `lg` when you hit enter, on the top left corner of the looking glass window there is a color picker icon, click on it and go with your cursor other your panel over the edge of the panel (where the show applications should have been) and see if it will show something like this in the center of your screen:
> 
> > ![image](https://user-images.githubusercontent.com/11244067/89719884-3298e900-d9a3-11ea-9cba-9d6d5ff5281f.png)
> 
> the `StButton.show-apps` is the show application button, if it's too small like 1px you can still see it using the looking glass
> 
> Btw: I'm not a dash-to-panel member, just another user

I tried what you recommended, there is still no button showing up or highlighted, which is strange. I tried increasing and decreasing the padding for the icon, to no avail. I also changed the gnome shell theme to the default and many others, which still did not fix the problem.

**Comment by hlechner** [comment]
Can you try to give me some logs? you can post it on a gist (https://gist.github.com/).

You can use the journalctl: `journalctl /usr/bin/gnome-shell -f`

you can try to restart the shell and see the messages from it, also try to click on visible and see what messages you receive, just comment what you did before the messages, like:
// GNOME-SHELL RESTARTED:
or
// CLICKED ON VISIBLE BUTTON:
etc

**Comment by HasanQZ** [comment]
> Can you try to give me some logs? you can post it on a gist (https://gist.github.com/).
> 
> You can use the journalctl: `journalctl /usr/bin/gnome-shell -f`
> 
> you can try to restart the shell and see the messages from it, also try to click on visible and see what messages you receive, just comment what you did before the messages, like:
> // GNOME-SHELL RESTARTED:
> or
> // CLICKED ON VISIBLE BUTTON:
> etc

after hitting alt+f2, typing "r" to restart gnome, and running the command, this is the output i got.
```

-- Logs begin at Tue 2020-08-04 23:38:19 GMT. --
Aug 08 16:57:09 manjaro gnome-shell[1598]: clutter_actor_set_child_at_index: assertion 'child->priv->parent == self' failed
Aug 08 16:57:09 manjaro gnome-shell[1598]: clutter_actor_add_child: assertion 'child->priv->parent == NULL' failed
Aug 08 16:57:09 manjaro gnome-shell[1598]: clutter_actor_set_child_at_index: assertion 'child->priv->parent == self' failed
Aug 08 16:57:09 manjaro gnome-shell[1598]: Extension ding@rastersoft.com already installed in /home/hasan/.local/share/gnome-shell/extensions/ding@rastersoft.com. /usr/share/gnome-shell/extensions/ding@rastersoft.com will not be loaded
Aug 08 16:57:09 manjaro gnome-shell[1598]: loading default theme (Adwaita)
Aug 08 16:57:11 manjaro gnome-shell[1598]: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
Aug 08 16:57:11 manjaro gnome-shell[1598]: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
Aug 08 16:57:11 manjaro gnome-shell[1598]: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
Aug 08 16:57:12 manjaro gnome-shell[1598]: GNOME Shell started at Sat Aug 08 2020 16:57:08 GMT+0000 (Greenwich Mean Time)
Aug 08 16:57:12 manjaro gnome-shell[1598]: Registering session with GDM
```

**Comment by charlesg99** [comment]
**Things to do first**
- Confirm that the problem persists when Dash-to-Panel is the only enabled extension. To do so, disable every other extension, then restart gnome-shell by running the `r` command from the prompt that appears when pressing Alt+F2 on an X.org session, or by logging out/in on a Wayland session.
- Look for Dash-to-Panel errors in your log. To do so, run the `journalctl /usr/bin/gnome-shell -f -o cat &` command and reproduce the problem.
- Search existing opened and closed issues to see if the problem has already been reported.

**Comment by HasanQZ** [comment]
>     * Confirm that the problem persists when Dash-to-Panel is the only enabled extension. To do so, disable every other extension, then restart gnome-shell by running the `r` command from the prompt that appears when pressing Alt+F2 on an X.org session, or by logging out/in on a Wayland session.

After disabling and uninstalling all extensions i could, the problem was still not fixed.

>     * Look for Dash-to-Panel errors in your log. To do so, run the `journalctl /usr/bin/gnome-shell -f -o cat &` command and reproduce the problem.
There were no errors with Dash-To-Panel in the log
```
JS ERROR: TypeError: actor.get_meta_window(...) is null
_destroyWindowDone@resource:///org/gnome/shell/ui/windowManager.js:1590:32
onStopped@resource:///org/gnome/shell/ui/windowManager.js:1560:39
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:73:13
_easeActor/<@resource:///org/gnome/shell/ui/environment.js:149:56
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:233:16

Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
Will monitor session 2
Telepathy is not available, chat integration will be disabled.
Extension ding@rastersoft.com already installed in /home/hasan/.local/share/gnome-shell/extensions/ding@rastersoft.com. /usr/share/gnome-shell/extensions/ding@rastersoft.com will not be loaded
Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
GNOME Shell started at Sat Aug 08 2020 23:56:04 GMT+0000 (Greenwich Mean Time)
Registering session with GDM
```
>     * Search existing opened and closed issues to see if the problem has already been reported.
someone has a similar problem in issue #1116, i remove all traces of dash to panel that i could find and git cloned and reinstalled the extension, which did not fix the problem. issue #432 is similar but the button apparently still appeared and worked for him.

Theres nothing there i can click, even after checking with looking-glass, there is just no button there to click.

**Comment by HasanQZ** [comment]
When i removed the extension again, and tried to reinstall it from the gnome extensions website, i get this error
```
The settings of extension dash-to-panel@jderose9.github.com had an error:

Error: GSettings key desktop-line-use-custom-color not found in schema org.gnome.shell.extensions.dash-to-panel


Stack trace:

_checkKey@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:576:23
_init/createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:528:30
_bindSettings@/home/hasan/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/prefs.js:924:24
wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
_init@/home/hasan/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/prefs.js:189:14
wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
_Base.prototype._construct@resource:///org/gnome/gjs/modules/script/_legacy.js:18:10
newClass@resource:///org/gnome/gjs/modules/script/_legacy.js:114:21
buildPrefsWidget@/home/hasan/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/prefs.js:2199:20
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by charlesg99** [comment]
>After disabling and uninstalling all extensions i could, the problem was still not fixed.

Did you restart gnome-shell after disabling all other extensions? This is probably a conflict with one of them as I can't reproduce that. Thanks!

**Comment by AndrewZaech** [comment]
This same issue happened to me after upgrading to v38

Steps to reproduce

- Install Dash to Panel v37
- Reload gnome-shell
- Turn off 'Show Applications Icon' in Dash to Panel settings under "Behavior" tab
- Install Dash to Panel v38
- Reload gnome-shell
- Application icon will not show even when toggling "Show Applications button" setting

Running `dconf reset -f /org/gnome/shell/extensions/dash-to-panel/show-show-apps-button` fixes the issue

**Comment by charlesg99** [comment]
Thanks a lot Andrew, I'll fix this right away!

**Comment by HasanQZ** [comment]
> Running `dconf reset -f /org/gnome/shell/extensions/dash-to-panel/show-show-apps-button` fixes the issue
This fixed the problem. Thank you so much.

**Comment by charlesg99** [comment]
Alright, the fix is now on master and the old setting is gone. Thanks!

**Comment by gkaravidas** [comment]
I have the same problem for a few version updates now. The "Applications button" is not showing on the dash panel, even if it is set to visible, but it does work when I click at the empty space where the icon should have been. 

I've read the solution above, with dconf, but it didn't work. Then I've noticed that the key "show-show-apps-button" does not exist. 
Any ideas how can I fix that?

![image](https://user-images.githubusercontent.com/13132336/192253206-c95fc009-47ca-401f-92c0-fa8d534c0e15.png)
