### ISSUE TITLE
An option to hide icons in the taskbar view

### ISSUE THREAD

**Issue by mattgcc** [home-sweet-gnome/dash-to-panel#1124]
**Describe the idea or feature you'd like**
Add a feature that makes it possible to hide icons from the taskbar view.
Please note that the favorite icons when the favorite application isn't open should be there, but the applications that are open should not have icons.

**Additional context**
Thank you for reading my feature request.
![image](https://user-images.githubusercontent.com/28257966/89696955-acd55900-d922-11ea-9942-0adff75a485e.png)

**Comment by jderose9** [comment]
If I am understanding correctly, this already exists in the settings:
![image](https://user-images.githubusercontent.com/2118702/89699347-391c5780-d8f4-11ea-88db-c93488a14035.png)
