### ISSUE TITLE
App Icon Margin: make it reflect the space between buttons (in px)

### ISSUE THREAD

**Issue by hlechner** [home-sweet-gnome/dash-to-panel#1125]
Hey @jderose9 I hope I'm not annoying you with my requests.

Based on closed pull request #1104 I've being trying a new way to do so without adding any option on preferences, so, I've found a way to do that.

my commit: https://github.com/hlechner/dash-to-panel/commit/5fe8f1d3604f7c82fe19a980db8dbaf7c8028396

I found a variable called `currentPosition` which is an int with the position of the button itself, so basically I use this variable to check if this variable is equal to 0 then `padding: 0;` otherwise uses the padding to left (or in case of vertical: top)

that was very simple, the tricky part was to use the current value, I tried your suggestion of float point `.5` but I found out it can't be done that way because I had to change on schematics from `int` to `double` and then it doesn't allow me to get the old results (even if the only key available on gsettings is the int one).

I have tried some options but I think the best (from that commit) is to add a new boolean inside schematics, if this boolean is false it will change the value (value *2) and set this boolean to true.

Since the original maximum was 32 of margin (considering it's just left now will be 64, so I change the scale to reflect it.

Thanks

**Comment by hlechner** [comment]
I just realize how annoying maybe I'm right now, by proposing too many changes.

I'm creating a gnome-shell theme and also a shell script (I want to create a repository when it's done) to change the configurable options of the extensions to create a windows 10 panel, as much as close as possible and since this awesome dash-to-panel extension is the key extension for that happens, that's why my requests.

I'm getting pretty close to the original metro panel right now, I sent some pull requests to others extensions as well.

But if I annoying too much or using too much of your guys time, don't worry to tell me and I will stop those requests.

thanks again

**Comment by jderose9** [comment]
@hlechner No worries at all. This project depends on community help and we appreciate the contributions.

I don't mean to disappoint but while many dash-to-panel users are current or former Windows users it is not our goal to make a pixel-perfect replica of Windows. Instead I would rather make sure the settings are intuitive and that we provide a reasonable amount of stability to the existing users.

I think defining the margin in terms of each icon (as it is now) is more intuitive especially to anyone that has done any sort of programming or graphical work. I'm also concerned about confusing existing users that are happy with their setup. For those reasons I don't think it's ideal to make a change like this right now. I'm having trouble envisioning a single pixel difference being perceptible in this situation but perhaps screenshots would help if you disagree. But at this point I think it makes most sense to close this issue.

**Comment by hlechner** [comment]
No problem, I understand, I think I will close the #1118 too, since the idea behind it was to change the style to get closer to windows.
