### ISSUE TITLE
Allow to change notification counter style

### ISSUE THREAD

**Issue by ExposedCat** [home-sweet-gnome/dash-to-panel#1127]
It is too big and ugly.

Also now I can't change width and font size for `#dashtopanelScrollview .notification-badge` in `stylesheet.css`

**Comment by kehanlu** [comment]
I think this is still under implementing. 
The `progress-show-count` is not working in the latest version.

To hide the badge you can clone the repository and modify the `progress-show-count` to `false` in `schemas/org.gnome.shell.extensions.dash-to-panel.gschema.xml`. Then `make install` by yourself. read the wiki/installation

To make it looks prettier like you did. After you modified the CSS file, you also need to `make install` it again.
