### ISSUE TITLE
Looking glass does not show completely when Dash-to-Panel is at the top

### ISSUE THREAD

**Issue by Puspam9876** [home-sweet-gnome/dash-to-panel#1128]
When this extension (Dash-to-panel) is enabled and is set to be at the top of the screen, the looking glass of Gnome shell (which can be accessed by Pressing <kbd>ALT</kbd>+<kbd>F4</kbd> and then typing **lg**), does not show up completely. It just stays at the top with only a small portion of it displayed.

**Steps to reproduce:** Set Dash-to-Panel to be at the top of the screen. Then try launching Gnome's looking glass.

**Linux distribution and version:** Ubuntu 20.04

**GNOME Shell version:** 3.36.3

**Dash-to-Panel version:** 38

Dash-to-Panel extension was installed from the Gnome extensions website.

**Screenshots:**
![Screenshot from 2020-08-09 19-20-14](https://user-images.githubusercontent.com/59383614/89733829-d05ce880-da75-11ea-8c9e-d221c311d639.png)

**Comment by charlesg99** [comment]
Hello, please see #1084 and also look into **closed** issues before opening a new one. Thanks!
