### ISSUE TITLE
Crash on gnome-shell 3.36.4-1ubuntu1~20.04.1

### ISSUE THREAD

**Issue by zq1997** [home-sweet-gnome/dash-to-panel#1129]
**Describe the bug**
Totally crashed on `gnome-shell 3.36.4-1ubuntu1~20.04.1`, the desktop enviroment is unusable at all.

**Linux distribution and version**
Ubuntu 20.04

**GNOME Shell version**
3.36.4-1ubuntu1~20.04.1

**Dash-to-Panel version**
The newest version in ubuntu repositroy

**Where was Dash-to-Panel installed from?**
ubuntu repositroy via apt-get

**Additional Info**
Well, `Gome 3.36.4-1ubuntu1~20.04.1` is provided by `focal-proposed` of ubuntu, not the `main` part of repository. However, the new released `Ubuntu 20.04.1 LTS` image use newer version of `gnome-shell` than `3.36.3-1ubuntu1~20.04.2` in main repository.

**Comment by charlesg99** [comment]
Hello, v38 is working fine for me on Ubuntu's 3.36.4, please install from [e.g.o.](https://extensions.gnome.org/extension/1160/dash-to-panel/) or from [Github](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation).

![image](https://user-images.githubusercontent.com/33044886/89779423-52ccc300-dadd-11ea-8773-43659944d0d2.png)

**Comment by zq1997** [comment]
Well, `gnome-shell-extension-dash-to-panel` in ubuntu repository is still in version `31-1`, maybe it's a little old, could you please upgrade it to date?

**Comment by charlesg99** [comment]
Hello, yes it is out of date, but unfortunately we aren't responsible for its packaging, maybe you could [open an issue](https://launchpad.net/ubuntu/+source/gnome-shell-extension-dash-to-panel) on Ubuntu's bug tracker.

I think your best bet is to install the extension from [e.g.o.](https://extensions.gnome.org/extension/1160/dash-to-panel/) Thanks!

**Comment by jderose9** [comment]
Yes, I think essentially they pin to the debian testing version at time of Ubuntu release and then never update it, but do continue to update gnome shell. So any breaking changes from GS that we fix don't get released to the ubuntu focal update repo.

**Comment by philippun1** [comment]
Bug report at launchpad: https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-dash-to-panel/+bug/1891378
Hopefully the groovy package gets backported.
