### ISSUE TITLE
Question- Is the panel height the same in the lastest version?

### ISSUE THREAD

**Issue by Lucapz** [home-sweet-gnome/dash-to-panel#1130]
I can't quite put my finger on it but something seems different with the latest version of DTP, is the panel height the same as it's always been or has there been a change in height for extra panel padding?

Sorry to waste people's time with something so trivial if i'm just imagining things.

**Comment by charlesg99** [comment]
Hello Lucapz, to my knowledge the panel's height hasn't changed. Did you install a new theme or something? Thanks!

**Comment by Lucapz** [comment]
Solved thanks charlesg99.

The font size and weight in the panel applications titles increased slightly , i've not changed anything as it's always been on the default settings but at least i now know what it was that looked different.

Thanks for getting back to me.
