### ISSUE TITLE
In ubuntu 20.04, clicking on 'All Applications' crashes the shell

### ISSUE THREAD

**Issue by digster** [home-sweet-gnome/dash-to-panel#1131]
Everything works in ubuntu 20.04 except when you click on 'All Applications' or press the super key.

- All the icons become blank
- application windows can't be focused on
- clicks don't register
- general shell crash overall

Restarting the shell or the session is the only solution. Already tried all the solutions including disabling all the extensions.

**Comment by jderose9** [comment]
Did you install via the Ubuntu package repo?

**Comment by Levidant** [comment]
Happens on Pop OS too. It can be solver by choosing shell version 3.36 and extension version 38

**Comment by sacherjj** [comment]
Got this as well.  Had to launch gnome-tweaks from CLI and disable dash-to-panel before ever clicking Show Applications.  

Running 3.34.0-2ubuntu1

**Comment by sacherjj** [comment]
Pulling down the latest from github and make install made everything good for me.  So this looks like it can be fixed with a packaging update.

**Comment by digster** [comment]
Fixed.
I had installed the extension from the package manager which was really old(31). Installing from the repo fixed it.
Tested working on - Ubuntu 20.04, gnome shell 3.36.4, Dash to panel 38.
Thanks to all those who chipped in.

**Comment by sacherjj** [comment]
Who handles packaging of this to Ubuntu?  Is that the gnome-tweaks team?  It would be great to push to get a newer version packaged so the update would not kill less capable users.

**Comment by philippun1** [comment]
Bug report at launchpad: https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-dash-to-panel/+bug/1891378
Hopefully the groovy package gets backported.

**Comment by lverissimo** [comment]
this is happening to me with version 38 installed on Fedora 32
