### ISSUE TITLE
Super Key Not Working

### ISSUE THREAD

**Issue by Srijan1214** [home-sweet-gnome/dash-to-panel#1132]
Hello,

I just ran sudo apt update/ upgrade and the dash to panel extension is giving me errors. The super overview is not showing correctly and I cannot exit out of the super overview. The work-spaces are also not showing. The only way to exit overview is with alt-F2 + r.

This is in gnome-shell version 3.36.4.

![gnome_bug](https://user-images.githubusercontent.com/25398686/90169023-01863300-dd6c-11ea-9063-f5673fcd625a.gif)

**Comment by VitalyOstanin** [comment]
Not reproduced with manual installed dash-to-panel v38.

**Comment by Srijan1214** [comment]
@VitalyOstanin Following your instructions fixed it. I tried removing dash to panel with
sudo apt-get remove gnome-shell-extension-dash-to-panel
and reinstalling with 
sudo apt-get install gnome-shell-extension-dash-to-panel
but that did not fix the issue.

But your method did. Thank You so much.
