### ISSUE TITLE
Extension breaks when accessing Overview or applications list

### ISSUE THREAD

**Issue by rivenirvana** [home-sweet-gnome/dash-to-panel#1134]
The problem was first observed after restarting the system after acquiring the recent gnome-shell update (3.36.5). It persists even when Dash-to-Panel is the only enabled extension, and journalctl prints out the following log when the bug occurs:

```
JS ERROR: TypeError: this._syncWorkspacesFullGeometry is not a function
_newUpdateWorkspacesViews@/home/rhaziz/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:563:22
show@resource:///org/gnome/shell/ui/workspacesView.js:612:14
show@resource:///org/gnome/shell/ui/viewSelector.js:276:33
_animateVisible@resource:///org/gnome/shell/ui/overview.js:580:27
show@resource:///org/gnome/shell/ui/overview.js:566:14
toggle@resource:///org/gnome/shell/ui/overview.js:689:18
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:220:22
```

The bug occurs when pressing the \<Super\> key which is supposed to bring out the Overview, or when clicking on the Show Applications icon which is supposed to bring out the applications grid. What happens instead is that the open windows do not scale to be laid onto the Overview; hovering over the windows show their focus highlight and close button on the top left corner of the screen; workspaces do not appear in right side of the screen; the extension's panel does not appear; keystrokes are not automatically captured by the search bar, and; you are stuck and cannot exit the Overview.

The windows do scale after pressing \<Super\>+\<a\> twice (showing and minimizing the applications grid), but the bug does not disappear, and there is no way to exit the Overview except for restarting the Shell via \<Alt\>+\<f2\> and r.

I am using Fedora 32 with GNOME Shell 3.36.5 on an X.org session. Dash-to-Panel is version 38 and was installed via the GNOME extensions website.

![Screenshot from 2020-08-14 15-33-30](https://user-images.githubusercontent.com/43519644/90226595-cce6aa00-de45-11ea-80d7-cdb9d68cd6b3.png)
_Before bringing out Overview_

![Screenshot from 2020-08-14 15-34-18](https://user-images.githubusercontent.com/43519644/90226616-d53ee500-de45-11ea-9f9e-d3559871d7fa.png)
_After bringing out Overview_

![Screenshot from 2020-08-14 15-34-36](https://user-images.githubusercontent.com/43519644/90226660-e1c33d80-de45-11ea-9dce-bbff4c6f9370.png)
_After forcing windows to scale by opening and closing the applications grid_

**Comment by charlesg99** [comment]
Hello, please search existing issues before opening a new one. See #1074, thanks!

**Comment by PJFonseca** [comment]
> Hello, please search existing issues before opening a new one. See #1074, thanks!

He is talking about Fedora 32, and using v38 does not fix the problem.

**Comment by lcavajani** [comment]
I also hit the same issue with `Fedora 32` and `v38`.

**Comment by rivenirvana** [comment]
Can confirm that the current master branch as of time of posting fixes the problem I was having. I think ed00ae6 is the relevant commit. I've been using the master branch for a few days now without any issues. Sorry for the missed report.
