### ISSUE TITLE
Time and date are not visible when panel is on left or right

### ISSUE THREAD

**Issue by manojbhatt101010** [home-sweet-gnome/dash-to-panel#1135]
Before this update, time and date were displayed vertically when the panel was on left but now it's always horizontal. Because of this, time and date are not visible on the panel. Please provide some fix as I like to use panel on left.
![Screenshot from 2020-08-14 15-28-15](https://user-images.githubusercontent.com/56686788/90238136-108be480-de43-11ea-973a-5cb55303d457.png)  
![Screenshot from 2020-08-14 15-29-32](https://user-images.githubusercontent.com/56686788/90238174-1bdf1000-de43-11ea-9109-9959dad6990c.png)
Date and time are visible when the panel is on bottom as in pictures above.

**Comment by charlesg99** [comment]
Hello, please search existing issues before opening a new one. See #1080, thanks!
