### ISSUE TITLE
[Feature Request] Option to remove dropdown arrow

### ISSUE THREAD

**Issue by amrmsaraya** [home-sweet-gnome/dash-to-panel#1136]
**Describe the idea or feature you'd like**
Acutally i'm not a fan of dropdown arrows, i think it is old school and doesn't fit modern desktop, i know there is extension to do that but it's buggy because it's not maintained anymore, so i think if you can add option to remove dropdown arrows it will be so great. thanks in advance

**Additional context**
With dropdown arrow
![1](https://user-images.githubusercontent.com/21042432/90317642-32f92d00-df2b-11ea-84fa-d4719d8ed475.png)

Without dropdown arrow
![2](https://user-images.githubusercontent.com/21042432/90317649-3c829500-df2b-11ea-825d-702c20392941.png)

**Comment by sojusnik** [comment]
Reference to https://github.com/home-sweet-gnome/dash-to-panel/issues/790

**Comment by camtofu** [comment]
same opinion with op.
I normally use vertical position of Dash-to-Panel.
dropdown arrows waste precious panel space.
![Screenshot from 2021-06-19 17-05-41_crop_g](https://user-images.githubusercontent.com/75305458/122639096-8a0ef600-d12a-11eb-9c16-2d27dcf56244.png)
