### ISSUE TITLE
cant start programs nor leave the activity page

### ISSUE THREAD

**Issue by JerryPenguin** [home-sweet-gnome/dash-to-panel#1138]
**Things to do first**
- Confirm that the problem persists when Dash-to-Panel is the only enabled extension. To do so, disable every other extension, then restart gnome-shell by running the `r` command from the prompt that appears when pressing Alt+F2 on an X.org session, or by logging out/in on a Wayland session.

done

- Look for Dash-to-Panel errors in your log. To do so, run the `journalctl /usr/bin/gnome-shell -f -o cat &` command and reproduce the problem.
-- snip
_newUpdateWorkspacesViews@/home/jerry/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:563:22
show@resource:///org/gnome/shell/ui/workspacesView.js:612:14
show@resource:///org/gnome/shell/ui/viewSelector.js:276:33
_animateVisible@resource:///org/gnome/shell/ui/overview.js:580:27
show@resource:///org/gnome/shell/ui/overview.js:566:14
toggle@resource:///org/gnome/shell/ui/overview.js:689:18
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:220:22
--snap

- Search existing opened and closed issues to see if the problem has already been reported.

done

**Describe the bug**
A clear and concise description of what the problem is, any steps to reproduce, and what you expected to happen instead.

Since updating the gnome-shell to version 3.36.5 under Fedora 32 I have the following problem:

After pressing the super key I get the activities overview page.
But I can neither start a program nor press the Super key again to leave this page.
The only remaining possibility is to log me out.

**Linux distribution and version**
Fedora 32 with wayland

**GNOME Shell version**
GNOME Shell 3.36.5

**Dash-to-Panel version**
Version 38

**Where was Dash-to-Panel installed from?**
The GNOME extensions website.

**Screenshots / Video captures**
none

**Additional Info**

**Comment by PJFonseca** [comment]
I have the same problem.

**Comment by PJFonseca** [comment]
Go and check @VitalyOstanin comment here: https://github.com/home-sweet-gnome/dash-to-panel/issues/1132#issuecomment-673689980

**Comment by RoflCopter24** [comment]
This is affecting me too. Started after updating the system (Ubuntu 20.04)
@PJFonseca Thanks for the tip. Installing from extensions.gnome.org instead worked!

__Linux distribution and version__
Ubuntu 20.04 / Wayland

__GNOME Shell version__
GNOME Shell 3.36.4

__Dash-to-Panel version__
Version 31-1

__Where was Dash-to-Panel installed from?__
Ubuntu repositories

**Comment by PeteS4** [comment]
For Fedora 32, extensions.gnome.org already is the primary way to obtain this extension, as there is no package in the DNF repos.  Can confirm that the latest version, installed manually from extensions.gnome.org, does not work with F32.

**Comment by PJFonseca** [comment]
> For Fedora 32, extensions.gnome.org already is the primary way to obtain this extension, as there is no package in the DNF repos. Can confirm that the latest version, installed manually from extensions.gnome.org, does not work with F32 and GNOME Shell 3.36.4.

Can confirm that. Did it right now...still fails.

**Comment by charlesg99** [comment]
https://github.com/home-sweet-gnome/dash-to-panel/issues/1074#issuecomment-657059578

Please search existing issues before opening new ones and install the latest master from Github until the next version is released on e.g.o. Thanks!

**Comment by PeteS4** [comment]
@charlesg99 Correct me if I'm wrong, but the latest release on Github is v38, which is the same version available on e.g.o. I installed the Github release anyway, but it's still broken on Fedora 32/Gnome 3.36.4.

**Comment by PJFonseca** [comment]
> @charlesg99 Correct me if I'm wrong, but the latest release on Github is v38, which is the same version available on e.g.o. I installed the Github release anyway, but it's still broken on Fedora 32/Gnome 3.36.4.

You are correct. Let's see what @charlesg99 says about it.

**Comment by JerryPenguin** [comment]
> @charlesg99 Correct me if I'm wrong, but the latest release on Github is v38, which is the same version available on e.g.o. I installed the Github release anyway, but it's still broken on Fedora 32/Gnome 3.36.4.

This is not quite correct, with git clone the release package is not installed, but the current repo is synchronized and installed with make install. You can also see from the timestamps that changes were made in the repo after the release of v38.

With mit, uninstalling and reinstalling directly from GIT (not the release, but via git clone and make install) worked.

many thanks @charlesg99 

and many greetings

**Comment by PJFonseca** [comment]
> > @charlesg99 Correct me if I'm wrong, but the latest release on Github is v38, which is the same version available on e.g.o. I installed the Github release anyway, but it's still broken on Fedora 32/Gnome 3.36.4.
> 
> This is not quite correct, with git clone the release package is not installed, but the current repo is synchronized and installed with make install. You can also see from the timestamps that changes were made in the repo after the release of v38.
> 
> In my case the uninstallation and reinstallation directly from the GIT (not the release, but via git clone and make install) worked.
> 
> many thanks @charlesg99
> 
> and many greetings

This is what I like on comments. You just made me learn about make files and how to fix the issue. Thanks for that.

**Comment by PeteS4** [comment]
@JerryPenguin Thanks, I was misled by the mention of a fix for 3.36.4 in the release notes of v38. Now it's working perfectly again!
