### ISSUE TITLE
Blue selection artifact with panel on bottom and clock at right

### ISSUE THREAD

**Issue by acabal** [home-sweet-gnome/dash-to-panel#114]
Great extension, thanks!

I found very small nitpick in case you're interested in pixel-perfectionism.

1. Place the panel on the bottom.
2. Place the clock on the right.
3. Open the system icons menu (volume, wifi, logout, etc.).

Result: the blue selection bar under the system icons shows the "curve" selection bar in the far lower-right of the screen.  This is an artifact of the bar having been designed to sit at the top of the screen.  It's a little hard to describe but here's a screenshot:

![screenshot from 2017-04-08 00-19-06](https://cloud.githubusercontent.com/assets/866144/24825986/73f6a018-1bf1-11e7-99e8-376f6b787ec6.png)

This is of course a very minor nitpick, but maybe something that can be fixed in the interest of a pixel-perfect presentation.

In either case thanks again for your hard work and the great extension!

**Comment by jderose9** [comment]
Thanks for reporting this! This is specific to the default theme, but perhaps we can override the style for the corners in this extension's stylesheet.

**Comment by charlesg99** [comment]
Hello, a small fix for this was added to master, thanks!
