### ISSUE TITLE
cp: cannot open './_build/metadata.json' for reading: Permission denied

### ISSUE THREAD

**Issue by nlpsuge** [home-sweet-gnome/dash-to-panel#1141]
**Describe the bug**
Clone the master branch from github, then run 'make install'. And I got this error:
cp: cannot open './_build/metadata.json' for reading: Permission denied

Run ll to see the file's permission:
ll ./_build/metadata.json
----------. 1 n n x x x x ./_build/metadata.json

The complete output is:
rm -fR ./_build
mkdir -p _build
cp extension.js stylesheet.css metadata.json COPYING README.md appIcons.js convenience.js panel.js panelManager.js proximity.js intellihide.js progress.js panelPositions.js panelStyle.js overview.js taskbar.js transparency.js windowPreview.js prefs.js update.js utils.js Settings.ui _build
mkdir -p _build/img
cd img ; cp highlight_stacked_bg.svg highlight_stacked_bg_2.svg highlight_stacked_bg_3.svg ../_build/img/
mkdir -p _build/schemas
cp schemas/*.xml _build/schemas/
cp schemas/gschemas.compiled _build/schemas/
mkdir -p _build/locale
for l in po/cs.mo po/uk.mo po/hu.mo po/ja.mo po/sv.mo po/zh_TW.mo po/pl.mo po/it.mo po/zh_CN.mo po/de.mo po/ru.mo po/tr.mo po/es.mo po/fr.mo po/kk.mo po/pt_BR.mo ; do \
	lf=_build/locale/`basename $l .mo`; \
	mkdir -p $lf; \
	mkdir -p $lf/LC_MESSAGES; \
	cp $l $lf/LC_MESSAGES/dash-to-panel.mo; \
done;
sed -i 's/"version": [[:digit:]][[:digit:]]*/"version": 38,\n"commit": "c793632b567d5f96ee8291caecb8aaac09f6f968"/'  _build/metadata.json;
rm -rf /home/n/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com
mkdir -p /home/n/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com
cp -r ./_build/* /home/n/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/
cp: cannot open './_build/metadata.json' for reading: Permission denied
make: *** [Makefile:65: install-local] Error 1

**Linux distribution and version**
Fedora 32

**GNOME Shell version**
GNOME Shell 3.36.5

**Dash-to-Panel version**
38

**Where was Dash-to-Panel installed from?**
Directly from github, on master branch

**Screenshots / Video captures**

**Additional Info**
My workaround is:
chmod 777 ./_build/metadata.json
cp -r ./_build/* /home/n/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/

**Comment by jderose9** [comment]
@nlpsuge I think this must be an issue on your end. Git only tracks whether a file is executable and should mark all files as readable on cloning.

**Comment by nlpsuge** [comment]
I happened to run into this similar issue [three months before](https://github.com/MycroftAI/mycroft-core/issues/2561#issuecomment-625308103)

That's so funny......
