### ISSUE TITLE
Not working with latest gnome-shell

### ISSUE THREAD

**Issue by mbevc1** [home-sweet-gnome/dash-to-panel#1143]
**Things to do first**
- Confirm that the problem persists when Dash-to-Panel is the only enabled extension. To do so, disable every other extension, then restart gnome-shell by running the `r` command from the prompt that appears when pressing Alt+F2 on an X.org session, or by logging out/in on a Wayland session.
- Look for Dash-to-Panel errors in your log. To do so, run the `journalctl /usr/bin/gnome-shell -f -o cat &` command and reproduce the problem.
- Search existing opened and closed issues to see if the problem has already been reported.

**Describe the bug**
Not sure if it's related to plugin or upstream: https://bugzilla.redhat.com/show_bug.cgi?id=1869540

**Linux distribution and version**
Fedora 32

**GNOME Shell version**
gnome-shell-3.36.5-1.fc32

**Dash-to-Panel version**
68

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Additional Info**

**Comment by charlesg99** [comment]
#1139

**Comment by mbevc1** [comment]
Sorry, haven't seen that one, will move to other ticket.

**Comment by mbevc1** [comment]
Also it is suggesting https://github.com/home-sweet-gnome/dash-to-panel/commit/ed00ae61ba5c81ceec6e5bb9f04afa8272fac13a is a solution and already in `master`. Could we get a new erlease or is there anything else stopping this ATM? Thanks!
