### ISSUE TITLE
Fall back to last window when super + num 

### ISSUE THREAD

**Issue by Austaras** [home-sweet-gnome/dash-to-panel#1144]
Say user has opened 5 apps and he pressed super + 8, currently this extension seems to do nothing, I believe it's better to activate last app which is app no.5

**Comment by jderose9** [comment]
@Austaras Thanks for the feedback. Realizing this stuff is rather subjective - I don't think this is intuitive so we probably will not be implementing it in this extension unless we get additional requests.
