### ISSUE TITLE
Can't enable the dev version on Fedora 33 (Gnome 3.37.3)

### ISSUE THREAD

**Issue by bkdwt** [home-sweet-gnome/dash-to-panel#1145]
Hi. Installed the dev version of the extension but still doesn't working on Fedora 33 with the Gnome 3.37. Installed successfully but I can't enable. 

![Screenshot from 2020-08-18 12-21-50](https://user-images.githubusercontent.com/51302074/90532261-687d6080-e14d-11ea-97da-c64546dc0661.png)

**Comment by charlesg99** [comment]
Hello, thank you for the report! 3.38 support hasn't been added yet, but we're planning to work on it soon as the release is next month. I'll close this one to keep 3.37+ discussion in #1034. Thanks!
