### ISSUE TITLE
Date and clock are not displayed correctly (anymore) when using the panel on it's side

### ISSUE THREAD

**Issue by pkly** [home-sweet-gnome/dash-to-panel#1148]
**Describe the bug**
Until a few days ago I could easily see my time, because the date and time were wrapped, but that changed when I logged in today for some reason.
Now I can only see the date, and time is hidden on the right side of it and doesn't get wrapped.

**Linux distribution and version**
Ubuntu 20.04

**GNOME Shell version**
3.36.4

**Dash-to-Panel version**
38

**Where was Dash-to-Panel installed from?**
GNOME extensions

**Screenshots / Video captures**
![image](https://user-images.githubusercontent.com/17160364/90722849-e3fd2000-e2bb-11ea-903c-02db395086ad.png)

**Additional Info**
I'm almost certain it used to work until today and was showed as

11:12
19 sie

**Comment by charlesg99** [comment]
Hello, please search existing issues before opening a new one. See #1080, thanks!
