### ISSUE TITLE
Indicator not showing up with some apps

### ISSUE THREAD

**Issue by davidmartos96** [home-sweet-gnome/dash-to-panel#1152]
**Describe the bug**
I have a 2 monitor setup and I have the "Isolate monitors" option activated.
There are some apps that when opened, the running indicator is not showing up unless moving the app to a different monitor. 
I did some JS debugging and it seems that the problem is that when opened, the "window.get_monitor()" returns the wrong monitor index for a few frames.
This doesn't occur with all the apps. Some that have this bug are:
- Nautilus
- Sublime Merge
- Tilix

Locally editing the function `onWindowsChanged` to this, fixes the issue. I don't have experience with developing Gnome extensions, there is probably a better way to fix it.

```js
    onWindowsChanged: function() {
        this._updateWindows();
        this.updateIcon();

        Mainloop.timeout_add(100, Lang.bind(this, function () {
            this._updateWindows();
            this._displayProperIndicator();
            return GLib.SOURCE_REMOVE;
        }));
    }
``` 

**Linux distribution and version**
Opensuse Tumbleweed

**GNOME Shell version**
GNOME Shell 3.36.5

**Dash-to-Panel version**
39

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Comment by davidmartos96** [comment]
This is still happening in the latest version

**Comment by chnavarro** [comment]
I have the same issue, also work with 2 monitors, and isolate monitors, this happens when I open nautilus file explorer. An issue workaround is to drag the app between monitors.

**Comment by davidmartos96** [comment]
@chnavarro That works for me too, but I find it very annoying. If you want to try my workaround from above you just need to open the `appIcons.js` file inside `$HOME/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/` and replace the `onWindowsChanged` function with: (important the comma at the end)

```js
onWindowsChanged: function() {
        this._updateWindows();
        this.updateIcon();

        Mainloop.timeout_add(100, Lang.bind(this, function () {
            this._updateWindows();
            this._displayProperIndicator();
            return GLib.SOURCE_REMOVE;
        }));
    },
```

Then you can restart the Gnome Shell with Alt+F2 and then type 'r'. Alternatively you can sign in and sign out.
The downside is that you need to do it everytime the extension updates, but is not that often.
Hope it helps!

**Comment by chnavarro** [comment]
@davidmartos96 
Thank you very much, you are a genius!, it works the first time. I already knew about the workarounds but as you said they are very annoying.

Thank you very much again, I hope this fix will come to release soon. I think it is something that may not be critical but it is very annoying in the case of multiple monitors.

**Comment by jderose9** [comment]
At this point I don't think there are going to be any further releases tagged from this repo for support of GNOME <= 3.38, so feel free to patch without worrying about it getting overwritten.

If anyone observes in GNOME 3.40, please share. Thanks!

**Comment by davidmartos96** [comment]
@jderose9 I use Opensuse Tumbleweed which is already running Gnome 3.40, and using one the forks of dash-to-panel I'm still running into the issue, so I'd say the bug is still there.

**Comment by chnavarro** [comment]
@jderose9 I just update from fedora 33 to Fedora 34 and the issue is still there :( , so I use the same fix of @davidmartos96, and works.

**Comment by chnavarro** [comment]
The bug is still present, please fix it :-(

**Comment by chnavarro** [comment]
Is still present

Linux distribution and version
Fedora 35

GNOME Shell version
GNOME Shell 41.5

Dash-to-Panel version
46
