### ISSUE TITLE
Time is displayed over multiple lines if panel position is left

### ISSUE THREAD

**Issue by d-t-o** [home-sweet-gnome/dash-to-panel#1155]
**Describe the bug**
in older versions of DTP the time was displayed in one line in a left-sided panel. Now it's displayed in 3 lines and the colon between hours and minutes seems to be misaligned (horizontal instead of vertical). Or maybe it's just 2 dots and not a rotated colon? can't tell, but whatever it is, it's too many lines :)
![image](https://user-images.githubusercontent.com/16400654/91211487-22a53700-e70f-11ea-8fa0-a8e2b0f767b3.png)

**Linux distribution and version**
Ubuntu 20.04

**GNOME Shell version**
GNOME Shell 3.36.4

**Dash-to-Panel version**
39

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
see above and below

**Additional Info**
my first idea was to just increase the panel size from 48px to 52px, which solves the time display, but it messes with the aspect ratio of tray icons, so i don't consider it a workaround:
![image](https://user-images.githubusercontent.com/16400654/91211654-6b5cf000-e70f-11ea-9c0f-45a4ec7d3e89.png)

**Comment by d-t-o** [comment]
In case anybody else is annoyed by this: I just realized that under 'fine-tune' in the dtp settings, one can change the font size of the tray area, so as a workaround: 16px -> 14px.

**Comment by charlesg99** [comment]
I'll close this as this is intended. As you pointed out you can adjust the font size or the panel size to bring it on one line. Thanks!
