### ISSUE TITLE
overview not centered on Fedora 33

### ISSUE THREAD

**Issue by briandconnolly** [home-sweet-gnome/dash-to-panel#1156]
See attached screenshot.

![Screenshot from 2020-08-31 07-47-13](https://user-images.githubusercontent.com/31881084/91722018-47f6d280-eb5f-11ea-9f5c-f1dd5773da0a.png)

**Comment by guoqiyi** [comment]
same here,and the systemd log keep reporting this warning:
gnome-shell[5997]: Can't update stage views actor StWidget is on because it needs an allocation.

**Comment by guoqiyi** [comment]
sorry,I missed the date,my problem occurs after I updated to gnome 3.38 on archlinux
