### ISSUE TITLE
Keep getting an error

### ISSUE THREAD

**Issue by 1marc1** [home-sweet-gnome/dash-to-panel#1157]
Whenever I try to enable Dash-to-Panel, it keeps showing up as "Error" on https://extensions.gnome.org/local/.

When looking at `sudo journalctl /usr/bin/gnome-shell`, I see the following:

`JS ERROR: Extension dash-to-panel@jderose9.github.com: TypeError: this._overview is undefined`

I am running Ubuntu 20.04.

```
$ cat /usr/share/gnome/gnome-version.xml 
<?xml version="1.0"?>
<gnome-version>
 <platform>3</platform>
 <minor>36</minor>
 <micro>3</micro>
 <distributor>Ubuntu</distributor>
 <!--<date></date>-->
</gnome-version>
```

Any ideas or suggestions are welcome.

**Comment by yummydirtx** [comment]
I have this same issue.

**Comment by 1marc1** [comment]
Let me know what additional information can be useful in attempting to resolve this issue.

**Comment by charlesg99** [comment]
**Things to do first**
- Confirm that the problem persists when Dash-to-Panel is the only enabled extension. To do so, disable every other extension, then restart gnome-shell by running the `r` command from the prompt that appears when pressing Alt+F2 on an X.org session, or by logging out/in on a Wayland session.
- Look for Dash-to-Panel errors in your log. To do so, run the `journalctl /usr/bin/gnome-shell -f -o cat &` command and reproduce the problem.
- Search existing opened and closed issues to see if the problem has already been reported.

**Dash-to-Panel version**
This can be seen in the Dash-to-Panel Settings in the About tab.

**Where was Dash-to-Panel installed from?**
The GNOME extensions website, GNOME Software store, your distribution's package manager, pre-installed with the distribution, directly from github, etc.

**Screenshots / Video captures**
If applicable, add screenshots or a link to a video capture to help explain your problem.

**Additional Info**

**Comment by 1marc1** [comment]
Thanks for your assistance, Charles. This is what I have done.

* Go to: https://extensions.gnome.org/local/
* Disabled all installed extensions.
* Pressed ALT+F2 and ran `r` command.
* Go to: https://extensions.gnome.org/extension/1160/dash-to-panel/
* Enabled the extension.
* Selected to install the extension.
* This results in "ERROR".
* Pressed ALT+F2 and ran `r` command.
* Still showing as "ERROR".
* Dash-to-Panel also shows as "ERROR" on https://extensions.gnome.org/local/
* Ran `journalctl /usr/bin/gnome-shell -f -o cat &`
* Go to: https://extensions.gnome.org/extension/1160/dash-to-panel/
* Uninstalled Dash-to-Panel.
* Enabled Dash-to-Panel and selected to Install it again.
* Output from journalctl:

`JS ERROR: Extension dash-to-panel@jderose9.github.com: TypeError: this._overview is undefined
get viewSelector@resource:///org/gnome/shell/ui/overview.js:158:9
_init@/home/marc/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:67:9
C@/home/marc/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/utils.js line 83 > eval:1:46
_enable@/home/marc/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:95:20
enable@/home/marc/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:65:5
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:349:26
callback@resource:///org/gnome/shell/ui/extensionDownloader.js:234:39
gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13`

* Dash-to-Panel version: 39

**Comment by ackstorm23** [comment]
Same problem here.

```
gnome-shell[442290]: JS ERROR: Extension dash-to-panel@jderose9.github.com: TypeError: this._overview is undefined
                                            get viewSelector@resource:///org/gnome/shell/ui/overview.js:158:9
                                            getAppDisplayViews@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/utils.js:307:5
                                            _init@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:67:15
                                            C@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/utils.js line 83 > eval:1:46
                                            _enable@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:95:20
                                            enable@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:65:5
                                            _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:166:32
                                            loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:348:26
                                            activate@/home/exile/.local/share/gnome-shell/extensions/extension-reloader@nls1729/extension.js:117:34
                                            vfunc_button_release_event@resource:///org/gnome/shell/ui/popupMenu.js:138:14

```

**Comment by ackstorm23** [comment]
@1marc1 you aren't by chance running in Gnome Classic mode are you?

**Comment by 1marc1** [comment]
@ackstorm23 yes, I am running Gnome Classic.

**Comment by ackstorm23** [comment]
> @ackstorm23 yes, I am running Gnome Classic.

I was too.   I switched to current Gnome-Shell and it now works perfectly. 

Might be that the author is only supporting current GS versions.

**Comment by 1marc1** [comment]
You are right, switching to Gnome-Shell makes it work. It would be nice if there was some sort of check to inform the user, like: "Dash-to-panel is not supported on Gnome Classic".
