### ISSUE TITLE
[Taskbar] Unable to move apps near favorite contents area and vise versa

### ISSUE THREAD

**Issue by Aikatsui** [home-sweet-gnome/dash-to-panel#1158]
**Is your feature request related to a problem? Please describe.**
This affect with both launched and non launched apps. Compared to windows, i cannot move apps near to left area on taskbar. If i bring any launched or non launched apps near to left side then auto add as favorite app. If i bring any favorite app (launched or not) to right side then auto remove from favorite apps.

No such problem with windows even has same facility. Is there way to disable happen that when dragging app icons?

PopOS 20.04.01

**Comment by KizunaH** [comment]
https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-ubuntu-dock/+bug/1896394
