### ISSUE TITLE
Closing a window in preview

### ISSUE THREAD

**Issue by JChamblee99** [home-sweet-gnome/dash-to-panel#1161]
**Describe the bug**
If peeking is enabled, closing a window from the preview can sometimes leave you temporarily stuck.
Specifically when closing a window that leaves your mouse outside of the list of window previews.

**Linux distribution and version**
Ubuntu 20.04

**GNOME Shell version**
3.36.4

**Dash-to-Panel version**
39

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**

Temporarily stuck until you hover back over the preview:
![Peek 2020-09-03 20-48](https://user-images.githubusercontent.com/42752805/92191480-80313600-ee29-11ea-9078-6fc94b2ac3ad.gif)

If you close the window before it can peek, you need to hover until it peeks into the window to fix it:
![Peek 2020-09-03 21-35](https://user-images.githubusercontent.com/42752805/92193251-76113680-ee2d-11ea-9ef6-d50d6dacf70b.gif)

**Comment by charlesg99** [comment]
Thank you John, I could reproduce the issue. It should now be fixed on the master branch, could you install it and confirm that the window peek now ends correctly? Thanks!

**Comment by JChamblee99** [comment]
It's working as expected now. Thanks @charlesg99!
