### ISSUE TITLE
Want a pinned and frequent section like in windows ..

### ISSUE THREAD

**Issue by nazar2sfive** [home-sweet-gnome/dash-to-panel#1162]
![image](https://user-images.githubusercontent.com/12841320/92325598-c07ff680-f06b-11ea-8e51-8e0e6ef1994f.png)

![image](https://user-images.githubusercontent.com/12841320/92325647-0210a180-f06c-11ea-867f-9976d99040e3.png)

I wish i could pin that .odt to the PINNED list for my easy access later.

**Comment by jderose9** [comment]
Thanks @nazar2sfive, but I think this one is a duplicate of #225 .
