### ISSUE TITLE
 Allow a user to select among a full screen app menu, bottom of the screen horizontal app menu with left/right arrows, or a vertical app menu with up/down arrows located next to the dash.

### ISSUE THREAD

**Issue by 49studebaker** [home-sweet-gnome/dash-to-panel#1164]
**Describe the idea or feature you'd like**
In the Settings app, Dock(Dash) screen, there should be an "Application Menu Style" option. The user could select: Full screen, Horizontal, or Vertical.

**Is your feature request related to a problem? Please describe.**
Some people would prefer a horizontal or vertical menu instead of a full screen menu.

**Additional context**
![bar](https://user-images.githubusercontent.com/18037226/92346773-6eeb6200-f093-11ea-8e58-9d243c74a963.png)

![bar2](https://user-images.githubusercontent.com/18037226/92346853-a78b3b80-f093-11ea-8a6d-82735e9403c2.png)

![vertical_bar1](https://user-images.githubusercontent.com/18037226/92346898-d6091680-f093-11ea-9e06-5b5975902375.png)

**Comment by jderose9** [comment]
Thanks for the idea, but I think this is outside of the scope of this extension.
