### ISSUE TITLE
Display the dash-to-panel at the top of screen as default.

### ISSUE THREAD

**Issue by 49studebaker** [home-sweet-gnome/dash-to-panel#1165]
**Describe the idea or feature you'd like**
By default, the dash-to-panel should be displayed at the top of the screen instead of the bottom. The window buttons(minimize, maximize, close) are at the top of the screen. In Firefox, the tabs, navigation buttons, url bar, bookmarks, etc are at the top of the screen. 

**Is your feature request related to a problem? Please describe.**
It takes more effort to move the mouse pointer from the top of the screen to the bottom of the screen.

**Additional context**
Add any other context or mock-ups for requested feature here.

**Comment by jderose9** [comment]
Thanks for the feedback. Lacking telemetry or a UX team, I’ll fall back to pretty much every commercial OS having the application launchers on the bottom, so we will leave it as-is. This can of course be changed in the settings for those that prefer the top.
