### ISSUE TITLE
Scrolling the panel cycles windows in the wrong direction

### ISSUE THREAD

**Issue by ekatz-quotient** [home-sweet-gnome/dash-to-panel#1167]
When _Scroll panel action_ is set to _Cycle windows_ scrolling **down** the panel cycles **left**, which is the opposite of the expected behaviour (say, in Firefox with _toolkit.tabbox.switchByScrolling_ set to _true_).
This is a great extension, thanks!

**Comment by chrisjbillington** [comment]
This is also the opposite of my expectation - compared to chrome as well, and Qt tabs.

**Comment by ekatz-quotient** [comment]
Still a problem.
