### ISSUE TITLE
I can't exit shell

### ISSUE THREAD

**Issue by picaso127** [home-sweet-gnome/dash-to-panel#1168]
**Describe the bug**
I can't exit the shell after entering it.

I tried to upgrade my system and gnome-shell from version 1:3.36.4-1 to 1:3.36.6-1.
Right after the upgrade everything worked, but after the system went through a reset
The shell broke.

I could not exit the shell and the screen got stuck that way.

after reporting the bug on the gnome-shell page we found out that the bug only happens when the dock to panel extention is enabled.

**Linux distribution and version**
Arch Linux x86_64  : 5.4.63-1-lts

**GNOME Shell version**
GNOME Shell version : 1:3.36.6-1

**Dash-to-Panel version**
version: 9999

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**

**Additional Info**
bug report on the shell which discovered that the bug related to dash to panel extension:
 https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3164#note_909495

**Comment by charlesg99** [comment]
Hello, please install from e.g.o. 

see https://github.com/home-sweet-gnome/dash-to-panel/issues/1147#issuecomment-687111330
