### ISSUE TITLE
Remove icon and text shadow

### ISSUE THREAD

**Issue by Unviray** [home-sweet-gnome/dash-to-panel#1171]
To make it more minimal.  
Is there any way to remove the shadow behind icons and texts ?
![Screenshot from 2020-09-12 17-20-22](https://user-images.githubusercontent.com/44167149/92997812-bd2eb400-f51e-11ea-890b-cd99f5024fe2.png)
![Screenshot from 2020-09-12 17-20-28](https://user-images.githubusercontent.com/44167149/92997817-c586ef00-f51e-11ea-82ad-b2a062cd06df.png)

**Comment by jderose9** [comment]
I think you just need to choose another Shell theme. I have no shadow.

![Screenshot from 2020-09-15 08-41-26](https://user-images.githubusercontent.com/2118702/93211552-65b36280-f72f-11ea-944f-be6de4a5556c.png)
