### ISSUE TITLE
Gnome 3.38 Compatibility

### ISSUE THREAD

**Issue by mohegan** [home-sweet-gnome/dash-to-panel#1178]
**Describe the bug**
The extension doesn't work properly with gnome 3.38. I have only an empty black bar. I have this error in journactl :
`sept. 17 14:28:00 jack-XPS-L322X gnome-shell[937]: JS ERROR: Extension dash-to-panel@jderose9.github.com: ImportError: No JS module 'screencast' found in search path`

**Linux distribution and version**
Ubuntu 20.10

**GNOME Shell version**
GNOME Shell 3.37.91

**Dash-to-Panel version**
The last version from github repository

**Where was Dash-to-Panel installed from?**
Directly from github

**Additional Info**
To work properly, I have modified the **panel.js** file. Just comment the lines 1482 and 1495 :
`//this._screencast = new imports.ui.status.screencast.Indicator();`
`//this._indicators.add_child(Utils.getIndicators(this._screencast));`

And restart gnome-shell.

_Maybe, it is due to this commit : [Move screencasting into a separate service process ](https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/2b0731ab81887fd9767da73695c754c5b9aadd7c)_

**Comment by mohegan** [comment]
This issue was fix with this commit : **[Fix system indicator removal on 3.38 ](https://github.com/home-sweet-gnome/dash-to-panel/commit/7d931b1fb4f4beed9d3a05d14b52fd31198a7d3a)**

:+1:

**Comment by Cretezy** [comment]
I'm using Ubuntu 20.10 with GNOME 3.38.1 and still getting this error after reinstalling from the extension page, version 40.

![image](https://user-images.githubusercontent.com/2672503/99824663-048b7f00-2b24-11eb-8897-835dcfe32571.png)
