### ISSUE TITLE
I hope there is an option to toggle the behavior when dragging file/folder into taskbar

### ISSUE THREAD

**Issue by axzxc1236** [home-sweet-gnome/dash-to-panel#1182]
**Describe the idea or feature you'd like**  
Add a options for Windows like behavior when dragging a file/folder into taskbar (icon):
I imagine the different/new behavior is to bring up preview window when I drag file into taskbar icon (like how I can make preview window appears when hover over taskbar icon), then I drag my file into preview window to bring up the certain program that I eventually drop the file into.

**Is your feature request related to a problem? Please describe.**
What I want is to have the **same workflow to dragging a file/folder into application** on Ubuntu and Windows.  
What I currently do on Gnome+Dash-to-panel ([screen recording](https://i.imgur.com/aHKvX47.mp4)): I drag a file -> move mouse to taskbar -> Overview shows up -> find the application in many programs that I've opened up -> move mouse to application -> drop
What I currently do on Windows ([screen recording](https://i.imgur.com/2dmrMRb.gif)): I drag a file -> move mouse to taskbar -> Preview window for the program I want to drag to shows up -> move mouse to preview window -> program shows up -> drop in program
The problem I currently have with Gnome+Dash-to-panel is that it's a mess compare to Windows, I drag the picture file and want to drop into Firefox (to upload to imgur), I have to find my Firefox window in like dozens of windows (not just firefox windows) I've opened.
I miss the Windows like behavior, if I opened 3 command prompt window, then I only have to choose from 3 command prompt windows, not choosing from 3+(other programs I've opened) windows

**Additional context**
none.... I've tried my best to describe what I want with texts... currently I can't find a better way to describe more precisely.

**Comment by l3nn4rt** [comment]
duplicated of https://github.com/home-sweet-gnome/dash-to-panel/issues/46.

briefly:
1. drag stuff in the top left corner (opening overview)
2. hover destination window
3. drop stuff
