### ISSUE TITLE
Dash needs to be clicked before use after opening an app from the picker

### ISSUE THREAD

**Issue by ankitkv** [home-sweet-gnome/dash-to-panel#1183]
**Describe the bug**
If an application is opened from the Application Picker menu (opened by clicking the "Show Applications" icon), the dash/panel is not receptive to click actions anymore until I first click somewhere on the dash/panel to "reactivate" it first. Essentially, after opening a new application through the Application Picker, I always need to double click my next action on the dash/panel for it to have any effect.

**Linux distribution and version**
Ubuntu 20.04 LTS.

**GNOME Shell version**
3.36.4.

**Dash-to-Panel version**
39.

**Where was Dash-to-Panel installed from?**
The GNOME extensions website.

**Comment by l3nn4rt** [comment]
Yes, it is really annoying!
Identified responsible commit to be 53672002f1598a8be19d460e5b58a2281282dde4.
It seems not to affect GS 3.38, but yet it needs to be fixed since many distros keep shipping 3.36 or lower.

**Comment by mansoorahmedmemon** [comment]
Same happened to me.

So, I had to disable that feature.

**Comment by jderose9** [comment]
Is this still occurring on latest master? I haven't been able to reproduce.

**Comment by ankitkv** [comment]
This issue persists after updating to version 40 from the GNOME extensions website (when "Click empty space to close overview" is enabled).
