### ISSUE TITLE
Disappearing date, after a while

### ISSUE THREAD

**Issue by deniswal** [home-sweet-gnome/dash-to-panel#1186]
**Things to do first**
- Confirm that the problem persists when Dash-to-Panel is the only enabled extension. To do so, disable every other extension, then restart gnome-shell by running the `r` command from the prompt that appears when pressing Alt+F2 on an X.org session, or by logging out/in on a Wayland session.

-> Done -> The bug with the clock display seems to disapper.

Compatibility issue: system-monitor by Cerin
Dash to Panel active
Enable System Monitor -> The date disappears

- Look for Dash-to-Panel errors in your log. To do so, run the `journalctl /usr/bin/gnome-shell -f -o cat &` command and reproduce the problem.

-> None

- Search existing opened and closed issues to see if the problem has already been reported.

-> I haven't found a recent one

**Describe the bug**
A clear and concise description of what the problem is, any steps to reproduce, and what you expected to happen instead.

After a while (5 - 10 minutes) the date field becomes blank

**Linux distribution and version**
Ubuntu 18.04, Fedora 31, Manjaro 19.02, Arch, Debian 10.3, openSUSE Leap 15.1, etc.

Ubuntu 20.04

**GNOME Shell version**
Run `gnome-shell --version` from the command line to get this

GNOME Shell 3.36.4

**Dash-to-Panel version**
This can be seen in the Dash-to-Panel Settings in the About tab.

39

**Where was Dash-to-Panel installed from?**
The GNOME extensions website, GNOME Software store, your distribution's package manager, pre-installed with the distribution, directly from github, etc.

https://extensions.gnome.org/local/

**Screenshots / Video captures**
If applicable, add screenshots or a link to a video capture to help explain your problem.

When it works ->
![Screenshot from 2020-09-24 11-52-43](https://user-images.githubusercontent.com/1943600/94130194-a2343c00-fe5c-11ea-9a7e-40052f38af49.png)

After a while ->

**Additional Info**

In Configuration / Dash to panel / position
clicking to Top brings back the date display
clicking to Bottom maintains it OK
![Screenshot from 2020-09-27 19-24-55](https://user-images.githubusercontent.com/1943600/94371482-31f51700-00f7-11eb-84f8-e057109faf88.png)

so Config, Top, Bottom restores the date display for a while, even with system monitor enabled.

**Comment by pho3nixx** [comment]
I had a similar problem with the clock disappearing, that occurred after every time I unlocked the screen.
**Un**checking _Move the clock_ in _system-monitor_'s preferences solved it for me. Maybe it helps you, too.
