### ISSUE TITLE
Wrong link to repo from extensions.gnome.org

### ISSUE THREAD

**Issue by nGoline** [home-sweet-gnome/dash-to-panel#1187]
I'm trying to install Dash-to-panel from the [gnome extensions website](https://extensions.gnome.org/extension/1160/dash-to-panel/) and I'm getting an error message:

```
ImportError: No JS module 'dash-to-panel@jderose9.github.com' found in search path

Stack trace:
  installImporter@resource:///org/gnome/Shell/Extensions/js/misc/extensionUtils.js:266:5
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:199:28
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:5
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

It seems that the extension is looking for the old repo link `dash-to-panel@jderose9.github.com` and not the current one `dash-to-panel@home-sweet-gnome.github.com`

**Linux distribution and version**
Ubuntu 20.04 LTS

**GNOME Shell version**
GNOME Shell 3.36.4

**Comment by nGoline** [comment]
I was able to manually install the extension for now.

**Comment by jderose9** [comment]
dash-to-panel@jderose9.github.com is actually the extension ID on gnome extensions site which is why I haven't changed it. So it sounds like some other issue kept the extension from being downloaded or loaded properly before this error occurred.
