### ISSUE TITLE
Error loading extension in Gnome Shell 3.38.0

### ISSUE THREAD

**Issue by kaushalyap** [home-sweet-gnome/dash-to-panel#1190]
**Things to do first**
- Confirm that the problem persists when Dash-to-Panel is the only enabled extension. To do so, disable every other extension, then restart gnome-shell by running the `r` command from the prompt that appears when pressing Alt+F2 on an X.org session, or by logging out/in on a Wayland session.
- Look for Dash-to-Panel errors in your log. To do so, run the `journalctl /usr/bin/gnome-shell -f -o cat &` command and reproduce the problem.
- Search existing opened and closed issues to see if the problem has already been reported.

**Describe the bug**
Extension does not load in Gnome Shell 3.38.0

**Linux distribution and version**
Fedora 33 beta
Linux localhost.localdomain 5.8.12-300.fc33.x86_64 #1 SMP Mon Sep 28 14:04:15 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**GNOME Shell version**
Gnome Shell 3.38.0

**Dash-to-Panel version**
39

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Additional Info**

```
❯ journalctl /usr/bin/gnome-shell | grep dash-to-panel
Sep 30 17:50:37 localhost.localdomain gnome-shell[1625]: JS ERROR: Extension dash-to-panel@jderose9.github.com: TypeError: Main.overview.viewSelector.appDisplay._views is undefined
                                                         _init@/home/user/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:67:9
                                                         C@/home/user/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/utils.js line 83 > eval:1:46
                                                         _enable@/home/user/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:95:20
                                                         enable@/home/user/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:65:5
Sep 30 18:20:33 localhost.localdomain gnome-shell[8167]: JS ERROR: Extension dash-to-panel@jderose9.github.com: TypeError: Main.overview.viewSelector.appDisplay._views is undefined
                                                         _init@/home/user/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:67:9
                                                         C@/home/user/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/utils.js line 83 > eval:1:46
                                                         _enable@/home/user/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:95:20
                                                         enable@/home/user/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:65:5
Sep 30 18:30:51 localhost.localdomain gnome-shell[8167]: JS ERROR: Extension dash-to-panel@jderose9.github.com: TypeError: Main.overview.viewSelector.appDisplay._views is undefined
                                                         _init@/home/user/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:67:9
                                                         C@/home/user/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/utils.js line 83 > eval:1:46
                                                         _enable@/home/user/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:95:20
                                                         enable@/home/user/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:65:5
Oct 01 20:34:53 localhost.localdomain gnome-shell[1687]: JS ERROR: Extension dash-to-panel@jderose9.github.com: TypeError: Main.overview.viewSelector.appDisplay._views is undefined
                                                         _init@/home/user/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:67:9
                                                         C@/home/user/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/utils.js line 83 > eval:1:46
                                                         _enable@/home/user/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:95:20
                                                         enable@/home/user/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:65:5
Oct 02 05:43:09 localhost.localdomain gnome-shell[1649]: JS ERROR: Extension dash-to-panel@jderose9.github.com: TypeError: Main.overview.viewSelector.appDisplay._views is undefined
                                                         _init@/home/user/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:67:9
                                                         C@/home/user/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/utils.js line 83 > eval:1:46
                                                         _enable@/home/user/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:95:20
                                                         enable@/home/user/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:65:5
Oct 02 06:50:02 localhost.localdomain gnome-shell[1612]: JS ERROR: Extension dash-to-panel@jderose9.github.com: TypeError: Main.overview.viewSelector.appDisplay._views is undefined
                                                         _init@/home/user/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:67:9
                                                         C@/home/user/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/utils.js line 83 > eval:1:46
                                                         _enable@/home/user/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:95:20
                                                         enable@/home/user/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:65:5

```

**Comment by seebacherd** [comment]
Describe the bug
Extension does not load in Gnome Shell 3.38.0
**Linux distribution and version**
Fedora 33 beta

**GNOME Shell version**
Gnome Shell 3.38.0

**Dash-to-Panel version**
39

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

Same issue here, also getting the error `Main.overview.viewSelector.appDisplay._views is undefined` when installing the extension.


Seems to be related to issue #1188

**Comment by set-soft** [comment]
I can confirm the same is happening on Debian bullseye using Gnome Shell 3.38.0 `Main.overview.viewSelector.appDisplay._views is undefined`

```
gnome-shell[47507]: JS ERROR: Extension dash-to-panel@jderose9.github.com: TypeError: Main.overview.viewSelector.appDisplay._views is undefined
                                              _init@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:67:9
                                              C@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/utils.js line 83 > eval:1:46
                                              _enable@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:95:20
                                              enable@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:65:5
```

**Comment by jcgoble3** [comment]
Can confirm that the fix discussed in #1188 (installing git master) works perfectly. Just need someone to publish a release.

**Comment by mansoorahmedmemon** [comment]
Can confirm on Gnome 3.8.1.
Platform: Archlinux

**Comment by ladsoftware** [comment]
the same here:
OS: Arch Linux

**Comment by thomas-wach** [comment]
Sources on github already contain the fix in master branch.For arch the package maintainer just did not update the arch-package yet.Get sources from here, build and copy to original location in /usr/share/gnome-shell/extensions/das-to-panel@jderose9.github.com/That worked for me.
-------- Ursprüngliche Nachricht --------Von: ladsoftware <notifications@github.com> Datum: 07.10.20  22:37  (GMT+01:00) An: home-sweet-gnome/dash-to-panel <dash-to-panel@noreply.github.com> Cc: Thomas Wach <th.wach@wach-it-solutions.de>, Manual <manual@noreply.github.com> Betreff: Re: [home-sweet-gnome/dash-to-panel] Error loading extension in Gnome Shell 3.38.0 (#1190) 
the same here:
OS: Arch Linux

**Comment by ladsoftware** [comment]
> Sources on github already contain the fix in master branch. For arch the package maintainer just did not update the arch-package yet. Get sources from here, build (make _build) and copy to original location in /usr/share/gnome-shell/extensions/das-to-panel@jderose9.github.com/. That worked for me.

thanks it worked for me.
-clone dash-to-panel repo
-cd inside the dash-to-panel
-run: make install
-cd out with: cd ../
-move dash-to-panel folder to /usr/share/gnome-shell/extensions/:
run: mv dash-to-panel/ /usr/share/gnome-shell/extensions/
-log out and log back in

**Comment by jimmytheneutrino** [comment]
> Sources on github already contain the fix in master branch. For arch the package maintainer just did not update the arch-package yet.

It is because the arch package is based on releases, and the latest release is 39, which does not have this fix. Could the authors make a release?.

**Comment by cmrd-senya** [comment]
I just used the version from git and manually added 3.38 to the list of supported versions and it works fine, no errors for me.
I'm using Arch with latest Gnome 3.38.1.

I wonder what is the reason why authors didn't add the version 3.38 to metadata.json? Are there any blockers for 3.38 support or you just missed to update it? It seems to be working fine for me.

CC @jderose9 and @charlesg99.

**Comment by jderose9** [comment]
v40 has been tagged and submitted to extensions.gnome.org (which will be available after they review).
