### ISSUE TITLE
Inconsistent drag and drop in the taskbar

### ISSUE THREAD

**Issue by Melix19** [home-sweet-gnome/dash-to-panel#1191]
When moving apps using drag and drop in the taskbar, the icons changes position in an inconsistent way if moving from the left to right and vice versa (the same applies for the vertical taskbar). The video capture below explains it better.

**Linux distribution and version**
Arch

**GNOME Shell version**
GNOME Shell 3.36.6

**Dash-to-Panel version**
b195c13

**Where was Dash-to-Panel installed from?**
GitHub

**Screenshots / Video captures**
https://streamable.com/6go5x9

**Additional Info**
This can be fixed by removing [this](https://github.com/home-sweet-gnome/dash-to-panel/blob/b195c138146f31d039789a79362377608cc322df/taskbar.js#L963) line, but I'm not sure it this is needed for something else so I didn't make a PR.

**Comment by charlesg99** [comment]
Thanks Marco, this is now fixed on the master branch.
