### ISSUE TITLE
Dual panels

### ISSUE THREAD

**Issue by NovaViper** [home-sweet-gnome/dash-to-panel#1198]
**Describe the idea or feature you'd like**
I want to be able to add multiple panels/docks to the interface.

**Is your feature request related to a problem? Please describe.**
I used to use Dash-to-Dock but it lacks alot of features (especially when comparing to this plugin), and it's saddening seeing that plugin receiving no more updates.

**Additional context**

**Comment by jderose9** [comment]
Hi @NovaViper, I think you want to turn on this feature:
![image](https://user-images.githubusercontent.com/2118702/95523717-5d9cba80-099d-11eb-9b86-c93cf17aa465.png)

**Comment by NovaViper** [comment]
I was actually aware of this feature, however the panel isn't customizible since it is the original gnome-shell panel instead of Dash-To-Panel's
