### ISSUE TITLE
"TypeError: this._overview is undefined" on load

### ISSUE THREAD

**Issue by ackstorm23** [home-sweet-gnome/dash-to-panel#1199]
**Problem persists when Dash-to-Panel is the only enabled extension.**

- Yes
  1. removed dash-to-panel
  2. all other extensions disabled
  3. restarted gnome-shell with alt+f2 then r
  4. installed dash-to-panel via extensions.gnome.org
  5. ERROR 

**Look for Dash-to-Panel errors in your log. To do so, run the `journalctl /usr/bin/gnome-shell -f -o cat &` command and reproduce the problem.**

```
gnome-shell[442290]: JS ERROR: Extension dash-to-panel@jderose9.github.com: TypeError: this._overview is undefined
                                            get viewSelector@resource:///org/gnome/shell/ui/overview.js:158:9
                                            getAppDisplayViews@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/utils.js:307:5
                                            _init@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:67:15
                                            C@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/utils.js line 83 > eval:1:46
                                            _enable@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:95:20
                                            enable@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:65:5
                                            _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:166:32
                                            loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:348:26
                                            activate@/home/exile/.local/share/gnome-shell/extensions/extension-reloader@nls1729/extension.js:117:34
                                            vfunc_button_release_event@resource:///org/gnome/shell/ui/popupMenu.js:138:14
```

**Describe the bug**

1. Attempt to install the extension via extensions.gnome.org
2. Activation fails with "ERROR" button
3. Above systemd logs show error

**Linux distribution and version**

- Manjaro (Arch)

**GNOME Shell version**

- GNOME Shell 3.36.6

**Dash-to-Panel version**

- 39

**Where was Dash-to-Panel installed from?**

I have tried individually installing the below three methods

- The GNOME extensions website
- My distribution's package manager
- Directly from github, etc.

Each time I removed it and restarted before installing the next method

**Additional Info**

**Comment by ackstorm23** [comment]
If there is any additional information or commands/changes to script/etc I can run to help debug, just let me know.

**Comment by HpiGuillaume** [comment]
Hi!

Experiencing the exactly same with Gnome 3.38.0

`JS ERROR: Extension dash-to-panel@jderose9.github.com: TypeError: Main.overview.viewSelector.appDisplay._views is undefined#012_init@/home/[...]/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:67:9#012C@/home/[...]/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/utils.js line 83 > eval:1:46#012_enable@/home/[...]/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:95:20#012enable@/home/`...

**Comment by ackstorm23** [comment]
> Hi!
> 
> Experiencing the exactly same with Gnome 3.38.0

"TypeError: Main.overview.viewSelector.appDisplay._views is undefined" and "TypeError: this._overview is undefined" are NOT exactly the same error. 

There is already a bug for your error on 3.38 in another open issue, please remove this comment to avoid confusion.

**Comment by ackstorm23** [comment]
Found the problem.  I was running in Gnome Classic mode. 

Switching back to regular mode re-enabled this extension.
