### ISSUE TITLE
Time does not update when dash-to-panel in hiding state

### ISSUE THREAD

**Issue by colben** [home-sweet-gnome/dash-to-panel#1206]
# ENV
- Archlinux with gnome: latest
- dash-to-panel installed by pacman: latest

# ISSUE
- Dash-to-panel does not update time when it is hidden.

**Comment by regzon** [comment]
The same issue. OS: Debian Testing. Dash-to-panel installed from the source code (master branch).

**Comment by qifei9** [comment]
same issue here.

**Comment by qifei9** [comment]
same issue here.

**Comment by charlesg99** [comment]
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2973

**Comment by ByteEnable** [comment]
A work-around was posted in the issue above:

As stated above, the issue should be resolved in 3.38.2, but you need to wait for your distro to provide this. In the meantime, if you enable "Show seconds" in gnome-tweaks, the issue will be resolved.

**Comment by crivaronicolini** [comment]
I have the same problem, but with de battery percentage instead.

**Comment by regzon** [comment]
For Debian Testing and Arch Linux the issue is resolved (with a `gnome-shell` update).

**Comment by jderose9** [comment]
I’ll close this since it’s resolved upstream.
