### ISSUE TITLE
Latest update breaks GNOME Extensions install on 20.04

### ISSUE THREAD

**Issue by whoiscoos** [home-sweet-gnome/dash-to-panel#1207]
Installing the latest update through GNOME Extensions causes installation error on 20.04.

![Screenshot from 2020-10-09 11-41-33](https://user-images.githubusercontent.com/52762083/95615015-0c510180-0a57-11eb-9449-856cb8386340.png)

**Comment by MathSteve22** [comment]
Similar error is occurring when trying to update the extension on Arch Linux

**Comment by lrogoff** [comment]
I concur.

Error is
`syslog:Oct  9 14:01:14 omelette gnome-shell[2230]: JS ERROR: Extension dash-to-panel@jderose9.github.com: Error: A different version was loaded previously. You need to log out for changes to take effect.#012loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:341:52#012callback@resource:///org/gnome/shell/ui/extensionDownloader.js:234:39#012gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13`

Guys, just do Alt+F2, type "r" and Enter. That will reload Gnome.
Or reboot, or logout/login.

**Comment by Levidant** [comment]
I tried reloading Gnome and Rebooting and I still have the same problem. I remember encountering this exact same scenario a few months ago and to solve it I had to install an old version.

**Comment by omelettedufromagee** [comment]
I also did an apt update/upgrade before, to make sure I have the latest gnome-tweaks

**Comment by IlyesBenarroum** [comment]
Same Problem With PopOs was working fine but after updating is broken

**Comment by Zyonin** [comment]
Had the same issue, reloading Gnome Shell fixed it however.   Still it is an issue that should be addressed as less experienced users will be confused and thus the reputation of Dash to Dock could suffer.

**Comment by zashme** [comment]
same problem on Fedora 32 with gnome-shell 3.36.6-1

**Comment by WouterWidgets** [comment]
Reloading Gnome did not fix the issue for me.
I end up with an empty black bar at the bottom of my screen.

**Comment by TheBudda** [comment]
Same problem on a fresh installation of Ubuntu 20.04.1 . Install from https://extensions.gnome.org, red error. So I  tried;
git clone https://github.com/home-sweet-gnome/dash-to-panel.git
make install

All went well, but still does not work! Still a red error at (extensions.gnome.org) dash to panel does not work!

**Comment by WouterWidgets** [comment]
I eventually fixed it by downloading the latest version from GitHub.
That didn't work at first, but apparently enabling the extension somehow still tried to activate the older version instead of the one I downloaded.

**Comment by joellgarcia** [comment]
> I concur.
> 
> Error is `syslog:Oct 9 14:01:14 omelette gnome-shell[2230]: JS ERROR: Extension dash-to-panel@jderose9.github.com: Error: A different version was loaded previously. You need to log out for changes to take effect.#012loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:341:52#012callback@resource:///org/gnome/shell/ui/extensionDownloader.js:234:39#012gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13`
> 
> Guys, just do Alt+F2, type "r" and Enter. That will reload Gnome. Or reboot, or logout/login.

Thanks, that works for me on Ubuntu 20.04.
