### ISSUE TITLE
Show apps as text instead of icons

### ISSUE THREAD

**Issue by H4kt** [home-sweet-gnome/dash-to-panel#1208]
First of all this might be a duplicate, but I haven't found any requests, nor I found a way to do that.
As the title says I'd like to show all the apps (favorite & running) just as their name
Here is a screenshot for better understanding:
![image](https://user-images.githubusercontent.com/50774419/95680899-80211480-0be5-11eb-939c-462b21884d01.png)

Basically I want apps to show like 'Applications' does, just the label.

**Comment by kleinHeiti** [comment]
I don't know if you are looking for this, but in the settings you will find an option to display the text.
![Bildschirmfoto vom 2021-03-15 10-08-55](https://user-images.githubusercontent.com/54942072/111130296-58105580-8577-11eb-9dce-b784ebf1b5a8.png)
![Bildschirmfoto vom 2021-03-15 10-08-30](https://user-images.githubusercontent.com/54942072/111130321-5c3c7300-8577-11eb-9883-7ecb0fefa530.png)
