### ISSUE TITLE
Size of the panel in dual monitor with different scales

### ISSUE THREAD

**Issue by arxcruz** [home-sweet-gnome/dash-to-panel#1210]
**Describe the bug**
If you have two monitors, one is 4k and the other one is 2k, and on the 4k monitor you set the scale to 200% while the 2k monitor remains in 100%, the size of the panel in the 2k monitor is scaled to 200 as well.

**Linux distribution and version**
Fedora Silverblue 33

**GNOME Shell version**
GNOME Shell 3.38.1

**Dash-to-Panel version**
Version 40

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Additional Info**
I'm using wayland.

**Comment by marksvc** [comment]
Different settings for each panels' size/thickness (in #1114 ) may be a stopgap until this is more directly addressed.
