### ISSUE TITLE
Collapse right box items into an arrow menu

### ISSUE THREAD

**Issue by PopeRigby** [home-sweet-gnome/dash-to-panel#1212]
**Describe the idea or feature you'd like**
The icons in the right box should collapse into a menu that has an arrow icon. The arrow should point upward when the icons are collapsed, and clicking on the arrow should point it downward and show all the icons in a menu.

**Is your feature request related to a problem? Please describe.**
The right box becomes very cluttered when lots of apps are using the system tray.

**Additional context**
It should behave similar to KDE's system tray widget: https://userbase.kde.org/Plasma/SystemTray

**Comment by jderose9** [comment]
Hi @PopeRigby !

Please see this issue: #438

**Comment by PopeRigby** [comment]
Ah, thanks. I was only searching for right box and didn't see that issue.
