### ISSUE TITLE
Main panel keeps moving to external monitor

### ISSUE THREAD

**Issue by ngoonee** [home-sweet-gnome/dash-to-panel#1215]
**Describe the bug**
I set my main panel to appear on my primary monitor (from the 'Position' tab in Dash to Panel's settings. This is on a laptop, and the setting stays through reboots, as long as I have not unplugged the external monitor.

If I use the laptop without my external monitor, the next time I use the external monitor the main panel switches to Monitor 2 instead.

**Linux distribution and version**
Arch

**GNOME Shell version**
3.38.1

**Dash-to-Panel version**
version: 40

**Where was Dash-to-Panel installed from?**
The GNOME extensions website. When installed from AUR I observed the same behaviour

**Screenshots / Video captures**

**Additional Info**
I actually see this as two (or three) issues. One is that Dash to Panel is not remembering the setting (I can see how this would happen when monitors disappear and reappear). Another is that it seems the default is to put the main panel on Monitor 2 (primary monitor should always be the default IMHO, and related is that Dash to Panel does not follow the primary monitor setting that the user provides (I think I've read this is very difficult for some technical backend reason[1])

[1] - https://github.com/home-sweet-gnome/dash-to-panel/issues/551

**Comment by fatalhare** [comment]
I have the same issue, and same setup as OP, using Wayland.

I've also noticed that it sometimes (not always) defaults back to monitor 2 when I change the resolution and scaling on the primary monitor. This usually happens when I have to switch from 3840x2160 to 1920x1080 on my laptop (for compatibility reasons when screen sharing in zoom).

**Comment by heldchen** [comment]
I experience the same: 3 screens (notebook + external monitor 1 + external monitor 2), setting set to "Primary screen" with all 3 screens connected, notebook is primary. closing the notebook screen has ubuntu set monitor 1 as the primary monitor, but Dash to Panel toggles the setting to "Monitor 2" and shows the main panel on the wrong screen, monitor 2. 

and like @fatalhare I'm also having this problem when the same number but different external screens are used (home vs office).

**Comment by mboudreau** [comment]
I have the same issue that's been bothering me.  I'm using popos 20.04 with wayland on my laptop that has a dock.  When I dock the laptop with my external screen, the setting for dash to panel changes from "primary monitor" to "monitor 2" which is the external screen, while I want it to _always_ be the primary monitor, no matter if it's docked or not.

Love this extension and want to thank you for creating and keeping it up to date.  Happy to help solve this myself if you can point me in the right direction.

**Comment by zclandry** [comment]
I am also having the same problem.  Every  time I reconnect to one of two external monitors the panel moves to Monitor 2.  I am running Debian Testing using Wayland.

**Comment by ngoonee** [comment]
Does this bug need further info or triaging?

**Comment by pegelf** [comment]
I think this bug is a simple labeling issue. The title of the monitor which is currently the primary monitor gets renamed to "primary monitor" while the other ones are kept being the second and third monitor. If the primary monitor still would be named "Monitor 1" then this function wouldn't be confusing for us.

So in my opinion, the name of the current monitor shouldn't be replaced but expanded (like "Monitor 1 (current primary)").

Also for me this bug report is a feature request which I agree with. It would be great to have a config "primary monitor" which will always be applied to the monitor which currently is the primary, even when you attach different screens to your computer.

**Comment by heldchen** [comment]
it should be the monitor the OS sets as primary, and just follow that when the os monitor configuration changes (i.e. when docking/undocking, adding new monitor etc) - which is what I as a user expect from the current wording in the Dash-to-Panel settings...

**Comment by mboudreau** [comment]
Literally just had this issue 15 minutes ago.  Docked my computer and the panel moved to my external monitor instead of staying on my primary, which is the option I _always_ use.

This is not a stale issue if the developer just doesn't fix it...

**Comment by ngoonee** [comment]
Well, it's stale enough that I no longer use dash-to-panel (or Gnome). Not sure if github issues allow me to transfer the issue to one of the other users here experiencing this problem?

**Comment by fatalhare** [comment]
Issue is persisting for me as well. Currently using latest Dash to Panel and Gnome 40.

**Comment by mboudreau** [comment]
Not stale, just still not fixed.  Maybe I'll have to create a PR for this :/

**Comment by mboudreau** [comment]
:facepalm:

**Comment by kasappeal** [comment]
Same here :wave:

**Comment by daniel-tp** [comment]
I switch the input of my main monitor a lot between ubuntu and another pc, which causes this issue when I go back to Ubuntu

**Comment by zclandry** [comment]
Alright.  It looks as if this issue is persisting.  How would I go about contributing to what looks to be an open source project and fixing this myself? I'm mainly asking the package maintainer here.

**Comment by criptoluiz** [comment]
hey guys, just came here trying to look for a fix. This seems to happen to me randomly, and the issue is temporally solved by going to dash-to-panel settings and setting the panel to appear on monitor 1 again.

**Comment by tagirb** [comment]
Still happening on a regular basis

**Comment by notklaatu** [comment]
This is also an issue for me. There seems to be no way to force this to be persistent.

**Comment by rodonile** [comment]
Happens to me as well, it is indeed quite annoying (Fedora 36, Gnome 42)

**Comment by MasterJubei** [comment]
Same issue here, would love to see it fixed.

**Comment by rodonile** [comment]
> Same issue here, would love to see it fixed.
> 
> Ubuntu 22.04, Dash to Panel 50 Gnome verison 42.2 Wayland

Refer to the issue I reopened. It should be fixed in the main branch, however the fix is not yet on the last version. You're gonna have to wait till the next version or compile directly from source.

**Comment by heldchen** [comment]
> Refer to the issue I reopened. It should be fixed in the main branch, however the fix is not yet on the last version. You're gonna have to wait till the next version or compile directly from source.

the upcoming version fixes it for me. thank you, this is great!
