### ISSUE TITLE
Add ability to minimize an application to the tray

### ISSUE THREAD

**Issue by JayBeeDe** [home-sweet-gnome/dash-to-panel#1216]
There are already existing tools such as kdocker or gnome extensions such as [gnome shell minimize to tray](https://github.com/oae/gnome-shell-minimize-to-tray) which have this minimize to tray feature.
Nevertheless they have their limitations and especially when comes the integration with dash to panel.

[gnome shell minimize to tray](https://github.com/oae/gnome-shell-minimize-to-tray) is working great on Ubuntu 20 but can only display its tray icons on the primary monitor (or not at all if area is disabled in dash to panel setttings). The main problem is that it's not possible to have this tray icons on the secondary monitor. This limitation is not related to dash to panel.

This is why it would be so easier to have this minimize to tray feature implemented within dash to panel without the need to use an external tool/extensions and the problems that come with its integration.

**Comment by guoqiyi** [comment]
Doesn't 'show running applicatione' option do a smillar function ? The difference is it shows app in panel bar not in the tray

**Comment by JayBeeDe** [comment]
Yes I see but this is a different feature. Tray like the tray icons area in the windows taskbar at the bottom right.

**Comment by JayBeeDe** [comment]
@charlesg99 this feature will be very appreciated because the [gnome-shell-minimize-to-tray](https://github.com/oae/gnome-shell-minimize-to-tray) gnome extension project has been abandoned (repo archived) and is not working anymore under ubuntu 22.04) .
Unfortunately I don't know anything about js/typescript, so I cannot help.
But what "just" need to be done is adding another settings menu where user can pick up a list of applications that will minimize to tray (little icons in dash to panel's right area) instead of in the task bar.
