### ISSUE TITLE
Since gnome 3.38 Windows on Overview not centered and systemd log keep show warning

### ISSUE THREAD

**Issue by guoqiyi** [home-sweet-gnome/dash-to-panel#1217]
**Things to do first**
- Confirm that the problem persists when Dash-to-Panel is the only enabled extension. To do so, disable every other extension, then restart gnome-shell by running the `r` command from the prompt that appears when pressing Alt+F2 on an X.org session, or by logging out/in on a Wayland session.
- Look for Dash-to-Panel errors in your log. To do so, run the `journalctl /usr/bin/gnome-shell -f -o cat &` command and reproduce the problem.
- Search existing opened and closed issues to see if the problem has already been reported.

**Describe the bug**
 Windows on Overview not centered because worksapce allways take a whitespace on right and system log keep showing warning like this:
Oct 21 00:39:29 nvme gnome-shell[564]: Can't update stage views actor StWidget is on because it needs an allocation.
Oct 21 00:39:29 nvme gnome-shell[564]: Can't update stage views actor StWidget is on because it needs an allocation.
Oct 21 00:39:29 nvme gnome-shell[564]: Can't update stage views actor StWidget is on because it needs an allocation.
Oct 21 00:39:29 nvme gnome-shell[564]: Can't update stage views actor StWidget is on because it needs an allocation.
Oct 21 00:39:29 nvme gnome-shell[564]: Can't update stage views actor StWidget is on because it needs an allocation.
Oct 21 00:39:29 nvme gnome-shell[564]: Can't update stage views actor StWidget is on because it needs an allocation.
Oct 21 00:39:29 nvme gnome-shell[564]: Can't update stage views actor StWidget is on because it needs an allocation.
Oct 21 00:39:29 nvme gnome-shell[564]: Can't update stage views actor StWidget is on because it needs an allocation.
Oct 21 00:39:29 nvme gnome-shell[564]: Can't update stage views actor StWidget is on because it needs an allocation.
Oct 21 00:39:30 nvme gnome-shell[564]: Can't update stage views actor StWidget is on because it needs an allocation.
Oct 21 00:39:30 nvme gnome-shell[564]: Can't update stage views actor StWidget is on because it needs an allocation.
Oct 21 00:39:30 nvme gnome-shell[564]: Can't update stage views actor StWidget is on because it needs an allocation.
Oct 21 00:39:30 nvme gnome-shell[564]: Can't update stage views actor StWidget is on because it needs an allocation.
Oct 21 00:39:30 nvme gnome-shell[564]: Can't update stage views actor StWidget is on because it needs an allocation.
Oct 21 00:39:30 nvme gnome-shell[564]: Can't update stage views actor StWidget is on because it needs an allocation.

**Linux distribution and version**
Archlinux
**GNOME Shell version**
3.38.1
**Dash-to-Panel version**
40
**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
If applicable, add screenshots or a link to a video capture to help explain your problem.

**Additional Info**

**Comment by charlesg99** [comment]
see #1211 and #1213
