### ISSUE TITLE
Panel Intellihide not work in Fedora 33 beta with Gnome 3.38.1

### ISSUE THREAD

**Issue by dbasinge** [home-sweet-gnome/dash-to-panel#1218]
Panel Intellihide not work in Fedora 33 beta with Gnome 3.38.1. It will hide, but does not reveal with pressure.

**Comment by guoxiao** [comment]
Same issue. If "Only hide the panel when it's obstructed by windows" is enabled and we have a maximized window, the panel doesn't reveal, only flashes and hide again.

**Comment by charlesg99** [comment]
Working fine for me on 3.38.2, is this still happening? Did you try after disabling your other extensions/restart gnome-shell? Thanks!
