### ISSUE TITLE
Crashes a lot on my setup

### ISSUE THREAD

**Issue by HclX** [home-sweet-gnome/dash-to-panel#1219]
**Things to do first**
- Confirm that the problem persists when Dash-to-Panel is the only enabled extension. To do so, disable every other extension, then restart gnome-shell by running the `r` command from the prompt that appears when pressing Alt+F2 on an X.org session, or by logging out/in on a Wayland session. 

[Me]: Confirmed

- Look for Dash-to-Panel errors in your log. To do so, run the `journalctl /usr/bin/gnome-shell -f -o cat &` command and reproduce the problem. 

[Me]: Unfortunately the crash happens when the computer is not in use, and I can't reproduce it on demand. I attached logs which I think is related from journalctl anyway

- Search existing opened and closed issues to see if the problem has already been reported.
[Me]: Not sure this one, will search later.

**Describe the bug**
A clear and concise description of what the problem is, any steps to reproduce, and what you expected to happen instead.

[Me]: I have a laptop (Lenovo x1c running a corporate linux based on Debian). The laptop is connected to an external monitor through USB-C, and that monitor connects a 3rd monitor over DisplayPort daisy chain. The symptom of the issue is basically the taskbar is found disappeared after I wake up my computer after leaving it for a while.

**Linux distribution and version**
Ubuntu 18.04, Fedora 31, Manjaro 19.02, Arch, Debian 10.3, openSUSE Leap 15.1, etc.
[Me]: Mine is a corporate customized version of Debian, not sure which version.

**GNOME Shell version**
Run `gnome-shell --version` from the command line to get this
[Me]: GNOME Shell 3.36.5

**Dash-to-Panel version**
This can be seen in the Dash-to-Panel Settings in the About tab.
[Me]: 40

**Where was Dash-to-Panel installed from?**
The GNOME extensions website, GNOME Software store, your distribution's package manager, pre-installed with the distribution, directly from github, etc.
[Me]: The GNOME extensions website

**Screenshots / Video captures**
If applicable, add screenshots or a link to a video capture to help explain your problem.
N/A

**Additional Info**
[dash_to_panel_crash.log](https://github.com/home-sweet-gnome/dash-to-panel/files/5448993/dash_to_panel_crash.log)

**Comment by charlesg99** [comment]
Hello, try to disable all of your other extensions, then restart gnome-shell. If the problem persists then, there should be a relevant log. Thanks!
