### ISSUE TITLE
window peek disappears too quickly

### ISSUE THREAD

**Issue by howudodat** [home-sweet-gnome/dash-to-panel#1220]
On my desktop when I hover on the window preview tile it temporarily raises the window and stays raised until I move my mouse
On my laptop when I hover on the window preview tile it raises the window for about a second or so and then lowers it again.

Both are running ubuntu 20.04.  Is there a setting somewhere that controls this behaviour?

**Comment by charlesg99** [comment]
I can't reproduce this, the peek should stay active until you move the mouse out of the preview.

**Things to do first**
- Confirm that the problem persists when Dash-to-Panel is the only enabled extension. To do so, disable every other extension, then restart gnome-shell by running the `r` command from the prompt that appears when pressing Alt+F2 on an X.org session, or by logging out/in on a Wayland session.
- Look for Dash-to-Panel errors in your log. To do so, run the `journalctl /usr/bin/gnome-shell -f -o cat &` command and reproduce the problem.
- Search existing opened and closed issues to see if the problem has already been reported.

**Linux distribution and version**
Ubuntu 18.04, Fedora 31, Manjaro 19.02, Arch, Debian 10.3, openSUSE Leap 15.1, etc.

**GNOME Shell version**
Run `gnome-shell --version` from the command line to get this

**Dash-to-Panel version**
This can be seen in the Dash-to-Panel Settings in the About tab.

**Where was Dash-to-Panel installed from?**
The GNOME extensions website, GNOME Software store, your distribution's package manager, pre-installed with the distribution, directly from github, etc.

**Screenshots / Video captures**
If applicable, add screenshots or a link to a video capture to help explain your problem.

**Additional Info**

Thanks!

**Comment by howudodat** [comment]
Distro: Ubuntu 20.04, Linux laptop 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
gnome-shell: GNOME Shell 3.36.4
Extension installed from gnome website

Disabled all extensions and reloaded the shell.  In the video below you can see my console window pre-peek.  I peek twice, once on just the icon, the 2nd time on the preview window.  Both times the window disappears a second or two later.  No errors shown in the log.

On my desktop which same OS/shell and extensions the peek function works as expected.

https://user-images.githubusercontent.com/3333605/103367145-3247da00-4a79-11eb-9761-34edd063a7d0.mp4

**Comment by charlesg99** [comment]
Why does your cursor disappears when you leave it on the icon the first time?

**Comment by howudodat** [comment]
> Why does your cursor disappear when you leave it idle?

After a bit of research, i found unclutter was running on my laptop but not my desktop.  I dont necessarily need unclutter running so I have disabled it, but it might be a good idea to see if there is a way to work along side unclutter

**Comment by charlesg99** [comment]
The whole previews behavior (as many in gnome-shell) relies on hover events provided by gnome-shell (Mutter). Seems like Unclutter doesn't only visually hide the cursor but removes it entirely (sending "hover out" events) so the hover detection can't function properly. Since Unclutter works at the system level (above Mutter), there is no way for us to detect this. Thanks!
