### ISSUE TITLE
Ability to close multiple windows by middle mouse click (on icon)

### ISSUE THREAD

**Issue by ShrirajHegde** [home-sweet-gnome/dash-to-panel#1222]
**Describe the idea or feature you'd like**
Ability to clone application by middle-clicking the icon on the taskbar (not just the preview)

**Is your feature request related to a problem? Please describe.**
I would like to be able to close too many windows of different applications on taskbar once I am done with them

**Comment by ArjunSingh99** [comment]
How will a user know which window is to be closed? Remember the order in which it was opened? I don't think that sounds very viable and user friendly. I think the current feature of being able to close windows by middle clicking on the window preview is sufficient and intuitive.

**Comment by ShrirajHegde** [comment]
I mean I open 6-7 pdf on Okular and I want to close it all.. some stuff like that with too many windows to close at once.

Like we have an option to enable this. Like ability to close with or without looking at the preview. Preview animation takes some time.
