### ISSUE TITLE
Left box and right box only visible on primary monitor

### ISSUE THREAD

**Issue by Lilalas** [home-sweet-gnome/dash-to-panel#1223]
**Things to do first**
- I disables all other extension to confirm that this problem is not caused by any other extension.
- I did not observe anything interesting using the `journalctl /usr/bin/gnome-shell -f -o cat &` command.
- This issue could be related to #794, but that one has a different intention.

**Describe the bug**
You can choose what elements shall appear on the panel the Position tab in the extension settings. Disable "Apply changes to all monitors" and select the monitor that is not chosen above under "Display the main panel on". You will have exactly the same options to enable/disable elements as for the other monitor. However, toggling the visibility of the "Left box" and the "Right box" has no effect; they will stay invisible.

I am interpreting this as a bug and not as an intended limitation, because the GUI has these options, so they should also have an effect.

**Linux distribution and version**
Ubuntu 20.04.

**GNOME Shell version**
GNOME Shell 3.36.4

**Dash-to-Panel version**
40.

**Where was Dash-to-Panel installed from?**
The GNOME extensions website.

**Additional Info**
I would like to have the left box on my left monitor and the right box on my right monitor. However, I can currently only set both of these elements to appear on the same monitor.

**Comment by charlesg99** [comment]
Please see #1235. Thanks!
