### ISSUE TITLE
Extreme Glitching in Ubuntu 20.10

### ISSUE THREAD

**Issue by user85475485** [home-sweet-gnome/dash-to-panel#1224]
![signal-2020-11-08-163620](https://user-images.githubusercontent.com/64977518/98830832-25284a80-243b-11eb-9c10-b2d40430d1a2.jpeg)
![signal-2020-11-08-164241](https://user-images.githubusercontent.com/64977518/98830838-26597780-243b-11eb-898a-96e9a96a92a3.jpeg)

Gnome randomely crashes/ glitches
Also happends on a clean boot

Im running
Ubuntu 20.10
Gnome 3.38.1
Dash to Pannel version 40 from gnome extensions website
I5 4460 
intel hd graphics 4600 with the i915 driver
8gb ram
in 20.04 they were no issues
sorry for bad english
everything updated

Log:

Can't update stage views actor StDrawingArea is on because it needs an allocation.
Can't update stage views actor StWidget is on because it needs an allocation.
Can't update stage views actor StWidget is on because it needs an allocation.
Can't update stage views actor Gjs_dash-to-panel_jderose9_github_com_utils_DashToPanel_TaskbarAppIcon is on because it needs an allocation.
Can't update stage views actor Gjs_ui_dash_DashItemContainer is on because it needs an allocation.
Can't update stage views actor StBoxLayout is on because it needs an allocation.
Can't update stage views actor dashtopanelScrollview is on because it needs an allocation.
Can't update stage views actor dashtopanelTaskbar is on because it needs an allocation.
Can't update stage views actor StBin is on because it needs an allocation.
Can't update stage views actor panel is on because it needs an allocation.
Can't update stage views actor Gjs_dash-to-panel_jderose9_github_com_utils_DashToPanel-Panel is on because it needs an allocation.
Can't update stage views actor panelBox is on because it needs an allocation.
Can't update stage views actor ClutterActor is on because it needs an allocation.
Can't update stage views actor StDrawingArea is on because it needs an allocation.
Can't update stage views actor StWidget is on because it needs an allocation.
Can't update stage views actor StWidget is on because it needs an allocation.
Can't update stage views actor Gjs_dash-to-panel_jderose9_github_com_utils_DashToPanel_TaskbarAppIcon is on because it needs an allocation.
Can't update stage views actor Gjs_ui_dash_DashItemContainer is on because it needs an allocation.
Can't update stage views actor StBoxLayout is on because it needs an allocation.
Can't update stage views actor dashtopanelScrollview is on because it needs an allocation.
Can't update stage views actor dashtopanelTaskbar is on because it needs an allocation.
Can't update stage views actor StBin is on because it needs an allocation.
Can't update stage views actor panel is on because it needs an allocation.
Can't update stage views actor Gjs_dash-to-panel_jderose9_github_com_utils_DashToPanel-Panel is on because it needs an allocation.
Can't update stage views actor panelBox is on because it needs an allocation.
Can't update stage views actor ClutterActor is on because it needs an allocation.
Can't update stage views actor StDrawingArea is on because it needs an allocation.
Can't update stage views actor StWidget is on because it needs an allocation.
Can't update stage views actor StWidget is on because it needs an allocation.
Can't update stage views actor Gjs_dash-to-panel_jderose9_github_com_utils_DashToPanel_TaskbarAppIcon is on because it needs an allocation.
Can't update stage views actor Gjs_ui_dash_DashItemContainer is on because it needs an allocation.
Can't update stage views actor StBoxLayout is on because it needs an allocation.
Can't update stage views actor dashtopanelScrollview is on because it needs an allocation.
Can't update stage views actor dashtopanelTaskbar is on because it needs an allocation.
Can't update stage views actor StBin is on because it needs an allocation.
Can't update stage views actor panel is on because it needs an allocation.
Can't update stage views actor Gjs_dash-to-panel_jderose9_github_com_utils_DashToPanel-Panel is on because it needs an allocation.
Can't update stage views actor panelBox is on because it needs an allocation.
Can't update stage views actor ClutterActor is on because it needs an allocation.
Can't update stage views actor StDrawingArea is on because it needs an allocation.
Can't update stage views actor StWidget is on because it needs an allocation.
Can't update stage views actor StWidget is on because it needs an allocation.
Can't update stage views actor Gjs_dash-to-panel_jderose9_github_com_utils_DashToPanel_TaskbarAppIcon is on because it needs an allocation.
Can't update stage views actor Gjs_ui_dash_DashItemContainer is on because it needs an allocation.
Can't update stage views actor StBoxLayout is on because it needs an allocation.
Can't update stage views actor dashtopanelScrollview is on because it needs an allocation.
Can't update stage views actor dashtopanelTaskbar is on because it needs an allocation.
Can't update stage views actor StBin is on because it needs an allocation.
Can't update stage views actor panel is on because it needs an allocation.
Can't update stage views actor Gjs_dash-to-panel_jderose9_github_com_utils_DashToPanel-Panel is on because it needs an allocation.
Can't update stage views actor panelBox is on because it needs an allocation.
Can't update stage views actor ClutterActor is on because it needs an allocation.
Can't update stage views actor StDrawingArea is on because it needs an allocation.
Can't update stage views actor StWidget is on because it needs an allocation.
Can't update stage views actor StWidget is on because it needs an allocation.
Can't update stage views actor Gjs_dash-to-panel_jderose9_github_com_utils_DashToPanel_TaskbarAppIcon is on because it needs an allocation.
Can't update stage views actor Gjs_ui_dash_DashItemContainer is on because it needs an allocation.
Can't update stage views actor StBoxLayout is on because it needs an allocation.
Can't update stage views actor dashtopanelScrollview is on because it needs an allocation.
Can't update stage views actor dashtopanelTaskbar is on because it needs an allocation.
Can't update stage views actor StBin is on because it needs an allocation.
Can't update stage views actor panel is on because it needs an allocation.
Can't update stage views actor Gjs_dash-to-panel_jderose9_github_com_utils_DashToPanel-Panel is on because it needs an allocation.
Can't update stage views actor panelBox is on because it needs an allocation.
Can't update stage views actor ClutterActor is on because it needs an allocation.
Can't update stage views actor StDrawingArea is on because it needs an allocation.
Can't update stage views actor StWidget is on because it needs an allocation.
Can't update stage views actor StWidget is on because it needs an allocation.
Can't update stage views actor Gjs_dash-to-panel_jderose9_github_com_utils_DashToPanel_TaskbarAppIcon is on because it needs an allocation.
Can't update stage views actor Gjs_ui_dash_DashItemContainer is on because it needs an allocation.
Can't update stage views actor StBoxLayout is on because it needs an allocation.
Can't update stage views actor dashtopanelScrollview is on because it needs an allocation.
Can't update stage views actor dashtopanelTaskbar is on because it needs an allocation.
Can't update stage views actor StBin is on because it needs an allocation.
Can't update stage views actor panel is on because it needs an allocation.
Can't update stage views actor Gjs_dash-to-panel_jderose9_github_com_utils_DashToPanel-Panel is on because it needs an allocation.
Can't update stage views actor panelBox is on because it needs an allocation.
Can't update stage views actor ClutterActor is on because it needs an allocation.
Can't update stage views actor StDrawingArea is on because it needs an allocation.
Can't update stage views actor StWidget is on because it needs an allocation.
Can't update stage views actor StWidget is on because it needs an allocation.
Can't update stage views actor Gjs_dash-to-panel_jderose9_github_com_utils_DashToPanel_TaskbarAppIcon is on because it needs an allocation.
Can't update stage views actor Gjs_ui_dash_DashItemContainer is on because it needs an allocation.
Can't update stage views actor StBoxLayout is on because it needs an allocation.
Can't update stage views actor dashtopanelScrollview is on because it needs an allocation.
Can't update stage views actor dashtopanelTaskbar is on because it needs an allocation.
Can't update stage views actor StBin is on because it needs an allocation.
Can't update stage views actor panel is on because it needs an allocation.
Can't update stage views actor Gjs_dash-to-panel_jderose9_github_com_utils_DashToPanel-Panel is on because it needs an allocation.
Can't update stage views actor panelBox is on because it needs an allocation.
Can't update stage views actor ClutterActor is on because it needs an allocation.
Can't update stage views actor StDrawingArea is on because it needs an allocation.
Can't update stage views actor StWidget is on because it needs an allocation.
Can't update stage views actor StWidget is on because it needs an allocation.
Can't update stage views actor Gjs_dash-to-panel_jderose9_github_com_utils_DashToPanel_TaskbarAppIcon is on because it needs an allocation.
Can't update stage views actor Gjs_ui_dash_DashItemContainer is on because it needs an allocation.
Can't update stage views actor StBoxLayout is on because it needs an allocation.
Can't update stage views actor dashtopanelScrollview is on because it needs an allocation.
Can't update stage views actor dashtopanelTaskbar is on because it needs an allocation.
Can't update stage views actor StBin is on because it needs an allocation.
Can't update stage views actor panel is on because it needs an allocation.

**Comment by Spurlos** [comment]
Seen same glitches on secondary screen, thought it was something wrong with HDMI.
Also seeing same logs output.
Don't know if its related - but i'm experiencing stutters in interface, noticeable when playing videos or dragging windows fast.
```
Nov 21 03:34:54 spurlos-ThinkPad-E580 gnome-shell[4088]: Can't update stage views actor Gjs_ui_appDisplay_AppIcon is on because it needs an allocation.
Nov 21 03:34:54 spurlos-ThinkPad-E580 gnome-shell[4088]: Can't update stage views actor StWidget is on because it needs an allocation.
Nov 21 03:34:54 spurlos-ThinkPad-E580 gnome-shell[4088]: Can't update stage views actor Gjs_ui_iconGrid_BaseIcon is on because it needs an allocation.
Nov 21 03:34:54 spurlos-ThinkPad-E580 gnome-shell[4088]: Can't update stage views actor StBoxLayout is on because it needs an allocation.
Nov 21 03:34:54 spurlos-ThinkPad-E580 gnome-shell[4088]: Can't update stage views actor StBin is on because it needs an allocation.
Nov 21 03:34:54 spurlos-ThinkPad-E580 gnome-shell[4088]: Can't update stage views actor StIcon is on because it needs an allocation.
Nov 21 03:34:54 spurlos-ThinkPad-E580 gnome-shell[4088]: Can't update stage views actor ClutterActor is on because it needs an allocation.
Nov 21 03:34:54 spurlos-ThinkPad-E580 gnome-shell[4088]: Can't update stage views actor StLabel is on because it needs an allocation.
Nov 21 03:34:54 spurlos-ThinkPad-E580 gnome-shell[4088]: Can't update stage views actor ClutterText is on because it needs an allocation.
Nov 21 03:34:54 spurlos-ThinkPad-E580 gnome-shell[4088]: Can't update stage views actor Gjs_ui_appDisplay_AppIcon is on because it needs an allocation.
Nov 21 03:34:54 spurlos-ThinkPad-E580 gnome-shell[4088]: Can't update stage views actor StWidget is on because it needs an allocation.
Nov 21 03:34:54 spurlos-ThinkPad-E580 gnome-shell[4088]: Can't update stage views actor Gjs_ui_iconGrid_BaseIcon is on because it needs an allocation.
Nov 21 03:34:54 spurlos-ThinkPad-E580 gnome-shell[4088]: Can't update stage views actor StBoxLayout is on because it needs an allocation.
Nov 21 03:34:54 spurlos-ThinkPad-E580 gnome-shell[4088]: Can't update stage views actor StBin is on because it needs an allocation.
Nov 21 03:34:54 spurlos-ThinkPad-E580 gnome-shell[4088]: Can't update stage views actor StIcon is on because it needs an allocation.
Nov 21 03:34:54 spurlos-ThinkPad-E580 gnome-shell[4088]: Can't update stage views actor ClutterActor is on because it needs an allocation.
Nov 21 03:34:54 spurlos-ThinkPad-E580 gnome-shell[4088]: Can't update stage views actor StLabel is on because it needs an allocation.
Nov 21 03:34:54 spurlos-ThinkPad-E580 gnome-shell[4088]: Can't update stage views actor ClutterText is on because it needs an allocation.
Nov 21 03:34:54 spurlos-ThinkPad-E580 gnome-shell[4088]: Can't update stage views actor Gjs_ui_appDisplay_SystemActionIcon is on because it needs an allocation.
Nov 21 03:34:54 spurlos-ThinkPad-E580 gnome-shell[4088]: Can't update stage views actor StBin is on because it needs an allocation.
Nov 21 03:34:54 spurlos-ThinkPad-E580 gnome-shell[4088]: Can't update stage views actor Gjs_ui_iconGrid_BaseIcon is on because it needs an allocation.
Nov 21 03:34:54 spurlos-ThinkPad-E580 gnome-shell[4088]: Can't update stage views actor StBoxLayout is on because it needs an allocation.
Nov 21 03:34:54 spurlos-ThinkPad-E580 gnome-shell[4088]: Can't update stage views actor StBin is on because it needs an allocation.
Nov 21 03:34:54 spurlos-ThinkPad-E580 gnome-shell[4088]: Can't update stage views actor StIcon is on because it needs an allocation.
Nov 21 03:34:54 spurlos-ThinkPad-E580 gnome-shell[4088]: Can't update stage views actor ClutterActor is on because it needs an allocation.
Nov 21 03:34:54 spurlos-ThinkPad-E580 gnome-shell[4088]: Can't update stage views actor StLabel is on because it needs an allocation.
Nov 21 03:34:54 spurlos-ThinkPad-E580 gnome-shell[4088]: Can't update stage views actor ClutterText is on because it needs an allocation.
Nov 21 03:34:54 spurlos-ThinkPad-E580 gnome-shell[4088]: Can't update stage views actor Gjs_ui_appDisplay_SystemActionIcon is on because it needs an allocation.
Nov 21 03:34:54 spurlos-ThinkPad-E580 gnome-shell[4088]: Can't update stage views actor StBin is on because it needs an allocation.
Nov 21 03:34:54 spurlos-ThinkPad-E580 gnome-shell[4088]: Can't update stage views actor Gjs_ui_iconGrid_BaseIcon is on because it needs an allocation.
Nov 21 03:34:54 spurlos-ThinkPad-E580 gnome-shell[4088]: Can't update stage views actor StBoxLayout is on because it needs an allocation.
Nov 21 03:34:54 spurlos-ThinkPad-E580 gnome-shell[4088]: Can't update stage views actor StBin is on because it needs an allocation.
Nov 21 03:34:54 spurlos-ThinkPad-E580 gnome-shell[4088]: Can't update stage views actor StIcon is on because it needs an allocation.
Nov 21 03:34:54 spurlos-ThinkPad-E580 gnome-shell[4088]: Can't update stage views actor ClutterActor is on because it needs an allocation.
Nov 21 03:34:54 spurlos-ThinkPad-E580 gnome-shell[4088]: Can't update stage views actor StLabel is on because it needs an allocation.
Nov 21 03:34:54 spurlos-ThinkPad-E580 gnome-shell[4088]: Can't update stage views actor ClutterText is on because it needs an allocation.
```

**Comment by sharyar** [comment]
Same issue on Pop OS 20.10

**Comment by charlesg99** [comment]
Does this also happens without the extension? Probably. I've never encountered this and can't think of a reason why the extension would corrupt the display like this. Also the logs are only warnings that have been fixed on the master branch. Thanks!
