### ISSUE TITLE
Problem with starting

### ISSUE THREAD

**Issue by MichalWerszner** [home-sweet-gnome/dash-to-panel#1231]
**Things to do first**
Disabled and the problem persists

**Describe the bug**
The first installation on a clean system was successful. Then I wanted to make the desktop more like Windows windows using https://raw.githubusercontent.com/bill-mavromatis/gnome-layout-manager/master/layoutmanager.sh
Of course it didn't work, and from then on I can't run dash-to-pabel

`TypeError: panelElementPositionsSettings is null

Stack trace:
  _displayPanelPositionsForMonitor@/home/mwr/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/prefs.js:272:37
  wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
  _updateVerticalRelatedOptions@/home/mwr/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/prefs.js:208:14
  wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
  _bindSettings@/home/mwr/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/prefs.js:728:14
  wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
  _init@/home/mwr/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/prefs.js:189:14
  wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
  _Base.prototype._construct@resource:///org/gnome/gjs/modules/script/_legacy.js:18:10
  newClass@resource:///org/gnome/gjs/modules/script/_legacy.js:114:21
  buildPrefsWidget@/home/mwr/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/prefs.js:2192:20
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17`

**Linux distribution and version**
Fedora 33 with running Wayland and Xorg desktop

**GNOME Shell version**
GNOME Shell 3.38.1

**Dash-to-Panel version**
40

**Where was Dash-to-Panel installed from?**
Installed from GNOME extensions website

**Screenshots / Video captures**
![Zrzut ekranu z 2020-11-21 17-21-03](https://user-images.githubusercontent.com/44341870/99882385-5b767e80-2c20-11eb-89b6-674e79ee8cfd.png)
![Zrzut ekranu z 2020-11-21 17-16-18](https://user-images.githubusercontent.com/44341870/99882386-5ca7ab80-2c20-11eb-9fe4-db3f8c54e3ff.png)
![Zrzut ekranu z 2020-11-21 17-15-40](https://user-images.githubusercontent.com/44341870/99882388-5dd8d880-2c20-11eb-81ed-a7aab95c3d6a.png)

**Additional Info**

**Comment by charlesg99** [comment]
Please reinstall and restart gnome-shell afterwards. Thanks!
