### ISSUE TITLE
"Show desktop" button causes apps to become invisible and it's hard to get them back!

### ISSUE THREAD

**Issue by williamd5** [home-sweet-gnome/dash-to-panel#1234]
**Describe the bug**
When you click the "show desktop" button and while it's shown if you try to open an app, it causes that app to open, but be invisible. Clicking again "show desktop" (as to show back all open windows), the app you tried bringing up is still transparent, and it's hard to get it back unless you restart it.

**Linux distribution and version**
Ubuntu 20.04 LTS

**GNOME Shell version**
3.36.4

**Dash-to-Panel version**
40

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
Will submit a video as a comment as soon as I can record it.

**Additional Info**
Steps to reproduce:
1. Open a couple of apps
2. Click "Show desktop"
3. From the panel, try bringing up one of the apps you already have open. It will be invisible.
4. Click "show desktop" again; now your other app will show up, but the one you clicked will remain invisible

Fix suggestion:
Instead of making apps invisible, consider the following approach:
- Click on show desktop button
    - are windows open?
        - yes: minimise all windows (and remember which they are)
        - no: check if there are windows that have been remembered as minimised via "show desktop" and unminimize them, otherwise unminimize all windows

**Comment by ParaSpl01t** [comment]
This bug only appears when "Hover to reveal desktop" option is enabled in "show desktop settings".
If you click before the hover delay, It works as expected. But if you click after hover delay, all windows get stuck on minimize/invisible.

**Comment by williamd5** [comment]
I can confirm I have that setting enabled. I see now what must be happening because of the hover, which makes windows invisible. Clicking the button before the hover delay minimises the apps as expected.

Disabling the "Hover to reveal desktop" option resolves the issue, as expected.

**Comment by charlesg99** [comment]
This is now fixed on the master branch. Thanks for the report!
