### ISSUE TITLE
Same panel on multiple monitors

### ISSUE THREAD

**Issue by benneti** [home-sweet-gnome/dash-to-panel#1235]
**Describe the idea or feature you'd like**
It would be nice to have an option to have the same panel on all monitors.
Right now (at least for me, latest version from extensions.gnome.org) status icons, and other extension symbols and options are only visible on the panel of the primary monitor.

**Is your feature request related to a problem? Please describe.**
Probably also related to clock override not being aplied on secondary panel, as all extensions seem to be ignored there, see https://github.com/home-sweet-gnome/dash-to-panel/issues/863#issuecomment-732722661.

**Comment by williamd5** [comment]
This is definitely possible. I have version 40 from the extensions website, and I have my panel the same on all monitors. I believe this is a setting, will post a follow-up comment with screenshots.

**Comment by williamd5** [comment]
![Screenshot from 2020-11-19 10-58-18](https://user-images.githubusercontent.com/66572326/100221285-21a7bf80-2f21-11eb-8ad9-f2d4f368462d.png)
![image](https://user-images.githubusercontent.com/66572326/100221299-266c7380-2f21-11eb-9962-6397921d6a8a.png)

**Comment by williamd5** [comment]
![image](https://user-images.githubusercontent.com/66572326/100221477-65022e00-2f21-11eb-95dd-783cc857d4be.png)

**Comment by benneti** [comment]
I use this, too. But if you look you see that the indicator items are not replicated, the same is true for all extensions I use (Workspace Indicator, Clock Override, Caffeine, and GSConnect).

**Comment by williamd5** [comment]
The screenshot above is of the panel on my two monitors.
The activities button is replicated, the favourite apps and the date menu, system menu, desktop button, etc.
I have the option "Isolate workspaces" and "Isolate windows" enabled, which shows open applications for the current workspace/monitor (this is from the behaviour) page. 
![image](https://user-images.githubusercontent.com/66572326/100230202-14450200-2f2e-11eb-89a5-f7d42063b540.png)
If I disable this, I see all open apps on every monitor or workspace.

I don't entirely understand what you described, but it is indeed plausible to be a bug or overall missing that feature.

**Comment by benneti** [comment]
Right now my primary dock looks like this
![Screenshot from 2020-11-25 14-08-16](https://user-images.githubusercontent.com/11725645/100231739-bad9d480-2f27-11eb-8175-66fa6463a0ac.png)
and the secondary dock like
![Screenshot from 2020-11-25 14-08-06](https://user-images.githubusercontent.com/11725645/100231735-b9101100-2f27-11eb-90e0-1fd868e253c1.png)
I would like both of them to look and behave the same as well as have the same content (including extensions, compare the symbols on the right).

**Comment by charlesg99** [comment]
This is something that was discussed before and unfortunately we can't duplicate every other extensions that add items to the main panel, this responsibility belongs to them (as an example, Arc-Menu integrated its menu on all panels). Thanks!

**Comment by oviniciusfeitosa** [comment]
> Right now my primary dock looks like this ![Screenshot from 2020-11-25 14-08-16](https://user-images.githubusercontent.com/11725645/100231739-bad9d480-2f27-11eb-8175-66fa6463a0ac.png) and the secondary dock like ![Screenshot from 2020-11-25 14-08-06](https://user-images.githubusercontent.com/11725645/100231735-b9101100-2f27-11eb-90e0-1fd868e253c1.png) I would like both of them to look and behave the same as well as have the same content (including extensions, compare the symbols on the right).

Same issue here.
