### ISSUE TITLE
Missing panel after unlock gnome shell > 3.38.1

### ISSUE THREAD

**Issue by ehatari** [home-sweet-gnome/dash-to-panel#1236]
Describe:
After playing a video in full screen (Netflix) using a web browser such as Firefox and then locking and unlocking the gnome using a hotkey and exiting the video from full screen the bar is missing.

Reproduction:
1. Open Web browser (i tested in Firefox and Vivaldi)
2. Open Netflix and play some video
3. Make video FullScreen
4. Lock gnome like Win+L
5. Unlock gnome 
6. Exit FullScreen

After Reproduction steps dash panel missing:
![after_unlock](https://user-images.githubusercontent.com/11526124/100281010-68210c80-2f69-11eb-8c4b-3e2228a7e16e.png)

Should be like this:
![should be](https://user-images.githubusercontent.com/11526124/100281039-7707bf00-2f69-11eb-9a19-b0de5130e2c4.png)

To bring back i need make restart gnome shell

Linux distribution:
Fedora 33

GNOME Shell version:
GNOME Shell 3.38.1-3

Dash-to-Panel version:
I tested in master and V40

Where was Dash-to-Panel installed from?
V40 from gnome extension portal
Master from github to verify bug

**Comment by Terryvanderjagt** [comment]
Same problem here on Arch Linux with Gnome Shell version 1:3.38.2-1 and V40 of the extension

**Comment by lumarel** [comment]
I'm having the exact same problem with any application which triggers the fullscreen-mode on Fedora 33 / GNOME Shell 3.38.2-1 / Extension V40.
Another way to get the panel back is to disable/re-enable the extension.

**Comment by ehatari** [comment]
I wonder if this is the dash panel fault or the gnome-shell fault ?

**Comment by ehatari** [comment]
After update gnome-shell to version 3.38.2-2 on the fedora 33 work using xorg. But dont work w Weyland

**Comment by ehatari** [comment]
@ Terryvanderjagt  what version gnome-shell is in the arch and do you can check this issue ?

**Comment by lumarel** [comment]
> 
> 
> After update gnome-shell to version 3.38.2-2 on the fedora 33 work using xorg. But dont work w Weyland

I can't confirm that, even after the update to 3.38.2-2 this behavior persists.

**Comment by Terryvanderjagt** [comment]
@ehatari On arch I'm on gnome-shell version 1:3.38.2+17+gf63812b0d-1 and I still have this problem. I'm using Xorg

**Comment by KaikiasVind** [comment]
I'm on debian gnome 3.38.2 and can confirm this problem appears every time the system suspends or locks the screen when in fullscreen.

**Comment by ehatari** [comment]
@lumarel i check again and  confirm this issue

**Comment by nailfarmer** [comment]
I've encountered this as well on debian gnome 3.38.2 under wayland. It seems to be tied to using a gnome-shell theme other than default / adwaita.  I've tried switching from an older custom theme to the Plano theme from the git master branch which has been updated for 3.38, hoping this would solve the problem, but the behaviour persists.

**Comment by ehatari** [comment]
Hi, i can confirm this bug  exist with set custom shell theme. With standard theme **adwaita** everything work.

**Comment by Hemlock** [comment]
I'm seeing it in 3.38.3 under X11 even with default theme. Emits the error message `this.monitor is null`.

**Comment by ehatari** [comment]
@Hemlock  how you debug this ?

**Comment by Hemlock** [comment]
@ehatari I used looking glass. alt+f2 > lg > extensions > show errors under dash to panel. It doesn't show much, just the message, but it is a start.

**Comment by ehatari** [comment]
I use looking glass and I don't see any issue.

**Comment by songyunli** [comment]
Got this issue on Debian Bullseye Gnome 3.38.4 + Dash to Panel v40

**Comment by ironclad-chomskyan** [comment]
Can confirm that this is happening, and replicable (by launching a video player, going full screen, then locking and unlocking the screen) in Pop OS (20.10) running kernel 5.11.0-7614-generic, and gnome-shell version 3.38.3. The same screenshots provided by OP is applicable here.

**Comment by Razer0123** [comment]
Happening also to me, gnome 40

**Comment by sparkchaser** [comment]
I'm seeing the same behavior, although I got there a slightly different way (fullscreen video in browser -> lose power forcing reboot -> no bar once the system comes back up).  I'm using:

 - Extension v42 from the website
 - gnome-shell 3.36.9
 - Ubuntu 20.04, kernel 5.4.0-84

Here's the stacktrace I'm seeing in my syslog:

```
JS ERROR: Extension dash-to-panel@jderose9.github.com:
TypeError: this.monitor is null 
#012getPosition@/home/me/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panel.js:539:24
#012_init@/home/me/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panel.js:119:29
#012_createPanel@/home/me/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:417:17
#012enable@/home/me/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:82:34
#012_enable@/home/me/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:96:18
#012enable@/home/me/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:65:5
#012_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
#012loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:351:26
#012_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:601:18
#012collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
#012_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:576:19
#012_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:610:18
#012_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:641:18
#012init@resource:///org/gnome/shell/ui/extensionSystem.js:56:14
#012_initializeUI@resource:///org/gnome/shell/ui/main.js:257:22
#012start@resource:///org/gnome/shell/ui/main.js:146:5
#012@<main>:1:47
```

**Comment by hynet-mel** [comment]
I can also report having the same issue whenever  I leave YouTube play full-screen and my session locks automatically

**Comment by lumarel** [comment]
I tried once again with fedora 35 / wayland / GNOME 41 / version from master, looks like it got fixed!
