### ISSUE TITLE
Lock Taskbar to Desktop permanently

### ISSUE THREAD

**Issue by floboehmi** [home-sweet-gnome/dash-to-panel#1238]
Hi,
I have only started using Linux yesterday. I chose Zorin for a distribution. When I restart my computer, the dash to panel disappears. How do I lock it to start permanently. Other than that I find it very user friendly. Thank you for your help.
floboehmi

**Comment by charlesg99** [comment]
Hello, how do you bring the panel back when it "disappears"?
