### ISSUE TITLE
Color or transparency

### ISSUE THREAD

**Issue by LMJulianS** [home-sweet-gnome/dash-to-panel#124]
I would like the option to change the color of the Panel or turn on transparency. I know there are other extensions which can do it, put Dash to Dock includes this option as well. 

Further more it would be cool to get a color from the Desktop Background and automatically set the Panel Color. Which, when Dash to Panel is used with BackSlide for example, would end in a similar feature as Win10 has, where the Ascent Color changes with changing background.

**Comment by jderose9** [comment]
Hi! Thanks for sharing your ideas. I agree that setting panel color and transparency is important, but [Dynamic Panel Transparency](https://extensions.gnome.org/extension/1011/dynamic-panel-transparency) currently supports those things (except for auto-matching the wallpaper). That extension works well with this one at the moment, so I don't see much reason to re-implement that here as it would just take time away from other features. Dynamic Panel Transparency seems to have motivated maintainer/contributors that can focus on providing a large number of panel color/transparency options, and keeping them working as expected when a new gnome version is released.

Dash-to-Dock does have these features built in, but it draws its own panel so Dynamic Panel Transparency does not work with it.

**Comment by jderose9** [comment]
Reopening as dynamic panel transparency will likely cease to work as-is when multi monitor support is added.

**Comment by charlesg99** [comment]
Hi, I just added some color/opacity options for the panels on branch "feature-multimon" (see #35 for more detail). Please let us know if this solve the issue. Thanks!

**Comment by charlesg99** [comment]
Hi, this feature was merged to master and gives you the possibility to customize the color and opacity of the panel. Please open a new issue if you encounter problems with it. Thanks!

**Comment by charlesg99** [comment]
Hello @glats, the new opacity features aren't yet released on extensions.gnome.org. If you want to try them now, you can do so by [installing the latest development version](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github) from github. Thanks!

**Comment by nexus-jk** [comment]
Hi @charlesg99, Don't suppose you've got a rough ETA for release to extensions.gnome.org for this feature? presumably after the pull request gets merged to master?
Thanks!

**Comment by charlesg99** [comment]
Hi @nexus-jk, we are aiming for a holiday season release. Might be off a bit if the e.g.o. review process is longer, but on our side we'll be tagging v17 in the next few days. Thanks!
