### ISSUE TITLE
Hide Java invisible windows

### ISSUE THREAD

**Issue by DanielRios549** [home-sweet-gnome/dash-to-panel#1240]
**Describe the bug**
It is showing multiple windows from Java apps that has invisible windows.

**Linux distribution and version**
Pop!_OS 20.04

**GNOME Shell version**
3.36.4

**Dash-to-Panel version**
40

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
![image](https://user-images.githubusercontent.com/11152535/101716920-1013fb00-3a7d-11eb-94cf-006a37eb8e42.png)

**Additional Info**
These windows are used to present the lyrics, videos, images and so on, the program itself has only one window that should appear, the last in the print.

**Comment by charlesg99** [comment]
You'll need to report this issue to the java app developpers so they can set the correct StartupWMClass. See #1247, thanks!

**Comment by DanielRios549** [comment]
How can I check what is the StartupWMClass for each of these windows? On KDE this is easier to do, on Gnome I don't know how to do

**Comment by charlesg99** [comment]
> How can I check what is the StartupWMClass for each of these windows

1. <kbd>Alt</kbd> + <kbd>f2</kbd>, type 'lg' then press <kbd>Enter</kbd>
2. Click on `Windows` on the upper right of the looking glass window
3. Find your window in the list and see its `wmclass`, that's the value you want to set for StartupWMClass in the .desktop file

**Comment by DanielRios549** [comment]
To appear only the main window, I need to set only the wmclass of the main window, right?
