### ISSUE TITLE
Feature missed

### ISSUE THREAD

**Issue by Faetu** [home-sweet-gnome/dash-to-panel#1243]
**Things to do first**
- Confirm that the problem persists when Dash-to-Panel is the only enabled extension. To do so, disable every other extension, then restart gnome-shell by running the `r` command from the prompt that appears when pressing Alt+F2 on an X.org session, or by logging out/in on a Wayland session. -> **Done**
- Look for Dash-to-Panel errors in your log. To do so, run the `journalctl /usr/bin/gnome-shell -f -o cat &` command and reproducee the problem. -> **Done**
- Search existing opened and closed issues to see if the problem has already been reported. -> **Done**

**Describe the bug**
It seems that I missed the feature to ungroup apps.
![image](https://user-images.githubusercontent.com/55803495/102206379-cb4cf180-3ecc-11eb-9144-a7f97ab7becd.png)

**Linux distribution and version**
Linux Arch 5.9.13-arch1-1

**GNOME Shell version**
GNOME Shell 3.38.2

**Dash-to-Panel version**
69

**Where was Dash-to-Panel installed from?**
The GNOME extensions website and i also try it from AUR.

**Screenshots / Video captures**
See screenshot above, pls.

**Additional Info**

**Comment by abakkk** [comment]
The screenshot you show is not v69 preferences. Remove all dash-to-panel AUR packages.

**Comment by Faetu** [comment]
omg.. this is so embarrassing! I'm sorry.
