### ISSUE TITLE
Missing Indicator on Firfox Developer and Nightly

### ISSUE THREAD

**Issue by TheGrandFinale2001** [home-sweet-gnome/dash-to-panel#1244]
**Describe the bug**
When I run programs like Firefox Developer or Firefox Nightly there doesn't appear to be an indicator for them.  These programs were installed by downloading the tar file and extracting them and then run them.  I've installed Firefox Beta and Firefox ESR in the same manner but do not have issues with them.

**Linux distribution and version**
Arch Linux

**GNOME Shell version**
GNOME Shell 3.38.1

**Dash-to-Panel version**
version: 40

**Where was Dash-to-Panel installed from?**
AUR

**Screenshots / Video captures**
![Dash_to_Panel01](https://user-images.githubusercontent.com/18177104/102422181-2fa6a880-3fd4-11eb-83b2-97bdc87379a6.png)

**Additional Info**

**Comment by charlesg99** [comment]
Hello, Firefox developer is working fine for me: 

![image](https://user-images.githubusercontent.com/33044886/103415196-13b41280-4b4f-11eb-9510-be0cc4e88bb7.png)

Do you have the same result if you disable "Indicator color - Icon Dominant"?

![image](https://user-images.githubusercontent.com/33044886/103415226-35ad9500-4b4f-11eb-8872-0c89d6ae58a1.png)

![image](https://user-images.githubusercontent.com/33044886/103415246-4e1daf80-4b4f-11eb-9629-1c9797e191a5.png)

**Comment by TheGrandFinale2001** [comment]
So after doing what you said it looks like it works, but not at first.  When I first launch Firefox Developer there is no indicator but after toggling the switch the indicator appears.

**Comment by charlesg99** [comment]
Which icon set is that? Seems like there is an issue with the main color detection of this icon.

**Comment by TheGrandFinale2001** [comment]
I using Papirus.
