### ISSUE TITLE
Extension suddenly stopped working

### ISSUE THREAD

**Issue by btaiii** [home-sweet-gnome/dash-to-panel#1246]
**Describe the bug**
The extension worked until today, but suddenly stopped working for me.  I have uninstalled and reinstalled to no avail.

**Linux distribution and version**
$ lsb_release -a
Distributor ID:	Pop
Description:	Pop!_OS 20.10
Release:	20.10
Codename:	groovy

**GNOME Shell version**
GNOME Shell 3.38.2

**Dash-to-Panel version**
Version 40

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
https://user-images.githubusercontent.com/5440294/102838988-197a5d00-43c5-11eb-8e04-d563d25c6186.mp4

**Additional Info**
No errors in Looking Glass
![Screenshot from 2020-12-21 19-47-30](https://user-images.githubusercontent.com/5440294/102839165-7d9d2100-43c5-11eb-87d8-2e3f50644022.png)

**Comment by philippun1** [comment]
Can confirm this on Ubuntu 20.10 as well. Both the packaged version and the one from gnome extension website no longer work.

**Comment by charlesg99** [comment]
Working fine for me, please follow the normal troubleshooting steps and report back:

- Confirm that the problem persists when Dash-to-Panel is the only enabled extension. To do so, disable every other extension, then restart gnome-shell by running the `r` command from the prompt that appears when pressing Alt+F2 on an X.org session, or by logging out/in on a Wayland session.
- Look for Dash-to-Panel errors in your log. To do so, run the `journalctl /usr/bin/gnome-shell -f -o cat &` command and reproduce the problem.
- Search existing opened and closed issues to see if the problem has already been reported.

**Comment by btaiii** [comment]
Yes the problem occurs when Dash-to-Panel is the only enabled extension, and I restart Gnome.
When I run ` journalctl /usr/bin/gnome-shell -f -o cat &` I get the following:

    Can't update stage views actor overviewGroup is on because it needs an allocation.
    Can't update stage views actor overview is on because it needs an allocation.
    Can't update stage views actor Gjs_ui_overviewControls_ControlsManager is on because it needs an allocation.
    Can't update stage views actor overview-group is on because it needs an allocation.
    Can't update stage views actor Gjs_ui_overviewControls_ThumbnailsSlider is on because it needs an allocation.
    Can't update stage views actor Gjs_ui_workspaceThumbnail_ThumbnailsBox is on because it needs an allocation.
    Can't update stage views actor Gjs_ui_workspaceThumbnail_WorkspaceThumbnail is on because it needs an allocation.
    Can't update stage views actor ClutterActor is on because it needs an allocation.
    Can't update stage views actor Gjs_ui_workspaceThumbnail_WindowClone is on because it needs an allocation.

No new errors appear when I install and activate dash-to-panel.

I can't find this problem in the issues list.

**Comment by philippun1** [comment]
I found the reason why it didn't work for me. In dconf /org/gnome/shell/extensions/ disable-user-extensions was set to true. I have no idea why that was the case. I just found this by accident, because I wanted to reset the dash-to-panel dconf tree. @btaiii maybe this will is the case for you as well?

**Comment by btaiii** [comment]
Oh wow.  Fantastic!  I didn't even know this setting existed.  It must have gotten set to false during one of the updates, because I never changed it.

I really like this extension, so I'm very glad to have it working again.
Thanks @philippun1!
