### ISSUE TITLE
Missing icon for custom application

### ISSUE THREAD

**Issue by fabricio7p** [home-sweet-gnome/dash-to-panel#1247]
Hello.

I'm having issue displaying suckless ST icon in dash to panel, let me explain.

I have created a st.desktop file so i can launch ST from gnome app menu which does work fine.
Here it is: 
```[Desktop Entry]
Type=Application
Name=Suckless ST
Comment=simple-terminal emulator for X
Icon=org.gnome.Shell.Extensions.GSConnect
Exec=st -g 140x40
Categories=System;TerminalEmulator
```
![image](https://user-images.githubusercontent.com/46208058/102898164-ddd4a700-4447-11eb-9a20-203efad52293.png)

But inside dash to panel no matter which icon i pick, it will be blank.

![image](https://user-images.githubusercontent.com/46208058/102898275-0a88be80-4448-11eb-93fd-1c66a6a93cbb.png)

Is this expected behavior? what can i do?
Thanks in advance

**Comment by charlesg99** [comment]
Hello, you'll need to set the StartupWMClass property in the desktop file. You can find the needed value using the looking glass. See [theses issues](https://github.com/home-sweet-gnome/dash-to-panel/issues?q=is%3Aissue+StartupWMClass) for more info. Thanks!
