### ISSUE TITLE
dash-to-panel settings gui: Show Apps Animation (animate-show-apps) setting not shown anymore

### ISSUE THREAD

**Issue by ToxicDragon** [home-sweet-gnome/dash-to-panel#1249]
**Things to do first**
Done

**Describe the bug**
The "animate-show-apps" switch is not visible in dash-to-panel settings gui anymore, although the setting is available e.g. in dconf editor (/org/gnome/shell/extensions/dash-to-panel/animate-show-apps). Due to the fact that this switch seemed to be available in previous releases, I was not able to return to the default behaviour since the switch apparently (or am I not seeing it anymore?) is missing in the current release (40). I was only able to reset this switch in e.g. dconf editor (which worked flawlessly).

Therefore, in order to have consistent behaviour to previous releases, it would be great if you included this setting in the dash-to-panel settings gui again in one of your future releases.

**Linux distribution and version**
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.10
Release:	20.10
Codename:	groovy

**GNOME Shell version**
gnome-shell --version
GNOME Shell 3.38.1

**Dash-to-Panel version**
40

**Where was Dash-to-Panel installed from?**
Directly from github (master branch)

**Screenshots / Video captures**
![image](https://user-images.githubusercontent.com/3375142/103279436-0de2f380-49ce-11eb-8f94-8991f3f7905a.png)
![image](https://user-images.githubusercontent.com/3375142/103279459-1fc49680-49ce-11eb-8df7-a846c717e151.png)

**Comment by charlesg99** [comment]
Hello, this setting was relocated in this dialog:

![image](https://user-images.githubusercontent.com/33044886/103353205-3e7e6800-4a76-11eb-89bc-189bb934dd42.png)

![image](https://user-images.githubusercontent.com/33044886/103353222-51913800-4a76-11eb-86e6-b914f43f4b79.png)

Thanks!

**Comment by ToxicDragon** [comment]
Oh, thank you for pointing that out!
