### ISSUE TITLE
Export settings as JSON

### ISSUE THREAD

**Issue by euh2** [home-sweet-gnome/dash-to-panel#1251]
**Idea**
Have the option to save settings. That would make it possible to share settings across desktops or even bundle them with a Gnome Theme.

**Additional context**
I haven't looked into the details. I imagine settings are stored in some type of Gnome Storage under ~/. Ideally the settings would be available as json for easy programmatically access. The file/s could then be shared or bundled. 

(If no one implements this, I will. But probably not before summer 2022)

**Comment by charlesg99** [comment]
![image](https://user-images.githubusercontent.com/33044886/103463736-975f3200-4cfc-11eb-9e7a-b042c79c30cd.png)

**Comment by euh2** [comment]
Apparantly I'm blind!
