### ISSUE TITLE
How to hide windows titles

### ISSUE THREAD

**Issue by myounus96** [home-sweet-gnome/dash-to-panel#1253]
Hi there, Thanks for this great extension, is there any way to hide windows titles?
For example in below picture I opened the postman application but I just wanna see the postman icon not the window title, how can I hide this?
![image](https://user-images.githubusercontent.com/13608139/103476945-bc76a200-4ddb-11eb-82a9-d02f15af580e.png)

**Comment by charlesg99** [comment]
Hello, to group applications (and remove window titles):

![image](https://user-images.githubusercontent.com/33044886/103479454-b2cd4a00-4d9b-11eb-8d21-1c0780e94f71.png)



To keep applications ungrouped, but remove window titles, set their width to 0:

![image](https://user-images.githubusercontent.com/33044886/103479487-f45df500-4d9b-11eb-8edf-ef6c7727401a.png)
![image](https://user-images.githubusercontent.com/33044886/103479490-ffb12080-4d9b-11eb-8289-51cb4f16fdb8.png)




Thanks!
