### ISSUE TITLE
Graphical bug when using panel intellihide

### ISSUE THREAD

**Issue by ArjunSingh99** [home-sweet-gnome/dash-to-panel#1255]
**Things to do first**
Confirmed that the problem persists even when Dash to Panel is the only enabled extension
**Describe the bug**
When panel intellihide is enabled, and I go to open the appmenu by hovering to the bottom and clicking on the appmenu icon, there is a graphical bug which can be seen in the video attached. This does not happen when in overview (activities) mode, as also seen in the attached video.
Also, this does not occur when panel intellihide is disabled, i.e., when it's static, non hiding.
**Linux distribution and version**
Pop!_OS 20.10

**GNOME Shell version**
GNOME Shell 3.38.2

**Dash-to-Panel version**
Version 40

**Where was Dash-to-Panel installed from?**
The GNOME extensions website.

**Screenshots / Video captures**
Video:

https://user-images.githubusercontent.com/53963483/103744886-8a0bb580-5024-11eb-9cfd-c052f518d158.mp4

**Additional Info**
GPU: Nvidia GTX 830M
Driver: Nvidia Driver 455
This bug does not occur when not using panel intellihide.

**Comment by charlesg99** [comment]
Hello, thank you for your report, this issue was introduced by gnome-shell 3.38.2 and is fixed on the master branch. Please install it or wait for the fix to be released on the gnome extensions website. Thanks!
