### ISSUE TITLE
Indicator for unread messages

### ISSUE THREAD

**Issue by stefan-kern** [home-sweet-gnome/dash-to-panel#126]
Is there a possibility to add an indicator to the app icons for unread messages? (e.g. skype)
i've only seen it used in some tray indicators (e.g. pushbullet) - is it even possible to get that status?

**Comment by jderose9** [comment]
Along the lines of #98, I'm not really sure if many applications report this in a uniform manner, but I would love to see the feature integrated.

**Comment by jderose9** [comment]
Looks like this was done for dash-to-dock and may be able to be merged in.

https://github.com/micheleg/dash-to-dock/pull/590

**Comment by stefan-kern** [comment]
Indicator support is now mentioned on the readme, so i'm wondering if this since has been implemented? It still is the one feature i would like to see the most for this plugin.

> From positioning and scaling panel elements to running **indicators** to multi-monitor display, [...]

**Comment by extremepayne** [comment]
I could be wrong but I believe the README is referring to the indication of if an app is running, not a notification-bubble-like thing.

**Comment by charlesg99** [comment]
Let's close this as it's a duplicate of the now implemented #98. Thanks!
