### ISSUE TITLE
Windows remain transparent after activation of "toggle single/preview muliple" action.

### ISSUE THREAD

**Issue by mgrewe** [home-sweet-gnome/dash-to-panel#1260]
Hi, 

I don't know exactly since when (maybe 2-3 month), I'm experiencing the following behavior:
When I have opened multiple windows of the same application (plenty of multi-window apps distributed across many workspaces) and click on the app's icon in the panel, the preview of all windows appears. If I now hover over the previews and remain for a short time, the particular window gets "highlighted" by increasing the transparency of all others. Under some circumstances that I couldn't specifically reproduce yet, these windows remained transparent even after the preview has been closed again. However, I can restore the full opaqueness of the affected windows if I open the app's preview and "highlight" them again. 

I'm not 100% sure about this but it might be that only windows in other workspaces, i.e., not in the workspace which was active when initiating the preview or the one containing the finally selected window, were affected.

I'm on current Arch with gnome 3.38.3 and use the official extension version 40, 

Cheers

**Comment by skontar** [comment]
I think I hit this or something similar today. I am not exactly sure what was the reason, but half of my windows became very transparent and I was not able to restore their opaqueness. It happened to me for the second time in two months, so not very often.

I recall that I had two windows of one application opened, so it may be the same bug. However I cannot find any pattern in which windows stayed opaque and which become transparent. 

I only used one workspace at the time.

My Gnome version is currently 3.38.1 and extensions version is 40.

**Comment by skontar** [comment]
OK, I now know how to reproduce:
1) Open two windows of the same application.
2) On the overview, highlight one of them, so the other one is transparent.
3) Hit the Super key, to open the overview.

**Comment by charlesg99** [comment]
Thanks @skontar, I could reproduce the issue. It should now be fixed on the master branch!

**Comment by mgrewe** [comment]
I can confirm that the issue has been fixed! Thanks a lot. Closing the issue. Cheers

**Comment by skontar** [comment]
Awesome. @charlesg99 thanks for your hard work!
