### ISSUE TITLE
Bot top bar and bottom

### ISSUE THREAD

**Issue by lopugit** [home-sweet-gnome/dash-to-panel#1261]
Is there a way to have the top bar and the bottom as well, where the top just has the context menu and clock/sound/power button etc.. but the bottom one has everything apps included?

**Comment by charlesg99** [comment]
![image](https://user-images.githubusercontent.com/33044886/104812680-f4191d00-57d1-11eb-9f53-f9d18538375b.png)

**Comment by lopugit** [comment]
Wow you are awesome!!!!!!!!! Geniuses
