### ISSUE TITLE
Show Application Window Flashing

### ISSUE THREAD

**Issue by brxken3301** [home-sweet-gnome/dash-to-panel#1262]
**Describe the bug**
Whenever the "Show Applications" button is pressed in the bottom-right, on the dock, the screen momentarily flashes before loading the app window correctly.

**Linux distribution and version**
pop_os! 20.10

**GNOME Shell version**
version 3.38.2

**Dash-to-Panel version**
version 40

**Where was Dash-to-Panel installed from?**
from https://extensions.gnome.org/extension/1160/dash-to-panel/

**Screenshots / Video captures**
https://streamable.com/wls8cs - here is a video of the issue

**Comment by charlesg99** [comment]
Thanks for the report, this new 3.38.2 issue is already fixed on the master branch. Please install it or wait for a new release on the gnome extensions website.
