### ISSUE TITLE
Unable to uninstall

### ISSUE THREAD

**Issue by jbagwell27** [home-sweet-gnome/dash-to-panel#1263]
**Describe the bug**
Extension will not uninstall. I'm trying to uninstall it to reset settings to default, and the settings keep coming back from somewhere. I uninstalled it from gnome-tweaks, manually deleted `~/.local/share/gnome-shell/extensions/dash-to-panel` and `/usr/share/gnome-shell/extensions/dash-to-panel`
When I reinstall it, and reboot gnome-shell, the extension installs with all of my previous settings. I am unsure where those settings are coming from.
When I uninstall it again, the top panel clears except for the far right system menu. (see attached picture below)
It appears to be only in this user-space, because my other local user has no issues.

**Linux distribution and version**
Fedora 33 | Kernel 5.10.7

**GNOME Shell version**
3.38.2 Wayland

**Dash-to-Panel version**
40

**Where was Dash-to-Panel installed from?**
I installed from both Github and GNOME.org

**Screenshots / Video captures**
![Screenshot from 2021-01-16 21-42-08](https://user-images.githubusercontent.com/53024286/104829682-13e92900-5844-11eb-828b-ebe7cb6797f7.png)

**Comment by charlesg99** [comment]
Hello, the settings are saved in dconf, so there isn't much we can do about resetting them when uninstalling. Please see the [FAQ to reset the extension settings](https://github.com/home-sweet-gnome/dash-to-panel#faq). Thanks!

**Comment by jbagwell27** [comment]
Sweet. I feel kind of dumb for not looking there first. Thank you
Joshua Bagwell
jbagwell27.github.io
