### ISSUE TITLE
subwindows of fullscreen apps don't show up at the right position

### ISSUE THREAD

**Issue by realmazharhussain** [home-sweet-gnome/dash-to-panel#1266]
When some app like VLC goes fullscreen (not maximized), it shows its content on top of the panel and it seems like the panel is hidden. But panel is just present in the background and it tries to keep any other window from taking its space (even a subwindow of fullscreen window). Since apps like VLC show some of the information in a subwindow, the subwindow shows up a little out of place.

It may not matter to most of the people but it is very annoying to me seeing something like given in the screenshot.

It would be great if you added the feature (in intellihide) to hide the panel when some app is fullscreen or let subwindows of fullscreen apps to be positioned wherever on the screen they try to position themselves. Or just make this the default behaviour.

This is the default behaviour in Windows and Cinnamon and can also be achieved in KDE.

**Reproduce the situation:**

1. Set dash-to-panel position to bottom in extenion settings
2. install VLC
3. Play a video in VLC in fullscreen mode by pressing F or double clicking on the video inside VLC
4. Move your cursor
5. A borderless subwindow appears near bottom of the screen which shows some info and controls
6. This window was supposed to appear exactly at the bottom of the screen not near it.

![Screenshot from 2021-01-20 13-00-17](https://user-images.githubusercontent.com/67191572/105144732-7f224c00-5b1f-11eb-81ce-46a49ca6021e.png)

**My setup:**

I don't think my setup matters in this kind of issue but it is following.
**OS:** Debian testing
**Gnome:** 3.38.2
**Extension:** 40

**Comment by Crucizer** [comment]
I have the same issue.
