### ISSUE TITLE
Can't install Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by mdeberts** [home-sweet-gnome/dash-to-panel#1268]
**Describe the bug**
I tried to install dash-to-panel in multiple ways without success.

**Linux distribution and version**
Ubuntu 20.04

**GNOME Shell version**
GNOME Shell 3.36.4

**Where was Dash-to-Panel installed from?**
*The GNOME extensions website - can't select  "shell version", "extension version" under downloads
*directly from github - errors:

(base) mdeberts@Labuntu:~/opt/dash-to-panel$ make install
glib-compile-schemas ./schemas/
msgfmt -c po/hu.po -o po/hu.mo
make: msgfmt: Command not found
make: *** [Makefile:58: po/hu.mo] Error 127

*GNOME-Software - not listed / found

[https://imgur.com/a/TLd2yx9](url)

**Comment by blackjackshellac** [comment]
msgfmt is part of the gettext package.

You should be able to install dash-to-panel on extensions.gnome.org

https://extensions.gnome.org/extension/1160/dash-to-panel/

**Comment by mdeberts** [comment]
Wow nice, I was looking for a solution the whole day and it's solved within minutes.
Perfect thank you very much!
