### ISSUE TITLE
Icons Size

### ISSUE THREAD

**Issue by moore-bryan** [home-sweet-gnome/dash-to-panel#1270]
When changing the size of a left-aligned panel, the icons "magnify" to fill the space resulting in comically large icons; changing the "width" of the panel should not affect the size of the icons.

**Linux distribution and version**
          /:-------------:\          bryan@zenbook 
       :-------------------::        ------------- 
     :-----------/shhOHbmp---:\      OS: Fedora 33 (Workstation Edition) x86_64 
   /-----------omMMMNNNMMD  ---:     Host: ZenBook UX425IA_UM425IA 1.0 
  :-----------sMMMMNMNMP.    ---:    Kernel: 5.10.10-200.fc33.x86_64 
 :-----------:MMMdP-------    ---\   Uptime: 52 mins 
,------------:MMMd--------    ---:   Packages: 1832 (rpm), 10 (flatpak) 
:------------:MMMd-------    .---:   Shell: bash 5.0.17 
:----    oNMMMMMMMMMNho     .----:   Resolution: 1920x1080 
:--     .+shhhMMMmhhy++   .------/   DE: GNOME 3.38.3 
:-    -------:MMMd--------------:    WM: Mutter 
:-   --------/MMMd-------------;     WM Theme: Flat-Remix-Blue-Dark-fullPanel 
:-    ------/hMMMy------------:      Theme: Qogir [GTK2/3] 
:-- :dMNdhhdNMMNo------------;       Icons: Tela [GTK2/3] 
:---:sdNMMMMNds:------------:        Terminal: gjs 
:------:://:-------------::          CPU: AMD Ryzen 7 4700U with Radeon Graphics (8) @ 2.000GHz 
:---------------------://            GPU: AMD ATI 04:00.0 Renoir 
                                     Memory: 4352MiB / 15480MiB 

**Dash-to-Panel version**
40

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
[https://web.tresorit.com/l/3WhUE#TjTVbQhIucMkSJSeJxQfHQ](url)

**Comment by moore-bryan** [comment]
I believe this is the part of the code (lines 702-749) that could be altered to allow for the icons to _not_ change size when the panel height/width is changed:
```
 _adjustIconSize: function() {
        let panelSize = Me.settings.get_int('panel-size');
        let availSize = panelSize - Me.settings.get_int('appicon-padding') * 2;
        let minIconSize = MIN_ICON_SIZE + panelSize % 2;

        if (availSize == this.iconSize)
            return;

        if (availSize < minIconSize) {
            availSize = minIconSize;
        }
        
        // For the icon size, we only consider children which are "proper"
        // icons and which are not animating out (which means they will be 
        // destroyed at the end of the animation)
        let iconChildren = this._getTaskbarIcons().concat([this._showAppsIcon]);
        let scale = this.iconSize / availSize;
        
        this.iconSize = availSize;

        for (let i = 0; i < iconChildren.length; i++) {
            let icon = iconChildren[i].child._delegate.icon;

            // Set the new size immediately, to keep the icons' sizes
            // in sync with this.iconSize
            icon.setIconSize(this.iconSize);

            // Don't animate the icon size change when the overview
            // is transitioning, or when initially filling
            // the taskbar
            if (Main.overview.animationInProgress ||
                !this._shownInitially)
                continue;

            let [targetWidth, targetHeight] = icon.icon.get_size();

            // Scale the icon's texture to the previous size and
            // tween to the new size
            icon.icon.set_size(icon.icon.width * scale, icon.icon.height * scale);

            Utils.animate(icon.icon,
                        { width: targetWidth,
                            height: targetHeight,
                            time: DASH_ANIMATION_TIME,
                            transition: 'easeOutQuad',
                        });
        }
    },
```

**Comment by charlesg99** [comment]
Hello, the icon scaling with the panel is the desired behavior. If you want to reduce the icon size on a large panel, use the "App Icon Padding" setting. This works on horizontal and vertical panels.

![image](https://user-images.githubusercontent.com/33044886/106462602-545fbe00-6464-11eb-91f2-d25e8799b808.png)

Thanks!

**Comment by moore-bryan** [comment]
Thanks, @charlesg99... For some reason that mix of settings wasn't quite working, although it's better now. I'm still wondering if this could be reopened as a feature request, then; for example, the icons could remain a specific size without the need for all the padding.

Thanks, again!
