### ISSUE TITLE
Terminal in context menu is hardcoded to gnome-terminal and not the default system terminal (x-terminal-emulator)

### ISSUE THREAD

**Issue by KushtrimPacaj** [home-sweet-gnome/dash-to-panel#1271]
**Describe the bug**
I just installed Terminator, which set itself as the default terminal ( by setting `x-terminal-emulator `to open it ). This is respected by Nautilus's` Open-in-terminal `context menu, as well as` CTRL+ALT+T.` But in this extension, the `gnome-terminal` is harcoded in the Terminal context menu, as can be seen here:

https://github.com/home-sweet-gnome/dash-to-panel/blob/5c502bcfd12e65d28f53bb8ec7c4efeba51ad5e6/appIcons.js#L1820

Should we change that line in `appIcons.js` to `x-terminal-emulator ` ?
If so, I can make a quick PR.

**Linux distribution and version**
Ubuntu 20.04.1 LTS

**GNOME Shell version**
GNOME Shell 3.36.4

**Dash-to-Panel version**
40

**Where was Dash-to-Panel installed from?**
The GNOME extensions website,

**Comment by charlesg99** [comment]
Hello, I don't think x-terminal-emulator comes default on Gnome installation, seems like a Debian thing (e.g. this command isn't available on my Arch machine). I normally just create a symlink so gnome-terminal opens Tilix instead (or whatever terminal you use). Seems to work best as other applications also use the "gnome-terminal" command. Thanks!

**Comment by KushtrimPacaj** [comment]
Thanks for the idea. This solved the problem. 

Unless you want to add distro specific code ( e.g. run x-terminal-emulator IFF it exists), we can close this issue :)
