### ISSUE TITLE
Show Application button icon

### ISSUE THREAD

**Issue by anggapw** [home-sweet-gnome/dash-to-panel#1272]
**Describe the bug**
When changing the icon in the Show Applications button options, the new icon overwrites the default icon.

**Linux distribution and version**
Fedora 33

**GNOME Shell version**
GNOME Shell 3.38.3

**Dash-to-Panel version**
v40

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
Before
https://ibb.co/Njh479G

After
https://ibb.co/qkttJKq

**Comment by charlesg99** [comment]
Hello, how did you first obtain the colored icon on the first screenshot? This isn't the default one. Is it from a theme? If so try reverting to the default theme and see if you have the same issue. Thanks!
