### ISSUE TITLE
Global keyboard shortcut Super + Q

### ISSUE THREAD

**Issue by ArjunSingh99** [home-sweet-gnome/dash-to-panel#1275]
**Things to do first**
Confirmed that the bug is only when dash to panel extension is enabled. Issue doesn't exist as far as I can see.

**Describe the bug**
Super + Q is the global keyboard shortcut to close windows.
After suspend and wake, Super + Q doesn't work to close windows. But with Dash to Panel disabled, it works.

**Linux distribution and version**
Pop!_OS 20.04 LTS x86_64 

**GNOME Shell version**
GNOME Shell 3.36.4

**Dash-to-Panel version**
Version 40

**Where was Dash-to-Panel installed from?**
The GNOME extensions website.

**Additional Info**
This bug is not there on GNOME Shell 3.38.x
I recently downgraded to Pop!_OS 20.04 due to some issues, and this was the first time I encountered this issue.

**Comment by Jack-Chou-HZ** [comment]
The bug is still there. When I press Super + Q, instead of the current window being closed, the Dock shows up.

This is a fresh installed system with all system updates installed.

Ubuntu 22.04.1 LTS x86_64
Kernel: 5.15.0-46-generic
DE: GNOME 42.2
