### ISSUE TITLE
Feature Request: Isolate Monitor

### ISSUE THREAD

**Issue by ElectricPrism** [home-sweet-gnome/dash-to-panel#128]
Essentially I have a TV as my secondary monitor and I would like my file manager and video player to not show up on my dock while I work but only when they're on the monitor with Dash to Panel.

Great work, I use this extension daily, this feature would improve my experience if you can implement it, thank you :) :+1:

**Comment by jderose9** [comment]
Thanks for submitting this! Do you use workspaces on your secondary monitor? (It's the last option on the Workspaces tab in Tweak Tool). Right now the behavior is to assume that if you do not use workspaces on a secondary monitor, that the window will appear on all workspaces, but perhaps if this would configurable it would resolve your issue?

**Comment by ElectricPrism** [comment]
I tried both Gnome Tweak Tool toggles "Workspaces only on primary display" on/off and it only made VLC appear on all workspaces and not make the monitor a seperate workspace.

With that feature (which is great because I'll be able to use workspace) if you could implement a switch to "Hide windows not on the primary monitor) - I X'd out the app icon in the screenshot below to further clarify.

![dash-to-panel-hide-when-not-on-screen-demo](https://cloud.githubusercontent.com/assets/635971/25096765/89c02af6-2356-11e7-9f13-26cafc9db6de.png)

If it's possible, I appreciate the efforts :)

**Comment by davidhiendl** [comment]
An option to only show windows on the current activity/monitor/workspace similar to DashToDock would be really great. It would make it possible to have Dash to Panel on primary monitor and DashToDock on secondary screens which essentially would fix many "multi-monitor support" issues or at least offer a acceptable solution.

**Comment by charlesg99** [comment]
This option was added to master with the multi-monitor support. Thanks!
