### ISSUE TITLE
Show Applications: icons flicker before their animated appearance

### ISSUE THREAD

**Issue by plashenkov** [home-sweet-gnome/dash-to-panel#1281]
Dash-to-Panel shares the same bug with Dash-to-Dock: https://github.com/micheleg/dash-to-dock/issues/1359

Application icons flicker for a moment before their animated appearance on the screen.

Here is the fix of this bug for Dash-to-Dock: https://github.com/micheleg/dash-to-dock/pull/1361/files
The code in Dash-to-Panel slightly differs, so I'm not sure I can suggest the exact fix.
But I hope this will be helpful.

**Linux distribution and version**
Ubuntu 20.10

**GNOME Shell version**
GNOME Shell 3.38.2

**Dash-to-Panel version**
Dash-to-Panel 40

**Where was Dash-to-Panel installed from?**
Directly from GitHub, compiled.

**Screenshots / Video captures**
Please see attached GIF here: https://github.com/micheleg/dash-to-dock/issues/1359

**Comment by appleton252** [comment]
Hello,

Sorry, a newbie here. I think I am applying the patch correctly, downloading the docking.js file and placing it in the directory as depicted and restarting the shell but the issue persists. Is there some something I am missing that I should be doing when using your fix? Thank you for your contribution.

https://www.dropbox.com/s/r48s78b3q6qo742/Screenshot%20from%202021-02-20%2021-58-08.png?dl=0

I notice when clicking activities and opening the application grid from there the flicker does not occur though!

Thank you

**Comment by plashenkov** [comment]
Hi @appleton252 
Nope, you can't directly apply this patch to Dash-to-Panel. This fix is for Dash-to-Dock, I've provided it here to help the developers find a solution to this problem in this project. Dash-to-Panel has the similar code, but it's not equal.

**Comment by appleton252** [comment]
Oh dear, my mistake.

Thank you

**Comment by plashenkov** [comment]
Hey @appleton252

Well, you can comment these three lines in taskbar.js:

![1](https://user-images.githubusercontent.com/2331932/108642930-357ba700-74b9-11eb-9371-0a66b1cd0534.png)

And then recompile and reinstall the project (make, make install).

I'm not sure this is a completely correct way of fixing this, but it works for me.

**Comment by appleton252** [comment]
Thank you for that,

I'm having difficulty compiling it has no ./configure files. What am I looking for to compile this instead?

Thank you,

**Comment by plashenkov** [comment]
I do not know about ./configure files. Here is info on how to install from source: https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github

**Comment by appleton252** [comment]
Thanks for the link. I got it working. 
Thank you @plashenkov :)

**Comment by vanrasselm** [comment]
I just updated from Ubuntu 20.04 to Ubuntu 20.10, and I believe I am experiencing the same bug now. When I click the "show applications" button, the icons appear, then quickly disappear before reappearing as their animation of "popping up" from the "show applications" button starts.

I am new to Linux, and can't seem to figure out how to use the fix that is described in this post. Getting Ubuntu installed on my machine has been tricky to say the least, so I don't want to just reinstall off USB if I don't have to.

Any help would be much appreciated. :)

**Comment by plashenkov** [comment]
Hey @vanrasselm 

You need to install Dash-to-Panel from this repo, not from the Gnome extensions website.
See here: https://github.com/home-sweet-gnome/dash-to-panel#installation

If that bug was not fixed in the current development version, then try to add these fixes manually:
https://github.com/home-sweet-gnome/dash-to-panel/issues/1281#issuecomment-782954399

If any questions, post them here, I'll try to help.

**Comment by vanrasselm** [comment]
@plashenkov 

I am an absolute newb here, so please bare with me.

This is what I have done so far.

I tried running this command

git clone https://github.com/home-sweet-gnome/dash-to-panel.git

and it gave me an error so i did this

sudo apt-get install dash-to-panel

and let it install.

I ran this command again.

git clone https://github.com/home-sweet-gnome/dash-to-panel.git

and it did some stuff.

I try to run this command

make install

and this is the output it gives me,

make: *** No rule to make target 'install'.  Stop.


I am sure that I am doing something wrong, but I can't seem to figure it out.

**Comment by plashenkov** [comment]
Well, you don't even need to `git clone`, you can simply download the repo (see the green "Code" button on the repo main page and then "Download ZIP", then extract). The result is the same as `git clone <...>`

Then you need to run `make` and `make install` (I do not know if `make install` is self-sufficient or you have to run `make` first, can't check this for now). And you need to run these commands from the folder where Makefile is located.

And maybe you need to uninstall the `apt-get` version to avoid conflicts.
