### ISSUE TITLE
Panel goes off screen for 125, 150 and 175 display scalings and bottom position 

### ISSUE THREAD

**Issue by bogdan-marian** [home-sweet-gnome/dash-to-panel#1283]
**Describe the bug**
When using bottom position the panel goes of screen when using the following display scalings: 125%, 150% and 175%

**Versions**
Ubuntu 20.04
GNOME Shell 3.36.4
Dash-to-Panel version: 40

**Where was Dash-to-Panel installed from?**
The GNOME extensions website,

**Comment by Jmennius** [comment]
I experience something similar - when I unlock the session, the panel is not visible and windows expand onto its space.
If I resize any window to miximized state - it will leave some space for the dock (transprent space).
It's hard for me to tell if it goes off-screen and I also use 100% scaling.
I can workaround it by locking and unlocking the session.

Fedora 33
GNOME Shell 3.38.3
Dash-to-panel from the repo v40-8-ge4a71fa
