### ISSUE TITLE
Glitch: Exiting activities overview moves windows to different monitor momentarily

### ISSUE THREAD

**Issue by KMouratidis** [home-sweet-gnome/dash-to-panel#1291]
**Describe the bug**
(Better if you see the attached video)
Pressing the super key brings up the activities tab, pressing it again makes some windows move temporarily to another monitor appearing as if they get minimized. This only happens with windows on the monitor with the **main panel**. 

**Linux distribution and version**
**Fedora 33**  (5.10.19-200)

**GNOME Shell version**
GNOME Shell **3.38.3**
Also: gnome-desktop3-3.38.4-1.fc33.x86_64

**Dash-to-Panel version**
Version **40**

**Where was Dash-to-Panel installed from?**
The GNOME extensions website (https://extensions.gnome.org/).

**Screenshots / Video captures**
[screen capture on imgur](https://imgur.com/a/d2lCubf)

**Additional Info**
- disaling other extensions doesn't help
- disabling D2P fixes the problem
- resolutions (left to right, 1-4): 1920x1080, 2560x1440, 1080x1920, 1080x1920 
- "primary monitor" (2, from system settings) and "main panel" monitor (3) are different
- moving the "main panel" to another monitor "fixes" the problem if there are no open windows
- displaying the "main panel" on the "primary monitor" works fine 
- `akmod-nvidia` driver **nvidia-kmod-460.56-1.fc33**, but remove + restart didn't help
- no problems on Fedora 32
- I tried turning it on and off again

`journalctl /usr/bin/gnome-shell -f -o cat &` logs:
```
Can't update stage views actor StWidget is on because it needs an allocation.
Can't update stage views actor StWidget is on because it needs an allocation.
Can't update stage views actor StWidget is on because it needs an allocation.
Can't update stage views actor StWidget is on because it needs an allocation.
Can't update stage views actor StWidget is on because it needs an allocation.
Can't update stage views actor StWidget is on because it needs an allocation.
Can't update stage views actor StWidget is on because it needs an allocation.
Can't update stage views actor StWidget is on because it needs an allocation.
Window manager warning: MetaSyncRing: Sync object is not ready -- were events handled properly?
Can't update stage views actor StWidget is on because it needs an allocation.
Can't update stage views actor StWidget is on because it needs an allocation.
Can't update stage views actor StWidget is on because it needs an allocation.
Can't update stage views actor StWidget is on because it needs an allocation.
```

Did the pre-steps, couldn't find a similar problem ( not sure what words to search for :/ )

PS: Great extension! Thanks for making Gnome usable :D

**Comment by rodneydup** [comment]
I'm having this same issue. I love this extension by the way. Great work. It's a shame that this issue makes my DM feel clunky and buggy, because otherwise this extension makes everything beautiful! If this were fixed, I think I'd finally be satisfied with my rice (lol).
