### ISSUE TITLE
Bad grouping of LibreOffice applications

### ISSUE THREAD

**Issue by oliviermarce** [home-sweet-gnome/dash-to-panel#1292]
When grouping application, Libre Office applications are all with the "LibreOffice" one, not with "LibreOffice Writer", "LibreOffice Calc", etc. 

**Linux distribution and version**
Ubuntu 20.04.2 LTS

**GNOME Shell version**
GNOME Shell 3.36.4

**Dash-to-Panel version**
40

**Where was Dash-to-Panel installed from?**
The GNOME extensions website,
![Untitled](https://user-images.githubusercontent.com/42432708/110653809-de1a4e00-81bd-11eb-979b-8676f6967c1c.png)

**Screenshots / Video captures**
See attached, Calc and Writer are both grouped with launcher

**Comment by oliviermarce** [comment]
The problem appears only with Wayland, not Worg

**Comment by Spinnekop** [comment]
This is an issue with libreoffice and wayland. The same occurs on kde plasma docks with wayland but not Xorg

**Comment by nekohayo** [comment]
As far as I understand it this is completely out of Dash-to-Dock's range of operation, it is somebody else's problem (GTK? Wayland? LibreOffice?).

https://bugzilla.redhat.com/show_bug.cgi?id=1334915 leads to https://bugzilla.gnome.org/show_bug.cgi?id=779143 which leads to https://bugs.documentfoundation.org/show_bug.cgi?id=100158 which leads right back to distro bug trackers, or https://bugs.documentfoundation.org/show_bug.cgi?id=139921 and https://bugs.documentfoundation.org/show_bug.cgi?id=125934 ...

**Comment by jderose9** [comment]
Thanks @nekohayo , I'll close this here.
