### ISSUE TITLE
Ability to collapse status and tray icons

### ISSUE THREAD

**Issue by quietmansoath** [home-sweet-gnome/dash-to-panel#1295]
**Describe the idea or feature you'd like**

Be able to hide the status and tray icons like you can in Windows and KDE, where in which they are grouped (but you can choose which ones display outside of the group).

Compare my current mix of tray and status icons on the right:
![Screenshot from 2021-03-14 14-08-30](https://user-images.githubusercontent.com/46270221/111079090-cd741b80-84ce-11eb-8961-1ee63409e19f.png)

...with how they are "collapsed" in Windows:
![699fdc1b-0b27-46fa-a3d2-3f7ea7ea16d3](https://user-images.githubusercontent.com/46270221/111079129-f4cae880-84ce-11eb-8983-7e0f86782f33.png)

**Is your feature request related to a problem? Please describe.**

I'm frustrated that I have only so much task bar screen real estate and I have to lose some of it to stuff I"m not actively using but still needs to be on. These apps don't always have the option to hide their icons themselves, either. On top of this, I don't necessarily want them to be permanently not in the task bar/try anymore, just hidden but still easily accesible. On windows and KDE, I can have have a bunch of things running in the background and not have to "see" them (their icons). Usually I still need quick access to those things, but having more task bar space for my already open applications, and also visual minimalism, is much nicer.

**Additional context**
Add any other context or mock-ups for requested feature here.
Having functionality similar to that collapsible windows arrow would be really great! But anyway thanks for your work on this extension!

**Comment by oryband** [comment]
Any chance to revive this feature request please?

**Comment by oryband** [comment]
possibly related to #438

**Comment by rodrigoGA** [comment]
this would be really helpful
