### ISSUE TITLE
support gnome-shell 40 

### ISSUE THREAD

**Issue by llegolas** [home-sweet-gnome/dash-to-panel#1297]
Any plans of supporting gnome 40 ?

The extension stopped working on my Fedora34 (beta) which comes with gnome-shell 40

**Comment by Nonononoki** [comment]
Duplicate: https://github.com/home-sweet-gnome/dash-to-panel/issues/1265

**Comment by nekohayo** [comment]
@llegolas, please close this ticket as it is a duplicate of issue #1265.
