### ISSUE TITLE
Dash-to-panel disappears leaving a white space in its place after a exiting a fullscreen youtube video on Firefox

### ISSUE THREAD

**Issue by siorenai** [home-sweet-gnome/dash-to-panel#1305]
Confirmed that the problem persists when Dash-to-Panel is the only enabled extension.

**journalctl /usr/bin/gnome-shell -f -o cat &**
```
st_widget_get_theme_node called on the widget [0x55c204418c60 StBoxLayout.panel-status-menu-box ("Firefox")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x55c20441f4a0 Gjs_ui_animation_Spinner] which is not in the stage.
st_widget_get_theme_node called on the widget [0x55c204416080 StBin ("Firefox")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x55c204414c60 Gjs_ui_panel_AppMenuButton.panel-button ("Firefox")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x55c204417f80 StBin "appMenu" ("Firefox")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x55c204418c60 StBoxLayout.panel-status-menu-box ("Firefox")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x55c20441f4a0 Gjs_ui_animation_Spinner] which is not in the stage.
Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
GNOME Shell started at Wed Apr 07 2021 18:23:02 GMT+0300 (Eastern European Summer Time)
Registering session with GDM
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x4400007
```

**Describe the bug and steps to reproduce**
Dash-to-panel enabled (without auto-hide). Opening a long Youtube video on Firefox in fullscreen. After about 40-50 or more minutes, upon exiting fullscreen, the panel has disappeared like a ghost leaving a white space in its place, where the panel was supposed to be. The only way to bring it back to life is disable and re-enable the extension or maybe restart gnome shell.

**Linux distribution and version**
5.4.105-1-MANJARO

**GNOME Shell version**
GNOME Shell 3.38.4

**Dash-to-Panel version**
40

**Where was Dash-to-Panel installed from?**
Extensions package pre-installed with the distribution.

**Screenshots / Video captures**

**Comment by alan7000** [comment]
Hello, I have also seen this problem on several laptops and desktops. I am using Google Chrome and after not even 20 minutes in full screen of a video on youtube or twitch, the dash to panel extension crashes and leaves an empty space in place of the extension.

**Comment by deivse** [comment]
Can confirm, this does happen on my machine as well. Ubuntu 20.10 w/ Gnome 3.38.3, Dash-to-Panel 40

**Comment by jlemonde** [comment]
This happens as well on Ubuntu 21.04 (fresh install slightly ahead of release) with Dash-to-Panel 40.

**Comment by KruyKaze** [comment]
Same here Youtube on Firefox.

**Comment by demilich1** [comment]
Happens to me as well. Also I am not sure if this is a different bug, but an easy way to reproduce this (without having to wait a long time): 

1. start any fullscreen video on Firefox 
2. press Windows + L to lock the screen
3. log back in
4. Dash to panel is gone

**Comment by jlemonde** [comment]
Yes, I get indeed the same as @demilich1. By the way, it doesn't need to be a video. Any fullscreened window triggers this bug eventually, for instance after locking the screen. (I tested Firefox)

I use Ubuntu 21.04 on Xorg and Dash to Panel version 42. Thankfully, you can have dash to panel back using Alt+F2, then 'r'

**Comment by demilich1** [comment]
Just want to mention that this issue seems to be fixed (using version 43 at the moment). Thank you!

**Comment by shah-xad** [comment]
Happening the same with me, any type of video player (Chrome( Youtube, Vimeo, etc..), VLC) if I pause the player in full-screen Dash to Panel just goes away.
