### ISSUE TITLE
Changing Color on (Top) panel does not work

### ISSUE THREAD

**Issue by GaVenga** [home-sweet-gnome/dash-to-panel#1311]
Changing Color on Top panel does not work. (same issue in Taskbar 2000 by c0ldplasma)

OS and version: Manjaro 21.1
GNOME Shell Version 40.0.1
Dash to Panel Version: latest

**Comment by AdisonCavani** [comment]
Same:

**Describe the bug**
"Override panel theme backgroundcolor" and "Override panel theme gradient" are not working. Color of the panel is not changing. It stays black all the time.

**Linux distribution and version**
ArchLinux

**GNOME Shell version**
GNOME Shell 40.1

**Dash-to-Panel version**
42

**Where was Dash-to-Panel installed from?**
https://github.com/home-sweet-gnome/dash-to-panel
Master branch

**Screenshots / Video captures**
https://imgur.com/a/ubDTCGT
