### ISSUE TITLE
V41

### ISSUE THREAD

**Issue by erickwill** [home-sweet-gnome/dash-to-panel#1317]
**Describe the bug**
After built it says that is incompatible to the latest gnome version (40.1)

**Linux distribution and version**
Arch Linux Rolling Release

**GNOME Shell version**
GNOME Shell 40.1

**Dash-to-Panel version**
v41

**Where was Dash-to-Panel installed from?**
Directly from github. Downloaded Source Code and make install.

**Screenshots / Video captures**
If applicable, add screenshots or a link to a video capture to help explain your problem.

**Additional Info**

**Comment by jderose9** [comment]
v42 will support gnome 40 soon.

**Comment by erickwill** [comment]
Thanks
