### ISSUE TITLE
Overlapping application titles on many ungrouped applications

### ISSUE THREAD

**Issue by BetaConnector** [home-sweet-gnome/dash-to-panel#1318]
**Describe the bug**
Since the update today the application icons/description is overlapping - I am not able to read the application title anymore.

**Linux distribution and version**
Ubuntu 20.10

**GNOME Shell version**
GNOME Shell 3.38.4

**Dash-to-Panel version**
Version 41

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
![image](https://user-images.githubusercontent.com/22777741/116936132-a8e32700-ac67-11eb-861c-ecb726e28e89.png)

**Additional Info**
I disabled all other extensions, restarted shell extensions and the whole OS - no effect.

**Comment by BetaConnector** [comment]
![image](https://user-images.githubusercontent.com/22777741/116936774-93223180-ac68-11eb-8d46-6a6dce1f6d4a.png)

Lowering the max width to the application title helps - but this still seems to be a bug.

**Comment by jderose9** [comment]
Thanks for reporting this! Are you able to help test the fix in the gnome-3.38 branch?

**Comment by caneraydinbey** [comment]
I also made the setting and it seems fixed some.

![image](https://user-images.githubusercontent.com/17731063/117031140-f82d6400-ad08-11eb-83c2-9f3b9005476e.png)

![image](https://user-images.githubusercontent.com/17731063/117031071-e8158480-ad08-11eb-8424-90ab90efd8f5.png)

but still, the favourite icons hold a huge place.

**Comment by jderose9** [comment]
@caneraydinbey Did you text the fix by installing the github version?

**Comment by esyon** [comment]
> Thanks for reporting this! Are you able to help test the fix in the gnome-3.38 branch?

Works fine! But the max width to 160 again and keep the apps ungrouped. Thanks a lot!
