### ISSUE TITLE
Hitting Super key gets stuck in Activities screen since upgrading to Ubuntu 21.04 (Wayland)

### ISSUE THREAD

**Issue by Dave--G** [home-sweet-gnome/dash-to-panel#1322]
Ever since upgrading from Ubuntu 20.10 to 21.04 Dash-to-Panel leaves me stuck in the activities screen when I hit the super key.
I can find no way to exit this mode other than to log out or reboot.
This doesn't happen when Dash-to-Panel is not enabled.
INo other Gnome extensions are enabled.
This problem is reproducible every time the super key is pressed.

**Comment by Calosis** [comment]
Can confirm, was about to report this issue, extermly fustrating and annoying...

**Comment by jderose9** [comment]
Hi there. I installed 21.04 in a VM and I'm having trouble reproducing this issue. Which version of dash-to-panel are you on? Can you explain the steps to reproduce? Does it happen every time you open the overview? Is there some combination of usage of the Show Applications button and Super key usage that gets you into this state?

**Comment by Calosis** [comment]
> Hi there. I installed 21.04 in a VM and I'm having trouble reproducing this issue. Which version of dash-to-panel are you on? Can you explain the steps to reproduce? Does it happen every time you open the overview? Is there some combination of usage of the Show Applications button and Super key usage that gets you into this state?

I'm currently using version 42, had the issue with 40 and 41. It seems totally random, as soon as you login in, it works fine. Start opening some applications, start doing some things, then randomly when clicking the super button you will get stuck, and you won't be able to do anything. It might have something to do with full screen applications, all though it has happend without full screening applications.

**Comment by jderose9** [comment]
Ok, perhaps there is something in the logs? After encountering the problem, you can view them using something like:
`journalctl /usr/bin/gnome-shell  --since "5 minutes ago"`

**Comment by Calosis** [comment]
> Ok, perhaps there is something in the logs? After encountering the problem, you can view them using something like:
> `journalctl /usr/bin/gnome-shell --since "5 minutes ago"`

I was able to reproduce it, and all I have is a bunch of "desktop gnome-shell[111648]: setup_framebuffers: assertion 'width > 0' failed" errors.

**Comment by kleinHeiti** [comment]
So, jetzt habe ich den Fehler auch. Hier ist mein output aus dem journal

`Mai 14 12:41:32 christian-h61ms2vb3 gnome-shell[1157]: libinput error: event3  - Logitech USB-PS/2 Optical Mouse: client bug: event processing lagging behind by 19ms, your >
Mai 14 12:41:38 christian-h61ms2vb3 gnome-shell[1157]: value "nan" of type 'gfloat' is invalid or out of range for property 'x' of type 'gfloat'
Mai 14 12:41:38 christian-h61ms2vb3 gnome-shell[1157]: value "nan" of type 'gfloat' is invalid or out of range for property 'y' of type 'gfloat'
Mai 14 12:41:38 christian-h61ms2vb3 gnome-shell[1157]: JS ERROR: Exception in callback for signal: shown: Error: Wrong type number; float expected. But it's out of range: ->
                                                       _init/GObject.Object.prototype.set@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:556:16
                                                       _easeActor@resource:///org/gnome/shell/ui/environment.js:155:15
                                                       init/Clutter.Actor.prototype.ease@resource:///org/gnome/shell/ui/environment.js:294:19
                                                       _syncWorkspacesActualGeometry@resource:///org/gnome/shell/ui/workspacesView.js:728:21
                                                       _init/this._overviewShownId<@resource:///org/gnome/shell/ui/workspacesView.js:396:18
                                                       _emit@resource:///org/gnome/gjs/modules/core/_signals.js:114:47
                                                       _showDone@resource:///org/gnome/shell/ui/overview.js:604:14
                                                       onComplete@resource:///org/gnome/shell/ui/overview.js:589:36
                                                       _makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:85:13
                                                       _easeActor/<@resource:///org/gnome/shell/ui/environment.js:168:64
Mai 14 12:43:55 christian-h61ms2vb3 gnome-shell[1157]: value "nan" of type 'gfloat' is invalid or out of range for property 'x' of type 'gfloat'
Mai 14 12:43:55 christian-h61ms2vb3 gnome-shell[1157]: value "nan" of type 'gfloat' is invalid or out of range for property 'y' of type 'gfloat'
Mai 14 12:43:55 christian-h61ms2vb3 gnome-shell[1157]: JS ERROR: Error: Wrong type number; float expected. But it's out of range: -Infinity
                                                       _init/GObject.Object.prototype.set@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:556:16
                                                       _easeActor@resource:///org/gnome/shell/ui/environment.js:155:15
                                                       init/Clutter.Actor.prototype.ease@resource:///org/gnome/shell/ui/environment.js:294:19
                                                       _syncWorkspacesActualGeometry@resource:///org/gnome/shell/ui/workspacesView.js:728:21
                                                       animateToOverview@resource:///org/gnome/shell/ui/workspacesView.js:577:18
                                                       animateToOverview@resource:///org/gnome/shell/ui/viewSelector.js:278:33
                                                       _animateVisible@resource:///org/gnome/shell/ui/overview.js:582:27
                                                       show@resource:///org/gnome/shell/ui/overview.js:568:14
                                                       toggle@resource:///org/gnome/shell/ui/overview.js:691:18
                                                       _initializeUI/<@resource:///org/gnome/shell/ui/main.js:235:22
Mai 14 12:44:08 christian-h61ms2vb3 gnome-shell[1157]: meta_get_window_actors: assertion 'compositor' failed
Mai 14 12:44:09 christian-h61ms2vb3 gnome-shell[1157]: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a >
lines 1-30
`

**Comment by Dave--G** [comment]
My system was pretty tweaked with various customizations to the point I couldn't really reproduce this bug and claim is wasn't due to something else.  In an attempt to fix this problem (and a few other more minor issues) I ended up reinstalling Ubuntu 21.04 from scratch.

After installing installing Dash to Panel on the new system, I thought the issue was resolved.  But no, it still happens, usually when the system is under moderate to heavy cpu load.  Which is fairly often for this system.

This time I had unsaved files open and lost a few hours work after being locked out of apps and eventually giving up and rebooting.

So for me at least this is still a serious issue.  I like Dash to Panel a lot...  For the moment I've disabled the super key but is there any way to resolve the problem?

**Comment by Dave--G** [comment]
Oh hi @jderose9 I didn't realize you were a developer on the project.
Since I can reproduce this problem on my shiny new (much less hacked) system, I'd like to help resolve this issue if possible.
I'm on version 42.  Pretty vanilla Ubuntu 21.04/Wayland.  Seems to happen less often than before but usually happens when I'm running windows in a VM and that process is hitting the CPU / memory / disk / etc pretty hard with load.
What can I do to help pin the bug down?

**Comment by Calosis** [comment]
> My system was pretty tweaked with various customizations to the point I couldn't really reproduce this bug and claim is wasn't due to something else.  In an attempt to fix this problem (and a few other more minor issues) I ended up reinstalling Ubuntu 21.04 from scratch.
> 
> After installing installing Dash to Panel on the new system, I thought the issue was resolved.  But no, it still happens, usually when the system is under moderate to heavy cpu load.  Which is fairly often for this system.
> 
> This time I had unsaved files open and lost a few hours work after being locked out of apps and eventually giving up and rebooting.
> 
> So for me at least this is still a serious issue.  I like Dash to Panel a lot...  For the moment I've disabled the super key but is there any way to resolve the problem?
> 
> 

This issue seems to be a Ubuntu / Gnome issue that has been reported and is being fixed. This doesn't seen to be a dash to panel issue.

**Comment by ChaoticNeural** [comment]
> This issue seems to be a Ubuntu / Gnome issue that has been reported and is being fixed. This doesn't seen to be a dash to panel issue.
Do you have a link to that issue at hand?

**Comment by Calosis** [comment]
> > This issue seems to be a Ubuntu / Gnome issue that has been reported and is being fixed. This doesn't seen to be a dash to panel issue.
> 
> Do you have a link to that issue at hand?
> 

I do not (not on my pc atm), but a simple search like "Ubuntu 21.04 super key activities stuck issue" should bring you to the right place.

**Comment by Dave--G** [comment]
Hi @Calosis, when I search for "Ubuntu 21.04 super key activities stuck issue" I don't find bugs other than those related to dash-to-panel.  Can you provide a link to the operating system bug you're referring to?

This bug is real.  I lost files due to it.  However if you're not interested in resolving the issue let me know and I'll close this bug.

**Comment by Calosis** [comment]
> Hi @Calosis, when I search for "Ubuntu 21.04 super key activities stuck issue" I don't find bugs other than those related to dash-to-panel. Can you provide a link to the operating system bug you're referring to?
> 
> This bug is real. I lost files due to it. However if you're not interested in resolving the issue let me know and I'll close this bug.
https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1922353

**Comment by yahya-mohammed07** [comment]
FIXED :
HIT `super+/` then disable show `minimize try`, boom problem solved

thanks to:

https://www.reddit.com/r/pop_os/comments/okfdvh/cant_get_out_of_activates_after_update/h58q94r?utm_source=share&utm_medium=web2x&context=3

**Comment by Calosis** [comment]
> FIXED :
> HIT `super+/` then disable show `minimize try`, boom problem solved
> 
> thanks to:
> 
> https://www.reddit.com/r/pop_os/comments/okfdvh/cant_get_out_of_activates_after_update/h58q94r?utm_source=share&utm_medium=web2x&context=3

The issue was fixed in GNOME, no need for workarounds...
