### ISSUE TITLE
Activities screen not displayed when Panel set to a Vertical Position (Left Or Right)

### ISSUE THREAD

**Issue by thrwyusr** [home-sweet-gnome/dash-to-panel#1326]
When dash-to-panel position is set to Vertical (left or right) some Gnome screens not displayed correctly.
Activities and Show All Applications screens are covered by solid color.
I guess this problem arises because of the new horizontal work-spaces and relevant transition effect of it.

I have added a short video clip for demo.

How to reproduce:
* Enable dash-to-panel
* Set panel positon to Left or Right from Panel Settings
* Press Super + A for Show All Applications
* Or Press Super for Activities screen of Gnome

Expected:
* According to pressed button, respected screen should be displayed correctly
E.g .: Super Key for Activities screen 

Behavior:
* A Blank Screen Comes with only Panel
* You can press ESC to return Desktop

What Works:
* Anything written on blank screen is registered.
* Relevant screens works as expected yet not shown.

Dash to panel Version:
version: 42 (a4224f4acc52a1b69e43951aaad1864c6db54e90)
Gnome Version: 40.1.0
Distro: Arch Linux (up-to-date)

https://user-images.githubusercontent.com/83893538/117560572-80a85d80-b097-11eb-89b0-d7080a006a58.mp4

**Comment by philippun1** [comment]
The overview / app grid are drawn below the panel even if it is vertical, so it is not visible. If you manually cut the height in half the panel will be drawn in the upper half and the overview / app grid in the lower half.
The issue is potentially caused by this commit https://github.com/philippun1/dash-to-panel/commit/6ff52e8f4502c2f4635c5f6882691ec301098005, but I'm not sure.

**Comment by JulienRobitaille** [comment]
I've tried to look into this one, but since I am not familiar with the code base it took me a while for not so much.
I found this log:

I think it has something to do with the `windowPreview` layout.

```

../mutter/clutter/clutter/clutter-actor.c:9226: Actor 'Gjs_ui_workspaceThumbnail_ThumbnailsBox' tried to allocate a size of 640.80 x -0.05
../mutter/clutter/clutter/clutter-actor.c:9226: Actor 'Gjs_ui_workspacesView_WorkspacesDisplay' tried to allocate a size of 3000.00 x -1.00
../mutter/clutter/clutter/clutter-actor.c:9226: Actor 'Gjs_ui_workspaceThumbnail_ThumbnailsBox' tried to allocate a size of 640.80 x -0.05
../mutter/clutter/clutter/clutter-actor.c:9226: Actor 'Gjs_ui_workspacesView_WorkspacesDisplay' tried to allocate a size of 3000.00 x -39.84
clutter_actor_set_allocation_internal: assertion '!isnan (box->x1) && !isnan (box->x2) && !isnan (box->y1) && !isnan (box->y2)' failed
../mutter/clutter/clutter/clutter-actor.c:9226: Actor 'ClutterActor' tried to allocate a size of -2147483648.00 x 0.00
../mutter/clutter/clutter/clutter-actor.c:9226: Actor 'MetaBackgroundGroup' tried to allocate a size of -2218474752.00 x 0.00
../mutter/clutter/clutter/clutter-actor.c:9226: Actor 'Gjs_ui_windowPreview_WindowPreview' tried to allocate a size of -20.07 x -13.01
../mutter/clutter/clutter/clutter-actor.c:9226: Actor 'Gjs_ui_windowPreview_WindowPreview' tried to allocate a size of -24.75 x -15.71
../mutter/clutter/clutter/clutter-actor.c:9226: Actor 'Gjs_ui_windowPreview_WindowPreview' tried to allocate a size of -27.95 x -19.25
../mutter/clutter/clutter/clutter-actor.c:9226: Actor 'Gjs_ui_windowPreview_WindowPreview' tried to allocate a size of -27.95 x -19.25
clutter_actor_set_allocation_internal: assertion '!isnan (box->x1) && !isnan (box->x2) && !isnan (box->y1) && !isnan (box->y2)' failed
../mutter/clutter/clutter/clutter-actor.c:9226: Actor 'ClutterActor' tried to allocate a size of -2147483648.00 x 0.00
../mutter/clutter/clutter/clutter-actor.c:9226: Actor 'MetaBackgroundGroup' tried to allocate a size of -2218474752.00 x 0.00
Can't update stage views actor Gjs_ui_workspace_WorkspaceBackground is on because it needs an allocation.
Can't update stage views actor Gjs_ui_workspace_WorkspaceBackground is on because it needs an allocation.
```
I hope this helps !
