### ISSUE TITLE
Dash-to-panel black line under workspaces

### ISSUE THREAD

**Issue by MuhammedTaha02** [home-sweet-gnome/dash-to-panel#1327]
![image](https://user-images.githubusercontent.com/62564400/117566047-130f2800-b0bd-11eb-96b5-e9596e3b12a5.png)

Hello. I am using gnome40 on Fedora. And I am using this plugin. But I ran into a problem. When the dash-to-panel is open, a line appears under the workspaces. It does not appear when I move the panel to the top. Or does not appear when I use the new dash-to-dock plugin. Or this problem does not occur when I turn on panel intellihide feature

**Comment by jderose9** [comment]
Thanks, yes I think some elements still think the top panel is there so for instance this shadow element is placed too low.

**Comment by MuhammedTaha02** [comment]
> Thanks, yes I think some elements still think the top panel is there so for instance this shadow element is placed too low.

🤔
