### ISSUE TITLE
Only show in overview

### ISSUE THREAD

**Issue by jbytes1027** [home-sweet-gnome/dash-to-panel#1332]
**Describe the idea or feature you'd like**
Have an option to only show the panel when the overview is open.

**Is your feature request related to a problem? Please describe.**
The dock doesn't need to always be accessible from the desktop and not having it is a much cleaner experience. Setting the pressure threshold to an absurdly high number is hackey and makes it so that when the mouse is over the dock in the overview and the overview is closed, the dock does not close too. Also, the dock can still be brought up with the keyboard shortcut when not in the overview with this hack.

**Comment by j-james** [comment]
Haha, seems like the inverse of #1315!
