### ISSUE TITLE
Fixing item width

### ISSUE THREAD

**Issue by aviNrich** [home-sweet-gnome/dash-to-panel#1336]
Hi, 
Please see in attached image bellow, it looks like they are all merged... one ontop of each other...
How can I fix that?
Thanks

![image](https://user-images.githubusercontent.com/77664579/118008454-c1cd9580-b355-11eb-8e92-bf7a4cfb601e.png)

**Comment by jderose9** [comment]
What version of the extension are you on?

**Comment by aviNrich** [comment]
@jderose9 Im using 41, I have the same version in another PC, I export from there and import to my PC but I still have the same problem. (this problem is kind of new, I have never had that in that PC before)
Thanks
