### ISSUE TITLE
panel on side affects size of gnome 40 overview layout

### ISSUE THREAD

**Issue by juhp** [home-sweet-gnome/dash-to-panel#1341]
**Describe the bug**
When placing the panel on the left or right sides, the overview layout size seems to be inverse to the length of the panel.
ie for 100% full height panel the overview disappears, but for 10% panel the overview is close to normal full size.

**Linux distribution and version**
Fedora 34

**GNOME Shell version**
GNOME Shell 40.1  (was same with 40)

**Dash-to-Panel version**
42 (3fb7bdb)

**Where was Dash-to-Panel installed from?**
directly from github

**Screenshots / Video captures**
![dash-to-panel](https://user-images.githubusercontent.com/82731/118427018-df588180-b6fe-11eb-828c-7a0cd9c35dda.png)

**Comment by sergioad** [comment]
For me dash to panel is annoyingly downscaling the app grid

**Comment by juhp** [comment]
To me this issue seems the most serious remaining Gnome 40 problem, though maybe I am biased.
Has it been reported upstream to gnome-shell - it seems changes are needed there?

**Comment by juhp** [comment]
I think this got fixed some months ago.

But recently (gnome-shell-40.4 perhaps?) the application is empty grid, which I think that is a new issue though.
