### ISSUE TITLE
Changing of open applications buttons places.

### ISSUE THREAD

**Issue by emlen** [home-sweet-gnome/dash-to-panel#1342]
Does it real to set it so to use drag and drop with open applications panel buttons to change there places on panel with each other?

**Comment by Akira-Hojo** [comment]
You can move around the application items Win style by very deliberately clicking and slowly dragging up. Mouse needs to be clicked for .5-1 second before dragging, but not too long where you open the sub menu.

Along these lines I would love to see some customization for this specific task of moving applications around, or just tightening up the timing.

**Comment by emlen** [comment]
> You can move around the application items Win style by very deliberately clicking and slowly dragging. Mouse needs to be held clicked for .5-1 second before dragging, but not too long where you open the sub menu.

this is not work for me...
