### ISSUE TITLE
Panel covers the top of maximized applications after unlocking the screen

### ISSUE THREAD

**Issue by tmarkov** [home-sweet-gnome/dash-to-panel#1344]
**Describe the bug**
After locking the screen, often (but not always) the top line of a maximized application (like the tabs on Firefox) are covered by the panel. Usually one screen locking and unlocking results in the application under the panel, while a second lock/unlock fixes it, but that pattern doesn't always hold true.

Besides locking the screen again, I can also fix the issue by disabling and enabling dash-to-panel or its intellihide feature.

**Linux distribution and version**
Arch

**GNOME Shell version**
GNOME Shell 40.1

**Dash-to-Panel version**
42

**Where was Dash-to-Panel installed from?**
AUR, using the -git package (built on 25 May, so should have the latest commits as of today).

**Screenshots / Video captures**
How it looks with the bug:
![image](https://user-images.githubusercontent.com/14000949/120188043-48231c00-c21e-11eb-94e4-9fa0f3ed2f91.png)

How it looks normally:
![image](https://user-images.githubusercontent.com/14000949/120187942-275ac680-c21e-11eb-90f2-0ceff6a67c3f.png)

**Additional Info**

Nothing in the output of `journalctl /usr/bin/gnome-shell -f -o cat &`  seems related to the problem. Just in case, here it is. Most of these happen when locking screen regardless of whether the issue occurs; the window manager warning happens irregularly but also independently of the issue occuring.

```
Window manager warning: last_user_time (49104081) is greater than comparison timestamp (49104080).  This most likely represents a buggy client sending inaccurate timestamps in messages such as _NET_ACTIVE_WINDOW.  Trying to work around...
Window manager warning: W4 appears to be one of the offending windows with a timestamp of 49104081.  Working around...
Timelines with detached actors are not supported
Timelines with detached actors are not supported
Timelines with detached actors are not supported
Timelines with detached actors are not supported
Timelines with detached actors are not supported
```

**Comment by 9000h** [comment]
had also go back to "git reset --hard fd3a7d48596ceeae54459212cd14730762244002" as the panel did disappear after lock/unlock
Ubuntu 20.04.2

**Comment by tmarkov** [comment]
> had also go back to "git reset --hard [fd3a7d4](https://github.com/home-sweet-gnome/dash-to-panel/commit/fd3a7d48596ceeae54459212cd14730762244002)" as the panel did disappear after lock/unlock
> Ubuntu 20.04.2

That's not related to this issue (just in case, I checked that reverting this commit doesn't solve it)..

**Comment by tmarkov** [comment]
Updated the description, since the bug doesn't affect only Firefox, but any maximized app.

**Comment by Jmennius** [comment]
Looks like a duplicate of #1252.
There is an upstream [issue in mutter](https://gitlab.gnome.org/GNOME/mutter/-/issues/1627).
One PR has been merged and released with GNOME 40 but the issue did not go away.

**Comment by m1027** [comment]
Similar on Gentoo, version gnome-shell-extension-dash-to-panel-43_pre20210510.

What I do as a workaround is disabling "Only hide when it is obstructed by
windows".

**Comment by tmarkov** [comment]
Closing since it's duplicate
