### ISSUE TITLE
Switching workspaces after some time in full screen makes the panel vanish

### ISSUE THREAD

**Issue by j-james** [home-sweet-gnome/dash-to-panel#1349]
**Describe the bug**
After having an application in full screen mode for a while, switching workspaces will make the dash disappear. The dash can be "respawned" by locking and unlocking the screen, similar to how the transparency issue at #1333 can be temporarily resolved.

I haven't figured out exactly how long an application needs to be in full screen mode for to trigger this - or if it's even caused by duration at all - but it definitely has to do with being in full screen.

**Linux distribution and version**
Arch 5.12

**GNOME Shell version**
40.1

**Dash-to-Panel version**
40

**Where was Dash-to-Panel installed from?**
`gnome-shell-extension-dash-to-panel-git` from the AUR.

**Screenshots / Video captures**
Not particularly interesting - it'd just be a picture of my background. (The dash vanishes, it doesn't leave anything behind).

**Additional Info**
This might be related to #1333.

**Comment by BrachyKnight** [comment]
It's happening to me too. Are you using wayland or Xorg? Just to know if that might be related to why this is happening

**Comment by j-james** [comment]
I'm using Wayland on a 1920x1080 screen.

**Comment by shmu26** [comment]
I have this same issue on Ubuntu 21.04 using Wayland. I restart it by opening the extensions app, and toggling dash-to-panel off and then on again. This makes the panel reappear.

**Comment by j-james** [comment]
FWIW, I haven't run into this issue since #1333 was fixed.
