### ISSUE TITLE
Overview Desktops lose their rounded corners when Dash to Panel is enabled

### ISSUE THREAD

**Issue by gnomie14** [home-sweet-gnome/dash-to-panel#1355]
**Things to do first**
- Confirm that the problem persists when Dash-to-Panel is the only enabled extension. To do so, disable every other extension, then restart gnome-shell by running the `r` command from the prompt that appears when pressing Alt+F2 on an X.org session, or by logging out/in on a Wayland session.
- Look for Dash-to-Panel errors in your log. To do so, run the `journalctl /usr/bin/gnome-shell -f -o cat &` command and reproduce the problem.
- Search existing opened and closed issues to see if the problem has already been reported.

**Describe the bug**
The virtual desktops in the GNOME Shell overview are supposed to have smooth rounded corners. However, when dash to panel is enabled, those corners are no longer rounded. Please see the attached images.

**Linux distribution and version**
Fedora 34.

**GNOME Shell version**
GNOME Shell 40.2

**Dash-to-Panel version**
version: 42 (latest git)

**Where was Dash-to-Panel installed from?**
Directly from Github. I used
`git clone https://github.com/home-sweet-gnome/dash-to-panel.git`
`make install`

**Screenshots / Video captures**

The two corners on the top side of the virtual desktop are not rounded in the following image.

![top](https://user-images.githubusercontent.com/85856174/121833179-63dff500-cce9-11eb-9991-ef4d7fb813e3.png)

The two corners on the bottom side of the virtual desktop are not smoothly rounded in the following image

![bottom](https://user-images.githubusercontent.com/85856174/121833011-0c418980-cce9-11eb-9b0d-e0c022b9ebed.png)

A small portion of the wallpaper is also being cut out at these corners in the overview desktop.

**Additional Info**
This is on a laptop screen of 1920 x 1080 (16:9) resolution.
I think this bug was introduced in the recently made commits on June 9, 11 and 13 since the Dash to Panel version I was using before in May didn't have this bug.

**Comment by Crucizer** [comment]
This is still an issue.

**Comment by charlesg99** [comment]
Thanks, this is now fixed on the master branch.
