### ISSUE TITLE
Dash to panel error on Ubuntu Web Remix 20.04.1

### ISSUE THREAD

**Issue by pranav-vaid** [home-sweet-gnome/dash-to-panel#1357]
I was using Ubuntu Web Remix, which is based on Ubuntu 20.04, and it was working normal. Then I upgraded my system and after restart this error was there on Extension page:

The settings of extension dash-to-panel@jderose9.github.com had an error:
```
Error: Invalid parameter interfaces (element 0 was not a GType)
```

Stack trace:
```
_init/GObject.Object._classInit@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:448:27
registerClass@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:94:22
@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/prefs.js:2286:30
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:204:33
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

This is the only extension installed, Gnome shell version is 3.36.9

**Comment by Zipdox** [comment]
Same issue

**Comment by pranav-vaid** [comment]
> Same issue

Turns out it was an error only on Ubuntu Web, which was resolved (special thanks to their Devs).
Try upgrading the repositories/distro. If the issue still persists, let me know, I will give you the exact instructions their lead dev gave me.

**Comment by Zipdox** [comment]
I'm on Debian SID, fresly installed and upgraded
