### ISSUE TITLE
Tray icons?

### ISSUE THREAD

**Issue by LiamDawe** [home-sweet-gnome/dash-to-panel#1361]
Hi, with the new GNOME40 support, is there a way to get tray icons back with dash to panel?

I have the AppIndicator/KStatus extension installed but they don't show up in dash to panel.

**Comment by maydayv7** [comment]
That is not a dash to panel problem.
But anyways, check that you have the `libappindicator-gtk3` package installed.

**Comment by LiamDawe** [comment]
I'm not clear if it specifically is a problem with dash to panel or not.

I have that installed. It seems for me, no tray icon extension will currently work with the new version.

**Comment by maydayv7** [comment]
It works fine for me on latest git version, Fedora 34

**Comment by LiamDawe** [comment]
Which extension are you using to get tray icons with it?

**Comment by maydayv7** [comment]
[This](https://extensions.gnome.org/extension/615/appindicator-support/) one

**Comment by LiamDawe** [comment]
Yeah, exactly what I have installed.

So then, what's the best way to debug to find out why they don't appear for me with the new version of dash to dock? Could end up being a bug.

**Comment by maydayv7** [comment]
Are you using latest git version of D2P. Also, which distro do you use.

**Comment by maydayv7** [comment]
It's fine for me: 
![Screenshot from 2021-06-17 16-32-50](https://user-images.githubusercontent.com/73811274/122387856-ecca8b00-cf8c-11eb-8548-46217bf79040.png)

**Comment by LiamDawe** [comment]
Found the issue, it displays on the wrong monitor. I have it set to display on both and the tray appears on my secondary screen.
