### ISSUE TITLE
Panel not on primary Monitor

### ISSUE THREAD

**Issue by TrusterX** [home-sweet-gnome/dash-to-panel#1364]
**Describe the bug**
After travelling from one Location (home office, two Monitors) to another Location (Office, 4 Monitors) , dash-to-panel doesn't remember the previous location on the Screen. The Main Bar defaults to "Monitor 2", i have to switch them back manually to Primary Monitor every time.

**Linux distribution and version**
Fedora 34

**GNOME Shell version**
40.2 (X11 Session)

**Dash-to-Panel version**
43

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
![image](https://user-images.githubusercontent.com/6065454/122343044-938b3900-cf45-11eb-82b1-37996dfeb5e5.png)

**Additional Info**

**Comment by NicolasGoeddel** [comment]
I have a similar issue every day. When I switch between my 4 and 2 monitor setup I also change the primary monitor. But dash-to-panel does not correctly handle that. If I set its settings to "Primary monitor" I assume it will automatically recognize any change in the primary monitor and switch to it if it changes. I usually change my monitor layout using scripts I created with `arandr` if that is relevant.

**Comment by zclandry** [comment]
I am also experiencing this every day.  It persists if I reconnect to the same monitor, but will not persist if I move to a new monitor.

**Comment by NicolasGoeddel** [comment]
The issue still exists.

**Comment by charlesg99** [comment]
Hi, a fix for this was added to the master branch. The primary monitor option should now follow the gnome-shell primary monitor index when changing monitors. Thanks!
