### ISSUE TITLE
Show activities button settings

### ISSUE THREAD

**Issue by sergioad** [home-sweet-gnome/dash-to-panel#1368]
The idea is to add a settings gear like the one in show all apps button, here the user can choose to use either the activities text (default) or icon and set a custom icon too

**Comment by sebastianjacobs** [comment]
Now the Activities button takes too much space and a icon would look way better. Like it's on Windows 10/11 and macOS.

![Bildschirmfoto vom 2021-07-05 20-28-44](https://user-images.githubusercontent.com/16266136/124508165-a3bd6800-ddcf-11eb-933e-d11e1da567f6.png)

**Comment by sergioad** [comment]
Please do not close the issue, nit solved

**Comment by sergioad** [comment]
Again, not solved yet

**Comment by ris58h** [comment]
I have the panel positioned vertically and the Activities button is just `Act...`. I neeed an icon here.

**Comment by sergioad** [comment]
Issue still not solved yet, dev attention needed

**Comment by charlesg99** [comment]
Thanks, closing in favor of #1650
