### ISSUE TITLE
Change volume in scroll panel not working.

### ISSUE THREAD

**Issue by diegovasconcelos** [home-sweet-gnome/dash-to-panel#1374]
Change volume in scroll panel action not working.

Log:

`JS ERROR: Error: Virtual function not implemented: Class StBoxLayout doesn't implement scroll_event
                                          _onPanelMouseScroll@/home/diego/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panel.js:1394:28
`

Fedora 34 
GNOME Shell 40.2 - Wayland
Dash-to-Panel 43

**Comment by BEvgeniyS** [comment]
Confirming this is still an issue on Arch Linux, Gnome 40.4.0

**Comment by zroug** [comment]
I'm getting the exact same error message on Ubuntu 21.10 with Gnome 40.4.0 (Wayland).
