### ISSUE TITLE
App icon are not inline when enable 'Keep original gnome-shell top panel'

### ISSUE THREAD

**Issue by nguyenhai97** [home-sweet-gnome/dash-to-panel#1378]
**Describe the bug**
When enable 'Keep original gnome-shell top panel' option in `Fine-Tune` menu, dash to panel did restore the top bar with a minnor down side which is the app icon are not inline with text (pardon my bad english, I will upload a image so it easier to understand

**Linux distribution and version**
Fedora 34

**GNOME Shell version**
GNOME Shell 40.2

**Dash-to-Panel version**
43

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
[https://imgur.com/a/SEYdb8Y](https://imgur.com/a/SEYdb8Y)

**Comment by hadipash** [comment]
Here's something that helped me: in the `Position` tab change `Panel length` to any value below 100, then set `Anchor` to `Top` and finally change back the `Panel length` to 100.

But yeah, this is definitely a bug.
