### ISSUE TITLE
Disappearing menu

### ISSUE THREAD

**Issue by Githuborian** [home-sweet-gnome/dash-to-panel#1379]
Hi,

I have had this problem for about a year now but it is getting so much more annoying.
I have 2 screenshots, one of the bug (constantly disappearing menubar, mostly when i use fullscreen video's) and the other is from when i temp. fix it by disabling it and enabling it again.
But is is happening much more often these days, sometimes every 5 minutes.

![2](https://user-images.githubusercontent.com/86555108/123542178-62cab100-d748-11eb-979b-4d351ca0d69d.png)
![1](https://user-images.githubusercontent.com/86555108/123542179-63634780-d748-11eb-8b39-1e973a83dabf.png)

ME@pop-os:~$ No journal files were opened due to insufficient permissions.
sudo journalctl /usr/bin/gnome-shell -f -o cat &
[2] 14057
[1]   Exit 1                  journalctl /usr/bin/gnome-shell -f -o cat

ME@pop-os:~$ gnome-shell --version
GNOME Shell 3.38.3

[2]+  Stopped                 sudo journalctl /usr/bin/gnome-shell -f -o cat

Not sure what i'm doing on linux (noob) but the above is what i got when i used the commends given when creating this topic.

Im using PopOS (unbuntu based)
Latest version, all up to date.
Hardly install anything new.

**Comment by Githuborian** [comment]
Update: i am now on PopOS 21.04 (ubuntu based)

**Comment by starmatt** [comment]
I have the same issue, but the panel disappears somtimes when the computer comes back from suspend for me.

Dash-To-Panel 42
GNOME Shell 40.2

**Comment by Githuborian** [comment]
Currently im using: GNOME Shell 3.38.4 and dash to panel 42.
I also have the same, what also works is signing off and back in or ALT+F2 and restart, this restarts gnome UI.
But that is a temp fix and still a bug.
Just installed the latest PopOS version just released and waiting if the bug persists here.

**Comment by starmatt** [comment]
I can confirm that updating to the latest git version fixed the issue for me #1347

**Comment by Githuborian** [comment]
And i can confirm that the bug is still there in the latest versions of everything.

**Comment by Githuborian** [comment]
Tried the Git fix but t does not work for me.
Latest updates of everything, clean install of pop-os, latest ubuntu, still dissapearing.

**Comment by aracnid** [comment]
This issue happens to me occasionally, but it's always related to me having a virtual machine open and usually in full screen mode. Look to see if you have something similar happening on your system. I'd be curious to see if this is the case or not.

**Comment by Githuborian** [comment]
Hey,

Good to have a reply.
With the latest updates of PopOS and dash to panel etc it is still giving me this sooooo anoying bug.
I have it multple times a day, even reinstalled my OS.
And i do not have a virtual machine or something that looks like that. I am a minimalistic guy so not much going on here.

July 19, 2021 3:07:07 PM CEST Jason Romano ***@***.***> wrote:

This issue happens to me occasionally, but it's always related to me having a virtual machine open and usually in full screen mode. Look to see if you have something similar happening on your system. I'd be curious to see if this is the case or not.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or ***@***.***": ***@***.***": "EmailMessage","potentialAction": ***@***.***": "ViewAction","target": "https://github.com/home-sweet-gnome/dash-to-panel/issues/1379#issuecomment-882531552","url": "https://github.com/home-sweet-gnome/dash-to-panel/issues/1379#issuecomment-882531552","name": "View Issue"},"description": "View this Issue on GitHub","publisher": ***@***.***": "Organization","name": "GitHub","url": "https://github.com"}}]
-- Mailfence.comPrivate and secure email

**Comment by Githuborian** [comment]
> This issue happens to me occasionally, but it's always related to me having a virtual machine open and usually in full screen mode. Look to see if you have something similar happening on your system. I'd be curious to see if this is the case or not.

Absolutely nothing like a VM running here but the thing is i am having this issue when i go fullscreen with youtube and switch back to normal screen. Since you have this issue to perhaps you know what can cause this?

**Comment by aracnid** [comment]
You might be on to something with the "fullscreen" mode. When I run my VM it is also fullscreen, so the menu bar is essentially covered up. As I mentioned before, it only happens occasionally. I still haven't determined the exact conditions that trigger this to occur.

**Comment by Githuborian** [comment]
For me it is just one thing, fullscreen on youtube. And i watch allot of youtube so i have it all the time.

July 24, 2021 1:58:28 PM CEST Jason Romano ***@***.***> wrote:

You might be on to something with the "fullscreen" mode. When I run my VM it is also fullscreen, so the menu bar is essentially covered up. As I mentioned before, it only happens occasionally. I still haven't determined the exact conditions that trigger this to occur.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or ***@***.***": ***@***.***": "EmailMessage","potentialAction": ***@***.***": "ViewAction","target": "https://github.com/home-sweet-gnome/dash-to-panel/issues/1379#issuecomment-886043130","url": "https://github.com/home-sweet-gnome/dash-to-panel/issues/1379#issuecomment-886043130","name": "View Issue"},"description": "View this Issue on GitHub","publisher": ***@***.***": "Organization","name": "GitHub","url": "https://github.com"}}]
-- Mailfence.comPrivate and secure email

**Comment by Mershl** [comment]
I see exactly the same issue on Fedora 33 (Gnome 3.38.5, wayland) + latest stable from extensions.gnome.org. Sometimes after suspend Dash to Panel is invisible, like in the screenshots above. Only way to get it back (I've found) is disable and enable Dash to Panel.

**Comment by aracnid** [comment]
Any chance you are using multiple monitors? I think my issue may be the result of multiple monitors, especially when I disconnect/reconnect my desk monitor.

**Comment by Mershl** [comment]
For me it's happening on a Notebook with a single display (only the built in is in use).

**Comment by Githuborian** [comment]
> Any chance you are using multiple monitors? I think my issue may be the result of multiple monitors, especially when I disconnect/reconnect my desk monitor.

Nope, just one laptop screen. Everytime latest updates of everything on my system and still get it everytime i go to fullscreen with something.

**Comment by Githuborian** [comment]
Today, it happend 6 times in a hour (was watching a movie on some site, so not just youtube fullscreen.

**Comment by Githuborian** [comment]
any dev looking here?

**Comment by Githuborian** [comment]
Still get anoyed by these dissapearing panels

**Comment by Githuborian** [comment]
So guys, is there any dev reading this or what????
Still experiencing this anoying bug constantly.

**Comment by Githuborian** [comment]
Hello?

**Comment by aracnid** [comment]
I ended up solving this problem myself by turning off the Cosmic Dock in the Gnome extensions.

**Comment by Githuborian** [comment]
thanks for trying but i already have that disabledv and it still keeps doing this.

December 11, 2021 1:54:51 PM CET Jason Romano ***@***.***> wrote:

I ended up solving this problem myself by turning off the Cosmic Dock in the Gnome extensions.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
-- Sent with https://mailfence.com  Secure and private email

**Comment by misog** [comment]
This happens on GNOME Shell 3.38.6 and version 40 when I enable the Dash to panel extension while some app is in fullscreen mode.

How o reproduce:
1. Start GNOME Tweaks or GNOME Extensions
2. Start full screen mode app (ex. Stellarium in fullscreen mode)
3. ALT+TAB to Tweaks or Extensions, Disable and then Enable Dash to panel
4. Exit full screen mode app (ex. Stellatium)
5. Dash to panel extension is hidden

**Comment by misog** [comment]
Workaround is to change `panelBox.visible = !monitor.inFullscreen;` to `panelBox.visible = true;` in panelManager.js
https://github.com/home-sweet-gnome/dash-to-panel/blob/1e46333210a8ed7a61d4c28e86f98f4abe579fcc/panelManager.js#L421

Then the panel is visible however it makes the full screen app non-clickable at bottom. But it can be solved by hitting F11 two times (exit full screen and enter full screen). Then the full screen works with the panel correctly.

So it looks like the problem is that plugin does not handle exit-fullscreen event correctly after session unlock.
