### ISSUE TITLE
Window overlapps panel after lock

### ISSUE THREAD

**Issue by Alexmitter** [home-sweet-gnome/dash-to-panel#1381]
I already noticed that bug in 3.38, it persists in 40.

If you have a maximized window, have it in foreground and lock the screen, in some cases it will then be changed in size, filling the full monitor and being partially behind the panel then.

Taking the window and make it maximized again will then cause the window to be properly maximized again respecting the border of the panel.

I see it multiple times per day but there is no way to reproduce it on command.

Reproducible on both 3.38 and 40, but not on 3.36 and earlier.

**Comment by skontar** [comment]
Duplicate of #1252.
