### ISSUE TITLE
Panel stutters terribly, when coming out of autohide with Chromium based browsers

### ISSUE THREAD

**Issue by chdslv** [home-sweet-gnome/dash-to-panel#1382]
Panel stutters terribly, when coming out of autohide with Chromium based browsers in full screen mode and hides itself completely. Works well with Firefox, though.

Arch Linux, Gnome version 40.2, Wayland
D2P installed from https://extensions.gnome.org/ extension version 43

**Comment by swatquest** [comment]
Chromium is not configured by default for Wayland
To enable support

Native Wayland support

Since version 87, native Wayland support in Chromium can be enabled with the following flags :

--enable-features=UseOzonePlatform --ozone-platform=wayland

https://wiki.archlinux.org/title/Chromium

**Comment by chdslv** [comment]
@swatquest 
Did that, but the problem persists.

**Comment by swatquest** [comment]
Here its works.

Test by terminal 

chromium --enable-features=UseOzonePlatform --ozone-platform=wayland

By filr
persistent configuration:

~/.config/chromium-flags.conf
--enable-features=UseOzonePlatform 
--ozone-platform=wayland


By desktop file chromium.desktop

url=chromium --enable-features=UseOzonePlatform --ozone-platform=wayland

**Comment by chdslv** [comment]
@swatquest 
With this enabled, Chromium browser becomes smaller, goes back to scaling 100% only for the browser, while all other apps have   font scaling factor of 136%, which I had set with Tweaks.

**Comment by swatquest** [comment]
Did you try to delete the contents of ~/.cache folder and also rename ~/.config/chromium folder?

**Comment by chdslv** [comment]
> Did you try to delete the contents of ~/.cache folder and also rename ~/.config/chromium folder?

All that's done, but the chromium based browsers don't keep the font scaling factor, goes back to 100%. I have 136% got through Tweaks. Panel comes from autohide without stuttering. All other apps keep the 136%, except chromium based browsers.

**Comment by swatquest** [comment]
Realmente hidpi link

https://wiki.archlinux.org/title/HiDPI#GNOME

**Comment by chdslv** [comment]
I have tried this earlier, changing _the experimental features_ with 'scale-monitor-framebuffer', _but_ all it does is blur the fonts. I knew this problem from the beginning. Keeping the display scaling to 100%, but font scaling to 136% (or whatever scaling you like to have) doesn't make the fonts blur, if/when you zoom a web page in any web browser, or in any application.  

So, the problem of stuttering of the D2P for Gnome 40, when coming out of autohide with chromium based browsers is a D2P bug. I hope @jderose9 and @charlesg99 will have a look into it.

**Comment by swatquest** [comment]
https://wiki.archlinux.org/title/HiDPI#Chromium_/_Google_Chrome

**Comment by chdslv** [comment]
> Did you see that?
> 
> https://wiki.archlinux.org/title/HiDPI#Chromium_/_Google_Chrome

Yes. I read the Arch wiki, usually, thanks!
This is a D2P bug.

**Comment by chdslv** [comment]
The problem is still there!
