### ISSUE TITLE
is it possible to restart dash-to-panel service using shell command?

### ISSUE THREAD

**Issue by Stephen2252Ro** [home-sweet-gnome/dash-to-panel#1385]
Hello. I want to know is it possible to restart dash-to-panel service using shell command? Because we I open a virtual screen, some setting always overide setting of dash-to-panel. Hence I want to restart it again. Or is it possible to import the its configure file again using shell command.

**Comment by skontar** [comment]
I use the following Bash script to restart dash-to-panel extension, i.e. switch it off and on again. I also do it together with Tray Icons Reloaded.

```
#!/bin/bash

PANEL="dash-to-panel@jderose9.github.com"
ICONS="trayIconsReloaded@selfmade.pl"


reload() {
    extension="$1"

    extensions=$( gsettings get org.gnome.shell enabled-extensions )
    extensions_without=$( sed -r "s/'$extension'//;s/\[, /[/;s/, , /, /;s/, \]/]/" <<< "$extensions" )

    gsettings set org.gnome.shell enabled-extensions "$extensions_without"
    gsettings set org.gnome.shell enabled-extensions "$extensions"
}

reload "$PANEL"
reload "$ICONS"
```
