### ISSUE TITLE
Dash-to-Panel breaks some Put Windows keyboard shortcuts

### ISSUE THREAD

**Issue by hemebond** [home-sweet-gnome/dash-to-panel#1391]
With Dash-to-Panel enabled some of my keyboard shortcuts for the Put Windows extension are broken.

I use `<super>+numpad` to move windows and with Dash-to-Panel enabled I can not use <super>+1, 2, or 3 properly. It seems the first press (e.g., `<super>+1`) works but subsequent presses (of `<super>+1`) do nothing.

Upon enabling Dash-to-Panel I see this in the logs:
```
$ journalctl -f
Jul 04 15:30:00 excession gnome-shell[2350]: Window manager warning: Overwriting existing binding of keysym ff51 with keysym ff51 (keycode 71).
Jul 04 15:30:00 excession gnome-shell[2350]: Window manager warning: Overwriting existing binding of keysym 60 with keysym 2f7259c9 (keycode 31).
Jul 04 15:30:00 excession gnome-shell[2350]: Window manager warning: Overwriting existing binding of keysym 70 with keysym 70 (keycode 21).
```

**Linux distribution and version**
```
Linux excession 5.10.0-7-amd64 #1 SMP Debian 5.10.40-1 (2021-05-28) x86_64 GNU/Linux
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```

**GNOME Shell version**
GNOME Shell 3.38.4

**Dash-to-Panel version**
42

**Where was Dash-to-Panel installed from?**
The GNOME extensions website,

**Additional Info**
As far as I can tell I do not have any shortcuts enabled in Dash-to-Panel and even changing the modifier key in Dash-to-Panel from `<super>` to something else made no difference. Nor did changing settings in dconf.

**Comment by hemebond** [comment]
The issue does not seem to affect gnome-terminal, but does affect other terminals, like Terminator and Alacritty. It's also possible to hold down the key-combination and have it occasionally work as one or two signals get through.

This extension might also be affect my P key as sometimes pressing it doesn't work, or delays it while the extension is running (tested by toggling the extension on and off).

**Comment by hemebond** [comment]
I don't know if this is still an issue or not because the extension is not compatible with Gnome 40.

**Comment by maxigit** [comment]
I have a similar issue using paperWM when `Super+I` and `Super+O` stop workings.
Activating Dash to Panel generates  the following errors in the journal

```

Jan 25 11:37:12 P16 gnome-shell[16215]: Window manager warning: Overwriting existing binding of keysym 33 with keysym 33 (keycode c).
Jan 25 11:37:12 P16 gnome-shell[16215]: Window manager warning: Overwriting existing binding of keysym 39 with keysym 39 (keycode 12).
Jan 25 11:37:12 P16 gnome-shell[16215]: Window manager warning: Overwriting existing binding of keysym 32 with keysym 32 (keycode b).
Jan 25 11:37:12 P16 gnome-shell[16215]: Window manager warning: Overwriting existing binding of keysym 35 with keysym 35 (keycode e).
Jan 25 11:37:12 P16 gnome-shell[16215]: Window manager warning: Overwriting existing binding of keysym 37 with keysym 37 (keycode 10).
Jan 25 11:37:12 P16 gnome-shell[16215]: Window manager warning: Overwriting existing binding of keysym 6f with keysym 6f (keycode 27).
Jan 25 11:37:12 P16 gnome-shell[16215]: Window manager warning: Overwriting existing binding of keysym 38 with keysym 38 (keycode 11).
Jan 25 11:37:12 P16 gnome-shell[16215]: Window manager warning: Overwriting existing binding of keysym 34 with keysym 34 (keycode d).
Jan 25 11:37:12 P16 gnome-shell[16215]: Window manager warning: Overwriting existing binding of keysym 69 with keysym 69 (keycode 2a).
Jan 25 11:37:12 P16 gnome-shell[16215]: Window manager warning: Overwriting existing binding of keysym 36 with keysym 36 (keycode f).
Jan 25 11:37:12 P16 gnome-shell[16215]: Window manager warning: Overwriting existing binding of keysym 30 with keysym 30 (keycode 13).
Jan 25 11:37:12 P16 gnome-shell[16215]: Window manager warning: Overwriting existing binding of keysym 31 with keysym 31 (keycode a).

```
