### ISSUE TITLE
Breaks in update PopOs 21.04

### ISSUE THREAD

**Issue by Arndorferd** [home-sweet-gnome/dash-to-panel#1396]
The update causes prevents proper lineup with datemenu and leftbox. When both are visible, Theres a large space before the leftbox even when datemenu is no where near it since the new PopOS 21.04 Update. The update also causes the super key to open the application launcher. I was hopping maybe there could be a setting in either Dash to Panel or Arc Menu to turn that off, Im not sure which it should be.

**Comment by jvanhees** [comment]
Having the same problem. If I change some display options (like fractional scaling) it pops back into place and works as expected again.

**Comment by jmbuhr** [comment]
This will be fixed in the next update to pop cosmic: https://github.com/pop-os/cosmic/pull/135
