### ISSUE TITLE
Maximised windows not correctly restored after screen unlock

### ISSUE THREAD

**Issue by CDrummond** [home-sweet-gnome/dash-to-panel#1400]
**Describe the bug**
1. Dash to panel on left side of screen, set to 100%
2. Open gedit, make fullscreen
3. Open nautilius, make fullscreen
4. Lock screen
5. Unlock
6. alt-tab to gedit - gedit's window is not flushed with the top of the screen, its about 20ish pixels lower, and sometimes moved to the left.

**Linux distribution and version**
Fedora 34

**GNOME Shell version**
40

**Dash-to-Panel version**
43

**Where was Dash-to-Panel installed from?**
extensions.gnome.org

**Screenshots / Video captures**
Top-left of screen after unlocked:

![TopLeft](https://user-images.githubusercontent.com/1141694/125354459-bdc0f280-e35b-11eb-86b3-118ced1677af.jpg)

You can see the gedit window in the background underneath dash-to-panel. When screen was locked both apps were maximised, and not under the panel.

**Comment by skontar** [comment]
Duplicate of #1252.
