### ISSUE TITLE
4K Monitor Support

### ISSUE THREAD

**Issue by kanaida2** [home-sweet-gnome/dash-to-panel#1412]
This is the best size I could get the icons to be in the middle...
I would like them all the same size as the one on the very left. Better yet, custom size.
[Image1](https://ibb.co/vDyNSFv) - Look at my middle panel on the bottom
[Image2](https://ibb.co/Htst2ZZ) - Here are my display settings in gnome. Typical of 4k monitors.

**Comment by mobiuscog** [comment]
Exactly the same issue here. Works fine under wayland, but under X11 the icons are all half-height (or thereabouts).

**Comment by kanaida2** [comment]
I can confirm I'm also running X11.

Unrelated Note:
If I do run Wayland, my screen resolution and zoom options disappear in Manjaro gnome. It's because I have Intel/Nvidia hybrid graphics. So on a 15" 4k display it's almost unusable. Everything is so tiny. I can't confirm on the size of the icons in this mode.

**Comment by KazuKoffee** [comment]
Same issue here, running X11 with a 4K monitor. Icons appear half size in the panel but  turning off "Animate hovering app icons" fixes their size.

**Comment by hyper1** [comment]
Ubuntu 20.04
2 displays:
1) 2k scalled to 200%
2) 1k scalled to 100%

dash-to-panel is on the second display.
![image](https://user-images.githubusercontent.com/2795554/144919147-fdaa74e1-0a05-4bcf-b768-245c45eba411.png)

**Comment by voodooattack** [comment]
Same issue here. 

![image](https://user-images.githubusercontent.com/1285826/147338124-ea0ce6a4-77e0-49c1-8f5a-0da5a4134b68.png)

**Comment by dodgio** [comment]
Still happening with Wayland on Fedora 35 on 4K HiDPI monitor. Turning off _Animate hovering app icons_ works around the problem. Still love Dash to Panel anyway! 💖
