### ISSUE TITLE
dash-to-panel -> dash-to-dock

### ISSUE THREAD

**Issue by fastrizwaan** [home-sweet-gnome/dash-to-panel#1413]
Hi,
Dock is loved by many users. but dash to dock is not available. I've tried to make dash-to-panel look like dock. But small panel does not horizontally resize itself to accomodate new task. could you please make the panel size dynamic?

You can try this Configuration file [panel-to-dock_import_me_in_dash_to_panel_about.txt](https://github.com/home-sweet-gnome/dash-to-panel/files/6874069/panel-to-dock_import_me_in_dash_to_panel_about.txt)

We can see the icons are partially visible when new tasks are added to panel, but the panel does not resize itself. if the panel can resize itself to accommodate new tasks, then it can be like dock. Please consider dynamic panel size, so that users who need dock can have it. Thank you!

![Panel_to_dock](https://user-images.githubusercontent.com/1161682/126903537-ef8e258e-586c-464d-8674-4677bd107fa6.png)

![Screenshot from 2021-07-25 20-24-47](https://user-images.githubusercontent.com/1161682/126903552-0b3ed626-c85d-4b4e-8403-681a87a8bbf7.png)

This is on gnome 40.02 fedora 34. Dash-to-Panel -> tranformed into dash-to-dock.

**Comment by Tuxman2** [comment]
Well it is a good idea. But the Dock must have round corners, it is not the case here. There is no space between the bottom of the screen and the dock.

So, more features must be added if you want to be similar to Dash-to-dock:

- Round corners for the panel (Dock)
- Space between the Dock and the edge of the screen
- Possibility to display mounted volumes/devices
- Display the trash with a separate bar

**Comment by edier88** [comment]
Yes, I have realised that Dash to Panel can be turned into a dock. It's great, but the developers need to make round corners and dynamic length so it can be larger as favourites apps are added in the dock.
That could be awesome! An all in one extension!
