### ISSUE TITLE
Generating pot file and new line code

### ISSUE THREAD

**Issue by vantu5z** [home-sweet-gnome/dash-to-panel#1415]
If I try create POT file by `make potfile`, get this error:
```
mkdir -p po
xgettext -k_ -kN_ -o po/dash-to-panel.pot --package-name "Dash To Panel" prefs.js appIcons.js
xgettext: Non-ASCII string at prefs.js:610.
          Please specify the source encoding through --from-code
```
If I change line 53 in Makefile (add parameter `--from-code=UTF-8`):
`xgettext -k_ -kN_ -o po/dash-to-panel.pot --package-name "Dash To Panel" $(TOLOCALIZE) --from-code=UTF-8`
Then POT file is generated successfully.
And I can do `make mergepo` to update strings in PO files.

Second issue with `Settings.ui`:
It has strings with new line code `&#10;` and seems translations for this strings are not applied.
What can I do to fix this issue?

**Comment by jose1711** [comment]
> It has strings with new line code &#10; and seems translations for this strings are not applied.
What can I do to fix this issue?

Change `&#10;` to `\n` in both `msgid` and `msgstr`
