### ISSUE TITLE
Allow navigation of the application icons with keyboard

### ISSUE THREAD

**Issue by alisabzevari** [home-sweet-gnome/dash-to-panel#142]
I suggest to reserve super+0 hotkey to select the last window in the list. This is the same in google chrome browser; If you press ctrl+0, it will focus the last (right most) tab in the browser.

**Comment by jderose9** [comment]
Hello! I'm not sure I follow when you say "last window in the list"? Which list are you referring to? The icons in the taskbar? Or are you saying that the keymapping for launching applications has overwritten a default browser binding?

Thanks for clarifying!

**Comment by alisabzevari** [comment]
Hi, Sorry for bad description. I meant the icons in the taskbar.

**Comment by jderose9** [comment]
My initial personal feeling is that this is a bit confusing. The items at the beginning of the dash are your favorites and have been pinned there in order, but the end of the dash are the items that you've opened and I'm not sure how useful it would be to access via keyboard shortcut the last item but not, say, the 2nd to last item. What's the scenario you are running into?

@franglais125 what are your thoughts?

Thanks!

**Comment by franglais125** [comment]
I don't have a strong preference. Personally I don't use hotkeys beyond 6 or 7, as I use them more for my favorite apps.

Do any of you know what the behavior is under Unity or on Windows? Perhaps it would be more worthwhile to keep a consistent feeling with those too, since there are some people migrating at the moment.

Does anyone else following the discussions here have an opinion on this?

Small detail: AFAIK, it's actually the shortcuts `Alt+9` (Firefox/Chrome) or `Ctrl+9` (Chrome) that take you to the last tab, not `Ctrl+0`.

**Comment by alisabzevari** [comment]
I've tested it on windows. Windows 10 does not assign 0 or 9 to the last item. In chrome these shortcuts are handy because if you have a lot of tabs open, then you can jump to the last one with `Ctrl+9` and using `Ctrl+Shift+Tab` move back, or jump to the first one and move forward. But here it is a little bit different because when you switch between windows the order of the items will change, so you cannot jump to the last one and then move to the second last one.

So, maybe you are right and it doesn't make sense to implement this functionality here.

**Comment by jderose9** [comment]
The order of the applications in the taskbar shouldn't change when you switch windows. You are talking about cycling through the applications right? Or the different windows of a single application?

What if there was a keystroke that enabled a selection mode for the taskbar, then you could arrow key through or use home/end to highlight your desired application and the hit enter to simulate a click or escape to exit the selection mode?

**Comment by alisabzevari** [comment]
Yes, I am talking about cycling through applications.

> What if there was a keystroke that enabled a selection mode for the taskbar, then you could arrow key through or use home/end to highlight your desired application and the hit enter to simulate a click or escape to exit the selection mode?

That's actually a good idea.

**Comment by jderose9** [comment]
@varsop has pointed out that we can activate keyboard navigation with Ctrl-Alt-Tab so we really just need to add a keybinding to the app icons to allow easy launch/activation of applications.

**Comment by fthx** [comment]
+1 for this feature request !

**Comment by charlesg99** [comment]
Let's continue in #1053. Thansk!
