### ISSUE TITLE
Overview window lose rounded corners and cuts off when Dash to Panel is enabled and has artifacts

### ISSUE THREAD

**Issue by Aryan20** [home-sweet-gnome/dash-to-panel#1421]
**Things to do first**
- Confirm that the problem persists when Dash-to-Panel is the only enabled extension. To do so, disable every other extension, then restart gnome-shell by running the `r` command from the prompt that appears when pressing Alt+F2 on an X.org session, or by logging out/in on a Wayland session.
- Look for Dash-to-Panel errors in your log. To do so, run the `journalctl /usr/bin/gnome-shell -f -o cat &` command and reproduce the problem.
- Search existing opened and closed issues to see if the problem has already been reported.

**Describe the bug**
GNOME Shell overview preview is supposed to have smooth rounded corners. However, when dash to panel is enabled, some corners are no longer rounded and the whole place where panel is supposed to be on Desktop gets cut off, and also have some artifacts plus dynamic transparency doesn't work. Please see the attached images.

**Linux distribution and version**
Garuda Linux ( Garuda Soaring Spotted-Eagle (latest) )

**GNOME Shell version**
GNOME Shell 40.3

**Dash-to-Panel version**
Version 43 and 9999 from GitHub ( ig version number is also broken)

**Where was Dash-to-Panel installed from?**
The GNOME extensions website, directly from GitHub (Tried both)

Wihout Dash to Panel - 
![Screenshot from 2021-07-30 19-51-03](https://user-images.githubusercontent.com/34372791/127667287-89492044-59b3-493a-9fbd-b5751d0d3f6a.png)

With Dash to Panel - 
![Screenshot from 2021-07-30 19-42-49](https://user-images.githubusercontent.com/34372791/127666433-1bc784a9-0fa7-4c65-8d95-3d42487dd29a.png)
![Screenshot from 2021-07-30 19-42-28](https://user-images.githubusercontent.com/34372791/127666451-a3211880-ac20-4e45-93a2-25734003743d.png)

**Comment by Aryan20** [comment]
![image](https://user-images.githubusercontent.com/34372791/127668805-0b821dd3-0229-4bf4-be40-e7a04303a124.png)
Artifact is visible will Blur my Shell extension enabled.

**Comment by suchinton** [comment]
I'm facing the same issue, so are other people I know. Please fix this bug! Thank you ( idk if it's appropriate to comment on a bug report but I wanted to push this issue forward as well)
