### ISSUE TITLE
[Bug] Dynamic Opacity doesn't change if on another workspace

### ISSUE THREAD

**Issue by ghost** [home-sweet-gnome/dash-to-panel#1424]
## Greetings,
I am using Dash to Panel instead of Dash to Dock in the meantime until it gets full GNOME 40 support.
I really enjoy this extension, as it is very customizable and very cool, but I got a problem w/ Dynamic Opacity.
### Screenshots
![image](https://user-images.githubusercontent.com/52204908/127779016-22a193e5-c1da-467b-bcb1-fb3d4fb01e4d.png)
_Workspace 1_
![image](https://i.imgur.com/PvuZlzS.png)
_Workspace 2_

---

As you can see, opacity doesn't change at all. This is because on Workspace 1 there's a maximised window (see my settings for dynamic opacity down here).
![image](https://user-images.githubusercontent.com/52204908/127779057-eb0a07a6-0b19-4e0a-ad47-12e0ba052f4e.png)
I setted it to work only with maximised windows, as I like this behaviour (and I don't have in mind to change it ;D)
Is there any way to fix this? AKA reducing the opacity on the another workspace automatically with a maximised windows on the first workspace.

This is how it should look like:
![image](https://user-images.githubusercontent.com/52204908/127779239-3ff32526-f824-42eb-bba7-3034edf96c72.png)

### Info
OS: Arch Linux
Windowing System: X11
Shell Version: GNOME Shell 40.3
DtP Version: 43
This happens with and without the extension **Blur my Shell**.

---

I have also tried to use the `git` version as #980 says it's the "solution", but it doesn't work for me.

**Comment by aScordino** [comment]
BTW sorry if I didn't followed the [template for issues](https://github.com/home-sweet-gnome/dash-to-panel/issues/new?assignees=&labels=bug&template=bug_report.md), I don't know how I even bypassed the selection :/

**Comment by NANISOREH** [comment]
I have the very same issue.
Is there any hope it could be taken into consideration?
