### ISSUE TITLE
Cannot create pot file

### ISSUE THREAD

**Issue by Etamuk** [home-sweet-gnome/dash-to-panel#1431]
Hello,

the German translation is very old. So I would like to work on it but I cannot create that pot file with `make potfile`.

I downloaded the latest source code today and opened that archive. After that in typed in terminal make potfile.
This is the output:
```
$ make potfile
fatal: Kein Git-Repository (oder irgendein Elternverzeichnis bis zum Einhängepunkt /)
Stoppe bei Dateisystemgrenze (GIT_DISCOVERY_ACROSS_FILESYSTEM nicht gesetzt).
fatal: Kein Git-Repository (oder irgendein Elternverzeichnis bis zum Einhängepunkt /)
Stoppe bei Dateisystemgrenze (GIT_DISCOVERY_ACROSS_FILESYSTEM nicht gesetzt).
mkdir -p po
xgettext -k_ -kN_ -o po/dash-to-panel.pot --package-name "Dash To Panel" prefs.js appIcons.js
xgettext: Non-ASCII string at prefs.js:610.
          Bitte die Kodierung des Quelltextes mit --from-code angeben.
          
make: *** [Makefile:53: po/dash-to-panel.pot] Fehler 1
```

Can somebody share to me the latest pot file?

**Comment by vantu5z** [comment]
Look here #1415
Don't forget to change new line code.

**Comment by Etamuk** [comment]
Thank you. I didn´t notice that topic.

Now I got an almost complete pot file.

But some strings are not availible:

![Bildschirmfoto vom 2021-08-07 22-57-32](https://user-images.githubusercontent.com/20098065/128613840-17e8896e-fe9a-4432-853e-ff9e9f2f7f6d.png)

![Bildschirmfoto vom 2021-08-07 22-58-19](https://user-images.githubusercontent.com/20098065/128613843-8f787355-d03b-4591-8531-a1ad8c1f76cf.png)

**Comment by vantu5z** [comment]
See #1418, there is commit to add this strings

**Comment by Etamuk** [comment]
Thanks again. 
Now the translation is fully complete. 
With copy&paste I added the missing strings above. Not nice but it works. 

I will create a PR with that German translation now.
