### ISSUE TITLE
Delay for IntelliHide No More Working

### ISSUE THREAD

**Issue by linuxtopia** [home-sweet-gnome/dash-to-panel#1433]
**Describe the bug**

After weeks my Dash-to-Panel works ridiculously when intelligently hiding. It appears and disappears suddenly, tweaked intelligent hiding settings for highest values but did not help. It appears and like a lighting clear away.

**Linux distribution and version**

Pop OS 21.04

**GNOME Shell version**

GNOME Shell 3.38.4

**Dash-to-Panel version**
42

**Where was Dash-to-Panel installed from?**

The GNOME extensions website

**Screenshots / Video captures**
![image](https://user-images.githubusercontent.com/19939134/128768155-6a073381-8a7a-4dc6-b2e0-d8b171eb0498.png)

**Additional Info**

Nothing works with the settings for delay. I'll use Pop OS Dock till find a solution

**Comment by oryband** [comment]
For me intellihide triggers (hiding the panel) after clicking on on of the right widgets e.g. date, network/airplane buttons, app tray icons, etc. - Practically I'm unable to open a menu and use it (e.g. network/airplane buttons) because the panel immediately hides after clicking on the buttons.
