### ISSUE TITLE
dash to panel does not get transparent until i reset the GNOME shell.

### ISSUE THREAD

**Issue by Master811129** [home-sweet-gnome/dash-to-panel#1434]
**Describe the bug**
dash to panel does not get transparent until i reset the GNOME shell.

**Linux distribution and version**
Manjaro 21.01.0

**GNOME Shell version**
GNOME Shell 40.3

**Dash-to-Panel version**
43
**Where was Dash-to-Panel installed from?**
The GNOME extensions website, your distribution's package manager (both have this issue)

**Screenshots / Video captures**
![Screenshot from 2021-08-10 11-52-00](https://user-images.githubusercontent.com/37829730/128825452-c455b247-cc29-43d8-badd-5f5c13adacb2.png)

**Comment by j-james** [comment]
I am also seeing this behavior again. Looks like #1333's back.

**Comment by maydayv7** [comment]
Also, using gestures in Wayland triggers the panel to reset to a black color, even if another color is specified in preferences.

**Comment by j-james** [comment]
This bug has gone away for me with the latest Git version.

**Comment by maydayv7** [comment]
It still does, with latest `master`, on Wayland, GNOME 40
