### ISSUE TITLE
Option to Group only Minimized Windows

### ISSUE THREAD

**Issue by Glint-Eye** [home-sweet-gnome/dash-to-panel#1435]
**Describe the idea or feature you'd like**
I like to use App Windows ungrouped, but with too many windows open it gets a bit busy, so it would be great to only group the minimized windows, as i still like to have them around for quick access through clicking app icons or alt+tab. I think that would also be a great compromise between the grouped and ungrouped options as it benefits from both approaches.  

**Additional context**
Usually i didn't care much for minimizing windows, as it didn't provide a lot of benefits for me compared to just using alt+tab, but since i started using Pop OS with its automatic window tiling capabilities, minimizing windows became really usefull as it automatically rearranges the tiled windows without having to close anything, but now the minimized windows are kind of just taking up space.

**Comment by guoqiyi** [comment]
same here,and journal log shows :
Aug 19 09:14:13 nvme gnome-shell[605]: JS ERROR: TypeError: appGridBox.get_height is not a function
                                       _getAppDisplayBoxForState@resource:///org/gnome/shell/ui/overviewControls.js:101:24                                       
                                       vfunc_allocate@/home/yi/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/overview.js:591:30
