### ISSUE TITLE
App grid not rendering

### ISSUE THREAD

**Issue by jsilll** [home-sweet-gnome/dash-to-panel#1439]
When dash-to-panel gnome stops displaying the app grid. 
Log error: 
```
JS ERROR: TypeError: appGridBox.get_height is not a function
_getAppDisplayBoxForState@resource:///org/gnome/shell/ui/overviewControls.js:94:62
vfunc_allocate@/home/joao/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/overview.js:591:30
```
Fedora 34 (Workstation Edition)
GNOME Shell 40.4
Dash-to-Panel version 43, installed through GNOME extensions website.

https://i.imgur.com/ZuAHCpk.png

**Comment by jsilll** [comment]
Sorry for duplicate

**Comment by escoand** [comment]
Just to mention #1437
