### ISSUE TITLE
Application list

### ISSUE THREAD

**Issue by raffaem** [home-sweet-gnome/dash-to-panel#1444]
After pressing Super+Alt+UpArrow two times, I noticed that the application list is not available anymore in GNOME 40 after 
activating this extension.

Is this normal?

**Comment by ConnerHansen** [comment]
I've also noticed this bug, I was on my way over here to open an issue on it. I've disabled all other extensions and it persists.

Fedora 34, Gnome 40.4.0, Wayland session

**Comment by mweirauch** [comment]
Duplicate of #1437 ?

**Comment by juanmata42** [comment]
Same thing as ConnerHansen happens to me, same situation

**Comment by Zesko** [comment]
Same issue for me. Thank for the info about #1437.
