### ISSUE TITLE
There is no icon for the show desktop button on the panel.

### ISSUE THREAD

**Issue by Tuxman2** [home-sweet-gnome/dash-to-panel#1447]
**Describe the bug**

I haven't got an icon for the show desktop button on the panel when I enabled it in the preferences. I've got a grey square (see picture)

**Linux distribution and version**
Manjaro 21.1.1 Gnome version.

**GNOME Shell version**
40.4

**Dash-to-Panel version**
43

**Where was Dash-to-Panel installed from?**
Pre-installed with the distribution

**Screenshots / Video captures**
![showdesktopbutton](https://user-images.githubusercontent.com/23556606/132013177-26585aa9-439c-47a9-9137-cbdf70d5416c.png)

**Comment by Tuxman2** [comment]
If an option can be added to be able to choose an icon for the show desktop button that will have the same size as the icons on my picture above, it will be great. Well, like you did with the option to choose the appmenu button.

Thanks.

**Comment by martinvonwittich** [comment]
This is still broken. Can the issue be reopened?
