### ISSUE TITLE
Dash to Panel Opacity on Session Start Issue

### ISSUE THREAD

**Issue by CuteLuma** [home-sweet-gnome/dash-to-panel#1448]
Describe the bug
If Dash to Panel's panel length is less than 100%, the override panel opacity feature will not work on a fresh session start until i move the length slider just a bit, then it will start working again

Linux distribution and version
Arch Linux x86_64

GNOME Shell version
GNOME Shell 40.4

Dash-to-Panel version
43

Where was Dash-to-Panel installed from?
The GNOME extensions website

Screenshots / Video captures
(When i start the session the settings are like this)
![Captura de tela de 2021-09-04 09-18-20](https://user-images.githubusercontent.com/39540116/132094396-1c003e46-81f8-449a-8e0f-a53621ac0102.png)

(When i move the length slider a little bit, the override opacity works again)
![Captura de tela de 2021-09-04 09-19-05](https://user-images.githubusercontent.com/39540116/132094373-db66daca-5520-4761-ac4e-9fb4d7e4b796.png)

**Comment by GothLuma** [comment]
It was a conflict with the Blur my Dash extension when it had the Blur Panel option enabled, when i disabled this option this problem haven't occurred anymore
