### ISSUE TITLE
Panel detached from the screen with round edge.

### ISSUE THREAD

**Issue by Tuxman2** [home-sweet-gnome/dash-to-panel#1449]
**Describe the idea or feature you'd like**
Have a panel detached from the screen with round edge. Like we can see in the Deepin desktop.
So with an option, we can define a value to move the panel from the edge of the screen (move up) and an option to round edge for the panel.

**Additional context**
It would look like this:

![panel](https://user-images.githubusercontent.com/23556606/132123304-f663ff54-54e7-4fe4-a03b-1d73fdac120e.png)

Thanks.

Note: Separators can also be added.

**Comment by balintmaci** [comment]
I would also really like this. The feature looks really good in Zorin, but I'm using up to date Fedora so the Zorin taskbar is not an option for me.

Looks something like this:
![image](https://user-images.githubusercontent.com/13272850/182723156-97f4229e-a498-4037-9930-24fdab31ca53.png)

I think it's possible to configure corner rounding, vertical displacement, height, and width.
