### ISSUE TITLE
Feature request: customise fonts

### ISSUE THREAD

**Issue by bluebear94** [home-sweet-gnome/dash-to-panel#145]
I'd like to customise the fonts used for the bar (if this is possible to implement).

**Comment by brandon-schumann** [comment]
Try changing your shell theme in Gnome Tweak Tool (enable User themes extension).

You can also make your own mini Gnome shell theme and use CSS to customize the font on the panel.

**Comment by jderose9** [comment]
The extension currently allows setting the font size so this doesn't seem unreasonable. Thanks!

**Comment by grandixximo** [comment]
It would be nice if you could change the font!
