### ISSUE TITLE
Error: Invalid parameter interfaces (element 0 was not a GType)

### ISSUE THREAD

**Issue by everio** [home-sweet-gnome/dash-to-panel#1451]
Hello,

**Describe the bug**
I have ths error : 
`Error: Invalid parameter interfaces (element 0 was not a GType)

Stack trace:
  _init/GObject.Object._classInit@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:444:27
  registerClass@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:78:22
  @/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/prefs.js:2286:30
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:204:33
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  `

**Linux distribution and version**
Debian GNU/Linux bookworm/sid

**GNOME Shell version**
GNOME Shell 3.38.6

**Dash-to-Panel version**
43

**Where was Dash-to-Panel installed from?**
distribution's package manager

**Comment by jonorthwash** [comment]
I also got this after I upgraded from gnome-shell 3.38.5 to 3.38.6.

**Comment by jonorthwash** [comment]
It happens with the version from Debian unstable and the current version from github.

To clarify: this isn't just an error message, but it also makes dash-to-panel unusable.  You're gonna get more reports of this soon, as people's machines update and they lose their panel (and can't restore their dock..)!

**Comment by BentHaase** [comment]
Same issue on  Ubuntu 20.04.3 LTS, GNOME Shell 3.36.

**Comment by zolt56** [comment]
Same error cloning the 3.38 branch on gnome-shell 3.38.4.

**Comment by akfrey171** [comment]
Also have this problem too, right after restarting my computer

**Comment by jonorthwash** [comment]
Btw, this can be fixed by manually adding versions in the json file.
