### ISSUE TITLE
Dash to Panel not working after every boot

### ISSUE THREAD

**Issue by tanng181** [home-sweet-gnome/dash-to-panel#1453]
**Things to do first**
- I tried disabling Dask to Dock and only keep Dash to Panel running but the problem still persists.

**Describe the bug**
- After booting up, Dock to Panel is missing from my taskbar. I would have to go to Dash to Panel GNOME extension and switch it OFF then ON again to get it working.

**Linux distribution and version**
 Pop!_OS 21.04 with NVIDIA driver

**GNOME Shell version**
GNOME Shell 3.38.4

**Dash-to-Panel version**
Version 42

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
Dash to Dock and Dash to Panel is disabled:
![Screenshot from 2021-09-09 06-56-08](https://user-images.githubusercontent.com/51953102/132601189-de8663f8-bdc5-4e49-b6c8-90314cfb1bda.png)

Dash to Dock disabled, Dash to Panel enabled:
![Screenshot from 2021-09-09 06-52-46](https://user-images.githubusercontent.com/51953102/132601138-581b3ca1-bbdf-4d6b-917d-8b8c676c2fd8.png)

Dash to Dock and Dash to Panel enabled:
![Screenshot from 2021-09-09 06-44-01](https://user-images.githubusercontent.com/51953102/132601215-7edadc7a-1074-4a4a-846d-3f067c75608e.png)

Turn off Dash to Panel:
![Screenshot from 2021-09-09 06-44-26](https://user-images.githubusercontent.com/51953102/132601275-38a92ea1-54cf-406d-9bff-87536c462ce1.png)

Turn Dash to Panel back On:
![Screenshot from 2021-09-09 06-44-29](https://user-images.githubusercontent.com/51953102/132601304-1f47a96d-2292-41ee-b305-51f9502579d7.png)

**Comment by TheLogan** [comment]
Same issue with same versions, other ways to reproduce
Click alt+f2 and then write r and click enter, the UI will refresh and dash to panel will stop working despite being enabled.
I checked the looking glass and saw the following error:  
"OverviewControls.ControlsManagersLayout is undefined"
I don't know if it is related, but it might be.
