### ISSUE TITLE
Issue with 'Display the main panel on' Feature when using multiple monitors

### ISSUE THREAD

**Issue by Dafarkias** [home-sweet-gnome/dash-to-panel#1454]
I use 3 different monitors, and when starting Fedora 34 (Gnome 40), the 'Display the main panel on' does not remember its assigned setting when connecting new external monitors. 

For instance, I have the setting assigned to 'Primary Monitor,' which I have assigned to my first external monitor. However, when I connect my second external monitor, this setting automatically assigns itself to the new monitor. 

Likewise, if I start my OS with my first external monitor powered off, and power the unit 'on' after booting and logging into Fedora 34, the feature does not apply correctly or automatically. I have to manually go into settings, and reassign the 'Display the main panel on' to 'Primary Monitor.'

Could this be fixed so that any time a new monitor/display is connected, the 'Display the main panel on' setting maintains its user selected source? That would be fantastic. This extensions is very nice. 

I am using Dash-to-Panel 43, installed directly from the GNOME extensions website.

Best Wishes,

Dafarkias

**Comment by auipga** [comment]
Same here. Please prioritize this issue.

**Comment by DaanDL** [comment]
Same here. 
More specifically: I always leave it on 'Primary monitor'. But when connecting to another monitor, it selects 'Monitor 2'. I always need to revert it to 'Primary monitor'.

**Comment by genebean** [comment]
I am having this issue too. My best guess is that dash to panel isn't always checking the "primary monitor" but rather checks once when you select that setting. I would like it to always pick the primary monitor.
