### ISSUE TITLE
Gnome 41 support

### ISSUE THREAD

**Issue by bubi-luka** [home-sweet-gnome/dash-to-panel#1457]
**Describe the bug**
The extension stopped working after upgrading to Fedora 35, development version with Gnome Shell 41 rc.1. The error is: `AppDisplay.AppIconMenu is undefined`.

**Linux distribution and version**
`Linux user 5.14.1-300.fc35.x86_64 #1 SMP Fri Sep 3 16:27:33 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**GNOME Shell version**
`GNOME Shell 41.rc.1`

**Dash-to-Panel version**
43

**Where was Dash-to-Panel installed from?**
Installed from here (github).

**Comment by cagdasbas** [comment]
This issue looks related to [this change](https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/b496c9f956f6da7e72b585e58ac20cad51f64e54) in gnome-shell. Replacing `AppIconMenu` with `AppMenu` in [here](https://github.com/home-sweet-gnome/dash-to-panel/blob/master/appIcons.js#L94) seems to solve the issue. I'm not sure what is the purpose of the change in ghome-shell though.

**Comment by bubi-luka** [comment]
@cagdasbas You are right, that change works. Thank you!

**Comment by PHLAK** [comment]
FYI, [Gnome 41 was released today](https://help.gnome.org/misc/release-notes/41.0/). I know we're still waiting on it to trickle down to the distros (not even in Arch yet) but thought now would be a good time to reignite the discussion. I will be waiting on the Gnome 41 to come to the stable Arch repos but as soon as does I will test this extension and start reporting problems. In the meantime  we still have several small left over issues from #1265 that would be nice to see resolved as well.

**Comment by cagdasbas** [comment]
I'm using the latest release on Gnome 41+Fedora 35 Beta for a week now. No issues so far.

**Comment by cagdasbas** [comment]
Okay I was mistaken :) There is one issue that I realized just now. When I right click on any icon or open window on taskbar, the menu doesn't show up and this is exception appears in the logs:
```
(gnome-shell:38663): Gjs-CRITICAL **: 11:06:21.853: JS ERROR: TypeError: super[func] is not a function
callParent@/home/cagdas/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/utils.js line 83 > eval:1:199
_init@/home/cagdas/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:1471:14
C@/home/cagdas/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/utils.js line 83 > eval:1:46
popupMenu@/home/cagdas/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:653:26
vfunc_button_press_event@resource:///org/gnome/shell/ui/appDisplay.js:3202:18
```

Here is my active extensions: 
```
AppIndicator and KStatusNotifierItem Support
Bluetooth quick connect
Dash to panel
Gnome Email Notifications
GSConnect
```

**Comment by PHLAK** [comment]
#1338 in particular is still bugging me. Also the inconsistent rounded corners. But these are cosmetic issues, not functional ones.

**Comment by philippun1** [comment]
I created PR #1468, it will work again on gnome 41. For now I only tested it on GNOME OS, I will do further testing once it lands in Manjaro testing/unstable.

**Comment by linuxiorr** [comment]
I'm running Solus GNOME with GNOME 41, and I have the same issue as @cagdasbas. 

Namely, the right click popover menu doesn't open when I right-click items on the task bar. Right-clicking has no effect.

**Comment by SGiuseppe** [comment]
Another bug on my system does not show the application grid

**Comment by SGiuseppe** [comment]
fix: #1437

**Comment by mbevc1** [comment]
Still fails with F35 Beta and Gnome41. Would #1468 be a fix? If that's backwards compatible perhaps cutting a release might be worth doing in order to remove this issue when people upgrade. Thanks!

**Comment by LaurentOngaro** [comment]
> This issue looks related to [this change](https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/b496c9f956f6da7e72b585e58ac20cad51f64e54) in gnome-shell. Replacing `AppIconMenu` with `AppMenu` in [here](https://github.com/home-sweet-gnome/dash-to-panel/blob/master/appIcons.js#L94) seems to solve the issue. I'm not sure what is the purpose of the change in ghome-shell though.

the line to change is #786 in appIcon.js file 

`
const MyAppIconMenu = class DashToDock_MyAppIconMenu extends AppDisplay.AppMenu {
`

It worked for me too, even if another error raised just after
`
No JS module 'viewSelector' found in search path
`

OS : Manjaro  Stable branch up to date
Gnome: 41.1
