### ISSUE TITLE
why control center opened in panel menu always shows wireless network setting page?

### ISSUE THREAD

**Issue by geldkang** [home-sweet-gnome/dash-to-panel#1459]
**Describe the bug**
right clicking panel, and select settings in menu, then it always shows wireless network settings page, even if i dont have any wireless adapters
**Linux distribution and version**
debian 10
**GNOME Shell version**
gnome 3.38.4
**Dash-to-Panel version**
it says 9999, but codes with problem also included in master
**Where was Dash-to-Panel installed from?**
customed debian package manager
**Additional Info**
            cmd: ['gnome-control-center', 'wifi']
i found some code in appIcons.js:1914, which designates cmd of gnome control center wifi page when pressed settings in panel menu. is it necessary?

**Comment by guoqiyi** [comment]
no  bug in ubuntu 21.04 with gnome 3.38.4,9999 is a unstable version,you should install from https://extensions.gnome.org/
