### ISSUE TITLE
Empty app grid

### ISSUE THREAD

**Issue by escoand** [home-sweet-gnome/dash-to-panel#1460]
**Describe the bug**
![image](https://user-images.githubusercontent.com/428567/133406057-6fddf79b-d87d-4a24-a22d-7aa7a528692a.png)
I'm having the same issue as described by George.LG on the extensions webpage. The app overview is completely empty.

**Linux distribution and version**
Fedora Silverblue 34 on Wayland

**GNOME Shell version**
Gnome 40.4.0

**Dash-to-Panel version**
43

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
![Bildschirmfoto von 2021-09-15 11-17-40](https://user-images.githubusercontent.com/428567/133407414-d3f39676-f959-44b2-a0b3-c8dbbf7b8352.png)

**Additional Info**
[grid.log](https://github.com/home-sweet-gnome/dash-to-panel/files/7168778/grid.log)

**Comment by ndrwbdnz** [comment]
I have the same issue - app grid is missing when activating dash to panel. When I deactivate dash to panel, app grid is visible again.

**Comment by hansjohn** [comment]
i have the same trouble

**Comment by Kuszki** [comment]
True story. Same problem on Debian, Gnome 40.4.0, X11.

**Comment by SomePineaple** [comment]
I also have the exact same issue. Fedora 34, Gnome 40.4.0, Wayland.
With dash to panel enabled:
![Screenshot from 2021-09-16 21-36-37](https://user-images.githubusercontent.com/69259448/133709930-fc3f5ca9-5ea5-49ab-9f83-dbc035e4643b.png)
When I disable it:
![Screenshot from 2021-09-16 21-39-22](https://user-images.githubusercontent.com/69259448/133710011-ad295abc-4dbe-46f7-91ce-31ac38fb309f.png)

**Comment by zubrzubr** [comment]
The same issue for me.
Fedora 34, Gnome 40.4.0,  Xorg.
two monitors setup

**Comment by escoand** [comment]
Duplicate of #1437
