### ISSUE TITLE
Display scaling breaks icon sizes

### ISSUE THREAD

**Issue by Ambr051us** [home-sweet-gnome/dash-to-panel#1461]
When the display scale is set to anything other than 100%, the favorites and running apps become half-height. It's always half, regardless of whether the scale is 125% or 200%. If there are multiple monitors connected, this happens on all monitors, even the ones set to 100%, as soon as one of the connected monitors gets set to a different scale value - even if the panel is set not to be displayed on the scaled monitor.
![image](https://user-images.githubusercontent.com/44926503/133737386-09410707-95cb-4bf7-805f-149be2a420b8.png)

**Comment by LPFchan** [comment]
duplicate of #1412
