### ISSUE TITLE
Allow the user to define a custom icon for the 'Activities' button and for the Show desktop button on the panel.

### ISSUE THREAD

**Issue by Tuxman2** [home-sweet-gnome/dash-to-panel#1462]
**Describe the idea or feature you'd like**

As the show applications button, allow the user to define a custom icon for the 'Activities' button and for the Show desktop button on the panel (same size as the show applications button).
The changes will be made through the parameters of the Dash-to-panel extension. If the size of the panel is changed, the Activities icon and the show-desktop-button should be expand or shrink as the other icons on the panel.

Thanks.

**Comment by LPFchan** [comment]
I'm all for it! 'Show applications' button already has that feature and it would be nice to remap the Activities button to something that takes up less space and more aesthetically pleasing!

**Comment by AshDThornex** [comment]
I'm all for it as well! Having the option natively would be a great improvement but until then, just wanted to point out that you can already assign a custom icon to the bottom through the "Just Perfection" extension.

**Comment by LPFchan** [comment]
I'd never knew! That's very neat :)
