### ISSUE TITLE
No application in the app grid/application menu.

### ISSUE THREAD

**Issue by alterseries83** [home-sweet-gnome/dash-to-panel#1463]
There are no apps in the app grid/application menu but everything works fine on Dash to Panel

Arch Linux 
Gnome 40.4.0/X11
Dash to Panel Version 43, installed in Gnome Extension website

![Screenshot-20210920091445-1919x1079](https://user-images.githubusercontent.com/60125965/133951667-5734a827-6421-4c7f-b704-978043eb68a5.png)

**Comment by SoumyaRanjanPatnaik** [comment]
I can confirm this on my system.  But I use ArcMenu extension so this is a non-issue for the most part. It does become a minor annoyance when the GNOME default app drawer launches accidentally.

**Comment by CoralCunt** [comment]
Same issue here and also on Arch Linux with Gnome 40.4 .

**Comment by mgholam** [comment]
Same here on fedora 34 gnome 40.3

**Comment by crazivik** [comment]
Same issue on Debian (Bookworm) gnome 40.4

**Comment by ekkinox** [comment]
same issue on EndeavourOS + gnome 40.4

**Comment by vieruuuu** [comment]
same here arch linux

**Comment by Gojodzojo** [comment]
Fix: https://github.com/home-sweet-gnome/dash-to-panel/issues/1437#issuecomment-902875910

**Comment by CoralCunt** [comment]
> Fix: [#1437 (comment)](https://github.com/home-sweet-gnome/dash-to-panel/issues/1437#issuecomment-902875910)

Yeah that fixed it for me, thank you.

**Comment by biji** [comment]
similiar issues:

- https://github.com/home-sweet-gnome/dash-to-panel/issues/1476
- https://github.com/home-sweet-gnome/dash-to-panel/issues/1478
- https://github.com/home-sweet-gnome/dash-to-panel/issues/1485
