### ISSUE TITLE
Number keys trigger hotkeys even when modifier keys(Super and/or alt) are not being pressed

### ISSUE THREAD

**Issue by SoumyaRanjanPatnaik** [home-sweet-gnome/dash-to-panel#1464]
## Bug Description
Using the number keys in the numbers row while typing triggers the hotkey even if the modifier keys (super, ctrl or alt) are not being pressed. Issue persisted even after changing the "hotkeys are activated with" option to "Numeric Numpad". Cannot determine if typing using the numpad causes the same issue as my keyboard lacks one.

### Steps to Reproduce

0. Disable all gnome extensions except Dash-to-Panel (optional).
1. Turn on the "Use hotkeys to activate apps" option in the action tab of Dash-to-Panel configuration window.
2. Open firefox, or any other app having text fields.
3. Type numbers from the number row of your keyboard.

**Outcome**: Hotkeys are triggered. If you have any apps open, typing numbers will minimise or bring the window into forcus.

### Workarounds
The following workarounds seem to fix this issue temporarily
1. Disable "Use hotkeys to activate apps" option. The hotkeys still seem to work, but number overlays doesn't.
2. You may disable Dash-to-Panel altogether, although, the previous option seems to be a much more viable solution.

*NOTE*: In my setup I have ArcMenu extension installed. If I enable the extension, and use the inbuilt search functionality of ArcMenu, the number keys seem to be working, even when hotkeys are enabled.

## System Details
**Linux distribution and version**:  Fedora 34

**GNOME Shell version**:  v40.4

**Dash-to-Panel version**: v43

**Where was Dash-to-Panel installed from?**: The GNOME extensions website

**Additional Info**; I updated the Dash-to-Panel extension today. But the issue wasn't apparent immediately after the update was completed, and only appeared after rebooting my system. I'm also not sure what the update actually was, as I originally installed Dash-to-Panel one week ago, and as per my knowledge, v43 was released much earlier.

**Comment by bdcarr** [comment]
Still happening as of a month ago (when I found this ticket and applied the workaround), and the last release was 3 months ago. So let's not close it.

**Comment by charlesg99** [comment]
Should now work on the master branch, you might have to change the "Hotkeys prefix" in the settings for it to work, can you confirm?

**Comment by steve-todorov** [comment]
I had to enable `HotKeys`, then `Reset To Defaults`, and finally disable `HotKeys`. Seems to be working now. Thanks! :)
