### ISSUE TITLE
Dash-to-panel Settings window clips outside the monitor on 200% Scaling

### ISSUE THREAD

**Issue by LPFchan** [home-sweet-gnome/dash-to-panel#1465]
**Describe the bug**
Dash-to-panel Settings window clips outside the monitor on 200% Scaling. Some buttons and controls are outright inaccessible. The settings pane should be able to shrink down and make the list items scrollable in this case.

**Linux distribution and version**
Ubuntu 21.04

**GNOME Shell version**
GNOME Shell 3.38.4

**Dash-to-Panel version**
Dash-to-Panel version: 42

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
![image_2021-09-21_10-18-48](https://user-images.githubusercontent.com/1547081/134098764-25f11bdd-865b-4416-97ad-01716803eb21.png)
![image_2021-09-21_10-21-44](https://user-images.githubusercontent.com/1547081/134098769-e53d8d77-931e-4edf-a3a3-1f18379873dd.png)

**Additional Info**

**Comment by LPFchan** [comment]
This bug is still present. Thanks

**Comment by charlesg99** [comment]
Seems ok with the latest versions, the scrollbar is available with 200%:

![image](https://user-images.githubusercontent.com/33044886/164343669-becc94f8-1d32-4ee6-9384-66287cd051da.png)

**Comment by charlesg99** [comment]
Should be fixed by the Adwaita settings
