### ISSUE TITLE
Is the Dash to panel extension still maintened ?

### ISSUE THREAD

**Issue by Tuxman2** [home-sweet-gnome/dash-to-panel#1466]
Hello,

There have been no more changes since 1 month or more, and no more news from the main developers since then. 

Is the extension still maintained ? 

Thanks.

**Comment by apinter** [comment]
If I would have to guess I would say no, it is not. Judging simply by the number of unmerged PRs and issues not touched. But that's ok, it's FOSS and up to forking. Guess if people would appreciate the devs more projects wouldn't just go dark. Then I can be wrong and the dev is just taking a break :man_shrugging:

**Comment by Tuxman2** [comment]
Some people here can not resume the project instead of the main developers ?

**Comment by jderose9** [comment]
It's true I haven't personally really had time anymore to maintain this project adequately. Even just keeping up with the breaking upstream changes and reviewing pull requests and issues can take quite a bit of time. Last I talked to @charlesg99 he was still planning to work on this project, but it is FOSS software, so.... if you have the time and inclination to fork it and make it better, I would suggest to just go for it!

That said, watching this pet project grow into something that so many different people have contributed to in so many different ways - language translations, testing, enhancements, bug fixes, design and feature ideas, distro packaging, and more - has been one of the neatest things I have been a part of. Thank you all!!

**Comment by Lucapz** [comment]
https://github.com/home-sweet-gnome/dash-to-panel/issues/1475

Charles posted in the above thread a few days ago and it sounds like he is still going to be active. :)

**Comment by rmkimathi** [comment]
I have to say, Dash-To-Panel extension cured my distro hopping 6 years ago. Everything on the bottom is the way. So after not being so satisfied with Linux Mint late updates, online support and feedback, Dash-To-Panel solved everything for Ubuntu. So install latest Ubuntu and just 1 extension.

Moving on .... I have found a workable alternative to maintain my sanity:

"Hide Top Bar"
( https://extensions.gnome.org/extension/545/hide-top-bar/ )
