### ISSUE TITLE
Dash-to-Panel doesn't fully restart

### ISSUE THREAD

**Issue by Draco18s** [home-sweet-gnome/dash-to-panel#1467]
**Things to do first**
- [x] Confirm that the problem persists when Dash-to-Panel is the only enabled extension. To do so, disable every other extension, then restart gnome-shell by running the `r` command from the prompt that appears when pressing Alt+F2 on an X.org session, or by logging out/in on a Wayland session.
- [x] Look for Dash-to-Panel errors in your log. To do so, run the `journalctl /usr/bin/gnome-shell -f -o cat &` command and reproduce the problem.
  - This is the only thing that shows up when using `r` that does not show up when disabling and re-enabling Dash-to-Panel with Tweaks: https://pastebin.com/pL04iQJ6
- [x] Search existing opened and closed issues to see if the problem has already been reported.
  - Did my best, it's a hard thing to search for

**Describe the bug**
When restarting my machine (or restarting the shell with `r`), Dash to Panel does not *completely* take effect and my applications bar has icons centered instead of left-aligned per my settings. Other settings do take effect, such as disabling the top bar.

**Linux distribution and version**
Pop! OS (Ubuntu 21.04)

**GNOME Shell version**
3.38.4

**Dash-to-Panel version**
42

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**

After restart:
![Screenshot from 2021-09-14 10-25-41](https://user-images.githubusercontent.com/1750680/133286800-20ad88ac-1374-4aaa-9fff-c9453f26a952.png)

Preferred settings:
![Screenshot from 2021-09-14 10-26-46](https://user-images.githubusercontent.com/1750680/133286937-723d2ef0-0418-4df2-b6e2-3da1f4da8330.png)

Video:
https://youtu.be/R7hFQOSHd54
Note how the dock doesn't left-align until it is restarted manually (done both with and without other extensions active), but the top bar is suppressed.

**Comment by staticvoidlol** [comment]
I have the same issue on same versions (happens on Gnome 3.38.3 as well). 

Additionally, on my multi-monitor setup the issue is not present on the additional monitors, i.e. only the default monitor seems to be affected by this behaviour: after restart, the main monitor looks like the "After restart" screenshot above, and the other two look like the "Preferred settings" screenshot above.

I'm happy to log a new issue if required.

**Comment by staticvoidlol** [comment]
> I have the same issue on same versions (happens on Gnome 3.38.3 as well).
> 
> Additionally, on my multi-monitor setup the issue is not present on the additional monitors, i.e. only the default monitor seems to be affected by this behaviour: after restart, the main monitor looks like the "After restart" screenshot above, and the other two look like the "Preferred settings" screenshot above.
> 
> I'm happy to log a new issue if required.

It looks like disabling the dock via **_Desktop > Dock > Enable Dock_** fixed the issue for me.

**Comment by Draco18s** [comment]
Oh good find. Fixed for me as well.

**Comment by JL102** [comment]
> It looks like disabling the dock via **_Launcher > Desktop > Dock > Enable Dock > Uncheck_** fixed the issue for me.

Fixed for me too. Can this be added to the FAQ, so that it's easier for people to find the solution?
"
Why isn't Dash-to-Panel loading when I restart? Disable the dock via _**Launcher > Desktop > Dock > Enable Dock > Uncheck**_.
"

**Comment by pablomalo** [comment]
I realize this issue is closed but maybe one of the original posters can help me out...

I can't seem to find this **Launcher > Desktop > Dock > Enable Dock > Uncheck** setting mentioned by @staticvoidlol, @Draco18s and @JL102.

A screenshot would be much appreciated.

**Comment by Draco18s** [comment]
Launcher -> Settings
[Peek 2022-07-09 01-29.webm](https://user-images.githubusercontent.com/1750680/178094580-0c71133d-9cbc-43f4-95f5-282a619ad631.webm)

**Comment by pablomalo** [comment]
@Draco18s Thank you!
