### ISSUE TITLE
Hiding of panel randomly...

### ISSUE THREAD

**Issue by MeroWing738** [home-sweet-gnome/dash-to-panel#1472]
----  Solved on my machine - solution below  ----

Hello, using Debian 11 unstable (same with stable) and Gnome 40.4 (same with 3.38) with newest Dash to Panel installed via Firefox plugin under Wayland I discover random hiding of panel in the following manner:

I always use autohiding taskbar since Windows 95 - it's the only behaviour that makes sense for me as not crippling the things I want to see. Since then there are occasional problems with that feature some more frustrating than others.

When going down with the mouse in half the cases the panel pops up and disappears right after that. Going up and down again may or may not show the panel consistently, only making it disappear when leaving panel area.

The only way to relatively securely avoid this behaviour is to go down diagonally relatively fast - the moving to the side while touching the bottom of the screen seems to avoid the behaviour nearly reproducably. But of course that's not what one intends and also I cannot offer such a behaviour to clients.

No other extensions are installed, theme is Adwaita - it's more or less out of the box Debian.

Any ideas why this occurs? Hint: I also have flickering of the panel when I enable showing in fullcreen apps and am running video apps for example - sometimes the panel appears as wanted, sometimes it starts flickering, sometimes it disappears but still accepts clicks. Those topics could be related.

Thanks for any help or bug removement.

----  As I have no idea how this GitHub-thing works and if my solution is welcome here the reason and changed code for everyone who is interested  ----

The problem arises whenever the mouse is moved down, touches the bottom of the screen and is not moved any pixel which happens relatively often. Then the panel does not update it's "hover"-property accordingly which may be a bug of gnome by itself as not only mouse movement but also window movement has effect on hover. As gnome does not recognize this by itself i simply help it to do so. I inserted one line in "intellihide.js" in function "_checkMousePointer", "this._panelBox.hover=true;". Here's the complete function:

    _checkMousePointer: function(x, y) {
        let position = this._dtpPanel.geom.position;

        if (!this._panelBox.hover && !Main.overview.visible &&
            ((position == St.Side.TOP && y <= this._monitor.y + 1) || 
             (position == St.Side.BOTTOM && y >= this._monitor.y + this._monitor.height - 1) ||
             (position == St.Side.LEFT && x <= this._monitor.x + 1) ||
             (position == St.Side.RIGHT && x >= this._monitor.x + this._monitor.width - 1)) &&
            ((x >= this._monitor.x && x < this._monitor.x + this._monitor.width) && 
             (y >= this._monitor.y && y < this._monitor.y + this._monitor.height)))
        {
            this._panelBox.hover=true;
            this._queueUpdatePanelPosition(true);
        }
    },

As I hate artificial latencies I also deleted some zeros at the beginning of this file - so I get (having deactivated animations everywhere) a blazing fast panel that does not waste my time driving me crazy and making me full of hate:

const CHECK_POINTER_MS = 20;
const CHECK_GRAB_MS = 40;
const POST_ANIMATE_MS = 50; 
const MIN_UPDATE_MS = 25;

Last but not least I have the bug (that seems to be reported earlier) that no icons are shown when clicking on the left button and getting overwiew. There's only the search bar and a small preview of the screen. If something is typed into the bar then some icons show up if matching the search. Not really important for me but definitely unacceptable in production environments. (Where this extension belongs to more than any extension that has ever been written.)

Regards!

**Comment by nnemkin** [comment]
Thanks, man. Your fix works great.

**Comment by MeroWing738** [comment]
Hi, Nikita,

thanks for your kind feedback. It really shocks me how other programmers work. Bugs stay open for felt decades, are negated and people who want to help are ignored.

I really have no idea how these people think and if they think at all...  ;-)

If it was another way we would live in a completely different world of software giving us all we ever had wanted. Maybe in our next life things will change.

Here's a an incredible example: GIMP has not changed in any (seeable) way since a decade. Meanwhile Photoshop has learned some cool things. No idea what their plans are. Maybe they do not have ones.

Have fun!

Volker
