### ISSUE TITLE
Application Icons in the app grid dissapear when enabling dash-to-panel [Closed, bug fixed]

### ISSUE THREAD

**Issue by jakubcze12** [home-sweet-gnome/dash-to-panel#1485]
**Describe the bug**
When enabling the dash-to-panel extension, the icons in the app grid disappear. When disabling the extension, they come back. This happens only on fedora for me. On gentoo it doesn't happen. 

**Linux distribution and version**
Fedora GNU/Linux 34 (updated to the latest version)

**GNOME Shell version**
GNOME Shell 40.4 (wayland)

**Dash-to-Panel version**
Version 43

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
https://i.redd.it/bhgd5qfygdt71.png

**Additional Info**

**Comment by jakubcze12** [comment]
Update: The bug was probably fixed, I compiled the extension from source and it works fine now. Update the gnome-store version please.

**Comment by shah-xad** [comment]
I'm also facing the same issue on 21.10.

**Comment by shah-xad** [comment]
> Update: The bug was probably fixed, I compiled the extension from source and it works fine now. Update the gnome-store version please.

Thanks, it worked like a charm.

**Comment by tjme** [comment]
Same issue here (no app grid on Ubuntu 21.10 and current dash-to-panel v43)
