### ISSUE TITLE
Change volume with scroll must ignore switch workspace

### ISSUE THREAD

**Issue by renantmagalhaes** [home-sweet-gnome/dash-to-panel#1486]
**Describe the idea or feature you'd like**
Make it possible to ignore the Switch panel action (Switch workspace) on the volume icon.

**Is your feature request related to a problem? Please describe.**
When the Switch panel action with the Switch workspace action is enabled, and we scroll in the volume icon(to lower or increase the volume) it also changes the workspace and  I believe that`s not the intention. 

https://i.imgur.com/emzFqyV.png

**extra info**
PopOS 21.04
X11
Dash-to-panel version 42

**Comment by mrerdem** [comment]
On Wayland and Ubuntu 21.10, it works as requested.

**Comment by molnarszilard** [comment]
Hi!
I have this problem using EndeavourOS, Gnome 47.2, and Wayland.
