### ISSUE TITLE
Right click doesn't work, GNOME 41

### ISSUE THREAD

**Issue by adamant-pwn** [home-sweet-gnome/dash-to-panel#1488]
**Describe the bug**
Right click on the panel or on the icons in "favorite" section of the panel. Expected: context menu, Result: nothing (see logs above).

 `journalctl /usr/bin/gnome-shell -f -o cat &` output:
```
JS ERROR: TypeError: this._menu.popup is not a function
popupMenu@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:675:20
vfunc_button_press_event@resource:///org/gnome/shell/ui/appDisplay.js:3202:18

JS ERROR: TypeError: this._menu.popup is not a function
popupMenu@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:1797:20
_onButtonPress@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panel.js:1070:38
```

**Linux distribution and version**
Arch Linux x86_64

**GNOME Shell version**
GNOME Shell 41.0

**Dash-to-Panel version**
43 (b7213be14c346872ff41d26da8ed15acee9c4fbe)

**Where was Dash-to-Panel installed from?**
https://aur.archlinux.org/packages/gnome-shell-extension-dash-to-panel-git/

**Comment by CountOmega** [comment]
I have the same issue on Debian testing, GNOME shell 41.

**Comment by philippun1** [comment]
I think #1506 fixes this.

**Comment by LionHeartP** [comment]
> I think #1506 fixes this.

Indeed it does. Thank you very much!

**Comment by tr1p0p** [comment]
still having this issue with the last installation from source. How can i see if i have #1506 merged into ? On last fedora 35

**Comment by LionHeartP** [comment]
> still having this issue with the last installation from source. How can i see if i have #1506 merged into ? On last fedora 35

You don't probably don't have #1506 merged if you're synced with the main repo since it hasn't been merged yet. You can manually patch the files though.
