### ISSUE TITLE
Unable to show applications after dash-to-panel extension installed

### ISSUE THREAD

**Issue by zidansec** [home-sweet-gnome/dash-to-panel#1489]
After installing the dash-to-panel extension, I can't _show apps_ when the **"Show Applicatins"** button is clicked.
This happened on **Ubuntu 21.10 Gnome Version 40**.

![screenshot](https://i.ibb.co/hZG9cLJ/Screenshot-from-2021-10-17-21-53-01.png)

**Comment by eypsilon** [comment]
The App Launcher removes already each Symbol if you set it as "Favorite", so maybe this new feature causes a conflict.

Ubuntu 21.10 - GNOME 40.4.0 - Display: X11 (wayland has same issue)

![applauncher-before](https://user-images.githubusercontent.com/27016183/137643198-8f612249-3314-49a2-a6d1-67ae5c2fd55a.png)
![applauncher-after](https://user-images.githubusercontent.com/27016183/137643201-943cd792-1a92-4605-9931-a2d3558e1856.png)

**Comment by eypsilon** [comment]
This fixed the issue for me.

https://github.com/home-sweet-gnome/dash-to-panel/issues/1437#issuecomment-902875910
