### ISSUE TITLE
extension doesn't work with the nautilus icon

### ISSUE THREAD

**Issue by nmrcardoso** [home-sweet-gnome/dash-to-panel#1497]
**Describe the bug**
Nautilus icon does not group, every click opens a new window. The right click over the nautilus icon does not show any open window, although there are several ones are open.
Tested many other and all working, also with Nemo is working fine.

**Linux distribution and version**
Ubuntu 21.10

**GNOME Shell version**
GNOME Shell 40.5

**Where was Dash-to-Panel installed from?**
Bug happens with the last version from GNOME extensions website, and from from github.

**Comment by risafov** [comment]
Same here.
And if you remove it from favorites, it can be added back.

Ubuntu 21.10
GNOME Shell 40.4.0

**Comment by pabloh84** [comment]
Same here. It also seems that when removed from favorites no icon appears in "Running applications"

**Comment by zanastar** [comment]
https://github.com/home-sweet-gnome/dash-to-panel/issues/1500#issuecomment-962511964

**Comment by enorrmann** [comment]
> [#1500 (comment)](https://github.com/home-sweet-gnome/dash-to-panel/issues/1500#issuecomment-962511964)

this worked for me ! thx
