### ISSUE TITLE
Option to center apps

### ISSUE THREAD

**Issue by Hativ** [home-sweet-gnome/dash-to-panel#150]
It would be create to have an option to center the apps like a dock. On 21:9 screens it's bad for productivity to have the apps at left.

A dock is not what I want because I like the panel with the show applications button on left and clock and status menu at right.

As a hack I have created apps with a transparent icon and added them before the other apps to my favorite apps. Screenshot: http://i.imgur.com/7JIK2e0.jpg

**Comment by SharpOB** [comment]
I like this idea alot.

**Comment by abakkk** [comment]
pull requests #288

**Comment by jderose9** [comment]
Thanks so much to @abakkk for completing this!!

**Comment by jderose9** [comment]
Actually, going to re-open for now as the original request was asking for the `Show Apps` button to be on the left. Should it always be on left or should this be configurable?

**Comment by jderose9** [comment]
Anyone care to weigh in on whether the Show Apps button should always be centered when the app icons are, always be on the left, or be independently configurable?

**Comment by josuedavidurand** [comment]
I think it's a good idea.
The best would be to have options:

- Left
- Center on monitor
- Center on monitor with left menu

- Center on content
- Center on content with left menu

The first three are the most ergonomic. The last two can be added if several people appreciate

> Best gnome extention :heart:

**Comment by enzosanchezewe** [comment]
i have tried to copy this
.show-apps {
margin-left: xxx px;
}
no matter what number i put on the xxx part, it doest do anything

**Comment by charlesg99** [comment]
Hello, this is now possible on the latest master, please try it out! Thanks!
