### ISSUE TITLE
dash-to-panel: Folders don't appear on taskbar

### ISSUE THREAD

**Issue by pierokarto1989** [home-sweet-gnome/dash-to-panel#1500]
**Things to do first**
problem persists when Dash-to-Panel is the only enabled extension

**Describe the bug**
When I open a folder, it does not appear in the taskbar. As you can see, I have opened a _video_ folder, but it is not displayed on the taskbar.

**Linux distribution and version**
Ubuntu 21.10

**GNOME Shell version**
GNOME Shell 40.5

**Dash-to-Panel version**
Version: 43

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
1. dash-to-panel extension enabled

![1](https://user-images.githubusercontent.com/32592858/138568492-376550b8-415e-4c2c-836e-9e138cf7292d.png)

2. dash-to-panel extension disabled

![2](https://user-images.githubusercontent.com/32592858/138568506-fdbd492c-b837-4e2e-9e74-f73c1391d146.png)

**Comment by nename0** [comment]
The workaround from above did not work for me. So I traced it down and here is the workaround that works for me:
```
gsettings set org.gnome.shell.extensions.dash-to-dock isolate-locations false
```
Now you might ask how does a dash-to-dock setting affect dash-to-panel?
Well dash-to-dock [hooks into nautilus](https://github.com/micheleg/dash-to-dock/pull/1402/commits/0b58602ab7abfaec9bb35c7945520b2402b98a0c), for this isolate-locations feature, but does NOT cleanup these hooks!
It's these hooks that then create the `dockManager is null` error, which prevents dash-to-panel from seeing the windows.

**Comment by Lucapz** [comment]
Wonder why manually disabling dash-to-dock and then logging out and back in again worked for me?

Any hows thanks for finding a specific fix.

**Comment by Lucapz** [comment]
@nename0 

I did consider purging dash-to-dock but wasn't sure if it would break anything.

**Comment by nename0** [comment]
Ah Ok. The issue was I disabled dash-to-dock (or ubuntu-dock in my case) using the gnome extension [website](https://extensions.gnome.org/local/).
But using the Gnome Extension Application I did work.
I really don't know why disabling using the website leads to dash-to-dock been created and destroyed (instead of been skipped) thereby leaving erroring listeners on nautilus.

**Comment by webbedfeet-stu** [comment]
> The workaround from above did not work for me. So I traced it down and here is the workaround that works for me:
> 
> ```
> gsettings set org.gnome.shell.extensions.dash-to-dock isolate-locations false
> ```
> 
> Then logout and login. Now you might ask how does a dash-to-dock setting affect dash-to-panel? Well dash-to-dock [hooks into nautilus](https://github.com/micheleg/dash-to-dock/pull/1402/commits/0b58602ab7abfaec9bb35c7945520b2402b98a0c), for this isolate-locations feature, but does NOT cleanup these hooks! It's these hooks that then create the `dockManager is null` error, which prevents dash-to-panel from seeing the windows.

Worked for me, also you can just do a restart of gnome-shell doing `Alt+F2` and inputting `r`, rather than a full restart or relog.

**Comment by chnavarro** [comment]
Is still present

Linux distribution and version
Fedora 35

GNOME Shell version
GNOME Shell 41.5

Dash-to-Panel version
46

The fix from @davidmartos96 on  https://github.com/home-sweet-gnome/dash-to-panel/issues/1152#issuecomment-861702573 just does not work anymore
