### ISSUE TITLE
Ubuntu 21.10 - Dash-to-Panel problem, all the Apps into the Menu Screen section disappear.

### ISSUE THREAD

**Issue by Special-Niewbie** [home-sweet-gnome/dash-to-panel#1507]
**Describe the bug**
- After the latest upgrade from _Ubuntu 20.04_ to _Ubuntu 21.10_ (Impish Indri), Dash-to-Panel starts to create a problem with the Start Application Menu. All the Apps into the Menu Screen section disappear. If I disable Dash-to-Panel extension, all the apps appear back in place.

**Linux distribution and version**
- Ubuntu 21.10 Impish Indri

**GNOME Shell version**
- GNOME Shell 40.5

**Dash-to-Panel version**
- Dash-to-Panel v. 43

**Where was Dash-to-Panel installed from?**
- The GNOME extensions website (https://extensions.gnome.org/)

**Screenshots / Video captures**
![Schermata da 2021-10-30 11-49-02](https://user-images.githubusercontent.com/64843123/139519532-11c7f9ab-aee6-4125-bfb6-6678f5bc09dc.png)

**Comment by Special-Niewbie** [comment]
Ok, I found now this temporary fix, but it will disable the Dash transparency, anyone has the over fix for the transparency Dash, on this FIX below?

Temporary Fix:
https://raw.githubusercontent.com/home-sweet-gnome/dash-to-panel/81af73b23911cbbdce807566ed6ef2a864417d6c/overview.js

**Comment by philippun1** [comment]
The package in Ubuntu 21.10 does not contain the latest fixes (mainly because there is no actual release of dtp...). You can install the [package from 22.04](https://launchpad.net/ubuntu/+archive/primary/+files/gnome-shell-extension-dash-to-panel_43+git20210906-b7213be-2_all.deb), this is a snapshot package from the latest git master.

**Comment by quentincaffeino** [comment]
Same on fedora 5.14.14-200.fc34.x86_64

**Comment by Special-Niewbie** [comment]
> The package in Ubuntu 21.10 does not contain the latest fixes (mainly because there is no actual release of dtp...). You can install the [package from 22.04](https://launchpad.net/ubuntu/+archive/primary/+files/gnome-shell-extension-dash-to-panel_43+git20210906-b7213be-2_all.deb), this is a snapshot package from the latest git master.

I LOVE YOU MAN!!!!!! Everything it's solved..... To whom it's interested and doesn't want to install by .deb as snapshot package file; I attach the files to replace in the main Dash-to-Folder, please place the files in this way if you have got already installed the extension:

1)  Place the 6 files into /home/YOUR NAME ACCOUNT/.local/share/gnome-shell/extensions
2) Place the unique file into /locale/es to /home/cris/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/es

And everything will start to working , thanks to @philippun1 

here are the files to download: 
[Files to replace.zip](https://github.com/home-sweet-gnome/dash-to-panel/files/7446661/Files.to.replace.zip)

**Comment by chdslv** [comment]
> The package in Ubuntu 21.10 does not contain the latest fixes (mainly because there is no actual release of dtp...). You can install the [package from 22.04](https://launchpad.net/ubuntu/+archive/primary/+files/gnome-shell-extension-dash-to-panel_43+git20210906-b7213be-2_all.deb), this is a snapshot package from the latest git master.

Thanks!
I put this on ~/.local/share/applications/gnome-shell/extensions. I know that this won't change, when the D2P in Gnome Shell Extensions site changes. But, what's the D2P there really for Gnome 40? Not the actual release as you say?

**Comment by hobbsy** [comment]
@Special-Niewbie what is the extension or tool called that is displaying temperatures in your bottom-right section of your screen please?

**Comment by Special-Niewbie** [comment]
> @Special-Niewbie what is the extension or tool called that is displaying temperatures in your bottom-right section of your screen please?

Hi, sure, it's the Gnome Shell Extension called FREON. If you install Freon, you should install the "lm_sensors" lib as well......
