### ISSUE TITLE
GNOME 41 Support

### ISSUE THREAD

**Issue by Tubb7** [home-sweet-gnome/dash-to-panel#1512]
Making this to keep track of support for GNOME 41, as there seems to be multiple bumps that I observed after using a version built from source.

**Comment by Durlyn** [comment]
after falling asleep, the panel goes to the right.

**Comment by ShrirajHegde** [comment]
Also, no extensions seem to follow dark theme. Including dash-to-panel

**Comment by ShrirajHegde** [comment]
@charlesg99  Please pin this along with Gnome 40 support.

**Comment by revane** [comment]
I don't know if my computer updated to Gnome 41 without me realizing overnight. This morning I was notified there was an update for dash-to-panel and when I applied it, it failed and now the plug-in is non-functional. Did the plug-in previously have support for 41 but was then removed by the update? (as #144960 seems to imply).

**Comment by ShrirajHegde** [comment]
> I don't know if my computer updated to Gnome 41 without me realizing overnight. This morning I was notified there was an update for dash-to-panel and when I applied it, the install failed and now the plug-in is non-functional. Did the plug-in previously have support for 41 but was then removed by the update? (as [NixOS/nixpkgs#144960](https://github.com/NixOS/nixpkgs/pull/144960) seems to imply).

yes, https://github.com/home-sweet-gnome/dash-to-panel/commit/53660a07b0eac8d0f518d3f89104bfb70fd06b96

You can use `gsettings set org.gnome.shell "disable-extension-version-validation" true ` to disable version validation, so it doesn't say incompatible. Or you can add it manually and install with make. 

It is pretty unstable as of now on gnome 41.

**Comment by philippun1** [comment]
Manjaro testing now has gnome 41.1 and dtp v45. I cannot confirm any of the mentioned issues. Besides #1513 everything seems to work nicely.
@charlesg99 Can you maybe pin this issue? Otherwise we will have the 4th gnome 41 issue once this one is pushed down to the 2nd page.

**Comment by lfom** [comment]
Dash to Panel crashes after the system is unlocked (it was not suspended, just locked + screen off). Extensions app shows the extension is disabled and this error:

`actor.has_style_class_name is not a function`

Logging out then back in and it works normally until the next time screen is locked.
Filtering systemd-journal for 'dashtopanel' does not show any crash, only warnings (many repeated), but `gnome-shell` crashed.

Garuda/Arch (Gnome 41.1).

**Comment by philippun1** [comment]
@charlesg99 I fixed #1513 / #1548 with #1556

**Comment by tekstryder** [comment]
> @charlesg99 I fixed #1513 / #1548 with #1556

That fix would be a game-changer for me. It's the only issue I currently face with this amazing extension.

Is there any chance for another release before gnome 42.x?
