### ISSUE TITLE
Hovering the panel with an icon does not open the overview in Wayland

### ISSUE THREAD

**Issue by mbousq** [home-sweet-gnome/dash-to-panel#1514]
**Describe the bug**
Hovering the panel with an icon does not open the overview in **wayland** (works with xorg).

**Linux distribution and version**
Ubuntu 21.10

**GNOME Shell version**
GNOME Shell 40.5

**Dash-to-Panel version**
Version 44

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Additional Info**
- Happened after the last maintenance update.
- Thanks everyone for all the work :heart:

**Comment by mrerdem** [comment]
Extra info: The issue does not exist on the same system with Gnome shell 40.4.
