### ISSUE TITLE
Artifacts on the panel after hibernation

### ISSUE THREAD

**Issue by Durlyn** [home-sweet-gnome/dash-to-panel#1517]
**Describe the bug**
After exiting sleep mode, only the button of the current window remains on the panel

**Linux distribution and version**
Fedora 35

**GNOME Shell version**
GNOME Shell 41.1

**Dash-to-Panel version**
Dash-to-Panel version 45

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
![image](https://user-images.githubusercontent.com/874902/141467187-ea667420-6cb9-420a-b588-5e4a5fd69e35.png)

**Additional Info**

**Comment by shrisha108** [comment]
Same here with 4 different computers. All Fedoras 35

**Comment by charlesg99** [comment]
Does it happen if you disable all your other extensions, then restart gnome-shell, then lock/unlock?

I can't reproduce this, which means this is probably something on your system that conflicts with the extension. Try running journalctl `/usr/bin/gnome-shell -f -o cat &`, then lock/unlock your system and post the resulting logs here.
