### ISSUE TITLE
Hovering app animation glitch with Intellihide

### ISSUE THREAD

**Issue by jmartinez23** [home-sweet-gnome/dash-to-panel#1518]
The animation of the icons glitches when combined with the intellihide feature. The position of the animated icons are offset  when hovering as the panel becomes visible. It looks like the positioning of the icons is relative to the panel "hidden" position instead of the "visible" or "current" position. For example, when the panel is at the bottom, the hovered icons appear offset down. As I hover over other icons when the panel is visible, the positioning will correct itself. A quick fix I found is to have the panel "hide and reveal duration" set to a very small amount.

**Comment by PROxZIMA** [comment]
I too came across this glitch.

https://user-images.githubusercontent.com/43103163/154425580-1c153a20-0f98-484d-af20-0eb74edba15a.mp4

**Comment by charlesg99** [comment]
Fixed in v46
