### ISSUE TITLE
Panel hides even on desktop with Intellihide for focused windows

### ISSUE THREAD

**Issue by yrzaa** [home-sweet-gnome/dash-to-panel#1521]
**Describe the bug**
With intellihide from focused windows is enabled, the panel hides even when on the desktop with no windows open. This typically happens only after a window is opened/closed after login.

Expected behaviour: Panel hides only from focused windows

**Linux distribution and version**
Ubuntu 21.10

**GNOME Shell version**
Gnome 40.05

**Dash-to-Panel version**
Dash to panel 44

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Comment by hasanmerkit** [comment]
Same issue.
Linux distro: Ubuntu 22.04
Gnome Shell: 40.5
Dash-to-Panel: 44
Gnome Version: 41.1

When playing full screen game, can see panel by pressing super key but if i click, just panel hides.

**Comment by charlesg99** [comment]
Is the problem happening when changing workspaces by chance? Some changes affecting the proximity detection were added to the master branch, please try it and see if the issue persists.
