### ISSUE TITLE
Extension load failure on GNOME 41

### ISSUE THREAD

**Issue by imi415** [home-sweet-gnome/dash-to-panel#1522]
**Things to do first**
- Confirm that the problem persists when Dash-to-Panel is the only enabled extension. To do so, disable every other extension, then restart gnome-shell by running the `r` command from the prompt that appears when pressing Alt+F2 on an X.org session, or by logging out/in on a Wayland session.
- Look for Dash-to-Panel errors in your log. To do so, run the `journalctl /usr/bin/gnome-shell -f -o cat &` command and reproduce the problem.
- Search existing opened and closed issues to see if the problem has already been reported.

**Describe the bug**
The extension failed to load, causing the whole panel unuseable, and since the extension load is failed, there is no way to disable it except uninstalling.

**Linux distribution and version**
Arch Linux

**GNOME Shell version**
GNOME Shell 41.1

**Dash-to-Panel version**
v45

**Where was Dash-to-Panel installed from?**
GNOME extensions website

**Screenshots / Video captures**
![image](https://user-images.githubusercontent.com/10695162/141666378-09c81829-d354-4c63-a1c6-c498e3103f93.png)
![image](https://user-images.githubusercontent.com/10695162/141666407-b2215812-436e-432c-a43b-3035f4506dfb.png)

<details>
<summary> Log entries </summary>
<pre>
11月 14 11:24:19 imi415 gnome-shell[2296]: Some code accessed the property 'AppMenu' on the module 'appDisplay'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
11月 14 11:24:19 imi415 gnome-shell[2296]: Timelines with detached actors are not supported
11月 14 11:24:19 imi415 gnome-shell[2296]: Timelines with detached actors are not supported
11月 14 11:24:19 imi415 gnome-shell[2296]: JS ERROR: Extension dash-to-panel@jderose9.github.com: TypeError: proto[Gi.hook_up_vfunc_symbol] is not a function
                                            hookVfunc@/home/imi415/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/utils.js:350:39
                                            enable@/home/imi415/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panel.js:236:23
                                            _createPanel@/home/imi415/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:405:15
                                            enable@/home/imi415/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:84:34
                                            _enable@/home/imi415/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:106:18
                                            enable@/home/imi415/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:66:5
                                            _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:166:32
                                            loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:349:26
                                            _onInstallButtonPressed@resource:///org/gnome/shell/ui/extensionDownloader.js:272:35
                                            Async*addButton/<@resource:///org/gnome/shell/ui/dialog.js:136:41
11月 14 11:24:19 imi415 gnome-shell[2296]: Spurious clutter_actor_allocate called for actor 0x55e74b133380/<unnamed>[<Gjs_ui_panel_PanelCorner>:0x55e74b133380] which isn't a descendent of the stage!
11月 14 11:24:19 imi415 gnome-shell[2296]: Spurious clutter_actor_allocate called for actor 0x55e74b134a10/<unnamed>[<Gjs_ui_panel_PanelCorner>:0x55e74b134a10] which isn't a descendent of the stage!
11月 14 11:24:19 imi415 gnome-shell[2296]: Can't update stage views actor <unnamed>[<StBin>:0x55e74b139280] is on because it needs an allocation.
11月 14 11:24:19 imi415 gnome-shell[2296]: Can't update stage views actor <panelActivities>[<Gjs_ui_panel_ActivitiesButton>:0x55e74b1386c0] is on because it needs an allocation.
11月 14 11:24:19 imi415 gnome-shell[2296]: Can't update stage views actor <unnamed>[<StLabel>:0x55e74b13ae40] is on because it needs an allocation.
11月 14 11:24:19 imi415 gnome-shell[2296]: Can't update stage views actor <unnamed>[<ClutterText>:0x55e74b13b550] is on because it needs an allocation.
11月 14 11:24:19 imi415 gnome-shell[2296]: Can't update stage views actor <unnamed>[<StBin>:0x55e74b3ab260] is on because it needs an allocation.
11月 14 11:24:19 imi415 gnome-shell[2296]: Can't update stage views actor <unnamed>[<Gjs_ui_panel_AggregateMenu>:0x55e74b40ea40] is on because it needs an allocation.
11月 14 11:24:19 imi415 gnome-shell[2296]: Can't update stage views actor <unnamed>[<StBoxLayout>:0x55e74b4118c0] is on because it needs an allocation.
11月 14 11:24:19 imi415 gnome-shell[2296]: Can't update stage views actor <unnamed>[<Gjs_status_network_Indicator>:0x55e74b3dda40] is on because it needs an allocation.
11月 14 11:24:19 imi415 gnome-shell[2296]: Can't update stage views actor <unnamed>[<StIcon>:0x55e74b3df060] is on because it needs an allocation.
11月 14 11:24:19 imi415 gnome-shell[2296]: Can't update stage views actor <unnamed>[<ClutterActor>:0x55e74babaf80] is on because it needs an allocation.
11月 14 11:24:19 imi415 gnome-shell[2296]: Can't update stage views actor <unnamed>[<Gjs_status_volume_Indicator>:0x55e74b514100] is on because it needs an allocation.
11月 14 11:24:19 imi415 gnome-shell[2296]: Can't update stage views actor <unnamed>[<StIcon>:0x55e74b517e30] is on because it needs an allocation.
11月 14 11:24:19 imi415 gnome-shell[2296]: Can't update stage views actor <unnamed>[<ClutterActor>:0x55e74babb2a0] is on because it needs an allocation.
11月 14 11:24:19 imi415 gnome-shell[2296]: Can't update stage views actor <unnamed>[<Gjs_status_power_Indicator>:0x55e74b46e9e0] is on because it needs an allocation.
11月 14 11:24:19 imi415 gnome-shell[2296]: Can't update stage views actor <unnamed>[<StIcon>:0x55e74b478d00] is on because it needs an allocation.
11月 14 11:24:19 imi415 gnome-shell[2296]: Can't update stage views actor <unnamed>[<ClutterActor>:0x55e74babb5c0] is on because it needs an allocation.
11月 14 11:24:19 imi415 gnome-shell[2296]: Can't update stage views actor <unnamed>[<StBin>:0x55e74b068890] is on because it needs an allocation.
11月 14 11:24:19 imi415 gnome-shell[2296]: Can't update stage views actor <unnamed>[<Gjs_ui_dateMenu_DateMenuButton>:0x55e74b0672e0] is on because it needs an allocation.
11月 14 11:24:19 imi415 gnome-shell[2296]: Can't update stage views actor <unnamed>[<StBoxLayout>:0x55e74b077260] is on because it needs an allocation.
11月 14 11:24:19 imi415 gnome-shell[2296]: Can't update stage views actor <unnamed>[<StWidget>:0x55e74b075b90] is on because it needs an allocation.
11月 14 11:24:19 imi415 gnome-shell[2296]: Can't update stage views actor <unnamed>[<StLabel>:0x55e74b06fbc0] is on because it needs an allocation.
11月 14 11:24:19 imi415 gnome-shell[2296]: Can't update stage views actor <unnamed>[<ClutterText>:0x55e74b071090] is on because it needs an allocation.
11月 14 11:24:19 imi415 gnome-shell[2296]: Can't update stage views actor <unnamed>[<Gjs_ui_dateMenu_MessagesIndicator>:0x55e74b0728b0] is on because it needs an allocation.
11月 14 11:24:19 imi415 gnome-shell[2296]: Can't update stage views actor <unnamed>[<ClutterActor>:0x55e74da732c0] is on because it needs an allocation.
11月 14 11:24:19 imi415 gnome-shell[2296]: Can't update stage views actor <unnamed>[<Gjs_ui_dash_ShowAppsIcon>:0x55e74b7f75d0] is on because it needs an allocation.
11月 14 11:24:19 imi415 gnome-shell[2296]: Can't update stage views actor <unnamed>[<StButton>:0x55e74d05be70] is on because it needs an allocation.
11月 14 11:24:19 imi415 gnome-shell[2296]: Can't update stage views actor <unnamed>[<Gjs_ui_iconGrid_BaseIcon>:0x55e74e63e330] is on because it needs an allocation.
11月 14 11:24:19 imi415 gnome-shell[2296]: Can't update stage views actor <unnamed>[<StBoxLayout>:0x55e74e39ace0] is on because it needs an allocation.
11月 14 11:24:19 imi415 gnome-shell[2296]: Can't update stage views actor <unnamed>[<StBin>:0x55e74a4b9f00] is on because it needs an allocation.
11月 14 11:24:19 imi415 gnome-shell[2296]: Can't update stage views actor <unnamed>[<StIcon>:0x55e749e63230] is on because it needs an allocation.
11月 14 11:24:19 imi415 gnome-shell[2296]: Can't update stage views actor <unnamed>[<ClutterActor>:0x55e74b602970] is on because it needs an allocation.
11月 14 11:24:19 imi415 gnome-shell[2296]: cogl_framebuffer_set_viewport: assertion 'width > 0 && height > 0' failed
11月 14 11:24:19 imi415 gnome-shell[2296]: cogl_framebuffer_set_viewport: assertion 'width > 0 && height > 0' failed

</pre>
</details>

**Comment by 488315** [comment]
i have that issue as well

**Comment by imi415** [comment]
Sorry, I replaced gjs with gjs-git then forgot it. Closing now.
