### ISSUE TITLE
panel spacing and padding [bug]

### ISSUE THREAD

**Issue by ghost** [home-sweet-gnome/dash-to-panel#1523]
Vanilla panel:
![vanilla](https://user-images.githubusercontent.com/74601193/141833601-aa967e9f-e5be-4110-b697-7055828851c0.png)

With extension:
![dash_to_panel](https://user-images.githubusercontent.com/74601193/141833594-2a4bdcfc-d9bd-4f22-9b33-8c726d2ee951.png)

Issues:
\> Space above the panel's gone
\> icons in the panel are not vertically centered.

Can there exists a setting to control cell spacing manually for different directions rather than one group setting?

**Comment by puphime** [comment]
I have this same issue and I would appreciate at least information on what the elements are in CSS so I could fix it myself

**Comment by charlesg99** [comment]
It would be the theme's responsibility to make it work correctly. See flat-remix for an example of floating panel that plays nice with dash to panel. Thanks!
