### ISSUE TITLE
Dash to Panel is no longer visible after locking the screen

### ISSUE THREAD

**Issue by TheNamibian** [home-sweet-gnome/dash-to-panel#1526]
Hi, 
I noticed some issues with Dash to Panel after my upgrade to Fedora 35 (yes I waited for Dash to Panel to support Gnome 41). Upgrade path was fresh install of Fedora 33, upgrade to 34 and now to 35. When locking the screen manually or the normal screen timeout, Dash to Panel disappeared after logging in again. I checked the logs and tried several different steps. All are documented in the attached file.

**Things to do first**
- Confirm that the problem persists when Dash-to-Panel is the only enabled extension.
-- With and without other extensions - different results - all log entries documented in attached file.

- Search existing opened and closed issues to see if the problem has already been reported.
-- could not find anything matching.

**Describe the bug**
Dash to Panel is no longer visible after locking the screen.

**Linux distribution and version**
Fedora 35
Linux linux 5.14.17-301.fc35.x86_64 #1 SMP Mon Nov 8 13:57:43 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**GNOME Shell version**
GNOME Shell 41.1

**Dash-to-Panel version**
45

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Additional Info**
Logs are attached in
[DashToPanel_logs.txt](https://github.com/home-sweet-gnome/dash-to-panel/files/7565848/DashToPanel_logs.txt)

Please let me know if you require any additional information.

Thank You.
Joe

**Comment by Durlyn** [comment]
seems to be the same problem as i described #1517

**Comment by TheNamibian** [comment]
> seems to be the same problem as i described #1517

You at least have something still displaying, On my machine there is nothing displayed anymore.

**Comment by ronnyek** [comment]
This one is haunting me too right now which is too bad. With this exension installed, everything looks and works fantastic
until you sleep ,or reboot, then you have to go into extensions and toggle it off and on.

Part of it is probably working because the top bar doesnt display, its just that nothing displays in the panel for clock/tray stuff

**Comment by charlesg99** [comment]
Does this still happen? Probably the fullscreen bug that was fixed a while ago

**Comment by TheNamibian** [comment]
Seems to be resolved. Sorry that I did not report this earlier. Thank you,
