### ISSUE TITLE
System icons are huge until hovered over

### ISSUE THREAD

**Issue by Freeplayg** [home-sweet-gnome/dash-to-panel#1527]
**Describe the bug**
When first booting into the desktop, locking then unlocking, or changing the any of the padding sliders in the fine tune tab in settings, the system icons are too big until you hover over them.

Not exactly sure what causes the time to be bugged, but it does happen as shown in the video below.

**Linux distribution and version**
Pop! OS 21.04

**GNOME Shell version**
3.38.4

**Dash-to-Panel version**
42

**Where was Dash-to-Panel installed from?**
extensions.gnome.org

**Screenshots / Video captures**

https://user-images.githubusercontent.com/40742947/142745412-5c6767a6-09ce-4511-8c2d-80f488024cc8.mp4

Edit: I've recently changed my layout, same thing happens but don't fix when hovering over.

https://user-images.githubusercontent.com/40742947/145720196-34aebb60-eed4-460f-82e2-0ec2abb54f58.mp4

:

**Comment by charlesg99** [comment]
I remember this being a gnome-shell bug and this is probably fixed by now. Could you try to reproduce the issue with the master branch?

**Comment by Freeplayg** [comment]
I've since moved to Fedora 35 so idk if that changes anything, but yea it seems to be fixed for me now.
