### ISSUE TITLE
Inconsistent button highlights in Vertical mode

### ISSUE THREAD

**Issue by Adam-O-Raad** [home-sweet-gnome/dash-to-panel#1529]
Hi,
I like to run my panel in vertical mode on the left side of the screen, while doing so, I noticed that the highlights (on hover) for the app button as well as the clock/notification button are inconsistent with the rest of the highlights on the panel as shown in the example photos, which gives off an unfinished look to the panel and is quite irritating in my case lol.
I hope this can be fixed.

Thanks for the awesome work on the extension, it really makes using Gnome more intuitive

Linux distribution and version
Manjaro Linux; Build ID: rolling

GNOME Shell version
41

Dash-to-Panel version
45

Where was Dash-to-Panel installed from?
extensions.gnome.org

Normal looking highlight:
![control panel highlight](https://user-images.githubusercontent.com/17184459/143094267-ee4c15fe-94ea-4c97-8f55-df3d49dc6d42.png)
Broken highlights:
![Clock highlight](https://user-images.githubusercontent.com/17184459/143094317-89790260-cc53-4e00-b331-c85f3db0a43f.png)
![app grid highlight](https://user-images.githubusercontent.com/17184459/143094341-4ff0d36d-d651-406e-b787-a682a6b18ad6.png)

**Comment by 1v** [comment]
Same, looks weird.
