### ISSUE TITLE
Apps open in double when using touchscreen.

### ISSUE THREAD

**Issue by JSparrow93** [home-sweet-gnome/dash-to-panel#153]
Any time I try to open a pinned app with a tap of the finger on my touchscreen it opens it twice.

**Comment by micheleg** [comment]
I have reports of similar issues as well in dash-to-dock (https://github.com/micheleg/dash-to-dock/issues/128). Some info there (it doesn't seem to affect all configurations).

**Comment by TurkeyMan** [comment]
I find it's hard to open apps at all using the touch screen, it gets confused and thinks I'm trying to drag the app icon even when I'm touching it quite carefully.

**Comment by Depaulicious** [comment]
Also, when using touchscreen, touching the app button opens the dash and closes it again immediately.

**Comment by Depaulicious** [comment]
This doesn't seem to affect the default gnome indicators or stylus - if I tap with the stylus they open only once.

**Comment by jderose9** [comment]
I don't have a touch-capable device so someone else will have to help out on this.

**Comment by TurkeyMan** [comment]
If you do a pass making this more configurable, I'd also like smaller thumbs with much smaller margins, but I'd also like an option to remove the text; I feel the thumbnail is enough, I don't read the text, it just wastes space.

**Comment by Depaulicious** [comment]
@jderose9 how?

**Comment by phil-harmoniq** [comment]
I also have a tablet running Ubuntu and experiencing this issue. Is there anything I can do to help debug this?

**Comment by Fatburger3** [comment]
I have discovered this issue on my Ubuntu Gnome 16.04 Acer Switch Alpha 12 tablet.  I have also experienced this issue with Dash to Dock

**Comment by freelancer84** [comment]
Same on Dell Inspiron 13 5000 series

**Comment by Swedneck** [comment]
Same issue on thinkpad x220t.

**Comment by Depaulicious** [comment]
This seems to happen only on Xorg. It doesn't happen on Wayland.

**Comment by Swedneck** [comment]
Recently installed Fedora 27 Workstation on my x220t, i no longer have this specific issue.
However sometimes apps will not open/focus when i click on their icon using the touch screen.
