### ISSUE TITLE
Add toggle option to decouple Favourites buttons from Applications

### ISSUE THREAD

**Issue by richardnpaul** [home-sweet-gnome/dash-to-panel#1530]
**Describe the idea or feature you'd like**
I would like favourites icons to act like shortcuts, not to be expanded as applications bars when used with the Ungroup applications option.

**Is your feature request related to a problem? Please describe.**
I find it disconcerting when a favourite opens in place, expanding other favourite icons to the right and adding another instance, not only opens along side it further pushing the favourites to the right, it requires right clicking the application and selecting open new window for example; this is more error prone and cumbersome than just clicking an icon.
I should be able to click on the favourite icon multiple times and get multiple instances of the favourite app and they should not disturb the flow of the favourites.

**Additional context**
If you want an example of how I use this, I use this like the quick launch toolbar that is in Windows (you have to work harder to get this feature to work, but it works right up to Windows 10 - I've not had any hands on time with Windows 11 yet).

**Comment by iamCristYe** [comment]
@richardnpaul I believe that's already offered in settings of `Ungroup application`, named `Use the favorite icons as application launchers`

![Screenshot from 2021-12-09 16-20-50](https://user-images.githubusercontent.com/12642018/145359904-6a80fe2f-4ba2-46f0-8ced-4f498d02ca89.png)

**Comment by richardnpaul** [comment]
Thanks @iamCristYe you're absolutely right, I had missed the settings cog for the ungrouped application options which allows for adjusting this feature.  I'll close this off now.
