### ISSUE TITLE
Workspace preview in the overview loses rounded corners when dash to panel is enabled 

### ISSUE THREAD

**Issue by rdgh8** [home-sweet-gnome/dash-to-panel#1532]
**Describe the bug**

When Dash to Panel is enabled, the workspace previews in the overview lose their rounded corners on the side that dash to panel is positioned on. For example, in the image below, I have dash to panel set on the top of my screen. In the overview, the top 2 corners of the workspace preview are not rounded. 

**Linux distribution and version**

Pop!_OS 21.10 Beta (VM)

**GNOME Shell version**

40.5

**Dash-to-Panel version**

44

**Where was Dash-to-Panel installed from?**

The GNOME extensions website

**Screenshots / Video captures**

![image](https://user-images.githubusercontent.com/66289396/143671367-fad2bc34-2e91-479d-ab01-a31744820953.png)

**Comment by charlesg99** [comment]
This is fixed on the master branch, thanks!
