### ISSUE TITLE
Dash to pannel crash when I import settings

### ISSUE THREAD

**Issue by MrVrops** [home-sweet-gnome/dash-to-panel#1535]
**Describe the bug**
Dash-to-panel crash when I import settings in the About tab, can't see logs.

**Linux distribution and version**
Manjaro 21.2.0 

**GNOME Shell version**
GNOME Shell 41.1

**Dash-to-Panel version**
Version 9999

**Where was Dash-to-Panel installed from?**
The GNOME extension was tested by GNOME extensions website and by AUR, same issue.

Thanks to you.

**Comment by charlesg99** [comment]
Thanks, yes the command line tool previously used caused some problems, seems like in recent gnome-shell versions just loading with dconf is enough. Should be fixed on the master branch!
