### ISSUE TITLE
Clock/Date in Horizontal Mode

### ISSUE THREAD

**Issue by Infraviored** [home-sweet-gnome/dash-to-panel#1536]
![image](https://user-images.githubusercontent.com/94627194/144114560-ada0d7cb-0936-430e-9c8d-3f3aad7b883c.png)
This pretty much says it all. I have to change the text size to 10 in order for Clock and Date to be visible. 
Can't I specify the padding for the text here in order to upscale it?
Where can I Change the size of the currently open applications' icons?

**Comment by Flavelius** [comment]
Same problem here. In '**vertical**' mode the normal padding seems unnecessary for the clock as it only cuts off the displayed characters. I had to use another extension to adapt the displayed text to fit. It would be nice if there was an option to accomodate for this in dash to panel.

**Comment by charlesg99** [comment]
The extra padding on the clock when the panel is vertical has been removed on the master branch. Thanks!
