### ISSUE TITLE
array is undefined 

### ISSUE THREAD

**Issue by Boffice** [home-sweet-gnome/dash-to-panel#1537]
**Describe the bug**
Constantly getting ```array is undefined``` error due to which dash is malfunctioning. 

**Linux distribution and version**
Zorin 16 PRO

**GNOME Shell version**
GNOME Shell 3.38.4

**Dash-to-Panel version**
42

**Where was Dash-to-Panel installed from?**
https://extensions.gnome.org/extension/1160/dash-to-panel/

**Screenshots / Video captures**
Normal View:
https://i.imgur.com/CKd7LBl.png

Error View:
https://i.imgur.com/NQiiRBX.png

Error:
https://i.imgur.com/dnQrCxZ.png

**Comment by KyleBroflowski** [comment]
Still isnt fixed, i have the issue when unlocking the screen

**Comment by timhorn1** [comment]
Get the error `array is undefined` with Gnome Shell Version 41.3 and Dash to Panel Version 45, too!
Would be nice to fix this error so that i mustn't restart gdm after unlocking the screen.

**Comment by charlesg99** [comment]
Could you provide the error stack trace found in `journalctl /usr/bin/gnome-shell`. I've added a fix for this on the master branch, but I'm curious to know how this happen. Thanks!

**Comment by timhorn1** [comment]
Already fixed! Tank you!
