### ISSUE TITLE
Menu applications disappear the moment the extension is active

### ISSUE THREAD

**Issue by NintenDuck** [home-sweet-gnome/dash-to-panel#1540]
**Describe the bug**
No joke, is just what the title says

**Linux distribution and version**
Ubuntu 21.10.

**GNOME Shell version**
GNOME Shell 40.5.

**Dash-to-Panel version**
v9999.

**Where was Dash-to-Panel installed from?**
Distribution's package manager.

**Screenshots / Video captures**
1) Extension DISABLED
![Captura de pantalla de 2021-12-17 14-59-46](https://user-images.githubusercontent.com/44201851/146608508-9b7c2531-cee6-4082-b4ab-4dd0bac6cb02.png)

2)  Extension ENABLED
![Captura de pantalla de 2021-12-17 14-59-21](https://user-images.githubusercontent.com/44201851/146608494-2aea5010-5969-4fe6-8e5b-159559b819b7.png)

**Comment by charlesg99** [comment]
This doesn't happen on v46 / master branch, please try it out!
