### ISSUE TITLE
Ungroup applcations options adds force window Title to Application icons

### ISSUE THREAD

**Issue by atay** [home-sweet-gnome/dash-to-panel#1541]
**Describe the bug**

When selecting "ungroup applications" the title of the applications shows immediately. 
I would like to have it as an option, so I would prefer to still have only icons with no titles and clicking "Ungroup" will just "Ungroup", as it should be, with no adding titles. I see no option to disable "show titles for windows".

**Linux distribution and version**
Ubuntu 21.10

**GNOME Shell version**
GNOME Shell 40.5

**Dash-to-Panel version**
Dash to Panel version 44,

**Where was Dash-to-Panel installed from?**
GNOME Software store

**Comment by matfantinel** [comment]
While yes, this could perhaps be more explicit, you can easily hide the window titles by setting their max width to 0:
![image](https://user-images.githubusercontent.com/24247035/146970848-827f4bb5-312a-44a4-a63b-d1050f0d626c.png)

Which results in what is probably your desired behavior:
![image](https://user-images.githubusercontent.com/24247035/146970919-22b39038-c890-4487-8efa-c58c92e8fdbd.png)

**Comment by atay** [comment]
@matfantinel it works fine with your way, thanks a lot!
