### ISSUE TITLE
If placed at top, when existing the overview mode, the background image gets vertically pressed

### ISSUE THREAD

**Issue by HubKing** [home-sweet-gnome/dash-to-panel#1545]
**Describe the bug**
It is at the bottom by default, and when it is bottom this problem does not happen. It happens if it is placed at the top. With no windows open, press the Windows key to view the Gnome's overview mode, and then press the Windows key again to exit the overview mode.

You can see that the desktop wallpaper gets vertically pressed. It may be viewed as just a cosmetic problem, but it seems that with certain configuration, this seems to cause FireFox's tabs to be placed beneath the Dash-To-Panel after that action.

**Linux distribution and version**
Ubuntu 21.10

**GNOME Shell version**
GNOME Shell 40.5

**Dash-to-Panel version**
44

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**

https://user-images.githubusercontent.com/10900489/148058632-9c461abd-8977-44d6-be06-b2923f844487.mp4

**Comment by muslimitmilch** [comment]
Also, when placed at the bottom with intellihide, the overview closing animation is broken.
The wallpaper and also open apps get bigger and bigger, but only fill the space not used by the open panel. Then, the panel closes and the apps/wallpaper resize again, now filling the whole display.
This actually annoyed me so much that I don't use intellihide anymore, when I loved it on GNOME 3.38.

**Comment by charlesg99** [comment]
This is fixed in 46 / master branch. Thanks!
