### ISSUE TITLE
Ellipsis (dots) instead of time is displayed when notification icon is shown in vertical mode

### ISSUE THREAD

**Issue by CommanderAlchemy** [home-sweet-gnome/dash-to-panel#1546]
**Describe the bug**
From time to time the date will display weird in the panel when in vertical/portrait mode. 

**Linux distribution and version**
Arch

**GNOME Shell version**
41.2

**Dash-to-Panel version**
45

**Where was Dash-to-Panel installed from?**
GIT https://aur.archlinux.org/packages/gnome-shell-extension-dash-to-panel-git/

**Screenshots / Video captures**
![image](https://user-images.githubusercontent.com/3089330/148253479-3608276f-fef2-43d0-b1b2-475e28c41d3b.png)

Clicking it then updates and shows correctly
![image](https://user-images.githubusercontent.com/3089330/148253562-e81892e7-2c73-41e9-8664-dfddea972205.png)

Feels that there is some sizing issues when the date ticks. Because sometimes saving something in the extension would trigger this and then a time update (minute has passed would "fix it")

Currently it seems to trigger when time ticks.

**Comment by CommanderAlchemy** [comment]
Update seems to happen when "notification dot is shown" I think previously it was below/above?

**Comment by charlesg99** [comment]
v46 should solve this.
