### ISSUE TITLE
(Panel intellihide) Gnome shortcut "Show the notification list" not functioning unless panel is unhidden.

### ISSUE THREAD

**Issue by AesaraB** [home-sweet-gnome/dash-to-panel#1547]
**Describe the bug**

As the title states, when the panel is hidden, Gnome keyboard shortcuts don't appear to be able to unhide the panel. Easiest solution seems to be read the Gnome shortcut from dconf and use the extension to unhide the panel call the notification menu if the panel is hidden.

**Linux distribution and version**

Fedora 35

**GNOME Shell version**

41.2

**Dash-to-Panel version**

45

**Where was Dash-to-Panel installed from?**

Gnome Extensions

**Comment by charlesg99** [comment]
Thanks, let's keep #1560 opened and close this one.
