### ISSUE TITLE
Closing one window of an app closes all windows, when the setting "ungroup applications" is enabled

### ISSUE THREAD

**Issue by Gabro86** [home-sweet-gnome/dash-to-panel#1548]
When the "Ungroup applications" setting is enabled and a window of an app is closed by right clicking on the window in Dash-to-Panel and clicking on "Quit", then all windows of the app are closed.

### Steps to reproduce:
- Open the settings of Dash to Panel
- Go to the tab "Behavior"
- Enabled the option "Ungroup applications"
- Open two separate windows of any app of your choice, e.g. Firefox.
- Hover with the mouse over one of the windows of the app in Dash-to-Panel
- Click the right mouse button on the window of the app in Dash-to-Panel. Now the Dash-to-Panel menu appears.
- Click the option "Quit"

### What happens:
All windows of the app are closed

### What I expected to happen:
Only the window that I click "Quit" on should be closed.

### Program versions:
Fedora Linux 35 (Workstation Edition, 64-bit), Clean installation and no other GNOME extensions
GNOME Shell 41.2
Windowing System: Wayland
Dash-to-Panel 45 (Installed from GNOME extensions website)

**Comment by wennaspeedy** [comment]
How to solve this issue?

**Comment by tekstryder** [comment]
@wennaspeedy install from git or await next release

**Comment by wennaspeedy** [comment]
Thanks, git version works.

**Comment by tekstryder** [comment]
@charlesg99 looks like you're hard at work and cleaning things up in the issue tracker. Awesome!

Please close this issue and #1513, all the same issue as #1569

**Comment by charlesg99** [comment]
@tekstryder Thanks! Yeah I've lost track of all the duplicates :)
