### ISSUE TITLE
Running Indicator Style broken

### ISSUE THREAD

**Issue by Draco18s** [home-sweet-gnome/dash-to-panel#1550]
**Describe the bug**

The task bar icon style for "running indicator" can't be modified with Gnome 40.5

**Linux distribution and version**
Ubuntu 21.10

**GNOME Shell version**
Gnome 40.5

**Dash-to-Panel version**
9999

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
![image](https://user-images.githubusercontent.com/1750680/148791869-3e9a60fb-997f-40cc-aac1-917063f03e68.png)
Note how I changed the color to blue, but icons are still gray/white. Icon dominant color doesn't work either.

**Comment by philippun1** [comment]
The focused application (dash-to-panel settings) is highlighted in blue with a opacity. Change the opacity to get it fully blue. So I don't think this is a bug.

**Comment by Draco18s** [comment]
Doh, you are correct. I was looking at the wrong setting.
