### ISSUE TITLE
Windows still become transparent

### ISSUE THREAD

**Issue by lmcjoma** [home-sweet-gnome/dash-to-panel#1555]
This is the same issue as reported in #1284, which was closed without action.

Running fedora34-x86-64, gnome40.5.
Dash-to-panel Settings shows version: "Oops there was a problem".

This is very annoying.

**Comment by realitix** [comment]
Hello,
Same problem here !

**Comment by vendeta44** [comment]
Same issue.  Pop os 21.10, gnome 40.4.0, Dash-to-panel 44

**Comment by skontar** [comment]
Try a workaround by disabling "Show window preview on hover". I think that the problem was previously tied to some combinations of showing window preview and activated overview.

**Comment by winter5un** [comment]
@skontar  I would much rather use the functionality.
Same issue in default ubuntu 21.10 setup. mousing over previews causes some windows to maintain translucence.

**Comment by winter5un** [comment]
Settings for "show window preview on hover" setting window peeking mode opacity to 100 mitigates the problem.
I would hazard a guess that where ever the function to set the window peeking opacity is called, the restoration process is either missed or has an incomplete/bad logic statement....

**Comment by charlesg99** [comment]
[#1284](https://github.com/home-sweet-gnome/dash-to-panel/issues/1284#issuecomment-1086734395)
