### ISSUE TITLE
dash to panel is missing upon reboot.

### ISSUE THREAD

**Issue by Ninjastorm380** [home-sweet-gnome/dash-to-panel#1559]
**Describe the bug**
panel is gone upon reboot.

**Linux distribution and version**
EndeavourOS Atlantis Neo (Arch-Derived)

**GNOME Shell version**
GNOME Shell 41.3

**Dash-to-Panel version**
v45

**Where was Dash-to-Panel installed from?**
GNOME extensions website

**Additional Info**
I run a triple monitor setup with dash to panel set to show up on my primary display.

checking journalctl reveals that dash to panel is failing to figure out what a 'panel' is:
```
JS ERROR: TypeError: panel is undefined
vfunc_allocate@/home/prydaran/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/overview.js:690:21
vfunc_allocate/<@resource:///org/gnome/shell/ui/workspacesView.js:382:19
vfunc_allocate@resource:///org/gnome/shell/ui/workspacesView.js:374:20
vfunc_allocate@resource:///org/gnome/shell/ui/workspacesView.js:737:30
```

this error appears multiple times, one for each time I rebooted my machine while trying to figure this out.

it appears that disabling and re-enabling will fix this. perhaps we have to wait for 'panel' to exist?

EDIT:
after a few more days of testing, it appears to only happen if 'keep original gnome panel' is disabled + having extension 'just perfection' installed. I edited the .js files for 'just perfection' to see if I could get everything to run by removing the sections that edited the panel, but nothing changed after a reboot.

**Comment by charlesg99** [comment]
Thanks, this is now fixed on master
