### ISSUE TITLE
Hide Window Preview when right clicking an app in the panel

### ISSUE THREAD

**Issue by sonicnkt** [home-sweet-gnome/dash-to-panel#1563]
**Describe the bug**
I'm not sure if this is a bug or this just hasn't been addressed yet. 
I have enabled window previews when hovering over on of the app icons in the panel. If i then decide to right click the icon the option dialog for that app opens "over" the window previews. 
This also happens the other way around, so for example i immediately right click an icon and still the previews open behind it after the configured hover time.

If this is not a bug i would propose that the previews will hide automatically if you right click an item as it looks a bit more polished. 
 
**Linux distribution and version**
Manjaro Gnome (latest)

**GNOME Shell version**
41.2

**Dash-to-Panel version**
45

**Where was Dash-to-Panel installed from?**
Distribution, preinstalled

**Screenshots / Video captures**
![image](https://user-images.githubusercontent.com/5454622/150682581-1cb88740-f0a1-44be-8b68-0b2fd30477ee.png)

**Comment by charlesg99** [comment]
Thanks!
