### ISSUE TITLE
Indicator not showing up with some apps

### ISSUE THREAD

**Issue by chnavarro** [home-sweet-gnome/dash-to-panel#1566]
### A copy from Indicator not showing up with some apps #1152 

Describe the bug
I have a 2 monitor setup and I have the "Isolate monitors" option activated.
There are some apps that when opened, the running indicator is not showing up unless moving the app to a different monitor.
I did some JS debugging and it seems that the problem is that when opened, the "window.get_monitor()" returns the wrong monitor index for a few frames.
This doesn't occur with all the apps. Some that have this bug are:

    Nautilus
    Sublime Merge
    Tilix

Locally editing the function onWindowsChanged to this, fixes the issue. I don't have experience with developing Gnome extensions, there is probably a better way to fix it.

    onWindowsChanged: function() {
        this._updateWindows();
        this.updateIcon();

        Mainloop.timeout_add(100, Lang.bind(this, function () {
            this._updateWindows();
            this._displayProperIndicator();
            return GLib.SOURCE_REMOVE;
        }));
    }

Linux distribution and version
Fedora 34

GNOME Shell version
GNOME Shell 40.8

**Dash-to-Panel version
44

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Comment by chnavarro** [comment]
Is still present 

Linux distribution and version
Fedora 35

GNOME Shell version
GNOME Shell 41.5

Dash-to-Panel version
46

**Comment by davidmartos96** [comment]
@chnavarro It's true that the previous workaround editing "onWindowsChanged" doesn't work anymore.
The following replacement works:

```js
onWindowsChanged() {
    this._updateWindows();
    this.updateIcon();

    Mainloop.timeout_add(100, () => {
        this._updateWindows();
        this._displayProperIndicator();
        return GLib.SOURCE_REMOVE;
    });
}
```

**Comment by charlesg99** [comment]
Thanks for reporting this!
