### ISSUE TITLE
Icons only

### ISSUE THREAD

**Issue by caasi-dev** [home-sweet-gnome/dash-to-panel#1567]
**Describe the idea or feature you'd like**
When you ungroup applications, add setting to hide text labels and leave just the icons

**Comment by mweirauch** [comment]
Next to the "ungroup Applications" switch there is the settings cogwheel. In these settings, there is a setting for the maximum text width. Set that to `0`. So I'd say what you are requesting is already there.

**Comment by caasi-dev** [comment]
Honestly I didn't think about it :/

Thanks so much, closing issue

**Comment by burner1024** [comment]
Any way to keep titles as tooltips, though? Right now, there's no tooltips at all.
