### ISSUE TITLE
Could you provide a tray?

### ISSUE THREAD

**Issue by CicadaSeventeen** [home-sweet-gnome/dash-to-panel#1568]
**Describe the idea or feature you'd like**
The gnome does not contain a tray. There is an extension called `tray icons reloaded` to add a tray to topbar. However, `dash to panel` provide most function of a topbar so I would like to remove topbar. The problem is that `tray icons reloaded` only works on topbar and do not work on `dash to panel`

**Is your feature request related to a problem? Please describe.**
For example, steam use tray as default. Gnome without topbar cannot really close it without using `pkill` or `killall` or something else. That makes it very strange.
At the same time, Gnome use `ibus` as default input method, but `ibus` is not so stable and `fcitx` especially `fcitx5` is better. `fcitx` needs a tray too.

**Additional context**
I also advise author of `tray icons reloaded` similar things. You can visit the work on github as `MartinPL/Tray-Icons-Reloaded`

**Comment by arun54321** [comment]
Why not use AppIndicator extension? https://extensions.gnome.org/extension/615/appindicator-support/

**Comment by gmankab** [comment]
> Why not use AppIndicator extension? https://extensions.gnome.org/extension/615/appindicator-support/

it works, thank you
