### ISSUE TITLE
Wrong app minimize and maximize.

### ISSUE THREAD

**Issue by arun54321** [home-sweet-gnome/dash-to-panel#1570]
**Describe the bug**
Adjacent apps from task bar gets maximized when clicking the minimized app.

**Linux distribution and version**
Arch Linux

**GNOME Shell version**
GNOME Shell 41.3

**Dash-to-Panel version**
45

**Where was Dash-to-Panel installed from?**
 directly from GitHub

**Screenshots / Video captures**

https://user-images.githubusercontent.com/42943340/152747147-7af7a7e0-7f6f-4b5e-84d5-1d5f658977b2.mp4

**Comment by charlesg99** [comment]
Thanks, should be good on master now, this is caused by a Clutter gesture that triggers every 4 clicks. I added a temporary fix to the master branch, but a real fix in Mutter is on the way https://gitlab.gnome.org/GNOME/mutter/-/issues/1907
