### ISSUE TITLE
reserved space on top

### ISSUE THREAD

**Issue by Hr46ph** [home-sweet-gnome/dash-to-panel#1573]
**Describe the bug**
The space where the original gnome top bar lived is still reserved even though there is no bar there, original or from dash to panel. My dash-to-panel bar is vertical on the right side of the screen (top or bottom bar makes no sense to me on ultrawide).

This becomes obvious when a window that saves its location is closed after it is moved to the top of the screen. Upon reopening it is moved down the same amount of pixels that the original top bar is wide.

Some applications that save their location on the screen are Bitwarden and Signal. I tend to move them to the upper right corner but every launch they are moved down.

**Linux distribution and version**
Arch Linux fully updated with latest Gnome and dash-to-panel with ArcMenu.

**GNOME Shell version**
GNOME Shell 41.3

**Dash-to-Panel version**
45

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
To illustrate:
![image](https://user-images.githubusercontent.com/6275310/153705858-9084c7f9-37f0-4eab-9276-23fe1c499f05.png)

**Additional Info**
I don't know if its intentional or not, but arcmenu on a vertical dash-to-panel, when its on top also opens leaving that space empty. This is best seen when opening arcmenu when a window has been moved down after reopening. The menu will be perfectly alligned with the top of that window.

**Comment by charlesg99** [comment]
Hi, are you saying you can't move a window up there or only that windows that were last closed at the top of the screen reopen under this space?

**Comment by Hr46ph** [comment]
The last one. An app can be moved and will stay there until reopend or after logout/login. Not all apps do this, firefox and vivaldi always open on top. Therefore I cant say for sure the issue is in Gnome, the panel of even the applications itself.

I can't test anymore for you though. I grew so tired of some Gnome issues and the developer attitude towards removing user choice in favor of their own awkward ideas and vision that I moved back to xfce. Dash-to-panel and arcmenu are awesome and eleviate much of the annoyances. You guys do a great job.

**Comment by charlesg99** [comment]
Yes, I hear you :smiling_face_with_tear:. I'll close the issue and we'll keep #1600 for now. Thanks!
