### ISSUE TITLE
Applications overview is gray (running applications are not displayed) after pc restart

### ISSUE THREAD

**Issue by gintunas** [home-sweet-gnome/dash-to-panel#1575]
This is how it looks after pc restart:
![image](https://user-images.githubusercontent.com/55278643/154420565-1b421e60-6236-4375-90a8-5aae881fc5a0.png)

After `Dash to Panel` extension is restarted, applications' windows become visible.

Ubuntu version 21.10

**Comment by AlienTux** [comment]
I'm having sort of the same issue. Runing Pop OS 21.10 after PC restart or logging out and back in Overview is gray. Also, if I activate Cosmic Workspaces extension (which is basically vertical workspaces) then it's not grayed out, but a dot appears in the upper left corner and no workspace overview is shown.. Restarting Gnome shell solves the issues.
