### ISSUE TITLE
stop working after apt upgrade

### ISSUE THREAD

**Issue by ex3yop** [home-sweet-gnome/dash-to-panel#1583]
ubuntu 22.04 amd64
apt source version: gnome-shell-extension-dash-to-panel/jammy,jammy,now 45-1

other maybe relate info:
gnome-shell/jammy,now 41.3-1ubuntu1 amd64
gjs/jammy,now 1.71.1-1 amd64

-----------------------------------------------------------------------------

log:
JS ERROR: Extension dash-to-panel@jderose9.github.com: TypeError: Object 0x16fa7a2e4e00 is not a subclass of GObject_Object, it's a Object
_patchContainerClass/containerClass.prototype.add@resource:///org/gnome/shell/ui/environment.js:61:14
_createPanel@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:404:18
enable@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:84:34
_enable@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:106:18
enable@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:66:5
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:350:26
_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:596:18
collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:28
_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:571:19
_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:605:18
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:636:18
init@resource:///org/gnome/shell/ui/extensionSystem.js:56:14
_initializeUI@resource:///org/gnome/shell/ui/main.js:268:22
start@resource:///org/gnome/shell/ui/main.js:165:5
@resource:///org/gnome/shell/ui/init.js:6:17
Caused by: Error: This JS object wrapper isn't wrapping a GObject. If this is a custom subclass, are you sure you chained up to the parent _init properly?

**Comment by khaled4vokalz** [comment]
Same is happening for me after the latest Jammy upgrade.

**Comment by charlesg99** [comment]
Thanks, let's keep it in #1581. The master branch should now work with gnome 42.
