### ISSUE TITLE
Dash to Panel does not show the Window in focus caption 

### ISSUE THREAD

**Issue by Deottive** [home-sweet-gnome/dash-to-panel#1588]
The toogle for app menu button does nothing when you enable it nothing happens. 
![image](https://user-images.githubusercontent.com/71910027/158087860-db75b25e-07d5-4ab7-8447-6eb2d32888e4.png)
It should be having the name of the current window in focus like this , If I am right , 
![image](https://user-images.githubusercontent.com/71910027/158087891-c8ab9600-0df3-42f4-b71a-b71354f0aa53.png)

Distro = Latest Manjaro Gnome

Gnome shell = 41.04 

Dash to Panel version = 45

The extension was preinstalled with Manjaro Gnome out of the box.
I hope this is a bug or an I doing something wrong , Thank you

**Comment by charlesg99** [comment]
Thanks, works fine on the master branch now

![Peek 2022-04-03 09-17](https://user-images.githubusercontent.com/33044886/161430110-dc3fe0ba-05c6-40e4-b068-4f0546540705.gif)
