### ISSUE TITLE
Background wrongly sized on miniature workspaces

### ISSUE THREAD

**Issue by tibequadorian** [home-sweet-gnome/dash-to-panel#1590]
**Describe the bug**
In the screenshots below you see the issue. When in the application grid view, the background[1] on miniature workspaces is wrongly sized with dash to panel enabled[2]. In particular, around 20% of the background is cut-off and the picture is slightly stretched vertically. I expect that it's correctly sized like in the screenshot with dash-to-panel disabled[3].

**Linux distribution and version**
Fedora 35

**GNOME Shell version**
GNOME Shell 41.4

**Dash-to-Panel version**
45

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
[1] Here is my background:
![g3457](https://user-images.githubusercontent.com/9560587/159480686-1c51d4dc-d40a-45a0-a003-7645de2d47fb.png)

[2] Here is a picture of application grid view with dash to panel enabled:
![with](https://user-images.githubusercontent.com/9560587/159480560-69b019b0-c0a7-4a27-8c33-3a5fd934e006.png)

[3] Here is a picture of application grid view with dash to panel disabled:
![without](https://user-images.githubusercontent.com/9560587/159480612-747a7084-1486-49c3-a364-cd98976f1940.png)

**Comment by tibequadorian** [comment]
I found out that the following minimal patch solves this particular issue for me:
```patch
--- a/overview.js
+++ b/overview.js
@@ -699,6 +699,7 @@ var dtpOverview = Utils.defineClass({
                     xOff += panel.panelBox.width;
                     break;
             }
+            yOff *= contentHeight / this._workarea.height;
             contentBox.set_origin(startX, startY);
             contentBox.set_size(xOff + contentWidth, yOff + contentHeight);
             this._backgroundGroup.allocate(contentBox);
```
The idea is to scale the `yOff` properly with the size of `contentBox`.
I won't PR this though because this is just a quick fix and it can be probably done in a better way.

**Comment by charlesg99** [comment]
Thanks! Seems like gnome-shell now accounts for external struts, so I removed the custom dash to panel code for that and it looks like it works! See https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1892
