### ISSUE TITLE
Shell notification location mis-match on multi monitor setup  

### ISSUE THREAD

**Issue by shriaviator** [home-sweet-gnome/dash-to-panel#1591]
**Things to do first**
- Unable to remove all extensions as POP OS cosmic is a extension.
- Extensions except cosmic disabled 

**Describe the bug**
- On a fresh installation of dash-to -panel - 
- shell top  bar was modified to secondary monitor **only** and location to top . 
- The pop up notifications still appears in the primary monitor where the top bar was originally  and the top bar is on  the secondary monitor  
---
**Linux distribution and version**
Pop OS 21.10
----

**GNOME Shell version**
GNOME Shell 40.5
-----
**Dash-to-Panel version**
version 44 

**Where was Dash-to-Panel installed from?**
The GNOME extensions website,
----
**Screenshots / Video captures**
.

**Additional Info**

**Comment by charlesg99** [comment]
Dtp doesn't change gnome-shell primary monitor, it only changes where the main panel is (panel merged with the default gnome-shell top bar).
