### ISSUE TITLE
Unable to activate the extension

### ISSUE THREAD

**Issue by kylefelipe** [home-sweet-gnome/dash-to-panel#1593]
Issuing the folow error
GObject_Object.prototype.[__GObject__hook_up_vfunc] called on incompatible Object

**Linux distribution and version**
Debian SID,

**GNOME Shell version**
41.4

**Dash-to-Panel version**
45

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Comment by Jeansen** [comment]
Same here. But it looks like this is a more global problem since I can activate other extensions but then on next login my Gnome-Session on Wayland hangs and on X it reloads constantly. Something central mus have been changed in Gnome Shell 41.4 ;-(

**Comment by mickaelj** [comment]
Same problem, same version of debian/Gnome Shell. I thnk like Jeansen.

**Comment by Raddinox** [comment]
I had the same problem yesterday on Debian SID. 
But few hours later I received an update and now Gnome shell is at version 42 in Debian SID. So the extension is marked as not supported.

**Comment by mickaelj** [comment]
Wonderfull, many thanks !

**Comment by kylefelipe** [comment]
> I had the same problem yesterday on Debian SID. But few hours later I received an update and now Gnome shell is at version 42 in Debian SID. So the extension is marked as not supported.
> 
> EDIT: Patches from here [#1581 (comment)](https://github.com/home-sweet-gnome/dash-to-panel/issues/1581#issuecomment-1069282984) Works on Debian SID with Gnome-shell 42

Here still incompatible to me.

**Comment by mickaelj** [comment]
It's work for me !

**Comment by Jeansen** [comment]
> I had the same problem yesterday on Debian SID. But few hours later I received an update and now Gnome shell is at version 42 in Debian SID. So the extension is marked as not supported.
> 
> EDIT: Patches from here [#1581 (comment)](https://github.com/home-sweet-gnome/dash-to-panel/issues/1581#issuecomment-1069282984) Works on Debian SID with Gnome-shell 42

Oh, great. I am also on Debian SID but have not updated to 42. Still waiting for the meta package to receive its update. I'll try the patch then. :+1:

**Comment by Raddinox** [comment]
The patches have been merged to the git repo. You only need to clone the repo and run 'make install' ('sudo apt install gettext make' for depends) works on Debian SID.

> It's work for me ! EDIT : Only at bottom :(

I had to logout/in before the settings works ok

**Comment by charlesg99** [comment]
Should now work correctly using the master branch, thanks!

**Comment by mickaelj** [comment]
Same here, it's work fine with the last git update on Gnome 42 and SID.
