### ISSUE TITLE
Nemo always assumes File Type is based on the very first 3 letters of a file extension - What about extensions Larger than 3?

### ISSUE THREAD

**Issue by amiga-500** [home-sweet-gnome/dash-to-panel#1595]
Example file names:

**file.rarabc**  
**another_file.txt2**

Nemo will incorrectly assume the file type for the first one is a "rar" type while the secnond is a "txt" file/
What if a file extension is indeed "rarabc" or "txt2" then nemo will not be able to recognize it.

So it's clear Nemo is looking at only up to the first 3 letters after a period to assume what the extension is.  

Can you fix this so it looks at the full extension, not just the 1st 3 characters, and if it is not registered it just treats it as the defaault: **Binary** ?

**Comment by charlesg99** [comment]
Not sure how this is dash to panel related
