### ISSUE TITLE
Doesnt work on Debian testing

### ISSUE THREAD

**Issue by Ud4ba** [home-sweet-gnome/dash-to-panel#1597]
This extension stopped to work yesterday with an update on Gnome package. Now im getting ERROR on Extensions. Any idea what i should do?

**Comment by highvoltage** [comment]
Yep, it effectively doesn't work on Gnome 42, which is now in Debian.

**Comment by Ud4ba** [comment]
Will we get any fix or workaround ? 
Thanks for your answer.

**Comment by philippun1** [comment]
There is a PR #1584 which is currently pending. You can only install the branch from it manually for now.

**Comment by Ud4ba** [comment]
Thanks. How i can do this?
Also this version crashes all other extension and Gnome and im not able to disable only Dash to panel.
Will this get updated soon?

**Comment by philippun1** [comment]
The PR is now merged into the main branch. For now you can pull it and run "make install". But I think there will be a new version soon.

**Comment by Ud4ba** [comment]
Thanks again for your wonderful job :)
Hope the best!

**Comment by charlesg99** [comment]
Thanks
