### ISSUE TITLE
Click empty space to close overview also closes the overview if clicked on the left/right scroll areas

### ISSUE THREAD

**Issue by philippun1** [home-sweet-gnome/dash-to-panel#1602]
**Describe the bug**
If you enable the "Click empty space to close overview" option, the overview will also be closed if the scroll areas left/right are clicked.

**Linux distribution and version**
Ubuntu 22.04

**GNOME Shell version**
Gnome 42.0

**Dash-to-Panel version**
latest master branch

**Comment by charlesg99** [comment]
Hey Philipp, just added a quick fix for the empty space, so far it seems to work good, but let me know if you find a click that misbehaves.

**Comment by philippun1** [comment]
Yes, it now works on Manjaro (gnome 41) and Ubuntu (gnome 42).
