### ISSUE TITLE
Click action: Toggle single/ Preview multiple isn't working properly

### ISSUE THREAD

**Issue by MrSnugglesGH** [home-sweet-gnome/dash-to-panel#1611]
'Toggle single' part is working as expected.

However, 'Preview multiple' isn't. Open multiple instances of file manager. Clicking on the file manager icon in the panel does nothing, in fact if you have previews already opened due to hovering over the icon then those previews will be closed if you click on the file manager icon.

**Comment by charlesg99** [comment]
Thanks again, yep that wasn't working. We relied on a Clutter api function that was recently removed in https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2024

**Comment by Janhouse** [comment]
Any plans to actually release this as a version any time soon? It's very hard to use it without this feature.

**Comment by charlesg99** [comment]
@Janhouse Yes, I'll be releasing at least another version before Ubuntu 22.04 hits next week.
