### ISSUE TITLE
Can't change the "shortcut to show the overlay for 2 seconds" option

### ISSUE THREAD

**Issue by jmaargh** [home-sweet-gnome/dash-to-panel#1612]
**Describe the bug**
Under the preferences > Action > Use hotkeys to activate apps (cog), there is an option labelled "shortcut to show the overlay for 2 seconds" which defaults to `<Super>q`. I cannot focus this text box and therefore cannot change the option. I can change all other options in that dialog (indeed, every other option I've tried in the whole extension), but I simply can't focus that text box.

Nothing useful comes up in the log when I try to focus it, it simply won't put a cursor in that text box.

**Linux distribution and version**
Fedora 35

**GNOME Shell version**
41.4

**Dash-to-Panel version**
46

**Where was Dash-to-Panel installed from?**
The GNOME extensions website (via Extension Manager app)

**Additional Info**
This is not only a very frustrating problem, but also a frustrating default configuration (Super + q is a relatively common "close current window" shortcut)

**Comment by charlesg99** [comment]
Thanks!
