### ISSUE TITLE
Application icons are coming out half-height on HDPI/HiDPI display on gnome-42/dash-to-panel-46

### ISSUE THREAD

**Issue by ikelos** [home-sweet-gnome/dash-to-panel#1613]
**Things to do first**
- All other extensions were switched off and wayland session was restarted.
- No relevant logs found in journalftl output.
- Closest matching issue appears to be #364 or #10, both of which are closed.

**Describe the bug**
Previously, before upgrade to gnome-42, dash-to-panel worked just fine on my laptop (with 200% scaling) and there were no issues.  After updating to gnome-42, and updating the extension to the version that support gnome-42 today, I found that the application icons were too small.  I did the same updates on my desktop, which has a reasonable resolution (ie, no scaling) and it looks just fine.

**Linux distribution and version**
Gentoo, Gnome 42, happy to provide other versions on request.

**GNOME Shell version**
GNOME Shell 42.0

**Dash-to-Panel version**
Dash-to-panel version: 46

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
![Screenshot from 2022-04-08 00-31-04](https://user-images.githubusercontent.com/1477845/162336326-9f76ad4f-b21d-415c-9ec1-466c25870d1b.png)

**Additional Info**
I tried disabling and re-enabling the extension, I tried altering the settings, but none seemed to increase the size of the application icons within the bar.  The applications menu button is the right size, as are all the status icons on the right, it's just the application icons causing the problems.

**Comment by charlesg99** [comment]
Hi, I just tested on xorg and wayland and both seem fine on gnome-shell 42. I'm not sure it's a scaling issue, are you positive that nothing shows up in your log? (the error causing this might not be from dash to panel)

![image](https://user-images.githubusercontent.com/33044886/162428551-9f1a7e4e-f028-4167-aeaa-2de12803d241.png)

**Comment by charlesg99** [comment]
Actually scratch that, I found an older issue that refers to it #1412 and it does happen when when "Animate hovering app icons" is enabled.

**Comment by charlesg99** [comment]
Thanks, should now work properly on the master branch.
