### ISSUE TITLE
Latest release conflicts with Ubuntu Dock

### ISSUE THREAD

**Issue by Neubulae** [home-sweet-gnome/dash-to-panel#1614]
**Describe the bug**
Dash to Panel would crash after locking and unlocking(using Super+L or other methods) if [Ubuntu Dock Latest](https://github.com/micheleg/dash-to-dock/releases/tag/ubuntu-dock-72_ubuntu2) is enabled.

**Linux distribution and version**
Arch Linux

**GNOME Shell version**
``GNOME 42.0``

**Dash-to-Panel version**
``9999``

**Where was Dash-to-Panel installed from?**
``aur/gnome-shell-extension-dash-to-panel``

**Additional Info**
The Error log spits out this:
```
JS ERROR: Extension dash-to-panel@jderose9.github.com: Error: Expected an object of type GFile for argument 'file' but got type undefined
                _enable@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:77:43
                enable@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:65:5
```
which looks like code handling Ubuntu Dock.

**Comment by charlesg99** [comment]
How did you install ubuntu-dock? I'm testing this on Jammy with the latest ubuntu-dock version and it works fine. The error you provided indicates that ubuntu-dock doesn't have a stylesheet when dtp tries to unload it, but it should have one, so I'm not sure how you get this result. Thanks!

**Comment by Neubulae** [comment]
> How did you install ubuntu-dock? I'm testing this on Jammy with the latest ubuntu-dock version and it works fine. The error you provided indicates that ubuntu-dock doesn't have a stylesheet when dtp tries to unload it, but it should have one, so I'm not sure how you get this result. Thanks!

I used the one here https://aur.archlinux.org/packages/gnome-shell-extension-dash-to-dock

**Comment by Neubulae** [comment]
after some enabling and disabling, Ubuntu Dock now refuses to enable with Dash to Panel. ~~I am scared help~~

**Comment by charlesg99** [comment]
Maybe the pkgbuild is not setting the stylesheet or something? What is your output when you run `sassc --version`?

I just installed the latest commit (same as in the pkgbuild) and it works fine here. Here are the steps I did:
```
git clone https://github.com/micheleg/dash-to-dock.git
cd dash-to-dock
git checkout ubuntu-dock
make install
```

Restart gnome-shell, then enable ubuntu-dock

![image](https://user-images.githubusercontent.com/33044886/162488455-bc8efdc4-f8d3-4eb1-ad63-45adad347432.png)

**Comment by Neubulae** [comment]
❯ sassc --version
sassc: na
libsass: 3.6.5
sass2scss: 1.1.1
sass: 3.5

**Comment by Neubulae** [comment]
I reinstalled thru manual building and Ubuntu Dock still kills itself after enabling Dash to Panel, even when it's enabled the moment before.

**Comment by charlesg99** [comment]
Ha sorry I think I misunderstood from the start... Dash to panel does disable ubuntu-dock when both extensions are enabled, this is expected for Ubuntu system users. 

If I understand correctly the problem is that you want to use dash-to-dock at the same time as dash to panel? If so you could just change the uuid from "ubuntu-dock@ubuntu.com" to something else in the file `~/.local/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/metadata.json`, then restart gnome-shell. Seems like it should be done in the pkgbuild as it is a "dash to dock" package, at least until the dash to dock branch is ported to GS 42.

**Comment by Neubulae** [comment]
Ah OK, then I was curious about why did it work then....

**Comment by Neubulae** [comment]
It does work like it should now, thanks!
