### ISSUE TITLE
Window title shown below panel in overview

### ISSUE THREAD

**Issue by philippun1** [home-sweet-gnome/dash-to-panel#1616]
**Describe the bug**
If you open 3 or more windows and go to overview, the title of the windows in the lower row are below the panel.
The screenshot shows Nautilus (dark theme) in overview, the title is cut off by the panel (the black area at the bottom of the screenshot).

**Linux distribution and version**
Ubuntu 22.04

**GNOME Shell version**
42.0

**Dash-to-Panel version**
latest master

**Screenshots / Video captures**
![Screenshot from 2022-04-08 22-25-46](https://user-images.githubusercontent.com/57151725/162526762-34c5661b-908b-4eb5-bb3f-880414018d39.png)

**Comment by charlesg99** [comment]
Hey Philipp! Thanks, yeah I felt like I half-assed that part and now it is biting me back :). I pushed some changes that should fix this and make the overview sizing more reliable.

**Comment by philippun1** [comment]
@charlesg99 It works now for multiple windows. But if I have one fullscreen window, the title is still below the panel.

**Comment by charlesg99** [comment]
Hmm not sure what's up, on my end a fullscreen window with the largest panel size has the same spacing. Can you think of some settings that could cause this on your system? Maybe the Ubuntu theme?

![Peek 2022-04-09 13-07](https://user-images.githubusercontent.com/33044886/162584348-118987eb-18a5-4ac9-949c-f81fd23aafb0.gif)

**Comment by philippun1** [comment]
It also happens on Manjaro (Unstable with gnome 42):

https://user-images.githubusercontent.com/57151725/162587504-eb447e71-a3dc-426c-a2fd-0491b308e7cd.mp4

**Comment by charlesg99** [comment]
Do you apply a scale factor by chance? I tried to find the issue and could reproduce when scaling to 200%. Pushed the fix for that, maybe it helped.
