### ISSUE TITLE
Dynamic opacity for should re-query on workspace change

### ISSUE THREAD

**Issue by szbergeron** [home-sweet-gnome/dash-to-panel#1618]
**Describe the bug**
I want the panel to be opaque if I have a currently visible window that is near the panel.

When I change workspaces, I may go from a workspace with a maximized window to one
with no windows at all.

Currently, with the "all windows" or "maximized windows" options, the bar stays opaque.

Instead, when I go to a workspace with no windows (or no windows near the panel), the panel should switch to being transparent.

**Linux distribution and version**
Arch

**GNOME Shell version**
GNOME Shell 42.0

**Dash-to-Panel version**
46

**Where was Dash-to-Panel installed from?**
Gnome extension manager

**Additional Info**

**Comment by charlesg99** [comment]
Thanks! Forgot to update on workspace change, should now work on master

**Comment by szbergeron** [comment]
Wow, you guys are *fast*, thanks!

**Comment by charlesg99** [comment]
Too fast... something is still not working right, I'll check again tomorrow!

**Comment by charlesg99** [comment]
Now we're good!
