### ISSUE TITLE
Window preview doesn't hide when moving mouse outside of panel area

### ISSUE THREAD

**Issue by szbergeron** [home-sweet-gnome/dash-to-panel#1619]
**Describe the bug**
After activating window preview, if I move my mouse outside of the panel or preview (move directly over a window), the preview stays open and does not go away until I move the mouse down and over the panel again.

**Linux distribution and version**
Arch

**GNOME Shell version**
GNOME Shell 42.0

**Dash-to-Panel version**
46

**Where was Dash-to-Panel installed from?**
Gnome extension manager

**Comment by charlesg99** [comment]
That's a Mutter bug. On my Arch system it was fixed by updating to 42.0-2 last thursday. Here is some more info about it https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2321
