### ISSUE TITLE
When used with Unite, FireFox's tab bar goes beneath it when lock/unlock the screen.

### ISSUE THREAD

**Issue by HubKing** [home-sweet-gnome/dash-to-panel#1621]
**Describe the bug**
This does not happen if only one of Dash To Panel and Unite is enabled. I am not sure if this is a bug of Unite because it does not happen when Dash to Panel is not enabled. It could be a bug of any one of all three (FireFox, Unite, Dash to Panel), but since I am not sure which is responsible, I am reporting here.

To reproduce this problem, start FireFox, maximise its window (not full screen), lock the screen (press Win + L), and unlock the screen. FireFox's tab bar is beneath Dash To Panel as show in the screenshot below, sometimes. That is, it sometimes happens, and sometimes does not, and  I am not sure about the exact criteria. But if you repeat the process 2~3 times, you will see it happening.

I have tested with the default FireFox (no settings have been changed). It happens on Manjaro/Ubuntu, etc. It happens only when using the default FireFox UI layout (tab bar above the address bar); it does not happen when FireFox is in the GTK layout (the FireFox that ships with Manjaro by default uses this Gnome layout in which the tab bar is beneath the tool bar).

**Linux distribution and version**
Manjaro Gnome latest. But also happens on Ubuntu 21.10 as far as I remember.

**GNOME Shell version**
GNOME Shell 41.4

**Dash-to-Panel version**
46

**Where was Dash-to-Panel installed from?**
The GNOME extensions website.

**Screenshots / Video captures**
I tried to record the screen with Kooha, but somehow it was stuck at "flushing" and the video file was not saved, so I am adding two screenshots below. The first one is before locking the screen, the second one is after unlocking the screen.

![before](https://user-images.githubusercontent.com/10900489/162726081-ad637f74-3f27-4c16-be96-07bce3a329de.png)

![after](https://user-images.githubusercontent.com/10900489/162726111-c4f547ff-0928-4563-9281-1f67133e29db.png)

**Additional Info**
Unite version 62: https://github.com/hardpixel/unite-shell

**Comment by charlesg99** [comment]
Unite and dash to panel both override the gnome-shell top panel allocation, so I'm shocked that combining both extensions work at all (unless you select in dtp settings to keep the original g-s top panel). I guess if dash to panel is enabled after unite, its allocation is the one that takes effect, but surely they're incompatible in some way. 

Could you run `journalctl /usr/bin/gnome-shell -f -o cat &` and check for errors when you unlock your system? It's mostly fishing because, unless both extensions account for one another, I don't see how they can coexist without problems.

**Comment by HubKing** [comment]
> Could you run `journalctl /usr/bin/gnome-shell -f -o cat &`

The output is below, but for some reason it does not happen when I tried this multiple times. If it does not happen for a long time, I will close this.

> Window manager warning: Overwriting existing binding of keysym 32 with keysym 32 (keycode b).
> Window manager warning: Overwriting existing binding of keysym 33 with keysym 33 (keycode c).
> Window manager warning: Overwriting existing binding of keysym 34 with keysym 34 (keycode d).
> Window manager warning: Overwriting existing binding of keysym 35 with keysym 35 (keycode e).
> Window manager warning: Overwriting existing binding of keysym 36 with keysym 36 (keycode f).
> Window manager warning: Overwriting existing binding of keysym 37 with keysym 37 (keycode 10).
> Window manager warning: Overwriting existing binding of keysym 38 with keysym 38 (keycode 11).
> Window manager warning: Overwriting existing binding of keysym 39 with keysym 39 (keycode 12).
> Window manager warning: Overwriting existing binding of keysym 61 with keysym 61 (keycode 26).
> Window manager warning: Overwriting existing binding of keysym 31 with keysym 31 (keycode a).
> Timelines with detached actors are not supported
> Timelines with detached actors are not supported
> _shell_embedded_window_unmap: assertion 'SHELL_IS_EMBEDDED_WINDOW (window)' failed
> Desktop Icons: Neo: Gjs-Message: 03:11:19.728: JS LOG: Error connecting to Nautilus
> GNOME nautilus 41.2
> 
> Window manager warning: Overwriting existing binding of keysym 34 with keysym 34 (keycode d).
> Window manager warning: Overwriting existing binding of keysym 35 with keysym 35 (keycode e).
> Window manager warning: Overwriting existing binding of keysym 32 with keysym 32 (keycode b).
> Window manager warning: Overwriting existing binding of keysym 37 with keysym 37 (keycode 10).
> Window manager warning: Overwriting existing binding of keysym 38 with keysym 38 (keycode 11).
> Window manager warning: Overwriting existing binding of keysym 61 with keysym 61 (keycode 26).
> Window manager warning: Overwriting existing binding of keysym 33 with keysym 33 (keycode c).
> Window manager warning: Overwriting existing binding of keysym 39 with keysym 39 (keycode 12).
> Window manager warning: Overwriting existing binding of keysym 31 with keysym 31 (keycode a).
> Window manager warning: Overwriting existing binding of keysym 36 with keysym 36 (keycode f).
> Timelines with detached actors are not supported
> Timelines with detached actors are not supported
> Timelines with detached actors are not supported
> Window manager warning: Overwriting existing binding of keysym 32 with keysym 32 (keycode b).
> Window manager warning: Overwriting existing binding of keysym 33 with keysym 33 (keycode c).
> Window manager warning: Overwriting existing binding of keysym 34 with keysym 34 (keycode d).
> Window manager warning: Overwriting existing binding of keysym 35 with keysym 35 (keycode e).
> Window manager warning: Overwriting existing binding of keysym 36 with keysym 36 (keycode f).
> Window manager warning: Overwriting existing binding of keysym 37 with keysym 37 (keycode 10).
> Window manager warning: Overwriting existing binding of keysym 39 with keysym 39 (keycode 12).
> Window manager warning: Overwriting existing binding of keysym 61 with keysym 61 (keycode 26).
> Window manager warning: Overwriting existing binding of keysym 38 with keysym 38 (keycode 11).
> Window manager warning: Overwriting existing binding of keysym 31 with keysym 31 (keycode a).

**Comment by HubKing** [comment]
It probably was fixed with version 62 (before version 62, it moved the screen down when unlocking the session (Issue #1545), and I had suspected that it was the cause of this FireFox problem)because I have not experienced this after posting this. This was posted right after upgrading it to version 62, but probably the problem persisted for a while because I had not restarted the PC or something.
