### ISSUE TITLE
Click favorite icon can't respect Exec field in Desktop Entry

### ISSUE THREAD

**Issue by kevinhwang91** [home-sweet-gnome/dash-to-panel#1622]
**Describe the bug**
I have enabled dark mode in my chrome since I read https://dev.to/ankitbrijwasi/enable-dark-mode-in-chrome-on-ubuntu-20na. This idea works fine when I lanuch chrome searched from gnome or run `gtk4-launch google-chrome.desktop` in the terminal.

However, it doesn't work if I click the icon from favorites. I have tried to add a log from the proxy shell, but it seems that can't be fired. 
 
**Linux distribution and version**
ArchLinux

**GNOME Shell version**
GNOME Shell 42.0

**Dash-to-Panel version**
version: 46

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Comment by charlesg99** [comment]
I don't think it is a dash to panel bug, we don't interact with .desktop files, we simply use the favorites provided by gnome-shell. You'd probably have the same problem if you launch chrome from the regular gnome-shell dash in the overview.

Is it possible that you have more than one .desktop file for chrome? Have a look in `~/.local/share/applications/` and `/usr/share/applications/`. You could simply unpin your favorite that doesn't work correctly, and re-pin the one from the search results. Also don't forget to restart gnome-shell as well when something suspect is happening on your system :)

**Comment by kevinhwang91** [comment]
> Is it possible that you have more than one .desktop file for chrome?

Only one. Have you tried the method from the link? It looks like a bug for gnome.

**Comment by charlesg99** [comment]
> It looks like a bug for gnome.

Yes, as I said you'd have the same issue when launching the application from the vanilla dash in the overview.
