### ISSUE TITLE
Can't reorder/move favorites (Gnome 42)

### ISSUE THREAD

**Issue by alescdb** [home-sweet-gnome/dash-to-panel#1623]
Since Gnome 42 I'm unable to move favorites in the task bar.

**Linux distribution and version**
ArchLinux

**GNOME Shell version**
GNOME Shell 42.0

**Dash-to-Panel version**
v46

**Where was Dash-to-Panel installed from?**
GNOME extensions website

**Comment by charlesg99** [comment]
Works fine here, g-s 42 and the master branch.

![Peek 2022-04-12 09-08](https://user-images.githubusercontent.com/33044886/162969488-f6ce4a6e-7382-4ba9-8121-7c458ae76186.gif)

Anything else special with your system? Errors in your log?

**Comment by alescdb** [comment]
Nothing in the logs.
I've installed latest master, and I have the same behavior. Can't drag & drop, icons are "locked in place".
I've also tried X11 & Wayland.

**Comment by charlesg99** [comment]
Is your taskbar locked by chance?

![image](https://user-images.githubusercontent.com/33044886/162979925-5c9d3d7f-d645-4f44-a124-297cf1a4f5e3.png)

**Comment by alescdb** [comment]
Ooops... sorry, I didn't knew about this option !!!
Thanks

**Comment by choc1024** [comment]
I have the same problem but taskbar isn't locked

**Comment by choc1024** [comment]
https://github.com/user-attachments/assets/c912735f-a845-4bcc-9c95-011ffcb48d29

**Comment by jnsorph** [comment]
If you use the extension "Favourites in AppGrid", you have to disable it and re-login. Then you can sort your apps in dock normally, seems to be a problem with this extension

**Comment by ch2a** [comment]
To unlock the taskbar on CachyOS:
`gsettings set org.gnome.shell.extensions.dash-to-panel taskbar-locked false`
