### ISSUE TITLE
[Feature request] UBS key and the trash can icon in the bare

### ISSUE THREAD

**Issue by hari-jeya** [home-sweet-gnome/dash-to-panel#1626]
Hello, first of all thank you very much for this very cool extension.
I've been using it since I learned about it and it gives my ubuntu a really cool look.
but I would like to have a feature that I think is pretty cool.

is it possible that when you plug in a storage device it is automatically displayed in the bar (like in the basic ubuntu dock). and when you click on the icon of the usb key or ssd or other storage device it opens the file explorer.
and is it possible to add an icon for the trash? and the possibility to empty the trash with a right click on the icon

I know that these two features existed in the Dash to Dock extension but I can't do it with dash to panel. I can't find anything on the internet... but if it's already possible to do it can someone tell me how to do it? 

I use version 42 of dash to panel. on ubuntu 20.04.4 with gnome 3.36.8

**Comment by charlesg99** [comment]
Thanks, duplicate of #1039
