### ISSUE TITLE
window preview not closing when hovering off of it from the top

### ISSUE THREAD

**Issue by fadihajjej** [home-sweet-gnome/dash-to-panel#1627]
Window preview should close when  hovering off of it as you can see in the clip it closes when you hover under it but it doesn't close when hover on top of it even if you click outside this applies to the tooltip too.

Fedora 36 Gnome 42 Dash to panel 46

https://user-images.githubusercontent.com/53702108/163653267-484b5985-2888-4a1e-8270-42bf0e3cebd1.mp4

**Comment by charlesg99** [comment]
Please see #1620
