### ISSUE TITLE
"Click empty space to close Overview" makes right-clicking on the toolbar area open Overview.

### ISSUE THREAD

**Issue by HubKing** [home-sweet-gnome/dash-to-panel#1629]
**Describe the bug**
It began to happen with the recent system update of Manjaro Linux, which made the Gnome version 41.5 (previously, it was 41.3, I think). Enabling "Click empty space to close Overview"  (may take a system restart to make this bug appear) makes right-clicking on the tool bar area of a GTK app show the Overview. This problem does not happen in version 45.

**Linux distribution and version**
Manjaro

**GNOME Shell version**
GNOME Shell 41.5

**Dash-to-Panel version**
46.

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**

https://user-images.githubusercontent.com/10900489/163678028-c79b32ec-60f7-4d26-b5ee-2d3b566e1a2a.mp4

**Additional Info**
I enabled/disabled various settings of Dash to Panel to pin-point the cause, which means that I had changed other settings before enabling "Click empty space to close Overview". I think I set every other setting than "Click empty space to close Overview" back to default and reproduced the problem, but to make it sure I looked for a way to completely reset the settings, but I could not find how. If you cannot reproduce the problem, please let me know a way to completely reset its settings, and I will test it again.

**Comment by charlesg99** [comment]
I can't reproduce it. See the [faq](https://github.com/home-sweet-gnome/dash-to-panel#user-content-faq) for how to reset your settings. Also make sure to restart gnome-shell **after** disabling your other extensions, then check for the issue. Thanks!

**Comment by HubKing** [comment]
Below is a screen recording that shows that it happens after resetting the settings in a virtual machine. It did not happen only in a virtual machine. It happened on my real hardware first, and I only used a virtual machine to reproduce the same problem.

https://filebin.net/dn5q2lrj1uhlfbs5 (The file size is 12MB, and GitHub rejects files larger than 10MB, so I had to upload it a third-party file sharing site.)

If you still cannot reproduce the problem, I may record and upload the whole process from installing Manjaro from scratch to reproduce this problem.

**Comment by HubKing** [comment]
In fact, I have just created and uploaded a video from scratch. From installation to the problem, no edit. The video is about 12 minutes long, and I have uploaded the file at the same link above.

![image](https://user-images.githubusercontent.com/10900489/163703321-365ae980-ef6f-4bf2-bde8-85bfbc165183.png)

**Comment by charlesg99** [comment]
Sorry I edited my last post so you probably weren't notified of my comment. Yes you were right, I did install Manjaro and I could reproduce the issue exactly as you described in your first post. The issue was closed because I pushed a fix on the master branch that resolves the issue, thanks for reporting it!
