### ISSUE TITLE
dynamic background opacity doesn't work in versian 48 dash-to-panel

### ISSUE THREAD

**Issue by zanastar** [home-sweet-gnome/dash-to-panel#1630]
dynamic background opacity doesn't work because of gjs.
dash to panel 48
gnome 42
archlinux

**Comment by charlesg99** [comment]
Care to elaborate? Works fine on my Arch machines (wayland and xorg). Also how is GJS related?

**Comment by zanastar** [comment]
sorry about elaborate . 

#Describe the bug
I tested the xorg and there was no problem . But in wayland gjs it opens a full screen hidden window and that made the dynamic background opacity not work . I found out that gjs belongs to desktop-icons-ng (ding) . The problem is solved when I turn off the desktop-icons-ng (ding) . But in dash to panel version 46 this problem does not exist .


#Linux distribution and version
archlinux

#GNOME Shell version
42.0

#Display server
wayland

#Dash-to-Panel version
48

#Where was Dash-to-Panel installed from?
The GNOME extensions website

**Comment by zanastar** [comment]
sorry about elaborate .

#Describe the bug
I tested the xorg and there was no problem . But in wayland gjs it opens a full screen hidden window and that made the dynamic background opacity not work . I found out that gjs belongs to desktop-icons-ng (ding) . The problem is solved when I turn off the desktop-icons-ng (ding) . But in dash to panel version 46 this problem does not exist .

#Linux distribution and version
archlinux

#GNOME Shell version
42.0

#Display server
wayland

#Dash-to-Panel version
48

#Where was Dash-to-Panel installed from?
The GNOME extensions website

**Comment by charlesg99** [comment]
Thanks for clarifying, you're correct I could reproduce the issue. For some reason the workspace window api returns the DING wayland window, but it wasn't the case with the previous global one. I fix for it was added to the master branch and I'll release it on e.g.o. on thursday.
