### ISSUE TITLE
icons very big in version 48

### ISSUE THREAD

**Issue by ndias** [home-sweet-gnome/dash-to-panel#1631]
In version 48 the icons are very big
![Screenshot from 2022-04-19 15-52-06](https://user-images.githubusercontent.com/886782/164037403-ef9a8138-2dff-4502-982a-c65b77f4b5da.png)

 
In Previous versions 46 for example 

![Screenshot from 2022-04-19 15-57-29](https://user-images.githubusercontent.com/886782/164037419-40fe198d-e92e-4c32-902f-1cd93f175369.png)

gnome-shell-41.4-1.fc35.x86_64
Fedora 35

**Comment by charlesg99** [comment]
Lol "it's not a bug, it's a feature". In version 46 that was actually a bug where the correct scaling (200% monitor) wasn't applied on the icons when "animate icon hover" was selected, see #1613. You can play with the icons padding/margin an panel size to reduce the icons size, but to me the bottom image clearly is the buggy one :)

**Comment by ndias** [comment]
Ok, if it isn't a bug then your solution doesn't solve my problem, because of the bug #1330

**Comment by charlesg99** [comment]
You can change the panel size to reduce the icon size, but yes, at the moment icons are always square. I'll reopen your other issue.
