### ISSUE TITLE
gjs-console error on Dash to Panel Settings (Ubuntu 22.04)

### ISSUE THREAD

**Issue by rmkimathi** [home-sweet-gnome/dash-to-panel#1633]
gjs-console error reported everytime opening Dash to Panel Settings on Ubuntu 22.04

DTP: v48 1d6c052412eb1e1e7cef74eddf1470f6bfe05e84

ProblemType: Bug
DistroRelease: Ubuntu 22.04
Package: gjs 1.72.0-1
ProcVersionSignature: Ubuntu 5.15.0-25.25-generic 5.15.30
Uname: Linux 5.15.0-25-generic x86_64
ApportVersion: 2.20.11-0ubuntu82
Architecture: amd64
CasperMD5CheckResult: pass
CurrentDesktop: ubuntu:GNOME
Date: Wed Apr 20 00:25:33 2022
InstallationDate: Installed on 2022-04-18 (0 days ago)
InstallationMedia: Ubuntu 22.04 LTS "Jammy Jellyfish" - Daily amd64 (20220418)
SourcePackage: gjs

#### Bug also reported to Ubuntu launchpad:
https://bugs.launchpad.net/ubuntu/+source/gjs/+bug/1969530

**Comment by charlesg99** [comment]
Thanks!
