### ISSUE TITLE
Taskbar icons don't disappear

### ISSUE THREAD

**Issue by mbevc1** [home-sweet-gnome/dash-to-panel#1635]
**Describe the bug**
Anyone else noticed on Gnome 42 taskbar titles don't always disappear if you move mouse across neighbouring icons?

**Linux distribution and version**
Fedora 36

**GNOME Shell version**
GNOME Shell 42.0

**Dash-to-Panel version**
v48

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Comment by charlesg99** [comment]
Yes, looks like it should solve it, in the change log: `Backport MR #2321 to fix top bar hover issues`. Thanks!
