### ISSUE TITLE
Ability to adjust hover time

### ISSUE THREAD

**Issue by cha0s** [home-sweet-gnome/dash-to-panel#1636]
I'd like a setting to adjust (read: increase) the amount of time require for a hover to pop up the preview of the running application. The thing constantly pops up and gets in my way when I even momentarily move my mouse over an icon.

Also, if I'm hovering over one of the previews that pops up, it would be nice if ESC closed it, but it currently doesn't.

**Comment by charlesg99** [comment]
![image](https://user-images.githubusercontent.com/33044886/164322607-e626dff0-313c-42ee-8ce0-3723ce783e29.png)

![image](https://user-images.githubusercontent.com/33044886/164322687-dde99d68-332b-45b0-be93-51f233449025.png)

**Comment by cha0s** [comment]
Thank you so much! I don't know how I didn't see it.
