### ISSUE TITLE
Hover effects staying active when moving from one monitor to another over panel

### ISSUE THREAD

**Issue by PiiNGPooNG** [home-sweet-gnome/dash-to-panel#1638]
**Describe the bug**
Moving mouse from one monitor to another over the panel can cause hover effects of icons to stay active (background color, window preview). Only happens when immediately entering a window on the second monitor.

See video below for clarification.

This doesn't seem to happen with every program. For example, Files and Text Editor don't cause the bug, but Firefox and various games in fullscreen do.

**Linux distribution and version**
Fedora 35

**GNOME Shell version**
Gnome Shell 41.4

**Dash-to-Panel version**
48

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**

https://user-images.githubusercontent.com/8688059/164477284-544acc46-01ff-44ff-a2d9-c934dc3c548e.mp4

**Comment by PiiNGPooNG** [comment]
Sorry if this is related to #1620

**Comment by charlesg99** [comment]
Hi, not sure if this is the same as 1620, but it sure looks like something similar. I'm not aware that this mutter bug happened on 41 though and so far I can't reproduce with your monitor configuration (on 41.5 and 42). 

One thing is for sure, we don't ourselves make the distinction between hovering out over a window or not, we simply respond to the hover out event, which clearly isn't fired when over Firefox. Any chance you could update to 41.5, maybe that'll help?

**Comment by PiiNGPooNG** [comment]
On 41.5 now and it still happens

**Comment by charlesg99** [comment]
Gnome 41 is EOL let's reopen if this happens on more recent versions
