### ISSUE TITLE
make thumbnail-border semi transparent?

### ISSUE THREAD

**Issue by dobkeratops** [home-sweet-gnome/dash-to-panel#164]
Slight aesthetic tweak, would it be possible to make the border area around the window thumbnails semi-transparent, to reduce obstruction of the underlying workspace less? See illustration:-

![gnomeshellpanelthumbnailsuggestion2](https://cloud.githubusercontent.com/assets/1120754/26179121/9d488e4a-3b59-11e7-9d0b-5b1c6839bb7c.gif)

**Comment by jderose9** [comment]
This should be tweakable in the theme CSS, but an opacity setting on the fine-tune tab might be nice, if someone wants to implement it.

**Comment by charlesg99** [comment]
Hello dobkeratops! New window previews allowing you to customize the opacity of the border area were added to master, please try them out! Thanks for the suggestion!
