### ISSUE TITLE
Activities overview appears after login in X11 session

### ISSUE THREAD

**Issue by gergo424** [home-sweet-gnome/dash-to-panel#1643]
**Describe the bug**
I've got touchpad glitches with Wayland, so I prefer X11 session in Ubuntu 22.04. With dash to panel extension enabled, the graphical session starts with the activities overview (workspace switcher) which is unnecessary and looks like a bug. After every login I need to click on the main workspace to start my work.

**Linux distribution and version**
Ubuntu 22.04

**GNOME Shell version**
GNOME Shell 42.0

**Dash-to-Panel version**
49

**Where was Dash-to-Panel installed from?**
With Extensions Manager 0.3.0

**Screenshots / Video captures**
![Screenshot from 2022-04-24 10-38-07](https://user-images.githubusercontent.com/66968707/164968877-edd3b02c-e330-4b8c-a0f4-5c05d0ab61e6.jpg)

**Comment by charlesg99** [comment]
This is the default gnome-shell behavior, it would also happen without the extension. You can disable it:

![image](https://user-images.githubusercontent.com/33044886/164976455-f0af2c00-739d-4276-af83-a36d29d2c038.png)

**Comment by gergo424** [comment]
Thanks, now everything works as expected! Sorry for the false alarm.

**Comment by Laci69** [comment]
> Thanks, now everything works as expected! Sorry for the false alarm.

Thanks for reporting.My issue was solved as well.
