### ISSUE TITLE
Pop 22.04 Cosmic bug

### ISSUE THREAD

**Issue by cercledefeu** [home-sweet-gnome/dash-to-panel#1646]
Everytime i shutdown then power back on, reboot  or logoff at the return on the desktop show the dock + the dash to panel.  Have to go under gnome extention, turn off the extention then turn it back on to make it work properly

**Linux distribution and version**
pop!_os 22.04

**GNOME Shell version**
42.0

**Dash-to-Panel version**
latest at the time writing

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Comment by charlesg99** [comment]
Thanks, let's track the PopOs conflicts in #1645

**Comment by samvoelzke** [comment]
Hey did you fix the bug? I jave the same issue.
