### ISSUE TITLE
Rounded corners for focused app highlight

### ISSUE THREAD

**Issue by arun54321** [home-sweet-gnome/dash-to-panel#1647]
rounded corners on focused indicator highlight like in screenshot. firefox highlight having rounded corners.

![rounded](https://user-images.githubusercontent.com/42943340/165809857-269d74f6-d9e7-4978-a204-85e14998e334.png)

**Comment by charlesg99** [comment]
Hello, you might be interested by this thread to set your own css: https://github.com/home-sweet-gnome/dash-to-panel/issues/726
