### ISSUE TITLE
Open tray app with left click

### ISSUE THREAD

**Issue by amiranagram** [home-sweet-gnome/dash-to-panel#1651]
Hi, love your extension.

Is there any way to make the tray apps open on left click? Currently both left and right click open the context menu.

**Comment by amiranagram** [comment]
The ones on the right, whatever they are called!

![image](https://user-images.githubusercontent.com/38536188/167011060-502df630-1caf-4513-8346-561e6337dd1d.png)

**Comment by charlesg99** [comment]
Ha sorry I thought you meant opening the tray app, not the apps themselves. Looks like Ubuntu so it probably is https://github.com/ubuntu/gnome-shell-extension-appindicator, please open your issue over there as it is this extension that controls those icons and their behaviors. Thanks!
