### ISSUE TITLE
"Display the main panel" setting doesn't persist

### ISSUE THREAD

**Issue by hoishing** [home-sweet-gnome/dash-to-panel#1653]
Hi, 

Whenever I connect my laptop to an external monitor, the panel will automatically move from my laptop to the external monitor. I can switch it back by changing `Display the main panel` setting to `Primary monitor`. However, it won't persist. The next time I connect my laptop to the external monitor the setting will change to `Monitor 2` again. Note that all other settings persist except this one. How can I work around it? 

thanks,
Kelvin

**Comment by hoishing** [comment]
gnome: 42.1
dash-to-panel: v50

any other diagnostic info can I provide to help solving the issue?

**Comment by charlesg99** [comment]
Could you provide screenshots of the dash to panel settings dialog as well as the gnome display settings window before and after connecting your external monitor? Not sure why but over here the panel always follow the gnome primary monitor.

**Comment by hoishing** [comment]
## before connect
![Screenshot from 2022-05-08 14-13-57](https://user-images.githubusercontent.com/992475/167284381-9ed8c70c-0675-4714-b596-13cbc7fcd41d.png)

![Screenshot from 2022-05-08 14-13-30](https://user-images.githubusercontent.com/992475/167284380-4d0e5644-045e-491c-bb93-eb43cdf1a3cd.png)

## after connect
![Screenshot from 2022-05-08 14-12-06](https://user-images.githubusercontent.com/992475/167284373-45805b9c-b04e-4cc2-91f7-fabeda2a54d0.png)

![Screenshot from 2022-05-08 14-13-16](https://user-images.githubusercontent.com/992475/167284378-f5ca3261-8d0e-4db0-bd7e-296bccc63cbd.png)

**Comment by charlesg99** [comment]
Could you try the latest master branch and see if it helps?

**Comment by hoishing** [comment]
yeah, after installing the latest master branch. I tried to plug, unplug the external monitor, reboot and switch the computer on and off several times. The panel position still persists 👍 
I think it's been fixed, thanks a lot!
