### ISSUE TITLE
"Export to file" file-chooser dialog unable to "Cancel".

### ISSUE THREAD

**Issue by schachmat** [home-sweet-gnome/dash-to-panel#1658]
**Describe the bug**
In the extension settings when clicking on "Export to file" to export the settings, I get a standard dialog to choose a file. If I click on "Cancel" in that dialog, I expect it to close, but it does not. I have to enter a filename and click "Save" to close the file chooser.

**Linux distribution and version**
Debian Testing based

**GNOME Shell version**
41.4

**Dash-to-Panel version**
9999

**Where was Dash-to-Panel installed from?**
Debian Package `gnome-shell-extension-dash-to-panel` version `43+git20210906-b7213be-2`

**Comment by charlesg99** [comment]
Please update dash to panel, this is fixed since v47
