### ISSUE TITLE
Object 0x282d346a020 is not a subclass of GObject_Object, it's a Object

### ISSUE THREAD

**Issue by AlekseyMelikov** [home-sweet-gnome/dash-to-panel#1659]
I updated my Debian yesterday to the latest version of testing. After that, Dash to Panel not starting. The error that shows up in the extension manager is "Object 0x282d346a020 is not a subclass of GObject_Object, it's a Object".

In addition, another Gnome extension broke - Smart Transperent Topbar. Error - "Settings.Prefs is not a constructor". It may not be related, but I figured I should mention it.

**Comment by charlesg99** [comment]
The only way to ensure a correct update is to **restart gnome-shell** afterwards.

**Comment by charlesg99** [comment]
Which versions are you using (gnome-shell, dash-to-panel)?

**Comment by AlekseyMelikov** [comment]
GNOME Shell 3.38.6
Dash-to-Panel 42

**Comment by AlekseyMelikov** [comment]
I also tried running gnome with wayland. But it did not help.
![image](https://user-images.githubusercontent.com/56497157/168101195-1c3b5c1c-9965-4529-92e6-6c2c8e208e66.png)
![image](https://user-images.githubusercontent.com/56497157/168101310-0026afa4-40de-4f62-901b-dd58c147f6f0.png)
