### ISSUE TITLE
How to center taskbar?

### ISSUE THREAD

**Issue by wadkarkundan** [home-sweet-gnome/dash-to-panel#1660]
How to center the apps in taskbar. I think there was an option previously Taskbar position. I want to center all the apps please help

**Comment by charlesg99** [comment]
![image](https://user-images.githubusercontent.com/33044886/168068051-fb96523a-3206-4af5-91c3-2bd87a83713a.png)

**Comment by wadkarkundan** [comment]
Sorry I Feel so dumb now. Thanks anyways
