### ISSUE TITLE
Switching workspaces while the cursor is over the panel causes it to teleport 

### ISSUE THREAD

**Issue by rdgh8** [home-sweet-gnome/dash-to-panel#1662]
**Describe the bug**

1. Set "Scroll panel action" to Switch workspace, or just use keyboard shortcuts to change workspaces
2. Place cursor anywhere on panel
3. Switch workspaces

The cursor teleports to the left corner of the panel. 

**Linux distribution and version**

Pop!_OS 22.04

**GNOME Shell version**

42.0

**Dash-to-Panel version**

50

**Where was Dash-to-Panel installed from?**

The GNOME extensions website

**Screenshots / Video captures**

https://user-images.githubusercontent.com/66289396/168297829-42a41bde-0246-4485-9d1b-411b7bfd7665.mp4

**Additional Info**

Output from `journalctl /usr/bin/gnome-shell -f -o cat &`:

```
Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x562b05cfe300] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x562b07c7a340] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x562b07ca8350] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x562b18d73330] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x562b18da86e0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x562b05cfe300] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x562b07c7a340] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x562b07ca8350] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x562b18d73330] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x562b18da86e0] is on because it needs an allocation.
```

**Comment by aracnid** [comment]
I see this exact issue. The mouse jumps to the top-left corner of whatever window on that workspace happens to have the focus. The effect is even more jarring when the window in focus is on another monitor through an extended display.

**Comment by wh1rstclass** [comment]
Same here
`5.10.117-1-MANJARO` x86_64 GNU/Linux`

**Comment by li-richard20** [comment]
For me, it was Pop Shell extension. I turned off "Mouse Cursor Follows Active Window" and the cursor stopped teleporting.

**Comment by aracnid** [comment]
I have that Pop Shell extension still turned on, but the issue has since stopped after a recent software update.
