### ISSUE TITLE
Long context menus go behind the dock (gome 42)

### ISSUE THREAD

**Issue by nicolasmol** [home-sweet-gnome/dash-to-panel#1665]
Hi
- On Manjaro
- - Just updated to Gnome 42 yesterday (not intentionnally but because of the "automatic system upgrading" _(what a mess it was 🤷‍♂️)._
- DashtoPanel only extension + restart session : done

Just look at this screen capture
![image](https://user-images.githubusercontent.com/61077647/168439244-998d4267-8637-428c-9aed-916fcf3151dc.png)

**Comment by charlesg99** [comment]
Every gnome-shell ui elements are above the windows layer so no surprise here. Not much we can do about it.
