### ISSUE TITLE
All right click menus are popping up at same time

### ISSUE THREAD

**Issue by multiple1** [home-sweet-gnome/dash-to-panel#1668]
**Describe the bug**
Since i upgraded from Debian 10 to 11 the extension behaves strange.
Randomly (every 10s - 5min) all right click menus are popping up even if i do not click any taskbar element.

I can reproduce this issue by switching workspaces using the mouse wheel to switch between them.
But it also happens random e.g. after unlock. All available right click menus which should be hidden show up a short time ~40ms 
and close again.

**Linux distribution and version**
Debian GNU/Linux 11 (bullseye)

**GNOME Shell version**
GNOME Shell 3.38.6

**Dash-to-Panel version**
42

**Where was Dash-to-Panel installed from?**
The GNOME extensions website.

**Screenshots / Video captures**
![text](https://i.ibb.co/wCkLL48/ezgif-1-3330228a21.gif)

**Comment by charlesg99** [comment]
Did you restart since updating to g-s 3.38.6? I don't have a 3.38.6 machine atm but I've never seen this.

**Comment by multiple1** [comment]
Sorry for the noise.
I could narrow it down to this extension:
https://extensions.gnome.org/extension/1680/animation-tweaks/
I changed everything to the minimum, because I hate animations. So i have to dig further there.
