### ISSUE TITLE
popup desktop thumbnails, similar to application window thumbnails

### ISSUE THREAD

**Issue by dobkeratops** [home-sweet-gnome/dash-to-panel#167]
See illustration,
![gnomeshellpanelthumbnailsuggestion3](https://cloud.githubusercontent.com/assets/1120754/26180611/68e7cc34-3b62-11e7-8dce-4a500caa76b3.gif)
Would it be possible to make a popup display of the desktop/workspace thumbnails, visually similar to the application window thumbnails;

(alternative suggestion with similar goal - see #165,#168)

This would enable all navigation to be done from the panel easily, just flick the mouse across the lower edge to see rapid overviews of everything; it would reduce the total mouse movement needed to do something , compared to the overview mode.

Of course this might make the 'gnome shell overview' display a little redundant, but you'd still want to activate that to move windows between workspaces.

Whether or not this is worth doing depends how complex it is to code... how much of the existing framework functionality is easy to re-use for this to work.

I realise multiple redundant ways of doing the same thing might grate; however from what I can see this one 'dash-to-panel' extention has the potential to unify most of the important behaviour in one place, which is nice.

**Comment by jderose9** [comment]
Nice idea, thanks!
