### ISSUE TITLE
Changes the alignment of date and time on gnome bar

### ISSUE THREAD

**Issue by TripleK2004** [home-sweet-gnome/dash-to-panel#1671]
Distro: Ubuntu 22.04

https://user-images.githubusercontent.com/76064725/169101497-69984328-d726-424e-87b9-bac69063aafc.mp4

Is it a ubuntu configuration related issue ? Also affecting the desktop icons

Turns out its related to dash to panel directly, tested on vanilla gnome

**Comment by charlesg99** [comment]
This isn't dash to panel, it's the ubuntu dock. Thanks

**Comment by TripleK2004** [comment]
> This isn't dash to panel, it's the ubuntu dock. Thanks

But I did say that it behaves the same on vanilla gnome, tested on Fedora

https://user-images.githubusercontent.com/76064725/170894788-807fce4d-dead-4674-b116-adc64f4b2a95.mp4
