### ISSUE TITLE
The "main" monitor is changed after restart\sleep

### ISSUE THREAD

**Issue by Episqol** [home-sweet-gnome/dash-to-panel#1674]
Describe the bug:
I use Dash-to-panel on a laptop. At home I have a second monitor for him, which is regularly connected/disconnected. Often (I don't understand if there is any pattern) after restarting or coming out of sleep mode, the connected monitor turns out to be a "main". After changing the settings to an integrated monitor, it usually works fine for a while (half a day), then again after restarting\sleep, the setting changes to the connected monitor.
Is there anyway to configure the Dash-to-panel so that it does not automatically switch to the connected monitor?

**Linux distribution**: Manjaro rolling(don't found version)
**Kernel**: 5.15.32-1-MANJARO

**GNOME Shell versions**: 41.5, 42.1

**Dash-to-Panel version**: 50

Dash-to-panel was installed from gnome extensions site

**Comment by hunabku94** [comment]
Same issue for me in desktop and latop

Linux distribution: Archlinux
Kernel: 5.17.9-arch1-1
GNOME Shell versions: 42.1
Dash-to-Panel version: 50-1 (say me 9999 in extension's about section)

Dash-to-panel was installed form AUR (compilation)
Compilation script :
`pkgname=gnome-shell-extension-dash-to-panel
_name=dash-to-panel
pkgver=50
pkgrel=1
pkgdesc='Extension for GNOME shell to combine the dash and main panel'
arch=(any)
url="https://github.com/home-sweet-gnome/dash-to-panel"
license=(GPL2)
makedepends=(git gnome-common intltool make)
source=("${url}/archive/v${pkgver}.tar.gz")
sha256sums=('192abfd84b9a6108a2c31cb74afbdbdee49ba824ec91687e7ca60bd58fe5b435')

build() {
    cd "${srcdir}/${_name}-${pkgver}"
    make VERSION="$pkgver" _build
}

package() {
    depends=('gnome-shell')
    cd "${srcdir}/${_name}-${pkgver}"
    make DESTDIR="$pkgdir" install
}`

**Comment by charlesg99** [comment]
I'd like to fix this, but I can't reproduce it. I've added a possible fix to the master branch, can anyone having the issue consistently try it?

**Comment by hunabku94** [comment]
For me, the panel is correctly restored on the same monitor after reboot and sleep with latest master.
Thanks for your reactivity!

**Comment by Episqol** [comment]
It seems to be working fine, but the symptoms remain, perhaps there are also some problems in the gnome.

**Comment by hunabku94** [comment]
Problems occurs now again for me
