### ISSUE TITLE
error after update GObject_Object.prototype.[__GObject__hook_up_vfunc] called on incompatible Object.

### ISSUE THREAD

**Issue by Theluga** [home-sweet-gnome/dash-to-panel#1679]
I have pop os 21.10.
I use Dash to panel with arcmenu and I'm very happy with it.

The problem is after my update, the extension of dash to panel gets a red exclamation of error.
I have shell 40.5. The Dash to panel version is 44 and the error is:

GObject_Object.prototype.[__GObject__hook_up_vfunc] called on incompatible Object.

I tried reinstalling, restarting, installing the 43 version, trying the versions of other shells, nothing worked... Please, help!

Thank you!
![Screenshot from 2022-05-26 21-28-03](https://user-images.githubusercontent.com/96307393/170611001-f5015f7c-369a-4615-bf1c-f06b8e8d7048.png)

**Comment by Theluga** [comment]
I tried it now again and got a new error: 
Object 0x2edbacb59250 is not a subclass of GObject_Object, it's a Object

**Comment by charlesg99** [comment]
Hello, what is your `gnome-shell --version`? Looks like you have an incompatible dash to panel version, you'll probably have to install v50.

**Comment by Theluga** [comment]
Hello, it was 40.5. I got to know it was an error on the gtk and python libraries. I just installed manjaro with gnome 42.1. Everything is great! Sorry for the delay, lots of chores irl.
Thank you!
