### ISSUE TITLE
Reopening  #1215 (Main panel keeps moving to external monitor)

### ISSUE THREAD

**Issue by rodonile** [home-sweet-gnome/dash-to-panel#1681]
The issue was closed but the bug's still there (Fedora 36, Gnome 42). Refer to #1215 for description. And also the bot shouldn't close the issue if it is not resolved ;)

**Comment by charlesg99** [comment]
This should be fixed on the master branch.

**Comment by AlexGluck** [comment]
+1

**Comment by AlexGluck** [comment]
Seems have been fixed.
