### ISSUE TITLE
How to Install

### ISSUE THREAD

**Issue by sparks79** [home-sweet-gnome/dash-to-panel#1683]
How do I install Dash to Panel.
After I download it and Unzip it, I can't see any Install File.
I am using ubuntu 20.04.
I have seen in some other stuff they ask for your shell version and extension number, How do I find out this info

**Comment by charlesg99** [comment]
To get the shell version, in a terminal run `gnome-shell --version`
To get the extension version, in the settings dialog go in the "About" tab, or you can check the last line of the metadata.json file in the zip.
Install instructions: https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation
