### ISSUE TITLE
Visual bug in application titlebars

### ISSUE THREAD

**Issue by gfxonline** [home-sweet-gnome/dash-to-panel#1685]
**Things to do first**
Didn't find anything similar in existing open issues (I hope I covered all of them).
The output from the logs (captured while clicking on titlebars):
`Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x561516e65ef0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x5615137694e0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StBin>:0x561513738bf0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StBin>:0x561513738bf0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StBin>:0x561513738bf0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StBin>:0x561513738bf0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StBin>:0x561513738bf0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StBin>:0x561513738bf0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StBin>:0x561513738bf0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StBin>:0x561513738bf0] is on because it needs an allocation.`

**Describe the bug**
Hello!
I recently started noticing this glitch where the titlebars of open applications in the panel get "squished" when clicked on, but they go back to normal as soon as the mouse moves away from the titlebar.
This only happens when the panel runs out of "free" horizontal space, due to many applications being open at once, see screenshot below for a better description of the bug.
Also happens regardless of screen resolution. The screenshot was captured at 1920x1080 at 100% scaling.

**Linux distribution and version**
Pop!_OS 22.04 LTS

**GNOME Shell version**
GNOME Shell 42.1

**Dash-to-Panel version**
50

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
![Screenshot from 2022-06-01 18-50-46](https://user-images.githubusercontent.com/10722478/171583719-3e4a3696-2f4b-41be-a6c4-ff054fce9107.png)

**Additional Info**
Running on X11.
Please let me know if you need more information to reproduce :)

**Comment by gfxonline** [comment]
Bumping this up to avoid automatic closure.

**Comment by charlesg99** [comment]
Probably a conflict with PopOs. Try disabling their extension and see if that fixes it.

**Comment by gfxonline** [comment]
> Probably a conflict with PopOs. Try disabling their extension and see if that fixes it.

Sorry for the late reply. I tried that a few days ago and the issue persists. I'm now running version 56 and GNOME 42.5.
