### ISSUE TITLE
"New Workspace" missing from overview

### ISSUE THREAD

**Issue by MattSturgeon** [home-sweet-gnome/dash-to-panel#1688]
**Things I checked first**

- No related errors in `journalctl /usr/bin/gnome-shell -f -o cat &` , even when opening the overview.
- Found a couple issues about the rounded corners. Couldn't find anything about the "new" (empty) workspace being missing
- Issue present when dash-to-panel is the only enabled extension

**Describe the bug**

When dash-to-panel is enabled, the blank/empty "new" workspace (usually shown to the right of the right-most workspace) is missing from the overview.

**Linux distribution and version**
openSUSE Tumbleweed

**GNOME Shell version**
42.2

**Dash-to-Panel version**
50

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**

Screenshot showing vanilla behaviour ("new" workspace circled in red, at the far right of the screen):

![Screenshot from 2022-06-06 17-32-05_annotated](https://user-images.githubusercontent.com/5046562/172207950-881ed23a-2e05-4f8f-9471-1a0210fa172e.png)

Screenshot showing the issue: 

![Screenshot from 2022-06-06 17-32-24_annotated](https://user-images.githubusercontent.com/5046562/172208148-6df5d055-763a-44b6-ab0c-a5bd0acf1825.png)

Screenshot showing the issue still present when dash-to-panel is the only enabled extension:

![Screenshot from 2022-06-06 17-44-20](https://user-images.githubusercontent.com/5046562/172207105-d0e7a0c1-01c4-4304-a9ff-3acd73821da5.png)

Screenshot showing the issue when the overview is navigated to the "new" empty workspace (note how "workspace 1" isn't shown to the left, despite windows being open in it):

![Screenshot from 2022-06-06 18-02-40](https://user-images.githubusercontent.com/5046562/172209727-53655b20-93c2-4746-bd9f-db80926f3959.png)

**Additional Info**

- My best guess, is that the code which hides the overlay's dash is also affecting the "new" workspace.
- So far, I've only been able to reproduce the issue with only one workspace open. As soon as a second workspace is in use all workspaces (including the "new" workspace) show up properly in the overview.
- Using keybinds (by default `PgUp` and `PgDown`) you can still "navigate" the overview into the new/empty workspace.
- If the overview is showing the new/blank workspace, then the preview for Workspace 1 isn't shown. It should appear on the left-edge of the overview.

**Comment by charlesg99** [comment]
I remember that when I first saw this issue I could reproduce it with only one workspace and with the "dynamic workspaces" gnome option. Not sure if something changed in gnome but on 44 the empty workspace on the right side is visible (although smaller than with the default overview dash).

**Comment by charlesg99** [comment]
Haven't seen this since gnome-shell 44.
