### ISSUE TITLE
shared headerbar/panel for maximised application

### ISSUE THREAD

**Issue by dobkeratops** [home-sweet-gnome/dash-to-panel#169]
see illustration,
![unifiedmaximizedheaderbarpanelsuggestion](https://cloud.githubusercontent.com/assets/1120754/26185430/db1e4ee8-3b82-11e7-9002-94bb544c1c33.gif)

probably beyond the scope of the dash-to-panel extention alone, but would anyone be interested in this capability..
imagine if the panel splits, leaving space in the middle for a maximised header bar in the middle, to save screenspace for a maximised application. (it would require some means for header-bars to co-operate with the shell, reserving space)

IMO header bars are an interesting idea, but they would consume too much space alongside a system panel (especially one such as DashToPanel which takes up more vertical space for icons ) .

This is similar in intent to the ubuntu-unity space-saving mentality.

(I should look for other places to leave this suggestion aswell)

**Comment by SolarLiner** [comment]
This would be awesome. Space saving in Unity is the number one feature I'll miss in GNOME and while Pixel Saver is good enough, it just doesn't feel natural. This plus an integrated global menu and I'll never leave GNOME, ever.

**Comment by jderose9** [comment]
Nice idea! I'm not really sure how feasible it is but if someone is motivated to look into it, it would be a nice addition I think. Thanks!

**Comment by dobkeratops** [comment]
possible ways of doing this?
- the header-bar is part of the full-screen maximised window (as normal), and the panel is an overlay split into two parts, but it 'tells' the application header bars how much space on the left & right is taken up (as if the middle of the panel is transparent).. the header bars use that information when calculating their internal layout

- or the header bar simply gets the panel elements directly built in (... but that sounds harder to me)
