### ISSUE TITLE
Update `How do I move the notifications to somewhere other than the top center? Panel OSD`

### ISSUE THREAD

**Issue by hzhangxyz** [home-sweet-gnome/dash-to-panel#1692]
Panel OSD is archived, and there are some other extension to move notification to somewhere other than top centor, such as https://extensions.gnome.org/extension/4651/notification-banner-reloaded/

Please update the FAQ

**Comment by hzhangxyz** [comment]
Solved: (022dd14641c2d8)

**Comment by dimisjim** [comment]
This also achieves the same: https://extensions.gnome.org/extension/3843/just-perfection/
