### ISSUE TITLE
Dual monitor inversion (main <=> secondary) after switching off the second one

### ISSUE THREAD

**Issue by nicolasmol** [home-sweet-gnome/dash-to-panel#1697]
Hi everyone.
Manjaro, Gnome 42.1. HP Laptop without GPU + second monitor on HDMI.

Say you set the panel at "bottom" for main monitor (the laptop's one) and at "top" for the second one (on HMDI).

_Switch off the second monitor:_ 
Result: the bar comes at "top" on the laptop's screen, **whereas it should be at bottom.**

Swicth on the second monitor and everything is back correctly.

**Comment by AlexGluck** [comment]
+1

**Comment by danialdunson** [comment]
+1. i have to change to primary monitor in settings after turning off a display. triple monitor setup.
![image](https://user-images.githubusercontent.com/70681191/184029268-09804302-fd80-48a6-a8ac-3813baa3774e.png)

**Comment by charlesg99** [comment]
Please see #1215
