### ISSUE TITLE
Applications minimization animation glitch

### ISSUE THREAD

**Issue by Motor-head** [home-sweet-gnome/dash-to-panel#1698]
Applications are glitching on minimization action. There's an animation conflict between the dash to panel minimization downwards and gnome default minimization towards top left corner.

**Linux distribution and version**
Fedora 36.

**GNOME Shell version**
Gnome shell 42.2

**Dash-to-Panel version**
Dash to panel v50

**Where was Dash-to-Panel installed from?**
The GNOME extensions website.

**Screenshots / Video captures**
Attached.

https://user-images.githubusercontent.com/93347209/173250451-003d4230-3975-414f-8acb-408960338109.mp4

**Additional Info**
This was not present on Fedora 35. This is experienced after upgrading to Fedora 36.

**Comment by zzhiyi** [comment]
I can still reproduce this issue with a refresh install of Dash to Panel v56 and Ubuntu 23.04
