### ISSUE TITLE
When running under Wayland with dash-to-panel set to the top position, maximized windows sometimes appear underneath it upon resume from suspend

### ISSUE THREAD

**Issue by nekohayo** [home-sweet-gnome/dash-to-panel#1699]
**Describe the bug**
When coming back from suspend, some applications that were left maximized, particularly Firefox, will tend to show up underneath the top-positioned dash-to-panel. This only happens under the GNOME Wayland session, not the GNOME Xorg session, and only when dash-to-panel is positioned at the top of the screen (instead of the bottom).

This has been tested on Intel graphics, whether Sandybridge or Kabylake.

**Linux distribution and version**
I've tested this on a fresh install of Fedora 35 / GNOME 41.6, but also noticed this in previous versions. I tried looking for an existing report about this specific issue but surprisingly didn't find any.

**GNOME Shell version**
41.6

**Dash-to-Panel version**
50

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Comment by charlesg99** [comment]
Same root cause as #1600
