### ISSUE TITLE
Main panel position

### ISSUE THREAD

**Issue by Philippe-M** [home-sweet-gnome/dash-to-panel#1704]
Hello, I work with on a laptop. Sometimes I have 2 screens in addition to the laptop and other times I only have one screen in addition to the laptop.

In any case, the position of the main panel places it on the screen with the highest resolution, whereas in the Dash To Panel configuration it is set to "Main screen".

Dash To Panel: 50
Config : [dash2panel.txt](https://github.com/home-sweet-gnome/dash-to-panel/files/8973935/dash2panel.txt)
Fedora 35
Gnome 41.6
Wayland

**Comment by AlexGluck** [comment]
+1

**Comment by coling** [comment]
I get this too. Took me ages to realise that the setting kept getting reset after unplugging/plugging back in. I'm not sure why, but it changes way from "Primary Display" (which is automatically updated when plugging into a larger monitor) to (in my case) "Monitor 2" which happens to be the built in display for the laptop.

The net result is that if I unplug, the panel moves from the left external monitor (in my two external monitor + built-in display setup) to the built in display as it should. But when I plug back in, the panel is stuck on the built in display. Going into the extension settings and reselecting "Primary Display" will move the panel back to where it should be.

**Comment by charlesg99** [comment]
This is fixed in v51.
