### ISSUE TITLE
Feature request: Resize icons

### ISSUE THREAD

**Issue by hai-nguyen-van** [home-sweet-gnome/dash-to-panel#1707]
A nice customization feature would be to allow the user to resize icons of the Dash. Icons are quite big and leave very few margin compared to the task bar.

Similarly as done in [Dash to Dock](https://extensions.gnome.org/extension/307/dash-to-dock/):
![](https://micheleg.github.io/dash-to-dock/media/screenshots.png)

**Comment by charlesg99** [comment]
Should be able to get what you want with: 

![image](https://github.com/home-sweet-gnome/dash-to-panel/assets/33044886/5c447e89-12c7-4e3b-9603-6c163cd0dacb)

and
![image](https://github.com/home-sweet-gnome/dash-to-panel/assets/33044886/7ff93554-efc1-421d-953f-c4ab9f71cc5b)
