### ISSUE TITLE
"Move to current workspace" feature disappeared

### ISSUE THREAD

**Issue by sojusnik** [home-sweet-gnome/dash-to-panel#1708]
**Describe the bug**
In the recent version, the right-click menu entry "move to current workspace" of a preview window is missing, only "move to workspace left/right" is present. 

Is this by design or a bug?

In the meantime, another extension called [OFP](https://extensions.gnome.org/extension/5192/ofp-overview-feature-pack/) implemented a similar feature, where "Shift + Click Moves App To Current Workspace" in the Dash, see [this](https://github.com/G-dH/overview-feature-pack/blob/main/OFP2.png) picture.

Maybe it would be possible to add a similar function to this extension as well, f.i. in the settings of window preview, where at the moment you can only enable that a mouse middle-click should close the window. Perhaps adding there an option that a mouse middle-click should either close or move the window to the current workspace would do it, as already proposed [here](https://github.com/home-sweet-gnome/dash-to-panel/issues/831)?

Having a dedicated mouse action for such a frequently used feature, at least in my case, would tremendously help with window management.

**Linux distribution and version**
Ubuntu 22.04

**GNOME Shell version**
Gnome 42.2

**Dash-to-Panel version**
50

**Where was Dash-to-Panel installed from?**
GNOME extensions website

**Comment by charlesg99** [comment]
Thanks for reporting this, it was indeed broken since gnome-shell 42. Right clicking the window preview would also close it and leave the context menu opened, which wasn't expected. This should now be restored on the master branch.
