### ISSUE TITLE
way to make any monitor 'primary',

### ISSUE THREAD

**Issue by dobkeratops** [home-sweet-gnome/dash-to-panel#171]
on Mac OSX, the panel can be brought up on any display by moving the cursor into the area where it would be,

I read that it's hard to make the panel appear on 'all monitors', but maybe we could give a quick way to *switch* the 'primary monitor'..
ideas:-
- moving the cursor to the upper or lower edge on any screen activates it as primary,
- clicking the left-button or mid button on an empty desktop switches that screen to primary, (and then activates the overview)
- dragging the panel itself moves it between monitors, by activating them as primary.

of course it may not be ideal unless the panel has a popup option, because it would clash with window placements if it was constantly appearing and disappearing (but if it just hides when you move away, it would be fine)

**Comment by jderose9** [comment]
You can change your primary monitor in gnome which will move the panel to the monitor that you wish. I do intend to eventually have an option that replicates the panel to all monitors.

I think there's still valid reason to set the primary monitor as detailed here: https://github.com/jderose9/dash-to-panel/issues/154#issuecomment-301303653

**Comment by SharpOB** [comment]
Changing the primary monitor is **not** a solution.

I prefer my panel to be on my right monitor, and my games to be on my left. My left monitor needs to be primary to play games. Unfortunately, my right monitor needs to be primary to show the panel on it.

People should be able to designate a monitor to show the panel on.

**Comment by SharpOB** [comment]
This screenshot should show you how I'd like things:

![screenshot from 2017-06-18 12-43-02](https://user-images.githubusercontent.com/24550634/27260471-f8ede644-5424-11e7-95a5-585d2158d651.png)

Just a note: This is a feature that Windows already supports out of the box. Just unlock the taskbar and drag it to the bottom of the second monitor. It already defaults to the primary monitor, but can be moved. I see no reason why Dash to Panel shouldn't support the same.

**Comment by dobkeratops** [comment]
'games' .. I don't know whats available to gnome, and do you mean things running in fullscreen (i don't think games combine well with a composited desktop .. performance hit..) this sounds like a special case to me. still I fully agree about configurability (lock/unlock).

the behaviour on the mac is good IMO. i don't need to worry about 'which is primary'.  Whichever screen i'm on, if i move the mouse to the bottom, i get a task bar. if i move to the top, i get a menu.

**Comment by SharpOB** [comment]
I've never had a noticeable performance hit.

**Comment by amenoko** [comment]
I'm in a similar situation, I have two monitors and I'd like all games to open on my right monitor by default while having the panel on the left (like for checking the time and panel extensions etc.). This would be a super useful feature and I can't think of any other extension that can do it.

**Comment by charlesg99** [comment]
Hi, this option was added to master with the new multi-monitor feature. Thanks!
