### ISSUE TITLE
Blur effect does not work

### ISSUE THREAD

**Issue by ghost** [home-sweet-gnome/dash-to-panel#1710]
**Describe the bug**
Cannot get blur effect. The extension does not seem to include a built-in blur effect and Blur my shell does not seem to work with it.
I can get the blur on the panel without dash-to-panel, but with dash-to-panel using the Blur my shell extension doesn't change anything.

**Linux distribution and version**
Ubuntu 20.04

**GNOME Shell version**
GNOME Shell 3.36.9

**Dash-to-Panel version**
42

**Blur my shell version**
22

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Comment by bbk-riact** [comment]
somehow it started working after turning extensions on and off and rebooting the computer
