### ISSUE TITLE
Full Screen Width for Panel

### ISSUE THREAD

**Issue by arjun44** [home-sweet-gnome/dash-to-panel#1711]
**Describe the idea or feature you'd like**
Currently the only way to make the panel full width and use up all space is to manually edit the `gnome-shell.css` file and add `padding: 0` to the `#panelBox` id.

**Is your feature request related to a problem? Please describe.**
The problem is that the panel doesn't fit the entire width (and sometimes height) of the space given due to the padding in the `gnome-shell.css` file. Dash to Dock is able to scale their panel to the full screen width, so maybe a similar solution can be applied to this project for this problem.

![image](https://user-images.githubusercontent.com/41452613/178362194-dc5ff68e-cebd-4126-b449-ef60a5ca2358.png)

Caption: Dash to Panel doesn't fit the full screen width and remaining height due to padding constraints. The black portion has been edited out, and is not a problem.

**Comment by charlesg99** [comment]
What theme are you using? With the default gnome-shell theme, the panel uses the full width.

**Comment by arjun44** [comment]
IIRC I tried it on the default GNOME shell theme and I had the same issue. It only showed the full width panel for a theme that had the `padding: 0` in `gnome-shell.css`. So most themes didn't have a full width panel.

I'm not currently using Linux so this problem doesn't apply to me anymore and thus I can't test it.

I'll close this issue for the meantime - if anyone experiences the same problem again, they can comment and I will reopen.
