### ISSUE TITLE
The position of the menu in the vertical orientation of the dash

### ISSUE THREAD

**Issue by sashaoshurkov** [home-sweet-gnome/dash-to-panel#1714]
Hello,

OS: Fedora 36
Dash to Panel: 50

I'm using the tray extensions you recommended - AppIndicators and KStatusNotifierItems - and I'm having trouble positioning the menu relative to the app icon when Dash to Panel is in vertical mode. This happens in both Wayland and Xorg. Also, I already created a ticket to the authors of the extension, but there is no response from them https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/349 Could you help in solving the problem?
![Screenshot from 2022-07-22 13-46-12](https://user-images.githubusercontent.com/1682848/180424567-f918232e-5e4b-4458-b965-1afc11df73e1.png)
![Screenshot from 2022-07-22 13-46-22](https://user-images.githubusercontent.com/1682848/180424592-1cf4a2c0-9de9-4338-8010-78c7ccca252d.png)

**Comment by zuusuuz** [comment]
I've got a similar issue with the quick settings panel

![Screenshot from 2022-12-22 19-16-05](https://user-images.githubusercontent.com/103016847/209100797-d5ffde0e-a247-47e3-9110-5c6a6937674f.png)

The date/time popup and application icon menus are centered and work fine.

**Comment by charlesg99** [comment]
Fixed on master
