### ISSUE TITLE
Dash to Panel not working

### ISSUE THREAD

**Issue by Puner420** [home-sweet-gnome/dash-to-panel#1715]
The issue started when I upgraded Ubtuntu to 22.04 LTS. The Dash to Panel version I had then was 44. Now after the Ubutnu upgrade, the extension manager showed "Object 0x31ef239d1ae0 is not a subclass of GObject_Object, it's a Object" Error, so I googled a bit and found out that I just had to upgrade the DtP version to the latest one from the repo (version 50 in this  case), and now that I did that the extension manager says that the extension is not compatible with the GNOME version even tho my GNOME version is 42.2.

Things I've tried were installing other versions (from 40-50) but all of them show me the incompatible error except 44 which shows me the Object... error. 
![Screenshot-20220722143956-680x284](https://user-images.githubusercontent.com/66172945/180441137-469e3adf-7b51-4f11-8b05-2fb0727533fa.png)
![Screenshot-20220722144128-759x388](https://user-images.githubusercontent.com/66172945/180441343-6022a943-7835-4db6-b576-483da0be980c.png)
![Screenshot from 2022-07-22 14-43-36](https://user-images.githubusercontent.com/66172945/180441638-f5291cc2-57dd-4d94-af0a-9483e2f43708.png)

**Comment by charlesg99** [comment]
Please install the latest version.

**Comment by Puner420** [comment]
> Please install the latest version.

Um did you not read or see the screenshots I've posted? I've already tried that.

**Comment by charlesg99** [comment]
Yeah sorry I meant **re-**install the latest version (50), then restart gnome-shell. The extension is tested on Ubuntu 22.04 so if that doesn't work on your system you'll need to dig a bit. The error `Object 0x31ef239d1ae0 is not a subclass of GObject_Object, it's a Object` indicates a versions mismatch aka wrong installation.

![image](https://user-images.githubusercontent.com/33044886/187101171-57e82326-8bc9-4e29-8bf8-0cc1c8279867.png)

Thanks.

**Comment by Puner420** [comment]
I've tried that many times but it just shows wrong gnome version. I guess I'll just have to wait for new DtP version or more probably new Ubuntu release.
Thanks anyways.

**Comment by emilpeychev** [comment]
I compiled it and still got the same error as Aleksa.
