### ISSUE TITLE
name of this?

### ISSUE THREAD

**Issue by TrevorBlythe** [home-sweet-gnome/dash-to-panel#1716]
Running the install command says it has no installation candidate. There is no other names that i can find.
E: Package 'gnome-shell-extension-dash-to-panel' has no installation candidate

**Comment by bilguun-zorigt** [comment]
I had to build the installer, might help you until it's fixed

```bash
#/bin/bash

sudo apt install -y wget make gnome-extensions
wget https://github.com/home-sweet-gnome/dash-to-panel/archive/refs/tags/v50.tar.gz -P "$(xdg-user-dir DOWNLOAD)"
cd "$(xdg-user-dir DOWNLOAD)"
tar -xvzf "$(xdg-user-dir DOWNLOAD)/v50.tar.gz"
cd dash-to-panel-50
rm po/*
make install
gnome-extensions enable dash-to-panel@jderose9.github.com
```

**Comment by TrevorBlythe** [comment]
> I had to build the installer, might help you until it's fixed
> 
> ```shell
> #/bin/bash
> 
> sudo apt install -y wget make gnome-extensions
> wget https://github.com/home-sweet-gnome/dash-to-panel/archive/refs/tags/v50.tar.gz -P "$(xdg-user-dir DOWNLOAD)"
> cd "$(xdg-user-dir DOWNLOAD)"
> tar -xvzf "$(xdg-user-dir DOWNLOAD)/v50.tar.gz"
> cd dash-to-panel-50
> rm po/*
> make install
> gnome-extensions enable dash-to-panel@jderose9.github.com
> ```

thanks, still didnt work though. Your last command gives error:
fatal: not a git repository (or any of the parent directories): .git

**Comment by bilguun-zorigt** [comment]
> > I had to build the installer, might help you until it's fixed
> > 
> > ```shell
> > #/bin/bash
> > 
> > sudo apt install -y wget make gnome-extensions
> > wget https://github.com/home-sweet-gnome/dash-to-panel/archive/refs/tags/v50.tar.gz -P "$(xdg-user-dir DOWNLOAD)"
> > cd "$(xdg-user-dir DOWNLOAD)"
> > tar -xvzf "$(xdg-user-dir DOWNLOAD)/v50.tar.gz"
> > cd dash-to-panel-50
> > rm po/*
> > make install
> > gnome-extensions enable dash-to-panel@jderose9.github.com
> > ```
> 
> thanks, still didnt work though. Your last command gives error:
> fatal: not a git repository (or any of the parent directories): .git
> 

Restart and try the last step.

**Comment by TrevorBlythe** [comment]
> > > I had to build the installer, might help you until it's fixed
> > > ```shell
> > > #/bin/bash
> > > 
> > > sudo apt install -y wget make gnome-extensions
> > > wget https://github.com/home-sweet-gnome/dash-to-panel/archive/refs/tags/v50.tar.gz -P "$(xdg-user-dir DOWNLOAD)"
> > > cd "$(xdg-user-dir DOWNLOAD)"
> > > tar -xvzf "$(xdg-user-dir DOWNLOAD)/v50.tar.gz"
> > > cd dash-to-panel-50
> > > rm po/*
> > > make install
> > > gnome-extensions enable dash-to-panel@jderose9.github.com
> > > ```
> > 
> > 
> > thanks, still didnt work though. Your last command gives error:
> > fatal: not a git repository (or any of the parent directories): .git
> 
> Restart and try the last step.

My bad it was actually the "make install" command causing the error.

**Comment by bilguun-zorigt** [comment]
> > > > I had to build the installer, might help you until it's fixed
> > > > ```shell
> > > > #/bin/bash
> > > > 
> > > > sudo apt install -y wget make gnome-extensions
> > > > wget https://github.com/home-sweet-gnome/dash-to-panel/archive/refs/tags/v50.tar.gz -P "$(xdg-user-dir DOWNLOAD)"
> > > > cd "$(xdg-user-dir DOWNLOAD)"
> > > > tar -xvzf "$(xdg-user-dir DOWNLOAD)/v50.tar.gz"
> > > > cd dash-to-panel-50
> > > > rm po/*
> > > > make install
> > > > gnome-extensions enable dash-to-panel@jderose9.github.com
> > > > ```
> > > 
> > > 
> > > thanks, still didnt work though. Your last command gives error:
> > > fatal: not a git repository (or any of the parent directories): .git
> > 
> > 
> > Restart and try the last step.
> 
> My bad it was actually the "make install" command causing the error.

my showed that error too, but target was successfully created, check if you have this dir created ~/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/

**Comment by TrevorBlythe** [comment]
It did! its working now. All you have to do is:

`cd ~/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/`  

after the make install command (i guess that part didnt work)

Thanks for the help you are a good good man

**Comment by TrevorBlythe** [comment]
It did! its working now. All you have to do is:

`cd ~/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/`  

after the make install command (i guess that part didnt work)

Thanks for the help you are a good good man
