### ISSUE TITLE
icon not showing when launching app with multiple windows

### ISSUE THREAD

**Issue by krodelabestiole** [home-sweet-gnome/dash-to-panel#1719]
hello, when opening an app with many windows dash to pannel won't show its icon. it works when openning windows one by one.

It is the case with Vivaldi or VScodium for instance (when last sessions had many windows).

Times to times it shows a glitchy icon : the appearing animation seems to freeze (see the red Vivaldi icons on screenshots).

Everything shows correctly when I disable and re-enable the extension.
The problem still occurres with every other extensions turned off.

journalctl shows an error such as :
```
JS ERROR: TypeError: record is undefined
_syncStacking@resource:///org/gnome/shell/ui/workspaceAnimation.js:81:13
Timelines with detached actors are not supported. <unnamed>[<StDrawingArea>:0x5636538b97c0] in animation of duration 200ms but not on stage.
```
I'm not sure it's related though.

Dash-to-Panel 50 installed from the GNOME extensions website.
GNOME Shell 42.3.1
Debian 5.18.5-1 (2022-06-16) x86_64 GNU/Linux

![Capture d’écran du 2022-07-25 18-40-13](https://user-images.githubusercontent.com/409655/180834103-8caf8ca8-ab05-42d5-859d-149418614b74.png)
![Capture d’écran du 2022-07-25 18-53-07](https://user-images.githubusercontent.com/409655/180834120-29263fc5-4460-46b3-bb5c-88d45630de18.png)

**Comment by pudup** [comment]
A temporary fix for me is having apps be ungrouped. Something you could try before this gets fixed.
Settings>Behaviour>Ungroup Applications

**Comment by charlesg99** [comment]
Hi, I think this is the same as #1737, could you install the master branch and see if that fixes it?
