### ISSUE TITLE
How to add some space between app icons and panel border? 

### ISSUE THREAD

**Issue by waldhef** [home-sweet-gnome/dash-to-panel#1721]
Hello,
I'am trying to add some space (padding?) between the app icons and panel border of a vertical panel.
See the picture I've attached:

![Panel](https://user-images.githubusercontent.com/93084746/181351808-bdc3e536-0911-4b3b-95bb-51004d6f769e.jpg)

I've done it by editing: `.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panel.js`
and changed the line:
```javascript
const panelSize = PanelSettings.getPanelSize(Me.settings, this.monitor.index);
```
to:
```javascript
const panelSize = PanelSettings.getPanelSize(Me.settings, this.monitor.index) + 12;
```

Then I added the following code to: `.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/stylesheet.css`

```css
#dashtopanelScrollview .dash-item-container > StWidget { 
	border-left: 6px;
	border-right: 6px;
}
```
It works just fine, but I wonder is there a more elegant way to achieve it? Maybe by only some css manipulations without editing the source code of `panel.js`?

Thank you in advance.

**Comment by Rio-Proton** [comment]
Use the Dash-to-Panel Settings, Style tab, "App icon margin" and "App icon padding" to change the icon padding in the panel. One will change the horizontal padding; the other the vertical padding. To find just the right settings, move each slider left and right with your mouse while watching your panel. Then settle the slider where the icons look padded properly to you.
![Screenshot from 2022-08-15 10-26-28](https://user-images.githubusercontent.com/111303498/184684976-321206a6-0e06-4cc6-b112-c8ca30f3b3d1.png)

**Comment by waldhef** [comment]
Thank you for your answer!
Yes I'm aware of this two sliders, but the first one "App icon margin" will only change the spacing between the apps icons among themselves, and the second one "App icon padding" will only change the icon size. In both cases the highlight area of the current active app will reach the panel border.
Maybe I did not express myself correctly, but with padding I mean this small stripe (in my case 6px) between the highlight area of the current active button and the panel border.

**Comment by Rio-Proton** [comment]
I see now you're referring the the "selected" icon background. I have not found a setting specifically addressing the opacity of that background. Try this (export your settings before you make changes):  On the Styles tab go to the bottom section beginning with "Override panel theme..." and turn everything off in this section. Hover your mouse over an icon until the tooltip displays then check the opacity of the background surrounding the icon. I notice yours are grayish. Mine are black matching the panel background so almost transparency maybe 10% opacity which is OK. I don't need that background anyway because of the tooltip. I'm not sure why it even displays but if you want to come up with a unique patch, maybe you can figure out how to get that "selected" background added as a setting so we can turn it on or off, color it, etc. Or is is already there and we just don't know it?

**Comment by waldhef** [comment]
Thank you very much for your suggestion, but I can't imagine how the change of the panel opacity, will bring an gap between the panel border an the highlighted icon. 

I think I will stick with my solution for now, which I described in my fist comment. It works great, I just thought there is maybe a less hacky way to achieve this.


> I don't need that background anyway because of the tooltip. I'm not sure why it even displays but if you want to come up with a unique patch, maybe you can figure out how to get that "selected" background added as a setting so we can turn it on or off, color it, etc. Or is is already there and we just don't know it?

If you want to disable, that the app icons gets highlighted if you hover with the mouse over it, you can achieve this by some style sheet manipulation. The style sheet file of Dash to Panel `stylesheet.css` you can find in your home directory under `.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/`

First make a backup of the original file with:
`cp ~/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/{stylesheet.css,stylesheet.css.bak}`

In case you made something wrong you can restore the original file with:
`cp ~/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/{stylesheet.css.bak,stylesheet.css}`

then open the file with your text editor of choice (eg.: gedit)
`gedit ~/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/stylesheet.css`

look for the section:

```css
.dashtopanelMainPanel .show-apps:hover .overview-icon,
#dashtopanelScrollview .app-well-app:hover .dtp-container,
#dashtopanelScrollview .app-well-app:focus .dtp-container {
	background-color: rgba(238, 238, 236, 0.1);
}
```

and change the line `background-color: rgba(238, 238, 236, 0.1);` to `background-color: none;`. So the section becomes:

```css
.dashtopanelMainPanel .show-apps:hover .overview-icon,
#dashtopanelScrollview .app-well-app:hover .dtp-container,
#dashtopanelScrollview .app-well-app:focus .dtp-container {
	background-color: none;
}
```

Finally save the file, log out and log in again. Now there shouldn't be any highlighting if you hover with the mouse over the apps icons. 

But be aware, on the next update of Dash to Panel this file gets overwritten and you have to apply this change again.

**Comment by Rio-Proton** [comment]
That's a nice workaround. Thanks for that. It removes the hover background-color; the dash icons now appear almost as they are floating.

**Comment by rogi27** [comment]
Would be nice to have this option included in the extension, because right now apps look too different from basic Gnome UI elements (no roundness and padding)

**Comment by charlesg99** [comment]
Let's keep the border radius discussion in #1586

**Comment by Web-inspector894** [comment]
> That's a nice workaround. Thanks for that. It removes the hover background-color; the dash icons now appear almost as they are floating.





https://csser.space/questions/modifying-the-background-color-of-the-selected-menu-item
