### ISSUE TITLE
Show Applications button does not reach bottom-left corner

### ISSUE THREAD

**Issue by PlanckTimeGames** [home-sweet-gnome/dash-to-panel#1728]
When Dash To Panel is at the bottom of the screen and the "Show Applications" button is the leftmost button on the panel, moving your mouse to the bottom-left corner of the screen and clicking does not activate the "Show Applications" button.

If any other button is the leftmost button, like "Activities button", "Taskbar", etc., then clicking on the bottom-left corner activates that particular button, but not so for the "Show Applications" button.

Given that the "Show Applications" button is the most natural button to be the leftmost button, this behavior is very inconvenient.

**Comment by charlesg99** [comment]
Try with the default gnome-shell theme, works fine for me.
