### ISSUE TITLE
login to activities instead of normal desktop (ubuntu 22.04)

### ISSUE THREAD

**Issue by TNirvT** [home-sweet-gnome/dash-to-panel#1730]
On Ubuntu 22.04, while Dash-to-Panel is the only enabled extension, every time log-in brings me to the activities view (just like when press a super key), instead of normal desktop.

- Ubuntu 22.04
- GNOME Shell 42.2
- Dash-to-Panel version 50, downloaded from extensions website, manually installed.

**Comment by waldhef** [comment]
Hello,
you have to activate "Don't show overview on start" see also the screenshot:

![screenshot](https://user-images.githubusercontent.com/93084746/184846752-0a72c27d-bcdf-411f-8243-0c3d7272a1f5.jpg)
.
it is on the third tab "Behavior" on the panel settings.

Please close this bug if it works for you.
