### ISSUE TITLE
No schema available on Gnome 42

### ISSUE THREAD

**Issue by dave-kennedy** [home-sweet-gnome/dash-to-panel#1732]
**Describe the bug**

No schema available. Can't restore the default value any dash-to-panel settings.

**Linux distribution and version**
Pop!_OS 22.04 LTS

**GNOME Shell version**
42.3.1

**Dash-to-Panel version**
50

**Where was Dash-to-Panel installed from?**
[Extension Manager](https://github.com/mjakeman/extension-manager)

**Screenshots / Video captures**
![image](https://user-images.githubusercontent.com/13735532/185686721-1576892f-44b8-4eb9-a58a-04099039bdfa.png)

**Additional Info**
Awesome extension. You actually made GNOME usable for me.

**Comment by charlesg99** [comment]
See the [faq](https://github.com/home-sweet-gnome/dash-to-panel#faq) about settings reset. If you want to reset a single setting, just put its name in the command like `dconf reset -f /org/gnome/shell/extensions/dash-to-panel/animate-appicon-hover-animation-extent`. We do provide a default value in our shema and I agree that it would be nice if dconf would show it somewhere.
