### ISSUE TITLE
Adaptive height not working /gnome 42

### ISSUE THREAD

**Issue by Kushtrim2** [home-sweet-gnome/dash-to-panel#1735]
Adaptive length is not working.

I have looked up for a solution, the only thing I could find was to disable "extend-height" in dconf but it's not doing anything for me.

Also positioning the dock in custom places would be a nice feature to have. Example: I want mine a little higher than the bottom, not attached to the bottom.

P.S. I Love the extension in general.

**Comment by charlesg99** [comment]
You're probably looking for [dash to dock](https://github.com/micheleg/dash-to-dock/issues) as extend-height isn't a dash to panel setting.
