### ISSUE TITLE
Volume change not working on gnome v43

### ISSUE THREAD

**Issue by raicabogdan** [home-sweet-gnome/dash-to-panel#1738]
**Describe the bug**
Volume change on scroll action isn't working

**Linux distribution and version**

Distributor ID:	Ubuntu
Description:	Ubuntu Kinetic Kudu (development branch)
Release:	22.10
Codename:	kinetic

**GNOME Shell version**
:~$ gnome-shell --version
GNOME Shell 43.beta

**Dash-to-Panel version**
Version 50

**Where was Dash-to-Panel installed from?**
Directly from github, last master version

**Screenshots / Video captures**
Not applicable

**Additional Info**
JS ERROR: TypeError: item.slider is undefined
_handleScrollEvent@resource:///org/gnome/shell/ui/status/volume.js:445:24
_onPanelMouseScroll@/home/folder/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panel.js:1325:22

**Comment by raicabogdan** [comment]
My temporary work around is this until a new update

                var item = Main.panel.statusArea[Utils.getSystemMenuInfo().name]._volume.quickSettingsItems[0];

                const result = item.slider.scroll(event);
  
                const gicon = new Gio.ThemedIcon({name: item.getIcon()});
                const level = item.getLevel();
                const maxLevel = item.getMaxLevel();
                Main.osdWindowManager.show(-1, gicon, null, level, maxLevel);

                //func.call(Main.panel.statusArea[Utils.getSystemMenuInfo().name]._volume, 0, event);

**Comment by charlesg99** [comment]
Thanks for reporting this!
