### ISSUE TITLE
Dash to Panel does not follow scaling rules when changing which monitor it displays on.

### ISSUE THREAD

**Issue by GloriousEggroll** [home-sweet-gnome/dash-to-panel#1739]
What is the problem:
```
I have two monitors:

Primary: Ultrawide 5120x1440 32:9
Secondary: 4k 16:9

I keep my ultrawide at 100% scale
I keep my 4k at 200% scale

(Settings > Displays > choose monitor > choose scale option)

Since I play most of my games on my ultrawide, I change dash 
to panel to display on 'Monitor 2', however it retains the 100%
scale value from my primary monitor instead of using the 200% 
scale factor of my 'Monitor 2', which of course looks very tiny
on 4k:
```
![Screenshot from 2022-08-31 19-07-38](https://user-images.githubusercontent.com/11287837/187811240-5f825da4-2a49-4380-ab55-e67b375de5f6.png)
![Screenshot from 2022-08-31 19-08-21](https://user-images.githubusercontent.com/11287837/187811243-981c55c8-2284-4f74-9070-397baf70ca1e.png)
![Screenshot from 2022-08-31 19-08-43](https://user-images.githubusercontent.com/11287837/187811244-53032ccf-f026-41fd-b790-43128b869293.png)
![Screenshot from 2022-08-31 19-08-51](https://user-images.githubusercontent.com/11287837/187811245-4b417664-ff44-43de-996d-d539c7a7773a.png)

What is expected:
```
Ideally, if dash to panel is displayed on a different monitor,
it should follow the scale setting for that monitor.
```

Linux distribution and version:
```
Nobara 36 (Fedora)
```

GNOME shell version:
```
$ gnome-shell --version
GNOME Shell 42.3.1
```

Dash-to-Panel version:
```
50
```

Where was Dash-to-Panel installed from?:
```
Built from git to fedora copr rpm:
```
https://download.copr.fedorainfracloud.org/results/gloriouseggroll/nobara/fedora-36-x86_64/04770022-gnome-shell-extension-dash-to-panel/

**Comment by Janhouse** [comment]
Seems like it keeps the scale that was used on the primary monitor (in Gnome settings).

**Comment by charlesg99** [comment]
I didn't even know you could specify a different scale factor per monitor. Not sure how though as on my system when I change it for a monitor all the others change as well. In all cases this would be a feature request for gnome itself as in GJS there is only one scale factor available and it is the same for the whole stage (every monitors combined).
