### ISSUE TITLE
DTP does not respect #panel margin in GTK theme

### ISSUE THREAD

**Issue by rstanuwijaya** [home-sweet-gnome/dash-to-panel#1740]
**Describe the bug**
When `margin` property `#panel` exist in the gnome theme, the items in the DTP appear to have some offset due to the added margin, causing items are not correctly centered in the panel 
  
**Linux distribution and version**
PopOS 22.04

**GNOME Shell version**
42.3.1, with Orchis-Dark theme

**Dash-to-Panel version**
50

**Where was Dash-to-Panel installed from?**
GNOME Store extension

**Screenshots / Video captures**
![image](https://user-images.githubusercontent.com/55012032/188040232-62c927c3-3e4d-4c23-a137-29d10712f175.png)

![image](https://user-images.githubusercontent.com/55012032/188040358-8fb98dcc-86a1-45f4-97fa-1a8d87e70ca2.png)

**Comment by charlesg99** [comment]
The theme would need to be adjusted
