### ISSUE TITLE
Notification counter not showing up

### ISSUE THREAD

**Issue by vittoriocioe** [home-sweet-gnome/dash-to-panel#1746]
Hello,

I am using Dash to Panel v42 on Gnome Shell v40 on Oracle Linux 9. The notification counter badge is not visible nor there is a toggle to activate it in the Behavior tab of the preferences.

I looked at the gschema.xml file and the progress-show-count field has value true.

Is it an issue or is it supposed to be like that?

Thanks a lot for the response

**Comment by Alt37** [comment]
I guess this functionality depends on "libunity" package.
And for notification badge from most programs which deliver notification you may try [modification](https://github.com/home-sweet-gnome/dash-to-panel/issues/1695#issuecomment-1160077515) from #1695

**Comment by vittoriocioe** [comment]
Hi, I tried the fix you suggested and now notification badge it is showing properly (disappears when you open the program which notified, not when you read the e-mail for example...but does not matter so much at this point).
For the toggle in the options, I guess libunity is specific of Ubuntu so nothing to do here.
Thanks a lot for the help!

**Comment by evgen-p-at-gorgany** [comment]
> I guess libunity is specific of Ubuntu so nothing to do here.

With "libunity" I was able to get badge for [Ferdium](https://github.com/ferdium/ferdium-app) on KDE Plasma. Seems like it provides badges and progress bar for programs which support [Unity Launcher API](https://wiki.ubuntu.com/Unity/LauncherAPI).
Dash to Dock "[used libunity at some point](https://github.com/micheleg/dash-to-dock/pull/590)", [not sure](https://github.com/home-sweet-gnome/dash-to-panel/issues/98) about "Dash to Panel"...

**Comment by charlesg99** [comment]
Duplicate of #1695
