### ISSUE TITLE
Opacity not respected

### ISSUE THREAD

**Issue by Philippe-M** [home-sweet-gnome/dash-to-panel#1754]
Hello,

In the DashToPanel setting I activated the opacity of the panel but the behavior is amazing. Depending on my place of work I have 1 or 2 screens in addition to that of the laptop (main screen).

Sometimes the opacity setting will be taken into account on the main screen and all of a sudden the background of the bar will again be 100% opaque.

For the test I activated the panel on all my screens and surprise, on the secondary screens the opacity setting is ok.

![image](https://user-images.githubusercontent.com/4558101/191681698-445d517d-c690-434f-aac4-e3668cb1e0d5.png)

Complement :
After a few hours of using my computer, none of the panels respect the opacity setting. Nothing in particular happened except for the aging of the screens.

![image](https://user-images.githubusercontent.com/4558101/191699927-89849db7-ee1e-4584-a0ad-0ea4d78c3a67.png)

Fedora: 36 Wayland
Gnome: 42.4
DashToPanel : 51
Config file : [dashtopanel.zip](https://github.com/home-sweet-gnome/dash-to-panel/files/9623235/dashtopanel.zip)

**Comment by Philippe-M** [comment]
Hello, I found the source of the problem.

This is an incompatibility with the Blur my Shell extension https://extensions.gnome.org/extension/3193/blur-my-shell/

**Comment by charlesg99** [comment]
Thanks for the follow up, I'm also using blur my shell, do you happen to know which combination of settings causes the issue?

**Comment by Philippe-M** [comment]
Hello,

I searched the options of Blur my shell and to have a normal behavior with DashToDock I disabled "Blur of the panel"

![image](https://user-images.githubusercontent.com/4558101/192709976-d8d12f42-8075-41dc-9238-5d24388dc694.png)

With "Blur of the panel" active

![image](https://user-images.githubusercontent.com/4558101/192710121-41304e4c-5a44-4917-8ff3-df3c3cfa1816.png)
