### ISSUE TITLE
Intellihide and QuickSettings (Gnome 43)

### ISSUE THREAD

**Issue by freddyw** [home-sweet-gnome/dash-to-panel#1755]
**Describe the bug**
Using Gnome 43 with the new and shiny 'QuickSettings' status area, combined with d-t-p's intellihide things are not working well when there are other windows open hiding the panel. On mouse-over, the panel displays, but as soon you want to click anything in the menu the panel hides again, so the menu action is not performed. Only when minimizing all windows (like 'show desktop') or explicitly showing the panel by using <super>i you can choose an action in the QuickSettings menu. 

**Linux distribution and version**
Fedora 37

**GNOME Shell version**
GNOME Shell 43.0

**Dash-to-Panel version**
version 51, git snapshot from 2022/09/21 (commit d0d655c)

**Where was Dash-to-Panel installed from?**
github

**Additional Info**
I was able to reproduce the issue on Fedora 36 using the 'quick-settings-extension' ( https://gitlab.gnome.org/fmuellner/quick-settings-extension ). 

Other status area menu's are working fine (like the notification and calendar menu).

Resetting intellihide settings to default does not make a difference.

**Comment by freddyw** [comment]
Thanks a lot for the quick fix, can confirm that it works as expected now!

**Comment by freddyw** [comment]
Did some more testing and the issue is not fully resolved. Expanding the menu works, but when of the items has sub-items (like wireless networks) you can't choose these sub-items, the panel hides again on click. I hope this makes sense, kind of hard to explain. Again, snapping the panel into place with <super>i the QuickSettings menu works as expected.

**Comment by charlesg99** [comment]
Thanks again, I could reproduce the panel hiding on sub items open. Should now work on master, hopefully this is it :)

**Comment by freddyw** [comment]
I hope i covered all the bases, seems to work just fine now. Thanks again for the prompt support!!
