### ISSUE TITLE
Package gnome-shell-extension-dash-to-panel is not available, but is referred to by another package.

### ISSUE THREAD

**Issue by NorthenIrbis** [home-sweet-gnome/dash-to-panel#1756]
I try to install Dash to panel from a terminal but i`ve got an error
➞  sudo apt-get install gnome-shell-extension-dash-to-panel                                                                                                                    
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package gnome-shell-extension-dash-to-panel is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'gnome-shell-extension-dash-to-panel' has no installation candidate

Could you help we? why have I got the error?

Thanks!

**Comment by charlesg99** [comment]
We do not package the extension for Debian/Ubuntu. Seems like Ubuntu [decided to remove the extension packages](https://discourse.ubuntu.com/t/update-for-dash-to-panel-package/27346) from their repo so you can ask them for the why. You can install the extension from [e.g.o](https://extensions.gnome.org/extension/1160/dash-to-panel/)
