### ISSUE TITLE
"Display window preview headers", when enabled, causes window previews to instantly disappear upon hover

### ISSUE THREAD

**Issue by EntityinArray** [home-sweet-gnome/dash-to-panel#1759]
**Things to do first**

- [x] Confirm that the problem persists when Dash-to-Panel is the only enabled extension. To do so, disable every other extension, then restart gnome-shell by running the `r` command from the prompt that appears when pressing Alt+F2 on an X.org session, or by logging out/in on a Wayland session.

- [x] ```No messages in log```
Look for Dash-to-Panel errors in your log. To do so, run the `journalctl /usr/bin/gnome-shell -f -o cat &` command and reproduce the problem.
- [x] Search existing opened and closed issues to see if the problem has already been reported.

**Describe the bug**
When "Display window preview headers" setting is enabled, it sometimes can cause a situation, where window previews show up when you hover over icon, but then instantly disappear as you move your mouse over the preview itself.

**Linux distribution and version**
Fedora Linux 36 (Workstation Edition)

**GNOME Shell version**
GNOME Shell 42.5

**Dash-to-Panel version**
version: 52

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
Video that shows the problem:
[preview_bug.webm](https://user-images.githubusercontent.com/18554021/192710420-8d0e3317-c74d-4f01-866a-b761ef6f348b.webm)

**Additional Info**

**Comment by charlesg99** [comment]
Is that a new thing since gnome-shell 42.5? I can't reproduce on 43.1 and It didn't do that for me on 42.4 before I moved to 43.
