### ISSUE TITLE
Application button visible while disabled

### ISSUE THREAD

**Issue by Philippe-M** [home-sweet-gnome/dash-to-panel#1765]
Hello,

I use three screens:
- That of the laptop
- 2 external screens.

The laptop screen is set as the main screen. On one of the two external ones the "Application" button appears even though I disabled it in the settings.

![image](https://user-images.githubusercontent.com/4558101/193519767-83ef2606-7824-458f-817a-d077f417c818.png)

Fedora 36
Gnome 42.4 Wayland
DashToPanel 52
Config : [dashtopanel.txt](https://github.com/home-sweet-gnome/dash-to-panel/files/9695357/dashtopanel.txt)

**Comment by charlesg99** [comment]
Hi, in your config file there are only 2 monitors with defined positions, so the third one is using the default values (visible Show Applications button). One thing that I can think of is if you connected the third monitor while dash to panel settings dialog was opened, it wouldn't take the new monitor into account until you reopened the dialog.

**Comment by Philippe-M** [comment]
All the monitors are activated when the machine is started and all display an image before I enter my username and password for my session.

![image](https://user-images.githubusercontent.com/4558101/193592610-a048eca5-c7e9-4524-8be4-157c6a53f48a.png)

**Comment by charlesg99** [comment]
Can you screenshot the dash to panel settings dialog showing the faulty panel positions? Your 3 monitors are in this dropdown?

**Comment by Philippe-M** [comment]
Yes the three screens are in the list.

![image](https://user-images.githubusercontent.com/4558101/193617072-483f5e11-9104-4ed6-aa93-b8dbac9724e0.png)

**Comment by charlesg99** [comment]
Can you screenshot the dash to panel settings dialog showing the faulty panel positions?

**Comment by Philippe-M** [comment]
Miracle, I just figured out the "problem". I was the one who didn't understand that I could configure the bar per screen or globally.

So there is no bug, if not in my head ;)

Sorry for the inconvenience.

**Comment by charlesg99** [comment]
No problem, glad it's working!
