### ISSUE TITLE
Window maximization and minimization animation is broken when autohide enabled

### ISSUE THREAD

**Issue by archee565** [home-sweet-gnome/dash-to-panel#1766]
The maximize/minimize animation is broken, it just delays and pops. Works fine while auto-hide is off.

Reproduce: Turn on auto-hide, maximize any window, then minimize it. 

Same behavior on:
Fedora 36, debian testing 
gnome 42,43,  
dash-to-panel 52
installed from extension site.
wayland and x11

**Comment by charlesg99** [comment]
Looks fine to me:

https://user-images.githubusercontent.com/33044886/193808667-0780db0e-171f-40b8-9206-f86ebc72bc68.mp4

**Comment by charlesg99** [comment]
https://user-images.githubusercontent.com/33044886/193814257-5d5cfd82-6a60-4844-b865-83cf85ee46e2.mp4

How about you show me?

**Comment by archee565** [comment]
Apparently it's broken only with top panel off.

https://user-images.githubusercontent.com/75748397/193840161-bb657504-e6fe-4c0d-9ead-33c76c6610e7.mov

**Comment by charlesg99** [comment]
Can you export your settings and upload them here? Maybe there is something in there that would help me reproduce as switching the top panel on/off makes no difference on my machine. 

To export your settings:

![image](https://user-images.githubusercontent.com/33044886/193927352-8ee49cb8-d517-4526-9ee3-319486f6bc44.png)

**Comment by archee565** [comment]
[/]
animate-appicon-hover-animation-extent={'RIPPLE': 4, 'PLANK': 4, 'SIMPLE': 1}
appicon-margin=7
appicon-padding=0
available-monitors=[0]
dot-position='LEFT'
group-apps=false
group-apps-label-font-color-minimized='#cdab8f'
group-apps-label-font-size=12
group-apps-label-font-weight='lighter'
group-apps-label-max-width=130
group-apps-use-launchers=true
hotkeys-overlay-combo='TEMPORARILY'
intellihide=true
leftbox-padding=-1
panel-anchors='{"0":"MIDDLE"}'
panel-element-positions='{"0":[{"element":"showAppsButton","visible":false,"position":"stackedTL"},{"element":"activitiesButton","visible":false,"position":"stackedTL"},{"element":"leftBox","visible":true,"position":"stackedTL"},{"element":"taskbar","visible":true,"position":"stackedTL"},{"element":"centerBox","visible":true,"position":"stackedBR"},{"element":"rightBox","visible":true,"position":"stackedBR"},{"element":"dateMenu","visible":true,"position":"stackedBR"},{"element":"systemMenu","visible":true,"position":"stackedBR"},{"element":"desktopButton","visible":true,"position":"stackedBR"}]}'
panel-lengths='{"0":100}'
panel-positions='{"0":"LEFT"}'
panel-sizes='{"0":38}'
primary-monitor=0
show-apps-icon-file=''
status-icon-padding=-1
tray-padding=-1
tray-size=0
window-preview-title-position='TOP'

**Comment by charlesg99** [comment]
Can't reproduce

**Comment by HardcodeCoder** [comment]
I am getting a similar issue on Arch with gnome 42. In my case this is most noticeable with chromium and gnome settings.
I don't have any other extensions installed apart from user themes.

[/]
animate-app-switch=true
animate-appicon-hover=false
animate-appicon-hover-animation-convexity={'RIPPLE': 2.0, 'PLANK': 1.0, 'SIMPLE': 0.0}
animate-appicon-hover-animation-extent={'RIPPLE': 4, 'PLANK': 4, 'SIMPLE': 1}
animate-appicon-hover-animation-rotation={'SIMPLE': 0, 'RIPPLE': 10, 'PLANK': 0}
animate-appicon-hover-animation-travel={'SIMPLE': 0.10000000000000001, 'RIPPLE': 0.40000000000000002, 'PLANK': 0.0}
animate-appicon-hover-animation-type='SIMPLE'
animate-appicon-hover-animation-zoom={'SIMPLE': 1.5, 'RIPPLE': 1.25, 'PLANK': 2.0}
appicon-margin=0
appicon-padding=6
available-monitors=[0]
dot-style-focused='SOLID'
dot-style-unfocused='DOTS'
group-apps=true
group-apps-use-launchers=true
hide-overview-on-startup=true
hotkeys-overlay-combo='TEMPORARILY'
intellihide=true
intellihide-behaviour='MAXIMIZED_WINDOWS'
intellihide-close-delay=200
intellihide-hide-from-windows=true
intellihide-show-in-fullscreen=true
intellihide-use-pressure=false
leftbox-padding=4
leftbox-size=16
panel-anchors='{"0":"MIDDLE"}'
panel-element-positions='{"0":[{"element":"showAppsButton","visible":true,"position":"stackedTL"},{"element":"activitiesButton","visible":false,"position":"stackedTL"},{"element":"leftBox","visible":false,"position":"stackedTL"},{"element":"taskbar","visible":true,"position":"centerMonitor"},{"element":"centerBox","visible":false,"position":"stackedBR"},{"element":"rightBox","visible":true,"position":"stackedBR"},{"element":"dateMenu","visible":true,"position":"stackedBR"},{"element":"systemMenu","visible":true,"position":"stackedBR"},{"element":"desktopButton","visible":false,"position":"stackedBR"}]}'
panel-lengths='{"0":100}'
panel-sizes='{"0":40}'
primary-monitor=0
secondarymenu-contains-appmenu=true
secondarymenu-contains-showdetails=false
show-appmenu=true
show-apps-icon-file=''
show-apps-icon-side-padding=0
show-favorites-all-monitors=false
show-running-apps=true
status-icon-padding=4
stockgs-keep-dash=false
stockgs-keep-top-panel=false
stockgs-panelbtn-click-only=true
trans-panel-opacity=0.65000000000000002
trans-use-custom-bg=false
trans-use-custom-gradient=false
trans-use-custom-opacity=true
trans-use-dynamic-opacity=false
tray-padding=4
tray-size=16
window-preview-title-position='TOP'

**Comment by EmilyisWIP** [comment]
Anyone had any luck fixing this?

**Comment by oparada1988** [comment]
Im having a similar Minimize animation bug that so far only effects nautilus and other gnome apps like the extension


https://user-images.githubusercontent.com/4031078/216209599-ef91f5a9-f515-4140-8e96-8a746dbb1631.mp4


Settings:

[/]
animate-appicon-hover-animation-extent={'RIPPLE': 4, 'PLANK': 4, 'SIMPLE': 1}
appicon-margin=8
appicon-padding=4
available-monitors=[0, 1]
hotkeys-overlay-combo='TEMPORARILY'
leftbox-padding=-1
panel-anchors='{"0":"MIDDLE","1":"MIDDLE"}'
panel-lengths='{"0":100,"1":100}'
panel-sizes='{"0":48,"1":48}'
primary-monitor=0
status-icon-padding=-1
tray-padding=-1
window-preview-title-position='TOP'

**Comment by paulo-roger** [comment]
> 

I have the very same bug, GNOME 44.3

**Comment by egirlcatnip** [comment]
this should be reopened, the issues is still present
