### ISSUE TITLE
Dynamic Background opacity should only be affected by windows of same monitor

### ISSUE THREAD

**Issue by raul-lezameta** [home-sweet-gnome/dash-to-panel#1767]
**Describe the bug**
Technically not a bug, but definitely an unexpected behavior in my opinion. The dynamic background opacity feature doesn't work as expected for vertical multi-monitor setups. I have the panel set to transparent by default, and configured it to turn opaque when a window touches it. 

Looking at the following screenshot, you see the problem: The window from the second monitor touches the panel and therefore makes it opaque. I really think it should stay transparent, since no windows on the same monitor touches it.
![Screenshot from 2022-10-04 22-18-47](https://user-images.githubusercontent.com/50103002/193921583-2b44cc1d-80f0-4ba1-b48f-776e27c8fcb1.png)

It might't not look wrong from the screenshot above, but keep in mind that physically there is always a bezel between the two monitors. This makes it really look wrong as it is currently implemented because a window from the monitor below would never really touch the dock seeing that it is separated by the bezels. I therefore think the dynamic background opacity should only be affected by windows of the same monitor by default, if not this could at least be an option.

**Linux distribution and version**
Arch

**GNOME Shell version**
42.5

**Dash-to-Panel version**
52

**Where was Dash-to-Panel installed from?**
The GNOME extensions website,

**Comment by charlesg99** [comment]
Thanks for pointing that out! Please install the master branch and report any problem, it should now behave as you described.
