### ISSUE TITLE
Matrix on bottom-panel will only show 6 workspaces

### ISSUE THREAD

**Issue by cponder** [home-sweet-gnome/dash-to-panel#1768]
I set up my bottom-panel to show the workspace-matrix and am able to switch workspaces by clicking on the corresponding cell of the matrix.
Also I can drag/drop application-windows between cells.

The problem is that if I increase the number of workspaces greater than 6, the matrix disappears and is replaced by a counter of the number of workspaces.
If I click on the counter, it gives me a pop-up list of the workspaces, but I don't want that.

I'm using Ubunto 22.04.
I was using Ubuntu 18.04 before, and could show 12 or more workspace cells on the matrix.

**Comment by charlesg99** [comment]
What extension are you using to provide the "workspace-matrix" on the panel?

**Comment by cponder** [comment]
Using the `dtconf editor`, would it be listed under the `/org/gnome/shell/extensions/dash-to-panel`?

**Comment by charlesg99** [comment]
I just installed wsmatrix and it doesn't provide the visual workspaces on your panel: https://user-images.githubusercontent.com/1598765/194525103-4f4a9ac6-5f0d-40d3-b007-15ad4b285a95.png

You have another extension for that, check here to see what you have installed: https://extensions.gnome.org/local/

**Comment by cponder** [comment]
This link says
GNOME Shell Extensions cannot list your installed extensions.
Is there some other way to generate the list?

**Comment by charlesg99** [comment]
Or in your terminal: `gnome-extensions list --enabled`

**Comment by cponder** [comment]
Ok -- I think "workspace indicator" is the issue here.
Just for the record though, here's the full list.
Thanks for pointing me to the HTTP listing.
![Extensions 1](https://user-images.githubusercontent.com/1598765/195964232-d0d3796a-3675-40fd-ad9e-eb67235c1297.png)
![Extensions 2](https://user-images.githubusercontent.com/1598765/195964234-0fab1306-09a3-41db-b91a-dee601635b49.png)

**Comment by cponder** [comment]
I re-filed the issue here:
https://gitlab.gnome.org/GNOME/gnome-shell-extensions/-/issues/417

**Comment by charlesg99** [comment]
Here is the commit where they decided to limit the thumbnails number to 6

https://gitlab.gnome.org/GNOME/gnome-shell-extensions/-/commit/bb2b1204b47a26c0003b795dce3aff5a372ec97d

**Comment by cponder** [comment]
Ok here's the fix that I can use:
```
sudo vi /usr/share/gnome-shell/extensions/workspace-indicator@gnome-shell-extensions.gcampax.github.com/extension.js        # Set MAX_THUMBNAILS=20. Was =6.
gnome-extensions disable workspace-indicator@gnome-shell-extensions.gcampax.github.com
gnome-extensions enable  workspace-indicator@gnome-shell-extensions.gcampax.github.com
```
