### ISSUE TITLE
show date and time in two lines when there is enough room for two lines.

### ISSUE THREAD

**Issue by zhangfuwen** [home-sweet-gnome/dash-to-panel#1769]
**Describe the idea or feature you'd like**

this is a feature request.
When showing date, day and time. I takes too much room when displayed in a single line. I hope they can wrap in two lines and thus saving some space horizontally.

**Is your feature request related to a problem? Please describe.**
NA.

**Additional context**
Add any other context or mock-ups for requested feature here.
NA.

**Comment by charlesg99** [comment]
Maybe a locale problem? Can you provide more info on your datetime format/locale?

This is what it (and should) looks like here:

![Peek 2023-04-11 08-47](https://user-images.githubusercontent.com/33044886/231167369-bf9eeb94-f6b2-4287-aadb-1489633df63b.gif)

**Comment by dbedrenko** [comment]
Thanks for the quick reply. 


* Here is how it looks like on my screen:
![image](https://user-images.githubusercontent.com/6204199/231248350-a3bd3146-0752-44c4-bc66-be75b57c5385.png)
* Your Dash To Panel settings window seems to be much different to mine; I don't have "Panel thickness" nor "Panel length" settings, for example. But I pulled the latest version from the [Extension page](https://extensions.gnome.org/extension/1160/dash-to-panel/). It's called "Version 9999" in the Extension "About" panel.
* Standard timezone: BST London.

![image](https://user-images.githubusercontent.com/6204199/231247399-64ab8810-b107-4671-a3c7-25f3c10f7acc.png)

But actually I found a workaround: the "[Datetime Format](https://extensions.gnome.org/extension/1173/datetime-format/)" extension works very well in overriding the clock format.

**Comment by charlesg99** [comment]
This is an old version of dash to panel. When correctly installed from [extensions.gnome.org](https://extensions.gnome.org/extension/1160/dash-to-panel/), you should see the version number in the about tab, "9999" is a placeholder and means it wasn't installed properly (my guess is that it came from Ubuntu repositories). You should be using v42 which is the last one supporting gnome 3.36 on Ubuntu 20.04:

![image](https://user-images.githubusercontent.com/33044886/231535825-25ac6da8-abad-486b-ba49-74e9ba0e9095.png)

**Comment by forteller** [comment]
Hi. I have this same problem, with the version installed from e.g.o.

The clock used to wrap around to two lines, but then I reinstalled my OS (Nobara 39), and now it stays on one line. Some times the font size is reduced to show the whole clock, while other times the clock overflows and I can only see the hours. I don't know why or when which of these things happens, it seems to be random.

I'd love to get the clock back on two lines. Let me know if you need any more info from me. Thanks!

Gnome 45.5, D2P 60

**Comment by kaisellgren** [comment]
For those who google this, the "Date Menu Formatter" extension with this setting:

![image](https://github.com/user-attachments/assets/a8a0f1bb-396b-468d-8324-c020acd7c05b)

Will show up nicely like this:

![image](https://github.com/user-attachments/assets/57f3916e-b576-4957-b25f-20a628de2585)

If the text is too wide, it will hide. The `\n` in the pattern provides a new line.
