### ISSUE TITLE
[Duplicate #666] Add glass effect.

### ISSUE THREAD

**Issue by Rexadev** [home-sweet-gnome/dash-to-panel#1770]
**Describe the idea or feature you'd like**A clear and concise description of what you want to happen.

Like transparency add Blur/Glass effect

**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Additional context** Add any other context or mock-ups for requested feature here.

Like `macOS` and `Windows`

**Comment by nekohayo** [comment]
This is a duplicate of issue #666, so please close this ticket as such. Someone would need to provide a patch for it.
