### ISSUE TITLE
Dynamic opacity doesn't update when minimizing background windows

### ISSUE THREAD

**Issue by Wuestengecko** [home-sweet-gnome/dash-to-panel#1771]
**Things to do first**
- [x] Confirm that the problem persists when Dash-to-Panel is the only enabled extension.
- [x] Look for Dash-to-Panel errors in your log.
- [x] Search existing opened and closed issues to see if the problem has already been reported.

**Describe the bug**
I have the top bar configured to 80% when a window is maximized and 40% otherwise. When I focus a non-maximized window and hide a backgrounded maximized window (via shift-click on the icon in the bar, or via `super-shift-<number>`), the top bar's opacity does not change until the next time the active/focused window changes.

Step-by-step repro:

1. Configure DtP with dynamic top bar opacity: 40% normally / 80% when a window is maximized ("influenced by: maximized windows").
2. Open two non-maximized / floating windows.
3. Open a maximized window.\
   The top bar correctly changes to 80% opacity.
4. Bring one of the non-maximized windows to front and focus it.
5. Without changing focus to it, hide the maximized window (e.g. with `super-shift-<number>` keyboard shortcut, if configured).\
   The top bar opacity should change to 40%, because no maximized window is visible anymore, but doesn't.\
   (Note that Super+RMB does change focus and therefore doesn't trigger the bug.)
6. Change focus to the other non-maximized window.\
   Top bar opacity now updates to 40%.

This happens individually per top bar, but all bars update on the next focus change, regardless of which monitor the focused/unfocused windows are on.

**Linux distribution and version**
Arch

**GNOME Shell version**
GNOME Shell 42.5

**Dash-to-Panel version**
v52 <sup>(extension settings show 9999)<sup>

**Where was Dash-to-Panel installed from?**
[The AUR](https://aur.archlinux.org/packages/gnome-shell-extension-dash-to-panel)

**Comment by charlesg99** [comment]
Thanks for reporting this, I could reproduce the issue. It should now work properly on the master branch.
