### ISSUE TITLE
everytime i need to restore window i have to click the desktop

### ISSUE THREAD

**Issue by geziliu** [home-sweet-gnome/dash-to-panel#1773]
After enable "Ungroup applications", when I minimize a window(only one or last one), i can't restore it when I click it, I guess becuase that it does not lose the focus, so i have to click the desktop top for change the focus, after that i can restore it.

how can i fix it,  everytime i need to restore window i have to click the desktop, it is so annoying...

thanks

https://user-images.githubusercontent.com/59383373/195565637-9f469ecd-70ed-45da-a0b7-f91ee9f0f7e0.mp4

**Comment by charlesg99** [comment]
Hello, I can't reproduce the issue. Must be a conflict with something else, please provide more information about your system:

**Things to do first**
- Confirm that the problem persists when Dash-to-Panel is the only enabled extension. To do so, disable every other extension, then restart gnome-shell by running the `r` command from the prompt that appears when pressing Alt+F2 on an X.org session, or by logging out/in on a Wayland session.
- Look for Dash-to-Panel errors in your log. To do so, run the `journalctl /usr/bin/gnome-shell -f -o cat &` command and reproduce the problem.
- Search existing opened and closed issues to see if the problem has already been reported.

**Linux distribution and version**
Ubuntu 18.04, Fedora 31, Manjaro 19.02, Arch, Debian 10.3, openSUSE Leap 15.1, etc.

**GNOME Shell version**
Run `gnome-shell --version` from the command line to get this

**Dash-to-Panel version**
This can be seen in the Dash-to-Panel Settings in the About tab.

**Where was Dash-to-Panel installed from?**
The GNOME extensions website, GNOME Software store, your distribution's package manager, pre-installed with the distribution, directly from github, etc.

**Comment by geziliu** [comment]
thanks for answering my questions.
1, i got 2 extension witch is Desktop icons NG, Ubuntu Appindicators, i ve tied to disable them, ALT+F2, r，it s same problem
2, journalctl /usr/bin/gnome-shell -f -o cat &
> Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x5642e2ef8b30] is on because it needs an allocation.
> Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x5642e27ca6e0] is on because it needs an allocation.
> Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x5642e05f8330] is on because it needs an allocation.
> Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x5642e2ef8b30] is on because it needs an allocation.
> Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x5642e27ca6e0] is on because it needs an allocation.
> meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
> meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
3,I ve searched all the issues before i asked;

Linux distribution and version
Description:	Ubuntu 22.04.1 LTS
Linux home 5.15.0-48-generic #54-Ubuntu SMP Fri Aug 26 13:26:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

GNOME Shell version
GNOME Shell 42.4

Dash-to-Panel version
52

Where was Dash-to-Panel installed from?
https://extensions.gnome.org/


I am so sorry, i still can't figure out

**Comment by geziliu** [comment]
@charlesg99

thanks very much.

i  solved the problem.
It is caused by the DeepWine.
when i uninstall the deepwine, pb was solved.

thanks again. 
good luck
