### ISSUE TITLE
Group favorites

### ISSUE THREAD

**Issue by Samuel-B-D** [home-sweet-gnome/dash-to-panel#1774]
**Describe the idea or feature you'd like**
It would be nice to have the ability to group the favorites together to the left or to the right.

Grouping them together on the left would behave mostly like "quick-launch-icons" in Windows versions prior to Windows 7 (Vista and earlier).

Having active applications intertwined with inactive ones is fine when using icons-only style, but it is very weird looking and disruptive when using labels (pre-windows7-style), leading me to currently just disabling favorite all-together for now.

**Comment by charlesg99** [comment]
Try this:

![image](https://user-images.githubusercontent.com/33044886/195708104-26990cd8-6738-4afe-8dcb-0da7b6972d3e.png)
