### ISSUE TITLE
hover font is too big

### ISSUE THREAD

**Issue by liukliukliuk** [home-sweet-gnome/dash-to-panel#1776]
Currently in Fedora 37, the font in Calendar, Volume settings, etc. are bigger than the panel and the rest of the shell.

![image](https://user-images.githubusercontent.com/46636729/196016387-bdd2317f-f53d-4b04-a083-a5d3ac7efde7.png)

**Comment by charlesg99** [comment]
What theme are you using? I use the default gnome-shell theme and the font size seem to match. Did you set a custom tray icon size in dash to panel settings?

![image](https://user-images.githubusercontent.com/33044886/201528013-06a3d6e4-e463-46c4-8e1f-95f6d2965f87.png)
