### ISSUE TITLE
Gamescope in borderless fullscreen is glitchy with the taskbar

### ISSUE THREAD

**Issue by LethalManBoob** [home-sweet-gnome/dash-to-panel#1777]
1. It doesnt hide the taskbar
2. If its set to intellihide it will still trigger it to come up if the mouse is moved downwards, even if the cursor should not be visible

**Comment by charlesg99** [comment]
Probably the same as #1666, fixed in the latest version

**Comment by LethalManBoob** [comment]
> Probably the same as #1666, fixed in the latest version

The error still occurs.

**Comment by charlesg99** [comment]
`gamescope -h 1080 -H 1080 -b vkcube` is not fullscreen, [it's a window](https://github.com/Plagman/gamescope#options) "-b: create a border-less **window**."

Try `gamescope -f vkcube`

**Comment by LethalManBoob** [comment]
➜  ~ gamescope -f vkcube
wlserver: [backend/headless/backend.c:68] Creating headless backend
/home/main-builder/pkgwork/src/SwiftShader/src/Vulkan/libVulkan.cpp:3763 WARNING: UNSUPPORTED: pProperties->pNext sType = 1000212000
/home/main-builder/pkgwork/src/SwiftShader/src/Vulkan/libVulkan.cpp:3763 WARNING: UNSUPPORTED: pProperties->pNext sType = 1000212000
vulkan: selecting physical device 'NVIDIA GeForce RTX 3070': queue family 2
vulkan: physical device supports DRM format modifiers
vulkan: vkCreateDevice failed (VkResult: -3)
Failed to initialize Vulkan


Nvidia is out of luck regarding this.

**Comment by LethalManBoob** [comment]
Still broken my dude.

**Comment by PadTrick** [comment]
still broken.

**Comment by LethalManBoob** [comment]
i dont think it is for me as of the latest nvidia driver today. i will test some more

**Comment by PadTrick** [comment]
nvidia drivers 530.xx & 535.xx are broken for all 4 of my pascal gpu based systems.
530.xx has gfx glitches and some games/3d apps crashing.
535.xx has the same bugs as 530.xx, but also has non working opengl

**Comment by LethalManBoob** [comment]
gamescope doesnt even work with nvidia rn so yeah still an issue

**Comment by charlesg99** [comment]
Seems more like an issue with gamescope.
