### ISSUE TITLE
Icon padding ideally shouldn't cause icon scaling

### ISSUE THREAD

**Issue by Turbine1991** [home-sweet-gnome/dash-to-panel#1778]
**Describe the bug**
I'm advocating for the icon size to be decoupled from the panel thickness and border.

Whenever you increase the icon padding, the icons scale/shrink to yield space for the padding. **Instead of the padding being allocated around a set icon size**. Causing icons to be malformed due to scaling on non-standard icon sizes. This would also make it easy for custom taskbar buttons like that provided by ArcMenu to match the icon size.

Icons are most crisp at their respective sizes 32x32, 48x48, 64x64, 128x128, etc.

**Linux distribution and version**
Fedora 33

**GNOME Shell version**
43.0

**Dash-to-Panel version**
52

**Where was Dash-to-Panel installed from?**
The GNOME extensions website.

**Screenshots / Video captures**
(For some reason I can't drag clips in)
https://tempclip.com/watch/I67JDBBjzc

**Additional Info**
Perhaps panel thickness could be calculated by icon size + border thickness. This issue has been the only gripe I've ever had with this extension. I really hope this can be seriously considered in order to improve the appearance of the taskbar icons for all users.

Thank you.

**Comment by charlesg99** [comment]
I agree it's not ideal, but that setting normally doesn't change much once you set it to your liking. Atm it's not so hard to get the icon size you want e.g. I always set my panel size (34px) and icon padding (1px) to end with 32px icons. Granted, setting an explicit icon size would be more straight forward, but unless we restrict the user to the standard sizes, we'll end up with the same problem of malformed icons anyway.

As a workaround, maybe next to the icon padding slider we could indicate the actual icon size resulting from the panel size / icon padding combination? We could also make it obvious when the icon size is "optimal" (standard size).
