### ISSUE TITLE
QuickSettings menu disappears when expanded sublist is larger than screen size

### ISSUE THREAD

**Issue by malfisya** [home-sweet-gnome/dash-to-panel#1779]
**Things to do first**
- Confirm that the problem persists when Dash-to-Panel is the only enabled extension. To do so, disable every other extension, then restart gnome-shell by running the `r` command from the prompt that appears when pressing Alt+F2 on an X.org session, or by logging out/in on a Wayland session.
- Look for Dash-to-Panel errors in your log. To do so, run the `journalctl /usr/bin/gnome-shell -f -o cat &` command and reproduce the problem.
- Search existing opened and closed issues to see if the problem has already been reported.

**Describe the bug**
Clicking GSConnect quick menu shows nothing

**Linux distribution and version**
Solus 4.3 Kernel 5.15

**GNOME Shell version**
GNOME Shell 43.0

**Dash-to-Panel version**
52

**Where was Dash-to-Panel installed from?**
Extension Manager via Flathub

**Screenshots / Video captures**
If applicable, add screenshots or a link to a video capture to help explain your problem.
[DTP enabled.webm](https://user-images.githubusercontent.com/101771435/196559873-d2d96595-0973-4be1-9579-191989c711fe.webm)
[DTP disabled.webm](https://user-images.githubusercontent.com/101771435/196559887-e4a8cb49-7213-4544-a3a4-ff866456fbca.webm)
[dtp enabled.txt](https://github.com/home-sweet-gnome/dash-to-panel/files/9815552/dtp.enabled.txt)
[dtp disabled.txt](https://github.com/home-sweet-gnome/dash-to-panel/files/9815553/dtp.disabled.txt)

**Additional Info**

**Comment by charlesg99** [comment]
Should stop disappearing when using the master branch.

**Comment by malfisya** [comment]
It works, thank you
