### ISSUE TITLE
Ubuntu 22.10, menu doesn't line up when the dock is on the left

### ISSUE THREAD

**Issue by PKMpl** [home-sweet-gnome/dash-to-panel#1788]
Minor issue but it bugs me. Present on both my PC (Ryzen, Nvidia gtx 1650) and Laptop (Intel I5 intergrated graphics) after upgrading to Ubuntu 22.10 from 22.04. Only present when the dock is on the left/right side, not down.

![Screenshot from 2022-10-28 12-22-10](https://user-images.githubusercontent.com/3823196/198565397-44f87e75-86fa-427d-b21f-30f04aaf72bb.png)

**Comment by mihalycsaba** [comment]
yeah same here, my panel is wider and it looks even weirder. I'm on arch, fluent gtk theme.

![Screenshot from 2022-11-01 19-50-21](https://user-images.githubusercontent.com/50019470/199303422-af62d8c8-aa30-4a36-bec9-acd025aacf51.png)

**Comment by forteller** [comment]
I think this is the same issue I have, with Gnome 42:

![image](https://user-images.githubusercontent.com/343561/199516666-ff4e6012-6c68-44ab-9182-28b575de0060.png)

![image](https://user-images.githubusercontent.com/343561/199516931-dbc91f6e-9deb-4d80-8558-fae70ebd4b77.png)

**Comment by sashaoshurkov** [comment]
Fedora 37 (Gnome 43) + Wayland + Nvidia
![Screenshot from 2022-11-11 15-20-31](https://user-images.githubusercontent.com/1682848/201419229-b6e4645e-becd-4a6d-8eb3-e2103b5f5078.png)

**Comment by iitalics** [comment]
Same issue here when the panel is on the right side. Is anyone able to look into why this is occuring? It's making dash to panel very frustrating to use with the new quicksettings in gnome shell

![image](https://user-images.githubusercontent.com/1772927/204162272-b7ac6729-dff8-4883-a8c6-0a8e35e8d625.png)

**Comment by charlesg99** [comment]
Should now align properly with the master branch.

**Comment by mihalycsaba** [comment]
![image](https://user-images.githubusercontent.com/50019470/207735501-7e5a4c14-51c4-4cff-a62e-82fd5e5032f7.png)

It's still the same, I think it should align to the panel's edge not the middle and be at the bottom of the screen(edge of the screen)

**Comment by charlesg99** [comment]
Try the master branch.

On Arch:

![image](https://user-images.githubusercontent.com/33044886/207736037-b99f1565-b3b0-4f6b-8ad4-e9621db19671.png)


Ubuntu 22.04:

![image](https://user-images.githubusercontent.com/33044886/207736476-eaa1fa32-485d-46fa-b1ef-6155c5a9dd68.png)

**Comment by mihalycsaba** [comment]
oh yeah, I get it now, it's not on the extensions website yet, sorry
