### ISSUE TITLE
The FAQ links to an unmaintained extension

### ISSUE THREAD

**Issue by patrakov** [home-sweet-gnome/dash-to-panel#1791]
The bug is not in the extension itself, but in its README.md file, which contains the FAQ.

Namely:

> How do I move the notifications to somewhere other than the top center? Panel OSD

However, the Panel OSD extension (https://extensions.gnome.org/extension/708/panel-osd/) is no longer maintained. Maybe it's a better idea to link to https://extensions.gnome.org/extension/4651/notification-banner-reloaded/

**Comment by charlesg99** [comment]
Thanks, FAQ was updated!
