### ISSUE TITLE
maximized windows dont get keystrokes after unlocking the gnome session

### ISSUE THREAD

**Issue by mabod** [home-sweet-gnome/dash-to-panel#1794]
I am using gnome 43 on an up-to-date endeavouros system:

gnome-shell 1:43.1-1
gnome-shell-extension-dash-to-panel 52-1
mutter 43.1-1

When I unlock a gnome session with a maximized gnome-terminal window, the gnome-terminal is not echoing the keystrokes I am entering. I have to minimize/maximize the gnome-teriminal to see keystrokes again. 

Here is how I can reproduce this 100 % of the time.

1.     I am running gnome 43 with X11
2.     I have several windows open (e.g. evolution, firefox, etc.). but i believe that doesnt matter
3.     I open gnome-terminal and maximize that window and keep it in the foreground
4.     i type a few character to make sure that gnome-terminal is responsive
5.     I lock the screen with the keyboard shortcut Meta-L
6.     I unlock the screen
7.     I type something into the gnome-terminal window but it doesn’t show any character I am typing
8.     I minimize/maximize the gnome-terminal and now I see the characters I typed

The issue does not happen with wayland. And if I deactivate the dash-to-panel extension the issue is gone for X11.

**Comment by mabod** [comment]
The issue is related to mutter 43.1
With the previous version mutter 43.0-1 I do not have that issue.

**Comment by theraser** [comment]
Thanks for that hint, downgrading mutter from 43.0-1 to 43.1 also solves my related/same issue :+1:

When maximizing gnome-terminal it freezes for me, but I don't need to lock the screen for this to happen. The terminal windows are freezing every time I maximize them, but I can recover it by moving it to another screen using my keyboard shortcut. And the windows are accepting keystrokes, but it just won't update what you see.

**Comment by tekstryder** [comment]
Same behavior observed here following the same STR of the OP. I just happened to notice it with thunar.

Here's what I see in the journal when this occurs when locking/unlocking session:

```
Nov 09 14:02:31 gnome-shell[1275]: Could not create transient scope for PID 59058: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 59058 does not exist.
Nov 09 14:02:31 gnome-shell[1275]: Could not create transient scope for PID 59060: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 59060 does not exist.
Nov 09 14:02:31 gnome-shell[1275]: Could not create transient scope for PID 59061: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 59061 does not exist.
Nov 09 14:02:31 gnome-shell[1275]: Could not create transient scope for PID 59062: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 59062 does not exist.
Nov 09 14:02:31 gnome-shell[1275]: Could not create transient scope for PID 59063: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 59063 does not exist.
Nov 09 14:02:47 dbus-daemon[814]: [system] Activating via systemd: service name='org.freedesktop.home1' unit='dbus-org.freedesktop.home1.service' requested by ':1.1382' (uid=0 pid=59071 comm="gdm-session-worker [pam/gdm-password]")
Nov 09 14:02:47 dbus-daemon[814]: [system] Activation via systemd failed for unit 'dbus-org.freedesktop.home1.service': Unit dbus-org.freedesktop.home1.service not found.
Nov 09 14:02:47 gdm-password][59071]: pam_systemd_home(gdm-password:auth): systemd-homed is not available: Unit dbus-org.freedesktop.home1.service not found.
Nov 09 14:02:49 gdm-password][59071]: gkr-pam: unlocked login keyring
Nov 09 14:02:49 gnome-shell[1275]: Could not create transient scope for PID 59078: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 59078 does not exist.
Nov 09 14:02:49 gnome-shell[1275]: Could not create transient scope for PID 59081: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 59081 does not exist.
Nov 09 14:02:49 gnome-shell[1275]: Could not create transient scope for PID 59083: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 59083 does not exist.
Nov 09 14:02:49 gnome-shell[1275]: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x55b8fc57a4b0] is on because it needs an allocation.
Nov 09 14:02:49 gnome-shell[1275]: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x55b8fd651260] is on because it needs an allocation.
Nov 09 14:02:49 gnome-shell[1275]: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x55b9136ae010] is on because it needs an allocation.
Nov 09 14:02:49 gnome-shell[1275]: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x55b8fe43a430] is on because it needs an allocation.
Nov 09 14:02:49 gnome-shell[1275]: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x55b91173a4f0] is on because it needs an allocation.
Nov 09 14:02:49 gnome-shell[1275]: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x55b8fd650ed0] is on because it needs an allocation.
Nov 09 14:02:49 gnome-shell[1275]: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x55b8fdc06b30] is on because it needs an allocation.
Nov 09 14:02:49 gnome-shell[1275]: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x55b8fd650b40] is on because it needs an allocation.

```

**Comment by Don-Keehotee** [comment]
Just ran into this one as well on 2 different systems - 1 Intel, 1 nvidia - both X11.

I upgraded directly from gnome-shell/mutter 42.5 to 43.1 and never tried mutter 43.0.

The mutter changeset from 43.0 to 43.1 does have several commits that mention fullscreen:
https://gitlab.gnome.org/GNOME/mutter/-/compare/43.0...43.1

...however I'm not familiar enough to make sense of any correlation with this extension. Hopefully @charlesg99 can easily determine which change or possible regression in mutter has triggered this issue here.

For now I'm just toggling each frozen window or re-opening them as a workaround. I'd rather not run mutter at a version out of sync with gnome-shell as they are released in sync.

**Comment by charlesg99** [comment]
Hey guys, had a look at it and I can reproduce the same issue on vanilla gnome, so hopefully Mutter's folks can fix that. Haven't seen an issue about it yet on their repo, I'll try to open one in the next few days if no one beats me to it.

**Comment by Don-Keehotee** [comment]
> Hey guys, had a look at it and I can reproduce the same issue on vanilla gnome, so hopefully Mutter's folks can fix that. Haven't seen an issue about it yet on their repo, I'll try to open one in the next few days if no one beats me to it.

Awesome, thank you for the quick response and catching this. I was unable to reproduce on vanilla gnome with either of my systems and thus didn't have enough info to submit an issue on mutter. Looking forward to your submission. 

Thanks for all your continued support and great work on this most-important extension!

**Comment by tekstryder** [comment]
Per this gnome-shell issue:
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/6054

I built mutter 43.1 with 7e7a639c reverted:
https://gitlab.gnome.org/GNOME/mutter/-/commit/7e7a639cc5132cf3355e861235f325540fe56548

The issue is no longer reproducible. Bonus, some other funky stuff like text highlighting in firefox is working properly again too.

**Comment by tekstryder** [comment]
@mabod mutter 43.2 has been released which contains the fix for this issue.   

Could you please retest your STR and perhaps close this report?.

**Comment by mabod** [comment]
I tested it with mutter 43.2-1 on EndeavourOS.
It fixes this issue here for me. I will close it.
