### ISSUE TITLE
Super+Number shortcut when ungrouping applications.

### ISSUE THREAD

**Issue by Philipp91** [home-sweet-gnome/dash-to-panel#1798]
**Describe the idea or feature you'd like**

This extension offers the `Super+<n>` shortcut, which can be enabled in the "Action" tab with the option called "Use hotkeys to activate apps". Currently, `n` is always the index of the _application_ in the order they appear on the panel. When users also enable the "Ungroup applications" option (on the "Behavior" tab), then each _window_ and not each _application_ gets its own button on the panel. Yet the numbering scheme remains the same, so there are potentially multiple windows with the same number on them. (As a heavy Chrome user, I have four or more windows with the number 1, and no other windows.)

**My proposal is to make it configurable whether `n` is the application index or the window index.** I'm not sure whether this option should be put into the "Action" tab or into the sub-settings window of the "Ungroup applications" option, either works for me.

Side note for a workaround: With otherwise default options, it is currently not even possible to select the "other" window of an application that is already open, as it will instead minimize all windows of that application. That can be worked around by enabling the "Show window previews on hotkey" option, which allows pressing the application number hotkey multiple times to select the desired window within that application. It's multiple button presses now and not very intuitive, but works.

**Additional context**

Vaguely related: #1772

**Comment by Philipp91** [comment]
Actually when the ungrouped applications are intermingled, the assigned numbers become nonsensical, e.g.:

* Chrome first window => assigned 1
* Text editor => assigned 2
* Chrome second window => assigned 2  <== This should be 1 or 3, but 2 is weird.

**Comment by Philipp91** [comment]
With the master branch, the numbers are assigned correctly and the right item is highlighted (on the dash itself) for any number I press. But when an app has multiple windows, pressing the number of any of those always opens the _first_ window of that app. In the example above, it would now show Chrome=1, TextEditor=2, Chrome=3, but pressing 3 would open window 1 (yet highlight both 3 _and_ 1 on the dash).

**Comment by charlesg99** [comment]
This is what I'm seeing with the master branch, can you share your settings?


https://user-images.githubusercontent.com/33044886/202295843-a482a39b-368b-4293-aa56-e9b797a586e1.mp4

**Comment by Philipp91** [comment]
[gnome_dash_to_panel.txt](https://github.com/home-sweet-gnome/dash-to-panel/files/10025849/gnome_dash_to_panel.txt)

I can't record a video due to this being a corporate machine.

**Comment by charlesg99** [comment]
Your settings works fine for me after unchecking "Show window previews on hotkey". Did you restart gnome-shell following the master branch install?

https://user-images.githubusercontent.com/33044886/202299312-3007dac5-492c-4d75-bddf-52f8a1b6225a.mp4

**Comment by Philipp91** [comment]
Ah, disabling that option fixed indeed. Thank you!

(I had listed that option in my opening post already, and I had thought to disable it after updating to the master branch and after restarting gnome-shell, _but_ I accidentally disabled "Show window previews on _hover_" instead. :facepalm:)
