### ISSUE TITLE
Taskbar get's reloaded/weird animation sometimes

### ISSUE THREAD

**Issue by francoism90** [home-sweet-gnome/dash-to-panel#1800]
**Things to do first**
- Confirm that the problem persists when Dash-to-Panel is the only enabled extension. To do so, disable every other extension, then restart gnome-shell by running the `r` command from the prompt that appears when pressing Alt+F2 on an X.org session, or by logging out/in on a Wayland session.
- Look for Dash-to-Panel errors in your log. To do so, run the `journalctl /usr/bin/gnome-shell -f -o cat &` command and reproduce the problem.
- Search existing opened and closed issues to see if the problem has already been reported.

**Describe the bug**
The taskbar shows a weird animation sometimes, it seems to reload.

**Linux distribution and version**
- Arch Linux
- Fedora 37

**GNOME Shell version**
GNOME Shell 43.1

**Dash-to-Panel version**
52

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
It's a bit difficult to capture this, it happens for about a second. I'll try to use capture software.

This is the debug information:
```bash
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
Timelines with detached actors are not supported. <unnamed>[<Gjs_ui_iconGrid_BaseIcon>:0x556b05d70140] in animation of duration 200ms but not on stage.
Timelines with detached actors are not supported. <unnamed>[<Gjs_ui_search_ListSearchResult>:0x556b060ddc80] in animation of duration 200ms but not on stage.
Timelines with detached actors are not supported. <unnamed>[<Gjs_ui_search_ListSearchResult>:0x556b03c92b90] in animation of duration 200ms but not on stage.
Timelines with detached actors are not supported. <unnamed>[<Gjs_ui_search_ListSearchResult>:0x556b036d4a80] in animation of duration 200ms but not on stage.
Error in size change accounting.
Error in size change accounting.
```

**Comment by charlesg99** [comment]
Hi, I've never seen that... Any clue/pattern that could help reproducing the issue?
