### ISSUE TITLE
Pinned applications are always running .desktop file in /usr/share/applications and not ~/.local/share/applications

### ISSUE THREAD

**Issue by MusaSSH** [home-sweet-gnome/dash-to-panel#1809]
**Describe the bug**
I have an application that needs some arguments to be added to .desktop file in order to make it work better. The problem is if I make changes to .desktop file in /usr/share/applications it will be overwritten by package manager whenever the application gets update. For that reason, I copy the .desktop file to ~/.local/share/applications and make my changes persistent. This method worked when using GNOME's built-in dock or Dash to Dock extensions, but it is not working when I use Dash to Panel. Dash to Panel keeps running the .desktop file in /usr/share/applications and not ~/.local/share/applications.

If I run the application from the GNOME search, it runs the .desktop file in ~/.local/share/applications even when Dash to Panel extension enabled, so this problem exists for applications pinned to panel.

**Linux distribution and version**
Fedora Workstation 37

**GNOME Shell version**
GNOME Shell 43.2

**Dash-to-Panel version**
52

**Where was Dash-to-Panel installed from?**
GNOME extensions website

**Screenshots / Video captures**

**Additional Info**

**Comment by charlesg99** [comment]
I think it uses the local .desktop file, just not the right action in that file (we don't explicitly select the file, we use what's provided by gnome). Please install the master branch, should be fixed. 

Otherwise, in the local .desktop file, try modifying the "new-window" action as well as the desktop entry, should work.

**Comment by charlesg99** [comment]
Should now work correctly
