### ISSUE TITLE
How can I show the dash in ⌘

### ISSUE THREAD

**Issue by matheustecchio** [home-sweet-gnome/dash-to-panel#1811]
How can I show this dash when I click ⌘(super)?

![image](https://user-images.githubusercontent.com/52295230/208196709-7cee549a-9706-4e05-9435-992f81c74d31.png)

With the extension run, don't show anything.

![image](https://user-images.githubusercontent.com/52295230/208196635-e06b3bb9-74dc-4ece-a09e-c525764404ab.png)

**Comment by charlesg99** [comment]
![image](https://user-images.githubusercontent.com/33044886/208200379-bf5615ef-e769-41dd-801a-2a96a3f735d3.png)
