### ISSUE TITLE
Ability to remove custom colors in addition to customize colors.

### ISSUE THREAD

**Issue by shuriken1812** [home-sweet-gnome/dash-to-panel#1818]
**Describe the idea or feature you'd like**

Example in the custom color menu I have two colors, I can customize them or add new ones but I can't remove them.
![Screenshot from 2023-01-04 02-21-15](https://user-images.githubusercontent.com/40650341/210439415-5df5d161-7657-4435-af2d-bb60e986d495.png)

**Is your feature request related to a problem? Please describe.**
I just wish there is a way to remove custom colors, maybe a simple x button or a delete button where we have the `customize` option

**Additional context**
![Screenshot from 2023-01-04 02-23-44](https://user-images.githubusercontent.com/40650341/210439750-d814edbe-abd3-4c42-85a1-768814890566.png)

Here we can see there is a customize option, will be great to have a delete option too.

**Comment by charlesg99** [comment]
This would be a [gtk](https://gitlab.gnome.org/GNOME/gtk) feature request
