### ISSUE TITLE
Intellihide overlaps search box in overview

### ISSUE THREAD

**Issue by adriankwiat** [home-sweet-gnome/dash-to-panel#1821]
**Describe the bug**
With Intellihide enabled, panel overlaps search box in overview

**Linux distribution and version**
Fedora 37

**GNOME Shell version**
43.2

**Dash-to-Panel version**
52

**Where was Dash-to-Panel installed from?**
GNOME extensions website

**Screenshots / Video captures**
![image](https://user-images.githubusercontent.com/36125672/211213957-ea9d1be0-8304-4b40-8e97-124b03621b55.png)

**Comment by charlesg99** [comment]
Thanks for reporting this, a fix was added to the master branch, can you try it?

**Comment by nater1983** [comment]
![image](https://user-images.githubusercontent.com/46272571/220802417-feda8e90-ced0-43c3-a0bc-4f6814d10b90.png)

**Comment by nater1983** [comment]
I have installed dash-to-panel from git as of today and I am still getting the same as the OP

Linux distribution and version
Slackware 15 Current

GNOME Shell version
43.2

Dash-to-Panel version
52

Where was Dash-to-Panel installed from?
extension git
