### ISSUE TITLE
Icons from executables launched from terminal blink every 30 seconds

### ISSUE THREAD

**Issue by DragonAxe** [home-sweet-gnome/dash-to-panel#1824]
When I launch executables from a terminal which don't have a .desktop file, their icons "blink" every 30 seconds as if they are being refreshed which is very distracting. See screen capture below:

[Screencast from 2023-01-23 09-19-31.webm](https://user-images.githubusercontent.com/12703200/214094480-fa4371b3-3208-4f0b-9642-91e0b623ef50.webm)

Distro: 5.15.85-1-MANJARO
Gnome: 43.2 x11
Dash-to-panel version: 52

**Comment by charlesg99** [comment]
Can't reproduce with the terminal apps that I use and that have no .desktop files. Which app is that?

**Comment by DragonAxe** [comment]
The app's name is Godot, an open source game engine.

I actually disabled dash-to-panel and I'm still getting this behavior in the Activities view, so it must not be caused by this dash-to-panel. I'll open an issue somewhere upstream, though I'm not sure where yet.

Thanks for trying to reproduce!
