### ISSUE TITLE
Applications not appearing in panel when they're supposed to

### ISSUE THREAD

**Issue by intra420** [home-sweet-gnome/dash-to-panel#1825]
**Describe the bug**
I have applications open in the same workspace that should appear on dash to panel but dont (imhex and gnome calculator in picture, have been others before such a ghidra, the libreoffices, gnome text, kwrite, gnome files etc.).
the icons still do not appear in the panel even when they are the active application, and it is impossible to use the pannel to switch to those applications.

this consistently happens when repeatedly changing work spaces using gnome's 3 finger swipe on wayland.
some of the application icons will also get bugged
I am able to temporary get around this issue by dragging every application to a new workspace

**Linux distribution and version**
Fedora 37

**GNOME Shell version**
gnome shell 43.2

**Dash-to-Panel version**
52

**Where was Dash-to-Panel installed from?**
gnome extention manager from flathub

**Screenshots / Video captures**
![image](https://user-images.githubusercontent.com/107241490/216168215-ecd0d5c1-0bff-44db-8691-638bc15f9c05.png)

`journalctl /usr/bin/gnome-shell -f -o cat` & output: 
(however I do not think the bug I'm describing shows up in the error logs)
``` Object St.Button (0x56389b37ec70), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Object St.Button (0x56389b37ec70), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Object .Gjs_ui_windowPreview_WindowPreview (0x56389d64cb40), has been already disposed — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
JS ERROR: TypeError: this.window_container is null
hideOverlay@resource:///org/gnome/shell/ui/windowPreview.js:373:9
vfunc_leave_event/this._idleHideOverlayId<@resource:///org/gnome/shell/ui/windowPreview.js:571:26

meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
Window manager warning: last_user_time (132398400) is greater than comparison timestamp (132398397).  This most likely represents a buggy client sending inaccurate timestamps in messages such as _NET_ACTIVE_WINDOW.  Trying to work around...
Window manager warning: W1450 appears to be one of the offending windows with a timestamp of 132398400.  Working around...
Received error from D-Bus search provider org.gnome.Photos.desktop during GetResultMetas: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/org/gnome/Photos/SearchProvider”
Received error from D-Bus search provider org.gnome.Photos.desktop during GetResultMetas: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/org/gnome/Photos/SearchProvider”
Received error from D-Bus search provider org.gnome.Photos.desktop during GetResultMetas: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/org/gnome/Photos/SearchProvider”
```

**Comment by charlesg99** [comment]
Does it only happen when using touch? Can you reproduce the issue with your mouse only?

**Comment by charlesg99** [comment]
We can reopen if needed, but I can't reproduce and never seen/heard of this issue before.
