### ISSUE TITLE
Running indicator dissapears

### ISSUE THREAD

**Issue by Alexandre-Fernandez** [home-sweet-gnome/dash-to-panel#1827]
**Things to do first**
> - Confirm that the problem persists when Dash-to-Panel is the only enabled extension. To do so, disable every other extension, then restart gnome-shell by running the `r` command from the prompt that appears when pressing Alt+F2 on an X.org session, or by logging out/in on a Wayland session.

Done
> - Look for Dash-to-Panel errors in your log. To do so, run the `journalctl /usr/bin/gnome-shell -f -o cat &` command and reproduce the problem.

This is what I get :
```
[3] 121967
DING: DBus interface for Nautilus (org.gnome.Nautilus.FileOperations2) is now available.                                                                                                                                                      
DING: DBus interface for Gvfs daemon (org.gtk.vfs.Metadata) is now available.
DING: DBus interface for Nautilus (org.freedesktop.FileManager1) is now available.
DING: DBus interface for Nautilus-Sushi (org.gnome.NautilusPreviewer) is now available.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x556f83bfe8c0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x556f84946ac0] is on because it needs an allocation.
NOTE: Not using GLX TFP!
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x600004
activated: Settings
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x600004
```
> - Search existing opened and closed issues to see if the problem has already been reported.

Done

**Describe the bug**
The running indicator disappears on random actions. It disappears if the app sends a notification (for example I receive a message on slack, its running indicator will disappear), when I switch tab or click previous/next in a browser (firefox/chromium), and probably more...
This is very annoying because if the running indicator disappears and the application is not currently active, I'll just think it's not even launched (it will be highlight-less and indicator-less).

**Linux distribution and version**
Fedora 37

**GNOME Shell version**
Gnome 43, X11

**Dash-to-Panel version**
v52

**Where was Dash-to-Panel installed from?**
The GNOME extensions website.

**Screenshots / Video captures**
[This video capture](https://webm.red/view/NCoU.webm) shows how the running indicator dissapears when clicking previous on LibreWolf (firefox fork), it reappears when clicking back on the dash to panel icon.

**Comment by charlesg99** [comment]
Some fixes for this kind of issue were added to the master branch and aren't released yet, please try it out.

**Comment by Alexandre-Fernandez** [comment]
- `git clone https://github.com/home-sweet-gnome/dash-to-panel.git`
- `cd dash-to-panel`
- `sudo make install`
```
rm -fR ./_build
mkdir -p _build
cp extension.js stylesheet.css metadata.json COPYING README.md appIcons.js panel.js panelManager.js proximity.js intellihide.js progress.js panelPositions.js panelSettings.js panelStyle.js overview.js taskbar.js transparency.js windowPreview.js prefs.js utils.js Settings.ui desktopIconsIntegration.js _build
cp: cannot stat 'Settings.ui': No such file or directory
make: *** [Makefile:85: _build] Error 1
```
This is what I got when I tried to install `master`.
I did uninstall the extension (with gnome-extensions-cli) before doing all this.

**Comment by charlesg99** [comment]
Thanks for pointing that out, we just merged a PR that changes the settings. Please pull/install again, it should now work:

`git pull origin master && make install`

**Comment by Alexandre-Fernandez** [comment]
> Thanks for pointing that out, we just merged a PR that changes the settings. Please pull/install again, it should now work:
> 
> `git pull origin master && make install`

How to enable it with `dconf` ?

**Comment by charlesg99** [comment]
Not sure, do you see an error here https://extensions.gnome.org/local/? Do you have the gnome Extensions app installed?
