### ISSUE TITLE
When positioned at the bottom, on smaller screen resolutions, dash to panel can't handle GNOME 43's wifi wireless networks quick settings submenu

### ISSUE THREAD

**Issue by nekohayo** [home-sweet-gnome/dash-to-panel#1829]
**Describe the bug**
1. Set your screen resolution to match that of a non-HiDPI 13" laptop, such as the ThinkPad X220T's 1366x768 resolution (or 1280x720)
2. Set dash-to-panel to the bottom of the screen
3. Open the system menu to reveal the quick settings toggle widgets
4. Click the ">" arrow in the wifi quick setting thing to reveal the list of wifi networks nearby

Result: it expands upwards and  hides itself within a fraction of a second.

This does not happen at higher screen resolutions (or by setting the font scaling to 50% instead of 90 or 100%), nor if you set dash-to-panel to be positioned at the top of the screen.  `journalctl /usr/bin/gnome-shell -f -o cat` does not output anything while this is happening.

**Linux distribution and version**
Fedora 37

**GNOME Shell version**
43.2, running in Xorg/X11 mode

**Dash-to-Panel version**
52

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Comment by charlesg99** [comment]
Please see #1779. Should be fixed on the master branch (please install it to help us test the new settings dialog :), but it isn't released yet.

**Comment by nekohayo** [comment]
Damned, I searched for existing tickets, and I hate that github's search is such rubbish that I couldn't find the two existing ones!
