### ISSUE TITLE
Isolate Workspaces + Ungroup Applications results in lost highlight when switching workspaces

### ISSUE THREAD

**Issue by miro011** [home-sweet-gnome/dash-to-panel#1830]
**Describe the bug**
When "Isolate Workspaces" and "Ungroup Applications" are both enabled, and you switch workspaces back and forth, the active application is no longer highlighted in the taskbar.

I believe this may have something to do directly with the "Ungroup Applications" option, as this problem only happens with that option enabled.

**Linux distribution and version**
Fedora 37, GNOME 43.0, Wayland (live-boot, everything fully stock test)
Fedora 37, GNOME 43.3, X11 (my OS)

**Dash-to-Panel version**
52

**Where was Dash-to-Panel installed from?**
The GNOME extensions website.

**Screenshots / Video captures**
[Screencast from 2023-02-09 05-33-45.webm](https://user-images.githubusercontent.com/31739501/217789431-3306d14e-d9c8-45fb-957e-6bf9cbc34929.webm)

**Comment by charlesg99** [comment]
Hi Miroslav, I think this is a duplicate issue, see #1827. Install the latest master branch untill we release a new version. Thanks!

**Comment by miro011** [comment]
> Hi Miroslav, I think this is a duplicate issue, see #1827. Install the latest master branch untill we release a new version. Thanks!

I don't think so. Mine is specific to the those two options working together.

The other issue you provided, I've encountered as well and it has to do with GNOME animations being off.
The trick is, if you have GNOME animations disabled, in Dash to Panel you want to disable "Animate Switching Applications" and "Animate Launching New Windows" in the Fine-Tune section.

The issue I provided is not affected by whether GNOME animations are on or off.

**Comment by charlesg99** [comment]
You're right, this was another issue. Thanks, should now be fixed on the master branch!

**Comment by miro011** [comment]
Ok thank you very much! I'm gonna have to figure out how GNOME extensions work so I can contribute code myself in the future.

**Comment by miro011** [comment]
fixed
