### ISSUE TITLE
feature-request: Add GNOME 44 support

### ISSUE THREAD

**Issue by git-Hmmm** [home-sweet-gnome/dash-to-panel#1831]
### Describe the idea or feature you'd like
It would be beneficial to have this extension be functional in gnome 44 as the beta phase has already begun.

### Is your feature request related to a problem? Please describe.
nope

### Additional context
nope

**Comment by philippun1** [comment]
Created a PR for gnome 44 support:  #1833

**Comment by git-Hmmm** [comment]
The 44 version is available and seems to work perfectly for me.
