### ISSUE TITLE
"Tray Font Size" is Not respected after locking/unlocking screen.

### ISSUE THREAD

**Issue by CyborgDragonFire** [home-sweet-gnome/dash-to-panel#1834]
**App Versions**
Latest up-to-date Manjaro Linux
GNOME Shell 43.2 - Wayland
AMD GPU - Latest Stable Mesa Drivers 22.3.5

Dash-to-Panel version 52
Dash-to-Panel was preinstalled with Manjaro Linux

Issue confirmed with No other extensions installed!

**Describe the bug**
The "Fine-Tune" > "Tray Font Size" setting is Not respected after locking/unlocking screen.

I've had this issue since about GNOME Shell 40, on boot the setting is respected, font is the correct size.
But after locking then unlocking the computer, the font reverts back to the default size.

I have to encourage Dash-to-Panel to remember the correct setting, by opening the settings menu and moving the "Tray Font Size" option up one point, then moving it back again. (20px > 21px > 20px)

Doing this reminds Dash-to-Panel about the setting, and then Dash-to-Panel displays the Tray Font at the correct size ... until I lock my PC's screen again.
Then I have to do this all over again.

**Comment by charlesg99** [comment]
I can't reproduce this on gnome-shell 42, 45 and 46
