### ISSUE TITLE
icon from .desktop?

### ISSUE THREAD

**Issue by Thatoo** [home-sweet-gnome/dash-to-panel#1839]
Hello,

I launch some application several time with the help of --profile=xxx in .desktop files.
I can, in these .desktop file, set a specific icon for each profile which is very useful to distinguish them in the app launcher.
Indeed, in the screen that display all application, it lists all the different launcher with their different icons.
I can even set each of them as favorite and they remain in the dash-to-panel.
However, once I launch the app, they all get joined into one icon, the original icon and that's confusing.
Would it be possible they keep their own icon?

**Comment by HubKing** [comment]
This is similar to my question that I posted weeks ago. It seems that DtP is getting application window information from Gnome, and Gnome does not distinguish two instances of the same application launched in different parameters. You can see this in the application overview (Super + A, by default): look at the dot.

**Comment by Thatoo** [comment]
So the enhancement request should be done to Gnome then.
Do you know where we could ask for it?

**Comment by HubKing** [comment]
> So the enhancement request should be done to Gnome then. Do you know where we could ask for it?

If it is a bug report, GitLab gnome-shell. If it is a feature request, discourse.gnome.org.
