### ISSUE TITLE
v53 - small visual bug, narrow indicators (dashes, dots, squares)

### ISSUE THREAD

**Issue by charlesg99** [home-sweet-gnome/dash-to-panel#1843]
### Discussed in https://github.com/home-sweet-gnome/dash-to-panel/discussions/1841

<div type='discussions-op-text'>

<sup>Originally posted by **danix1234** March  5, 2023</sup>
running indicators style "dots", "square" and "dashes" don't show when opening favorites apps
![Screenshot from 2023-03-05 17-43-08](https://user-images.githubusercontent.com/116650308/222973844-9e7d9e5f-3f4d-4cd8-abac-10aa766d4421.png)
as you can see in the image, gnome-terminal has no circle to indicate a window is open.</div>

**Comment by charlesg99** [comment]
Fixed on master, will re-release soon!

**Comment by prigal** [comment]
Here, it's only on web apps where indicators are missing, it's ok on others.
![image](https://user-images.githubusercontent.com/895267/223052045-00d19e2a-0491-476a-8ede-5d0b3761558e.png)

**Comment by dln949** [comment]
> Here, it's only on web apps where indicators are missing, it's ok on others. ![image](https://user-images.githubusercontent.com/895267/223052045-00d19e2a-0491-476a-8ede-5d0b3761558e.png)

In case it matters:  Sadly not true in my case, the indicators stopped showing on everything, web app or regular application.

**Comment by Betzalel-Maor** [comment]
I got the same bug here. It just came so sudden

**Comment by davidmartos96** [comment]
@charlesg99 After the update I noticed a small visual issue, not sure if it is related. I'm using the Metro indicator style, but since the new version it doesn't take the full width of the icon

![image](https://user-images.githubusercontent.com/22084723/223383348-2e0d7436-a918-42fc-a940-c64f3131c4b0.png)

**Comment by Betzalel-Maor** [comment]
> @charlesg99 After the update I noticed a small visual issue, not sure if it is related. I'm using the Metro indicator style, but since the new version it doesn't take the full width of the icon
> 
> ![image](https://user-images.githubusercontent.com/22084723/223383348-2e0d7436-a918-42fc-a940-c64f3131c4b0.png)

It might be part of the issue. This is what it looks like for me
![Screenshot from 2023-03-07-131438(KSNIP)](https://user-images.githubusercontent.com/120188538/223407078-dec3e7fc-9664-4626-b478-7628495b1904.png)

**Comment by charlesg99** [comment]
@davidmartos96 Thanks for letting me know, this was a different issue. Just to be sure, you are using scaling right? Should be fixed on master, will release soon.

**Comment by davidmartos96** [comment]
> @davidmartos96 Thanks for letting me know, this was a different issue. Just to be sure, you are using scaling right? Should be fixed on master, will release soon.

Yes, I am. Glad to hear that!

**Comment by SagnikSRHUSE** [comment]
I'm also noticing an issue where the indicator doesn't change for focused/unfocused apps. I'm using dots for unfocused apps, and dashes for focused ones, it seems to stay on dots for both focused and unfocused applications.

**Comment by Betzalel-Maor** [comment]
@charlesg99 the bug is now fixed with the update. Thank you!
