### ISSUE TITLE
It seems something has changed in the way Dash to Panel v53 treats .desktop files

### ISSUE THREAD

**Issue by user1-github** [home-sweet-gnome/dash-to-panel#1845]
I'm using Vivaldi web browser that has 2 desktop actions in it's .desktop file: "New Window" and "New Private Window".
Previously, with Dash to Panel v52, if I directly clicked the Vivaldi icon, it launched with the "New Window" desktop action. Now in v53 if I directly click Vivaldi icon, it doesn't launch with the desktop action anymore. I can confirm this by looking in the browser about page: Previously the Vivaldi executable was displayed as "vivaldi --new-window", but now it is displayed as "vivaldi".
Now, I can still launch it with the "New Window" desktop action by right clicking the Vivaldi icon and selecting New Window, but still, I think v52 had the correct behavior.

**Comment by user1-github** [comment]
@charlesg99 Actually yes, if I launch it from the overview, it also doesn't launch with "New Window".

This matters to me because I've added some of my own flags to the Vivaldi .desktop file that only work if they're added to the "New Window" or "New Private Window" desktop action sections.

For me it's not a huge problem launching Vivaldi with right click --> New Window every time, but for reference, if I directly click Vivaldi icon on any other desktop environment or on Windows, it launches as "vivaldi --new-window".

So what you mean is that not respecting desktop actions by default is a Gnome shell behavior?

**Comment by charlesg99** [comment]
> So what you mean is that not respecting desktop actions by default is a Gnome shell behavior?

I guess so, I dug a bit in gnome-shell and the new-window action is only invoked when the app is already running. Not sure what to do with this, but I'm leaning towards respecting the default gnome-shell behavior. Maybe you could add the `--new-window` switch (as well as your customs ones) in the `Exec=` line of the `[Desktop Entry]` of the .desktop file?

**Comment by user1-github** [comment]
> Maybe you could add the `--new-window` switch (as well as your customs ones) in the `Exec=` line of the `[Desktop Entry]` section of the .desktop file?

Yeah, I think I'll try doing that. Maybe this way my custom flags will also work under Desktop Entry section (previously they didn't).

**Comment by charlesg99** [comment]
We'll keep the default gnome behavior for now.
