### ISSUE TITLE
Dash to panel does not show after reboot

### ISSUE THREAD

**Issue by Qweting** [home-sweet-gnome/dash-to-panel#1846]
My dash to panel does not show after rebooting and i need to manually activate it, by 'turning off' and 'turning on' on extension manager. I'm on ubuntu 22.04 and I'm using gnome version 42.5. This happened yesterday after i updated the dash to panel. I tried downgrading to version 52  but it keeps upgrading it to 53. I have everything inside of my top panel and the top panel doesn't show up after rebooting. Any idea what is causing this? 

Also this extension is amazing, thank you & everyone involved for the amazing work.    

When i reboot it looks like (first image) this (I have "panel Intellihide" to show you what it looks like). After turning all extensions off and then on inside of extension manager it looks like the second picture. The second image includes the setting that i use as well. (I have "panel Intellihide" disabled as well)  

![image](https://user-images.githubusercontent.com/89273171/223138942-5aaca892-0811-4bbc-9edc-84132fad6407.png)

![image](https://user-images.githubusercontent.com/89273171/223141370-c1c7613c-dce1-4249-845e-4730c2bd3e5d.png)

**Comment by charlesg99** [comment]
Looks like a conflict with something else, I can't reproduce that on a fresh Ubuntu 22.04 install. Can you see errors in your logs? Also to test without other extensions, disable everything but dash to panel, then reboot, then test by enabling you other extensions one at a time (reboot/log out after enabling each one) to see if there is a conflict. Thanks!

**Comment by Qweting** [comment]
You are 100% correct, it was indeed another extension that was causing it. "Shell Configurator" seems to be the cause, I'll see if i can fix it. I didn't think about disabling extensions since I've had all these installed at the same time and never had an issue. I might have changed something there without being aware of it. 
Thanks the help!

**Comment by charlesg99** [comment]
Great!
