### ISSUE TITLE
menu button issue on pop cosmic

### ISSUE THREAD

**Issue by MarkoJokinen** [home-sweet-gnome/dash-to-panel#1847]
im using pop os with pop cosmic on everything works exellent except the menu button. if i take all cosmic dock options it starts kind of work it togles workspaces and applications, but that way i loose half of pop cosmic apps. and there is that section on settings to enable Top Bar -> Show App Menu must be enabled in tweak tools, but i dont have that kind of menu. i really hope this could come to work on POP cosmic since i love this now and Cosmic DE is still so far away

**Comment by cotizcesar** [comment]
Same problem here.

**Comment by Dejv311** [comment]
Also experiencing this problem

**Comment by Dejv311** [comment]
Solved here:

https://github.com/home-sweet-gnome/dash-to-panel/issues/1551#issuecomment-1112606220
