### ISSUE TITLE
Smart masking problem since version 54

### ISSUE THREAD

**Issue by dom21121** [home-sweet-gnome/dash-to-panel#1850]
Good morning,

Under UBUNTU 22.04.2 and GNOME 42.5, "dash to panel (v54)" no longer works as before...
Under wayland, smart hiding no longer works, the panel is always hidden as soon as there is no window or as soon as the window no longer has the focus...
No problem under xorg.

Thank you to consider.

**Comment by dom21121** [comment]
Sorry,
I went a little fast, I tried with older versions, and it does the same thing...
I don't see where the problem could be...

**Comment by dom21121** [comment]
I've found. the problem comes from the DING extension integrated into UBUNTU, when I deactivate it, Dash To Panel works correctly again, but there is still a problem when DING is on...

**Comment by ygurin** [comment]
Interestingly, this last update (version 54), spotted Dynamic background opacity stopped working. When "background opacity" is enabled my panel is not transparent even with no windows on the screen.

On Manjaro Gnome 43.3 Wayland

**Comment by charlesg99** [comment]
Yes, this is a long standing issue with DING on wayland, see #946 and https://gitlab.com/rastersoft/desktop-icons-ng/-/issues/55.

We normally detected its window with the skip_taskbar flag, but new Adwaita dialog windows have this flag set to true while being visible on screen, so they couldn't be detected for proximity tasks. I added a DING specific fix to the master branch, should resolve the issue.

**Comment by ulipo** [comment]
I can confirm that the fix/workaround in [294b223](https://github.com/home-sweet-gnome/dash-to-panel/commit/294b223fe2659d85794cb647d5249676bc48f9a5) is working nicely also with [GTK4 DING](https://extensions.gnome.org/extension/5263/gtk4-desktop-icons-ng-ding/).

**Comment by charlesg99** [comment]
Fix is now on e.g.o.

**Comment by dom21121** [comment]
everything works as before!
THANKS
