### ISSUE TITLE
Maximized windows appear in the wrong location on unlock

### ISSUE THREAD

**Issue by road2react** [home-sweet-gnome/dash-to-panel#1853]
**Describe the bug**
Maximized windows appear in the wrong location on unlock

To reproduce:

1. Open Google Chrome with ozone platform wayland
2. Maximize the window
3. Lock screen
4. Unlock screen

The window will appear as if the top panel was present. There would be a gap at the top unoccupied by the maximized window and the bottom part of the window will be obscured by the panel at the bottom.

**Linux distribution and version**
Arch Linux

**GNOME Shell version**
GNOME Shell 43.3

**Dash-to-Panel version**
54

**Where was Dash-to-Panel installed from?**
extensions website

**Comment by charlesg99** [comment]
Yes it's a long standing mutter issue, see #1600
