### ISSUE TITLE
On Gnome 44 beta changed icon theme not used during startup

### ISSUE THREAD

**Issue by Bleistein** [home-sweet-gnome/dash-to-panel#1857]
We are on Fedora 38 beta with Gnome 44 beta. We have the Yaru icon theme installed. Dash to Panel is NOT using this icon theme after booting but the GNOME 44 beta default one.

Launched applications like Files 44.rc are displayed properly with the Yaru icon theme...

Workaround is switching to a different icon theme and back with GNOME Tweaks. Then Dash to Panel is displaying the correct icons...

**Comment by charlesg99** [comment]
Can't reproduce and icons aren't controlled by dtp.
