### ISSUE TITLE
Firefox Nightly has no icon on the taskbar.

### ISSUE THREAD

**Issue by p0c0k** [home-sweet-gnome/dash-to-panel#1865]
I downloaded Firefox Nightly from Mozilla's site then I made a .Desktop file and pinned it to the taskbar but when I click on it crates an other icon next to it without an icon. Same thing if I just run it from my applications menu..

Nobara 37
GNOME Shell 43.2
Dash to Panel version 9999 and it's pre installed with Nobara official iso

![kép](https://user-images.githubusercontent.com/88557395/226728766-e541a9b9-e615-41e9-a9fb-ccf50d7e67b9.png)

**Comment by p0c0k** [comment]
If i do the same with regular Firefox it works fine. I can chance the ico and everything. I also tried installing it with Firefox Automatic Install For Linux and again the icon was not showing up..

**Comment by charlesg99** [comment]
Refer to #1247, see [StartupWMClass](https://github.com/home-sweet-gnome/dash-to-panel/issues?q=is%3Aissue+StartupWMClass)

**Comment by p0c0k** [comment]
Thanks I used "StartupWMClass=firefox-nightly" and it works fine now :)
