### ISSUE TITLE
Running applications icon shows multiple windows icon even if only one is open

### ISSUE THREAD

**Issue by pudup** [home-sweet-gnome/dash-to-panel#1866]
**Describe the bug**
Multiple window icon persists after windows are closed and only one is left. It fixes itself if the application is minimised or if I switch to another open window of another application.

**How to reproduce**
Open any app, eg. Firefox. Open a second window of Firefox and then close it and it'll look like the screenshot below.

**Linux distribution and version**
Ubuntu 22.04

**GNOME Shell version**
42.5

**Dash-to-Panel version**
55

**Where was Dash-to-Panel installed from?**
Gnome-extensions manager/website

**Screenshots / Video captures**
![Screenshot from 2023-03-22 11-15-55](https://user-images.githubusercontent.com/35901162/226813401-c8d2aad7-44ca-47a0-b155-3ac0071c3ea5.png)
Only one instance of firefox is open in this screenshot

**Additional Info**
Happens in Wayland and Xorg

**Comment by charlesg99** [comment]
Thanks for reporting this, should now be fixed on the master branch!

**Comment by nikfilippas** [comment]
Thanks for fixing this Charles - I was about to submit this as an issue myself.
Are you planning on tagging a new release soon for those of us who have installed it via extensions.gnome?

**Comment by pudup** [comment]
@nikfilippas You can use another running indicator while you wait for this to be released. Anything other than Metro works fine.
