### ISSUE TITLE
Don't set Wi-Fi as the default page when opening Gnome Settings

### ISSUE THREAD

**Issue by HubKing** [home-sweet-gnome/dash-to-panel#1869]
**Describe the bug**
You can right-click DtP to open Gnome Settings. It seems that DtP defaults to Wi-Fi no matter what, whereas when Gnome Settings is launched from application list, it starts with last-used page. I am using a desktop, so Wi-Fi does not even exist. It should not set Wi-Fi as the default page, and let G.S. restore last-used page.

**Linux distribution and version**
EOS

**GNOME Shell version**
43.3

**Dash-to-Panel version**
55

**Where was Dash-to-Panel installed from?**
The GNOME extensions website.

**Screenshots / Video captures**
When opened by DtP
![image](https://user-images.githubusercontent.com/10900489/227573484-fabdd974-f9de-4cb7-a773-0a5b7595379d.png)

When opened by from application list. Note that the first item is "Network", not "Wi-Fi".
![image](https://user-images.githubusercontent.com/10900489/227574244-38ba1c43-c1ca-4a79-bf1c-a3df3f2f61fa.png)

**Additional Info**

When you open G.S. from DtP, it shows non-existing Wi-Fi. If you close G.S. in this state, next time, even if you open G.S. in application list, not from DtP, G.S. shows the same Wi-Fi page. I was confused and thought that this is G.S.'s bug, but I realised that this is only because G.S. was trying to restore the last-used page, which was erroneously set to Wi-Fi by DtP.

**Comment by charlesg99** [comment]
Should now be fixed on master
