### ISSUE TITLE
Can't override indicators with theme

### ISSUE THREAD

**Issue by zagortenay333** [home-sweet-gnome/dash-to-panel#187]
![screenshot from 2017-06-12 13-29-15](https://user-images.githubusercontent.com/11144630/27032170-c7dc0438-4f73-11e7-8cc9-36459f2714da.png)

I see you have a function for checking whether a border image is being used, but it's not working.

Stylesheet:  
https://github.com/zagortenay333/ciliora-tertia-shell/blob/master/Ciliora-Tertia/gnome-shell/gnome-shell.css#L5991

Is it a bug or am I not properly overriding?

**Comment by jderose9** [comment]
Seems to be a bug. That code was specifically to work with your theme.

**Comment by zagortenay333** [comment]
It's probably 'cause you're checking on `this.icon` instead of `this.actor`; that's the one with the `app-well-app` css class.
