### ISSUE TITLE
Right click menu for TaskBar to show recent files/folders

### ISSUE THREAD

**Issue by AndrewBasem1** [home-sweet-gnome/dash-to-panel#1870]
**Describe the idea or feature you'd like**
Addition of the recent files/folders/workspaces opened using each app pinned in the TaskBar, this should mimic the windows feature like this:
![right click recent menu](https://i.stack.imgur.com/QHdTh.png)

**Is your feature request related to a problem? Please describe.**
It'll improve navigation and increase workflow speed

**Comment by charlesg99** [comment]
Duplicate of #1835
