### ISSUE TITLE
Improve touch screen support

### ISSUE THREAD

**Issue by astrophil04** [home-sweet-gnome/dash-to-panel#1878]
The extension is unusable on a Linux tablet because minimized windows can't be maximized when touching the running app's icon. 

It would be nice if a touch could maximize the app just like a left mouse click does. "Dash to Dock" works like that. "Dash to Panel" would be the far better choice for small screens though, because it allows you to save valuable screen space.

**Comment by liznevada** [comment]
i can confirm this behavior, 
touching the icon of a closed app will open the app, but subsequent touches do nothing, no minimize or maximize like a left click will do

im using a convertible laptop. and i thought this was a particularity of the weird resistive touchscreen but its nice to know its not my hardware the culprit.

**Comment by Blacklands** [comment]
Yeah, same issue here on a tablet. I hope this is a relatively simple fix/feature addition. because otherwise this extension works really well! But this is a major block for using it with a tablet without a mouse attached.

**Comment by SnoutBug** [comment]
better touchscreen support would be neat. the "show applications" button is usable with a touchscreen, but the app icons are not

**Comment by charlesg99** [comment]
Should work better with the latest version
