### ISSUE TITLE
Make icons grayscale

### ISSUE THREAD

**Issue by DM-VLK** [home-sweet-gnome/dash-to-panel#1879]
**Describe the idea or feature you'd like**

Hello! I want to make a suggestion to add a setting that would make all the icons of running and attached applications grayscale, as GNOME itself shows them in its top panel. For example, the "AppIndicator and KStatusNotifierItem Support" extension has the "Desaturation" option.

**Comment by charlesg99** [comment]
You can now set the icons to symbolic on v62

**Comment by DM-VLK** [comment]
> You can now set the icons to symbolic on v62

Thank you!
