### ISSUE TITLE
Add option to change color and shadow in panel text 

### ISSUE THREAD

**Issue by mkarajohn** [home-sweet-gnome/dash-to-panel#1890]
**Describe the idea or feature you'd like**
It would be nice if we could get an option to control text color and text shadow in the panel text. 

In the screenshot I am showing how I have modified the text in order to better match my preferred color scheme. 
![image](https://user-images.githubusercontent.com/3789226/234832649-8dccd32d-2ad2-4e5d-a18d-5c86234187bb.png)

I had also opened a related issue in Ask Ubuntu [here](https://askubuntu.com/questions/1427040/ubuntu-22-04-change-the-font-color-and-font-shadow-in-dash-to-panel-gnome-exten), where I also documented how I solved the issue myself

The reason I am making this request now is that probably due to an update something must have gone overridden in my modified CSS and the text shadow came back and the text color reverted to black, which now I have to manually remove again by fiddling with the .css file

![image](https://user-images.githubusercontent.com/3789226/234833011-68804e88-762e-4f78-86e8-3f7cc28da1d7.png)

**Comment by charlesg99** [comment]
More of a theme task
