### ISSUE TITLE
Support for AppIndicator badges

### ISSUE THREAD

**Issue by hcldan** [home-sweet-gnome/dash-to-panel#1898]
**Describe the idea or feature you'd like**
I can see that AppIndicators are being fired for some of my applications by using https://extensions.gnome.org/extension/615/appindicator-support/

For example, discord shows me I have unread messages:
![image](https://github.com/home-sweet-gnome/dash-to-panel/assets/648319/e8ff019f-c5c3-41bc-b5ab-6eac80c99a79)

But it never shows on the panel icon:
![image](https://github.com/home-sweet-gnome/dash-to-panel/assets/648319/b0b0f3b7-24a3-4257-8ebf-df3852887c49)

**Comment by charlesg99** [comment]
duplicate of #1695
