### ISSUE TITLE
There's a line under the panel even when transparent.

### ISSUE THREAD

**Issue by wildcard-f8** [home-sweet-gnome/dash-to-panel#1908]
I have the panel completely transparent but now it has a line under it which it never had before.

Manjaro 23.0.0
Gnome Shell 44.1
Dash-to-Panel version 56
Manjaro Official Repositories
![Screenshot from 2023-06-05 13-16-48](https://github.com/home-sweet-gnome/dash-to-panel/assets/51791246/ca4b19d2-60ee-4c99-a4de-56b51eeb5abb)

**Comment by Switch123456789** [comment]
I have the same issue since the update from Gnome 43 to 44, I tried every single setting, I changed color, alpha, sizes, every setting this extension has to offer. But no matter what, the line remains. It is always black, 100% alpha and has a thickness of 1px.

`Arch` `Gnome 44.1` `Dash to Panel 56`

**Comment by Switch123456789** [comment]
The issue still exist (fresh arch install), if I remember correctly it only occurs if color gradient for the taskbar is enabled.

**Comment by charlesg99** [comment]
Dtp doesn't add a line, probably a theme you installed:
![image](https://github.com/home-sweet-gnome/dash-to-panel/assets/33044886/d98fdd85-67d8-4ad8-8dac-1baf3c3a8327)

**Comment by Switch123456789** [comment]
> probably a theme you installed

Like I said, it occurs only with color gradient enabled (wich is probably not enabled in your screenshot). I had that issue on fresh Manjaro & Arch installs, a year ago and a few weeks back still. However, I gave it another try today and indeed, the black line is gone now. I guess it got fixed at some point.

**Comment by charlesg99** [comment]
![image](https://github.com/home-sweet-gnome/dash-to-panel/assets/33044886/b2c8db76-8a16-47e0-8ede-c3ea82954aaf)
