### ISSUE TITLE
Panel rounded ends not showing - Gnome 44.1

### ISSUE THREAD

**Issue by AMoonRabbit** [home-sweet-gnome/dash-to-panel#1910]
**Things to do first**
- Confirm that the problem persists when Dash-to-Panel is the only enabled extension. To do so, disable every other extension, then restart gnome-shell by running the `r` command from the prompt that appears when pressing Alt+F2 on an X.org session, or by logging out/in on a Wayland session.
- Look for Dash-to-Panel errors in your log. To do so, run the `journalctl /usr/bin/gnome-shell -f -o cat &` command and reproduce the problem.
- Search existing opened and closed issues to see if the problem has already been reported.

**Describe the bug**
With Orchis theme applied (both user theme extension and gnome tweaks), dtp should have rounded ends to the panel, however they are missing. If you play with the panel width size, or toggle the extension a few times, they will appear but do not survive a session refresh.

**Linux distribution and version**
Fedora 38 Worstations

**GNOME Shell version**
GNOME Shell 44.1

**Dash-to-Panel version**
56

**Where was Dash-to-Panel installed from?**
GNOME Look site via extension

**Screenshots / Video captures**
If applicable, add screenshots or a link to a video capture to help explain your problem.
![image](https://github.com/home-sweet-gnome/dash-to-panel/assets/3766988/2e3f220b-d376-4db2-a3f3-0813776b0804)

Status bar without rounded ends
![image](https://github.com/home-sweet-gnome/dash-to-panel/assets/3766988/a3b2cb16-15f6-453a-894f-6145881ece10)

How it should look
![image](https://github.com/home-sweet-gnome/dash-to-panel/assets/3766988/82680e1e-44d3-4659-a806-e1f26873c6ac)

I have since removed Blur my Shell as this appears to not play nicely despite panel settings being disabled.

**Additional Info**
Issue I raised on the theme creators' repo
https://github.com/vinceliuice/Orchis-theme/issues/343

**Comment by charlesg99** [comment]
Seems like you fixed it
