### ISSUE TITLE
quicklists / jumplists

### ISSUE THREAD

**Issue by Rik44444** [home-sweet-gnome/dash-to-panel#1911]
Hi,
I'm trying to get clear who to report to that I would love to see quicklists or jumplists in Ubuntu/Gnome. I use the Dash to Panel extension (and love it!! Thank you for the amazing development), so I thought I would try here too.

Basically, what I would want is when I right-click an icon in the taskbar, that I get to see recently opened items of that app (mainly for: all Libreoffice apps, Okular and Thunar, my file manager). 

There is an old feature request here on your Github that relates to it:
https://github.com/home-sweet-gnome/dash-to-panel/issues/225 

I posted this in the past weeks on the gits/fora for Ubuntu, Gnome and LibreOffice, but I am still unclear where the right place is for me to ask this:
Gnome: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/6398
Ubuntu: https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-ubuntu-dock/+bug/2007281 
LibreOffice: https://bugs.documentfoundation.org/show_bug.cgi?id=155680

thanks,
Rik

**Comment by Rik44444** [comment]
For additional info: a dev at LibreOffice [did quite some additional tests](https://bugs.documentfoundation.org/show_bug.cgi?id=155680) and is convinced this is an Ubuntu / Gnome / Dash to Panel issue, and not a LibreOffice issue. THis is consistent with reports that I've seen of quicklists/junplists working on other distros such as Xubuntu. 

Also, [at Gnome they think](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/6398) this is regulated at a dash level, which is good news I guess, that means that Dash to Panel could implement it :)

**Comment by charlesg99** [comment]
Thanks, duplicate of #1835
