### ISSUE TITLE
CSS property border-radius not accepting multiple values

### ISSUE THREAD

**Issue by alixyz-1** [home-sweet-gnome/dash-to-panel#1917]
Description:

When added to stylesheet.css (path /usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/stylesheet.css), css property border-radius applies the first value to all corners, even when multiple values are specified.

For example:
.dashtopanelMainPanel {border-radius: 5px 0px 0px 0px;}

This will set a border-radius of 5px to all corners as if only one value is given.

Version information: Manjaro 23.0.0, GNOME Shell 44.1, Dash-to-Panel version 56 (pre-installed with the distribution).

**Comment by guoqiyi** [comment]
maybe gnome is not using a full-function CSS engine so that someting doesn't work smae as web

**Comment by charlesg99** [comment]
This is a gnome-shell ST issue.
