### ISSUE TITLE
45 alpha support

### ISSUE THREAD

**Issue by darkblaze69** [home-sweet-gnome/dash-to-panel#1925]
**Describe the idea or feature you'd like**
45 alpha is out, so dash-to-panel needs some updating.

**Comment by philippun1** [comment]
The changes for 45 are not final yet, better wait for 45.beta. See https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/6849#note_1799027

**Comment by crab2313** [comment]
https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1499

**Comment by philippun1** [comment]
The migration guide is now available:
https://gjs.guide/extensions/upgrading/gnome-shell-45.html

I started a draft MR: #1939

**Comment by philippun1** [comment]
The migration to gnome 45 is now (almost) done. Everything but the show apps button seems to work again.

Would be nice if someone could test it.

**Comment by Yoskaldyr** [comment]
@philippun1 Where can I get test version for gnome 45?

**Comment by philippun1** [comment]
@Yoskaldyr I use [GNOME OS](https://os.gnome.org/) and [Ubuntu development version](https://cdimage.ubuntu.com/daily-live/current/).

**Comment by Yoskaldyr** [comment]
> @Yoskaldyr I use [GNOME OS](https://os.gnome.org/) and [Ubuntu development version](https://cdimage.ubuntu.com/daily-live/current/).

I mean devel version of dash to panel (I'm using Fedora 39 beta with gnome 45)

**Comment by philippun1** [comment]
You have to checkout / download my [branch ](https://github.com/philippun1/dash-to-panel/tree/gnome-45)and follow the [instructions here](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github).

**Comment by Yoskaldyr** [comment]
> You have to checkout / download my [branch ](https://github.com/philippun1/dash-to-panel/tree/gnome-45)and follow the [instructions here](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github).

Thank you. Looks like everything is working fine

**Comment by skewty** [comment]
working in Fedora Linux 39 Workstation Beta. This issue should probably be closed.
