### ISSUE TITLE
Applications open/close animations have wrong offset

### ISSUE THREAD

**Issue by darekdeo** [home-sweet-gnome/dash-to-panel#193]
When opening or closing applications the animation which is played for window coming out of the application icon has wrong offset when certain conditions are met (explained below).

I am using "Applications Menu" extension and "Places status indicator". The app menu button is also enabled. All of above items are placed at the left side of the panel and are usualy at the left side of the applications icons.

Steps to reproduce:
1. Open any application
2. Enable or disable any of panel items (gnome extensions) which is placed at the left of applications list to make application list change position horizontally
3. Minimize or maximize previously runned application, now window animation is coming to/out of application icon previous origin

**Comment by jderose9** [comment]
Which version of gnome are you on? I'm not seeing this behavior. It seems to animate properly even after adding Applications and Places to the left side of the panel.

**Comment by darekdeo** [comment]
GNOME Shell 3.18.5 on Ubuntu 16.04.2 LTS

**Comment by charlesg99** [comment]
Can't reproduce this. Don't know what fixed it since this was first opened, but it works now :)
