### ISSUE TITLE
Shell freeze when revealing panel

### ISSUE THREAD

**Issue by alvv-z** [home-sweet-gnome/dash-to-panel#1934]
**Describe the bug**
When watching a video full screen with mpv, revealing the panel freezes the shell until I re-login via <kbd>CTRL + ALT + F1</kbd>

**Linux distribution and version**
Ubuntu 22.04.2 LTS

**GNOME Shell version**
GNOME Shell 42.9

**Dash-to-Panel version**
56

**Where was Dash-to-Panel installed from?**
Directly from GitHub

**Screenshots / Video captures**
N.A.

**Additional Info**
Seems to happen with both border=yes and border=no. I have intellihide enabled for maximized windows, and it happens regardless if `Require pressure...` is turned on.

**Comment by charlesg99** [comment]
I can't reproduce this.
