### ISSUE TITLE
dash to panel overridden by chrome window

### ISSUE THREAD

**Issue by valbadalejo** [home-sweet-gnome/dash-to-panel#1936]
After a while of using chrome maximized, its window overrides part of the dash to panel.
It only happens with chrome, as seen in screenshots.
Sorry I can't seem to know how to check the gnome-shell version
Ubuntu version 23.04.
Dash to panel version 56, installed from extensions.gnome

![Captura de pantalla de 2023-08-06 10-23-30](https://github.com/home-sweet-gnome/dash-to-panel/assets/141549965/2a39c3c3-d936-425a-bff8-75a77dbdfdfb)

Thanks

**Comment by charlesg99** [comment]
Using chrome all the time, never seen that. Need a way to reproduce, otherwise this something else on your system.
