### ISSUE TITLE
Gnome 45 system tray running applications not showing. [SOLVED]

### ISSUE THREAD

**Issue by sagitariozod** [home-sweet-gnome/dash-to-panel#1947]
In Gnome 45 beta 1 "system tray" running applications not showing.

![Captura de pantalla de 2023-09-01 10-01-31](https://github.com/home-sweet-gnome/dash-to-panel/assets/7887307/86c5ce05-cdca-4b03-9730-f3fee1b022f9)

**Comment by meizuflym** [comment]
please give a version that supports gnome 45 because the latest version gives an error.

**Comment by sagitariozod** [comment]
I use a branch.

https://github.com/philippun1/dash-to-panel/tree/gnome-45

**Comment by sagitariozod** [comment]
Problem solved. I apologize for opening this thread, I had disabled the Ubuntu Appindicators extension, I have enabled it again and the icons are displayed correctly.

I'm sorry.

![Icons Tray](https://github.com/home-sweet-gnome/dash-to-panel/assets/7887307/7cc98458-a475-41b9-b16e-7e99ff0ab172)

**Comment by sagitariozod** [comment]
![Icons Tray](https://github.com/home-sweet-gnome/dash-to-panel/assets/7887307/49fe5cdc-2b4a-46f5-b0c0-6e928bf53353)
