### ISSUE TITLE
App list context menu arrow or for window previews are touching the panel

### ISSUE THREAD

**Issue by darekdeo** [home-sweet-gnome/dash-to-panel#195]
As described in the title seems like the right click context menu (or window previews) are missing the vertical offset. I made a screenshot to present it:
![issue_image](http://i.imgur.com/AjFVT5v.jpg)
Rather minor problem.

**Comment by darekdeo** [comment]
I've checked and arrow position is touching the "panel" for default Dash (when no extension is installed) and it is the same for Dash to Dock.

So it is made this way by default, but hopefully it could be tweaked for Dash to Panel?

**Comment by jderose9** [comment]
This seems to be an issue with the default theme specifically.

**Comment by charlesg99** [comment]
Hello darekdeo, going to close this as the styling of the new window previews removes the arrow, so this should resolve the issue! Please install master and open new issues if you find something wrong with the new previews! Thanks!
