### ISSUE TITLE
Option to display 'main panel' on all monitors

### ISSUE THREAD

**Issue by dasvh** [home-sweet-gnome/dash-to-panel#1951]
**Describe the idea or feature you'd like**
Currently there is an option to choose on which display the `main panel` should be displayed on.
Additional option to display the `main panel` on all monitors.

**Is your feature request related to a problem? Please describe.**
I did not find a related issue.

**Additional context**
In my setup I do not have a primary monitor, so that ideally every monitor behaves and looks the same. 
As of now I can only display the panel on all monitors but not the `main panel` with the additional extensions / system menus.

**Comment by annndruha** [comment]
+1 vote for this enhancement.
I have a second monitor for laptop, and when i close laptop, the main panel automatically change to second monitor and don't change back when laptop is open again. It would be cool if this setting has a "All monitors" option, and don't change automatically.

**Comment by axel-h** [comment]
The option exists in the version I am using, so it seems this can be closed.

**Comment by dasvh** [comment]
> The option exists in the version I am using, so it seems this can be closed.

Do you mind sharing a screenshot of the option on the version you are using?
I would like to verify your claim before closing this issue.

**Comment by axel-h** [comment]
![image](https://github.com/home-sweet-gnome/dash-to-panel/assets/12140423/c26507a2-68a8-41bb-bbfa-e7f0436640f6)

**Comment by axel-h** [comment]
Actually, I'm not sure I fully understand the issue you facing. Seems even with the option enable, you are still missing some extension to be shown on each monitor's panel then?

**Comment by dasvh** [comment]
> ![image](https://user-images.githubusercontent.com/12140423/277331504-c26507a2-68a8-41bb-bbfa-e7f0436640f6.png)

I assume you are referring to the `Display panels on all monitors`:
This only allows for displaying the dash on all monitors but not the `main panel` itself.
For example, the `main panel` constitutes of the _system menu_ or _date menu_ by default, if I remember correctly:

![test](https://github.com/home-sweet-gnome/dash-to-panel/assets/131653108/c6dafe4e-72ad-4bcb-9936-f238e21e89f1)

**Comment by axel-h** [comment]
Ok, I've done some local experimenting and now I can see the issue you are running into. Things worked for me, because I had things tweaked a bit, so I can actually see all the stuff I use on every monitor. But without the tweaks and using some more extensions I see that these are missing on the other monitors then. 
Sorry for the confusion.

**Comment by charlesg99** [comment]
Unfortunately the other extensions can't easily be duplicated and reused. This would be the responsibility of other extensions to account for multiple panels (like arc-menu does).

**Comment by ankitp94** [comment]
I would also like to request this feature. :)

**Comment by ankitp94** [comment]
It seems that this issue was mistakenly closed. (All the other similar issues, #2007 and #2014, have (rightly) been closed.)
