### ISSUE TITLE
Weird "1" digit in all my window previews' header bars

### ISSUE THREAD

**Issue by nazihhawi** [home-sweet-gnome/dash-to-panel#1952]
I have a weird "1" digit in all my window previews' header bars, right next to the app icon (on the left side, to the right of the app icon). Looks like a badge or something but it's static and doesn't change no matter how many windows or instances of that app are open.

**Linux distribution and version**
Ubuntu 22.04

**GNOME Shell version**
42.9

**Dash-to-Panel version**
56

**Where was Dash-to-Panel installed from?**
The GNOME extensions website.

**Screenshots / Video captures**
![WPHB1](https://github.com/home-sweet-gnome/dash-to-panel/assets/19196258/78cc566c-a989-48a2-87ae-c2bb0eb6b86f)
![WPHB2](https://github.com/home-sweet-gnome/dash-to-panel/assets/19196258/20c5b0c8-4fdf-4944-8a24-baf4bdc7c167)
![WPHB3](https://github.com/home-sweet-gnome/dash-to-panel/assets/19196258/ae93d04c-1248-4717-b162-db34252a63f6)
![WPHB4](https://github.com/home-sweet-gnome/dash-to-panel/assets/19196258/439e358a-92b0-47d4-a3a0-0dcf75511bd2)
https://ibb.co/k00z299
https://ibb.co/bLF9sYR
https://ibb.co/TYJNwxs
https://ibb.co/JK72wD7

**Comment by guoqiyi** [comment]
that means shows your current workspace number,maybe frome your other extension,not dashtopanel's bug

**Comment by nazihhawi** [comment]
Is it configurable in settings? Can it be tuned off? Or for example not shown when there's only 1 workspace?

**Comment by guoqiyi** [comment]
Dash-To-Panel have not this option as I know,also I don't konw what else extensions you've enabled as you havn't list out,maybe you can try disabled one by one to find out which one it is and then configure it.

**Comment by nazihhawi** [comment]
Displaying the workspace number should definitely be an option

**Comment by charlesg99** [comment]
![image](https://github.com/home-sweet-gnome/dash-to-panel/assets/33044886/b919ad53-6ee5-4ea3-b54f-2b6abcb65f04)

**Comment by nazihhawi** [comment]
> ![image](https://user-images.githubusercontent.com/33044886/268443903-b919ad53-6ee5-4ea3-b54f-2b6abcb65f04.png)

Yep, that works. Thanks!
Closing this issue now.
