### ISSUE TITLE
Doubleclicking close button in the window preview crashes the entire gnome-shell

### ISSUE THREAD

**Issue by Proxtx** [home-sweet-gnome/dash-to-panel#1968]
**Describe the bug**
When hovering over an App and then clicking on the close button in the preview in quick succession will crash gnome. Note that I have Ungroup Applications enabled

**Linux distribution and version**
Ubuntu 23.10
**GNOME Shell version**
45

**Dash-to-Panel version**
59

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Comment by charlesg99** [comment]
Maybe I double click like an old person, but I can't reproduce this
