### ISSUE TITLE
Options in menu duplicates dissapear

### ISSUE THREAD

**Issue by simonbcn** [home-sweet-gnome/dash-to-panel#197]
### Environment
- GNOME/GTK+ versions: GNOME Shell 3.24.2 / GTK+ 3.22.15-1
- GNU/Linux distribution: Arch

The Lollypop app menu has one "_Quit_" option (_in English version_):
![salida](https://user-images.githubusercontent.com/428231/27252506-867d84e4-5360-11e7-9ec5-d6e155a4cc9d.jpg)

But in Spanish "_Quit_" was translated as "_Salir_".
The integrated Gnome menu has a "_Salir_" option too (_see screenshot_), this provokes that only one "_Salir_" was printed. In this case, the menu option of app should have preference over the Gnome menú.

**Comment by bil-elmoussaoui** [comment]
It's due to this line of code https://github.com/jderose9/dash-to-panel/blob/0812521f298f3905e852c797b413733dd21e611b/appIcons.js#L939

**Comment by jderose9** [comment]
Quit shouldn't appear under the AppMenu options. 

What I don't understand is why your left image has the application menu in English while your language in gnome shell is set to Spanish?

**Comment by simonbcn** [comment]
The problem is with applications like Lollypop that have a menu option with the same name than integrated Gnome menu.
In left image I executed Lollypop in English (_in console_) to show the hidden option in spanish menu.

**Comment by simonbcn** [comment]
The Lollypop "_Quit_" option is different than "_Salir_" (_Exit_ in english) of Gnome menu. The Lollypop "_Quit_" option closes the window and the program. The Gnome "_Salir_" option only closes the window if Lollypop is playing music.

**Comment by jderose9** [comment]
I'm not really sure of a great way to solve this other than to just add a `Show Quit menu item` toggle to the secondary menu options.
![screenshot from 2017-10-24 21-29-37](https://user-images.githubusercontent.com/2118702/31975945-77a405c6-b902-11e7-993b-26341f72210b.png)
