### ISSUE TITLE
GNOME 45, fixed width for application titles

### ISSUE THREAD

**Issue by theraser** [home-sweet-gnome/dash-to-panel#1974]
**Describe the bug**
If fixed application title width is enabled for dash-to-panel and you open a lot of applications, some of their icons will move out of the visible taskbar area, which is quite uncomfortable.
This is the option I'm talking about: ![image](https://github.com/home-sweet-gnome/dash-to-panel/assets/7988080/70142417-5193-48f3-a5ec-9ef087b17f9d)

And this is the now changed behavior, after upgrading to GNOME Shell 45 (note the fading at the left and right corner, there are more application icons): 
![image](https://github.com/home-sweet-gnome/dash-to-panel/assets/7988080/f233de07-414e-45e9-8207-4f1929c866fa)

This fading area is now "scrollable": If you hold the cursor above one of the faded out corners, the taskbar area will scroll left/right and show the hidden icons. In the past the fixed width was applied until the visible taskbar area was filled, then the icons were compressed to gain space. There was no "scrolling" taskbar and no icons moving out of the visible area at all.

Hopefully this is a new bug and wasn't just unexpected behavior in the past which is fixed now, I really liked the old one! :slightly_smiling_face: 

**Linux distribution and version**
Arch Linux

**GNOME Shell version**
```
$ gnome-shell --version
GNOME Shell 45.0
```

**Dash-to-Panel version**
59

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Comment by delthas** [comment]
Can confirm this appears on my end as well since my last upgrade.

**Comment by runsisi** [comment]
> Can confirm this appears on my end as well since my last upgrade.

me too, the same envrionment as @theraser

**Comment by metal03326** [comment]
The same on Fedora 39 running GNOME 45.1.

**Comment by makkarpov** [comment]
While there is already a lot of confirmations that it's reproducible, I can confirm that I consider this a bug too. Old behavior was much more convenient.

**Comment by gaeljw** [comment]
Same here, Fedora 39, version 59 of the extension. Gnome 45.1.

**Comment by charlesg99** [comment]
I can't reproduce this on xorg gnome 45.1, is this a wayland only thing?
![Peek 2023-11-29 07-51](https://github.com/home-sweet-gnome/dash-to-panel/assets/33044886/fbe1ab1a-05ed-4cb5-b6cb-6327f2a23063)

**Comment by SkyMaverick** [comment]
IMHO this [commit](https://github.com/home-sweet-gnome/dash-to-panel/commit/e9d8702d50c523f6c1bf5fae9f07c2104cd8565a) fixed this bug

**Comment by charlesg99** [comment]
@SkyMaverick You're probably right! I'll prepare a maintenance release soon
