### ISSUE TITLE
Add a note about gettext to manual install process

### ISSUE THREAD

**Issue by epbccorey** [home-sweet-gnome/dash-to-panel#1982]
**Describe the idea or feature you'd like**
In the "Installation from Github" section, under General Instructions there are only two steps.
I did those two and the make failed. The make error didn't make it obvious that I did not have gettext installed.
Can you add a note in the instructions to make sure gettext is installed?

**Is your feature request related to a problem? Please describe.**
Yes, the make failed but I found the solution in 1838
sudo apt install git gettext
https://github.com/home-sweet-gnome/dash-to-panel/issues/1838#top

**Additional context**
Ubuntu 22.04.3 LTS

Make error:
make install
msgfmt -c po/cs.po -o po/cs.mo
make: msgfmt: No such file or directory
make: *** [Makefile:66: po/cs.mo] Error 127

**Comment by charlesg99** [comment]
Thanks, I added the note in the wiki
