### ISSUE TITLE
Rotating display switches Dash to Panel back to Gnome Default

### ISSUE THREAD

**Issue by LinuxTuxguin** [home-sweet-gnome/dash-to-panel#1985]
PopOS 22.04. Kind of a niche issue, but I'm using a 2 in 1 laptop, and any time my display rotates, Dash to Panel reverts my bottom panel to the original one, but the top bar does not reappear. Fixes after restarting the extension via extensions.gnome.org(as I can't figure out how to restart extensions in any other way - restarting Gnome does not work) in any display orientation.

**Comment by charlesg99** [comment]
Unfortunately I PopOS extensions aren't compatible anymore.
