### ISSUE TITLE
Feature Request: More Gnome-like Selection Indicator for Active Window

### ISSUE THREAD

**Issue by Hyperspeed1313** [home-sweet-gnome/dash-to-panel#1986]
**Describe the idea or feature you'd like**
The current design for highlighting the active window in the taskbar doesn't feel very "Gnome-like" being that it's just a sharp-cornered rectangle, while the rest of the items you can select in the panel will use rounded shapes to highlight
![image](https://github.com/home-sweet-gnome/dash-to-panel/assets/2414807/b74c1d77-6dca-42e4-96bb-64c72b191c8f)
![image](https://github.com/home-sweet-gnome/dash-to-panel/assets/2414807/8a541ced-f69b-4f69-815e-467e05ea793a)

![image](https://github.com/home-sweet-gnome/dash-to-panel/assets/2414807/db691de0-1b4f-4a79-aebc-a4d7f6ae2f0c)

It would be nice if the highlight for the active app had options to add rounded corners + optional padding both inside and outside the highlight to more closely match the Gnome style.

Also, combined with fixing #1892 it would finally allow ungrouped applications in a way that doesn't feel like I'm still running Windows 10.

**Comment by xalt7x** [comment]
Might be a duplicate of #1819

**Comment by Hyperspeed1313** [comment]
Agreed this appears to duplicate that issue
