### ISSUE TITLE
Padding settings don't persist after restart.

### ISSUE THREAD

**Issue by wildcard-f8** [home-sweet-gnome/dash-to-panel#1989]
**Describe the bug**
Status icon padding settings don't persist when restarting my computer. I have to turn the extension off and on for it to go back to my preferred settings.

**Linux distribution and version**
Manjaro 23.1

**GNOME Shell version**
45.1

**Dash-to-Panel version**
59

**Where was Dash-to-Panel installed from?**
Manjaro Official Repositories

**Comment by MineShadow7** [comment]
Can confirm the same thing for "Keep original gnome-shell dash = off" setting for Ubuntu 23.10. 
After restart you have both "Dash to panel" and "Gnome panel" with Gnome Panel overriding on top.

**Comment by charlesg99** [comment]
Can't reproduce this
