### ISSUE TITLE
Floating panel and auto width

### ISSUE THREAD

**Issue by Spinnekop** [home-sweet-gnome/dash-to-panel#1993]
1. Floating panel a la Mac and KDE with gap close when maximized window touching?
2. Auto width for non 100% Panel length (if all centred). 
3. Also, rounded corners when not 100%.

**Comment by uzvg** [comment]
I agree, floating panel with round corners and autohide function can give it a shining look.

**Comment by charlesg99** [comment]
All existing issues. Thanks!
