### ISSUE TITLE
Indicator - Metro style is not working correct

### ISSUE THREAD

**Issue by Crestanzio** [home-sweet-gnome/dash-to-panel#1995]
After some time i use my pc like 1 or 2 hours, without a reason, indicator style just changes from what I have selected as an option.

**Screenshots**
![indicator-bug](https://github.com/home-sweet-gnome/dash-to-panel/assets/57988055/6bd621f2-6d90-4b07-8812-2875d2e85eb0)

![indicator-settings](https://github.com/home-sweet-gnome/dash-to-panel/assets/57988055/6e10fdaa-d268-4b33-9a01-dbfc7ece7b37)

**Comment by charlesg99** [comment]
I haven't seen this. Please provide a way to reproduce and we can reopen this.
