### ISSUE TITLE
No longer hiding gnome-shell dash on load

### ISSUE THREAD

**Issue by x9sim9** [home-sweet-gnome/dash-to-panel#1999]
**Describe the bug**
When loading dash to panel the original gnome-shell dash is not hidden

If i go Dash to Panel Settings > Fine Tune > "Keep original gnome-shell dash" and switch it on then off again the dash disappears

**Linux distribution and version**
Ubuntu 23.10

**GNOME Shell version**
Gnome 35

**Dash-to-Panel version**
59

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
![Screenshot from 2023-11-26 18-40-03](https://github.com/home-sweet-gnome/dash-to-panel/assets/43406118/f83ab2ff-1abe-4094-8837-707b73192b57)

**Additional Info**

**Comment by sranger** [comment]
> same here, version 59, ubuntu 23.10.
> 
> actually the original gnome dash disappears on **any** applied setting change.

Same for me, changing any setting has the original dock disappear but loads on startup every time.

**Comment by garyx** [comment]
Been an issue since I upgraded to 23.10 for me. Tried removing and reinstalling. Same issue.

**Comment by charlesg99** [comment]
Should be fixed on master.

**Comment by zpetukhov** [comment]
@charlesg99 
Thank you for fixing & thank you for the product!

ps. to install the master branch on ubuntu23.10 I was needed to install gettext package, otherwise the "make" command didn't work (because 'msgfmt' command wasn't working):
```
sudo apt install gettext
```

**Comment by x9sim9** [comment]
> Should be fixed on master.

I noticed the last release was September I am guessing there are a few fixes in the pipeline for the next release so looking forward to it. Do you have a rough ETA for the next release, would prefer to stick with the releases so I can get future updates but if its still far away I will clone master.

thanks for getting this sorted :-)

**Comment by sranger** [comment]
I would also very much prefer to stick to the releases on the Gnome Extensions website; any idea when the next release will be published there? Thanks for the hard work; awesome extension!

**Comment by radeklat** [comment]
> I would also very much prefer to stick to the releases on the Gnome Extensions website; any idea when the next release will be published there? Thanks for the hard work; awesome extension!

I second this request and thank you for the amazing work :clap: 

Btw. the fastest workaround I found so far is to open the extension manager and turn the extension off/on.

**Comment by radeklat** [comment]
The latest release fixed this issue for me in Gnome 45 :tada:

**Comment by sranger** [comment]
> The latest release fixed this issue for me in Gnome 45 🎉

Same here; thanks for the release update!
