### ISSUE TITLE
Missing the Running Indicator

### ISSUE THREAD

**Issue by Lenald** [home-sweet-gnome/dash-to-panel#2008]
This bug happens sometimes... I barely can describe the steps to reproduce it, but it happens... I had it after some HDMI cable plug outs and ins or after hibernate and boot again.

What is the problem:
Sometimes you can see the running indicators looks like "Dashes", but there is "Metro" selected in the settings. So i would describe it like "The setting is being ignored somewhen"
But if u go to the settings and change Running Indicator Style (Focused/Unfocused Style) OR Running Indicator Position to any value and back -- everything is working good again.

Tbh, if you change the position (for example, it was "Bottom", and you changed it to the "Top") -- you already have the correct Style (For example "Metro"), but in the "Top" position. So you need just to restore the origin value.

My suspicions are:
Somewhen in some cases the extension is being reloaded/reinitiated, and somewhy it is being reading not the set settings values but something else (defaults or what). And you need to reboot the system (to re-read the settings) or to re-set the corresponding settings values to get the application render things according to settings... So my suspicions are: somewhy the app is not reading the real settings during some init cases...

**Comment by Lenald** [comment]
If you could provide me some instructions how to run it from source code and debug -- maybe i could help more... But for now -- i am dump in gnome extensions :C

**Comment by charlesg99** [comment]
Please let me know if you find a way to reproduce this, we'll reopen.
