### ISSUE TITLE
Ubuntu 23.10/Gnome 45 - v60 force disables original dash even when keep dash is enabled in extension settings

### ISSUE THREAD

**Issue by ParodyVerse** [home-sweet-gnome/dash-to-panel#2016]
The newest version force-disables the original dock/dash even when keep dash is enabled in extension settlings.

**Comment by charlesg99** [comment]
This is the original gnome-shell dash:

![image](https://github.com/home-sweet-gnome/dash-to-panel/assets/33044886/e18af4b2-d5df-48e6-a08b-5a103a2c6eeb)

**Comment by ParodyVerse** [comment]
Ah. In that case, can I suggest a button to keep the original launcher on the bottom or more customization (Icon size separate from panel size, rounded highlights as opposed to square (image below), etc)?
![image](https://github.com/home-sweet-gnome/dash-to-panel/assets/32398836/dd91625f-2439-420b-afc7-9ede0d02b57a)

**Comment by ParodyVerse** [comment]
Ah. In that case, can I suggest a button to keep the original launcher on the bottom or more customization (Icon size separate from panel size, rounded highlights as opposed to square (image below), etc)?
![image](https://github.com/home-sweet-gnome/dash-to-panel/assets/32398836/dd91625f-2439-420b-afc7-9ede0d02b57a)
