### ISSUE TITLE
Control the order of applications

### ISSUE THREAD

**Issue by Crestanzio** [home-sweet-gnome/dash-to-panel#2019]
Is there any way to change the order of the applications? i can't find something relative in the settings.

**Comment by charlesg99** [comment]
You can drag and drop the icons, make sure to unlock the taskbar first:

![image](https://github.com/home-sweet-gnome/dash-to-panel/assets/33044886/85fe3692-0d5d-4c32-ba68-f4e951fe1a17)

**Comment by Crestanzio** [comment]
Thanks! that works!

**Comment by tekstryder** [comment]
Hi @Crestanzio: if this is resolved for you, please close the issue.
