### ISSUE TITLE
Dock hides on wrong monitor when fullscreening a window that spans monitors

### ISSUE THREAD

**Issue by lunik1** [home-sweet-gnome/dash-to-panel#2021]
**Describe the bug**
When making a window that spans two monitors fullscreen, dash-to-panel will hide on the monitor the app did not use for fullscreen. 

**Linux distribution and version**
NixOS 23.11

**GNOME Shell version**
45.2

**Dash-to-Panel version**
59

**Where was Dash-to-Panel installed from?**
nixpkgs

**Screenshots / Video captures**
[Video capture](https://www.youtube.com/watch?v=y2ofjbOE3X0)

**Additional Info**
If the window is entirely on one monitor, the dock does not hide when that window is fullscreened, as expected.

**Comment by charlesg99** [comment]
I noticed that with an older version (0.34.1) of mpv. It doesn't happen with the other applications that I tried. Update mpv and check if the issue persists. Not sure when it got fixed, but I can't reproduce this with mpv version 0.36.

**Comment by lunik1** [comment]
I am using mpv version 0.36.0 and can reproduce with firefox https://youtu.be/9Ij8gHM-I40

**Comment by lunik1** [comment]
I've seen this behaviour on vanilla GNOME with the top panel., so probably not dash-to-panel's fault.
