### ISSUE TITLE
No signal connection 39 found error message

### ISSUE THREAD

**Issue by x9sim9** [home-sweet-gnome/dash-to-panel#2024]
**Describe the bug**
Intermittently the Panel loses the clock and widget area, and looks like the screenshot attached, in extensions manager it shows this error "No signal connection 39 found". 

**Linux distribution and version**
Ubuntu 23.10

**GNOME Shell version**
Gnome 45

**Dash-to-Panel version**
60

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
[Panel when working Normally]
![Screenshot from 2024-01-24 09-48-01](https://github.com/home-sweet-gnome/dash-to-panel/assets/43406118/72111368-3ba5-4e6e-b6f2-3c09cd7e5ac4)

[Panel when Broken]
![Screenshot from 2024-01-24 09-44-50](https://github.com/home-sweet-gnome/dash-to-panel/assets/43406118/54d6e281-6eb4-41b5-9f98-becbb77a92b3)

[Error Message]
![Screenshot from 2024-01-24 09-45-49](https://github.com/home-sweet-gnome/dash-to-panel/assets/43406118/90740942-355e-4ec3-9700-f9c345e6b30a)

**Comment by richardroberts** [comment]
Same here, this seems to happen most often when waking from sleep with an external monitor connected.  Ubuntu 23.10, gnome 45, and dashtopanel v 60.  I checked journalctl but only see the following:

```
Feb 29 18:41:43 richard-sc gnome-shell[126919]: JS ERROR: Extension dash-to-panel@jderose9.github.com: Error: No signal connection 8 found
                                                _enable@file:///home/richard/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:110:29
                                                enable@file:///home/richard/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:70:16
F
```

Happy to spend time tracking this down if anyone can give me a hint of where to look.

**Comment by x9sim9** [comment]
> Same here, this seems to happen most often when waking from sleep with an external monitor connected. Ubuntu 23.10, gnome 45, and dashtopanel v 60. I checked journalctl but only see the following:
> 
> ```
> Feb 29 18:41:43 richard-sc gnome-shell[126919]: JS ERROR: Extension dash-to-panel@jderose9.github.com: Error: No signal connection 8 found
>                                                 _enable@file:///home/richard/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:110:29
>                                                 enable@file:///home/richard/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:70:16
> F
> ```
> 
> Happy to spend time tracking this down if anyone can give me a hint of where to look.

Just to clarify in my case I have no external monitor connected and I get this issue happen almost every day, it does seem to be linked to sleep/resume

**Comment by AlbertoZiliani** [comment]
Same here, it happens every time I lock and unlock screen
Ubuntu 23.10 - Gnome 45 (gnome-session)
the weird thing is that if i use ubuntu-gnome-session it doesn't happen so frequently
