### ISSUE TITLE
Icons not showing

### ISSUE THREAD

**Issue by jahan2133** [home-sweet-gnome/dash-to-panel#2027]
I am using gnome 45 in my ubuntu 23.10. It was all fine but suddenly some icons is not showing but the are working properly.
![Screenshot from 2024-02-03 12-39-13](https://github.com/home-sweet-gnome/dash-to-panel/assets/157298499/b50f63f2-3783-49f8-898c-f23f1298faea)

**Comment by charlesg99** [comment]
That's dash to dock
