### ISSUE TITLE
New Workspace Indicator (Gnome 45) Shown in Taskbar Option

### ISSUE THREAD

**Issue by p134c0d3** [home-sweet-gnome/dash-to-panel#2031]
**Describe the idea or feature you'd like**
How difficult would it be to have an option to show the Workspace indicator/switcher in the taskbar? Specifically the new dashed version in Gnome 45?

**Is your feature request related to a problem? Please describe.**
No not related to a problem, just a request. 🙂 

**Additional context**
with the same options to be in left, center or right box, stacked to left, center or right if possible. 

Please let me know if you need additional info! Love Dash to Panel!

**Comment by charlesg99** [comment]
You talk about the activities button? If so please close this issue
![image](https://github.com/home-sweet-gnome/dash-to-panel/assets/33044886/7a34ffe3-6649-4327-8124-ef8256ea45ad)
