### ISSUE TITLE
Backup feature isn't working

### ISSUE THREAD

**Issue by M-Rick** [home-sweet-gnome/dash-to-panel#2032]
**Describe the bug**
When restoring settings from a backup made with Dash-to-Panel, or by using the command line with dconf, Dash-to-Panel isn't working. The extension won't start. It is necessary to remove it clompetely, clear all the settings, and then reinstalling it, in order to get it working again.

I tried to set the settings directly into the extension code with the same results happening.

It works well if I do the configuration manually.

**Linux distribution and version**
Ubuntu 22.04 to Ubuntu 23.10.

**GNOME Shell version**
From Gnome Shell 43 at least to Gnome Shell 45.2.

**Dash-to-Panel version**
from at least version 55 to 60 the last one.

**Where was Dash-to-Panel installed from?**
The GNOME extensions website.

**Screenshots / Video captures**
![Capture d’écran du 2023-03-19 19-54-24](https://github.com/home-sweet-gnome/dash-to-panel/assets/2520948/cc06e678-952c-4c8a-a0d0-e666c9a1bbbc)
![Capture d’écran du 2023-03-19 19-55-52](https://github.com/home-sweet-gnome/dash-to-panel/assets/2520948/5aeb7c57-5466-4d68-a1c2-9b9e391a8eae)
![Capture d’écran du 2023-03-19 19-56-13](https://github.com/home-sweet-gnome/dash-to-panel/assets/2520948/0bf5259a-b6ee-4043-b680-a201315bed33)
![Capture d’écran du 2023-03-19 19-56-26](https://github.com/home-sweet-gnome/dash-to-panel/assets/2520948/9a6abf3e-4a31-4ddb-867e-372d333e4275)
![Capture d’écran du 2023-03-19 19-56-41](https://github.com/home-sweet-gnome/dash-to-panel/assets/2520948/73a497ab-99b4-4790-b783-d91a90b9ef1b)
![Capture d’écran du 2023-03-19 19-56-54](https://github.com/home-sweet-gnome/dash-to-panel/assets/2520948/68366571-f612-4006-9182-65aa27fb26a5)

**Additional Info**
```
[/]
animate-appicon-hover-animation-extent={'RIPPLE': 4, 'PLANK': 4, 'SIMPLE': 1}
appicon-margin=4
appicon-padding=4
available-monitors=[0]
dot-position='BOTTOM'
hide-overview-on-startup=true
hotkeys-overlay-combo='TEMPORARILY'
leftbox-padding=-1
overview-click-to-exit=true
panel-anchors='{"0":"END"}'
panel-element-positions='{"0":[{"element":"showAppsButton","visible":false,"position":"stackedTL"},{"element":"activitiesButton","visible":false,"position":"stackedTL"},{"element":"leftBox","visible":false,"position":"stackedTL"},{"element":"taskbar","visible":false,"position":"stackedTL"},{"element":"centerBox","visible":false,"position":"stackedBR"},{"element":"rightBox","visible":true,"position":"stackedBR"},{"element":"dateMenu","visible":true,"position":"stackedBR"},{"element":"systemMenu","visible":true,"position":"stackedBR"},{"element":"desktopButton","visible":false,"position":"stackedBR"}]}'
panel-lengths='{"0":23}'
panel-positions='{"0":"TOP"}'
panel-sizes='{"0":28}'
primary-monitor=0
status-icon-padding=4
stockgs-keep-dash=true
stockgs-keep-top-panel=false
trans-panel-opacity=0.0
trans-use-custom-opacity=true
tray-padding=10
window-preview-title-position='TOP'
```

**Comment by charlesg99** [comment]
Just tried restoring your file and it works fine on my machine.
