### ISSUE TITLE
46 beta: JS ERROR: TypeError: bodyColor.shade is not a function

### ISSUE THREAD

**Issue by darkblaze69** [home-sweet-gnome/dash-to-panel#2039]
* OS: Arch Linux
* mutter 46beta+r66+gb00fcbf94-1
* gnome-shell 46beta+r74+gb199f466a-1
* gnome-shell-extension-dash-to-panel-git 60.r3.g42eba9b-1 + https://github.com/home-sweet-gnome/dash-to-panel/pull/2028

Since [(clutter: Remove unused Color APIs)](https://gitlab.gnome.org/GNOME/mutter/-/commit/b00fcbf948359d7ac246240d36d82a9f341ab988) there's an issue with indicators for 2nd and more windows of an app - the indicator is not shown, and the error is logged:

```
Feb 26 01:37:03 gnome-shell[223499]: JS ERROR: TypeError: bodyColor.shade is not a function
                                     _drawRunningIndicator@file:///usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:1117:48
                                     _showDots/<@file:///usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:482:26
                                     _setIconStyle@file:///usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:606:33
                                     _displayProperIndicator@file:///usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:693:14
                                     _onFocusAppChanged@file:///usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:668:14
                                     @resource:///org/gnome/shell/ui/init.js:21:20
```

Temporarily removing or commenting out nonexistent shade() function helps, but maybe there could be a way to recreate the intention.

[Screencast from 2024-02-26 01-36-23.webm](https://github.com/home-sweet-gnome/dash-to-panel/assets/6976920/22263b6f-d400-461b-b642-602ca048c35e)

**Comment by philippun1** [comment]
I added a commit which calculates the shades inline and it works again.
