### ISSUE TITLE
Show Applications not working

### ISSUE THREAD

**Issue by MorganNilsson-Upwork** [home-sweet-gnome/dash-to-panel#2040]
I installed this via the extensions on the website. I also tried it via the extension manager. Both have this issue when I click on the button "Show Applications" a side window appears a split second, but nothing else happens. The button doesn't work. I was hoping it would show my "library" where all the apps are installed, similar to Windows. 

What am I doing wrong or is anyone else experiencing this? Everything else works great, just this little problem.

**Comment by okgojoe** [comment]
I have the same issue on Pop OS 22.04 LTS.

**Comment by MorganNilsson-Upwork** [comment]
Yes, I’m using Pop!_OS as well. 
I’ve found a work-around for now, by using ArcMenu (found in extensions). Another problem appeared though, it was not possible to activate this extension, so I used the terminal: **sudo apt install gir1.2-gmenu-3.0** . Then afterwards entering: **killall -3 gnome-shell** . Screen goes black for a while but gets back to normal and I can use the ArcMenu instead. Works great together with Dash to Panel.
