### ISSUE TITLE
this plugin blocks popup menus.

### ISSUE THREAD

**Issue by goulf-3m** [home-sweet-gnome/dash-to-panel#2041]
If I activate a (long) popup menu, the first menu item (the item over dash-to-panel, since dash-to-panel is at the top) does not work.
Visually, the menu item is shown covering dash-to-panel, which is correct.
However, the item cannot be highlighted with "mouse move" nor clicked.
I have to use keyboard to activate that item.

Fedora 39.
The popup menu is from Firefox.
GNOME Shell 45.4
dash-to-panel 60, installed from DNF

**Comment by charlesg99** [comment]
How can I reproduce this with firefox?

**Comment by charlesg99** [comment]
duplicate of #1837
