### ISSUE TITLE
Chrome overlaps dash-to-panel

### ISSUE THREAD

**Issue by maorhz** [home-sweet-gnome/dash-to-panel#2042]
When Google Chrome window is in full screen mode it hides the dash-to-panel bar at the bottom of the screen.
Anyway to prevent that from happening making sure the dash-to-panel bar is always on top? I tried a few tweaks in the extension settings but no dice so far.

**Comment by charlesg99** [comment]
You could set intellihide to allow the panel to be revealed in fullscreen mode then hold it with Super-i. Otherwise this is expected behavior.

![image](https://github.com/home-sweet-gnome/dash-to-panel/assets/33044886/3ab5ecfd-59a2-4f36-86ba-2b15d214be40)
