### ISSUE TITLE
46.beta - Taskbar running application text is neither left-justified, nor centered (sometimes)

### ISSUE THREAD

**Issue by tekstryder** [home-sweet-gnome/dash-to-panel#2045]
Arch Linux | Kernel 6.7.6
Gnome-shell | Mutter 46.beta
Wayland (gnome-shell --no-x11)
Dash-to-Panel Master+https://github.com/home-sweet-gnome/dash-to-panel/pull/2028

![Screenshot from 2024-02-28 09-25-12](https://github.com/home-sweet-gnome/dash-to-panel/assets/11696773/64dc4a96-edec-40c0-a3e6-7360c4ef250c)

When an app is first launched the window title is left-justified. 

After the title changes while using the app, the text moves to the right of centered.

Note the difference between Nautilus window titles (Home vs Music).

**Comment by City-busz** [comment]
https://github.com/home-sweet-gnome/dash-to-panel/pull/2058 fixes the problem.

**Comment by tekstryder** [comment]
> #2058 fixes the problem.

Verified fixed applied atop Master+https://github.com/home-sweet-gnome/dash-to-panel/pull/2028 branch

I'll close this issue when this is merged and the next release is tagged.

Thanks!

**Comment by tekstryder** [comment]
Verified fixed in v61 tag on Gnome 46.0.

Closing.
