### ISSUE TITLE
gap between show-apps and applications list

### ISSUE THREAD

**Issue by geniusahyan** [home-sweet-gnome/dash-to-panel#2049]
**Install dash to pannel**
- And after set it its showing that issue , in past i used it fine but now its not working like i want,
- I tried left box visible button but not working that button properly
![Screenshot from 2024-03-04 02-44-52](https://github.com/home-sweet-gnome/dash-to-panel/assets/147688822/b77414d3-ba40-49a5-b3c7-4e734f312407)

**Comment by charlesg99** [comment]
Hide those two items:
![image](https://github.com/home-sweet-gnome/dash-to-panel/assets/33044886/54064a6a-4ee7-49f0-a7af-441aa3001d9e)
