### ISSUE TITLE
Feature request: Separate icons by workspace

### ISSUE THREAD

**Issue by wxnarwhal** [home-sweet-gnome/dash-to-panel#205]
Great work on this extension.  I've attached a screenshot of my desktop using tint2 because of one feature that's very important to me: separating icons by workspace.  I can switch workspaces by clicking on the tint2 panel or an icon, and I can move an app to a different workspace simply by dragging the icon.  Such a feature in dash-to-panel would make it the perfect dock imo.  This is a feature request and not a bug so I apologize if this is not the appropriate place to contact. 

![tint2_workspaces](https://user-images.githubusercontent.com/10369715/27925793-e0478c7a-623a-11e7-892d-355a0a81c889.png)

**Comment by jderose9** [comment]
Cool idea! Thanks.

**Comment by calarco** [comment]
Something like this [extension](https://github.com/fthx/simple-task-bar)?

**Comment by sne4ky** [comment]
Great job on this essential extension! It would be an amazing addition if we could have the possibility to define different favorite apps in each workspace, so the shortcuts Ctrl+1, Ctrl+2, Ctrl+3... could work differently on each workspace.

This would make it easy to have a workspace for work, another for social apps, etc
