### ISSUE TITLE
Panel takes only half of screen

### ISSUE THREAD

**Issue by bobleman** [home-sweet-gnome/dash-to-panel#2053]
journalctl /usr/bin/gnome-shell -f -o cat &
`Window manager warning: Overwriting existing binding of keysym 37 with keysym 37 (keycode 10).
Window manager warning: Overwriting existing binding of keysym 38 with keysym 38 (keycode 11).
Window manager warning: Overwriting existing binding of keysym 39 with keysym 39 (keycode 12).
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x63500545aa00] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x63500dd5b240] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x635005d59e60] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x6350066e5d00] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x635003de5f40] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x63500524de20] is on because it needs an allocation.
JS ERROR: TypeError: DockManager.getDefault() is null
get extension@file:///usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/docking.js:1719:28
_sendMarginsToExtension@file:///usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/desktopIconsIntegration.js:161:1
_sendMarginsToAll/<@file:///usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/desktopIconsIntegration.js:149:18
_sendMarginsToAll@file:///usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/desktopIconsIntegration.js:148:43
_changedMargins/this._timedMarginsID<@file:///usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/desktopIconsIntegration.js:141:18
@resource:///org/gnome/shell/ui/init.js:21:20
`

panel takes only half of screen

ubuntu 23.10
GNOME Shell 45.2

Dash-to-Panel version 60

**Where was Dash-to-Panel installed from? - GNOME extensions website

**Screenshots / Video captures**
![Screenshot from 2024-03-12 17-34-05](https://github.com/home-sweet-gnome/dash-to-panel/assets/43342591/a23f8360-bc2f-4d8e-a4ca-56a15a86f553)

**Additional Info**
Screen resolution 2560 1440. Extension worked fine, but broke after ubuntu release upgrade

**Comment by charlesg99** [comment]
![image](https://github.com/home-sweet-gnome/dash-to-panel/assets/33044886/1380cbf3-58d1-40e8-b97b-ddfb4ae5e577)

**Comment by bobleman** [comment]
@charlesg99 It is already on 100%. When I change it it shrinks more

**Comment by charlesg99** [comment]
Works fine on my up to date 23.10 test machine. Sorry you're going to have to investigate what is causing this on your system. If you can find a way to reproduce it on a vanilla Ubuntu installation, I will fix it. Thanks

![image](https://github.com/home-sweet-gnome/dash-to-panel/assets/33044886/5562f44f-8756-4371-a448-686a6fdb1593)
