### ISSUE TITLE
If you disable an extension, it cannot be reactivated

### ISSUE THREAD

**Issue by VadimVadimVadim1337** [home-sweet-gnome/dash-to-panel#2054]
Ubuntu 23.10, wayland, GNOME 45.2
downloaded from:
https://extensions.gnome.org/extension/1160/dash-to-panel/
Version: 60

When I disable apps in Extentions I can't re-enable it
No signal connection 11 found
![Screenshot from 2024-03-13 11-15-19](https://github.com/home-sweet-gnome/dash-to-panel/assets/36221770/87621d3e-4e18-4e08-93c1-79b482d3e72e)

![image](https://github.com/home-sweet-gnome/dash-to-panel/assets/36221770/cb880700-5e24-45ab-8886-afedaf093e66)

[journalctl.txt](https://github.com/home-sweet-gnome/dash-to-panel/files/14584585/journalctl.txt)

**Comment by VadimVadimVadim1337** [comment]
I downgraded the version to 59 and this version works

**Comment by VadimVadimVadim1337** [comment]
I increased it to 60 and the problem disappeared. I don't know what happened.

**Comment by tekstryder** [comment]
> You can close the issue!

You can close your issue.
