### ISSUE TITLE
[BUG] Show apps icon off-center/off-screen

### ISSUE THREAD

**Issue by fernandesafp** [home-sweet-gnome/dash-to-panel#2061]
**Describe the bug**
The Show apps icon is off-center/off-screen. I have tried disabling all the extensions but still the same.

**Linux distribution and version**
Arch

**GNOME Shell version**
Gnome 46.0

**Dash-to-Panel version**
Version 61

**Where was Dash-to-Panel installed from?**
The GNOME extensions website.

**Screenshots / Video captures**
![image](https://github.com/home-sweet-gnome/dash-to-panel/assets/71726270/0fb9e1b5-94c6-42f8-9fa9-74941cfea4ad)

**Comment by charlesg99** [comment]
I would think this is more of a theme problem (not icon theme). I can't reproduce the issue with the default gnome-shell theme.

**Comment by fernandesafp** [comment]
I did have [vinceluice's WhiteSur-gtk-theme](https://github.com/vinceliuice/WhiteSur-gtk-theme) installed but it is now removed.

I also ran `dconf reset -f /` and still the same.

**Comment by fernandesafp** [comment]
My solution was to install [Arc Menu extension](https://gitlab.com/arcmenu/ArcMenu) and have it show apps with the GNOME Overview menu option with the intended icon.
