### ISSUE TITLE
Large popup menus are invisible when opened from the panel

### ISSUE THREAD

**Issue by City-busz** [home-sweet-gnome/dash-to-panel#2070]
When I click on a button in the bottom panel, the popup does not appear on the screen if the popup is larger than the height of the screen. I can still navigate the menu blindly using keyboard, so it's probably displayed outside of the screen. To reproduce this, enable an extension that usually provide a large popup menu, e.g. Extension List, Places Status Indicator, Vitals.

It happens only when the Dash to Panel extension is enabled before other extensions with long menus.

Tested with Dash to Panel 61 and GNOME Shell 46.0 on Arch Linux.

**Comment by charlesg99** [comment]
Thanks! Should be fixed on master

**Comment by City-busz** [comment]
I confirm that commit 12675269a860728adea9c962ba67d613376dc397 fixes the problem. Thanks!
