### ISSUE TITLE
how to set style on mouse over?

### ISSUE THREAD

**Issue by JE-Amouel** [home-sweet-gnome/dash-to-panel#2072]
hi,
i wonder how i would be abel to set  differentt style on mouse hover the panel,
mi prime goal is to have a border around the panel when my mouse is hover it,
how can i achieve that goal?
thank.

**Comment by charlesg99** [comment]
Edit this style as you want: https://github.com/home-sweet-gnome/dash-to-panel/blob/12675269a860728adea9c962ba67d613376dc397/stylesheet.css#L43
