### ISSUE TITLE
Horizontally aligned system menu in a vertical panel on the left or right of the screen

### ISSUE THREAD

**Issue by lobstick** [home-sweet-gnome/dash-to-panel#2075]
### Discussed in https://github.com/home-sweet-gnome/dash-to-panel/discussions/2074

<div type='discussions-op-text'>

<sup>Originally posted by **lobstick** April 10, 2024</sup>
If the panel screen position is left the system menu items are aligned as such: (w - wi-fi; s - sound; p - power; icons)
|      (w)     |
|       (s)     |
|       (p)     |

whereas an option to align it horizontally could be added like this:
| (w) (s) (p) |</div>

**Comment by charlesg99** [comment]
Thanks, should be fixed on master
