### ISSUE TITLE
Toggling original gnome-shell top panel doesn't respect current system top bar

### ISSUE THREAD

**Issue by xNS5** [home-sweet-gnome/dash-to-panel#2079]
**Describe the bug**
When I enable the "keep original gnome-shell top panel" setting in the fine-tune menu, Dash to Dock doesn't respect the current top panel settings. For example, I prefer the calendar extension to be on the far right hand side of the panel. 

![Pasted image 20240410212725](https://github.com/home-sweet-gnome/dash-to-panel/assets/27764452/47651b53-17e5-447d-bc77-a6357119c593)

However with that setting enabled, it reverts to the other side of the extensions

![Screenshot from 2024-04-10 21-28-51](https://github.com/home-sweet-gnome/dash-to-panel/assets/27764452/4d561c16-9062-49aa-ae01-a373e710b83b)

In addition to that, when I attempt to move the extension as well as toggle the other top bar settings (Show Workspaces Button and Show Applications Button) nothing happens.

As a workaround, I've found that if I disable Dash to Dock, move the placement of the clock extension back where I want it, then re-enable it respects what I have in my settings.

**Linux distribution and version**
Pop_OS 22.04 LTS

**GNOME Shell version**
Gnome Shell 42.5

**Dash-to-Panel version**
Version 56

**Where was Dash-to-Panel installed from?**
Gnome extension manager

**Comment by charlesg99** [comment]
I don't understand. How do you position the clock to the right of the original gnome-shell top panel? It is centered by default. The extension doesn't modify the gnome-shell top panel when the option to keep it is enabled, so you probably have something else messing it up.

**Comment by xNS5** [comment]
I believe it is centered by default, but in Pop_OS Cosmic you can adjust the position of it in the system settings 

![image](https://github.com/home-sweet-gnome/dash-to-panel/assets/27764452/6d78fee9-d46b-41b6-8766-8098b63d55fc)

I'd need to spin up an ubuntu VM to verify whether this exists in both.
