### ISSUE TITLE
ubuntu 24.04 beta/  white square envelops icons

### ISSUE THREAD

**Issue by vadimk1337** [home-sweet-gnome/dash-to-panel#2081]
![image](https://github.com/home-sweet-gnome/dash-to-panel/assets/36221770/def02352-bdff-477a-aac4-c1628858130c)

I updated to beta and now the white square envelops the icons
Also, my accent colors stopped working, by default it is simply white.

**Comment by debevv** [comment]
Same here, but only for hovered icons
![Schermata del 2024-04-18 22-08-52](https://github.com/home-sweet-gnome/dash-to-panel/assets/8508972/709fd60f-b24e-4e0f-a8e3-f4be5031e61e)

**Comment by vadimk1337** [comment]
> Same here, but only for hovered icons ![Schermata del 2024-04-18 22-08-52](https://private-user-images.githubusercontent.com/8508972/323746394-709fd60f-b24e-4e0f-a8e3-f4be5031e61e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NzU4MDMsIm5iZiI6MTcxMzQ3NTUwMywicGF0aCI6Ii84NTA4OTcyLzMyMzc0NjM5NC03MDlmZDYwZi1iMjRlLTRlMGYtYThlMy1mNGJlNTAzMWU2MWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MThUMjEyNTAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjBlOTllYjFiMmUwMWQ5NzBjYjEwMjBiMjhhYWM5YTk5NzcyMzM0ODAxMTgxZmE1OWViNTdjNTA1NmEyOWFiMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uitNjIfZKs7xcsbZDCq3zf5AO6t5U2z_QyV04scWLmI)
Yes exactly

**Comment by eebette** [comment]
One more here

**Comment by Tamas-Toth-ebola** [comment]
Same here with all the Ubuntu 24.04 betas in the past and currently with the final also.

**Comment by arinc9** [comment]
me too on Ubuntu 24.04.

**Comment by carbohydrate** [comment]
I'm working on the 'white square envelops' around icons piece of this.  I finally found what was causing it and have a fix.  Though I think I can come up with something better (will look at it more later this week).  I'm very new to gnome-shell extensions and still getting a handle on how they work.

Here is what I have right now.
appIcons.js line 154: `this._iconContainer.get_children().forEach(x => x.remove_style_class_name('overview-icon'));`
Right before `this.remove_child(this._iconContainer);`

**Comment by carbohydrate** [comment]
Yeah, I can take a look.  I'm assuming this used to lift the color from your theme?  Sorry not super familiar with how this used to work.

I did notice that in the dash-to-panel settings -> style tab -> Running indicator style (Focused app) -> cog wheel -> Indicator color - Override Theme -> turn on and you can manually change the color.  But guessing that used to be automatic?

**Comment by vadimk1337** [comment]
@carbohydrate 
This worked on Ubuntu 23.10  gnome 45/ dash to panel ver 60. In Gnome-tweaks appearance->Legacy Applications you could choose suppose yaru-red and the color changed automatically. But on 24.04 it disappeared

**Comment by struestyle** [comment]
same problem here 🖐️

**Comment by charlesg99** [comment]
Should be fixed on master. 
@carbohydrate Thanks for the PR!

**Comment by prasannavl** [comment]
Would be great to have a release in with this :)

**Comment by debevv** [comment]
I tried the fix and apparently did not work for me. Then I discovered that there is a similar bug in gnome-shell: https://ubuntuforums.org/showthread.php?t=2497990  
Using the workaround in the bug report solved the issue

**Comment by vadimk1337** [comment]
I reinstalled Ubuntu and the white square appeared again. I understand that the release with this fix hasn't been issued on https://extensions.gnome.org/ 🤣🤣🤣

**Comment by Sargates** [comment]
Fix from release worked, tysm
