### ISSUE TITLE
Application Icons are small .

### ISSUE THREAD

**Issue by houssemko** [home-sweet-gnome/dash-to-panel#2084]
**Things to do first**
I did those things .

**Describe the bug**
The application icons in overview are small when using dash to panel , when using the default adwaita icons or any other custom icon theme .

**Linux distribution and version**
Garuda linux rolling release , 

**GNOME Shell version**
GNOME Shell 46.0

**Dash-to-Panel version**
Version 62 .

**Where was Dash-to-Panel installed from?**
From the third party gnome extension manager app .

**Screenshots / Video captures**
![Screenshot from 2024-04-17 11-53-42](https://github.com/home-sweet-gnome/dash-to-panel/assets/41808005/49ebeb65-b1ec-4ba3-97a6-7bcdd42b98b3)

**Additional Info**
No additional info

**Comment by charlesg99** [comment]
I don't understand, you mean the icons in the app grid? From your screenshot they look normal. With a panel smaller than the original dash, they should have the same size as if the extension was disabled.

**Comment by houssemko** [comment]
Before they used to look bigger .

**Comment by houssemko** [comment]
with all extensions disabled.
![Screenshot from 2024-04-20 10-02-37](https://github.com/home-sweet-gnome/dash-to-panel/assets/41808005/9a1be06a-204a-49ff-a3f0-1542609b7b25)
it used to look like that .

**Comment by houssemko** [comment]
I forgot to apply the default the adwaita icons again but they get to that size too , it's not consistent .  I don't know how to reproduce it .

**Comment by charlesg99** [comment]
Ok, let's close this and reopen if you find a way to reproduce. On my system, the icons have the same size as default gnome.
