### ISSUE TITLE
How can I hide the original dash when I move my mouse to its hotspot?

### ISSUE THREAD

**Issue by pmorch** [home-sweet-gnome/dash-to-panel#2095]
**Describe the idea or feature you'd like**

When I move my mouse the center bottom I'd like nothing to happen.

**Is your feature request related to a problem? Please describe.**

When I move my mouse the center bottom I see this (ironically I couldn't get a normal screenshot of that):

![screenshot on imgur](https://i.imgur.com/yACRwT2.jpeg)

I also see the original dash in addition to dash-to-panel which is visible all the time. But only when I move my mouse center-bottom.

**Additional context**

Dash-to-panel v 59
Gnome 45.5
NixOS 23.11

**Comment by charlesg99** [comment]
I don't think this is dash to panel related. Try disabling all other extensions (including system ones, I don't know NixOS) then restart.
