### ISSUE TITLE
Double-Highlighting of icons

### ISSUE THREAD

**Issue by MartinHaeusler** [home-sweet-gnome/dash-to-panel#2098]
**Describe the bug**

![image](https://github.com/home-sweet-gnome/dash-to-panel/assets/16356998/6792c708-3c32-456f-9be7-d6768dd3625e)

The application I'm hovering over is highlighted (that's ok) but the application **icon** is again highlighted, resulting in two nested boxes. Looks very weird. Happened since I've upgraded to Ubuntu 24.04. Never occurred on 22.04.

**Linux distribution and version**
Ubuntu 24.04

**GNOME Shell version**
GNOME Shell 46.0

**Dash-to-Panel version**
62

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
See bug description.

**Comment by vadimk1337** [comment]
Duplicate 

https://github.com/home-sweet-gnome/dash-to-panel/issues/2081

**Comment by charlesg99** [comment]
Thanks, should be fixed on master
