### ISSUE TITLE
Program icons look bad. When you hover over the apps icon, a black box is displayed.

### ISSUE THREAD

**Issue by Esteban70x7** [home-sweet-gnome/dash-to-panel#2109]
The icons in the panel are seen with a double box. When you hover over the apps icon, a black box is displayed.
I don't know if it is a bug or a wrong configuration. I tried changing some settings, but it didn't work.
![Captura desde 2024-05-23 16-35-16](https://github.com/home-sweet-gnome/dash-to-panel/assets/39741475/3b40c6df-c506-4e68-bf36-5bfd18edb3e2)
![Captura desde 2024-05-23 16-34-56](https://github.com/home-sweet-gnome/dash-to-panel/assets/39741475/ab1da874-57e0-461e-9c46-89732c75c6c5)
[Grabación de pantalla desde 2024-05-23 16-33-14.webm](https://github.com/home-sweet-gnome/dash-to-panel/assets/39741475/15f473a3-ee5c-4172-9722-fc7cf8c783d6)

**Comment by lazarmitic** [comment]
Same here with Ubuntu 24.04 LTS

**Comment by ooliver1** [comment]
Ubuntu 24.04 LTS along with my config
<details>
<pre>
[/]
animate-appicon-hover=true
animate-appicon-hover-animation-extent={'RIPPLE': 4, 'PLANK': 4, 'SIMPLE': 1}
appicon-margin=8
appicon-padding=4
appicon-style='NORMAL'
available-monitors=[0]
dot-color-dominant=false
dot-color-override=false
dot-color-unfocused-different=false
dot-position='BOTTOM'
dot-size=3
dot-style-focused='SOLID'
dot-style-unfocused='DASHES'
focus-highlight-dominant=false
group-apps=true
hide-overview-on-startup=false
hotkeys-overlay-combo='TEMPORARILY'
intellihide=false
isolate-workspaces=true
leftbox-padding=-1
leftbox-size=0
overview-click-to-exit=false
panel-anchors='{"0":"MIDDLE"}'
panel-element-positions='{"0":[{"element":"showAppsButton","visible":true,"position":"stackedTL"},{"element":"activitiesButton","visible":true,"position":"stackedTL"},{"element":"leftBox","visible":true,"position":"stackedTL"},{"element":"taskbar","visible":true,"position":"stackedTL"},{"element":"centerBox","visible":true,"position":"stackedTL"},{"element":"rightBox","visible":true,"position":"stackedBR"},{"element":"dateMenu","visible":true,"position":"stackedBR"},{"element":"systemMenu","visible":true,"position":"stackedBR"},{"element":"desktopButton","visible":true,"position":"stackedBR"}]}'
panel-element-positions-monitors-sync=true
panel-lengths='{"0":100}'
panel-positions='{"0":"BOTTOM"}'
panel-sizes='{"0":48}'
peek-mode=true
preview-custom-opacity=80
primary-monitor=0
secondarymenu-contains-appmenu=true
secondarymenu-contains-showdetails=true
show-appmenu=false
show-apps-icon-file=''
show-favorites=true
show-favorites-all-monitors=true
show-running-apps=true
show-tooltip=true
show-window-previews=true
show-window-previews-timeout=300
status-icon-padding=-1
stockgs-force-hotcorner=false
stockgs-keep-dash=false
stockgs-keep-top-panel=false
stockgs-panelbtn-click-only=false
taskbar-locked=true
trans-bg-color='#9966cc'
trans-dynamic-anim-target=0.20000000000000001
trans-dynamic-behavior='ALL_WINDOWS'
trans-dynamic-distance=20
trans-gradient-bottom-color='#9966cc'
trans-gradient-bottom-opacity=0.40000000000000002
trans-gradient-top-color='#9966cc'
trans-gradient-top-opacity=0.050000000000000003
trans-panel-opacity=0.0
trans-use-custom-bg=true
trans-use-custom-gradient=true
trans-use-custom-opacity=true
trans-use-dynamic-opacity=true
tray-padding=-1
tray-size=0
window-preview-fixed-y=true
window-preview-hide-immediate-click=false
window-preview-show-title=true
window-preview-title-position='TOP'
</pre>
</details>

**Comment by charlesg99** [comment]
#2098
