### ISSUE TITLE
[FEATURE REQUEST] Notification Dots on Apps Icons

### ISSUE THREAD

**Issue by Malix-Labs** [home-sweet-gnome/dash-to-panel#2122]
# Feature Request

## Description

Notification Dots on Apps Icons

## Illustration

Example from [Dash to Dock](https://extensions.gnome.org/extension/307/dash-to-dock/)

### Display

![image](https://github.com/home-sweet-gnome/dash-to-panel/assets/76160668/ddc4e661-18d4-4292-81e2-196585e4a552)

### Settings

![image](https://github.com/home-sweet-gnome/dash-to-panel/assets/76160668/9fee13ec-e35a-4a7e-b575-99cc3e753895)

**Comment by xalt7x** [comment]
Duplicate of the #1695 
Relevant PR - https://github.com/home-sweet-gnome/dash-to-panel/pull/1803

**Comment by Malix-off** [comment]
@xalt7x thanks for the triage!

**Comment by Malix-off** [comment]
Duplicate of #1695
