### ISSUE TITLE
[BUG]The taskbar is shaded

### ISSUE THREAD

**Issue by LFRon** [home-sweet-gnome/dash-to-panel#2130]
Hello,I met a problem while using this extension on GNOME46,the app has an external shader around the app.Could developer fix it?Thanks!
![IMG20240627172656](https://github.com/home-sweet-gnome/dash-to-panel/assets/141307807/ab3f8f20-0efc-425e-8939-ab4091146e21)

**Comment by slax57** [comment]
Seems this is duplicate of https://github.com/home-sweet-gnome/dash-to-panel/issues/2118

**Comment by LFRon** [comment]
> Seems this is duplicate of #2118

Yes it is the same😂I will get it closed now
