### ISSUE TITLE
Upgrade from ubuntu 22.04 to 24.04.1 both panels displayed

### ISSUE THREAD

**Issue by Pastim** [home-sweet-gnome/dash-to-panel#2167]
ubuntu 24.04.1 
Wayland
gnome-shell 46.0
Dash-to-panel 62 from Gnome extensions website

I have only just upgraded from 22.04, where it behaved perfectly.

My panel is at the bottom. When the display powers off, and comes back on, the side panel is also displayed.
When the PC suspends and comes back on, the side panel is displayed even though I have not yet logged on, and the apps are accessible.

I can't find a record of the same issue - I may have missed it.  I have see a similar report on ask ubuntu.

I have now tried with all other extensions off, and it did the same thing.

The following is shown when I suspend and restart.  I hope it is relevant.
DING: (gjs:24934): GLib-GIO-CRITICAL **: 21:11:35.633: file ../../../gio/gfileinfo.c: line 1676 (g_file_info_get_is_symlink): should not be reached
DING: DBus interface for Nautilus (org.gnome.Nautilus.FileOperations2) is now available.
DING: DBus interface for Nautilus (org.freedesktop.FileManager1) is now available.
DING: DBus interface for Switcheroo control (net.hadess.SwitcherooControl) is now available.
DING: DBus interface for Gvfs daemon (org.gtk.vfs.Metadata) is now available.
DING: ** Message: 21:11:35.656: Connecting to org.freedesktop.Tracker3.Miner.Files
DING: GNOME nautilus 46.2
Impossible to enumerate trash children: TypeError: this.location is null

Stack trace:
  _updateTrash@file:///usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/locations.js:786:40
  async*_init@file:///usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/locations.js:714:14
  LocationAppInfo@file:///usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/locations.js:113:4
  TrashAppInfo@file:///usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/locations.js:682:1
  _ensureApp@file:///usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/locations.js:1277:22
  getApp@file:///usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/locations.js:1283:14
  wrapFileManagerApp@file:///usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/locations.js:1230:22
  _ensureLocations@file:///usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/docking.js:1840:50
  DockManager@file:///usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/docking.js:1722:14
  _conditionallyEnableDock@file:///usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/extension.js:21:27
  enable@file:///usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/extension.js:14:14
  _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:267:38
  _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:807:24
  async*_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:836:20
  async*ExtensionManager/<@resource:///org/gnome/shell/ui/extensionSystem.js:49:18
  _callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
  _emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
  _sync@resource:///org/gnome/shell/ui/sessionMode.js:211:14
  popMode@resource:///org/gnome/shell/ui/sessionMode.js:182:14
  _continueDeactivate@resource:///org/gnome/shell/ui/screenShield.js:588:30
  deactivate/<@resource:///org/gnome/shell/ui/screenShield.js:579:44
  finish@resource:///org/gnome/shell/gdm/authPrompt.js:905:13
  finish@resource:///org/gnome/shell/ui/unlockDialog.js:931:26
  deactivate@resource:///org/gnome/shell/ui/screenShield.js:579:26
  _getLoginSession/<@resource:///org/gnome/shell/ui/screenShield.js:170:24
  _callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
  _emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
  _convertToNativeSignal@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:152:19
  @resource:///org/gnome/shell/ui/init.js:21:20

**Comment by giulioturrisi** [comment]
I have the same problem with a fresh Ubuntu 24 installation.

**Comment by Pastim** [comment]
I have managed to make it slightly less of a nuisance.  I turn the extension off and went back to the standard panel, this time on the bottom rather than the side.  After a while I thought I'd give this extension another go.  Now the standard panel is in the same place as my dash to panel.  When the screen is powered off and back on all is good - I don't get both panels.  When the PC is suspended, sometimes it comes back up, before logging in, with the standard panels, sometimes not.  On logging in all gets back to normal.

Could this be some sort of timing issue, the order in which things get executed?

**Comment by Vladimir-Khm** [comment]
I faced the same issue some time ago at Ubuntu 22 with the dash-to-dock extension. Just make sure that when you turn on the dock extension you turn OFF Ubuntu dock, because as I understand it’s forked from it and when they are turned on together it may lead to bugs

**Comment by Pastim** [comment]
> I faced the same issue some time ago at Ubuntu 22 with the dash-to-dock extension. Just make sure that when you turn on the dock extension you turn OFF Ubuntu dock, because as I understand it’s forked from it and when they are turned on together it may lead to bugs

Yes, thanks.  I have turned that off.  However, I still get the standard dock showing when the PC restarts from suspension before I log on, but once logged on all is well.

**Comment by hsg246** [comment]
I have the same problem running fully updated 24.04.1 on a 4K monitor with NVIDIA card and latest NVIDIA driver 550. The problem occurs whenever my screen locks, not related to sleeping since my desktop never sleeps. The original Ubuntu dock appears on the lock screen and is active (so people can turn on various programs even though they can't see the new windows that appear). Unlocking the screen I see just the Ubuntu dock, Dock to Panel is gone. Deleting and reinstalling Dock to Panel from the Gnome Extension webpage gets it working again but I don't want to do that every time I unlock my screen. Hope there is a fix since Dock to Panel is such a useful and elegant program.

**Comment by jjshoots** [comment]
Same issue here, commenting for traction.

**Comment by Pastim** [comment]
The latest release, 63, is worse - I have now got both panels on the bottom bar after resuming from suspension, overlapping and unusable.

**Comment by Pastim** [comment]
I found it hard to downgrade to version 62, but found another rather odd solution.  I looked at the settings of the disabled 'Ubuntu Dock' extension.  I removed all apps and icons etc, moved it to the top row (my Dash to Panel is on the bottom) and got it down to one small blob.  I then turned the opacity right down to 0, so the blob disappeared.

**Comment by FIXXERAUTO** [comment]
Same issue, both panels come up after coming out of standby. trying to figure out how to roll it back to 62

**Comment by charlesg99** [comment]
It might be the same issue as #2018. I added a fix for this on the master branch @FIXXERAUTO @Pastim could you try it and see if it helps?

**Comment by Pastim** [comment]
> It might be the same issue as #2018. I added a fix for this on the master branch @FIXXERAUTO @Pastim could you try it and see if it helps?

Hi,

It took me a while to find out how to update the extension, but I managed.

So far it works, both on resumption from suspend, and from display off and resume..  Thanks a lot.

I cloned (git clone https....) the master version. Renamed the directory to the uuid in metadata.json (dash-to-panel@jderose9.github.com).  I then moved the same directory name from ~/.local/share/gnome-shell/extensions to a safe place, and copied the new directory to  ~/.local/share/gnome-shell/extensions

If there is an easier way I'd like to know :-)

**Comment by charlesg99** [comment]
https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation

On ubuntu you might have to install gettext before running make: `sudo apt install gettext`

Thanks, I'll release this soon on e.g.o!

**Comment by charlesg99** [comment]
#2115

**Comment by Telofy** [comment]
This workaround works for me for now. (I'll upgrade when I get the upgrade through the official channels. I don't want to spend a lot of time trying to figure out how to do it manually.)

![image](https://github.com/user-attachments/assets/b65daaa7-63b9-49eb-8e64-76fdb96320fc)
