### ISSUE TITLE
Dash to Panel (Intellihide) + ArcMenu bug

### ISSUE THREAD

**Issue by valiksheva** [home-sweet-gnome/dash-to-panel#2176]
When used with Dash to Panel extension and its Intellihide option a bug may occur that causes panel to disappear and not reappear with regular cursor move to the bottom of the screen. Panel would not reappear until Super key is used to call ArcMenu again. Sometimes after this bug, the Panel won't hide automatically until extension is disabled and enabled again.

Steps to reproduce:
1. Install Dash to Panel and ArcMenu
2. Activate Intellihide
3. Click ArcMenu button
4. Click at any other point outside the ArcMenu. As the menu closes and Panel is in hiding animation, quickly click ArcMenu again.

Timing is important here and sometimes you can get it working properly, but another time the bug occurs. It's easier to reproduce if timing for Panel hiding is increased.

**Linux distribution and version**
Fedora 40

**GNOME Shell version**
Gnome Shell 46.5

**Dash-to-Panel version**
62

**Where was Dash-to-Panel installed from?**
The GNOME extension manager

**Screenshots / Video captures**

https://github.com/user-attachments/assets/4a514bf8-63c3-4a20-9460-494241c246e0

**Comment by charlesg99** [comment]
Thanks I could reproduce it. Seems like it is an issue with ArcMenu, here is the log when reproducing the issue:

```
Exception in callback for signal: open-state-changed: Error: Argument event may not be null

Stack trace:
  _maybeHidePanel@file:///home/cgagnon/.local/share/gnome-shell/extensions/arcmenu@arcmenu.com/menuButton.js:544:36
  _onOpenStateChanged@file:///home/cgagnon/.local/share/gnome-shell/extensions/arcmenu@arcmenu.com/menuButton.js:520:50
  _callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
  _emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
  close@resource:///org/gnome/shell/ui/popupMenu.js:1125:14
  close@file:///home/cgagnon/.local/share/gnome-shell/extensions/arcmenu@arcmenu.com/menuButton.js:627:15
  PopupMenu/<@resource:///org/gnome/shell/ui/popupMenu.js:1018:30
  onComplete@file:///home/cgagnon/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/intellihide.js:416:50
  _makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:67:13
  _easeActor/<@resource:///org/gnome/shell/ui/environment.js:160:64
  @resource:///org/gnome/shell/ui/init.js:21:20

```

**Comment by valiksheva** [comment]
Hi.
Thanks. 
I posted the issue to the ArcMenu team and now it's fixed.
