### ISSUE TITLE
"tray" icons missing.

### ISSUE THREAD

**Issue by iconoclasthero** [home-sweet-gnome/dash-to-panel#2177]
**Things to do first**
ok.

**Describe the bug**
there'reno tray icons.
I'm trying to find a bunch of things that should be in there like deluge-gtk, keepassxc, guake... Nothing.  The only thing thing that shows up in a tray-like capacity is Pano.

**Linux distribution and version**
**GNOME Shell version**

OS: Rhino Linux 2024.2 (server) x86_64 
Kernel: Linux 6.10.9-061009-generic 
DE: GNOME 47.0 
DE: GNOME Shell 47.0 

**Dash-to-Panel version**
9999

**Where was Dash-to-Panel installed from?**
https://github.com/home-sweet-gnome/dash-to-panel/pull/2154

(It wasn't working properly when I was still using GNOME 46 and whatever was on gnome extensions website so I don't think this should be dismissed simply because it's not a release version.)

**Screenshots / Video captures**
If applicable, add screenshots or a link to a video capture to help explain your problem.
![screenshot From 2024-09-19 15-03-57](https://github.com/user-attachments/assets/6e8950ce-b8ce-40d5-a1be-746038778f36)

![screenshot From 2024-09-19 15-05-54](https://github.com/user-attachments/assets/7c51ad51-d67f-4d36-a1ee-ec274798dc94)

**Comment by charlesg99** [comment]
This extension doesn't provide tray icons. Try installing one like https://extensions.gnome.org/extension/615/appindicator-support/
