### ISSUE TITLE
Panel Not rendering GNOME 47

### ISSUE THREAD

**Issue by o-Haxolotl-o** [home-sweet-gnome/dash-to-panel#2178]
**Bug result**
- Panel renders as black bar or not at all, though windows still scale to its bounds
- When rendered as black, right clicking the panel shows the correct menu

**Expected result**
![Screenshot From 2024-09-19 18-32-15](https://github.com/user-attachments/assets/95002b99-5d72-4f6c-97b0-afad0cb2a4d6)
(screenshot of a video capture)

**Linux distribution and version**
Arch

**GNOME Shell version**
version 47.0

**Dash-to-Panel version**
version 62

**Where was Dash-to-Panel installed from?**
GNOME shell extension manager

**Screenshots / Video captures**
Result of `journalctl /usr/bin/gnome-shell -f -o cat &`  command
![Screenshot From 2024-09-19 18-16-19](https://github.com/user-attachments/assets/650e1302-562b-4fb6-a835-5a0cb3614b14)

Error shown in extension manager
![Screenshot From 2024-09-19 18-21-35](https://github.com/user-attachments/assets/c6b5bb17-50b9-4815-9f70-2197f080848b)

Panel is currently not rendering at all so I cannot screenshot it

**Additional Info**
Bug occurred immediately after rebooting into GNOME 47 so it is likely the root cause

Thank you!

**Comment by vialrogo** [comment]
I had the same error. I think that the method no longer exists. Furthermore, I could run the extension disabling the override panel theme background color option (for obvious reasons), but, besides it works, I experimented some crashes, then for now I had it disable waiting to the official release.

**Comment by o-Haxolotl-o** [comment]
Thank you so much for the quick fix! I tried the same thing earlier after seeing the error, but forgot to reload the shell. Anyways, I appreciate it.

**Comment by NiffirgkcaJ** [comment]
GNOME 47 finally dropped! Unfortunately, it broke this extension. :(

**Comment by o-Haxolotl-o** [comment]
It officially works, Nice! closing it.
