### ISSUE TITLE
"Show running applications" includes applications from all workspaces

### ISSUE THREAD

**Issue by steve-todorov** [home-sweet-gnome/dash-to-panel#2184]
**Describe the bug**

I have the following configuration:

![image](https://github.com/user-attachments/assets/12f8b188-ecc6-4bde-9797-6bd313f9c479)
![image](https://github.com/user-attachments/assets/eb58e896-3e41-4f05-a8ca-843dfc73307a)

However when I switch workspaces, the panel includes the application list from **all workspaces**.
Previously, it used to only show the list of apps running in the current workspace. 
I have a vague memory in some versions of Dash To Panel there was an actual checkbox, but it got removed due to the new setting in Gnome.

**Linux distribution and version**
```
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
```

**GNOME Shell version**
```
GNOME Shell 46.0
```

**Dash-to-Panel version**

```
63
```

**Where was Dash-to-Panel installed from?**

From extensions.gnome.org

**Comment by charlesg99** [comment]
Your first screenshot... scroll down a little

**Comment by steve-todorov** [comment]
Oh... I was looking for that "Isolated Workspaces" so hard. Was not showing for me for some reason. Once I upgraded to the latest version it seems to be showing and is working as expected. Probably was some glitch. Closing as fixed, thanks! :)
