### ISSUE TITLE
Feature Request: Show desktop on mouse hover over Show Desktop button

### ISSUE THREAD

**Issue by AlexGluck** [home-sweet-gnome/dash-to-panel#219]
Simple idea, subject say all.

**Comment by Warmuser** [comment]
Can I add my tip too? @jderose9 would be possible to hide only the favourites when the menu is opened? I mean like this: [https://i.imgbox.com/xnDfqKD8.png](url)

**Comment by jderose9** [comment]
@AlexGluck  You mean show the desktop when hovering over the "Show Desktop" button right?

@Warmuser Your image link isn't working.

**Comment by AlexGluck** [comment]
@jderose9 Yep.

**Comment by Warmuser** [comment]
@jderose9 here is the corrected url, I'm sorry: http://imgbox.com/xnDfqKD8 :)

**Comment by charlesg99** [comment]
Hey guys, I know it's been a while, but this option was added to master if you want to try it! Thanks!

**Comment by jderose9** [comment]
@charlesg99 This is awesome! Thanks! Do you think it should be enabled by default?

**Comment by charlesg99** [comment]
@jderose9 Not sure... It might bother people who are already using the desktop button, then again it should be easy enough to figure out how to disable it. Also, on default gnome-shell there isn't much to see on the desktop, but on ubuntu people can have icons... uhmm... I guess what I'm saying is, you decide :)
