### ISSUE TITLE
How to get launcher behavior instead of pins

### ISSUE THREAD

**Issue by OoDeLally** [home-sweet-gnome/dash-to-panel#2217]
Both Windows and Linux used to have a bar of launcher icons, which when clicked, would launch an app. The taskbar would show that app running, while the launcher icon would stay in its original place, unaffected by whether or not you have that app running.
Then MacOS came with its dock & pins paradigm, and Ubuntu adopted the same philosophy on Gnome3, so oldies like me had to switch to either Linux Mint, or Ubuntu with DashToPanel.
I noticed that DashToPanel "favorite apps" uses that "pin" behavior, where the launcher icon is **replaced** by the running app, and shifts every other launcher icons sideway. Afterall, most monitors have plenty of horizontal real estate, so the benefits of grouping things is small.
This really hurts my OCD, and I wish I had the old behavior, where the launcher icons would be static and never pop sideway. 
Is there a way to obtain this behavior? I have not found it in the settings.

**Comment by charlesg99** [comment]
Try this:

![image](https://github.com/user-attachments/assets/9134ba9c-de61-4424-8a9a-d19b083e7bf5)

**Comment by OoDeLally** [comment]
Holy moly, that's it, thanks!
