### ISSUE TITLE
Jump-lists?

### ISSUE THREAD

**Issue by rhyek** [home-sweet-gnome/dash-to-panel#225]
This extension is a god-send for someone coming over from Windows 10. This is the only feature missing. I am a developer and I greatly miss jump-lists which I use to directly open a project in Visual Studio Code from the task bar.

![image](https://user-images.githubusercontent.com/702922/28996658-0a2e9364-79c2-11e7-9491-f65669887bc8.png)

**Comment by voidray** [comment]
For me this is a must have, before I could switch to linux. I really like the extension and I hope this will be implemented at some point.

**Comment by jderose9** [comment]
If I understand correctly, I believe this is already supported, but just not implemented by many applications. For instance, Nemo:

![screenshot from 2017-09-12 15-31-31](https://user-images.githubusercontent.com/2118702/30344499-826b9162-97cf-11e7-9fd3-c6df2c0d9936.png)

I think that you don't see this in more applications is more specific to the applications not implementing this than it not being supported. If you opened a text file, for instance, having it added to recently used documents list would have to happen on the application side as the shell would not have this information.

It could be possible to create your own lists by pinning different command line arguments to the list, ie: `gedit ~/my-note.txt`. Is that desirable?

**Comment by jderose9** [comment]
Good question. Actually looking into it now, it seems that those nemo options are provided in the .desktop file, which means they are static. They are called "Action Lists".

https://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#extra-actions

So you could actually add them yourself to your `/usr/share/applications/code.desktop` file currently to open specific locations:

```
[Desktop Action open-myProject]
Name=My Project
Exec=code ~/myProject
```

This is your best bet at an easy fix, but it won't provide a recently used list, only a static list that you specify in the .desktop file.

I'm curious if VS Code could write an appended .desktop file to the `~/.local/share/applications` folder each time a new project is opened, though. (The `~/.local/share/applications` directory desktop file overwrites the `/usr/share/applications` file of the same name).

In terms of other options
- Applications can implement the gnome appMenu (called RemoteMenu in the shell code) which can be used to dynamically add options to the right-click menu, but sadly is only available when the application is running so wouldn't be useful for this scenario.
- It looks like there is a systemd service called Zeitgeist that ships with Ubuntu which tracks file usage and gnome-shell extensions based on this to provide jump-lists used to exist, however they seem to have been abandoned/deprecated years ago.

**Comment by rhyek** [comment]
I'm don't think these actions are meant to be dynamic. Two issues I see from a couple tests I did:
- You must have all the content in `/usr/share/applications/code.desktop` copied to `~/.local/share/applications/code.desktop` including `[Desktop Entry]`. Application updates would be an issue.
- I've only been able to reflect the changes with a reboot.
- Any new action is shown inside a default extra actions section in the taskbar menu. There doesn't appear to be a way to create a new section with actions associated to it. For example: A 'Recently opened' section.

The following image shows my custom action `salesmaster` right below the application's own `New Window` action.

![image](https://user-images.githubusercontent.com/702922/30353559-5fa7412c-97ec-11e7-85c2-b01b4559ae85.png)

**Comment by jderose9** [comment]
Thanks for the research. If the applications could store their recently used files list in dconf (or a text file) that could be read by the extension, creating the additional menu items seems pretty trivial. I'm just not sure whether some standard exists for this behavior already. I'm also not sure whether there are any permissions issues (for instance, can an extension read from a key written by an application).

Perhaps @micheleg has some knowledge? This seems like it could benefit dash-to-dock as well.

**Comment by maoschanz** [comment]
Hi, i did this extension https://github.com/maoschanz/quicklists-gnome-shell-extension and while the code is not very performant, i think it's a good start if you want to implement this feature here.

It's not necessary however, AFAIK both extensions can coexist.
