### ISSUE TITLE
Context (right-click) menu doesn't work correctly in some applications

### ISSUE THREAD

**Issue by ceyhunn** [home-sweet-gnome/dash-to-panel#228]
When I right click  on gnome-sushi icon in order to show context menu above dash-to-panel, context menu appears on top-left corner:

![screenshot-20170814131037-520x376](https://user-images.githubusercontent.com/5506156/29265416-017ec144-80f2-11e7-8451-4dc176accf9d.png)

**Comment by jderose9** [comment]
I'm having trouble reproducing this. Are you launching sushi from inside of Files? when I do so, it doesn't even open an icon on the dash - the window is just attached to the parent window.

**Comment by ceyhunnabiyev** [comment]
On the the panel, click right click of gnome sushi icon in order to see context menu on Wayland, not on Xorg..

**Comment by jderose9** [comment]
Is this still an issue?

**Comment by ceyhunn** [comment]
Hi @jderose9 
I don't use Wayland anymore, because of driver issues. If you don't notice this issue, you may close.
