### ISSUE TITLE
Invisible hover window on  some extension icons 

### ISSUE THREAD

**Issue by ceyhunnabiyev** [home-sweet-gnome/dash-to-panel#229]
Gnome-Panel shows cursor hover window  on some extension icons at the bottom of the panel, When I enable dash-to-panel extension, the hover window have to appear above the panel.
(Example: [gnome-shell-system-monitor-applet](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet) )

Thanks for Great Extension,
Best Regards..

**Comment by jderose9** [comment]
So you are currently not seeing the system monitor window at all when the panel is in the bottom position? Am I understanding? Does the popup take up most of your vertical space on your monitor by chance?

**Comment by ceyhunnabiyev** [comment]
Hi @jderose9 ,  Sorry for late answer..
> So you are currently not seeing the system monitor window at all when the panel is in the bottom position? Am I understanding?

 Absolutely right :) When mouse  cursor on the item, I don't see the window, and I guess, this issue is no only  related to this extension.

> Does the popup take up most of your vertical space on your monitor by chance?

I gave you screenshots:

![screenshot from 2017-09-13 13-49-36](https://user-images.githubusercontent.com/5506156/30371369-6b0263a4-988b-11e7-9f17-b207e8dfb6df.png)
![screenshot from 2017-09-13 13-50-22](https://user-images.githubusercontent.com/5506156/30371367-6afad26a-988b-11e7-90c8-a18fc23c3b49.png)

**Comment by jderose9** [comment]
I installed this extension. When I hover over the panel button, nothing happens. But nothing happens without dash-to-panel either. When I click, the menu pops open (with and without dash-to-panel). Are you sure there is an issue related to this extension?

**Comment by ceyhunnabiyev** [comment]
Enable `show tooltip` option in this extension preferences, and you will see..

**Comment by charlesg99** [comment]
Hello, I think it was an "issue" with the system monitor extension which was resolved at some point. From their code:

```
// Hacky condition to determine if the status bar is at the top or at the bottom of the screen
if (allocation.y1 / monitor.height > 0.3) {
    tipy = allocation.y1 - height; // If it is at the bottom, place the tooltip above instead of below
}
```

I just tried the extension and the tooltips are working correctly:

![image](https://user-images.githubusercontent.com/33044886/47616049-e3afe700-da8d-11e8-82a0-a9b8a000eb8d.png)

Thanks!

**Comment by charlesg99** [comment]
Reference: paradoxxxzero/gnome-shell-system-monitor-applet#408
