### ISSUE TITLE
Feature Request: Click to open window preview (if more than one application)

### ISSUE THREAD

**Issue by andrewgazelka** [home-sweet-gnome/dash-to-panel#235]
Dash to Panel looks much better than Dash to Dock in my opinion, but the killer feature dash to dock offers is the ability to click (and not hover) to see window previews if there is more than one application. If there is one application, then DTD just opens it. Can this be integrated into Dash to Panel?

**Comment by jderose9** [comment]
Sounds reasonable to me.. thanks!

**Comment by lkc0987** [comment]
Can this be a config option? because I really like the way it works currently.

**Comment by jderose9** [comment]
Definitely would be a config option with the default behavior as it is now.

**Comment by khpark0203** [comment]
When will this feature be added?
Is this function the same as that of Dash to dock (Minimize or show previews)?

**Comment by AdrianVerde** [comment]
Can we have this? :+1:

**Comment by khpark0203** [comment]
I correct my local "dash to panel" code.
And I add this function (minimize and preview).
It is work well.
So, can I add corrected code on my github?
If you (jderose9) tell me "OK", I want to add code on my github.

**Comment by jderose9** [comment]
Hey guys, this has been added to master as pull request #553. To enable it, you will find a new "Toggle single / preview multiple" option in the click behavior dropdown on the Behavior tab. Thanks @ihsankavalci !
