### ISSUE TITLE
Make App Icon Margin clickable

### ISSUE THREAD

**Issue by jhasse** [home-sweet-gnome/dash-to-panel#244]
Basically turning it into a padding instead. The reason for this is, that I often miss the icons by clicking between them, when I'm quickly moving my mouse to the panel.

**Comment by jderose9** [comment]
I don't mind for this to be added, but I'm not clear on whether this needs to be configurable, or whether the hover appearance should reflect this.. any thoughts?

**Comment by jhasse** [comment]
I don't see any disadvantage for this, so I don't think it needs to be configurable. I think the hover appearance should visually stay the same but should be triggered by the clickable margin.

**Comment by charlesg99** [comment]
Hey, I started looking at this, but I need some feedback on what should happen on hover... 

I find it weird to have the same hover appearance when there is a large clickable margin: 
![small_hover](https://user-images.githubusercontent.com/33044886/38697290-2a27ee36-3e57-11e8-9e59-6a471f6be57e.gif)





I also don't really like extending the hover style to accommodate the clickable margin:
![large_hover](https://user-images.githubusercontent.com/33044886/38697317-3a684c00-3e57-11e8-8842-a5a59d101fef.gif)




What do you guys think? Thanks

**Comment by jhasse** [comment]
I like the first version :) Makes it also easier to open the popup.

**Comment by charlesg99** [comment]
Hey jhasse, thanks for your feedback. Could you please try the update on branch "appicons-padding"? The margins should now be clickable. Thanks!

**Comment by jhasse** [comment]
Just tried it and it works perfectly :)

**Comment by charlesg99** [comment]
Thanks for the feedback, the update has been merged to master.

**Comment by duncanw-xyz** [comment]
@charlesg99 Thanks for fixing this issue, clickable margins work great now.

I know this issue has been closed, but is it possible to revisit the hover appearance? Personally, I think it makes more sense to go with option 2 above as there is no difference between clicking the app icon or the app margin from a functionality point of view.
