### ISSUE TITLE
Windows Thumbnails are too large

### ISSUE THREAD

**Issue by alex285** [home-sweet-gnome/dash-to-panel#27]
and also there is a lots of padding between them.
can be an option so we can make them smaller, and compact (reduce padding / margin)

**Comment by jderose9** [comment]
Great idea.. I agree!

**Comment by nelsonsimao** [comment]
I agree with that, it will be nice to have a feature to reduce/increase the preview window size.
Normally I edit windowPreview.js and change size variables to:
DEFAULT_THUMBNAIL_WIDTH = 250;
DEFAULT_THUMBNAIL_HEIGHT = 100;

How can I change padding?

**Comment by slacka** [comment]
I experimented with these defaults
```
DEFAULT_THUMBNAIL_WIDTH = 250;
DEFAULT_THUMBNAIL_HEIGHT = 100;
```
And I found them too small to make out the content clearly. If we make this change, it should be an optional setting.

**Comment by dobkeratops** [comment]
would it make sense to scale the previews based on the number of windows visible.. if you've got a couple of windows, show them large (so you can read the content); if you have loads option, show them smaller.
in the case where you have a lot of windows open, you probably want to use desktops to organise things more (now imagine if you had an icon for the desktop overview on the panel aswell, maybe that could actually show desktop thumbnails when you hover in a similar manner for a seemless experience)

**Comment by SolarLiner** [comment]
Also, the previews should scale according to screen dimensions - the larger the screen the larger the thumbnail can be while staying comfortable. The thing is that most desktop computers have large screens and would feel the thumbnails to be small while on my 14'' laptop the same thumbnails would be huge.

**Comment by jderose9** [comment]
On #163 dobkeratops added:

> Could the window thumbnails be brought closer together by splitting the title text over 2 or more lines, to minimize the gaps between each?

**Comment by TurkeyMan** [comment]
If you do a pass making this more configurable, I'd also like smaller thumbs with much smaller margins, but I'd also like an option to remove the text; I feel the thumbnail is enough, I don't read the text, it just wastes space.

**Comment by charlesg99** [comment]
Hey alex285, do you think the new settings resolve the issue?

**Comment by alex285** [comment]
@charlesg99 sure! i just didnt have a notification to this issue to close it!
thank you!
