### ISSUE TITLE
Leaving desktop breaks app hotkeys

### ISSUE THREAD

**Issue by alterionisto** [home-sweet-gnome/dash-to-panel#281]
Got my setting *Use hotkeys to activate apps* enabled.
When I logout and login to my user, `Super+(0-9)` hotkeys no longer work. 
To make them work again I must go to *Dash to Panel Settings* and re-enable *Use hotkeys to activate apps* setting

As a workaround I'm using "Appkeys" Gnome extension which doesn't have the described issue

Ubuntu 17.10
gnome-shell 3.26.1-0ubuntu5
dash-to-panel 4a54f1896c65d77908e71144c38365cd1e987fae

**Comment by jderose9** [comment]
Are you saying that after logging out and back in, that the setting has been disabled? Or is it still enabled but does not work as expected?

**Comment by alterionisto** [comment]
The setting is left enabled, but it doesn't work

**Comment by MylesJohnson** [comment]
This was fixed for me by uninstalling the built-in Ubuntu dock, even though it was disabled.
`sudo apt remove gnome-shell-extension-ubuntu-dock`

**Comment by jderose9** [comment]
Pinging @franglais125 ..

**Comment by jderose9** [comment]
I believe @charlesg99 fixed this. Can you try the latest master?
