### ISSUE TITLE
Feature request: Keep Old Dash in Activities Window

### ISSUE THREAD

**Issue by lexman098** [home-sweet-gnome/dash-to-panel#284]
Sorry if this has already been requested, but I couldn't find a search term that gave me less than 100s of results. It would be nice to have an option to not remove the original dash (dock) that shows up in the left of the activities pane.

**Comment by Baltix** [comment]
+1 for optional feature "Keep original Dash in Activities Overview" - there are lots of video tutorials how to user GNOME Shell and Dash is on the left side when you click on "Activities", please add setting for keeping original Dash on the left in Activities Overview mode.
Thanks for very useful extension :)

**Comment by charlesg99** [comment]
Hi, thank you for the suggestion! A setting ("fine-tune" tab) to keep the original dash was just added to master, please check it out. Thanks!
