### ISSUE TITLE
gnome-shell segfaults on enabling extension

### ISSUE THREAD

**Issue by Jayfrown** [home-sweet-gnome/dash-to-panel#285]
Enabling any version of `dash-to-panel` extension, either from extensions.gnome.org or from git, directly results in a `SIGSEGV` for gnome-shell. No such problems with other extensions (e.g. `dash-to-dock`)

Funtoo Linux AMD64 (`-march=bdver2`)
GNOME Shell 3.20.4
kernel-debian-sources-x86_64-4.8.15-1

N.B.: Funtoo builds `gnome-shell` with `USE="deprecated"` to disable systemd dependencies. Gnome versions differ from upstream (i.e. Gentoo ebuilds) so Funtoo likely adapts source code to work without systemd/udev

Might you need more information, I'm willing to provide it.
Core backtraces generated by abrt: https://pastebin.com/6eaDziJk
Most of my shared objects are missing debugging symbols. Let me know which ones you need to see, and I'll regenerate the core dumps.

**Comment by jderose9** [comment]
Do you mind to give the latest `master` branch a shot and see if this issue persists? Thanks!
