### ISSUE TITLE
Feature Request: Suitable Vertical Panels

### ISSUE THREAD

**Issue by CpTait** [home-sweet-gnome/dash-to-panel#289]
I like my dock to the left of the screen. I'd love it if this was integrated.

**Comment by Miguel-Dorta** [comment]
I think it's explained in the FAQ of README.md, in the part that says:

> Why can't I put the panel vertically on the left or right of the display? Gnome-shell and it's numerous extensions add widgets to the panel. These widgets have been designed using padding and absolute positioning assuming a horizontal layout. At this point in time, I don't think it is possible to allow for a vertical layout and still maintain any sort of reasonable compatibility with many of the other features of Gnome.

**Comment by MBach** [comment]
Don't you think you could add this feature and mark it as "alpha" or "experimental". So testers enjoy this new thing, and could list all widgets that are not working very well, and maybe, might create a virtuous circle of PR?

**Comment by charlesg99** [comment]
Hi, please see #3 to follow this issue. Thanks!
