### ISSUE TITLE
Negative app icon margin.

### ISSUE THREAD

**Issue by Swedneck** [home-sweet-gnome/dash-to-panel#293]
Would it be possible to implement this? I'd really like the app icons to be much closer together.
![image](https://user-images.githubusercontent.com/31285258/33140887-aea41e74-cfb1-11e7-9a3a-91bfd06d400b.png)

**Comment by jderose9** [comment]
Are you looking for the behavior requesting in #244 ?

**Comment by charlesg99** [comment]
Hey Swedneck, could you please try the update on branch "appicons-padding" and see if the new setting that adjusts the icons padding helps with this issue? Thanks!

**Comment by charlesg99** [comment]
The new setting has been merged to master and it should allow to reduce the space between the app icons. Thanks!
