### ISSUE TITLE
Keyboard shortcut to launch apps

### ISSUE THREAD

**Issue by febcrash** [home-sweet-gnome/dash-to-panel#304]
Super+Number shortcut doesn't work every time.

**Comment by roberttaylor426** [comment]
Same here. In order to get it to work I have toggle the extension setting off and on again. The next time I login it will have reset itself once more. 

Something must be overriding the setting I guess, but I'm new to Gnome shell extensions so I'm fumbling around a bit at the moment.

**Comment by jderose9** [comment]
Any ideas, @franglais125 ?

**Comment by jderose9** [comment]
Are you guys on the latest Ubuntu? This seems like it may be the same issue as #281.

**Comment by anshuman73** [comment]
Yeah, same happens to me on Ubuntu 18.04
However, the hotkey shortcut seems to work EVERY time with the keyboard's numpad, whether or not the num lock is on or not. Maybe that overrides ?

**Comment by jderose9** [comment]
I believe @charlesg99 fixed this. Can you try the latest master?

**Comment by anshuman73** [comment]
Is there any way to like preserve my configuration ?
Basically, If I build from source using this - https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation , would it preserve my customization or erase the settings ?

Just asking, so that I'm cautious incase I have to redo the settings.

**Comment by anshuman73** [comment]
Oh, alright, @charlesg99 
I'll try that as a precautionary measure and try and confirm as soon as I can.

**Comment by anshuman73** [comment]
Hey, yes it works !
Thanks !
Just a feedback, the super + numpad is still functional, irrespective of whether or not the num lock is on or not. But I don't think that's a bug, just thought it's best I report it once.

**Comment by anshuman73** [comment]
Shouldn't this issue and #281  be closed ?
Or it's waiting for the official launch to go out on the gnome extensions ?

**Comment by charlesg99** [comment]
Thanks for the feedback!

**Comment by anshuman73** [comment]
@charlesg99 No problem at all !
I love this extension so much, this is the least I can do !
Thanks for putting in all the hardwork !

Also, just to put it down somewhere, installing from github did not change the settings !
