### ISSUE TITLE
feature request: disable app icons, set it to symbolic or use app names

### ISSUE THREAD

**Issue by impartof** [home-sweet-gnome/dash-to-panel#307]
Hi! may be this extension needs some features like:

1: `App names` instead `App icons` with separators between (dot, vertical line).
    When panel is small i prefer diasble icons. 

2: `Symbolic icons` instead `Normal icons`. 

3: Feature for disable: App icons (both 👀↑), App Names (useful, because we already can see running Apps (Super),: change app  (Alt+tab, Super+tab). 

4: change AppMenu button position to left side (if we have ApplicationsMenu, then after it)

Seems, Gnome will be more better with your extension and if Gnome developers add feature like  (Window > Menu) to (Panel > Appmenu) translater.

Thanks!

![hisll](https://user-images.githubusercontent.com/32578645/34434398-2353bea8-ecb0-11e7-9624-e62bd7548f30.png)

**Comment by hThoreau** [comment]
I would prefer to use symbolic icons.

**Comment by peejxyy** [comment]
i like this, where can i get this feature? i use dash to panel but there is no option to remove the icons, but i just want the text. it looks cleaner in my opinion
