### ISSUE TITLE
Statusbar lost after lockscreen

### ISSUE THREAD

**Issue by FarizInk** [home-sweet-gnome/dash-to-panel#313]
Before Lockscreen
![image](https://user-images.githubusercontent.com/20873955/34968011-2bd91536-fa99-11e7-8d83-edf8d7e78c83.png)

After Lockscreen (Open Desktop after lockscreen)
![image](https://user-images.githubusercontent.com/20873955/34968026-4a3912a6-fa99-11e7-84b5-212bfe9bec48.png)

OS : Ubuntu 17.10
Gnome : 3.26.2

**Comment by jderose9** [comment]
Thanks for the report! Does this happen every time you lock? Does it happen if you disable all other extensions? Does it happen if you disable ALL the extension including dash-to-panel? Thank you!
