### ISSUE TITLE
Application Menu Position

### ISSUE THREAD

**Issue by joca-bt** [home-sweet-gnome/dash-to-panel#321]
Would it be possible to add an option to move the application menu from the status menu (right side) to the taskbar (left side)? With the latest dev version it goes to the left side when the taskbar position is changed to the middle.

For example:
Application menu position:
- Left of taskbar
- Right of taskbar
- Left of status menu
- Right of status menu
- etc

However, with more and more options for positioning, we should of think of a better way to specify them.

**Comment by jderose9** [comment]
I agree - I think with the increasing number of elements that can be moved around, I'd rather not add dropdowns for every possible element, but rather have some sort of re-orderable list for the left, center and right portions of the panel. Also, some care would need to be taken to deal with other extensions that allow positioning adjustments on the panel (top icons plus, open weather, etc).

**Comment by joca-bt** [comment]
I have a suggestion on how it could look:

```
+------------------+
| Application Menu |
| Task Bar         |
|------------------|
|                  |
|------------------|
| Top Icons        |
| Status Menu      |
| Clock            |
+------------------+

[v] -------------------
    Centered in monitor
    Centered in content
```

**Comment by charlesg99** [comment]
Hello, new positioning options that should take care of this are now available on the master branch. Thanks!
