### ISSUE TITLE
appIcons.js related multiple crashes cause the whole system to freeze/stutter for a short time

### ISSUE THREAD

**Issue by craigacgomez** [home-sweet-gnome/dash-to-panel#338]
OS: Arch Linux x64 (All latest updates)
Kernel: 4.15.1-2-ARCH

Noticed this quite recently, after the updating to gjs 1:1.50.4-1 and it only affect a few applications. Chromium 64 has had the most noticeable issues, particularly when visiting websites like GitHub or pages with video content. Until the whole page is loaded, the entire system either completely freezes or slows down to a stutter, and when I look at the journalctl logs, I see a host of stack traces originating from appIcons.js.

Attached the contents of my journalctl logs for a period of about 9 seconds. The only action taken was clicking a link to a GitHub page, which opened Chromium, and then closing Chromium. The system was pretty much unusable for 5 of those 9 seconds.

Also attached screencaps of my Dash to Panel settings.

I tried the current stable version of Dash To Panel from the Gnome Extensions website, the latest release version from GitHub as well as master from Github (commit 998b66d). Tried with and with "Animations", never use "Window Previews"

Do not experience these issues if I disable Dash To Panel but i do love this extension!

[dash-to-panel-apppIcons-crash.log](https://github.com/jderose9/dash-to-panel/files/1707741/dash-to-panel-apppIcons-crash.log)
![dash-to-panel-settings-1](https://user-images.githubusercontent.com/1096710/35982870-bc7baeb2-0ce8-11e8-8eb3-9b08c060940e.png)
![dash-to-panel-settings-2](https://user-images.githubusercontent.com/1096710/35982875-be828bf4-0ce8-11e8-9a10-417d234c1bf0.png)
![dash-to-panel-settings-3](https://user-images.githubusercontent.com/1096710/35982882-c06d6bb4-0ce8-11e8-92f1-621c82d84401.png)

**Comment by charlesg99** [comment]
I experience this as well on gjs 1.50.4, but I do get different warning messages (from windowPreview.js) and my system doesn't freeze. Also, I do see the same kind of warnings even if dash to panel is disabled.

I personally decided to wait and see after the next gjs update. My temporary solution is to rollback to gjs 1.50.2:
 
`sudo pacman -U /var/cache/pacman/pkg/gjs-1:1.50.2-1-x86_64.pkg.tar.xz`
