### ISSUE TITLE
Make buttons clickable at the screen edge, when panel is at the bottom

### ISSUE THREAD

**Issue by dandrei** [home-sweet-gnome/dash-to-panel#340]
When the panel is on top, "Desktop" and "Application Menu" buttons are clickable at the top edge of the screen. They are not clickable when the panel is on the bottom. Is this something that can be addressed? Thanks.

**Comment by jderose9** [comment]
I'm not sure if I understand, but I don't think I've experienced this. Can you elaborate? Which theme are you using? If you are able to take a screen capture that shows the problem, that would be great. Thanks!

**Comment by dandrei** [comment]
Hi, thanks for your reply.

I'm running Ubuntu-based Pop!_OS 17.10 (Artful Aardvark).

In the attached screenshot, I marked the area where the mouse isn't active. It's a few pixels above the bottom edge of the screen.

When the panel is on top, there are no inactive pixels next to the top edge of the screen.

![screenshot from 2018-02-18 20-30-33](https://user-images.githubusercontent.com/350897/36355444-ee73078e-14eb-11e8-9d73-abd5747ba13e.jpg)

**Comment by jderose9** [comment]
Are you still experiencing this?

**Comment by ShivamSinghania** [comment]
I installed dash to panel today and experienced this problem. I have problem with 'show desktop' and 'Applications' buttons. When mouse pointer is at the left or right edge of screen, buttons aren't clickable (bottom edge works fine). Seems like the buttons are padded (just 1px) at the edge.

In extension settings I tried all sliders under "Position and style" and "fine tune" tabs but prolem still persists. Changing shell theme doesn't solve this either.

Screenshots:

Mouse pointer on Left edge of screen: Applications button doesn't get selected for click
![left edge](https://user-images.githubusercontent.com/30895841/43078012-be2ac8b6-8ea6-11e8-9520-26111afaa37c.png)
Just to the right of the left edge: works !
![beyond left edge](https://user-images.githubusercontent.com/30895841/43078009-bd53db08-8ea6-11e8-9e70-9d391dd01131.png)
Mouse pointer on Right edge of screen: show desktop button doesn't get selected for click
![right edge](https://user-images.githubusercontent.com/30895841/43078013-be71d472-8ea6-11e8-8b23-a0037b69bc71.png)
Just to the left of the right edge: works !
![beyond right edge](https://user-images.githubusercontent.com/30895841/43078010-bd9be7ae-8ea6-11e8-93a8-93642f724e57.png)
Bottom edge works.
![bottom edge](https://user-images.githubusercontent.com/30895841/43078011-bddeca2e-8ea6-11e8-857f-f742396ec7f9.png)

But corners don't work, I guess bcoz of left and right.

**Comment by charlesg99** [comment]
Hey ShivamSinghania, could you please tell us which theme you're using? Seems like it is defining some borders on both sides of the panel. We could override the theme's borders, but I don't think it is ideal. You could locally modify your theme yourself if you want. 

Unfortunately, I think that it isn't really a dash to panel issue. Even with the default gnome panel, this theme makes it impossible to click on the panel's sides (not sure if this is intended or not). Thanks.

**Comment by ShivamSinghania** [comment]
It's not a theme issue. I did reset theme settings to default to double check. No luck, problem still persists. Previously, in screenshots it's Arc-dark theme for applications and shell. everything else is default.

**Comment by charlesg99** [comment]
Hi, could you try the latest master? I'm also using Arc-dark and can't reproduce the issue. Thanks

**Comment by ShivamSinghania** [comment]
I just tried but no luck, problem persists. It's not related to the theme though, problem persists on both the default ubuntu theme and Arc-dark. Also, problem exists only in dash-to-panel extension, when I turn off this extension in gnome tweaks, everything is alright. 
Another thing I just noticed, when 'panel screen position' is set to 'Top', this issue is absent and edges and corners are perfectly clickable. Only 'bottom' creates this slight annoyance.

**Comment by charlesg99** [comment]
Do you mind providing your settings using `dconf dump /org/gnome/shell/extensions/dash-to-panel/`? Thanks

**Comment by ShivamSinghania** [comment]
Here you go

> $ dconf dump /org/gnome/shell/extensions/dash-to-panel/
[/]
dot-style-unfocused='DASHES'
app-hotkey-kp-7=['<Super>KP_7']
app-hotkey-kp-8=['<Super>KP_8']
app-hotkey-kp-9=['<Super>KP_9']
show-window-previews-timeout=50
secondarymenu-contains-showdetails=true
shift-click-action='MINIMIZE'
tray-size=0
show-show-apps-button=false
focus-highlight-color='#eeeeee'
app-hotkey-kp-10=['<Super>KP_0']
shift-middle-click-action='LAUNCH'
show-window-previews=true
show-activities-button=false
showdesktop-button-width=10
tray-padding=-1
enter-peek-mode-timeout=250
location-clock='STATUSRIGHT'
panel-position='BOTTOM'
app-shift-hotkey-kp-1=['<Shift><Super>KP_1']
app-shift-hotkey-kp-2=['<Shift><Super>KP_2']
app-shift-hotkey-kp-3=['<Shift><Super>KP_3']
app-shift-hotkey-kp-4=['<Shift><Super>KP_4']
app-shift-hotkey-kp-10=['<Shift><Super>KP_0']
app-shift-hotkey-kp-5=['<Shift><Super>KP_5']
app-shift-hotkey-kp-7=['<Shift><Super>KP_7']
app-shift-hotkey-kp-8=['<Shift><Super>KP_8']
app-shift-hotkey-kp-9=['<Shift><Super>KP_9']
show-appmenu=true
app-ctrl-hotkey-kp-10=['<Primary><Super>KP_0']
app-shift-hotkey-kp-6=['<Shift><Super>KP_6']
shortcut-text='<Super>q'
intellihide-animation-time=150
isolate-workspaces=false
shortcut=['<Super>q']
hot-keys=false
leftbox-size=0
panel-size=40
app-shift-hotkey-10=['<Shift><Super>0']
intellihide-behaviour='FOCUSED_WINDOWS'
show-showdesktop-button=true
window-preview-padding=5
show-favorites=true
group-apps=true
middle-click-action='LAUNCH'
status-icon-padding=-1
taskbar-position='CENTEREDMONITOR'
app-hotkey-10=['<Super>0']
app-ctrl-hotkey-1=['<Primary><Super>1']
app-ctrl-hotkey-2=['<Primary><Super>2']
app-ctrl-hotkey-3=['<Primary><Super>3']
app-ctrl-hotkey-4=['<Primary><Super>4']
app-ctrl-hotkey-5=['<Primary><Super>5']
app-ctrl-hotkey-6=['<Primary><Super>6']
app-ctrl-hotkey-8=['<Primary><Super>8']
app-ctrl-hotkey-9=['<Primary><Super>9']
app-hotkey-4=['<Super>4']
app-hotkey-2=['<Super>2']
app-hotkey-6=['<Super>6']
app-hotkey-7=['<Super>7']
app-hotkey-8=['<Super>8']
app-hotkey-9=['<Super>9']
app-hotkey-3=['<Super>3']
app-ctrl-hotkey-7=['<Primary><Super>7']
app-hotkey-5=['<Super>5']
app-hotkey-1=['<Super>1']
app-ctrl-hotkey-kp-4=['<Primary><Super>KP_4']
app-ctrl-hotkey-kp-1=['<Primary><Super>KP_1']
app-ctrl-hotkey-kp-2=['<Primary><Super>KP_2']
app-ctrl-hotkey-kp-3=['<Primary><Super>KP_3']
app-ctrl-hotkey-kp-8=['<Primary><Super>KP_8']
app-ctrl-hotkey-kp-5=['<Primary><Super>KP_5']
app-ctrl-hotkey-kp-6=['<Primary><Super>KP_6']
app-ctrl-hotkey-kp-7=['<Primary><Super>KP_7']
dot-color-1='#5294e2'
app-ctrl-hotkey-kp-9=['<Primary><Super>KP_9']
dot-color-3='#5294e2'
dot-color-2='#5294e2'
app-ctrl-hotkey-10=['<Primary><Super>0']
dot-color-4='#5294e2'
appicon-padding=1
intellihide-close-delay=500
intellihide-hide-from-windows=true
dot-color-unfocused-1='#5294e2'
dot-color-unfocused-2='#5294e2'
appicon-margin=0
dot-color-unfocused-3='#5294e2'
dot-color-unfocused-4='#5294e2'
intellihide=true
overlay-timeout=750
hotkeys-overlay-combo='TEMPORARILY'
dot-position='BOTTOM'
dot-style-focused='METRO'
hotkey-prefix-text='Super'
leftbox-padding=-1
multi-monitors=false
peek-mode-opacity=50
app-hotkey-kp-1=['<Super>KP_1']
app-hotkey-kp-2=['<Super>KP_2']
app-shift-hotkey-1=['<Shift><Super>1']
app-shift-hotkey-2=['<Shift><Super>2']
app-shift-hotkey-3=['<Shift><Super>3']
app-shift-hotkey-4=['<Shift><Super>4']
app-shift-hotkey-5=['<Shift><Super>5']
app-shift-hotkey-6=['<Shift><Super>6']
app-shift-hotkey-7=['<Shift><Super>7']
app-shift-hotkey-8=['<Shift><Super>8']
app-shift-hotkey-9=['<Shift><Super>9']
app-hotkey-kp-6=['<Super>KP_6']
app-hotkey-kp-3=['<Super>KP_3']
app-hotkey-kp-4=['<Super>KP_4']
app-hotkey-kp-5=['<Super>KP_5']

**Comment by charlesg99** [comment]
Can't reproduce it with your settings on ubuntu 18.04 using arc-dark or the default ambiance theme. Are you on ubuntu 18.04 as well?

**Comment by ShivamSinghania** [comment]
Yes, 18.04.1

**Comment by ShivamSinghania** [comment]
I switched to windows a few months ago, so 🤷‍♂️ .

**Comment by JoyceBabu** [comment]
@charlesg99  The issue is still not resolved. I am using latest Dash to Panel on `Pop!_OS 19.04` (`Ubuntu 19.04`)
