### ISSUE TITLE
Icons are not scaling

### ISSUE THREAD

**Issue by btxtiger** [home-sweet-gnome/dash-to-panel#364]
Icons in panel are not scaling with panel resize, but jumping between the embedded resolutions in the icon file. This is a problem, because on my HDPI screen, an optimal panel size is 54px. But in this setting, the icons are really small. Increasing the panel size to 55px, displays the next larger icon resolution, which is really too big for this panel size.

**Comment by charlesg99** [comment]
Hey btxtiger, could you please try the update on branch "appicons-padding" and see if the new  setting that adjusts the icons padding helps with this issue? Thanks!

**Comment by charlesg99** [comment]
The new setting has been merged to master. Feel free to reopen the issue if the scaling doesn't work as expected. Thanks!
