### ISSUE TITLE
[Feature request] Dynamic transparency with intellihide

### ISSUE THREAD

**Issue by nunocastromartins** [home-sweet-gnome/dash-to-panel#366]
This might be out of the scope of this extension, but seeing as the intellihide has recently arrived, and because [Dynamic Top Bar](https://extensions.gnome.org/extension/885/dynamic-top-bar/) seems to have some issues for me (hangs at times), I thought I'd ask for this feature here.

Since the logic required to know whether a window is overlapping the panel should already be implemented, I believe this shouldn't be very difficult to implement.

Please feel free to close the issue if you believe this issue to be out of this extension's scope.
Thank you for your work!

Pinging @charlesg99, since (to the extent of my knowledge) he implemented the intellihide feature.

**Comment by charlesg99** [comment]
Hey nunocastromartins, which gnome-shell version are you running? On 3.26+ the panel's dynamic transparency is a default behaviour and it is working well for me.

Maybe we could include a setting that would control if the dynamic transparency is applied or not, on all gnome-shell versions? I personally would make this option available even if the intellihide is disabled. What do you think? @jderose9 any thoughts?

**Comment by nunocastromartins** [comment]
Oh, my bad! I suppose I didn't properly explain the feature request!
I'm using `GNOME Shell 3.28.0`; the dynamic transparency behaviour effectively works for the default shell theme, but not for others (I'm using Arc Dark as the shell theme). The Dynamic Top Bar extension, as far as I can tell, supports the dynamic transparency for all themes.

However, seeing as the dynamic transparency seems to now be supported at the theme level, maybe I should move this discussion to the theme's repository. This might, after all, be out of scope for this extension. What are your thoughts?

**Comment by jderose9** [comment]
I use  [Dynamic Panel Transparency](https://extensions.gnome.org/extension/1011/dynamic-panel-transparency/). It is highly configurable and doesn't seem to have any conflict with this extension, so it has seemed to make sense to me to not duplicate effort within this extension.

You can read more here: #124

**Comment by charlesg99** [comment]
To add to what jderose9 said, I think it would be best if the themes themselves could include css styles to utilise the new native dynamic transparency mechanism, otherwise dash-to-panel would have to override the themes' css (as the other plugins already do) and I'm not sure this is desirable in all cases (say if a theme does provide the appropriate styles).

Basically, the panel is transparent by default and when it "senses" that a window is close enough, gnome-shell adds a `solid` css class that makes the panel become opaque. For example, here are the default theme styles:

Default transparent panel:
```
#panel {
  background-color: rgba(0, 0, 0, 0.35);
  /* transition from solid to transparent */
  transition-duration: 500ms;
  ... }
```
When a window is close enough, the panel has this `solid` class added, which makes it opaque:
```
  #panel.solid {
    background-color: black;
    /* transition from transparent to solid */
    transition-duration: 300ms; }
```

I checked arc-dark styles and it doesn't include a `solid` class, so it wont do anything when a window comes close to the panel.

Thanks

**Comment by nunocastromartins** [comment]
Sorry for the delay and thank you for your input on the matter.

@jderose9 I gave Dynamic Panel Transparency a try and I get the exact same issue with it as I get with Dynamic Top Bar: whenever I switch from a workspace with a maximised window to a workspace without one I get a slight (albeit annoying) hang.

This doesn't happen with either of those extensions disabled or with the default shell theme. There also doesn't seem to exist a conflict between them and this or any other extension that I'm using since I could reproduce the issue with all other extensions disabled. This likely means that the issue is on them and that I should (eventually) open an issue there.

Regarding this extension, whilst I agree with your reasoning about not wanting to duplicate effort, I wouldn't (as a user, of course) mind that this extension becomes a sort of monolithic extension for most things that are panel related. On another note, and I'm just _guessing_ here, the most difficult part should already be implemented with the intellihide feature: which I assume is knowing whether a window is inside the panel's area; maybe it's as easy as checking for the `solid` class as @charlesg99 mentioned, I really don't know. In any case, the side-effect of the argument of not wanting to duplicate effort might be that you have two extensions running duplicated (or at least similar) code because they require it for different reasons.

@charlesg99 I honestly agree with you, but that leaves the question of how to get the user-desired behaviour if the theme author is not interested in supporting the feature. As far as I know, themes have the problem that they aren't configurable; extensions are. My question is: _should_ this be supported here?

I'm not aware of how the currently existent extensions that provide the functionality that I desire are implemented; maybe they do not yet leverage the change introduced in newer Gnome versions that adds the `solid` class that you mentioned; if so, perhaps they should be updated. But my question still stands, and feel free to close this issue if the answer is negative: should Dash to Panel support this as a configuration option?

Regarding implementation details, setting and resetting `background-color: transparent;` should be compatible with most themes? It is likely the only way that doesn't require knowing the panel's background colour so there wouldn't be a need to try to obtain it first; it wouldn't be possible to specify the desired opacity, however, just `0%` or `100%` which although fine for my use-case, might not be for others'. I shouldn't dwell in implementation details of technologies that I'm not fully comfortable with, so I'll leave the solution to you if you plan on supporting this. :smile:

**Comment by charlesg99** [comment]
Hi @nunocastromartins, I know it's been a while but I just added dynamic transparency to the panels on branch "feature-multimon" (see #35 for more detail). Please let us know if this works on your end. Thanks!

**Comment by nunocastromartins** [comment]
Hi @charlesg99, thank you for the notice! I'm sorry but I'm no longer using this extension; please feel free to close this issue at your discretion. :)

**Comment by charlesg99** [comment]
Thanks
