### ISSUE TITLE
Custom "Show Applications Icon" adds new one on top of old one

### ISSUE THREAD

**Issue by mpkh** [home-sweet-gnome/dash-to-panel#371]
Custom "Show Applications Icon" does not replace default one so custom is placed on top of default one

**Comment by charlesg99** [comment]
Hey rkn, thank you for the report. Could you please provide more information? 

- what version of gnome-shell are you running? 
- what is the file type of the new icon (jpg, svg, etc.)?

Also, when you say "on top of default one", do you mean that your new icon is correctly positioned, but you can still see the default one "behind" the new one?

Thanks.

**Comment by rkn** [comment]
-  3.28
- png

yes, I see old one behind new one, I use git master of this extension

**Comment by charlesg99** [comment]
Are you using any other extensions that might affect the default icon? I'm also on gnome-shell 3.28 and I downloaded a transparent png to try, it is working as expected:

![image](https://user-images.githubusercontent.com/33044886/38101645-1e1a3a82-333e-11e8-9e91-fabf63139666.png)

Here is the png I'm using in the screenshot. Could you please try it and see if you get the same result as I am?
![start-here monochrome light](https://user-images.githubusercontent.com/33044886/38102173-b7aa7c60-333f-11e8-9dd9-f7370174b7cd.png)

Thanks

**Comment by charlesg99** [comment]
Hey mpkh, do you still have this issue? Thanks

**Comment by mpkh** [comment]
no, it's fixed now

**Comment by charlesg99** [comment]
Great, thanks for the feedback!
