### ISSUE TITLE
Middle-click on icon closes the window

### ISSUE THREAD

**Issue by eyome** [home-sweet-gnome/dash-to-panel#374]
Hi,

At the moment, middle-click on icon for an open window opens a new instance. Could you add an option which allows to close this window with a middle-click on icon?
Thank you for your work.

**Comment by charlesg99** [comment]
Hey eyome, could you please try the latest master and see if this option works for you (dash to panel settings -> "Behavior" tab -> gear button next to "Click action") ?

![image](https://user-images.githubusercontent.com/33044886/39587354-4ec6983e-4ec7-11e8-927f-cefe40be2efa.png)

Thanks

**Comment by eyome** [comment]
Yeah, it works like a charm :D.
Thank you for your contribution!
