### ISSUE TITLE
"Require pressure" intellihide setting - issue when modifying multi-monitor display arrangement

### ISSUE THREAD

**Issue by aspurdy** [home-sweet-gnome/dash-to-panel#379]
Hi,

When changing the display arrangement of a multiple monitor setup in gnome settings the "pressure" region doesn't seem to stay attached to the primary monitor. 

In my case, if I swap the logical positions of my primary and secondary monitors the pressure region gets swapped to the secondary screen. 

Placing the mouse at the edge of the second monitor causes the slide-up animation to play on the primary monitor, then the panel hides itself again. Restarting gnome-shell with Alt-F2 r seems to fix things, the pressure region becomes active on the primary monitor again. 

Thank you for creating this extension!

**Comment by charlesg99** [comment]
Hey aspurdy, thanks for the report. Indeed, the primary monitor used to set the intellihide reveal mechanism is only assigned once when starting gnome shell... I was hoping to avoid putting too much code binding the intellihide behaviour to the primary monitor since we are planning to support multi monitor panels, which will render this added code useless. 

Seems like this is worth adding after all :) Thanks.

**Comment by charlesg99** [comment]
Could you please try the latest master and see if that solves the issue? Thanks

**Comment by aspurdy** [comment]
Hi Charles,

Thank you for your quick reply. I tried the latest master but unfortunately the issue seems to persist.

Sorry if my initial explanation was unclear, I was not changing the primary monitor, just the arrangement of the two monitors. In my case, I don't think `Main.layoutManager.primaryIndex` would change, but `Main.layoutManager.primaryMonitor.x` would. I assume the pressure barrier would need to be reinitialised in this case too.

I tried tweaking a few things myself, I modified the `monitors-changed` callback to call `_restart()` unconditionally. Unfortunately that did not seem to work: after changing the primary monitor or modifying the monitor layout the pressure barrier becomes unresponsive. However, if I go into gnome-tweak-tools and toggle the "Panel Intellihide" switch (the old try turning it off and on?) everything seems to work. Restarting gnome shell has the same effect.

I'm fine with these workarounds if you are planning on larger changes to support multiple monitors.

**Comment by charlesg99** [comment]
Haaa, sorry I misunderstood... I'll investigate further when I get back home in front of my 2 monitors (~April 20th), as I'm currently shooting in the dark from my laptop :) Thanks!

**Comment by charlesg99** [comment]
Hi aspurdy, sorry for the delay, I'm finally in front of my 2 monitors and I was able to reproduce what you described. Could you please update to the latest master and see if that fixes the issue? Thanks!

**Comment by aspurdy** [comment]
Just had a chance to try the latest master and everything seems to be working now. Thank you for your help!

**Comment by charlesg99** [comment]
Great! Thanks for the feedback.
