### ISSUE TITLE
Icon theme not applied

### ISSUE THREAD

**Issue by usharf** [home-sweet-gnome/dash-to-panel#382]
I've noticed recently that the chosen 3rd party icons theme (Papirus) is not applied any more, but defaults to the standard for my distro (Fedora 27). It'll be applied when I reselect this theme, but will revert to the default when system restarted.

NB the icons are applied everywhere else, only not in the panel.

**Comment by charlesg99** [comment]
Hey usharf, thank you for the report! Could you please provide more information? Which dash-to-panel version are you using? Does it happen with every panel sizes? Do you have the same result with other 3rd party icon themes? Thanks

**Comment by usharf** [comment]
Hi there! I've since upgrade to Fedora 28 (test days)... and I'm not seeing this issue currently. I'll re-open if I do. Thanks!
