### ISSUE TITLE
[feature-request] hide/blacklist windows from taskbar/panel

### ISSUE THREAD

**Issue by didrip** [home-sweet-gnome/dash-to-panel#383]
Would it be possible to be able to blacklist some windows so their icons are not visible ?

For example I use an youtube app for music (Headset) which uses two windows but only one is useful and the other is hidden (it is mandatory for Youtube API use to have a window showing the video). Therefor 2 icons are shown but one is useless.

**Comment by charlesg99** [comment]
Hello monkeydri, thank you for the suggestion. When you say 2 windows/2 icons, what is the difference between them? Is it the same application? How would you distinguish between these 2 windows? Sorry I don't know Headset. Thanks!
