### ISSUE TITLE
Updated translations for v14

### ISSUE THREAD

**Issue by jderose9** [home-sweet-gnome/dash-to-panel#385]
If anyone would like to submit updated translation, I plan to release v14 in about a week. As always, thanks so much!!

@frnogueira @zeten30 @franglais125 @LaurentTreguier @SolarLiner @elsieholmes @hosiet @jonnius @urbalazs @pappfer @crayxt @pkomur @AlexGluck

**Comment by SolarLiner** [comment]
I'm on it!

**Comment by zeten30** [comment]
@jderose9  please review https://github.com/home-sweet-gnome/dash-to-panel/pull/380 before I'll start work on v14. Thanks in advance

**Comment by jonnius** [comment]
#390 done

**Comment by urbalazs** [comment]
Hungarian translation is done in https://github.com/home-sweet-gnome/dash-to-panel/pull/392

**Comment by pkomur** [comment]
#401 Polish translation done.

**Comment by AlexGluck** [comment]
#422 Russian translation done.

**Comment by charlesg99** [comment]
Thanks!
