### ISSUE TITLE
HiDPI: AppIcon scaling issue with 200% scaling

### ISSUE THREAD

**Issue by mweirauch** [home-sweet-gnome/dash-to-panel#387]
It seems the AppIcon size is twice the size as it should be. Dunno if the Panel itself is supposed to be that big at this "resolution".
* 14" 2560x1440 scalled 200% so effectively 1280x720 "appearance"
* gnome-shell: 3.26.2
* dash-to-panel: git@6a21b1e0caa5ac5debafaf45226c1368a4977a44 (v13+)
* usually running with more extensions but kept disabled for sanity (e.g. system-monitor)
![dtp-appicon-scaling-hidpi](https://user-images.githubusercontent.com/1134031/39376852-6a011642-4a53-11e8-9b77-68609af5dd4b.png)

Disclaimer: I am not an active dash-to-panel user. Just try it from time to time. (Still using TaskBar due to some missing features I got used to.)

**Comment by charlesg99** [comment]
Hi mweirauch, thank you for the report, I could reproduce the issue. Could you please pull master and see if the latest commit fixes the issue? Thanks

**Comment by mweirauch** [comment]
Wow, thanks! I assume this looks as it should?
![dtp-appicon-scaling-hidpi-fixed](https://user-images.githubusercontent.com/1134031/39381811-b17e8fe4-4a63-11e8-8fd1-22dfdc84b80f.png)

**Comment by charlesg99** [comment]
Thanks for the feedback, this looks right to me :)
