### ISSUE TITLE
Drag&drop adds existing panel applications to favorites

### ISSUE THREAD

**Issue by spantaleev** [home-sweet-gnome/dash-to-panel#391]
When you've got an application open in the panel, if you drag it a bit and drop it, it will be added to favorites.
You don't even need to drag it out of the panel and back in. You just need to drag it slightly and it will trigger.

Because of this, I find myself frequently adding my open applications to Favorites by mistake.

Is this an intentional feature?

**Comment by charlesg99** [comment]
Hi spantaleev and thank you for the report. Are you using the "ungroup application" option? Seems like the drag and drop isn't synchronised correctly when the appicons also have the window title. Thanks!

**Comment by spantaleev** [comment]
@charlesg99, yes, I'm using the "Ungroup applications" option.

I can confirm that the problem isn't there with that option turned off.

**Comment by charlesg99** [comment]
Hey spantaleev, would you mind trying the fix on branch "fix-appicon-drag"? This should resolve the issue and also prevent the window previews from staying on screen after a drag & drop. Thanks!

**Comment by spantaleev** [comment]
@charlesg99, I can confirm that it's fixed in `fix-appicon-drag`.

I didn't have previews enabled, so I never saw an issue with them. But I enabled them now and it seems like they work well (they don't get stuck on screen).

Seems like it's all good. :+1: 

Thank you!

**Comment by charlesg99** [comment]
Great, thanks for testing it! The fix was merged to master.
