### ISSUE TITLE
Incorrect icon displayed in panel

### ISSUE THREAD

**Issue by milankni** [home-sweet-gnome/dash-to-panel#393]
Hi,

There is some default placeholder icon

![screenshot-20180430-190413-2560x1440](https://user-images.githubusercontent.com/937861/39439897-6a756b70-4ca9-11e8-8833-d20995e29702.png)

displayed for Joplin desktop application https://github.com/laurent22/joplin/releases run from AppImage container (on the first run, it asks the user if he wants the desktop integration).

The rest of the Gnome shows the icon properly (menu). The icon appimagekit-joplin.png is stored in $HOME/.local/icons/... in two sizes.

The desktop file:
```
[Desktop Entry]
Name=Joplin
Comment=Joplin for Desktop
Exec="/home/u/AppImg/Joplin-1.0.83-x86_64.AppImage" %U
Terminal=false
Type=Application
Icon=appimagekit-joplin
X-AppImage-Version=1.0.83.444
X-AppImage-BuildId=70246000-383e-11a8-1b18-0d992d6d5f1a
Categories=Office;
X-Desktop-File-Install-Version=0.23
X-AppImage-Comment=Generated by /tmp/.mount_JoplinRjioEO/AppRun
TryExec=/home/u/AppImg/Joplin-1.0.83-x86_64.AppImage
```

**Comment by jderose9** [comment]
This is typically caused by the running window not being associated with the appplication. You can verify by disabling this extension and examining whether the same behavior occurs in the left dash in the Activies Overview screen.

To resolve, you need to define the StartupWMClass in the desktop file. You can use the command `xprop WM_CLASS` and then click on the problematic window to find the proper name to use.

**Comment by milankni** [comment]
The problem also exists in Activities Overview with DashToPanel disabled.

`StartupWMClass=Joplin` resolved the problem for both.

Thanks!

P.S. Would you consider this a bug to be reported to Joplin upstream (to include WM Class)?

**Comment by charlesg99** [comment]
I would mention it to Joplin as it is an easy fix... Thanks!

**Comment by milankni** [comment]
Already reported here:
    https://github.com/laurent22/joplin/issues/338
which appears to be dependent on:
    https://github.com/electron-userland/electron-builder/issues/2098
