### ISSUE TITLE
How to configure extension by the CLI?

### ISSUE THREAD

**Issue by in-in** [home-sweet-gnome/dash-to-panel#394]
I installed extension by the command line
```bash
sudo apt install gnome-shell-extension-dash-to-panel
```
But I can't configure it the same way.  

I can customize the original dash this way:
```bash
gsettings set org.gnome.shell.extensions.dash-to-dock dash-max-icon-size 32
```

But I can't do it for dash-to-panel:
```bash
~|⇒ gsettings set org.gnome.shell.extensions.dash-to-panel taskbarPosition CENTEREDMONITOR
No such schema “org.gnome.shell.extensions.dash-to-panel”
```

I see the extension in Tweaks
![7c3e4](https://user-images.githubusercontent.com/8797432/39495632-b817cd1e-4da3-11e8-91e1-5811ad2f11e7.png)

But don't see in _dconf_
![8e3f0](https://user-images.githubusercontent.com/8797432/39495678-eec0cabe-4da3-11e8-8321-4b43e9ccc351.png)

Only after I changed some parameters in Tweaks, _dash-to-panel_ will appear in _dconf_. But only the changed options.
![57744](https://user-images.githubusercontent.com/8797432/39495803-93d1ebb4-4da4-11e8-8308-5be6df1c6ed8.png)

![c2fa3](https://user-images.githubusercontent.com/8797432/39495862-d5053c3a-4da4-11e8-88f1-5f4736f9eadb.png)

And _dconf_ also cannot recognize the schema
![61e68](https://user-images.githubusercontent.com/8797432/39495909-1191fde6-4da5-11e8-81c4-cdcc61d3fbad.png)

>gnome-shell: 3.28.1
gnome-shell-extension-dash-to-panel: 13-1
gnome-tweaks: 3.28.1
dconf-editor: 3.28.0
ubuntu: 18.04 (in Virtualbox)

**Comment by in-in** [comment]
I think I found that the problem was. The schema file is in the wrong directory.
```bash
sudo cp /usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/schemas/ /usr/share/glib-2.0/schemas/ &&
sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
```

from here: https://askubuntu.com/questions/490939/configure-gnome-shell-extensions-from-command-line/491224#491224

And now I can configure dash-to-panel  through the _dconf_
![6ce63](https://user-images.githubusercontent.com/8797432/39678503-c5120100-5196-11e8-9046-0455e8d94add.png)

**Comment by jderose9** [comment]
Thanks for doing the research. Unfortunately, unless I am misunderstanding, I don't think there's any action we can take on this end. A release is provided to GNOME Extensions as a zip file which is then delivered and unpacked via chrome-gnome-shell or gnome software. There's no opportunity to place files in a system folder (and I assume the proper target location would be distro-specific).

**Comment by in-in** [comment]
How do other extensions get to the system folder?
When I install these extensions:
```bash
sudo apt install gnome-shell-extension-dash-to-panel gnome-shell-extension-dashtodock gnome-shell-extensions
```
Their schemas are located in `/ usr / share / glib-2.0 / schemas /` except _dash-to-panel_

![b2e90](https://user-images.githubusercontent.com/8797432/39770076-b29c17de-52f6-11e8-87e7-4d71d89849be.png)

I also tried three different ways to install `dash-to-panel`:

- from `apt-get` (above)
- manual, from Github https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation
- from this page https://extensions.gnome.org/extension/1160/dash-to-panel/

The same result every time

**Comment by charlesg99** [comment]
I looked at [how dash to dock is doing that](https://github.com/micheleg/dash-to-dock/commit/4dd565dad920ce44303635b550a39bbdbe34fb70#diff-b67911656ef5d18c4ae36cb6741b7965) and I ported the solution on branch "system-wide-install". 

Could you please pull that branch and then try this command from your repo directory?
`sudo make DESTDIR=/ install`

Thanks!

**Comment by in-in** [comment]
After these actions:
```bash
git clone -b system-wide-install https://github.com/jderose9/dash-to-panel
cd dash-to-panel
sudo make DESTDIR=/ install
```
The extension stops loading and still does not appear in _dconf_

![571f0](https://user-images.githubusercontent.com/8797432/39810136-94e818aa-538c-11e8-81b1-3ee3b1d67874.png)

**Comment by charlesg99** [comment]
Could you please look at your log using `journalctl /usr/bin/gnome-shell -f -o cat` while you're trying to enable the extension? 

I did some tests and if I remove the dash-to-dock file from `/usr/share/glib-2.0/schemas`, no matter how I try to install it (apt, extensions.gnome.org, make), the schema doesn't go back there. Then the same problem occurs in dconf:
![image](https://user-images.githubusercontent.com/33044886/39815890-755428be-5367-11e8-9ba4-69704dc1885e.png)

Still doesn't explain how it got there in the first place, unless it comes pre-installed with ubuntu (as the ubuntu-dock). Thanks.

**Comment by jderose9** [comment]
For both extensions, ubuntu is sourcing the package from debian. I'm not familiar with their package configuration format, but there seems to be a line copying the schema out for dash-to-dock, that doesn't exist in dash-to-panel.

https://gitlab.com/highvoltage/gnome-shell-extension-dashtodock-packaging/blob/master/debian/install

The maintainer is the same for both packages, so I would suggest reaching out to him to see if the package can be updated to match the dash-to-dock configuration (and perhaps if he needs us to tweak anything on this end, he can provide guidance on that).

Also, just for the sake of clarity, I wanted to mention that this won't really help installation from other sources - I assume dash-to-dock schema wouldn't be found in dconf had the extension been installed from e.g.o rather than apt.

**Comment by in-in** [comment]
> Could you please look at your log using journalctl /usr/bin/gnome-shell -f -o cat while you're trying to enable the extension?


```bash
GNOME Shell started at Wed May 09 2018 16:02:29 GMT-0400 (EDT)
Extension "dash-to-panel@jderose9.github.com" had error: Error: Schema org.gnome.shell.extensions.dash-to-panel could not be found for extension dash-to-panel@jderose9.github.com. Please check your installation.
JS ERROR: Exception in callback for signal: extension-state-changed: Error: Schema org.gnome.shell.extensions.dash-to-panel could not be found for extension dash-to-panel@jderose9.github.com. Please check your installation.
getSettings@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/convenience.js:85:15
_enable@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:79:16
_emit@resource:///org/gnome/gjs/modules/signals.js:128:27
logExtensionError@resource:///org/gnome/shell/ui/extensionSystem.js:152:5
enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:134:9
onEnabledExtensionsChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:279:9
onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:276:5

```

**Comment by jderose9** [comment]
> Hey @jderose9, thanks for the insight. Do you know what is the purpose of the "system-wide installation" mentioned here? Is it useful in dash to panel or should I scrap that?

It looks like this was done by an Ubuntu dev to support installation into the system level folders (rather than under the user's home folder). The debian package configuration seems to be doing the same thing basically, but I can't figure out whether it's actually using that flag in the Makefile.

It might be easiest to see if we can just get the debian package maintainer to chime in. I just sent him an email.

**Comment by jderose9** [comment]
Jonathan responded and said that he would update the debian package configuration soon to copy the schema out.

**Comment by highvoltage** [comment]
"Uploading gnome-shell-extension-dash-to-panel_14-1_amd64.changes"
^^^ That fixes this issue and should be synced to ubuntu too later today (although a backport would be nice if someone has the time for that)

**Comment by charlesg99** [comment]
Thanks a bunch @highvoltage!

**Comment by BoQsc** [comment]
This Issue still exists in the 19.10 and latest dash to panel.
