### ISSUE TITLE
[Feature Request] Move window to current workspace

### ISSUE THREAD

**Issue by ddnexus** [home-sweet-gnome/dash-to-panel#395]
When you are peeking a window on a different workspace, it would be nice to have a way to move it to the current workspace.

It would be a lot more practical than just _going_ to its workspace on click... or opening the overview and find it again to move it to the current workspace.

**Comment by jlemonde** [comment]
It's a fact that pretty much every one is using workspaces a different way. I wouldn't use that feature, but it seems important and pertinent to me to implement that. Maybe could it be great to add that to the possible actions of the middle click on an icon...

**Comment by charlesg99** [comment]
Hello, this feature was added to master with the new window previews. Please try them out. Thanks!
