### ISSUE TITLE
tray icons not working after restart

### ISSUE THREAD

**Issue by ProLejka** [home-sweet-gnome/dash-to-panel#399]
Ubuntu 18.04
When you enable dash-to-panel all tray icons are there. But after restart none are shown. When you disable dash-to-panel they are still missing. After restart they are working again when dash-to-panel is off.

**Comment by charlesg99** [comment]
Hi ProLejka, which version of dash to panel are you using? If you're not on the latest master, would you mind giving it a try and see if the issue persists? Thanks!

**Comment by ProLejka** [comment]
Dash-to-Panel
Version: 13 (a460d2828ac38b27b7688115910f6eb6b9f274a3)

**Comment by ProLejka** [comment]
Hi. Sorry for late response.
It looks like it fixed it.
Thank you
