### ISSUE TITLE
[Feature request] Activities button placement and appearance

### ISSUE THREAD

**Issue by JohannesKahl** [home-sweet-gnome/dash-to-panel#400]
If there's any interest to implement this, i thought it would be nice to be able to set the activites button placement optionally after the applications one, eventually style it directly (without the need to use other extensions) to show a custom icon.
What do you think?

**Comment by kowalski7cc** [comment]
I have some ideas in my mind. I'll post some mockups later...

**Comment by kowalski7cc** [comment]
What do think about this mockup?
![mockup](https://user-images.githubusercontent.com/5065094/78299523-5dc38580-7536-11ea-8eb5-9d02492a8789.png)

**Comment by kowalski7cc** [comment]
Just thought `view-more-horizontal-symbolic` could be used for this task

**Comment by tmfksoft** [comment]
This looks great, for those like myself who use the ungroup feature to display window titles it helps avoid using even more space.
