### ISSUE TITLE
Desktop icons get positioned outside of the screen when the extension is enabled

### ISSUE THREAD

**Issue by conradus** [home-sweet-gnome/dash-to-panel#406]
I'm using version 13 of dash to panel extension, gnome 3.28.

Whenever I enable the extension, the desktop icons are positioned outside of the screen, as shown by the prints below. New icons are created outside of the screen as well, it seems like the location of the "screen" for desktop purposes was displaced a little above the real screen.

![01](https://user-images.githubusercontent.com/13765567/39822660-84d60892-5381-11e8-8e38-ec65cc49cccb.jpg)
![02](https://user-images.githubusercontent.com/13765567/39822661-850c47a4-5381-11e8-8d41-256a7ddffde5.jpg)

**Comment by jderose9** [comment]
Hello, thanks for reporting this! My understanding is that desktop icon support was removed from GNOME in 3.28. What are you using to provide this feature? Thank you!

**Comment by conradus** [comment]
Thanks for the quick reply! Ubuntu 18.04 uses a customized version of Gnome 3.28, and in the same configuration screen that is shown in my prints, the last option (Área de Trabalho, which means Desktop) has a toogle for desktop icons.

**Comment by ddnexus** [comment]
@conradus: FYI you don't need Frippery Move Clock if you use Dash To Panel. ;)

**Comment by jderose9** [comment]
> Thanks for the quick reply! Ubuntu 18.04 uses a customized version of Gnome 3.28, and in the same configuration screen that is shown in my prints, the last option (Área de Trabalho, which means Desktop - although the word wasn't exactly translated to Portuguese in this case) has a switch for enabling desktop icons.

Thanks for explaining! I made a fresh installation of Ubuntu 18.04 in Boxes and can't seem to reproduce the issue. Could you try disabling all other extensions, restart gnome shell, and see if the issue still occurs?

![screenshot from 2018-05-10 13-13-51](https://user-images.githubusercontent.com/2118702/39903326-aa682372-54a0-11e8-9982-2f35c9044b7b.png)

**Comment by charlesg99** [comment]
Just adding to what jderose9 said, I also can't reproduce this on a fresh Ubuntu 18.04 install. Thanks!

**Comment by ddnexus** [comment]
I remember I saw that glitch on U-18.04, but now I can't get it anymore. Maybe some extension, or a different setting combination.

**Comment by conradus** [comment]
Well, my conclusion is that the desktop icon functionality provided by Nautilus is totally broken, and that's why they removed it from Gnome 3.28. So, I installed Nemo file manager (which, by the way, is exponentially better than the new version of Nautilus, which was totally dumbed down - shame!) and used the tip from https://askubuntu.com/questions/980855/make-nemo-produce-desktop-icons-gnome-3-26-1-on-ubuntu-17-10 to make Nemo draw the Desktop icons from now on. Problem solved!

**Comment by charlesg99** [comment]
Hey conradus, are you using 2 monitors? If so, you might have the same issue as reported in #421. A fix was just added to master (thanks to @jamesst20 for identifying the cause), could you try it and see if it helps? Thanks!
