### ISSUE TITLE
Overview Hot Corner enabled at start

### ISSUE THREAD

**Issue by ddnexus** [home-sweet-gnome/dash-to-panel#407]
The Tweak tool > Top Bar has the option to disable the "Activities Overview Hot Corner". If you disable it while DtP is enabled, it will work as expected, but as soon as you restart the shell or disable and re-enable DtP the Hot Corner will be enabled again (even if the option is still disabled in the Tweek tool).

Disable DtP and the Hot Corner will be disabled again, showing that DtP is just enabling it on its own.

**Comment by charlesg99** [comment]
Hey ddnexus, thank you for reporting this, I could reproduce the issue on ubuntu. Could you please pull master again and see if the latest commit fixes it on your end? Thanks!

**Comment by ddnexus** [comment]
Yup! It fixed it! Thanks for the fast action!

**Comment by AddisonG** [comment]
A [StackOverflow issue](https://askubuntu.com/questions/1033739/activities-corner-keeps-re-enabling-itself/1149223), possibly related to this bug. Hoping for an officially supported release soon.
