### ISSUE TITLE
Panel can be hidden if leftBox is too large

### ISSUE THREAD

**Issue by freeroot** [home-sweet-gnome/dash-to-panel#408]
Hello,

I opened a PR (#405) , I don't know if open an issue is necessary so I open one now for better discussion.

---

Because I'm using both _Dash to Panel_ and _No Title Bar_, I can have very long leftBox while I'm in CENTEREDMONITOR option. So, when it's so long, when leftBox reaches centerBox, the centerBox is moved to the right to let leftBox occupies all the space it want to. My centerBox, with my dash in panel, can even be hidden by the rightBox.

To avoid this, I fix centerBox in its place when CENTEREDMONITOR option is checked.

Before:
 ![capture du 2018-05-08 16-31-06](https://user-images.githubusercontent.com/20989929/39763427-54e1aac8-52dd-11e8-8685-0ad0647640ab.png)

After:
![capture du 2018-05-08 16-26-45](https://user-images.githubusercontent.com/20989929/39763426-5488f798-52dd-11e8-8889-2d04914c6eba.png)

**Comment by jderose9** [comment]
Thanks @freeroot. No problem, just needed a chance to review. Looks good to me - Thanks for contributing!
