### ISSUE TITLE
Overlay S/C should reveal panel on intellihide 

### ISSUE THREAD

**Issue by alex285** [home-sweet-gnome/dash-to-panel#409]
**Reproduce:**
1. Set Panel on Intellihide mode
2. Press Super+q to get numbers overlay

**Outcome:**
Panel stays hidden so you cannot actually see the shortcuts

**Expected:**
On Super+q panel should reveal (if hidden)

**Comment by charlesg99** [comment]
Hey alex285, thanks for the report. 

I agree that the panel should be revealed while the hotkeys overlay is on screen, but I'm unclear on what should happen if a user selects the option to always show the hotkeys overlay? To be consistent, we would need to completely disable the intellihide in that case. What do you think?

**Comment by alex285** [comment]
Hello,
to me seems sufficient and natural to bring the panel up when you press Super+q (or whatever s/c) for a certain amount of time (eg 3sec) for those who have set overlay numbers always visible

Moreover it may be a good idea to reveal the panel even on Super+Num, but that might be annoying in cases

**Comment by charlesg99** [comment]
Could you please pull/install the update on branch "show-panel-on-hotkeys" and see if that behavior is what you had in mind? Thanks!

**Comment by alex285** [comment]
Wow that was fast! Thank you!

I was sure that Super+q should reveal the panel, but I wasn't so sure if Super+Num should do the same! Now I'm trying it, it feels very expected behavior, without being annoying! I need to use it in a everyday natural way to give a better feedback, but I can already say it is super cool!

If you guys push that in master though, it would be a good idea to add an option on this on Advanced Hotkey Options, just for the people who want a bit less distraction (I'm definitely not one of them!)

**Comment by alex285** [comment]
That's a bit irrelevant, but since Dash To Panel has many options already, perhaps it needs some re-design, with a sidebar with more items, and less buttons that open dialogs as it is now, including a search too maybe. Even if use Dash To Panel a lot, i really find hard to navigate into options!

If you agree on that, and it consider it is doable (eg time), I could at least try make some mockups

**Comment by jderose9** [comment]
I also thought that the taskbar shouldn't come up on application launch, but after using it, I think the explicit visual feedback makes sense. I think we can release v14 with this behavior and see what sort of feedback comes in before adding additional settings.

@alex285 I do agree the Settings could be improved, and a search sound like a great idea. It's not high priority for me right now, though. If you want to mock something up or throw out some ideas in a new issue, please go for it, with the caveat that it might not get actually implemented in the near feature. (Of course, someone else may want to do the work).

**Comment by charlesg99** [comment]
Thank you for the feedback! I kind of went with the idea "when you reveal the hotkeys, you reveal the taskbar". I'm not really using the hotkeys so I'm definitely not the best to provide good usability feedback. Please let me know if, after using it, you think it would be better to only reveal the taskbar on "Super-q" (minor change). Thanks

**Comment by jderose9** [comment]
@charlesg99  Are we good to merge this? I'd like to include it in v14 if possible.

**Comment by charlesg99** [comment]
@jderose9 Yeah I think we're good, I just merged it. Thanks!
