### ISSUE TITLE
Icons size is too small

### ISSUE THREAD

**Issue by fthx** [home-sweet-gnome/dash-to-panel#413]
Hi Charles,

Since latest git (v. 14) I dowloaded yesterday I get very small apps icons in taskbar, e.g. size=29.
In version 13, there is no issue. In my previous version (git from maybe 1 or 2 weeks) it was ok too.

**Comment by charlesg99** [comment]
Hey fthx, thank you for the report. Maybe this is because of the new appicon padding setting? What happens if you set the padding to 0px? This is what I'm seeing with size 29:

![image](https://user-images.githubusercontent.com/33044886/40234449-e7f8e06c-5a74-11e8-855a-c93d4c226a28.png)

Thanks!

**Comment by fthx** [comment]
Oh yes I missed it completely ! Thanks !
Do you think that the default padding value could be lower than 4 ?
(The icons scaling is now very good, much better than before. Or my eyes are tired and nothing was done here ?)

**Comment by jderose9** [comment]
@fthx Could you post a screenshot of what you are seeing at 4px? Are you using window scaling? I'm wondering if the padding is getting multiplied more than once or something.

**Comment by fthx** [comment]
size=28, padding=4
![image](https://user-images.githubusercontent.com/23138504/40238691-3939a7c4-5ab4-11e8-8f84-cd1df8c996f3.png)
size=28, padding=0
![image](https://user-images.githubusercontent.com/23138504/40238731-5726ab24-5ab4-11e8-9959-ceefd558f06c.png)

**Comment by fthx** [comment]
no window scaling, FHD display

**Comment by charlesg99** [comment]
Yeah, I understand that it might change the look of existing dtp users panels if they had set a different panel size before the v14 update. The default 4px padding was chosen because it most resembles the look of the default panel size setting of 48px without the new padding setting. Thanks.

**Comment by charlesg99** [comment]
> (The icons scaling is now very good, much better than before. Or my eyes are tired and nothing was done here ?)

Glad you noticed :) Thanks
