### ISSUE TITLE
Disabling extension does not place app menu in native place

### ISSUE THREAD

**Issue by fthx** [home-sweet-gnome/dash-to-panel#414]
Hi Charles,

Yes I know that I should not try to disable this extension. :-)

But if I do so, the GS app menu in topbar is left centered instead of left-packed.
My DtP config places apps icons in the content center, it seems that the native app menu keeps on following this setting and stays here when disabling, just on the left of the date/time.

![image](https://user-images.githubusercontent.com/23138504/40266193-31a06654-5b47-11e8-81b3-d27b1d2c8c40.png)

**Comment by fthx** [comment]
All is ok now, great !

**Comment by charlesg99** [comment]
Thanks for the feedback! The fix is now on master.
