### ISSUE TITLE
[Design] Simplify Intelli-hide Options

### ISSUE THREAD

**Issue by alex285** [home-sweet-gnome/dash-to-panel#416]
Hello @jderose9 @charlesg99 

On https://github.com/home-sweet-gnome/dash-to-panel/issues/409#issuecomment-388545152 I said that I want to work on re-designing the Panel Preferences by introducing a sidebar. I will start with some mockups, and in case you will accept them, I will try (hopefully!) to PR the changes

But before I want to discuss some current options that I feel they bring unnecessary complexity without clear benefits. In particular I want to revisit some of Intelli-hide options

![screenshot from 2018-05-22 18-11-46](https://user-images.githubusercontent.com/11244308/40371649-9e9122de-5deb-11e8-8297-eee35e170cd5.png)

## 1. Pressure Sensitivity should not be an option
Panel should be invoked only with Pressure Sensitivity and not just by placing the cursor on the edge of the screen. The last behavior only leads to "accidentally" triggers

By doing so, we simplify options (by removing a switch), we make easier for users to find what they are looking for, plus we provide a better UX in actual use

Moreover we don't need `Trashehold` & `Timeout`. Those should be identical to default Shell Hot Spot values. In case we want such an option, it should also affect the Shell Top-Left Corner, to provide a consistent experience, and it should be a global preference and not inside intelli-hide

## 2. On Full Screen Mode
`Hide and reveal animation duration` & `Delay before hiding the panel`perhaps is better to be removed. We can have values that are very close to "optimal", and I can't think of any use case that someone wants to change those. Btw I think what Panel has now  {200,400} is already fine
___
All options I'm asking for removal will be obviously still accessible via GSetttings, but I believe Dash To Panel can provide a better usability if we remove those from the preferences interface, without sacrificing anything in real use. 

**I just bring this up for discussion & feedback!**

**Comment by charlesg99** [comment]
Hey Alex, I'm gonna close this as the pressure sensitivity option was useful to someone after all :) See #749. Thanks!
