### ISSUE TITLE
Option to hide apps text labels on hover ?

### ISSUE THREAD

**Issue by fthx** [home-sweet-gnome/dash-to-panel#418]
Hi Charles,

Would it be possible to make an option to remove this : 
![image](https://user-images.githubusercontent.com/23138504/40468470-d10a607a-5f2d-11e8-8178-ca7c9ecce9fe.png)
?
You will notice that the text is quite blurry too :-) .

Additionally, don't you find that the "Advanced Options" button  in prefs looks somewhat odd since there is only one option available ?

**Comment by jderose9** [comment]
The tooltip a GNOME default behavior and is styled by your theme. It's not a lot of effort to allow it to be disabled, but I agree with the Settings getting increasingly crowded... any thoughts on where it should go? Maybe it is time to re-organize?

Advanced options is basically "don't touch this unless you are having a specific reason to do so and know what you are doing". In a perfect world, it probably wouldn't exist at all.

**Comment by nealot** [comment]
I think placing it below "Show window previews on hover" as "Show tooltip on hover" would be a good choice. The tooltips are pretty inconvenient if your panel is at the top, since they usually obscure browser tab names.

**Comment by charlesg99** [comment]
Hi guys, this option was added to master, let us know if it works for you! Thanks!

**Comment by nealot** [comment]
I can verify that it works as intended on my machine. Thank you!

**Comment by charlesg99** [comment]
Great, thanks!
