### ISSUE TITLE
DtP removes the "barrier" in screen corners

### ISSUE THREAD

**Issue by Wuestengecko** [home-sweet-gnome/dash-to-panel#420]
I have to monitors side by side, with the left one being the main monitor with the top bar. In plain GNOME, when I move the mouse pointer along the top edge of the left monitor, it gets stuck right in the corner before going over to the second monitor.

When I enable this extension however, this behavior is removed, and the pointer will just fly out of the screen. This means I can no longer aimlessly throw my mouse into the top right corner to find the close button. (I also have "No title bar" active, which moves the close button into the top bar.)

This might seem like a niche request, but I really got used to this convenience. Please look into it, and re-enable the corner barriers (or make them configurable)!

**Comment by charlesg99** [comment]
Hey Wuestengecko, thank you for the report. I never noticed that stock gnome had this right hand side barrier, but I also find it useful now that I restored/played with it (especially with the show destkop button). I'm just wondering if we should add an option for it or simply restore it. Also, I'm not sure about what should happen when the panel is hidden from intellihide. Any thoughts? @jderose9 
Thanks!

**Comment by jderose9** [comment]
I removed the barrier intentionally. Once the panel is moved to the bottom, a large invisible barrier existed at the top that trapped the mouse.

Looking now at Windows 10, there is a barrier at both the top and bottom between monitors, but it is very small (just a few pixels). Maybe we can model this behavior? I'm not opposed to a config setting (adjustable barrier height of 0 to whatever px, maybe?), but if we can get away without one, I think it's probably one of those things that would be better to just work as expected out of the box.

**Comment by charlesg99** [comment]
That makes sense. I also think a smaller barrier would be perfect for most people as it helps to quickly reach the corner without being in the way. I pushed a tryout version on branch "right-barrier", the barrier should follow the panel to the bottom and its size is currently set to 10px. Please let know what you think. Thanks

**Comment by Wuestengecko** [comment]
For me the 10px barrier is just perfect.

I can imagine a large barrier really getting in the way if it has the size of the panel, as this extension does have a quite large default size (similar to Windows 7+). But I also think that a small barrier in the top corners is useful even with the panel at the bottom (or hidden at the top), if only for finding a close button easier.

That said, I should add that I got really confused a few times when I first started using Windows 10 - I did accidentally close windows more than one time due to this. So, making it configurable surely wouldn't hurt. ;)

**Comment by jderose9** [comment]
I think the 10px barrier is great! Thanks @charlesg99 . Hopefully it will be a subtle enough change that it doesn't require even more sliders in the settings :). I might prefer an even smaller barrier (5px?) but not enough to complain if everyone else is happy with it.

I'm also wondering if a top right barrier when the panel is in the bottom position would be useful, for closing maximized applications?

**Comment by charlesg99** [comment]
Great, I've merged it to master, thanks for the feedback. 

I think a top barrier would be useful when the panel is at the bottom, but I wonder if it would be appropriate since it is "outside" of the panel. People might get confused as to where this barrier is coming from if it annoys them. Then again, creating a separate extension just for this purpose seems overkill :)

**Comment by jderose9** [comment]
Yeah, it's weird because stock gnome does have a top-right barrier, but it doesn't have a barrier near the maximized window close button which is now at the top right once the panel is moved. Overall, I guess it does feel out-of-scope and should probably be discussed separately (and include a config setting if it is implemented). I think we can close this one for now if everyone else is good with it. Thanks guys!

**Comment by charlesg99** [comment]
Thanks
