### ISSUE TITLE
Ubuntu 18.04 : Desktop icons disapear when using a monitor

### ISSUE THREAD

**Issue by jamesst20** [home-sweet-gnome/dash-to-panel#421]
Hi,

I currently have a fresh install of Ubuntu 18.04 on my Lenovo Thinkpad E280.

I installed the latest v14 (also tried v13) and for some reasons, as soon as I enable Dash-To-Panel, my desktop icons simply disapear. As soon as I disable it again they come back.

In the mean time I must open a file manager window to be able to see my desktop icons.

** Please note, the issue is only presents when I connect an external monitor on my laptop

Thank you

**Comment by jamesst20** [comment]
After digging a little more.. it seems like the icons are following exactly the primary screen position in Monitors settings.

![capture d ecran de 2018-06-02 20-54-44](https://user-images.githubusercontent.com/490234/40882148-36a35e02-66a7-11e8-9b40-c0596a62293e.png)

**Comment by charlesg99** [comment]
Hey jamesst20, thanks for the report! I never heard of this issue before gnome 3.28 where ubuntu had to restore this functionality. Does it also happen when you set dash to panel to the top position? Thanks!

**Comment by jamesst20** [comment]
Thank you!

It does not happen when the panel is at the top, I just tried! But I must admit I love it much more at the bottom :)

Is it something that you are able to fix easily?

**Comment by charlesg99** [comment]
Hi James! I think I found a workaround, could you please try the latest master and see if that fixes the issue on your end? Thanks!

**Comment by jamesst20** [comment]
Hi,

The issue is almost perfectly solved !

Case 1 : Internal Monitor & External monitor : 1920x1080
100% perfect, icons always in the primary screen perfectly placed.

However, it is only fine after we press "Confirm Changes". Doesn't really matter, but here are image describing what I mean.

Before clicking 'Keep changes'
![capture d ecran de 2018-06-03 23-13-33](https://user-images.githubusercontent.com/490234/40896644-31eeaf1e-6784-11e8-8b28-877e3a4b919a.png)

After clicking 'Keep changes' everything is perfect.
![capture d ecran de 2018-06-03 23-13-40](https://user-images.githubusercontent.com/490234/40896649-3551290c-6784-11e8-868c-220568ada310.png)


Case 2 : Internal Monitor 1920x1080, External monitor 4k resolution

The bug mentioned in case 1 does not seems to occur, however icons are displayed on the secondary monitor

![capture d ecran de 2018-06-03 23-13-04](https://user-images.githubusercontent.com/490234/40896685-6d21d804-6784-11e8-9be3-98b23b904b6f.png)

**Comment by charlesg99** [comment]
Hey James, thank you for the feedback. Yes unfortunately we can only readjust when the "confirm changes" is pressed because this is when gnome-shell "notifies" us that the monitors configuration has been changed. As for case 2, do you have the same result if you disable dash to panel and use the default top bar? Thanks
