### ISSUE TITLE
Urgent !!!

### ISSUE THREAD

**Issue by LinxGem33** [home-sweet-gnome/dash-to-panel#423]
hi  @jderose9  @charlesg99 

ive just been deleting my repos as im migrating to GitLab and one of my repos held some artwork for your landing page and just by chance i realised as when i clicked on your repo that some artwork might be pointing to this repo so i advise you to check just in case before i delete it, i have now re uploaded this repo (its called Neon) for you to double check that nothing is pointing to this repo on your landing page.

kind regards - LinxGem33

**Comment by charlesg99** [comment]
Hey LinxGem33, thank you for the heads up! I've quickly looked at the landing page and everything seems to be correctly pointing to the dash to panel repo. jderose9 can confirm this, but to me it looks like you could complete your migration. Thanks!

**Comment by jderose9** [comment]
Yup, thanks for checking (and for the design work!) @LinxGem33, but there are not any references to your repos at this time.

**Comment by LinxGem33** [comment]
thanks for the reply ill close this repo soon as i only have a couple of repos left to migrate to GitLab. 

ps. ill close this issue now :)
