### ISSUE TITLE
How to remove/hide left one dock?

### ISSUE THREAD

**Issue by omkarnathsingh** [home-sweet-gnome/dash-to-panel#424]
![screenshot from 2018-06-08 13-39-09](https://user-images.githubusercontent.com/12734027/41147008-cac18eae-6b22-11e8-85eb-771d7a0f8d6b.png)

Refer above image, I dont like 2 docks. Please tell how to remove left one. 
OS: Ubuntu 18.04 
Thanks.

**Comment by Wuestengecko** [comment]
The left dock doesn't look like it comes from DtP, but rather some Unity-esque extension shipped with Ubuntu. Please install the `gnome-tweak-tool` and check if there are any other extensions active that might be doing this.

**Comment by omkarnathsingh** [comment]
![image](https://user-images.githubusercontent.com/12734027/41158997-9b5f64c6-6b48-11e8-9279-6ae59ca68461.png)
 Is this correct?

**Comment by omkarnathsingh** [comment]
sudo apt remove gnome-shell-extension-ubuntu-dock

This helped me. 

Thanks devs who is make this.

**Comment by jderose9** [comment]
Glad you got your issue resolved! The Ubuntu dock should be disabled automatically on the latest version, though.
