### ISSUE TITLE
Panel layout got messed up

### ISSUE THREAD

**Issue by Wuestengecko** [home-sweet-gnome/dash-to-panel#425]
Previously, my top panel looked like this, which is similar to (but not quite) stock GNOME, and I was totally happy with it:
![statusbar-before](https://user-images.githubusercontent.com/1579756/41158628-e9028be6-6b29-11e8-823b-6396d377efba.png)

Commit 74161cd changed some inner workings of the positioning options, which messes with the layout:
![statusbar-after](https://user-images.githubusercontent.com/1579756/41158673-1f3bae0e-6b2a-11e8-9720-2cfb4bd5b977.png)

I also observed the applications button ("Anwendungen") wandering off to the right side of the panel, just left of the clock in the second screenshot, after some time of being logged in. Restarting Gnome Shell resets it. I never actually saw it going there, I only realized that it was there suddenly when trying to click it.

In DtP settings, "clock position" is set to "left of the status menu", and "Application bar position" is set to "Left side of the panel". None of the positioning options restore the positions seen in the first picture. The only way to get back to the previous state is to revert 74161cd (or checkout just before it).

## Environment

Arch Linux w/ Gnome 3.28.2
Full list of active Gnome extensions:

* AlternateTab
* Applications menu (the "Anwendungen" button)
* Dash to Panel
* Drop Down Terminal
* No title bar (the X in the far right)
* No topleft hot corner
* Removable drive menu (not visible in screens, but stays to the right of Topicons afaict)
* Topicons (Keepass icon)

A little bit of random testing with different combinations didn't show any change, which is expected as DtP is the only one that actually changes the layout instead of just adding new buttons.

All extensions except DtP either shipped or installed from extensions.gnome.org.

**Comment by charlesg99** [comment]
Hey Wuestengecko, thank you for reporting this! I will have a look, seems like I didn't correctly restore the positions when disabling the extension. Is this accurate? You only get the incorrect positioning after disabling dash to panel and restarting gnome shell correctly resets the layout? Thanks!

**Comment by Wuestengecko** [comment]
No, not when disabling - both screenshots were made with DtP enabled. Disabling correctly restores the stock layout, with the clock in the center of the screen.

This happened after I updated dash to panel from 796814a (first screenshot) to a0f0217 (second shot) The relevant change was made in commit 74161cd.

Restarting Gnome shell mostly has no effect, except when - for whatever reason - the applications button had jumped over the right side. THEN it resets that button to the left side, but not the outermost corner (where I want it), but only as seen in the second screenshot.

**Comment by Wuestengecko** [comment]
These changes look good, the positioning is just like before again. Thanks for the quick fix! :)
