### ISSUE TITLE
[Feature request] Shortcut to access app by "right click"

### ISSUE THREAD

**Issue by varsop** [home-sweet-gnome/dash-to-panel#426]
Currently I am able to launch an app by primary click via keyboard. I am able to control the click action. Is it also possible to launch an app via keyboard as I would perform a right click on the icon?  

PS: My current workaround is like this: give keyboard focus to the top bar (Ctrl + Alt + Tab), use arrow keys to navigate, hit Shift + F10 for right click or use the appropriate key on keyboard.

**Comment by jderose9** [comment]
There's actually an open issue to address this (#142), but I wasn't aware of the Ctrl-Alt-Shift behavior. We definitely should add additional key bindings to launch the application easily in this mode. I'm going to close this one in favor of the existing issue, but thanks very much for letting us know.
