### ISSUE TITLE
[Feature request] Keybinding to trigger panel show/hide

### ISSUE THREAD

**Issue by thatside** [home-sweet-gnome/dash-to-panel#428]
First of all thanks for your work - it's really impressive!
I was using HideTopBar extension previously with DashToPanel, but now it works for me with only latter one. The only feature I'm missing is showing the panel with a keypress (for me it was Meta + Q) - just to peek the clock or notifications.

**Comment by charlesg99** [comment]
Hey thatside, if you enable the hotkeys (under the "Behavior" tab in settings), you should be able mimic the HideTopBar feature by setting the "shortcut to show the overlay" (by default it is Super + q). Thanks!

**Comment by thatside** [comment]
Also if "Number overlay" option is set to "Never" you are unable to show the panel with a shortcut - it simply doesn't work.

**Comment by thedonquixotic** [comment]
I agree this would be a nice feature to have.

**Comment by charlesg99** [comment]
Hi, a specific intellihide setting was added to master. Thanks!
