### ISSUE TITLE
Crashes since last upgrade [Ubuntu 18.04, Gnome 3.28]

### ISSUE THREAD

**Issue by ponchofiesta** [home-sweet-gnome/dash-to-panel#430]
Since the last upgrade of dash to panel extension it often crashes. I have to reload gnome shell and it starts again.
If there is any debug log please tell me and I will post it here.

Ubuntu 18.04 with Gnome 3.28

**Comment by charlesg99** [comment]
Hi ponchofiesta, you can run `journalctl /usr/bin/gnome-shell -f -o cat` in a terminal and try to see if there is a dash to panel error when the crash occurs. Thanks!

**Comment by borgdylan** [comment]
```Extension "dash-to-panel@jderose9.github.com" had error: TypeError: ubuntuDock.stateObj is undefined
JS ERROR: Exception in callback for signal: extension-state-changed: TypeError: ubuntuDock.stateObj is undefined
_enable@/home/dylan/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:59:1
_emit@resource:///org/gnome/gjs/modules/signals.js:128:27
logExtensionError@resource:///org/gnome/shell/ui/extensionSystem.js:152:5
enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:134:9
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:171:17
callback@resource:///org/gnome/shell/ui/extensionDownloader.js:264:17
gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13

JS ERROR: Exception in callback for signal: extension-state-changed: TypeError: ubuntuDock.stateObj is undefined
_enable@/home/dylan/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:59:1
_emit@resource:///org/gnome/gjs/modules/signals.js:128:27
logExtensionError@resource:///org/gnome/shell/ui/extensionSystem.js:152:5
enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:134:9
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:171:17
callback@resource:///org/gnome/shell/ui/extensionDownloader.js:264:17
gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13

JS ERROR: Exception in callback for signal: extension-state-changed: TypeError: ubuntuDock.stateObj is undefined
_enable@/home/dylan/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:59:1
_emit@resource:///org/gnome/gjs/modules/signals.js:128:27
logExtensionError@resource:///org/gnome/shell/ui/extensionSystem.js:152:5
enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:134:9
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:171:17
callback@resource:///org/gnome/shell/ui/extensionDownloader.js:264:17
gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13

JS ERROR: Exception in callback for signal: extension-state-changed: TypeError: ubuntuDock.stateObj is undefined
_enable@/home/dylan/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:59:1
_emit@resource:///org/gnome/gjs/modules/signals.js:128:27
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:177:5
callback@resource:///org/gnome/shell/ui/extensionDownloader.js:264:17
gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13

JS ERROR: Exception in callback for signal: extension-state-changed: TypeError: ubuntuDock.stateObj is undefined
_enable@/home/dylan/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:59:1
_emit@resource:///org/gnome/gjs/modules/signals.js:128:27
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:177:5
callback@resource:///org/gnome/shell/ui/extensionDownloader.js:264:17
gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13

JS ERROR: Exception in callback for signal: extension-state-changed: TypeError: ubuntuDock.stateObj is undefined
_enable@/home/dylan/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:59:1
_emit@resource:///org/gnome/gjs/modules/signals.js:128:27
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:177:5
callback@resource:///org/gnome/shell/ui/extensionDownloader.js:264:17
gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13```

**Comment by borgdylan** [comment]
I had to enable the uninstall dash to panel, enable ubuntu dock, then install dash to panel again to get it to work. I am using the stock Gnome on Xorg seesion.

**Comment by ponchofiesta** [comment]
Looks like this is the same as @borgdylan said.
```
Extension "dash-to-panel@jderose9.github.com" had error: TypeError: overview is null
Extension "dash-to-panel@jderose9.github.com" had error: TypeError: ubuntuDock.stateObj is undefined
...
Extension "dash-to-panel@jderose9.github.com" had error: TypeError: ubuntuDock.stateObj is undefined
```

**Comment by esserrge** [comment]
This happens to me every time I wake my laptop (Lenovo Thinkpad T460s) from sleep, on Ubuntu 18.04 LTS, Xorg, Gnome 3.28.1. 


Archive:  /tmp/OXODLZ.shell-extension.zip                                         
   creating: /home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/cs/
   creating: /home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/es/LC_MESSAGES/
   creating: /home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/schemas/    
   creating: /home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/pt_BR/LC_MESSAGES/
  inflating: /home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/schemas/gschemas.compiled
  inflating: /home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/overview.js
  inflating: /home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/ru_RU/LC_MESSAGES/dash-to-panel.mo
  inflating: /home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/hu/LC_MESSAGES/dash-to-panel.mo
  inflating: /home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/intellihide.js     
   creating: /home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/ru/LC_MESSAGES/
  inflating: /home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/windowPreview.js
  inflating: /home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/pl/LC_MESSAGES/dash-to-panel.mo
  inflating: /home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/uk/LC_MESSAGES/dash-to-panel.mo
   creating: /home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/de/LC_MESSAGES/
  inflating: /home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/Settings.ui
  inflating: /home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelStyle.js      
  inflating: /home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/fr/LC_MESSAGES/dash-to-panel.mo
   creating: /home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/cs/LC_MESSAGES/
  inflating: /home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/img/highlight_stacked_bg.svg
  inflating: /home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/stylesheet.css
  inflating: /home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/cs/LC_MESSAGES/dash-to-panel.mo
  inflating: /home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/ru/LC_MESSAGES/dash-to-panel.mo
  inflating: /home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/de/LC_MESSAGES/dash-to-panel.mo
  inflating: /home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/convenience.js
  inflating: /home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/pt_BR/LC_MESSAGES/dash-to-panel.mo
  inflating: /home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/kk/LC_MESSAGES/dash-to-panel.mo
  inflating: /home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/README.md
  inflating: /home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/zh_CN/LC_MESSAGES/dash-to-panel.mo
  inflating: /home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/es/LC_MESSAGES/dash-to-panel.mo
  inflating: /home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panel.js           
  inflating: /home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js
  inflating: /home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/taskbar.js
  inflating: /home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/prefs.js
  inflating: /home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/COPYING
  inflating: /home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/schemas/org.gnome.shell.extensions.dash-to-panel.gschema.xml
  inflating: /home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js
 extracting: /home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/metadata.json
Extension "dash-to-panel@jderose9.github.com" had error: TypeError: ubuntuDock.stateObj is undefined
JS ERROR: Exception in callback for signal: extension-state-changed: TypeError: ubuntuDock.stateObj is undefined
_enable@/home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:59:1
_emit@resource:///org/gnome/gjs/modules/signals.js:128:27
logExtensionError@resource:///org/gnome/shell/ui/extensionSystem.js:152:5
enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:134:9
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:171:17
callback@resource:///org/gnome/shell/ui/extensionDownloader.js:264:17
gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13

JS ERROR: Exception in callback for signal: extension-state-changed: TypeError: ubuntuDock.stateObj is undefined
_enable@/home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:59:1
_emit@resource:///org/gnome/gjs/modules/signals.js:128:27
logExtensionError@resource:///org/gnome/shell/ui/extensionSystem.js:152:5
enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:134:9
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:171:17
callback@resource:///org/gnome/shell/ui/extensionDownloader.js:264:17
gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13

JS ERROR: Exception in callback for signal: extension-state-changed: TypeError: ubuntuDock.stateObj is undefined
_enable@/home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:59:1
_emit@resource:///org/gnome/gjs/modules/signals.js:128:27
logExtensionError@resource:///org/gnome/shell/ui/extensionSystem.js:152:5
enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:134:9
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:171:17
callback@resource:///org/gnome/shell/ui/extensionDownloader.js:264:17
gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13

JS ERROR: Exception in callback for signal: extension-state-changed: TypeError: ubuntuDock.stateObj is undefined
_enable@/home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:59:1
_emit@resource:///org/gnome/gjs/modules/signals.js:128:27
logExtensionError@resource:///org/gnome/shell/ui/extensionSystem.js:152:5
enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:134:9
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:171:17
callback@resource:///org/gnome/shell/ui/extensionDownloader.js:264:17
gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13

JS ERROR: Exception in callback for signal: extension-state-changed: TypeError: ubuntuDock.stateObj is undefined
_enable@/home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:59:1
_emit@resource:///org/gnome/gjs/modules/signals.js:128:27
logExtensionError@resource:///org/gnome/shell/ui/extensionSystem.js:152:5
enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:134:9
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:171:17
callback@resource:///org/gnome/shell/ui/extensionDownloader.js:264:17
gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13

JS ERROR: Exception in callback for signal: extension-state-changed: TypeError: ubuntuDock.stateObj is undefined
_enable@/home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:59:1
_emit@resource:///org/gnome/gjs/modules/signals.js:128:27
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:177:5
callback@resource:///org/gnome/shell/ui/extensionDownloader.js:264:17
gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13

JS ERROR: Exception in callback for signal: extension-state-changed: TypeError: ubuntuDock.stateObj is undefined
_enable@/home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:59:1
_emit@resource:///org/gnome/gjs/modules/signals.js:128:27
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:177:5
callback@resource:///org/gnome/shell/ui/extensionDownloader.js:264:17
gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13

JS ERROR: Exception in callback for signal: extension-state-changed: TypeError: ubuntuDock.stateObj is undefined
_enable@/home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:59:1
_emit@resource:///org/gnome/gjs/modules/signals.js:128:27
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:177:5
callback@resource:///org/gnome/shell/ui/extensionDownloader.js:264:17
gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13

JS ERROR: Exception in callback for signal: extension-state-changed: TypeError: ubuntuDock.stateObj is undefined
_enable@/home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:59:1
_emit@resource:///org/gnome/gjs/modules/signals.js:128:27
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:177:5
callback@resource:///org/gnome/shell/ui/extensionDownloader.js:264:17
gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13

JS ERROR: Exception in callback for signal: extension-state-changed: TypeError: ubuntuDock.stateObj is undefined
_enable@/home/srg/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:59:1
_emit@resource:///org/gnome/gjs/modules/signals.js:128:27
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:177:5
callback@resource:///org/gnome/shell/ui/extensionDownloader.js:264:17
gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13

**Comment by mati865** [comment]
Version v15 seems not to crash anymore.

**Comment by esserrge** [comment]
Yes v15 seems to work, have had 0 crashes since updating and I had a 100% crash rate on laptop wakeup on v14. Thanks!

**Comment by ponchofiesta** [comment]
With new version no crashes so far
