### ISSUE TITLE
[Feature request]  Media controls on window preview

### ISSUE THREAD

**Issue by rafaelmardojai** [home-sweet-gnome/dash-to-panel#431]
This can be a nice feature to have.
Em—Dash (https://github.com/tliron/em-dash) has something similar.

![windows](https://user-images.githubusercontent.com/6210397/41558915-141ed574-7308-11e8-901e-f7889fd844e1.png)

**Comment by thedonquixotic** [comment]
Plus one from me!

**Comment by HandsMaluman** [comment]
There's a gnome extension that does this as an indicator button. 
https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button
Maybe the creator would be interested in supplying his code to Dash-to-panel if that's feasible

**Comment by jdbeitz** [comment]
+1
