### ISSUE TITLE
"Show Applications" icon missing with update to version 15

### ISSUE THREAD

**Issue by Gi60s** [home-sweet-gnome/dash-to-panel#432]
**Issue Description**

I updated to version 15. Immediately after I noticed:

- The "Show Applications" button is missing its icon.
- The button still works although the hit box is not as wide.
- The button does not have a hover state like the rest of the icons do.

**Troubleshooting Done**

- Disabled and then enabled the plugin (no change).
- Logged out and then logged in (no change).

**Reference Image**

See the bottom left corner of this image:

![dash-to-panel](https://user-images.githubusercontent.com/714117/42229920-df1e287c-7ea4-11e8-820f-10035f28412a.png)

**Comment by Gi60s** [comment]
I haven't set a custom icon, but I did find where that is at in the settings. It looks to me that the current icon is set to none. I also noticed while playing with these settings that the "Show Desktop Button" also does not have an icon. Is it supposed to?

Clicking reset did not change anything.

I'm happy to go find the icon on my computer's hard drive, although I'm not sure where it is located.

Thanks for the help.

![dash-to-panel-behavior](https://user-images.githubusercontent.com/714117/42389927-7b8a6fd6-8107-11e8-9ba1-18f901273349.png)

**Comment by charlesg99** [comment]
What theme are you using? Seems like the default icon (view-app-grid-symbolic) isn't available. Do you have the same result if you try a different theme? Thanks

**Comment by Gi60s** [comment]
Are you referring to the theme set in tweaks? It says "Adwaita". Changing the theme or icons doesn't make it reappear.

Also, I don't know how this affects things, but I'm running [Ubuntu Gnome 16.04](https://ubuntugnome.org/).

![tweaks-theme](https://user-images.githubusercontent.com/714117/42415215-62018eac-8204-11e8-89d0-54827ba33d9b.png)

**Comment by jderose9** [comment]
@charlesg99 Looks like this icon is actually called `view-grid-symbolic` in Gnome 3.18 and earlier.

**Comment by charlesg99** [comment]
Ha that makes sense, thanks for your insight @jderose9. Gi60s, could you please install the latest master and see if the fix solves this issue?

**Comment by Gi60s** [comment]
I could have done this wrong. I've never installed an extension from github directly. Here is what I did:

1. Downloaded a zip
2. Opened Tweaks and chose the "None" button at the bottom to select the zip file.
3. Logged out and in.

It's getting this error:

```
GLib.FileError: Failed to open file '/home/james/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/schemas/gschemas.compiled': open() failed: No such file or directory

Stack trace:
  getSettings@/home/james/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/convenience.js:79
  Settings<._init@/home/james/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/prefs.js:148
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  _Base.prototype._construct@resource:///org/gnome/gjs/modules/lang.js:110
  Class.prototype._construct/newClass@resource:///org/gnome/gjs/modules/lang.js:213
  buildPrefsWidget@/home/james/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/prefs.js:1303
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:95
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:259
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397
  @<main>:1
  
```

**Comment by charlesg99** [comment]
I don't think you can install an extension this way. Please see [this page](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github) for the correct way to install from github. If you don't have/want git, just extract the zip you previously downloaded, cd into the "dash-to-panel-master" folder (coming from the zip), then run "make install" and restart gnome-shell as stated in the link above. Thanks.

**Comment by Gi60s** [comment]
Ah, thank you for the instruction. I'll try that and post an update.

**Comment by Gi60s** [comment]
OK, that did install the panel successfully, but the icon is still missing. On the up side, there is now a hoverable area. Also, I don't think that the "Show Applications" menu used to show on hover. I did reset the application icon to default too.

![master-1](https://user-images.githubusercontent.com/714117/42586868-49a4b934-84f6-11e8-9741-777ad6acce00.png)

**Comment by jderose9** [comment]
Looks like on a fully-updated 16.04 system, Config.PACKAGE_VERSION is '3.18.5'.

**Comment by charlesg99** [comment]
Sorry about that, my bad. Please update again, it should work correctly now. Thanks

**Comment by Gi60s** [comment]
It works! Well done.

Thank you both for working through this issue. I'll leave this issue open in case you want to do anything else before closing it.

Also, I'd like to know when https://extensions.gnome.org/ has the updated copy too.

Thanks again.
