### ISSUE TITLE
D2P is broken on GNOME 3.30 | global.screen is undefined

### ISSUE THREAD

**Issue by alex285** [home-sweet-gnome/dash-to-panel#434]
Hello! This is a bit early but Dash To Panel doesn't work on GNOME Shell 3.29.3. 

It throws 
```
Extension "dash-to-panel@jderose9.github.com" had error: TypeError: global.screen is undefined
``` 
And it now only places panel on bottom
![screenshot from 2018-07-11 15-14-22](https://user-images.githubusercontent.com/11244308/42570846-e8156ec0-851d-11e8-869d-97795a04fb88.png)

I think the problem is on [**Remove usage of MetaScreen** commit](https://gitlab.gnome.org/GNOME/gnome-shell/commit/47ea10b7c976abb1b9ab4f34da87abb1e36855fe) in GNOME Shell

**Comment by franglais125** [comment]
Have a look at this PR from dash-to-dock: https://github.com/micheleg/dash-to-dock/pull/770 (thanks to @3v1n0 )

**Comment by alex285** [comment]
@franglais125 thanks for the PR link! I patched DtP similar, but for some reason JHbuild Shell now crashes (even without the extension enabled) and i cant fix it :( I will wait till Fedora29 (im using) to push 3.29.3 and retest

**Comment by jderose9** [comment]
Thanks for the heads up. I'll work on this. Are you using Rawhide?

**Comment by alex285** [comment]
@jderose9 yes, but not sure what happened with my JHBuild and crashes now. I rebuild everything! And it was a golden opportunity for my first patch :(

**Comment by jderose9** [comment]
@alex285 Looks like Rawhide repos have 3.29.4 now. Did you want to take a stab at it?

**Comment by alex285** [comment]
@jderose9 actually im just about! got it last night!

**Comment by cnd** [comment]
maybe you know working topicons plus alternative too?

**Comment by jderose9** [comment]
@cnd Does this one work?
https://extensions.gnome.org/extension/615/appindicator-support/

**Comment by 3v1n0** [comment]
@jderose9 yes, no changes involved there.

**Comment by horvathz** [comment]
Just a simple patch. It works with 3.29.4. And it breaks 3.28.x of course.

**Comment by vans163** [comment]
I love Gnome, like a fully automatic shotgun, hang up API, close eyes, spray shells, open eyes, ++ major version, release.

**Comment by 3v1n0** [comment]
@horvathz Using a wrapper like done in https://github.com/micheleg/dash-to-dock/pull/770 will keep compatibility with both.

It can be cleaner, but that's the fastest and simplest solution ;-)

**Comment by Prototik** [comment]
@jderose9 You forgot to import imports.gi.Meta in latest 6206195 commit. It still doesn't work on 3.30 without it.

**Comment by jderose9** [comment]
@Prototik Thank! Give it a shot now. I believe everything should be working with 3.30 as expected.

**Comment by Prototik** [comment]
@jderose9 yeah, with fixed import it works like a charm.
