### ISSUE TITLE
do not change pane on tray icon mouse hover

### ISSUE THREAD

**Issue by monkeydri** [home-sweet-gnome/dash-to-panel#435]
when clicking a tray icon the corresponding pane opens (volume, network, power...).

Hovering over other tray icons switches to the corresponding pane, without requiring a click on it. If find it very annoying (I often use a touchpad) and it would be nice to at least have an option for disabling this.

dash-panel v1.5
ubuntu 18.04

*I did not tested this on standard gnome so I do not know if this is the default behaviour.*

**Comment by thedonquixotic** [comment]
It is standard behavior. And I agree it's a little bit difficult to use. I often will accidentally trigger opening a different pain as I move my mouse up to interact with my intended pane.

**Comment by jderose9** [comment]
Can you clarify which icons are opening on hover?

**Comment by charlesg99** [comment]
Hi, this is something that was annoying me as well, but not enough to have me look into it until now... An option to prevent this native behavior was added to master, can you try it and see if that solves the issue? The new option can be found under the "fine-tune" tab. Thanks!

**Comment by wiktor-k** [comment]
:thinking: I didn't know I need this feature before I saw this bug, it's excellent :clap: 

Toggling the checkbox in fine-tune didn't work immediately for me but after a restart it works like a charm, perfect, thanks!

**Comment by monkeydri** [comment]
Thanks @charlesg99  and sorry for the super-late reply, this is awesome !
