### ISSUE TITLE
Possibility of reordering window titles in "ungroup application" mode

### ISSUE THREAD

**Issue by MikeShysh** [home-sweet-gnome/dash-to-panel#436]
Hi,

Ubuntu 18.04
Dash to panel 3.28

STR:
1) Enable Ungroup applications in the settings
2) Open for example several terminals 
[Terminal 1] [Terminal 2] [Terminal 3]
3) Try to reorder window titles on the panel by dragging one of them before another
[Terminal 2] [Terminal 1] [Terminal 3]

Actual result: It's not possible to do
Expected result: window titles are successfully reordered

Is it possible to implement such feature? Thank you in advance

**Comment by thedonquixotic** [comment]
agreed. It's not a big deal but it is a bit odd that one can't do that.

**Comment by charlesg99** [comment]
Hi, this feature was just added to master, if you want to give it a try. Let us know if this is working for you. Thanks!

**Comment by MikeShysh** [comment]
Strange things, but I failed to load ubuntu UI after installing the latest version. Of course, it could well be incorrect installation from my side, so, I will wait for the release on gnome extensions portal

**Comment by charlesg99** [comment]
Hey @MikeShysh, sorry about that, you didn't do anything wrong, it really wasn't working... See #504. Could you please try installing again? Thanks!
