### ISSUE TITLE
Tray taking too much space

### ISSUE THREAD

**Issue by Adyel** [home-sweet-gnome/dash-to-panel#440]
Hey,

Why is the tray taking so much space? Look how much padding each icon have. Am I doing something wrong? How can I fix it?

Please, HELP :sos: 

![image](https://user-images.githubusercontent.com/4653623/43600018-45703264-96ab-11e8-8b82-9ba623c6aa04.png)

**Comment by jderose9** [comment]
Hello! By default this is controlled by your theme. You can override it with the Tray Item Padding setting in the fine-tune tab. If you set it to 0px it will remove the extra whitespace.
