### ISSUE TITLE
Possibility to show both the top bar and dash to panel?

### ISSUE THREAD

**Issue by Paralusion** [home-sweet-gnome/dash-to-panel#443]
Exactly what the title says. Not really a issue, more a question.

**Comment by jderose9** [comment]
Sorry, it is not possible in dash-to-panel, but I think the extension you are looking for is dash-to-dock.

**Comment by Paralusion** [comment]
No, I'm not looking for dash-to-dock. I've always used dash to panel and always loved it. Thanks for your answer, no top panel for me then.
