### ISSUE TITLE
Feature Request (or bug): Panel should dodge dialog windows

### ISSUE THREAD

**Issue by lagerspetz** [home-sweet-gnome/dash-to-panel#444]
When I use Intellihide and set it to dodge the active window, it only dodges the parent window. For example:
1. Open Evolution Mail
2. Make the window small enough that it does not cover the panel. The panel appears.
3. Right click to save an attachment
4. Save As dialog appears. If the dialog is at the very top of the screen, the panel now covers it.

I would expect that in step 4, as the dialog window appears, the panel would hide.

**Comment by lagerspetz** [comment]
Yes, that is almost correct. The dialog can be smaller, but appear at the top of the screen, covered by the panel (my panel is at the top). Then for example the file name line and the save button are not visible. The window is also hard to move, since I cannot grab the top of the window, since it is behind the panel.

**Comment by charlesg99** [comment]
Normally the dialog windows ignored by the intellisense are fixed and centered over their main windows. This is also what happens for me when I try to "save as" in firefox (61.0.2). I see that you changed your example from firefox to evolution mail, but I unfortunately don't use it. If I open it, I see that the welcome window behaves normally though, could you provide a screenshot? 

As a side note (not as a solution of course), you can grab and move a window by clicking anywhere in it if you hold the windows button.

Thanks

**Comment by lagerspetz** [comment]
Here's an example with the panel set to dodge focused windows, using Firefox. Before:
![screenshot from 2018-08-15 21-42-33](https://user-images.githubusercontent.com/1171264/44166547-4a02ab80-a0d4-11e8-8029-0c8444c6a442.png)
After opening save image dialog:
![screenshot from 2018-08-15 21-42-21](https://user-images.githubusercontent.com/1171264/44166561-538c1380-a0d4-11e8-8899-f47542dee0aa.png)

**Comment by lagerspetz** [comment]
More reliable instructions to reproduce:
1. Use dash to panel extension.
2. Make the panel dodge focused windows.
3. Move the panel to the top.
4. Open firefox on any page with images.
5. Make sure your firefox settings enable the prompt to save files.
6. Right click and choose save image.
7. If the file saving dialog does not appear under the panel, make the firefox window smaller, and move it closer to the top of the screen, then try again.
8. The file saving dialog will be centred on the firefox window, so if the firefox window is smaller than the file saving dialog, the issue is reproduced.

**Comment by charlesg99** [comment]
A modification was added to master, could you please try it and see if that solves the issue on your end? Thanks

**Comment by lagerspetz** [comment]
Master version works for me! Thanks!
