### ISSUE TITLE
Panel hides when I focus a legacy statusbar icon

### ISSUE THREAD

**Issue by lagerspetz** [home-sweet-gnome/dash-to-panel#446]
When using the Topicons Plus extension (to show legacy app icons at the top bar): https://extensions.gnome.org/extension/1031/topicons/
1. Have a maximized, focused firefox window.
2. Have panel (at the top), set to dodge the focused window.
3. Move mouse to the top.
4. Panel appears.
5. Keep mouse on the panel, moving it to a legacy program status icon such as Skype, MegaSync, Rambox.io (a messenger), or Solaar (Logitech mouse receiver indicator).
6. The panel hides, probably because it thinks it has lost focus.

**Comment by charlesg99** [comment]
Hi lagerspetz, I can't reproduce this issue using Rambox. I'm using a forked topicons plus though, maybe you could give it a try? https://github.com/charlesg99/TopIcons-plus

Thanks!

**Comment by charlesg99** [comment]
Thanks!
