### ISSUE TITLE
round window corners when dock is persistent.

### ISSUE THREAD

**Issue by gmlshadi** [home-sweet-gnome/dash-to-panel#448]
![image](https://user-images.githubusercontent.com/11833878/44468083-158b7400-a62d-11e8-9be9-dc7453c792ac.png)

![image](https://user-images.githubusercontent.com/11833878/44468136-35bb3300-a62d-11e8-80c7-8be22cf7e8e1.png)
the extension would fit in better with the desktop if the corners were round. also windows would look nicer.

**Comment by jderose9** [comment]
Thanks for reporting this, but your images are not from this extension.

Maybe you are looking for
[Dash-to-dock](https://github.com/micheleg/dash-to-dock)
or
[Ubuntu dock](https://help.ubuntu.com/community/ReportingBugs)
?

**Comment by gmlshadi** [comment]
Oh right. haha. You could try implementing this in dash to panel too! AFAIK, it doesn't have rounded corners either.
