### ISSUE TITLE
[Feature request] Option to position the gnome clock/calendar in the center of the panel.

### ISSUE THREAD

**Issue by tnilzon** [home-sweet-gnome/dash-to-panel#451]
The gnome clock/calendar optimal panel position is in the center of the panel. Please add that as a possibility in the options, thanks!

**Comment by jderose9** [comment]
Hello! This was completed already and is available in the latest `master`. If you'd like to install that version and try it, feedback would be appreciated.

Also.. this request already exists as #60. I'll close this one and you can hop over there if you would like to leave feedback.
