### ISSUE TITLE
[Feature request] tray context menu position

### ISSUE THREAD

**Issue by hairowits** [home-sweet-gnome/dash-to-panel#454]
Hi. I am new to gnome so I'm sorry if I cannot use proper words to describe.
Right now the tray menu is is drawn left from right starting at the center position of the tray icon. This leaves a gap where I misclicked a lot when I want to select something from the context menu quickly. 
Example:
![1](https://user-images.githubusercontent.com/25667858/44819496-0e2f1200-abbb-11e8-9af3-251eec881232.png)
![screenshot from 2018-08-29 18-29-24](https://user-images.githubusercontent.com/25667858/44819887-995cd780-abbc-11e8-95ff-e2f793ed764d.png)

Is there a Gnome extension that could make the context menu either align with the left edge of the tray icon (like picture 2) or the center of the tray icon and the context menu align (picture 3)?
Picture 2:
![2](https://user-images.githubusercontent.com/25667858/44819649-a1684780-abbb-11e8-8072-6053a7c37ecf.png)
Picture 3
![3](https://user-images.githubusercontent.com/25667858/44819652-a4633800-abbb-11e8-87c6-fa84652f2235.png)

I am sorry I don't know any better. I don't know if this is a gnome-related problem or it depends on specific gnome extension. Is there already a Gnome extension that could fix this already? Could this be fixed with dash-to-panel? Thanks a lot

**Comment by charlesg99** [comment]
Hi hairowits, what theme are you using? Is this what you see with every context menu (even the system ones like the clock) or only from your other extensions? Normally the context menu is supposed to go in the middle I believe:

![image](https://user-images.githubusercontent.com/33044886/44995526-552d5680-af71-11e8-9b1c-c5be2972bb37.png)

Thanks!

**Comment by hairowits** [comment]
Hi charlesg99. I am using Arc theme. Thanks a lot for pointing that out, it's the Arc shell theme issue and not related to Dash-to-panel at all. I disabled Dash-to-panel and the problem was still there. It only occurs with icons from community gnome tweak extensions. I just switched to default Ambiance shell theme and this goes back to what I expected, with or without Dash-2-panel extension enabled. I should have investigated a little bit more.

**Comment by jderose9** [comment]
You might want to make sure you have the latest version of Arc theme - it fixed some issues for me. (there is a new maintainer)

https://github.com/NicoHood/arc-theme

Also, I've really been enjoying Qogir lately, which is derived from Arc.

https://github.com/vinceliuice/Qogir-theme
