### ISSUE TITLE
[Bug?] Dash to Panel loaded error on Gnome 3.30

### ISSUE THREAD

**Issue by bkkgbkjb** [home-sweet-gnome/dash-to-panel#455]
Greetings!

It seems on the latest GNOME shell version 3.30, D2P cannot successfully load.

Error is `TypeError: global.screen is undefined`(thrown by lg)

There has been a similar confirmation in this [report](https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1786948)

Given the already closed issue #434, just want to make sure, is this my own problem? or the patch currently undergoing?

Best regards

**Comment by jderose9** [comment]
Thank you for reporting this, I have just released v16 to the gnome extension site, though it will have to be reviewed before going live. In the meantime, feel free to install from github using these instructions:

https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github

Thanks again!

**Comment by bkkgbkjb** [comment]
Just `git clone` and `make install` the plugin

Works perfectly on my GNOME till now 

really appreciate your beautiful work and now you can close this issue:)

**Comment by jderose9** [comment]
Version 16 with Gnome Shell 3.30 support is now live on extensions.gnome.org.
