### ISSUE TITLE
[Feature request] Add "On Desktop x" in the previews.

### ISSUE THREAD

**Issue by tnilzon** [home-sweet-gnome/dash-to-panel#456]
If it is possible it would be great to have the actual desktop where a window in the preview is placed displayed (at the bottom of the preview, after the window name). See example below:

![screenshot from 2018-09-08 12-59-29-2](https://user-images.githubusercontent.com/6920015/45253535-3c55e400-b369-11e8-891a-d7ba25375ff2.png)

**Comment by jkearneyma** [comment]
I miss being able to easily tell which desktop a window is in too, especially for something like a browser where I have multiple windows on every desktop.  I'd prefer an overlay icon with the desktop number over putting it in the title, though.
![desktop](https://user-images.githubusercontent.com/10373462/57624195-72361280-755f-11e9-848f-c8c0e2299e0b.png)

**Comment by charlesg99** [comment]
Hello, I'm currently working on the window previews and added an indicator for the workspace, which is a mix of both your ideas... This indicator, the "0" next to the icon, will only appear if the workspaces aren't set to be isolated:

![image](https://user-images.githubusercontent.com/33044886/58045597-e13bda00-7b10-11e9-8f8a-b0ce0cfd33d4.png)


Would that be ok? Thanks!

**Comment by jkearneyma** [comment]
Looks good to me

**Comment by tnilzon** [comment]
That would be a good solution, great idea!

**Comment by charlesg99** [comment]
The new window previews are available on a separate branch, if you'd like to try it and see if this is a suitable solution. More info [here](https://github.com/home-sweet-gnome/dash-to-panel/issues/611#issuecomment-495455229). Thanks!

**Comment by jkearneyma** [comment]
Looks good.  My only quibble would be that the indicator could be styled like the standard workspace indicator extension (white box, gray field) for visual consistency and as a meaning hint.
https://extensions.gnome.org/extension/21/workspace-indicator/

**Comment by charlesg99** [comment]
Hello, the new window previews indicating the window's workspace are now on master. Please try them out and open new issues if you find something wrong! Thanks!
