### ISSUE TITLE
[Feature request] move taskbar position to right

### ISSUE THREAD

**Issue by torchlard** [home-sweet-gnome/dash-to-panel#458]
First thank you for this awesome extension. Right now taskbar position is only available in center or left side, I want to know is it possible to move taskbar to somewhere next to system indicator on right side? And is it possible to move system indicator to left? Thank you.

**Comment by torchlard** [comment]
> Currently, it is not possible, unless you are using a Right-to-Left language. In that case, the order of the elements is inverted.
> 
> This doesn't seem like an unreasonable feature though, if there are people that would prefer it. Are you envisioning the entire order of the panel to be reversed?

yes, just like mirror to entirely reverse order

**Comment by MycroftHolmes1989** [comment]
Is it at least possible to move the Show Applications button to the right?

**Comment by charlesg99** [comment]
Hello, this is now possible on the master branch. Thanks!

**Comment by rknx** [comment]
Was this removed or am I not seeing the options? (v56)
