### ISSUE TITLE
Not working after Gnome update

### ISSUE THREAD

**Issue by JakubFojtik** [home-sweet-gnome/dash-to-panel#464]
After gnome-desktop upgrade to 1:3.30.0-1 while also installing gnome-tweaks on Arch linux, dash in panel disappears and errors on Update/Install/Enable:

gnome-shell[904]: Extension "dash-to-panel@jderose9.github.com" had error: TypeError: overview is undefined
gnome-software[1170]: dash-to-panel_jderose9.github.com has error: TypeError: overview is undefined
gnome-software[1170]: State change on user/*/*/shell-extension/dash-to-panel_jderose9.github.com/* from installed to available is not OK
gnome-software[1170]: no app for changed apps-menu@gnome-shell-extensions.gcampax.github.com
gnome-software[1170]: no app for changed launch-new-instance@gnome-shell-extensions.gcampax.github.com
gnome-software[1170]: no app for changed places-menu@gnome-shell-extensions.gcampax.github.com

**Comment by charlesg99** [comment]
Hey JakubFojtik, I'm also on arch and I just updated to gnome 3.30 without issue. Are you using other extensions? Could you please try dash to panel alone? Thanks!

**Comment by JakubFojtik** [comment]
Hi, I guess i had some default ones enabled (Launch new instance and maybe others i have since disabled). But the Enable button became disabled on this extension because of the errors.

So i did what a Windows user has to do and it worked: restart :)
Thanks for the help!

**Comment by charlesg99** [comment]
Great, thanks for the feedback!
