### ISSUE TITLE
[BUG] Notification icons disapear when locking computer

### ISSUE THREAD

**Issue by jfisbein** [home-sweet-gnome/dash-to-panel#469]
After locking my computer (either manually with windows key + L, or when it locks automatically), the notification icons disappears.

Here you have some panel screenshots.

Before locking my computer:
![desktop screenshot with notification icons](https://user-images.githubusercontent.com/272565/45969278-86122000-c033-11e8-8198-2933868959c6.png)

After unlocking it:
![desktop screenshot without notification icons](https://user-images.githubusercontent.com/272565/45969301-9cb87700-c033-11e8-8c05-9301850c34b1.png)

The only way I found to recover icons is to restart gnome (ALT+F2 and then "r")

Here is the log i got from journalctl when I lock and unlock:
[lock and unlock log.txt](https://github.com/home-sweet-gnome/dash-to-panel/files/2412239/lock.and.unlock.log.txt)

This are the extension I have installed:
![installed extensions gnome shell extensions](https://user-images.githubusercontent.com/272565/45969683-b6a68980-c034-11e8-8e75-3c221bb28780.png)

I'm using and up to date ubuntu 18.04.
This bug is occurring with latest and previous extension version in 2 different computers.

If I can help with more information or testing anything please tell me.

Thanks,
    Joan

**Comment by charlesg99** [comment]
Hey Joan, thank you for the report. Could you please close the notification icon programs aside from dropbox and try again to lock/unlock ubuntu? I installed the same extensions as you on a fresh ubuntu 18.04 and I can't reproduce the issue with only dropbox installed (I don't recognize the icons of the other ones). I also get the same log errors as you do, but those aren't from dash to panel. Thanks!

**Comment by jfisbein** [comment]
Hy Charles, I made the test you suggested, I closed all the notification icons but Dropbox, and the problem persists, after unlocking, the Dropbox icon has disappeared (it shows again with ALT+F2 and "r")

I tested in 2 different computers (home & work) with the same result :-(

Is there anything I can do to help solve this problem?

Thanks,
   Joan

**Comment by jderose9** [comment]
The errors you posted are coming from the [ubuntu appindicator extension](https://github.com/ubuntu/gnome-shell-extension-appindicator). Have you tried reproducing the problem with dash-to-panel disabled?

**Comment by jfisbein** [comment]
Hi @jderose9, I just installed [(K)StatusNotifierItem/AppIndicator Support](https://extensions.gnome.org/extension/615/appindicator-support/) and the problem is solved :-O
Thanks!
