### ISSUE TITLE
Disabling DtP does enable Ubuntu dock

### ISSUE THREAD

**Issue by fthx** [home-sweet-gnome/dash-to-panel#472]
Hi,

Running a GNOME session in Ubuntu 18.10 (that runs without Ubuntu dock) : when I disable DtP, I have the surprise to get the Ubuntu dock activated. Back to standard GNOME dock was expected.

**Comment by jderose9** [comment]
Thanks. Sounds like we need to check if it was actually disabled by dash-to-panel before re-enabling it.

**Comment by charlesg99** [comment]
I added a small fix to master, could you please check if that resolves the issue on your end? Thanks!

**Comment by fthx** [comment]
Seems to be perfect, as usual :-) .

**Comment by charlesg99** [comment]
Thanks for the feedback!
