### ISSUE TITLE
Icons hiding after lock screen / suspending or hibernating 

### ISSUE THREAD

**Issue by rDieCbw** [home-sweet-gnome/dash-to-panel#474]
Every time my PC lock or suspend for inactivity the launcher icons and "show apps" icons disappear and i need to go to settings and change the position of the icons to another one and go back just to appear again.

This doesn't happen when the system start normally after the PC restart or just turn on

**Comment by charlesg99** [comment]
Hey BWRaul, can you see errors in your log when you unlock your computer and the icons are missing? You could run `journalctl /usr/bin/gnome-shell -f -o cat` to monitor your log. Also, could you please try the latest master and see if it resolves the issue? Thanks!

**Comment by rDieCbw** [comment]
Unfortunely there's nothing about this on the log only chrome bugs. 
I'm Using Kali (trying to learn this one) so the extension was downloaded by software center, they're using the latest master ?

**Comment by PaPerseller** [comment]
This issue also appears on my Ubuntu 18.10. I am using the latest master from github source code. It appears  one day ago after the latest commit "Disconnect setting signals" two days ago.

**Comment by PaPerseller** [comment]
> I just installed a fresh Ubuntu 18.10 with dash-to-panel and I can't reproduce the issue with the latest master or v16. Do you have any other extension installed that might conflict with dash-to-panel? Could you please share you current settings using `dconf dump /org/gnome/shell/extensions/dash-to-panel/`? Thanks!

[/]
dot-style-unfocused='DASHES'
app-hotkey-kp-7=['<Super>KP_7']
app-hotkey-kp-8=['<Super>KP_8']
app-hotkey-kp-9=['<Super>KP_9']
taskbar-position='CENTEREDMONITOR'
focus-highlight-color='#eeeeee'
dot-color-override=true
app-hotkey-kp-10=['<Super>KP_0']
intellihide-use-pressure=true
show-activities-button=false
location-clock='STATUSRIGHT'
panel-position='BOTTOM'
app-shift-hotkey-kp-1=['<Shift><Super>KP_1']
app-shift-hotkey-kp-2=['<Shift><Super>KP_2']
app-shift-hotkey-kp-3=['<Shift><Super>KP_3']
app-shift-hotkey-kp-4=['<Shift><Super>KP_4']
app-shift-hotkey-kp-10=['<Shift><Super>KP_0']
app-shift-hotkey-kp-5=['<Shift><Super>KP_5']
app-shift-hotkey-kp-7=['<Shift><Super>KP_7']
app-shift-hotkey-kp-8=['<Shift><Super>KP_8']
app-shift-hotkey-kp-9=['<Shift><Super>KP_9']
intellihide-pressure-threshold=100
app-ctrl-hotkey-kp-10=['<Primary><Super>KP_0']
app-shift-hotkey-kp-6=['<Shift><Super>KP_6']
show-appmenu=false
panel-size=48
show-apps-icon-file='/usr/share/gnome-shell/theme/Yaru/ubuntu-appgrid-icon.svg'
hot-keys=false
show-showdesktop-button=false
app-shift-hotkey-10=['<Shift><Super>0']
intellihide-behaviour='FOCUSED_WINDOWS'
app-hotkey-10=['<Super>0']
app-ctrl-hotkey-1=['<Primary><Super>1']
app-ctrl-hotkey-2=['<Primary><Super>2']
app-ctrl-hotkey-3=['<Primary><Super>3']
app-ctrl-hotkey-4=['<Primary><Super>4']
app-ctrl-hotkey-5=['<Primary><Super>5']
app-ctrl-hotkey-6=['<Primary><Super>6']
app-ctrl-hotkey-8=['<Primary><Super>8']
app-ctrl-hotkey-9=['<Primary><Super>9']
app-hotkey-4=['<Super>4']
app-hotkey-2=['<Super>2']
app-hotkey-6=['<Super>6']
app-hotkey-7=['<Super>7']
app-hotkey-8=['<Super>8']
app-hotkey-9=['<Super>9']
app-hotkey-3=['<Super>3']
app-ctrl-hotkey-7=['<Primary><Super>7']
app-hotkey-5=['<Super>5']
app-hotkey-1=['<Super>1']
app-ctrl-hotkey-kp-4=['<Primary><Super>KP_4']
app-ctrl-hotkey-kp-1=['<Primary><Super>KP_1']
app-ctrl-hotkey-kp-2=['<Primary><Super>KP_2']
app-ctrl-hotkey-kp-3=['<Primary><Super>KP_3']
app-ctrl-hotkey-kp-8=['<Primary><Super>KP_8']
app-ctrl-hotkey-kp-5=['<Primary><Super>KP_5']
app-ctrl-hotkey-kp-6=['<Primary><Super>KP_6']
app-ctrl-hotkey-kp-7=['<Primary><Super>KP_7']
dot-color-1='#5294e2'
app-ctrl-hotkey-kp-9=['<Primary><Super>KP_9']
dot-color-3='#5294e2'
dot-color-2='#5294e2'
app-ctrl-hotkey-10=['<Primary><Super>0']
dot-color-4='#5294e2'
appicon-padding=1
dot-color-unfocused-different=false
intellihide-hide-from-windows=true
dot-color-unfocused-1='#5294e2'
dot-color-unfocused-2='#5294e2'
appicon-margin=2
dot-color-unfocused-3='#5294e2'
dot-color-unfocused-4='#5294e2'
intellihide=true
hotkeys-overlay-combo='TEMPORARILY'
dot-style-focused='METRO'
hotkey-prefix-text='Super'
app-hotkey-kp-1=['<Super>KP_1']
app-hotkey-kp-2=['<Super>KP_2']
app-shift-hotkey-1=['<Shift><Super>1']
app-shift-hotkey-2=['<Shift><Super>2']
app-shift-hotkey-3=['<Shift><Super>3']
app-shift-hotkey-4=['<Shift><Super>4']
app-shift-hotkey-5=['<Shift><Super>5']
app-shift-hotkey-6=['<Shift><Super>6']
app-shift-hotkey-7=['<Shift><Super>7']
app-shift-hotkey-8=['<Shift><Super>8']
app-shift-hotkey-9=['<Shift><Super>9']
app-hotkey-kp-6=['<Super>KP_6']
app-hotkey-kp-3=['<Super>KP_3']
app-hotkey-kp-4=['<Super>KP_4']
app-hotkey-kp-5=['<Super>KP_5']

**Comment by PaPerseller** [comment]
> Still can't reproduce with you settings. If you run `journalctl /usr/bin/gnome-shell -f -o cat`, then lock/unlock, do you see errors in the log? Thanks!

This issue seems disappear since I turn this extension off/on in tweaks.

**Comment by charlesg99** [comment]
Please feel free to reopen if you encounter this issue again. Thanks!
