### ISSUE TITLE
Reorder preview thumbnails

### ISSUE THREAD

**Issue by tleasure** [home-sweet-gnome/dash-to-panel#477]
Is there currently any way to reorder preview thumbnails?  Suppose you have 3 Firefox windows open, you hover over the icon and see 3 previews.  Is there any way to drag one so that it's in a different position?

**Comment by Bindea** [comment]
Go in options and ungroup applications?

**Comment by tleasure** [comment]
I'd actually still like them to be grouped. I use 3 monitors, so it's easier to keep track of multiple windows if I can order them within the group.

**Comment by jderose9** [comment]
@tleasure 
It seems like a frustrating workflow to constantly have to re-arrange your thumbnails as you open/close applications?

Perhaps using the new multi-monitor feature discussed in #35, with Isolate Monitors enabled will help resolve your issue (the preview for each window will only show on the monitor it is on).

**Comment by jderose9** [comment]
Multi-monitor has been released in v17+. Check it out with Isolate monitors on. If that still doesn't cover what you are looking for, please report back. Thanks!
