### ISSUE TITLE
Disable running indicator without favourite apps showing

### ISSUE THREAD

**Issue by blackjackshellac** [home-sweet-gnome/dash-to-panel#478]
I don't show favourites so I'd rather not see the running indicator at all.  A toggle on the taskbar to show favourites would be very cool too.

BTW, great extension, almost perfect :)

**Comment by charlesg99** [comment]
Hey @blackjackshellac, thank you for your input! Not sure if we need to add a dedicated option to remove the running indicators, as you can simply set their heights to 0 to hide them completely. Is it acceptable? Also the toggle sounds like a good idea, but I'm unsure of how we could add it in a non-intrusive way, any thoughts? Thanks!

**Comment by fchiacchiaretta** [comment]
> Also the toggle sounds like a good idea, but I'm unsure of how we could add it in a non-intrusive way, any thoughts? Thanks!

Maybe favourites can be collected in a menu, and you can have an icon (or text) on the panel which shows the favourites menu on click (and maybe also with a keyboard shortcut). Sounds like a dedicated shell extension.

**Comment by jderose9** [comment]
I'm going to close this for now as I believe setting height to 0 should be satisfactory for most users.

@fchiacchiaretta I think that would be covered under #117.

Thanks all!

**Comment by SethMacKayChandler** [comment]
Greeting from the future. I just found this via google search to fix the exact same problem. I think this is a valid issue because the UI could be improved in some way to make this solution more obvious or apparent

**Comment by sharesiesben** [comment]
I've just started using Dash to Panel on Ubuntu after years on MATE. I am loving it, thank you!

I also wanted to remove the Running indicator and I'm happy with the height: 0 workaround, but the first thing I tried was to click on the already active position indicator to see if I could have no options selected, which I think could be a nice option to do this unobtrusively
