### ISSUE TITLE
Multirow for Application section

### ISSUE THREAD

**Issue by KRtekTM** [home-sweet-gnome/dash-to-panel#479]
Hello everybody,
I'm trying to modify CSS file of dash-to-panel to have multirow in the #dashtopanelScrollview so it'll look more like on Windows (I'm using 2 rows size taskbar - like the guy here: https://postto.me/is/tskbrpgt.png).

However I'm unsuccessful. Maybe you'll help me - do you think it's possible to do just with css modifications or it'll have bigger impact to the design and requires changes alson in JS?

Big thanks for your reply.

**Comment by KRtekTM** [comment]
I was able to modify it so this is my result now:

![screenshot from 2018-10-13 17-42-04](https://user-images.githubusercontent.com/6234196/46907200-5c9c3400-cf0f-11e8-8c6b-9a40bd8abad5.png)

However with more opened applications, it keeps showing them on the top row and can't make it to split to two rows (by CSS changes).

Attaching my CSS file: http://share.krtkovo.eu/files/stylesheet.css

**Comment by charlesg99** [comment]
Hi KRtekTM, it looks pretty good so far, but unfortunately the end result won't be possible using css only, as the javascript will need to be modified as well. I'm gonna close this as there already is an opened feature request #268 concerning this, so feel free to chime in over there. Thanks!
