### ISSUE TITLE
Full transparent taskbar + Fullscreen window = Taskbar bottom  gold highlight 

### ISSUE THREAD

**Issue by GMFalka** [home-sweet-gnome/dash-to-panel#482]
Hello!

Setting the taskbar to full transparent and maximizing a window to fullscreen, the taskbar goes into this "ugly" half transparent half gold accent/highlight state. Is this intentional?

**Examples:**

![image](https://user-images.githubusercontent.com/17993825/47038300-6a58f000-d181-11e8-8714-240cb5717e20.png)

![image](https://user-images.githubusercontent.com/17993825/47038275-57deb680-d181-11e8-8f46-5b274e7318d2.png)

**If no window is maximized**

![image](https://user-images.githubusercontent.com/17993825/47038328-7c3a9300-d181-11e8-9aa3-fa705727be57.png)

**Comment by charlesg99** [comment]
Hey GMFalka, I'm assuming that you are using the new opacity settings from branch feature-multimon? If so, could you provide the following: 

- gnome-shell version
- theme used
- list of your settings using `dconf dump /org/gnome/shell/extensions/dash-to-panel/`

Thanks!

**Comment by GMFalka** [comment]
Thanks for the quick replay, charlesg99!

I may have goofed, not 100% sure its a Dash to Panel problem. Im using Dynamic Panel Transparency "addon", that makes it transparent (not DtP)

I found this setting in that addon.. I thnik i will close this and check on that addon github for more info,help.

![image](https://user-images.githubusercontent.com/17993825/47042949-c117f700-d18c-11e8-9192-efa9d60ec5a4.png)

**Comment by charlesg99** [comment]
Thanks, let us know if you have problems with dash to panel
