### ISSUE TITLE
Add customization option for App Icon Margin (top left right bottom)

### ISSUE THREAD

**Issue by BoQsc** [home-sweet-gnome/dash-to-panel#484]
I would like to futher tune the margin of the icons: make them little bit closer to the bottom.
The problem: there is only a general option to make all the margin sides with the same equal value, no way to customizing each margin side to your own design needs.

**Comment by charlesg99** [comment]
Hello BoQsc! I personally think we offer enough customization right now... @jderose9 What is your take on this?

**Comment by jderose9** [comment]
One annoyance I have is that when there is a large running indicator, it eats into the padding, so I had considered adding a vertical offset at one point. The problem then becomes that you are out of alignment with the rest of the content in the panel. This is also why I'm not really sure how a top/bottom alignment would work for the icons.
