### ISSUE TITLE
Enable multi monitor support

### ISSUE THREAD

**Issue by yar05** [home-sweet-gnome/dash-to-panel#485]
Is there any way to make this dock appear on all monitors and only show windows from each window separately ? 

Or having top bar only with status bar but window list on the bottom ? I would be willing to pay for this ! :)

**Comment by charlesg99** [comment]
Well you're in luck, we just finished implementing that (see #35 for details). Please [install the latest development version](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github) to help us test this new feature! Feedback is also welcome! Thanks
