### ISSUE TITLE
[Feature Request] Mouse scroll wheel to move between workspaces

### ISSUE THREAD

**Issue by ningacoding** [home-sweet-gnome/dash-to-panel#486]
Please enable an option to use wheel of mouse, so we can navigate between workspaces.

**Comment by fchiacchiaretta** [comment]
As a temporary solution, you can install [Top panel workspace scroll extension](https://extensions.gnome.org/extension/701/top-panel-workspace-scroll/). However, scrolling only works for me on empty space of the panel.

**Comment by mweirauch** [comment]
This might be related to #336 which asks for a workspace indicator feature.

**Comment by ningacoding** [comment]
@fchiacchiaretta you right, not working when mouse over app icons and plugin icons, but as "temporary solution" as you said, is enough for me, if Dash to Panel can cover this feature will be excellent.

**Comment by varsop** [comment]
Concerning this feature request, I can recommend following extension, which works really great with dash to panel extension:

    https://github.com/Tomha/gnome-shell-extension-workspace-switcher

**Comment by deekosta** [comment]
I'd like to add a vote for this. The mentioned extension does work, but it does not provide the overlay to show which space you are in. Adding this feature to dash-to-panel natively, as it is with dash-to-dock, would be greatly appreciated!

**Comment by charlesg99** [comment]
Hello, this feature was just added to the master branch. Didn't add a setting, it should just work by scrolling over any area of the panel that isn't an appIcon (in the future, those will be used to switch windows #30). Thanks!
