### ISSUE TITLE
App menus are being removed in GNOME 3.32

### ISSUE THREAD

**Issue by catb0t** [home-sweet-gnome/dash-to-panel#489]
[Remove support for app menus](https://gitlab.gnome.org/GNOME/gnome-shell/issues/624)

[Farewell, application menus!](https://blogs.gnome.org/aday/2018/10/09/farewell-application-menus/)

Will this affect Dash to Panel? I don't mind not being able to access the application's *menu* from its icon in the DtP top bar, but I would like to maintain the application list, Favorite apps, the "New Window" etc options in the icon dropdowns (that are not actually part of the application's menu)

Current DtP top-left

![screenshot from 2018-10-29 13-03-30](https://user-images.githubusercontent.com/3238748/47666969-374c2e80-db7b-11e8-9135-bf7468db7cd8.png)

Rhythmbox application menu. Rhythmbox's "application menu" proper only contains the things like "Add Music" to "About", and the "Play/Pause" etc entries.

The "Rhythmbox", "Add to Favorites" and "Quit" items are added by GNOME, but will DtP be able to keep them around? 

![screenshot from 2018-10-29 12-56-01](https://user-images.githubusercontent.com/3238748/47666841-f2c09300-db7a-11e8-9abe-aa056cfb7b48.png)

**Comment by charlesg99** [comment]
Hi @catb0t, thank you for your interest. The content of the app menus can be displayed in two ways in dash to panel, the one you mention in the contextual menu of an app icon and on the taskbar itself (if app menus are enabled in tweak tool). 

From what I understand of the proposed changes found in your links, the contextual menus should still work correctly, but the option to display the app menu on the taskbar won't in 3.32. So unless the applications themselves remove options from their menus, the dash to panel contextual menus should be unaffected. The default menus like "Add to Favorites" aren't affected by this gnome-shell change, so they'll still be in the contextual menu as well.

Thanks!

**Comment by catb0t** [comment]
Great to hear, thank you :)
