### ISSUE TITLE
Something's wrong in dynamic opacity management

### ISSUE THREAD

**Issue by fthx** [home-sweet-gnome/dash-to-panel#490]
Hi Charles,

When I play around with maximized/unmaximized windows, I notice that the dynamic opacity goes away. The top panel then becomes all opaque black, aka the old GS behaviour. I did not use the new opacity customization in DtP settings.

This does never happen without DtP. (Ubuntu 18.10, GNOME session (wayland), GS 3.30, latest DtP git)

**Comment by charlesg99** [comment]
> I did not use the new opacity customization in DtP settings. This does never happen without DtP.

Hello fthx, not sure I understand correctly, are you referring to the default gnome-shell transparency or the new one in dtp? In the latest dtp version, the gnome-shell transparency is disabled because it didn't work with the multi-monitors feature. Thanks!

**Comment by fthx** [comment]
Ok I guess I found it.
It's related to the Firefox or Thunderbird topbar-less modes. If I maximize/unmaximize it, the dynamic transparency is broken in GS (without extensions) until I go to overview. Using DtP, it becomes broken forever.
NOTE :
I do see dynamic transparency using latest DtP git ! I tried maximizing/unmaximizing GNOME Terminal a dozen of times and GS topbar still becomes transparent/opaque ! :-) I do use only one monitor.

**Comment by charlesg99** [comment]
> Using DtP, it becomes broken forever.

Still not sure I understand :) As I said, the latest development version of dash to panel completely disables the gnome-shell dynamic transparency, so if the new dash to panel dynamic transparency option isn't enabled, the panel's opacity shouldn't change at all. This is true even if you only have one monitor. Is this what you're seeing? Thanks!

**Comment by fthx** [comment]
No I see dynamic transparency !

**Comment by charlesg99** [comment]
I realize that there might be some confusion when this new feature is released as the dash to panel dynamic transparency is disabled by default, but it also disables the gnome-shell one, so the perception will be that it stopped working somehow (only with the default theme). I don't think this is such a big issue though as users will have to adjust their settings only once to suit their needs and then be on their way. Thanks!
