### ISSUE TITLE
Multi-monitor incompatability with no-title-bar extension

### ISSUE THREAD

**Issue by SimonLammer** [home-sweet-gnome/dash-to-panel#491]
When combined with [the no title bar extension](https://extensions.gnome.org/extension/1267/no-title-bar/) I can't un-maximize windows on the second monitor the way i can on the primary one (by dragging down from the top panel).

(moved from comment in #35)

**Comment by charlesg99** [comment]
Hello Simon, thank you for the report! Seems like it isn't related to the no title bar extension as I can reproduce the issue without it being enabled. A fix for this was added to master, could you pull and see if it works for you? Thanks!

**Comment by SimonLammer** [comment]
Just tried with current master, but nothing regarding this issue changed as far as I can see. Also, as you correctly pointed out, this also happenes without the no-title-bar extension (it's just a worse experience with it, because I can't un-minimize by dragging the title bar either - for obvious reasons)

**Comment by charlesg99** [comment]
Which gnome-shell version are you running? Xorg or Wayland? I just tested on ubuntu 18.04 and 18.10 with both Xorg and Wayland and I can correctly minimize windows on a secondary monitor by dragging from the top panel. I couldn't do that before the latest commit to master, so I'm a bit confused as to why it doesn't word on your end. Did you install correctly? Thanks!

**Comment by SimonLammer** [comment]
I'm running Ubuntu 18.04.1 LTS (4.15.0-36-generic kernel), GNOME 3.28.2, Xorg

**Comment by charlesg99** [comment]
Thanks Simon, do you have other extensions enabled that could cause some conflicts? Do you have some errors in your log? Not sure what is wrong with your installation, but this is what I see on a secondary monitor of ubuntu 18.04.1 with Xorg:

![peek 2018-11-01 16-08](https://user-images.githubusercontent.com/33044886/47877209-bc407d80-ddf1-11e8-9a32-531a764eb88b.gif)

**Comment by charlesg99** [comment]
Hey Simon, did you have time to try the latest development version? Are you still experiencing this issue? Thanks!

**Comment by SimonLammer** [comment]
It's kind of weird: I've since moved to ubuntu 18.10 and after reboot it doesn't work until I restart gnome shell (alt+f2 "r"). No Idea what could cause that.

**Comment by charlesg99** [comment]
I've been using this for a while now without issues, please report back if you are still experiencing problems with it, thanks!

**Comment by SimonLammer** [comment]
Still have the problem sometimes - mostly restarting the gnome shell fixes it.
