### ISSUE TITLE
Multi-Monitor - Isolated workspaces bug on secondary screen when 'ungroup applications' is enabled

### ISSUE THREAD

**Issue by laurensV** [home-sweet-gnome/dash-to-panel#496]
When 'isolated workspaces' is on and multi-monitor panel is enabled, the isolated workspace functionality works on the primary monitor panel, but not on the panel on the secondary monitor. Only after opening a new application the icons on the panel on the secondary monitor are correct (untill you switch workspace again, then you have to open another new application to get the icons on the panel correct again).

BTW. I also have 'ungroup applications' enabled.

**Comment by charlesg99** [comment]
Thank you Laurens! Indeed, I could reproduce the issue. Never noticed it since I use the "Workspaces on primary display only" in Tweaks. A fix for this was added to master, could you please pull/install again to confirm that it is working for you as well? Thanks!

**Comment by laurensV** [comment]
Thanks for the quick fix, works great now!
