### ISSUE TITLE
[Feature Request] Allow smaller panel size

### ISSUE THREAD

**Issue by schrodog** [home-sweet-gnome/dash-to-panel#498]
Right now panel size has minimum of 16px, but I still find icons to be too large on my 2k screen. Can the minimum panel size decrease to ~12px ?
(Btw, when I test out adjusting panel size below 16px, I found that the status icon only shrink in vertical direction, but not keeping aspect ratio; meanwhile font size of clock and language unchange. Those are issues if panel size below 16px. Can they be fixed? )

**Comment by charlesg99** [comment]
Hi schrodog, could you please post a screenshot of your panel when the panel size is set at 16px? Thanks!

**Comment by schrodog** [comment]
![screenshot from 2018-11-03 22-36-00](https://user-images.githubusercontent.com/16360247/47953458-fd36be80-dfb8-11e8-808a-25a1e9f0aed4.png)

**Comment by charlesg99** [comment]
Thanks, did you try different values of "App icon padding"? That would reduce the application icon sizes without distorting the status icons. You can also modify the panel size value past 16px by using dconf.

**Comment by schrodog** [comment]
Looks much better after adjusting font size in gnome-shell.css for panel size 13px. Still has some misalignment in clock label and lang label, not sure where to fix it.
![screenshot from 2018-11-04 09-53-46](https://user-images.githubusercontent.com/16360247/47959134-8f6daf80-e017-11e8-82f3-6a8f18502157.png)
