### ISSUE TITLE
Left position on the screen

### ISSUE THREAD

**Issue by n-osennij** [home-sweet-gnome/dash-to-panel#500]
I very like this extention. Panel looks sumptuously. Like windows 10 panel - all buttons, clock and etc on one panel. But now avaible only two positions on the screen - top & bottom. How can I place panel to the left? So that application menu will be on the left-top. Clock and show desctop - left-bottom. Is it possible?

**Comment by charlesg99** [comment]
Hello n-osennij! This isn't possible yet, please refer to #3 for more details and advancement. Thanks!
