### ISSUE TITLE
[Feature Request] Better visual feedback for activation

### ISSUE THREAD

**Issue by prasannavl** [home-sweet-gnome/dash-to-panel#502]
Currently, if an icon is tapped/clicked, it has a small animation as a visual feedback. However, when animations are disabled, there is no feedback whatsoever. I think it'd be nice to have some small feedback in the form, similar to focus/hover feedback, where it's indicated with a change in opacity of the selection. It could just use another opacity shade momentarily so it doesn't introduce another color choice (I'm a big fan of keeps things in grayscale/opacity filter), with the color/opacity being optionally modifiable.

**Comment by jderose9** [comment]
By default, there is both a tint to the icon container and a running indicator which changes appearance for the focused application.

Could you post a screenshot so we could better understand what you are seeing? Thanks!

**Comment by prasannavl** [comment]
@jderose9: It seems like you misunderstood. I wasn't talking about the window focus, which, of course works perfectly. I'm referring to the feedback on "click" - essentially the activation. 

I'm attaching it here:

![peek 2018-11-05 22-32](https://user-images.githubusercontent.com/559409/48013623-bd074580-e14a-11e8-990d-475b61267f76.gif)

What happens here is that the panel itself, doesn't have any indication that the icons were clicked. You'll see some of the icons light up, after it's activated and gains focus, but from the point of "click" to focus. There's no indication. Thankfully, in this particular case though the cursor changes. But I've often found that to be unreliable. There are n-number of things that can affect the cursor. So, it'd be very nice to have the icons change state ever-so-slightly for a moment to indicate that it has been clicked.

**Comment by prasannavl** [comment]
Ok, here's a better example. Most of the ones above started rather quickly. (This doesn't happen on portable devices with low low rpm mechanical HDDs). 

But here's where the problem is better elucidated: I'm opening CLion in this one. You'll see that there are no changes. I've actually clicked in 10 times, and after a few seconds, I'll see 10 windows of CLion opening - There's no visual feedback. 

![peek 2018-11-05 22-40](https://user-images.githubusercontent.com/559409/48014065-dd83cf80-e14b-11e8-857a-21d7933f3c62.gif)

**Comment by prasannavl** [comment]
IIRC, Windows 10 does a very subtle, but very nice effect on click originating from the exact pointer location. But that might be a little too complex to get right.

However, another tint with a different opacity momentarily should do the job with some elegance.

**Comment by jderose9** [comment]
I'm not observing a pointer effect on Windows 10 but I do see that they briefly toggle the focus highlight on click. Perhaps that would work here?

**Comment by prasannavl** [comment]
@jderose9, ah, you're right. Been a while since I used Windows, but I almost remember it had a subtle glow directed from the pointer. But anyway, looks like they simplified it. Probably for the better.

![record](https://user-images.githubusercontent.com/559409/48026580-71fe2a00-e16c-11e8-9d08-b7fadef030c0.gif)

But it's not just the focus highlight though. It's a slightly different tint. So, it works even on a focused one.

**Comment by jderose9** [comment]
Thanks for all of the screen caps, @prasannavl .

I'm still a little confused as to why not just re-enable the launch animation as it seems like it would address your concern here?

**Comment by prasannavl** [comment]
@jderose9, Unfortunately, simply put mutter isn't a very reliable compositor as compared as Window's DWM or Mac, and well Linux graphics driver ecosystem while probably at it's best state so far, it's yet reliable enough across the board. 

I have a two high end laptop both of 2016+ makes, which are both still choppy, even on intel modesetting drivers. Animation preferences aside, this makes it mandatory in systems like this to disable animations to have usable environment.

**Comment by marcoms** [comment]
I also have animations disabled due to GNOME's poor performance, which hopefully can be addressed in 3.22 according to reports. I agree that it would be nice at least to have a lighter highlight on the icon on the `:active` state

**Comment by charlesg99** [comment]
Hey guys, I just added a small background opacity change when clicking on an icon. Nothing crazy, but maybe it is enough to resolve the issue? Thanks!

**Comment by charlesg99** [comment]
Gonna close now as I believe the new opacity change on click provides a good enough visual feedback. Please feel free to reopen if you think otherwise. Thanks!

**Comment by codepushr** [comment]
I might be a bit late but chiming in nevertheless: @charlesg99 I wonder if there's a way to 'animate' the icon for the time being until the application finished booting and starts? On macOS the icon would bounce basically forever until the application loads. This would GREATLY improve the UX as currently I have no indication IF i clicked the right icon and if  it's even loading up.

**Comment by charlesg99** [comment]
Hello codepushr, I agree something like this would be a good addition. I'm not yet aware of a way to know when the started application instance has finished loading, but there must be something of the sort.

Could you please open a new feature request with this idea, so we can keep track of it? Thanks!
