### ISSUE TITLE
Drag and Drop question?

### ISSUE THREAD

**Issue by Bindea** [home-sweet-gnome/dash-to-panel#503]
I see that Commits have been added for drag and drop possibilities does this mean we can drag folders to the bottom panel as i would like to add the download folder?

I've tried dragging and dropping both the download folder and a symbolic links in the past but neither worked.

Thanks

**Comment by charlesg99** [comment]
Hello Bindea, the added possibilities are to reorder running applications and application instances (while ungrouped). So far only the favorite applications could be reordered. As for the favorite folders, did you try creating "desktop entries" that would open your desired folder? Not sure if this would work but it might be worth a try. Thanks!

**Comment by Bindea** [comment]
@charlesg99 

Thanks for explaining the commits are about the reorder on the panel , I'll look into trying to create and  pin "desktop entries"

Sorry to take you away from your work , this can be closed now.

Thanks

**Comment by charlesg99** [comment]
Thanks Bindea!
