### ISSUE TITLE
[Feature Request] Show urgent hints

### ISSUE THREAD

**Issue by veridiam** [home-sweet-gnome/dash-to-panel#505]
When a client wants the user's attention it sets its WM_HINTS to UrgencyHint (https://tronche.com/gui/x/icccm/sec-4.html#s-4.1.2.4). In other window managers, and in dash-to-dock, the app panel icon changes color. An example of this is receiving a message on Skype. Currently dash-to-panel doesn't seem to support this.

**Comment by smt923** [comment]
Is there any news on this? It's a feature a lot of desktops implement and is also something many people are used to when switching away from Windows, would love to see this added to dash to panel

**Comment by veridiam** [comment]
Correction: I actually have found dash-to-dock does not support this. You can see it in action on Plasma's task manager or icons-only task manager in the panel, though.

**Comment by jderose9** [comment]
This has been implemented.
