### ISSUE TITLE
Logging out with Show Applications screen shown

### ISSUE THREAD

**Issue by Cariffo** [home-sweet-gnome/dash-to-panel#506]
So I have been testing this today and here are my results:

Running Ubuntu 18.04.1 LTS

I cant install anything after Commits on Nov 7, 2018 (including) that would work on two monitors so i am currently running b0c314f2c5c8a9d2cef2db5933157dc280b6c926 from November 6th

When i try to log out with the Show Applications screen up, after i log back in i get this (see screenshot) and i cannot recover from that state

![screenshot from 2018-11-11 01-16-34](https://user-images.githubusercontent.com/32733604/48307556-e1e72880-e54f-11e8-8c56-c7a0abff8302.png)

Keep up the great work!
Thank you.

**Comment by Cariffo** [comment]
Also as you can see there is a volume icon missing on my secondary monitor, however this only happens sometimes and i couldnt figure out why.

**Comment by charlesg99** [comment]
Thank you Cariffo, I could reproduce the issue. Some fixes were added to master, could you please try again the latest version and see if it is working for you? Thanks!

**Comment by Cariffo** [comment]
This fixes the issue, i no longer end up in a state i cant recover from. Thank you!

However on my journey i have observed 2 more (the curse of being a tester by profession)

1
After i do a fresh reboot and log in and press Super (which in my case serves to open Show Applications) i get this screen:

![screenshot from 2018-11-11 12-01-55](https://user-images.githubusercontent.com/32733604/48312132-7f6f4600-e5aa-11e8-9300-567d80723b04.png)

But if i go through the icon Show Applications on the panel i get this:

![screenshot from 2018-11-11 12-02-28](https://user-images.githubusercontent.com/32733604/48312141-93b34300-e5aa-11e8-8e77-cf119e2f6650.png)

After i interact with the panel it will remain shown in Show Applications (at this point even by just using Super key)

2
When i do fresh reboot panel looks like this:

![screenshot from 2018-11-11 12-04-08](https://user-images.githubusercontent.com/32733604/48312163-eee53580-e5aa-11e8-9ae3-898e7cde7841.png)

 After i log out and in it looks like this:

![screenshot from 2018-11-11 12-04-18](https://user-images.githubusercontent.com/32733604/48312165-fc022480-e5aa-11e8-82e2-a659e59b2b8e.png)

As you can see the volume and battery percentage on my secondary monitor disappear

**Comment by charlesg99** [comment]
> However on my journey i have observed 2 more (the curse of being a tester by profession)

Exactly what we need :) 

Some more fixes were added to master to address the 2 new issues. I couldn't test the missing battery percentage so your feedback will be appreciated. Thanks!

**Comment by Cariffo** [comment]
Okay so I went ahead and tested the fix:

Volume and battery percentage remain present after log out/in so I think the issue is gone.
Also the panel is present after boot in the Show Applications screen so that issue should be resoveld aswell.

However the original issue of logging out with the Show Applications screen displayed is still present just in a different way. Every time you log out and in while the Show Applications screen is displayed the application menu gets a little bit smaller... if you repeat several times you will end up with something like this:

![screenshot from 2018-11-11 17-42-23](https://user-images.githubusercontent.com/32733604/48315649-2d91e480-e5d9-11e8-93f5-f6a5637e6d2a.png)

This is only fixable by resetting the workspace (Alt+F2 with the command r) or reboot

**Comment by Cariffo** [comment]
You are doing great work tho! 
Thank you.

**Comment by charlesg99** [comment]
Thank again for your help Cariffo! I could reproduce the applications menu getting smaller and a fix for it was added to master. Please let me know if that corrects it on your end. Thanks!

**Comment by Cariffo** [comment]
I can confirm that it works. As of now i have no further issues on my list.
However i shall report if I come by any new ones.

Thank you again for your work. Loving the extension.

**Comment by charlesg99** [comment]
Great, thanks for the feedback!
