### ISSUE TITLE
multi-monitor resutls in being highlighted wrongly for applications with icons on both windows

### ISSUE THREAD

**Issue by Miclebrick** [home-sweet-gnome/dash-to-panel#507]
monitor with it actually open:
![image](https://user-images.githubusercontent.com/6323125/48510342-9d92ab80-e821-11e8-9db6-28bf7145aef6.png)
monitor with it as a favorite:
![image](https://user-images.githubusercontent.com/6323125/48510355-a7b4aa00-e821-11e8-8ff8-356a16fd878d.png)

**Comment by fchiacchiaretta** [comment]
I think you activated the option "Isolate monitors" in multi monitor options.
Navigate to Dash to Panel settings -> Position tab -> Click on the gear near "Display panel on all monitor" and uncheck "Isolate monitors".

**Comment by Miclebrick** [comment]
But I want isolate monitors on, so only the apps on each monitor show. However I might have two instances of the same app open, one on each monitor

**Comment by jderose9** [comment]
It seems only the running indicator is isolated on each monitor now. The focus highlight should probably also be isolated.

**Comment by charlesg99** [comment]
Hey guys, a fix for this was added to master. Thanks!

**Comment by Miclebrick** [comment]
https://github.com/home-sweet-gnome/dash-to-panel/commit/d0a519983ba77d5287c0afc916d9e02c17dc3c4a seems to have fixed it. Thanks!
