### ISSUE TITLE
Disable "dynamic transparency"

### ISSUE THREAD

**Issue by cybermancy** [home-sweet-gnome/dash-to-panel#509]
When I make a window full screen or a window touches the panel: the panel becomes matte rather than transparent. I don't like this. How can I change the panel to either stay the same or slightly darken. On the default Ubuntu 18.04 Ambiance theme the panel becomes extremely ugly.

**Comment by cybermancy** [comment]
After reading more I've learned what I am talking about is called "dynamic transparency". This is what I want to disable.

**Comment by charlesg99** [comment]
Hello cybermancy, what you're asking has already been added to the latest development version, but isn't yet available on extension.gnome.org. Feel free to [install from github](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github) if you want to give it a try. Thanks!

**Comment by cybermancy** [comment]
Appreciate it.
