### ISSUE TITLE
♥♥♥ Thank You! ♥♥♥

### ISSUE THREAD

**Issue by alex285** [home-sweet-gnome/dash-to-panel#51]
thats not an issue, just want to say thank you guys for doing this awesome extension!

**Comment by jderose9** [comment]
Glade you find it useful. Thanks for the kind words!

**Comment by AlexGluck** [comment]
Thx, after this extension i replace cinnamon to gnome.

**Comment by greatquux** [comment]
thank you!!!

**Comment by grayzusht** [comment]
This extension made gnome-shell my main DE. I was trapped in eOS because of its desktop. Thank you guys

**Comment by timrichardson** [comment]
what a nice issue to leave open! This is fantastic extension. I think standard gnome is good, the gnome devs have a vision for a modern clean UI, but they also made it extensible, and so with a lot of work, we have this wonderful extension which personally I wouldn't like to be without. 

None of the open issues is tagged as a good first issue for would-be contributors, at the moment.

**Comment by JayBeeDe** [comment]
This extension is amazing !

**Comment by tmfksoft** [comment]
+1, Loving this extension within minutes of installing and customising it, It's made the jump from Windows 10 to Ubuntu a real joy and has been the last piece of the puzzle.

**Comment by cerqueiramatheus** [comment]
I love it too! How can I update the pt_BR translation?

**Comment by chrisjbillington** [comment]
Go away stale bot

**Comment by LPFchan** [comment]
Yeah, fully agreed! This extension made my switch to Linux 100x smoother and better <3
