### ISSUE TITLE
Dock is not transparent when an app is maximixed.

### ISSUE THREAD

**Issue by hackdelight** [home-sweet-gnome/dash-to-panel#512]
Dock is transparent when in applications menu or desktop. But when i open chrome or any other app in fullscreen, it gets a non-transparent light grey color. 
I used dash-to-dock to see if it is the same but dash-to-dock worked perfectly fine.
Ubuntu 18.0.4,gnome 3.30

**Comment by charlesg99** [comment]
Hello hackdelight, please refer to #509. Thanks!
