### ISSUE TITLE
<Solved> Pin Favourite Icons so they stay on the left?

### ISSUE THREAD

**Issue by Bindea** [home-sweet-gnome/dash-to-panel#513]
Is it possible to pin the Favourite Icons so they stay on the left and every application or ungrouped window that opens is placed to the right of the Favourite Icons , i had a look in options but could see anything?

Not sure if that made any sense and if anyone else agrees with this? :)

Thanks

**Comment by Lucapz** [comment]
Yeah , that would be nice if they stayed where they are as they can end up on the far right with lots of ungrouped widows open that you keep going to the wrong place for the favourites icon and have to search along the panel.

**Comment by charlesg99** [comment]
Hey guys, if I understand correctly, this is already possible. In the "ungrouped application options", enable "use the favorite icons as application launchers". Is this what you're referring to? Thanks!

**Comment by Lucapz** [comment]
@charlesg99 

That Worked Perfectly , That's exactly what i was referring too so i assume Bindea meant the same thing as they now stay on the left.

Thanks

**Comment by Bindea** [comment]
LOL, do i feel like an idiot that the setting was there all along , though in my defence i wouldn't have guessed it by the description. :)

Thanks charlesg99 , i'll close this now.
