### ISSUE TITLE
Integration with "Places" menu

### ISSUE THREAD

**Issue by Brandon-Campanile** [home-sweet-gnome/dash-to-panel#514]
The 'places' menu moves to an incorrect position on login. I was hoping you could look into the issue. I believe it may be caused by placement in the load order. Here's a [link](https://gitlab.gnome.org/GNOME/gnome-shell-extensions/issues/124) to the issue I submitted with them.

**Comment by charlesg99** [comment]
Hello Brandon-Campanile, is it gno-menu on your screenshot? If so, could you please see if you have the same problem when you disable gno-menu, as it creates a lot of error on login (see #493). For me the places menu is always at the far left of the panel, even after lock-unlock:

![image](https://user-images.githubusercontent.com/33044886/49122735-a81e5d80-f283-11e8-82f5-9e0d89e3ac69.png)
 

Thanks

**Comment by Brandon-Campanile** [comment]
I disabled and re-enabled the gno-menu extensions and it seems to have fixed the issue.

**Comment by charlesg99** [comment]
Hello Brandon, sorry, I think I was unclear. I meant to disable the gno-menu and then locking and unlocking your session to confirm that gno-menu causes the issue. Or is this what you did? Thanks!
