### ISSUE TITLE
Mouse lag over clock / notifications and settings 

### ISSUE THREAD

**Issue by lnicola** [home-sweet-gnome/dash-to-panel#515]
See also #62 
See also https://github.com/andyholmes/gnome-shell-extension-gsconnect/issues/364.

I have an extension that produces a lot of notifications. After a while, the calendar widget stops opening when clicked and the mouse lags a lot when hovering the settings (WiFi/volume/battery) widget.

Filing this here since after disabling Dash to panel I can clear the notifications (the widget opens fine). I think it's also enough to restart the extension. I will confirm the next time it happens to me.

**Comment by charlesg99** [comment]
Hello, maybe you could use this option to minimize the lag? It makes it so the menu doesn't open on hover, only when clicking it:

![image](https://user-images.githubusercontent.com/33044886/57964328-9ac46080-7901-11e9-8d7e-4cc18a994619.png)

Thanks!

**Comment by lnicola** [comment]
@charlesg99 Maybe. I can't test right now, but for me it only shows the pop-up on click, even if I don't enable that option. I'm not sure if it was different before.
