### ISSUE TITLE
Official extensions badge

### ISSUE THREAD

**Issue by andyholmes** [home-sweet-gnome/dash-to-panel#516]
Sorry, I missed your extension when I was spreading the word about the new official extensions badge! Awhile ago I asked for "Get it on..." badge for extensions like Google Play has, so GNOME had their marketing designer Caroline Henriksen make an official badge for us. They asked if I'd contact a few extension developers to get the word out.

[<img src="https://raw.githubusercontent.com/andyholmes/gnome-shell-extensions-badge/master/get-it-on-ego.svg?sanitize=true" height="100">](https://extensions.gnome.org/extension/1160/dash-to-panel/)

There is a PNG and SVG available that you can host yourself, possibly link from the [GitLab issue](https://gitlab.gnome.org/Teams/Engagement/marketing-design/issues/3), or I have a [repository on Github](https://github.com/andyholmes/gnome-shell-extensions-badge) you can link from (see the raw markdown from this comment for using SVG on Github). I see you have a nice banner on your front page, and it's probably okay to insert the badge into that too, as long as you don't make any trademark-y changes to it.

Or just feel free to close the issue if you're not interested! Best of luck with your extension, looks like a lot of work :wink:

**Comment by charlesg99** [comment]
Thanks a lot!

**Comment by charlesg99** [comment]
The new badge was added to the readme in PR #534 
Thanks!
