### ISSUE TITLE
[Feature Request] Backup settings

### ISSUE THREAD

**Issue by sbadux** [home-sweet-gnome/dash-to-panel#517]
Hello,
it would be great to have a backup functions with an Export/Import backup feature. So an user can bring the same settings in all the PCs or back it up for future use.

Thanks a lot for this great extensions. It's super useful.

**Comment by charlesg99** [comment]
Hey sbadux, thanks for the suggestion! I'm not sure if this is necessary as it's pretty easy to export/import settings using dconf.

To export your settings to a "dtp_settings" file:
`dconf dump /org/gnome/shell/extensions/dash-to-panel/ > dtp_settings`

and then import them on another pc with:
`dconf load /org/gnome/shell/extensions/dash-to-panel/ < dtp_settings`

Not that "user friendly", but it gets the job done. What do you think?

Thanks!

**Comment by sbadux** [comment]
Hello, good to see that there is a way to backup my settings :) Anyway, IMHO, it would be great for all the users to have this feature in the GUI. Much easier to use and you don't have to remember dconf command line commands.

**Comment by catb0t** [comment]
Would you accept a pull request that just adds a button which (more or less) executes those commands?

**Comment by catb0t** [comment]
Let's go with your version, since it's mostly for the feature and I'm anyway inexperienced at extension development (so it will take longer)  :)

**Comment by charlesg99** [comment]
The import/export functionality was added to master, please let me know if it works for you! Thanks
