### ISSUE TITLE
How to upload a translation?

### ISSUE THREAD

**Issue by sbadux** [home-sweet-gnome/dash-to-panel#518]
Hello,
I've never used GitHub so I'm sorry to open this "fake" issue but I need help.
I've translated Dash to Panel in Italian and I want to upload the it.po file, but the file upload seems to be disabled and I can't write a private message to the maintainer. I've the it.po file ready but how can I send it?

Thanks

**Comment by charlesg99** [comment]
Yep looks good, Thanks!
