### ISSUE TITLE
Call for translation updates for v17

### ISSUE THREAD

**Issue by jderose9** [home-sweet-gnome/dash-to-panel#520]
We will be tagging v17 in about a week. If you'd like to submit an updated translation to cover the new configuration settings, it would be greatly appreciated. Thanks very much to all!

@frnogueira (pt_BR), @zeten30 (cs), @franglais125 (es), @LaurentTreguier / @SolarLiner (fr), @elsieholmes (uk), @hosiet (zh_CN), @jonnius (de), @urbalazs / @pappfer (hu), @crayxt (kk), @pkomur (pl), @AlexGluck / @GoodNike (ru), @TeknoMobil / @oltulu (tr), @sbadux (it), @sicklylife-jp (jp)

**Comment by TeknoMobil** [comment]
Hello there
Waiting for a new pot file

**Comment by AlexGluck** [comment]
@TeknoMobil Consider utilizing the Makefile. make potfile will regenerate the pot file and a following make mergepo will help you with msgmerge task.

**Comment by jderose9** [comment]
Thank you so much for all the submissions! It is very much appreciated.
