### ISSUE TITLE
Freeze when mouse horizontal scroll on windows preview

### ISSUE THREAD

**Issue by usbkey9** [home-sweet-gnome/dash-to-panel#528]
Hi Guys,

There is a small bug when I scroll horizontally using my mouse on windows preview:
It make system much slower and doesn't display preview anymore

![screencast_13-12-2018_12_21_06](https://user-images.githubusercontent.com/31854427/49935680-fb262080-fed1-11e8-99b6-08e8caf1a9e4.gif)

**Comment by charlesg99** [comment]
Hello usbkey9! Thanks for the report, could you please clarify "scroll horizontally using my mouse"? Do you mean using the mouse wheel while holding shift or do you have a mouse that has a mouse wheel with side buttons? I tried a to reproduce but coudn't, so I'm probably doing it wrong.

**Comment by usbkey9** [comment]
Hi @charlesg99,

I meen : a mouse that has a mouse wheel with side buttons like 
![image](https://user-images.githubusercontent.com/31854427/49943471-44816a80-fee8-11e8-9fdc-20b60af627ca.png)

**Comment by charlesg99** [comment]
Hey usbkey9, I found a mouse like this and I still can't reproduce the problem. Could you please check your logs and see if an error occurs when this happens? This command helps monitoring gnome-shell logs: `journalctl /usr/bin/gnome-shell -f -o cat` Thanks!

**Comment by usbkey9** [comment]
Hi @charlesg99 ,

Nothing appear in log =(

**Comment by markomarkovic** [comment]
I can confirm that it happens on the latest master branch, using Logitech MX Master side wheel. Nothing shows in the gnome-shell logs, icons and tasks disappear, everything just becomes really sluggish until the dash-to-panel extension is turned off, when everything goes back to normal. Turning extension back on, everything continues to be normal until the side-scroll event happens again.

I don't have window previews on, it happens when scrolling on the panel itself.

`xev` shows these events for side-wheel scrolling:

```
ButtonPress event, serial 34, synthetic NO, window 0x2200001,
    root 0x39f, subw 0x0, time 269020707, (136,70), root:(5807,1098),
    state 0x10, button 7, same_screen YES

ButtonRelease event, serial 34, synthetic NO, window 0x2200001,
    root 0x39f, subw 0x0, time 269020707, (136,70), root:(5807,1098),
    state 0x10, button 7, same_screen YES

ButtonPress event, serial 34, synthetic NO, window 0x2200001,
    root 0x39f, subw 0x0, time 269022314, (136,70), root:(5807,1098),
    state 0x10, button 6, same_screen YES

ButtonRelease event, serial 34, synthetic NO, window 0x2200001,
    root 0x39f, subw 0x0, time 269022314, (136,70), root:(5807,1098),
    state 0x10, button 6, same_screen YES
```
Button 7 is scroll-down, button 6 is up.

![peek 2018-12-30 12-33](https://user-images.githubusercontent.com/99233/50545512-896b0800-0c2f-11e9-9190-07cfb9f2054a.gif)

**Comment by jderose9** [comment]
I'm also unable to reproduce. Do you guys know if this is a new issue?

**Comment by usbkey9** [comment]
Hi @jderose9,

Just tested on Wayland, Ubuntu 18.10, Fedora 29 and bug still appear
What's your setup ?

Best

**Comment by jderose9** [comment]
I tested the same. But, I do not have these buttons bound out of the box.

Which package did you use to bind buttons 6&7 and what action do you have them tied to?

**Comment by usbkey9** [comment]
https://pypi.org/project/python-uinput/

Somewhere here I hope : https://github.com/tuomasjjrasanen/python-uinput/blob/master/src/ev.py

**Comment by charlesg99** [comment]
Thanks to @leebickmtu!
