### ISSUE TITLE
Significant lag when hovering over application icons

### ISSUE THREAD

**Issue by marcoms** [home-sweet-gnome/dash-to-panel#533]
This comes up after a while of using the extension, but can be temporarily mitigated by restarting the shell or unloading and reloading the extension using GNOME Tweaks.

Perhaps this is similar to #310, although the issue seems to be only with the panel - I haven't noticed the entire system lagging.

![laggy-panel-2018-12-21_16 55 01](https://user-images.githubusercontent.com/4211302/50354089-44194d00-0542-11e9-9704-2ac4a210a325.gif)

**Comment by charlesg99** [comment]
Hello marcoms, what gnome-shell version are you running? Thanks!

**Comment by marcoms** [comment]
I’m on 3.30

**Comment by nortexoid** [comment]
I've the same issue on Fedora 29, Gnome 3.30.2. My hardware is a Core i5 7200U with integrated graphics. Seems to be related to the slight highlight effect on hover. Happens also with the date and systray entries.

**Comment by marcoms** [comment]
I've had to switch to dash to dock cause I can't click on the app until the highlight appears, which slows me down a lot :/

**Comment by worldknote** [comment]
fedora silverblue 30, dash to panel v19.

i had the same problem. but only under wayland, not under xorg (here everything went smoothly). solution under wayland (worked for me): disable "display panel on all monitors". 

this was the main setting. and to be on the safe side, i have nothing but "override panel theme background opacity" & "animate opening of applications" activated. maybe a wayland problem.

**Comment by charlesg99** [comment]
Hello, I would think this is the same issue as #561. Gonna close this for now as the new window previews were added to master. Thanks!
