### ISSUE TITLE
Multi-monitor, secondary taskbar doesn't get updated.

### ISSUE THREAD

**Issue by markomarkovic** [home-sweet-gnome/dash-to-panel#535]
I've recently added a second monitor, and I've noticed several issues with multi-monitor support that could be related. I've tested this with 46628d9d47ab8458b6f5ae62cd602a3a7af6da94

Mostly, no matter the initial state of "Isolate monitors", the secondary taskbar doesn't get updated correctly after any action, until  I toggle the "Isolate" switch. This includes starting/quiting programs, moving them from one screen to another, moving them from one workspace to another, etc.

Here's the video illustrating the problems: https://photos.app.goo.gl/9XmvBzWNMHitF74v9

Here's my config:

    [/]
    focus-highlight-color='#eeeeee'
    hotkeys-overlay-combo='TEMPORARILY'
    show-status-menu-all-monitors=false
    primary-monitor=0
    group-apps-label-max-width=350
    dot-color-unfocused-1='#5294e2'
    dot-color-unfocused-2='#5294e2'
    dot-color-unfocused-3='#5294e2'
    dot-color-unfocused-4='#5294e2'
    focus-highlight=true
    group-apps-use-launchers=false
    leftbox-size=0
    show-show-apps-button=true
    group-apps=false
    show-favorites-all-monitors=true
    show-activities-button=false
    middle-click-action='LAUNCH'
    dot-color-1='#5294e2'
    dot-color-2='#5294e2'
    dot-color-override=false
    dot-color-3='#5294e2'
    dot-color-4='#5294e2'
    show-favorites=true
    focus-highlight-opacity=20
    showdesktop-button-width=1
    shift-click-action='MINIMIZE'
    leftbox-padding=-1
    panel-size=24
    stockgs-keep-dash=false
    group-apps-label-font-color='#dddddd'
    secondarymenu-contains-appmenu=true
    isolate-workspaces=true
    show-appmenu=false
    group-apps-use-fixed-width=true
    secondarymenu-contains-showdetails=false
    show-clock-all-monitors=false
    dot-size=0
    status-icon-padding=-1
    group-apps-underline-unfocused=false
    tray-padding=2
    click-action='CYCLE-MIN'
    location-clock='STATUSRIGHT'
    dot-style-focused='SOLID'
    group-apps-label-font-size=14
    isolate-monitors=true
    animate-show-apps=false
    shift-middle-click-action='LAUNCH'
    show-showdesktop-button=true
    show-window-previews=false
    appicon-margin=0
    dot-style-unfocused='SOLID'
    tray-size=0

**Comment by charlesg99** [comment]
Hello markomarkovic, thank you for the report. I tried your configuration as is and I can't reproduce the issue. Can you provide more information? What distro/gnome-shell version are you running? Xorg or Wayland? Do you see dash-to-panel related errors in your logs? Does it also happen when you disable every other extension?

Also, we utilize the same events as the workspace manager, so, when you drag a window on to the secondary monitor and it doesn't appear on the taskbar, is it correctly displayed in the overview when you press the windows key on your keyboard? Thanks!

**Comment by markomarkovic** [comment]
I'm using Debian sid, GNOME Shell 3.30.2 on Wayland. I've disabled all other extensions, and it's still happening. Workspace manager shows windows correctly when I'm moving them around. As far as I can see, the secondary taskbar just doesn't get updated visually, behind the scenes it gets updated -- e.g. when I turn "Display favorite applications on all monitors" on nothing visually changes but hovering over the space where the icons are supposed to be shows the correct tooltips for each icon, they're just not drawn.

    % lsb_release -a
    No LSB modules are available.
    Distributor ID:	Debian
    Description:	Debian GNU/Linux buster/sid
    Release:	unstable
    Codename:	sid

    % lspci | grep VGA
    00:02.0 VGA compatible controller: Intel Corporation Iris Graphics 540 (rev 0a)

    % gnome-shell --version
    GNOME Shell 3.30.2

    % loginctl show-session 2 -p Type   
    Type=wayland


Looking glass shows

    dash-to-panel@jderose9.github.com has not emited any errors

Please, let me know if/how I can give you any more info you might need.

**Comment by charlesg99** [comment]
Thank you @markomarkovic, I could reproduce the issue under these conditions:
- debian sid
- wayland
- the primary panel is on the primary monitor
- the secondary monitor has a smaller resolution than the primary panel

I did some tests and the modification from pull request #531 by @MartinPL seems to fix the issue on wayland! Since it just got merged to master, could you please pull/install again and see if that fixes it on your end? Thanks!

**Comment by markomarkovic** [comment]
Thank you, b1f31f487ec675317fa09965e65b80d59c0b2a53 seems to have fixed the issue, the secondary taskbar now repaints correctly and reacts to all the changes immediately.
