### ISSUE TITLE
The taskbar overlaps the rest of the panel

### ISSUE THREAD

**Issue by abakkk** [home-sweet-gnome/dash-to-panel#537]
When taskbar is well filled, it overflows. There is no actual scroll view in sight.

![screenshot](https://user-images.githubusercontent.com/33428071/50520624-b3062100-0ac1-11e9-8eb7-f7b3b6e8937c.png)

**Comment by charlesg99** [comment]
Thank you for the report abakkk! Yes it seems that I broke that when optimizing allocations (in 0c1ab4fcc748923ffaede239619b693c874fde9c) and never noticed this issue afterwards. I'll try your patch right away!

**Comment by charlesg99** [comment]
Hey abakkk! Some more commits were added to master to fix the scrollview on multi-monitor and to remove the right hand side offset. Do you think this is acceptable? Thanks!
