### ISSUE TITLE
gnome dash to panel: remove applications label

### ISSUE THREAD

**Issue by sarahwc5** [home-sweet-gnome/dash-to-panel#542]
I'm using Ubuntu with gnome and the dash-to-panel extension. On the bottom left, I have a 'Applications' label with a bottom arrow next to it, which is not clickable (see screenshot here: https://i.stack.imgur.com/x16xa.png). Next to it is the applications icon (9 dots) since I opted for the 'show applications icon' in the settings. How to get rid of the 'Application' label, which has no use and eats space?

**Comment by charlesg99** [comment]
Hey sarahwc5! Could you please check if the "Applications menu" extension is enabled on you system? It looks like another extension to me. Thanks!

**Comment by jderose9** [comment]
I got a separate report for this issue from I believe a different user, via the GNOME Extensions email form.

> What&#39;s wrong?
> The applications menu is dead.
> 
> 
> What have you tried?
> I have turned it on and off, uninstall, reinstall and yet noting happens when I click Applications menu.
> 
> Automatically detected errors:
> 
> GNOME Shell Extensions did not detect any errors with this extension.
> 
> Version information:
> 
>     Shell version: 3.28.3
>     Extension version: 17

**Comment by charlesg99** [comment]
I just tried on Ubuntu 18.04 and the extension "Applications menu" generates this error when clicking on its menu:

```
JS ERROR: TypeError: this._button.hotCorner is undefined
open@/home/cgagnon/.local/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com/extension.js:242:9
toggle@resource:///org/gnome/shell/ui/popupMenu.js:755:13
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
toggle@/home/cgagnon/.local/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com/extension.js:263:9
_onEvent@resource:///org/gnome/shell/ui/panelMenu.js:138:13
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
```

This happens even when dash-to-panel is disabled or on v16, so I don't think this issue is related to us. Would be better to open an issue over there https://gitlab.gnome.org/GNOME/gnome-shell-extensions.

Thanks!

**Comment by Llewellynvdm** [comment]
Nope... this must be with dash-to-panel, if I turn in off the application link goes away:

![image](https://user-images.githubusercontent.com/5607939/50725253-a4dc8400-1103-11e9-9c6c-b9b436ba08ae.png)

If I turn only the dash-to-panel back-on:
![image](https://user-images.githubusercontent.com/5607939/50725262-c50c4300-1103-11e9-8dae-a581fc762115.png)

The **Applications** menu is back and does nothing.

**Comment by Llewellynvdm** [comment]
So you just close the issue before any feedback? the issue is not resolved :-1:

**Comment by Llewellynvdm** [comment]
My apologies... I found the issue and is not dash-to-panel...

There was an extension called **Applications Menu** it was not on, but it still must have had some effect, I had to manually remove it from the `/usr/share/gnome-shell/extensions/` folder before it was no longer effecting the dash-to-panel.

it was called `/usr/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com` removing it resolved it for me :+1:

**Comment by charlesg99** [comment]
As a reference: https://gitlab.gnome.org/GNOME/gnome-shell-extensions/issues/85
