### ISSUE TITLE
Feature request: Add 'Toggle window (Minimize/Raise)' to 'Click action'

### ISSUE THREAD

**Issue by michael-schaller** [home-sweet-gnome/dash-to-panel#544]
It would be nice to have a ```Toggle window (Minimize/Raise)``` option for the ```Click action``` so that a window can be minimized with a click and then be re-activated with just another click. This would allow to quickly check the status of a window (raise) and then to switch back again (minimize). To implement this it looks like the extension would just need to check the ```minimized``` window property [1].

[1] https://developer.gnome.org/meta/stable/MetaWindow.html#MetaWindow--minimized

**Comment by jderose9** [comment]
Hi there! If I'm understanding properly, the "Cycle Windows + Minimize" option should do what you are looking for, at least in the scenario that you only have one window open for an application or are ungrouped. Or are you looking for all windows to be toggled simultaneously ?

**Comment by michael-schaller** [comment]
Oh! This does indeed work but I didn't even try it as the name of the option didn't seem like what I wanted. I sadly don't have an idea on how the name of the option could be improved. So I guess we can close this issue as is. Thanks for the help.

**Comment by CTimmerman** [comment]
![image](https://user-images.githubusercontent.com/9662163/69250638-5798c200-0bb0-11ea-82cf-fea2a9f0f25e.png)

That's the Windows feature i'm missing. The "Cycle windows + minimize" setting makes me lose the Chrome window i wanted to toggle, and "Toggle windows" hides the Chrome window under the active Chrome window as well.
