### ISSUE TITLE
Presets, example Windows 10

### ISSUE THREAD

**Issue by vanillajonathan** [home-sweet-gnome/dash-to-panel#546]
Maybe dash-to-panel should come with a list of presets?

Or maybe the wiki could have some presets that can be imported?

If anyone is interested, here are settings to resemble Windows 10.

```ini
[/]
animate-show-apps=true
appicon-margin=8
dot-color-1='#5294e2'
dot-color-2='#5294e2'
dot-color-3='#5294e2'
dot-color-4='#5294e2'
dot-color-unfocused-1='#5294e2'
dot-color-unfocused-2='#5294e2'
dot-color-unfocused-3='#5294e2'
dot-color-unfocused-4='#5294e2'
enter-peek-mode-timeout=500
hotkeys-overlay-combo='TEMPORARILY'
isolate-workspaces=false
leave-timeout=100
location-clock='STATUSLEFT'
multi-monitors=false
panel-position='BOTTOM'
panel-size=40
peek-mode=true
peek-mode-opacity=40
preview-middle-click-close=true
secondarymenu-contains-showdetails=false
show-activities-button=false
show-appmenu=false
show-apps-icon-file=''
show-favorites=true
show-show-apps-button=true
show-showdesktop-button=true
show-window-previews=false
show-window-previews-timeout=100
stockgs-keep-dash=false
taskbar-position='LEFTPANEL'
trans-use-custom-bg=false
trans-use-custom-gradient=false
trans-use-custom-opacity=false
trans-use-dynamic-opacity=true
```

**Comment by charlesg99** [comment]
Hi vanillajonathan, thanks for the suggestion. Since the readme was updated for v17, the settings to recreate the examples seen under "Customizable appearance" can be found here: https://github.com/home-sweet-gnome/dash-to-panel/tree/master/media/sources/D2P_import%20settings

If you are inclined to modify the wiki, please feel free to clone it, do some changes and I'll be happy to import the modifications. Thanks!

**Comment by jderose9** [comment]
Thanks @vanillajonathan . Charles had suggested similar recently. I was intending to provide preset choices for the panel layout (taskbard, clock, status menu positions) in an upcoming release. Does it seem important to include behavioral choices in that as well? I was hoping that sane defaults would cover most users, but perhaps that's not the case.

**Comment by vanillajonathan** [comment]
Preset choices for the panel layout sounds good.
Not sure exactly what behavioral choices mean.
Sane defaults is important.

Just some quick way to make it resemble Windows 10 so someone from such a background can feel at home.

**Comment by jderose9** [comment]
Actually.. Looking more closely at your config, it looks pretty similar to the current defaults. We've informally been following Windows defaults when possible thus far (and indeed, the extension was initially created to ease my transition from Windows). If there's something that can be changed to improve parity, I think it makes sense to do so.

I think we should definitely add links out to the example settings import files.. (Maybe README could have a link to a new wiki section? does that make sense?)

**Comment by stefan-kern** [comment]
not fully related, but this is the closest issue i found. im wondering, where can i find the configs? reinstalling the plugin does not reset the config, and i can't locate the settings file to delete and regenerate. i also could not find a global "restore defaults" setting.

**Comment by charlesg99** [comment]
Hello stefan-kern, the option isn't in dash to panel settings, but you can reset your configuration by running `dconf reset -f /org/gnome/shell/extensions/dash-to-panel/` in a terminal. Thanks!

**Comment by vanillajonathan** [comment]
@jderose9 I had to change the `panel-size` (from its default of 48) to 40 be the same as Windows 10.
