### ISSUE TITLE
Inconsistent Overview Application Icons Animation

### ISSUE THREAD

**Issue by leebickmtu** [home-sweet-gnome/dash-to-panel#550]
Somewhat related to issue #49 but not fixed in it,

Different behavior is observed regarding the origin location of the icon spread animation depending on how it was triggered.

**Icon spread animation originates properly (spreads out from overview button)**
A. We click the 9-dot button

**Icon spread animation originates improperly (spreads from other location)**
A. We click the 9-dot button when we are in windows overview
B. We press 9-dot button to leave application overview

I'm seeing this behavior in GNOME shell 3.30.2 with Dash-to-Panel 17

**Comment by charlesg99** [comment]
Hello leebickmtu! Thank you for reporting this, I could reproduce the issue using multi-monitor. I don't use the spring animation and didn't (forgot) to test with it enabled. A fix for this was just added to master if you want to have a look. Thanks!

**Comment by leebickmtu** [comment]
Master branch works good for me now. Thanks
