### ISSUE TITLE
cannot re-install dash to panel

### ISSUE THREAD

**Issue by krostifangers** [home-sweet-gnome/dash-to-panel#554]
Hello
After updating dah-to-panel, I realized that it contained some issues, like unability to scroll over applications, and so on. I then removed this extension in order to rollback. Tying to rollback from anterior version on github did not work. Extension did not appear in list on gnome-tweak-tools.  
Then I tried to re-install from the website (gnome-shell-extensions) but the On/Off button automatically turns back to Off. 
My computer is running on Debian 9 with Gnome 3.22
thank you in advance
christophe

**Comment by charlesg99** [comment]
> some issues, like unability to scroll over applications, and so on

Hello christophe! I would much rather help solving these instead. Could you elaborate? Also if the extension can't enable (On/Off button automatically turns back to Off), there probably is an error that is added to your logs when it happens... could you look at this by running `journalctl /usr/bin/gnome-shell -f -o cat` beforehand?

To answer your question, if you must go back to v16, you can do so by following those steps:
 - close gnome-tweak-tools
 - in a command line, `cd` to a folder in which you want to add the dash to panel sources (can be anywhere)
 - run `git clone https://github.com/home-sweet-gnome/dash-to-panel.git && cd dash-to-panel`
 - run `git checkout v16 && make install`
 - restart gnome-shell with `ALT-F2` followed by `r` then `ENTER`, or by logging out/in if you're on Wayland.
 - open gnome-tweak-tools and enable dash to panel.

Thanks!

**Comment by charlesg99** [comment]
Hello christophe, some fixes were added to master, could you please [install the latest development version](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github) and see if that fixes your issue on gnome 3.22? Thanks!
