### ISSUE TITLE
Main panel showing on wrong monitor with dual monitors above each other

### ISSUE THREAD

**Issue by 33Fraise33** [home-sweet-gnome/dash-to-panel#555]
Hello,

I'm running gnome 3.30 with the latest version of dash to panel. I have 2 monitors, importantly: above each other, not next to each other.
The only plugin I'm currently running is dash to panel.

When my taskbar is at the bottom and I click on the main panel on my upper monitor the panel pops up on my lower monitor. Is it possible to force the panel to open on the monitor it was requested on?

**Comment by jderose9** [comment]
Hello @33Fraise33 ! When you say "panel" I believe you are talking about opening the status menu (network, audio, user settings)? or opening the clock/calendar? Is that correct?

**Comment by 33Fraise33** [comment]
Hello @jderose9,

yes that is correct. The clock & calendar actually does this as well I just noticed.

**Comment by charlesg99** [comment]
Hello 33Fraise33, a fix for this was added to master. Could you please install it and see if that resolves the issue? Thanks!

**Comment by 33Fraise33** [comment]
@charlesg99 can confirm this fixes my issue!

**Comment by wiktor-k** [comment]
I was about to report the same exact issue, but I see it was reported... and already fixed in master! Just... wow! :clap: 

Out of all Gnome extensions I've installed (and there were many) there is no single one that has this level of quality and professionalism as Dash to Panel. Thank you!

**Comment by charlesg99** [comment]
Great, thanks for the feedback and the kind words!
