### ISSUE TITLE
extension stop working

### ISSUE THREAD

**Issue by rettoo** [home-sweet-gnome/dash-to-panel#556]
The latest release can result in the extension reverting back to a vanilla setup. This happens intermittently when waking from a sleep state. When opening "Dash to Panel", it is unresponsive to any user input. 

The only solution that I have found is to re-start the system.

**Comment by charlesg99** [comment]
Hello rettoo, could you please [install the latest development version](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github) and see if the issue persists? Thanks!

**Comment by rettoo** [comment]
I do not think the install worked :

david@Jaws:~/Downloads/dash-to-panel-master$ git init
Initialized empty Git repository in /home/david/Downloads/dash-to-panel-master/.git/
david@Jaws:~/Downloads/dash-to-panel-master$ make install
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
rm -fR ./_build
mkdir -p _build
cp extension.js stylesheet.css metadata.json COPYING README.md appIcons.js convenience.js panel.js panelManager.js proximity.js intellihide.js panelStyle.js overview.js taskbar.js transparency.js windowPreview.js prefs.js utils.js Settings.ui _build
mkdir -p _build/img
cd img ; cp highlight_stacked_bg.svg ../_build/img/
mkdir -p _build/schemas
cp schemas/*.xml _build/schemas/
cp schemas/gschemas.compiled _build/schemas/
mkdir -p _build/locale
for l in po/de.mo po/cs.mo po/uk.mo po/hu.mo po/zh_CN.mo po/ja.mo po/pl.mo po/it.mo po/fr.mo po/kk.mo po/ru_RU.mo po/tr.mo po/es.mo po/pt_BR.mo ; do \
	lf=_build/locale/`basename $l .mo`; \
	mkdir -p $lf; \
	mkdir -p $lf/LC_MESSAGES; \
	cp $l $lf/LC_MESSAGES/dash-to-panel.mo; \
done;
rm -rf /home/david/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com
mkdir -p /home/david/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com
cp -r ./_build/* /home/david/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/
rm -fR _build
echo done
done

**Comment by charlesg99** [comment]
Hello rettoo, yeah I think the easiest way to install is to clone the repository using git, not to download it (the error you see is because we are using git's HEAD hash number to set the extension version number during the make install... this isn't available when downloading the sources).

Please follow the steps from the link I posted earlier, that should work properly. Thanks for your help!

**Comment by rettoo** [comment]
Installed using the method you outlined. Extension says it is version 9999. I continue to have the same issue.

**Comment by rettoo** [comment]
Update : On the first day that I installed the extension I had the same issue. However, since then I have not had any problems. Except for system updates, via Ubuntu, nothing has changed. Will let you know if anything changes.

**Comment by charlesg99** [comment]
Great, let us know if you find any more issues, thanks!
