### ISSUE TITLE
GNOME 3.32: this._allocate is not a function

### ISSUE THREAD

**Issue by alex285** [home-sweet-gnome/dash-to-panel#559]
on GNOME 3.31.4 after https://github.com/home-sweet-gnome/dash-to-panel/commit/a39cdc41d8e29a1357ee26861084558e99c684b4#diff-2599b72aecbef8f8725aa5c4bf2fc0a0R135

![screenshot from 2019-01-11 15-08-37](https://user-images.githubusercontent.com/11244308/51035538-f7f68100-15b2-11e9-9030-4177a653fbdf.png)

**Comment by charlesg99** [comment]
Hello alex285, thank you for the report! Sorry I don't yet have the reflex to test on gnome > 3.30 :) This will likely change soon as, now that the v17 kinks are getting ironed out, I should soon look into the padding problem. 

The issue here should be fixed now. Thanks!

**Comment by alex285** [comment]
yeap, https://github.com/home-sweet-gnome/dash-to-panel/commit/6e53889082eef4eed9cdc1c496e90a6f8450d1fd fixed it; thanks!

**Comment by alex285** [comment]
> This will likely change soon as..

https://twitter.com/BabyWogue/status/1083752019058397184 🙃
