### ISSUE TITLE
Laggy mouse when hovering over taskbar [Wayland]

### ISSUE THREAD

**Issue by VladimirP1** [home-sweet-gnome/dash-to-panel#561]
For some time I have been running gnome-shell with dash to panel extension.
After a few hours of usage, while moving the mouse over the taskbar, I experience severe mouse lag.
I know, it is connected with poor architecture of gnome shell(no separation between the compositor and the UI) and with the fact that gnome wayland session utilises a software pointer.
Can the usability be improved, without total GNOME rewrite? 
[Video, demonstrating the lag](https://youtu.be/5g-_y9s1YaA)

**Comment by VladimirP1** [comment]
And, oh yes, it is gnome-shell 3.30.2 on Fedora 29.
And here is the list of other enabled extensions:
- Alt tab workspace
- Arc menu
- Background logo
- Block caribou
- Caffeine

**Comment by VladimirP1** [comment]
This *May* be a duplicate of #530

**Comment by VladimirP1** [comment]
My machine is a dell xps 13, with i7-8550U, so I do not think, that this can be a problem.

As I understand, gnome on Xorg uses hardware cursor acceleration and the pointer is drawn by the X server, while on wayland it is drawn by the compositor, in the same **thread** with the UI. That's why, any 3D pipeline stall causes mouse pointer lag.

So in fact, every operation in the JS engine stalls the whole 3D pipeline, and nothing can be done about it, as I understand.
But I am sure something can be done to minimize the lag.

[Demonstration of 3d pipeline stalls on X11](https://youtu.be/8y2Sc1Mqrdo)

References:
https://www.phoronix.com/scan.php?page=news_item&px=GNOME-3-Hungry-For-Pi
https://bugzilla.gnome.org/show_bug.cgi?id=745032#c85
https://wiki.gnome.org/Initiatives/Wayland/GnomeShell/GnomeShell4

**Comment by jderose9** [comment]
I would love to reproduce this one too. @VladimirP1 I've got access to the same device (1080p non-touchscreen model), with fedora 29 installed, but haven't noticed this lag. Is there something you can do to force it to occur consistently?

**Comment by VladimirP1** [comment]
I have disabled every extension except dash to panel, running for about 6 hours, no lags so far. So maybe, the lag is caused by some other extension, but I have to pause my investigation, cause I have to prepare for my university exams.

**Comment by jderose9** [comment]
@VladimirP1 I'd be curious if you are able to narrow it down to a particular extension, in the case that there is a conflict when both are installed.

**Comment by VladimirP1** [comment]
I have been enabling extensions one by one and found out that enabling the **Block caribou extension** triggers the lag, which is a workaround for GNOME not having an option to disable the popping-out on-screen keyboard (when touchscreen is used).
There's nothing I can say about reproducing it, I simply use the shell until it becomes too laggy, but I doubt that this can be reproduced on a non-touch machine.

**Comment by jderose9** [comment]
Do you know if it occurs with that extension enabled but dash-to-panel disabled?

**Comment by VladimirP1** [comment]
I do not, but now I see that the lag only occurs while only hovering over the icons of runnig/favourite apps.
By the way, I have just read that the bug has been fixed https://github.com/keringar/cariboublocker , but I had not yet understood was it fixed in Ubuntu only or upstream and how.

**Comment by VladimirP1** [comment]
Do all the extensions get a disable() call on screen lock?

**Comment by charlesg99** [comment]
@VladimirP1 To the best of my knowledge, yes, all extensions are disabled on screen lock. Thanks!

**Comment by jgillich** [comment]
I have the same issue. Hovering the corner causes the mouse to lag and the activities overview does sometimes not toggle. I've only recently switched to Wayland, never experienced this with Xorg.

System is Fedora 29 Silverblue/Atomic. I don't use any of the mentioned extensions and don't have a touchscreen so I'm not sure what's going on here. It does not cause a spike in CPU usage so I don't think this is #530.

**Comment by antonvalletas** [comment]
I am also having this issue on the taskbar above all, on an XPS 15 9570, and again, this only happens on Wayland. It is completely smooth on X.org

**Comment by nortexoid** [comment]
I had the same issue as well on Fedora 29, wayland session.

**Comment by digiberk** [comment]
Same issue here. On Fedora 30 with GNOME 3.32 running only Dash to Panel as my extension. The cursor/mouse lag is only present under Wayland. When running Xorg, there is no lag but GNOME has other problems under Xorg for me. Also, I'm running an i5 8250u with integrated graphics. With GNOME 3.32, the performance is better but the lag is still there. When I was on 3.30, dash-to-panel under wayland was unusable for me.

**Comment by charlesg99** [comment]
A new version of the window previews is available. If someone who can reproduce the Wayland lag could try it, I'd be interested to know if it helps. More info [here](https://github.com/home-sweet-gnome/dash-to-panel/issues/611#issuecomment-495455229). Thanks!

**Comment by charlesg99** [comment]
The new version of the window previews is available on master. Please try them out and open a new issue if the lag is still present. Thanks!

**Comment by PetrBlaha** [comment]
For me, this occures only when o open for example notification / calendar popup from top bar (keep it open) and then hover something else (for example wifi icon in top bar). And yes this is happening only on Wayland (Xorg is ok). (dash-to-panel, Fedora 30, thinkpad t480)
