### ISSUE TITLE
dash-to-panel is incompitable with virt-viewer

### ISSUE THREAD

**Issue by crab2313** [home-sweet-gnome/dash-to-panel#564]
There is a problem with virt-viewer (not virt-manager). Here are the steps to reproduce it:

1. launch a virtual machine with SPICE server enabled (so we can connected it with SPICE protocol client)
2. connect the virtual machine by remote-viewer (in my case, simply run `remote-viewer spice://localhost:5900`)
3. click the maximum button of the remote-viewer window
4. try to click some preview menu , and there is a high possibility the whole desktop will freeze. The cursor is movable but the mouse click event is lost. The keyboard is grabbed by remote-viewer so that all your key press is passed to the virtual machine.

I find a way to recover from this situation after some research. Just press Ctrl + Alt, then Alt+Tab. It seems that the keyboard is grabbed by remote-viewer, but the focus is not. The debug log of remote-viewer (remote-viewer --spice-debug) shows that remote-viewer receives no mouse event in this situation.

I can easily reproduce the problem on Centos 7 (gnome 3.22) and the latest archlinux (gnome 3.30) with the latest git master branch.

**Comment by charlesg99** [comment]
Hello, I don't quite understand the problem, could you maybe post a video of what you're experiencing? We changed the window previews a while ago, maybe this got fixed? Thanks!
