### ISSUE TITLE
Windows Overview Animation Choppy

### ISSUE THREAD

**Issue by ZOezdem** [home-sweet-gnome/dash-to-panel#565]
If the windows overview is entered via the super key the animation is missing/choppy.  
When using it via hot corner it is smooth.

Fedora 29
GNOME Shell version 3.30
Dash-to-Panel version: 17

**Comment by charlesg99** [comment]
Hey ZOezdem, thank you I could reproduce this. A fix was added to master, could you check if it solves the problem on you machine? Thanks!

**Comment by ZOezdem** [comment]
Hey charlesg99, the issue has been solved. Thanks a lot for the fast response.
