### ISSUE TITLE
[Feature request] Use system scaling across multiple monitor resolutions

### ISSUE THREAD

**Issue by huntie** [home-sweet-gnome/dash-to-panel#568]
The image below shows my HiDPI laptop (2x density, left) connected to an external 1920x1080 display (primary GNOME display, 1x density, right).

Dash to Panel scales appropriately using GNOME's display settings when I'm using either display independently, however ignores scaling differences on other displays (left). Ideally, the panel on my laptop's display should be scaled appropriately at 2x (as with the GNOME Terminal window). For now, I settle with enabling the panel only on the primary display.

![screenshot from 2019-01-20 17-56-09](https://user-images.githubusercontent.com/2547783/51443182-ead94080-1cdc-11e9-99e3-54113f7b8ac7.png)

Massive fan of Dash to Panel by the way, **thank you** maintainers.

**Comment by charlesg99** [comment]
Hello huntie, thank you for bringing that up. Just wondering if the default gnome-shell top panel scales the same way as dash to panel when both monitors are connected? (sorry I don't have a hidpi screen to test against). I'm not (yet) aware of a way to scale gnome-shell "per monitor", only globally. I know GDK has methods to do so, but I'm not sure if these functionalities are exposed to the js layer. Thanks!

**Comment by charlesg99** [comment]
Maybe this [gnome-shell issue](https://gitlab.gnome.org/GNOME/gnome-shell/issues/974) is related?

**Comment by charlesg99** [comment]
Saw this go by, maybe it helps? https://www.reddit.com/r/gnome/comments/avlhi9/dual_monitor_scaling_one_hidpi_and_the_other_not/

**Comment by charlesg99** [comment]
Closing for now as it is an upstream issue. Thanks!
