### ISSUE TITLE
[Feature Request] Intellihide panels which aren't on the primary monitor

### ISSUE THREAD

**Issue by eyal0803** [home-sweet-gnome/dash-to-panel#569]
I have 3 monitors side-by-side with the middle one being the primary monitor.
I like having the panel always shown so I'm able to glance down and see the time etc.
I also like having the panel on all monitors so I can easily access it on the current monitor.
What I don't like is having the panel take up screen real estate on secondary monitors.

Could we have an option in the "Panel Intellihide" options to enable Intellihide only for secondary monitors?

**Comment by charlesg99** [comment]
Hello eyal0803, thank you for the suggestion! This feature was just added to the master branch, please install the latest development version and let us know if this suits your need. The new switch can be found in the intellihide options. Thanks!

**Comment by eyal0803** [comment]
This is exactly what I had in mind! A huge thanks to you and to whoever developed this!
