### ISSUE TITLE
[Feature Request] Go to last app if only 1 instance of app otherwise cycle

### ISSUE THREAD

**Issue by nealot** [home-sweet-gnome/dash-to-panel#570]
Hi, I would like to suggest a behavior where clicking the active app icon returns to the last focused app instead of minimizing. If there is more than one instance of the app, then it should just cycle. Ideally, this behavior would work with isolated workspaces and the 1-9 keyboard shortcuts.

**Comment by jderose9** [comment]
Hi @nealot! This should be the behavior for the click action setting "Cycle windows + minimize" on the Behavior tab (This is actually the default setting). Which setting are you currently using?

**Comment by nealot** [comment]
I'm using Cycle Windows because I found the minimizing disorienting (I'm transitioning from i3wm). I've noticed that it's possible to minimize all windows, which is something I don't like; I'd much prefer it if I didn't have to see my wallpaper. The workflow I'm used to is this:

1. Raise window
2. Cycle instances if more than one, otherwise raise previous app

Is this behavior possible?

**Comment by jderose9** [comment]
Oh so you want to raise a different application than the icon you clicked on?

**Comment by jderose9** [comment]
Have you tried the new "Toggle single / preview multiple" option in the `master` branch? It may be close enough to what you are looking for, though it sounds like you really want "Toggle single / cycle multiple"?

**Comment by nealot** [comment]
Wouldn't that just be "cycle-windows + minimize"? On second thought, I think I'm just going to have to change my workflow to align with gnome's. Closing this request as I'm satisfied with the options already provided. Thanks for the guidance!
