### ISSUE TITLE
It's not a mistake, it's a proposal.

### ISSUE THREAD

**Issue by lordgault** [home-sweet-gnome/dash-to-panel#575]
It's not a mistake, it's a proposal.
First of all thank you again for the V18 version that fixes the bug with multi monitors. Returning to the subject I wanted to propose an improvement that I think is interesting.  It has to do with the menus of the system tray, clock and others. The improvement would be to isolate the menu that is displayed when we click on them. Imagine I want to go to the Gnome options on the left side of the drop-down menu. I have to lift the pointer almost horizontally and then move it vertically until I get to the options icon because if the pointer touches the clock it displays the clock menu. 
https://youtu.be/E_Eoh9bRvxA

**Comment by charlesg99** [comment]
Hello lordgault, thank you for the suggestion. I'm gonna close this as this is a duplicate (I think) of #435, so please head over there to contribute further. A fix for this was just added to master if you want to check it out! Thanks!
