### ISSUE TITLE
Remove preview border

### ISSUE THREAD

**Issue by brofjst** [home-sweet-gnome/dash-to-panel#576]
Hi!
Could you remove the border around the window preview? it's annoying and useless (imho), i'd like something like windows where the preview is composed only by the application's preview.
[example](https://i.ibb.co/Dz1NT7Z/yolo.png)
Btw thanks for this extension, it's great!

**Comment by cbmarc** [comment]
It's a good idea but I'd add it as an option.

**Comment by Lucapz** [comment]
Great idea.

**Comment by charlesg99** [comment]
Hello, new optionally border-less window previews are now available on master. Please try them out! Thanks!

**Comment by hkyq** [comment]
@charlesg99 Where is this option?

**Comment by charlesg99** [comment]
@hkyq This is currently on the [master branch](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github) and should be released soon on [e.g.o.](https://extensions.gnome.org/extension/1160/dash-to-panel/) with v20. The option can be found in the window preview options of Dash to Panel settings:

![image](https://user-images.githubusercontent.com/33044886/61317583-44748080-a7d1-11e9-85b7-48c109fd6411.png)

![image](https://user-images.githubusercontent.com/33044886/61317610-56562380-a7d1-11e9-8933-3601b5aa5b74.png)

Thanks!

**Comment by hkyq** [comment]
Ah I wasn't aware master wasn't pushed yet. This looks so much better! Thanks a ton. Also, is there a way to change the peek close button icon theme?

@charlesg99

**Comment by charlesg99** [comment]
Glad you like it :) Are you referring to the close button on the window preview frame? If so, this button comes from your current theme (same as the one used in the overview when hovering windows). Changing your theme should also change the close button. Thanks!
