### ISSUE TITLE
v18 not on GNOME Extensions?

### ISSUE THREAD

**Issue by DragoCubed** [home-sweet-gnome/dash-to-panel#577]
The latest on GNOME Extensions is v17 but it says here that v18 is the latest. Is there some review process for updates or something?

I'm sorry if I was not meant to make an issue for this.

**Comment by charlesg99** [comment]
Hello DragoCubed! 

Yes there is a review process when submitting a new version on e.g.o (extensions.gnome.org). Normally this process takes about a week, but for some reason this time it is much longer. You can view the e.g.o pending reviews [here](https://extensions.gnome.org/review/), although it doesn't provide much information I'm afraid. 

If you want to stay up to date as much as possible, I encourage you to [install the latest master](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github) and pull/install occasionally. This is quite easy with git and it helps us testing the new fixes and features.  

Thanks!

**Comment by DragoCubed** [comment]
Thank you! :)
