### ISSUE TITLE
Opening more than 4 windows causes gnome to crash.

### ISSUE THREAD

**Issue by jakerambo** [home-sweet-gnome/dash-to-panel#580]
Example open 5 windows in chrome gnome crashes, forces you to login again and all applications are closed. This doesn't happen when dash to panel is removed.

**Comment by jakerambo** [comment]
The issue is not present in version 16.

**Comment by charlesg99** [comment]
Hello jakerambo, thank you for the report. We are aware of this issue and it's been fixed for a while now, but the new version ([v18](https://extensions.gnome.org/review/8933)) hasn't been released on e.g.o yet. Hopefully it will be reviewed/released soon! In the meantime, you could install the latest master to resolve the issue. Please see #573 and #552 as references. Thanks!

**Comment by b00f** [comment]
May you can email them to publish the new version sooner. This issue is a big pain!
