### ISSUE TITLE
Issue / Feature Request

### ISSUE THREAD

**Issue by Fwardalonious** [home-sweet-gnome/dash-to-panel#581]
I'm not sure what category I should place this in.

When I have many windows open, dash to panel does not correctly scale the icons / nor allow you to scroll - it simply places the icons behind your dash/tray icons making it impossible to select your open applications. 

Photo attached to demonstrate, is there a way to fix this? If not, there should be a feature added to allow for scrolling between open windows as the normal dock allows. 

![imagen](https://user-images.githubusercontent.com/29343222/52645165-d6383480-2ea5-11e9-9d39-b50977b85f8e.png)

**Comment by jderose9** [comment]
Thanks for reporting this @Fwardalonious . This issue should actually be fixed already in the latest `master` branch. If you would like to verify, you can install following [these instructions](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github).

We've submitted the new version to extensions.gnome.org, but they have been short on qualified reviewers to process new submissions so it is taking a very long time.
