### ISSUE TITLE
Feature Request: Add an option in settings to sort not running icons to the left

### ISSUE THREAD

**Issue by cbmarc** [home-sweet-gnome/dash-to-panel#583]
Hi,

When using un-grouped icons (with text to the right of a running icon) such as in KDE Plasma, running icons mix up with not running ones. [Here you can see an image of such a thing](https://ibin.co/4XlMGZqO0bNa.png).

This is not bad, I know it's the default thing for grouped icons and it is as this in most docks. So my feature request is to add a setting to provide this functionality of moving not running (favorite) apps to the left. [Here you can see an image of how I like it](https://ibin.co/4XlNfgakKjVL.png).

If you need help I will be more than happy to discuss this with you to know what the best solution is, if you think this is an option worth having for everybody (as a setting). But for me it bugs me, so just to fix myself I developed a small fix for it, but would like it as a feature.

Thanks!

**Comment by Lucapz** [comment]
https://github.com/home-sweet-gnome/dash-to-panel/issues/513

/me points ---------------^ . :)

People might disagree but i think "use the favorite icons as application launchers" should be enabled as the default setting as i can't see anyone making sense of a jumbled set of icons?

When it's enabled it is a thing of beauty and acts just like windows and all the icon positions make sense. :)

**Comment by cbmarc** [comment]
Oh! I didn't notice that setting. Ok this is better, but not exactly what I was referring to (pretty similar though). I agree about the setting being enabled by default.

What I mean is a setting that enables this behaviour:
- I have a chrome launcher.
- When I click on the chrome launcher, the launcher dissapears and moves to the right with the running windows.
- Upon closing chrome, it returns to its place in the launchers part.

Maybe it could fit in the grouped applications settings under a name such as "Hide launcher icon when the application is running", only check-able if the "Use the favorite icons as application launchers" option is checked.

Does it make sense? This way the taskbar is less cluttered.

**Comment by Lucapz** [comment]
That's odd as with Ubuntu 18:10 with "use the favourite icons as application launchers" the icons stay on the left such as firefox and doesn't move to the right or disappear when you open a running window?

**Comment by cbmarc** [comment]
What is odd for some, might be right for others. Just an option :slightly_smiling_face: 

But ofc, if most people find this odd I can live with the classic launcher style or develop my own patch for personal use :) I was just thinking on saving space since I usually work with lots of windows and like this setup.

**Comment by Lucapz** [comment]
What i'm saying is odd is that your launch icon is moving and disappearing when the setting above is supposed to fix this and stop the icons moving around in the taskbar as a jumbled mess?

It solved the issue for others including myself so we need to find out why yours still moves about and disappears?

**Comment by Lucapz** [comment]
With the above enabled Icons that are not running stay on the left and never move , running icons appear to the right.

If you don't have that behaviour then something is wrong , maybe you have found a bug?

**Comment by cbmarc** [comment]
Oh nonono sorry for the confussion. The above screenshot is not a bug, it's actually that I coded in my local the way I wanted it to behave. Let's just close the issue as it is ok with the launchers as it is :)

Sorry for the confussion

**Comment by jderose9** [comment]
@cbmarc I'm fine with leaving this open if you think it should be in the official release. And since it sounds like you've completed the work, a pull request is certainly welcome!

**Comment by Lucapz** [comment]
It would give some power users more space to use @cbmarc patch rather than the fixed launcher to keep unused icon to the left.
