### ISSUE TITLE
hundreds of gnome-shell warnings: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

### ISSUE THREAD

**Issue by asegarra** [home-sweet-gnome/dash-to-panel#585]
Running Gnome 3.30.2 and version 18 of dash-to-panel, after enabling I get flooded with 

> g_object_unref: assertion 'G_IS_OBJECT (object)' failed

 every time I close an app, even happens if I copy text from gnome terminal.

**Comment by charlesg99** [comment]
Thank you for the report asegarra! Yes I see the same error, it seems to be caused by the new use of Atspi introduced in bc82e08dd1109aa339119f364ce524396827a74f. I'll try to fix that!

**Comment by charlesg99** [comment]
Hey asegarra, I couldn't find a way to use atspi without those errors, so I replaced it by shell-global to solve the issue you reported. Could you please pull/install again to confirm that it removes the log errors on your system? Thanks!

(Atspi [issue upstream](https://gitlab.gnome.org/GNOME/gnome-shell/issues/998))

**Comment by asegarra** [comment]
Hi, I can confirm I no longer see the errors. Thanks!

**Comment by charlesg99** [comment]
Great, thanks for the feedback!
