### ISSUE TITLE
Panel transparency lost when lock screen with maxmized window left

### ISSUE THREAD

**Issue by guoqiyi** [home-sweet-gnome/dash-to-panel#586]
I opend the "cover backgroud tranparency" option in the settings,and set tranparent digree to 0,so the panel looks totally tranarent.But everytime after I locked screen with maxmized windows left and then log in,the panel became total blcak and change the setting dosen't affect.Only after I closed all maxmized windows then locked screen and log in again,the panel will become nomal as before.Is that a bug or someting wrong with my settings ?

**Comment by charlesg99** [comment]
Hello guoqiyi, thank you for the report. I can't reproduce that so far, could you please tell us a bit more about your setup? What gnome-shell version are you on? Which dash-to-panel version? Did you enable "dynamic background opacity"?

Also, could you reproduce the issue by locking/unlocking and then send us the output of `journalctl --since="10 minutes ago" /usr/bin/gnome-shell`

Thanks!

**Comment by guoqiyi** [comment]
Thanks for your response,my linux distribution is archlinux and the gnome version is 3.30,dash-to-panel version is 17  which is downloaded from official https://extensions.gnome.org,my setup is like following:
![screenshot from 2019-02-27 23-58-32](https://user-images.githubusercontent.com/3457554/53504867-bcc1fa00-3aed-11e9-97bd-7dc9f81524c1.png)
Archlinux's gnome-shell log is full of errors,it's too large to paste here,maybe it is not the extension'bug but the Arch system,maybe I'll try another linux distribution like fedora to check it.

**Comment by guoqiyi** [comment]
I tried ubuntu 18.10,still have the same issue,here is my gnome-shell log:
-- Logs begin at Sat 2018-05-05 10:30:05 CST, end at Sat 2019-03-02 15:30:41 CST. --
Mar 02 15:29:32 ubuntu org.gnome.Shell.desktop[9223]: [9803:9803:0302/152932.255557:ERROR:http_bridge.cc(126)] Not implemented reached in virtual void syncer::HttpBridgeFactory::OnSignalReceived()
Mar 02 15:29:32 ubuntu org.gnome.Shell.desktop[9223]: [9803:9827:0302/152932.391837:ERROR:browser_process_sub_thread.cc(209)] Waited 22 ms for network service
Mar 02 15:29:34 ubuntu gnome-shell[9223]: Object St.Bin (0x55c165b1f460), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: == Stack trace for context 0x55c1620801b0 ==
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #0   55c166cbec10 i   /home/u/.local/share/gnome-shell/extensions/windowoverlay-icons@sustmidown.centrum.cz/extension.js:263 (7f77b418a430 @ 129)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #1   55c166cbeb50 i   resource:///org/gnome/shell/ui/extensionSystem.js:83 (7f77b5c59160 @ 436)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #2   55c166cbead0 i   resource:///org/gnome/shell/ui/extensionSystem.js:354 (7f77b5c59ca0 @ 13)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #3   7ffcdc5bf8a0 b   self-hosted:261 (7f77b5ec1dc0 @ 223)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #4   55c166cbea50 i   resource:///org/gnome/shell/ui/extensionSystem.js:353 (7f77b5c59c10 @ 64)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #5   55c166cbe9d0 i   resource:///org/gnome/shell/ui/extensionSystem.js:371 (7f77b5c59d30 @ 87)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #6   7ffcdc5c09e0 b   resource:///org/gnome/gjs/modules/signals.js:128 (7f77b5ec18b0 @ 386)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #7   7ffcdc5c1600 b   resource:///org/gnome/shell/ui/sessionMode.js:208 (7f77b5b41dc0 @ 254)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #8   7ffcdc5c2280 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f77b5eb0b80 @ 71)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #9   55c166cbe890 i   resource:///org/gnome/shell/ui/sessionMode.js:170 (7f77b5b41b80 @ 40)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #10   7ffcdc5c3200 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f77b5eb0b80 @ 71)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #11   55c166cbe7e8 i   resource:///org/gnome/shell/ui/screenShield.js:1282 (7f77b5b28af0 @ 188)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #12   7ffcdc5c4180 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f77b5eb0b80 @ 71)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #13   55c166cbe738 i   resource:///org/gnome/shell/ui/screenShield.js:1331 (7f77b5b28b80 @ 391)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #14   7ffcdc5c5100 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f77b5eb0b80 @ 71)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #15   55c166cbe6b0 i   resource:///org/gnome/shell/ui/shellDBus.js:371 (7f77b5b31e50 @ 67)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #16   7ffcdc5c6080 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f77b5eb0b80 @ 71)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #17   55c166cbe5e8 i   resource:///org/gnome/gjs/modules/overrides/Gio.js:295 (7f77b5ebd5e0 @ 604)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #18   55c166cbe540 i   resource:///org/gnome/gjs/modules/overrides/Gio.js:326 (7f77b5ebd820 @ 34)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: == Stack trace for context 0x55c1620801b0 ==
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #0   7ffcdc5bebf0 b   /home/u/.local/share/gnome-shell/extensions/windowoverlay-icons@sustmidown.centrum.cz/extension.js:263 (7f77b418a430 @ 129)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #1   55c166cbeb50 i   resource:///org/gnome/shell/ui/extensionSystem.js:83 (7f77b5c59160 @ 436)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #2   55c166cbead0 i   resource:///org/gnome/shell/ui/extensionSystem.js:354 (7f77b5c59ca0 @ 13)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #3   7ffcdc5bf8a0 b   self-hosted:261 (7f77b5ec1dc0 @ 223)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #4   55c166cbea50 i   resource:///org/gnome/shell/ui/extensionSystem.js:353 (7f77b5c59c10 @ 64)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #5   55c166cbe9d0 i   resource:///org/gnome/shell/ui/extensionSystem.js:371 (7f77b5c59d30 @ 87)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #6   7ffcdc5c09e0 b   resource:///org/gnome/gjs/modules/signals.js:128 (7f77b5ec18b0 @ 386)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #7   7ffcdc5c1600 b   resource:///org/gnome/shell/ui/sessionMode.js:208 (7f77b5b41dc0 @ 254)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #8   7ffcdc5c2280 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f77b5eb0b80 @ 71)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #9   55c166cbe890 i   resource:///org/gnome/shell/ui/sessionMode.js:170 (7f77b5b41b80 @ 40)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #10   7ffcdc5c3200 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f77b5eb0b80 @ 71)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #11   55c166cbe7e8 i   resource:///org/gnome/shell/ui/screenShield.js:1282 (7f77b5b28af0 @ 188)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #12   7ffcdc5c4180 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f77b5eb0b80 @ 71)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #13   55c166cbe738 i   resource:///org/gnome/shell/ui/screenShield.js:1331 (7f77b5b28b80 @ 391)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #14   7ffcdc5c5100 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f77b5eb0b80 @ 71)
Mar 02 15:29:34 ubuntu gnome-shell[9223]: clutter_actor_destroy: assertion 'CLUTTER_IS_ACTOR (self)' failed
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #15   55c166cbe6b0 i   resource:///org/gnome/shell/ui/shellDBus.js:371 (7f77b5b31e50 @ 67)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #16   7ffcdc5c6080 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f77b5eb0b80 @ 71)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #17   55c166cbe5e8 i   resource:///org/gnome/gjs/modules/overrides/Gio.js:295 (7f77b5ebd5e0 @ 604)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #18   55c166cbe540 i   resource:///org/gnome/gjs/modules/overrides/Gio.js:326 (7f77b5ebd820 @ 34)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: == Stack trace for context 0x55c1620801b0 ==
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #0   7ffcdc5bebf0 b   /home/u/.local/share/gnome-shell/extensions/windowoverlay-icons@sustmidown.centrum.cz/extension.js:263 (7f77b418a430 @ 129)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #1   55c166cbeb50 i   resource:///org/gnome/shell/ui/extensionSystem.js:83 (7f77b5c59160 @ 436)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #2   55c166cbead0 i   resource:///org/gnome/shell/ui/extensionSystem.js:354 (7f77b5c59ca0 @ 13)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #3   7ffcdc5bf8a0 b   self-hosted:261 (7f77b5ec1dc0 @ 223)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #4   55c166cbea50 i   resource:///org/gnome/shell/ui/extensionSystem.js:353 (7f77b5c59c10 @ 64)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #5   55c166cbe9d0 i   resource:///org/gnome/shell/ui/extensionSystem.js:371 (7f77b5c59d30 @ 87)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #6   7ffcdc5c09e0 b   resource:///org/gnome/gjs/modules/signals.js:128 (7f77b5ec18b0 @ 386)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #7   7ffcdc5c1600 b   resource:///org/gnome/shell/ui/sessionMode.js:208 (7f77b5b41dc0 @ 254)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #8   7ffcdc5c2280 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f77b5eb0b80 @ 71)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #9   55c166cbe890 i   resource:///org/gnome/shell/ui/sessionMode.js:170 (7f77b5b41b80 @ 40)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #10   7ffcdc5c3200 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f77b5eb0b80 @ 71)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #11   55c166cbe7e8 i   resource:///org/gnome/shell/ui/screenShield.js:1282 (7f77b5b28af0 @ 188)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #12   7ffcdc5c4180 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f77b5eb0b80 @ 71)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #13   55c166cbe738 i   resource:///org/gnome/shell/ui/screenShield.js:1331 (7f77b5b28b80 @ 391)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #14   7ffcdc5c5100 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f77b5eb0b80 @ 71)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #15   55c166cbe6b0 i   resource:///org/gnome/shell/ui/shellDBus.js:371 (7f77b5b31e50 @ 67)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #16   7ffcdc5c6080 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f77b5eb0b80 @ 71)
Mar 02 15:29:34 ubuntu gnome-shell[9223]: Object St.Bin (0x55c164ec10b0), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #17   55c166cbe5e8 i   resource:///org/gnome/gjs/modules/overrides/Gio.js:295 (7f77b5ebd5e0 @ 604)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #18   55c166cbe540 i   resource:///org/gnome/gjs/modules/overrides/Gio.js:326 (7f77b5ebd820 @ 34)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: == Stack trace for context 0x55c1620801b0 ==
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #0   7ffcdc5bebf0 b   /home/u/.local/share/gnome-shell/extensions/windowoverlay-icons@sustmidown.centrum.cz/extension.js:263 (7f77b418a430 @ 129)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #1   55c166cbeb50 i   resource:///org/gnome/shell/ui/extensionSystem.js:83 (7f77b5c59160 @ 436)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #2   55c166cbead0 i   resource:///org/gnome/shell/ui/extensionSystem.js:354 (7f77b5c59ca0 @ 13)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #3   7ffcdc5bf8a0 b   self-hosted:261 (7f77b5ec1dc0 @ 223)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #4   55c166cbea50 i   resource:///org/gnome/shell/ui/extensionSystem.js:353 (7f77b5c59c10 @ 64)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #5   55c166cbe9d0 i   resource:///org/gnome/shell/ui/extensionSystem.js:371 (7f77b5c59d30 @ 87)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #6   7ffcdc5c09e0 b   resource:///org/gnome/gjs/modules/signals.js:128 (7f77b5ec18b0 @ 386)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #7   7ffcdc5c1600 b   resource:///org/gnome/shell/ui/sessionMode.js:208 (7f77b5b41dc0 @ 254)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #8   7ffcdc5c2280 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f77b5eb0b80 @ 71)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #9   55c166cbe890 i   resource:///org/gnome/shell/ui/sessionMode.js:170 (7f77b5b41b80 @ 40)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #10   7ffcdc5c3200 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f77b5eb0b80 @ 71)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #11   55c166cbe7e8 i   resource:///org/gnome/shell/ui/screenShield.js:1282 (7f77b5b28af0 @ 188)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #12   7ffcdc5c4180 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f77b5eb0b80 @ 71)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #13   55c166cbe738 i   resource:///org/gnome/shell/ui/screenShield.js:1331 (7f77b5b28b80 @ 391)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #14   7ffcdc5c5100 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f77b5eb0b80 @ 71)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #15   55c166cbe6b0 i   resource:///org/gnome/shell/ui/shellDBus.js:371 (7f77b5b31e50 @ 67)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #16   7ffcdc5c6080 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f77b5eb0b80 @ 71)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #17   55c166cbe5e8 i   resource:///org/gnome/gjs/modules/overrides/Gio.js:295 (7f77b5ebd5e0 @ 604)
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: #18   55c166cbe540 i   resource:///org/gnome/gjs/modules/overrides/Gio.js:326 (7f77b5ebd820 @ 34)
Mar 02 15:29:34 ubuntu gnome-shell[9223]: clutter_actor_destroy: assertion 'CLUTTER_IS_ACTOR (self)' failed
Mar 02 15:29:34 ubuntu gnome-shell[9223]: Object St.Bin (0x55c1642de060), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Mar 02 15:29:34 ubuntu gnome-shell[9223]: clutter_actor_destroy: assertion 'CLUTTER_IS_ACTOR (self)' failed
Mar 02 15:29:34 ubuntu gnome-shell[9223]: Object St.Bin (0x55c1623c3260), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Mar 02 15:29:34 ubuntu gnome-shell[9223]: clutter_actor_destroy: assertion 'CLUTTER_IS_ACTOR (self)' failed
Mar 02 15:29:34 ubuntu org.gnome.Shell.desktop[9223]: Window manager warning: Overwriting existing binding of keysym 73 with keysym 73 (keycode 27).
Mar 02 15:29:40 ubuntu org.gnome.Shell.desktop[9223]: Window manager warning: Overwriting existing binding of keysym 73 with keysym 73 (keycode 27).
Mar 02 15:29:42 ubuntu org.gnome.Shell.desktop[9223]: # watch_fast: "/org/gnome/terminal/legacy/" (establishing: 0, active: 0)
Mar 02 15:29:42 ubuntu org.gnome.Shell.desktop[9223]: # unwatch_fast: "/org/gnome/terminal/legacy/" (active: 0, establishing: 1)
Mar 02 15:29:42 ubuntu org.gnome.Shell.desktop[9223]: # watch_established: "/org/gnome/terminal/legacy/" (establishing: 0)
Mar 02 15:30:04 ubuntu org.gnome.Shell.desktop[9223]: Window manager warning: Overwriting existing binding of keysym 73 with keysym 73 (keycode 27).
Mar 02 15:30:10 ubuntu org.gnome.Shell.desktop[9223]: Window manager warning: Overwriting existing binding of keysym 73 with keysym 73 (keycode 27).

**Comment by charlesg99** [comment]
Hey guoqiyi, thank you for the log. Seems like this is caused by an issue with the "windowoverlay-icons" extension. Could you please disable it, restart gnome shell and see it the problem persists? Thanks!

**Comment by guoqiyi** [comment]
I disabled all other extensions but there's still same problem....
But I solved the problem by  enbale both the "override panel theme gradient" and "override panel theme background color" option,everything goes OK !I was thinking these two are alternative option so I only enabled "override panel theme gradient" option...
So is that still count as a little bug need to fix or just my misunderstanding that I should close the issue?Anyway,thanks for your help and sorry for the trouble i've caused.
![screenshot from 2019-03-02 23-25-13](https://user-images.githubusercontent.com/3457554/53684107-13c10c80-3d44-11e9-88ea-01b7e239343f.png)

**Comment by charlesg99** [comment]
Yeah some themes style the panel using gradients and the background color opacity doesn't affect these gradients... This is mostly the reason why the gradient settings were added in the first place. Glad you got it resolved, thanks!
