### ISSUE TITLE
Configuration to create a Debian package to allow install the extension for all users

### ISSUE THREAD

**Issue by diegolagoglez** [home-sweet-gnome/dash-to-panel#587]
I think it could be a good idea to create the configuration required to create a Debian package to allow install this extension for all users instead only for the current user.

This package should install the extension in `/usr/share/gnome-shell/extensions` directory and should enable it to be available to all users.

**Comment by jderose9** [comment]
Hi @diegolagoglez !

Is this what you are looking for?
https://packages.debian.org/sid/gnome/gnome-shell-extension-dash-to-panel

**Comment by diegolagoglez** [comment]
Yes! It's that. But I would like that this project has the famous `debian` directory with the control files to create the Debian package from itself.

**Comment by charlesg99** [comment]
Hello, I'll close this as we aren't packaging the extension for means of distribution other than e.g.o. Thanks!
