### ISSUE TITLE
Problem with libreoffice

### ISSUE THREAD

**Issue by Zkdc** [home-sweet-gnome/dash-to-panel#588]
libreoffice 6.1.5.1 Build ID: 1:6.1.5~rc1-2~bpo9+1

gnome3  3.22.2
debian 9
dash-to-panel 17

When I start libreoffice and then start writer or other components from its welcome window, it's icon on dash-to-panel will perform abnormally until I open or close a window.
I tried to fix it by adding following in taskbar's  signalshandler and it works well on my machine:
`	    [
            	this._appSystem,
            	'app-state-changed',
            	Lang.bind(this, this._queueRedisplay)
            ],`

[problem_video_and_moded_taskbar_js.zip](https://github.com/home-sweet-gnome/dash-to-panel/files/2919766/problem_video_and_moded_taskbar_js.zip)

**Comment by charlesg99** [comment]
Hello Zkdc! Thank you for the report and investigation! I've never see this happen on more recent gs versions, very odd. I don't see a problem with the addition you are proposing if it fixes the issue, would you like to make a pull request or would you rather us to add it? Thanks!

**Comment by Zkdc** [comment]
forgot to say that it happens on x11 but not on wayland.

**Comment by charlesg99** [comment]
Thanks!
