### ISSUE TITLE
Multi Monitor with Arc Menu

### ISSUE THREAD

**Issue by AdmiralCode** [home-sweet-gnome/dash-to-panel#590]
Is there any way to allow Arc Menu to show up on the second monitor or is this an issue with Arc Menu?

**Comment by charlesg99** [comment]
Hello AdminiralCode! Sorry if we can't be of more help, but yes, you will need to ask the [Arc Menu people](https://gitlab.com/LinxGem33/Arc-Menu) if they could support both our panels. Thanks!

**Comment by jderose9** [comment]
@charlesg99 do you think it would be ok to attach our panel collection to Main so that other extension developers could easily iterate them?

**Comment by charlesg99** [comment]
Hey Jason! Yeah I think that would be fine, although I fear only exposing the panels collection wouldn't be enough. The problem I'm seeing is the varying order in which the extensions are loaded... i.e. if arc-menu is loaded before dash to panel, our panels collection (or panels for that matter) won't yet be available during arc-menu's initialization. Maybe we could emit a signal when we create/initialize our panels or something? Thanks!

**Comment by jderose9** [comment]
Re-opening this for now so we don't lose track of the necessary work on our end.

**Comment by LinxGem33** [comment]
Hi @jderose9  @charlesg99 

I have just opened this account so i can communicate with some of the devs on GitHub, we have added this feature to the proposed feature list on the ArcMenu project. 

As i don't have dual monitors its difficult for me to test this feature but its on the list for another dev or contributor to pick up when they get some time.

kind regards

**Comment by charlesg99** [comment]
Hello, the required additions are now on master and a pull request to bring this functionality was [submitted](https://gitlab.com/LinxGem33/Arc-Menu/merge_requests/28) to Arc-Menu. Thanks!
