### ISSUE TITLE
GNOME 3.32: Drag and Drop on panel doesnt work

### ISSUE THREAD

**Issue by alex285** [home-sweet-gnome/dash-to-panel#593]
**Reproduce:**
1. Open Nautilus
2. Drag a file to panel

**Output:**
Nothing happens

**Expected:**
Shell should open Overview so we can DnD file on another app

**Comment by charlesg99** [comment]
Hey alex285, thanks for the report! A fix for this was added to master, could you please check if that resolves the issue on your end?

**Comment by alex285** [comment]
it works now, but it needs to "slide" the file on Panel for opening overview; im on Xorg, and i guess that is not an intentional behavior, is it? :)

**Comment by alex285** [comment]
oops! it was the pressure sensitivity! i feel very embarrassed now! so it works! thanks for the quick fix!!
