### ISSUE TITLE
Right-click menu translation

### ISSUE THREAD

**Issue by TeknoMobil** [home-sweet-gnome/dash-to-panel#594]
Hello there
No language translation appears in menu right-click.
Translation done. Right click menu only appears in English

**Invisible Translations:**
- Lock taskbar
- Unlock taskbar
- Dash to Panel Settings
- Show Desktop
- Restore Window

![Ekran Görüntüsü - 2019-03-09 16-38-25](https://user-images.githubusercontent.com/42881121/54072291-eadfd080-4289-11e9-8bff-49cd8dde42c8.png)

**Comment by TeknoMobil** [comment]
Gnome 3.31.91 (latest developer package)
Gnome 3.30 (gnome plugins page)

**Comment by charlesg99** [comment]
Thank you for the report TeknoMobil, I could reproduce the issue. A fix was added to master, can you pull/install/check if you now see the missing translations?

**Comment by TeknoMobil** [comment]
Thank you so much, problem solved :)

**Comment by charlesg99** [comment]
Great!
