### ISSUE TITLE
Doesn't work with gnome shell 3.31.92

### ISSUE THREAD

**Issue by ostrol** [home-sweet-gnome/dash-to-panel#596]
Doesn't work with gnome shell 3.31.92. Says error.

**Comment by platinum95** [comment]
Also encountering this error, Ubuntu 19.04 with Gnome shell 3.31.92. 
Error in looking-glass is 
`ImportError: No JS module 'remoteMenu' found in search path`

**Comment by platinum95** [comment]
Looks like gnome-shell's ui.remoteMenu has been removed.
Removed in commit [753618a](https://github.com/GNOME/gnome-shell/commit/7df93458d728ddc52178c32a7e591be6ed648fe8#diff-209a033dd5b3c2873e9835e2d99acd8c).
Discussion of it on the [gitlab page](https://gitlab.gnome.org/GNOME/gnome-shell/issues/624)

**Comment by charlesg99** [comment]
Hi guys, please install the latest dash-to-panel version (see #545 for fixed 3.32 related issues) Thanks!
