### ISSUE TITLE
The panel gets black after unlocking the screen.

### ISSUE THREAD

**Issue by Alexander88207** [home-sweet-gnome/dash-to-panel#599]
![Bug](https://user-images.githubusercontent.com/37543796/54464854-b16eff80-4778-11e9-83ef-d89263b5d119.gif)

**Comment by charlesg99** [comment]
Hi Alexander88207. I can't reproduce that on g-s 3.30 or 3.32. Please provide your system information (dash to panel version, gnome-shell version, installed extensions, etc). Also, do you see errors in your gnome-shell log? Thanks!

**Comment by Alexander88207** [comment]
well, ehm sry i switched to xfce now but here:

gnome-shell-3.26.2-r4
installed extensions: dash to panel, topicons plus.
dtp version: i dont know i think the newest from the gnome-extensions site.

**Comment by charlesg99** [comment]
What distro was/is that?

**Comment by Alexander88207** [comment]
Sabayon based on gentoo

**Comment by Alexander88207** [comment]
The newest version in DtP is now only and my issue got now fixed :smiley:
