### ISSUE TITLE
After reinstalling Dash-To-Panel, "hotkey to activate app" works only for favorites

### ISSUE THREAD

**Issue by GinGin3203** [home-sweet-gnome/dash-to-panel#601]
Hi!

After reinstalling the extension, I can't get `<Super>+num ` hotkeys to work for non-favorite applications, (i.e. I can't bring on top an open window of a non-favorite app - it doesn't react), although I could before. Maybe it has something to do with the new version of GNOME rolled out today (Arch)

**Comment by charlesg99** [comment]
Hello GinGin3203, thank you for the report, I could reproduce the issue on 3.32. A fix for it was added to master, could you please pull/install/restart gnome-shell and see if the hotkeys now work correctly? Thanks!

**Comment by GinGin3203** [comment]
Yep, works like charm now, thanks!

**Comment by GinGin3203** [comment]
Okay, for some reason `<Super>+6` doesn't work properly. 
@charlesg99 are you able to duplicate the problem?

**Comment by charlesg99** [comment]
Hum yes strange... For me this is not always `<Super>+6`, sometimes it is `<Super>+7`. Seems like a race condition with something else and it only occurs after manually restarting gnome-shell with `Alt-F2 - r`. It doesn't happen on first boot or coming back from the lock screen (on my end anyway). Will investigate.

**Comment by charlesg99** [comment]
Alright, got time to check it out and it seems gnome-shell 3.32 [introduced similar hotkeys](https://gitlab.gnome.org/GNOME/gnome-shell/commit/4590094605774dab4c76d67953cf032616dee089) that were conflicting with ours. A fix was added to master to resolve the keybinding conflicts and it should work properly now. Thanks!

**Comment by GinGin3203** [comment]
All good now!
