### ISSUE TITLE
Feature Request (episode 1)

### ISSUE THREAD

**Issue by PranavBhattarai** [home-sweet-gnome/dash-to-panel#604]
_Some feature request:_

**1. This extension should let the users to use shortkey of "Show/Revel panel" even without enabling "PanelIntell Hide".**

**2. There is no way to cut the middle empty part of the panel like a notch which can be used to view the contents of other application for browsing etc.**

**Comment by charlesg99** [comment]
Hello PranavBhattrai and thank you for the suggestions! Some questions though:

1. Why? Makes sense to me to only allow to hide the panel when intellihide is enabled... You already can simply toggle the panel without it being affected by windows proximity, is this what you'd like?

2. What do you mean "fully transparent"? As it stands, you can set the panel opacity to 0 and the background becomes completely transparent, is this not what you're seeing?

![image](https://user-images.githubusercontent.com/33044886/54784346-04720800-4bfa-11e9-8668-68fc4ab372fc.png)

Thanks!

**Comment by PranavBhattrai** [comment]
I come from the "windows" world, and they provide the shortkey mechanism to hide/reveal the panel.
I loved that idea. 
Which is what's missing in this extension.
There are two types of hide and revel:
1. Reveling by showing the "original" state.
2. Reveling by overriding the all windows application.
Our extension can do the second point.
I think it would be great to provide the first point too with another kind of shortkey.

**Comment by charlesg99** [comment]
> showing the "original" state.

Not sure I understand correctly. Do you mean that you want to hide and reveal the panel without it being affected by windows proximity? If so, you can do that with the following settings and using the same keyboard shortcut (i.e. I'm pressing `<Super>+i` to hide and reveal the panel):

![Peek 2019-03-22 16-38](https://user-images.githubusercontent.com/33044886/54851630-f6d38580-4cc0-11e9-86c8-90fda1744c21.gif)

**Comment by PranavBhattrai** [comment]
![Screenshot from 2019-03-24 11-44-30](https://user-images.githubusercontent.com/32763112/54875607-41bcdc80-4e2a-11e9-86bf-9006b7b2b4cf.png)

As u can see in the buttom, the panel icon overrice the conent on browser at the buttom of the screen even after i deselect "Only hide panel..." option.

As am not sayin this feature is good, but people should have two kinds of reveling/hiding panel from the shortcut.
1. That overrides.
2. Another the works like "PanelIntell hide" option is disabled.

**Comment by jderose9** [comment]
Regarding not overriding the windows, you mean that you want all windows in the area of the taskbar to be resized to make way for the panel? I think that makes sense, except then we would someone need to un-resize them when you closed the panel, and the windows wouldn't necessarily be in the same place at that point.

Would it make sense to do this only in the case of maximized windows? (always/across the board, not a new setting)

Regarding the notch, please see the theme [plano](https://github.com/lassekongo83/plano-theme).

**Comment by PranavBhattrai** [comment]
Plano make things a bit complicated. 
Now i have to press exactly a little above panel in the battery percentage to see option.
And that a hugh speed difference experience. 
![Screenshot from 2019-04-01 13-09-07](https://user-images.githubusercontent.com/32763112/55310139-7874a180-547f-11e9-9626-9da07f44ef0f.png)
This buttom gap is unecessary. I can't go fastly to setting, poweroptions  fastly.

**Comment by charlesg99** [comment]
Closing as the same as the only request left here is the same as #693. Thanks!

**Comment by PranavBhattarai** [comment]
@charlesg99 

1 question: Is it not possible to make "the notch area" clickable?

![Screenshot from 2020-03-19 17-02-51](https://user-images.githubusercontent.com/32763112/77062246-9c6c2280-6a03-11ea-9edb-06a02ed523b2.png)

Afterall those in that big area, we don't have any icons, menus. I really think it can be really helpful.
