### ISSUE TITLE
[BUG] Missing close button in window preview

### ISSUE THREAD

**Issue by libalis** [home-sweet-gnome/dash-to-panel#609]
Since my update to GNOME 3.32 I recompiled DTP several times from master.
But the update seems to have broken the close button on the window preview.
(Allthough it still shows up in the Meta-Overview)
![Bildschirmfoto](https://user-images.githubusercontent.com/45124869/54881898-1d2a2a00-4e55-11e9-808f-d22f3eee7e34.png)

**Comment by charlesg99** [comment]
Thank you for the report libalis! Yes indeed, seems like on gnome-shell 3.32 the close button was splitted into 2 separate icons. A fix for this was just added to master if you want to have a look. Thanks!

**Comment by libalis** [comment]
Thank you so much for your quick reply and fix!
It was indeed fixed and does now work flawlessly!
Thank you again and have a nive day!

**Comment by charlesg99** [comment]
Great, thanks for the feedback!
