### ISSUE TITLE
Rounded corner is not getting transparent 

### ISSUE THREAD

**Issue by rafaeldeoliveira** [home-sweet-gnome/dash-to-panel#615]
When I enable panel transparency with panel on top, the corner is not getting transparent (both left and right):

![image](https://user-images.githubusercontent.com/16655995/55302867-a32c0f00-5419-11e9-97a8-a76812215caa.png)

![image](https://user-images.githubusercontent.com/16655995/55302767-0ff2d980-5419-11e9-9453-d8c0e953e79f.png)

![image](https://user-images.githubusercontent.com/16655995/55302802-357fe300-5419-11e9-9ab2-7cd91210c787.png)

Gnome 3.32 (Arch + Adwaita + default shell theme)

Thanks!

**Comment by charlesg99** [comment]
Hello rafaeldeoliveira, thank you for bringing this up, but it was recently reported/fixed #612. Please install the latest development version until we release a new version to e.g.o. Thanks!

**Comment by rafaeldeoliveira** [comment]
It worked, thanks!

**Comment by charlesg99** [comment]
Great, thanks for the feedback!
