### ISSUE TITLE
Application icons in dash have shifted from panel, looks like a bug

### ISSUE THREAD

**Issue by optimistic5** [home-sweet-gnome/dash-to-panel#617]
After some update or or something else my dash-to-panel start to looks awful.
Applications shifted from the normal places.
And tray become crazy, it is newer hides.

Please, look at this screenshots.
![image](https://user-images.githubusercontent.com/25054050/55798909-bbb2be00-5ad8-11e9-9f5d-76e8ba76de6d.png)
![image](https://user-images.githubusercontent.com/25054050/55798881-ab024800-5ad8-11e9-8d79-b5b99f572053.png)

I tried to change icons size, but it looks the same.
I tried move panel to buttom, but it is the same bug.
This is my [settings](https://privatebin.net/?1a7c3a1eaee4c5c3#dPkAJOz7AtGU1kIBq+qNN7pDxCfU1QuVWs4obxTqA9s=).

**Please, fix it.**
Thank you.

Dash to panel version 19.
Gnome 3.32.0
ArchLinux, up to date.

**Comment by charlesg99** [comment]
Hello optimistic5, please refer to #616, should be fixed if you install the latest development version. Thanks!

**Comment by optimistic5** [comment]
Issue is gone on development version. Thanks.
