### ISSUE TITLE
no app for changed [extension]

### ISSUE THREAD

**Issue by angela-d** [home-sweet-gnome/dash-to-panel#618]
Dash to Panel crashed and revealed the default panel after a timed out VPN connection.

```text
Apr 15 18:21:34 debian NetworkManager[760]: <info>  [1555370494.5702] vpn-connection[..,"VPN",0]: VPN service disappeared
Apr 15 18:21:34 debian gnome-software-service.desktop[1294]: 23:21:34:0878 Gs  no app for changed dash-to-panel@jderose9.github.com
Apr 15 18:21:34 debian gnome-software-service.desktop[1294]: 23:21:34:0878 Gs  no app for changed dash-to-panel@jderose9.github.com
Apr 15 18:21:34 debian gnome-software-service.desktop[1294]: 23:21:34:0879 Gs  no app for changed dash-to-panel@jderose9.github.com
... [ every single gnome extension installed listed with the no app for changed, as seen below: ] ...
Apr 15 18:21:34 debian gnome-software-service.desktop[1294]: 23:21:34:0883 Gs  no app for changed windowsNavigator@gnome-shell-extensions.gcampax.github.com
Apr 15 18:21:34 debian gnome-software-service.desktop[1294]: 23:21:34:0884 Gs  no app for changed workspace-indicator@gnome-shell-ext
Apr 15 18:21:34 debian gnome-shell[1142]: JS LOG: Extension "dash-to-panel@jderose9.github.com" had error: Error: Type name Gjs_DashToPanel-TaskbarActor is already registered
Apr 15 18:21:34 debian gnome-software-service.desktop[1294]: 23:21:34:0954 Gs  no app for changed dash-to-panel@jderose9.github.com
```
```text
Linux debian 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux
```

Dash to Panel comes back fine after restarting Gnome shell.

**Comment by charlesg99** [comment]
Hello angela-d, thanks for bringing that up! Can you reliably reproduce the issue? Those `no app for changed ...` logs indicate that a check for newer versions was done by the software app. 

We recently had a similar issue #597 and it turned out that when gnome crashes, another extension wasn't being disabled correctly and this prevented dash to panel to be correctly re-enabled. If you can reproduce the crash, could you please try with your other extensions disabled to rule out this possibility? 

Thanks!

**Comment by angela-d** [comment]
Unfortunately, it seems I cannot reliably reproduce.  It's intermittent!

**Comment by jderose9** [comment]
Based on the log you shared, I don't necessarily see that dash-to-panel crashed, but rather that gnome tried to start dash-to-panel again without it stopping cleanly or having been stopped at all. So, for whatever reason, gnome's extension handling state was out of sync.

I would have to second @charlesg99's recommendation of disabling all other extensions and see if the issue persists, then continue to narrow it down from there.

**Comment by angela-d** [comment]
Thanks for the explanations, guys!
