### ISSUE TITLE
When ungrouped, some windows with long names shift names down when panel is less than default height

### ISSUE THREAD

**Issue by nortexoid** [home-sweet-gnome/dash-to-panel#620]
I've attached a screenshot showing what I mean. This doesn't happen with all files, but the title of the pdf that evince takes from the pdf metadata shows a strange symbol in it, so that might be the cause.

[Screenshot](https://imgur.com/8CItsSj)

**Comment by charlesg99** [comment]
Hello nortexoid, what is the strange symbol you're referring to? I would like to reproduce this. Thanks!

**Comment by nortexoid** [comment]
[Here's a link ](https://www.dropbox.com/s/mxk6xucks7nj20v/Pryor%20-%20Whats%20wrong%20with%20Moores%20argument%20%282004%29_backup.pdf?dl=0)to the file. After editing the title in the metadata, the bug goes away. The strange symbol appears to be standing in for a line feed (the box shows OOOA if read from top-to-bottom, left-to-right).

**Comment by charlesg99** [comment]
Thank you for the link, I could reproduce the issue. A fix to remove the line breaks from the titles was added to master, could you please try it and confirm that the title now stays on one line?

**Comment by nortexoid** [comment]
Thanks for the fix--it works for me!
