### ISSUE TITLE
[Feature request] Customize entries App icon secondary (right-click) menu

### ISSUE THREAD

**Issue by linuxr01** [home-sweet-gnome/dash-to-panel#621]
Give us the option to add new entries?

**Actual state:**
![right-click menu2](https://user-images.githubusercontent.com/49744994/56342620-ca743180-61b8-11e9-9d44-98d4603f846f.JPG)

**Example:**
![right-click menu](https://user-images.githubusercontent.com/49744994/56342423-4752db80-61b8-11e9-9972-aaa7d602b9ed.JPG)

**Comment by linuxrx01** [comment]
Is this possible?

**Comment by charlesg99** [comment]
Hi linuxrx01! Yes it is possible, but it would be much simpler to add some fixed entries in the context menu instead of allowing users to define their own. Our preferences UI is overcrowded and I feel it wouldn't see much usage. Do you think it would be acceptable to add some fixed entries like "system monitor", "system settings" and so on? Thanks!

**Comment by linuxrx01** [comment]
Yes, fixed entries would be great too. Thank you

**Comment by charlesg99** [comment]
What entries did you have in mind?

**Comment by linuxrx01** [comment]
**Example**(I dont know if it is too complex)

Thank you for your work!

Apps (open Software) 
Power Options (open Settings/Power) 
Event Logs (open Logs) 
System (open Settings/Details)
Device Managment (open Settings/Devices) 
Network Connections (open Settings/Network) 
Disk Managment (open Disks) 
Terminal 
---------------------- 
System Monitor 
Files 
Settings 
Panel Settings
 -------------------------- 
Shutdown or sign out 
Lock/unlock Taskbar 
Show Desktop (Default)

**Comment by charlesg99** [comment]
Hello, most of these entries were added to master if you want to give it a shot. The only one that I left out is "Shutdown or sign out" as I think it would be frustrating to sign out by misclicking and hitting this option. Thanks!

**Comment by linuxrx01** [comment]
Works great!
