### ISSUE TITLE
unfocused apps not showing indicator

### ISSUE THREAD

**Issue by Goddard** [home-sweet-gnome/dash-to-panel#624]
I just upgraded from 18.10 pop-os/ubuntu and when upgrading everything seems to be working except this extension.

Only the focused application indicators are showing so I can't see which applications are running any more.  I tried uninstalling and changing styles, but nothing seems to work.

Any ideas are appreciated.

**Comment by charlesg99** [comment]
Hello Goddard, I assume you updated to Ubuntu 19.04? What dash to panel version are using? Could you please try to disable all of your extensions aside from dash to panel, restart gnome-shell and check if you still experience this issue? Thanks!

**Comment by charlesg99** [comment]
Hello, is this still relevant? Thanks!
