### ISSUE TITLE
Padding causes bottom of panel to appear off screen when placed on bottom of screen.

### ISSUE THREAD

**Issue by amostman** [home-sweet-gnome/dash-to-panel#628]
I am using Ubuntu 19.04 and when deploy the panel I could not see the running indicators.  I learned that if I change the padding to 0 then they appear.  So what I am seeing is that the app icon padding causes the panel to expand downward off the screen.

Padding: 0
![image](https://user-images.githubusercontent.com/49995435/56761132-409d0900-6762-11e9-9c2b-96828efb3423.png)

Padding: 4
![image](https://user-images.githubusercontent.com/49995435/56761821-eac96080-6763-11e9-8945-c0b2115ef923.png)

Padding: Max
![image](https://user-images.githubusercontent.com/49995435/56761190-64f8e580-6762-11e9-892b-9591125f25c8.png)

**Comment by amostman** [comment]
Padding: 4
![image](https://user-images.githubusercontent.com/49995435/56761265-8fe33980-6762-11e9-80f6-e23735d28a7d.png)

**Comment by charlesg99** [comment]
Hi, looks like #595, did you try the latest development version? Thanks!

**Comment by amostman** [comment]
Yep that one looks the same.  I even searched git for padding and I didn't see that #595.  Sorry for the duplicate.  Anyway, I will try the dev version.  Thanks
