### ISSUE TITLE
can't move through vertical multi monitor

### ISSUE THREAD

**Issue by sketet** [home-sweet-gnome/dash-to-panel#629]
I would like to use 2 monitors in vertical configuration, the secondary above the main.
I also use the option "intellihide" to save pixel, but with this setting I can't move the mouse through the monitors. So, each monitor is isolated!
Is there a way to use the intellihide with this configuration?

**Comment by charlesg99** [comment]
Not really, no. You could disable the intellihide option "Require pressure at the edge of the screen" to allow the mouse to move through, but you'll end up with 2 panels on one screen. We currently don't "hide" the panel, we just move it off screen, so with your setup it's going to move to your other screen when hidden. Thanks!

**Comment by sketet** [comment]
yes, I noticed this behavior... unfortunately.
will there be the chance to solve this? or maybe, could customize the panel for each monitor.
I mean, there is the option to fix the panel in the main monitor and intellihide in the secondary.
So customize the panel in the main screen (maybe reducing the height) and a further option to customize the panel in the secondary monitor (intellihide, change the height, colors...)

**Comment by charlesg99** [comment]
Hello sketet, a fix for this was added to master. The panels should now hide correctly on monitors in a vertical configuration. Thanks!

**Comment by sketet** [comment]
thank you! unfortunately this week I'm in a mobile mode, I will try next week-end.
well done guys!

**Comment by sketet** [comment]
Hello, I installed the version 19 from here... but same issue.
The monitors are isolated, with the intellihide option enabled, if I stay in the bottom monitor I can't go in the top.

**Comment by charlesg99** [comment]
Ha sorry, I was referring to the top monitor's panel sliding down on top of the bottom monitor when "hiding". 

The barrier that prevents you from moving across monitors is only enabled to sense pressure, which doesn't make much sense in this case. As I said before:
> You could disable the intellihide option "Require pressure at the edge of the screen" to allow the mouse to move through.

 Thanks!

**Comment by usersaurus** [comment]
About this...
> Hello sketet, a fix for this was added to master. The panels should now hide correctly on monitors in a vertical configuration. Thanks!

...I'm still getting that error.

![Screenshot from 2019-08-08 17-51-51](https://user-images.githubusercontent.com/14541427/62718157-9e015100-ba05-11e9-998e-716015c6a58a.png)

Shall I open another issue?

**Comment by charlesg99** [comment]
Hello usersaurus, are you using the development version of Dash to Panel? Thanks!

**Comment by usersaurus** [comment]
Hey @charlesg99! I'm currently using the version available in the Ubuntu Store.

**Comment by charlesg99** [comment]
@usersaurus, the fix is only available since v20 of Dash-to-Panel. Not sure which version was installed from the Ubuntu store, but you can know for sure by looking at the "About" tab of the extension settings:

![image](https://user-images.githubusercontent.com/33044886/62803435-6a333380-bab8-11e9-8043-a831e11cb45d.png)


Thanks!

**Comment by usersaurus** [comment]
@charlesg99 looks like the current version is 19 in the Ubuntu Software Store. Knowing that it's fixed in version 20, I think I'll wait to the plugin being updated there. Thank you so much for ur help :D

**Comment by jderose9** [comment]
I'm going to close this assuming it is resolved. If it's not, we can re-open. Thanks!
