### ISSUE TITLE
Feature request: The notch style panel, where the area between is clickable.

### ISSUE THREAD

**Issue by PranavBhattrai** [home-sweet-gnome/dash-to-panel#632]
I have used the "pano theme", as u told, but those area which are transparent should also be clickable. It would have been cool. 

1 problem with use pano theme with is module is, the edge corner of the panel where we click for setting, power off, etc is not attached to the complete edge. There is few inches of separate space, which make clicking that portion very annoying. I have to take my time and click on the focused area. It was more faster before. Because there was no space. One random click at corner and u get ur option. 

So, what's my point is there should be transparent panel option built-in instead of depending on pano theme. They don't even have a PPA or any such things to update the theme even IF the update is available. 

And the when "notch" feature is available, there will be no need of pano theme I guess. 

(Sorry for saying this issue in repeat. But it's little different.)

**Comment by charlesg99** [comment]
Hello PranavBhattrai! Themes, like plano, can change the panel however they want and we don't really want to interfere with that. The non-clickable gap you refer to comes from the plano theme, so I suggest you bring this issue to the theme creator.
 
> So, what's my point is there should be transparent panel option built-in instead of depending on pano theme. 

There is, as already mentioned: https://github.com/home-sweet-gnome/dash-to-panel/issues/604#issuecomment-475399823. As for the "notch" feature, I personally don't see this being brought in dash to panel as an option. You could modify the css of a theme you like to change the background style of the `StBoxLayout #panelRight` element to make it opaque, though. 

Thanks!

**Comment by PranavBhattrai** [comment]
@charlesg99 What about rest of the clickable area which is blank and unused? Will it be "clickable" in future?
![Screenshot from 2019-04-30 12-32-12](https://user-images.githubusercontent.com/32763112/56944728-3a34d580-6b44-11e9-9d49-a22736dd2226.png)

**Comment by charlesg99** [comment]
I don't understand what you mean... please define "clickable". The fact that the panel has its opacity set to 0 doesn't change anything other than its appearance. Thanks!
