### ISSUE TITLE
App Icon menu does not work after screen lock

### ISSUE THREAD

**Issue by gujjwal00** [home-sweet-gnome/dash-to-panel#634]
I can not access menu for app icons (neither for apps in Applications, nor for apps pinned on panel) after locking then unlocking. Things work correctly if i log out/ login again.

Something like a empty menu appears in top-left corner:
![image](https://user-images.githubusercontent.com/27951674/57034775-0c4bb000-6c6e-11e9-9b0c-e63cd3f4374c.png)

Following appears in syslog:

gnome-shell[1833]: JS ERROR: TypeError: super[func] is not a function#012callParent@/home/gaurav/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/utils.js line 65 > eval:1:244#012_redisplay@/home/gaurav/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:1285:9#012popup@resource:///org/gnome/shell/ui/appDisplay.js:1826:9#012popupMenu@/home/gaurav/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:574:9#012_onButtonPress@resource:///org/gnome/shell/ui/appDisplay.js:1552:13

I am on Ubuntu 19.04

**Comment by charlesg99** [comment]
Hello gujjwal00, I can't reproduce this on Ubuntu 19.04. Please try to disable all of your extensions aside from dash to panel, restart gnome-shell and see if you have the same issue. My guess is that one of your other extensions runs into an error when locking the screen. Thanks!

**Comment by gujjwal00** [comment]
You are right! It is caused by [Appfolders Management extension](https://github.com/maoschanz/appfolders-manager-gnome-extension).
It looks like author is [aware](https://github.com/maoschanz/appfolders-manager-gnome-extension/issues/64#issuecomment-479113688) of it.

Thanks for your help.
