### ISSUE TITLE
Resize icons

### ISSUE THREAD

**Issue by ndias** [home-sweet-gnome/dash-to-panel#637]
Can you have an option to resize icons? and no, the Padding doesn't do what I want, because the padding will put the icons smaller but with longer margins

**Comment by charlesg99** [comment]
Hello, did you try resizing the panel? What do you want to do exactly?

**Comment by ndias** [comment]
I don't want to resize the panel (and yes I tried that), I want the panel with a fixed size, 30px for example, and then I want the icons smaller, 20px for example.
Thanks

**Comment by charlesg99** [comment]
> I want the panel with a fixed size, 30px for example, and then I want the icons smaller, 20px

Well, if you set your panel size to 30px and your padding size to 5px you'll get just that.
![image](https://user-images.githubusercontent.com/33044886/57166083-074e4400-6dc7-11e9-9633-1dbc7f55019a.png)

Is your issue with the the horizontal space between the icons?

**Comment by ndias** [comment]
Yes, my problem is the space between the icons, in a small screen several icons will disappear from screen, and the running indicator is placed outside of the panel (see Screenshot1 before, and Screenshot2 after apply the padding).
My request if possible is, only resize the icons (the applications font in the right of the panel is resized withn the padding), center the icons (vertical center), put the indicator bellow the resize icon, not in the bottom of the panel, and the option to choose the space between icons.

Thanks
Nuno
![Screenshot1](https://user-images.githubusercontent.com/886782/57177067-17623400-6e58-11e9-9906-0406e23e5938.png)
![Screenshot2](https://user-images.githubusercontent.com/886782/57177068-17623400-6e58-11e9-87c9-bb1d1e314654.png)

**Comment by charlesg99** [comment]
Well obviously something is wrong on your second screenshot, this isn't intended. Please [install the latest development version](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github) and see if that resolves the issue. If not, disable every other extensions, restart gnome-shell and see if that fixes it. Thanks

**Comment by ndias** [comment]
Ok, the dev version solve the problem, thanks
