### ISSUE TITLE
Multi-monitor indicator issues

### ISSUE THREAD

**Issue by jordanribera** [home-sweet-gnome/dash-to-panel#638]
First some system info:
```
$ uname -a && lsb_release -dc && gnome-shell --version

Linux oriko 5.0.0-13-generic #14-Ubuntu SMP Mon Apr 15 14:59:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Description:	Ubuntu 19.04
Codename:	disco
GNOME Shell 3.32.0
```

I've noticed the following possibly related issues:

1. When a window is dragged from one monitor to another, the indicator does not follow
2. Certain apps launched on secondary monitor show their indicator on the primary monitor

The first issue can be seen [here](http://spiralpower.net/files/bug__drag_and_focus.webm). When I drag (and release) the window to the other monitor, the indicator stays on the previous monitor. Changing focus to another window causes the indicator to update.

The second issue can be seen [here](http://spiralpower.net/files/bug__various_apps.webm). When the terminal or file browser are launched on the secondary monitor, the indicator is shown on the primary. The active window highlight is shown on the correct display. This is not the case with other applications like settings, system monitor, or interestingly the "About" [dialog](http://spiralpower.net/files/bug__terminal_vs_dialog.webm) from the terminal.

The first difference that comes to mind between the file browser or terminal and other applications is that they will launch multiple windows. Possibly they don't interact with the window manager in the same way and need to be detected differently.

I'm happy to dig further but I'm pretty new to Gnome in general so any direction is appreciated!

**Comment by charlesg99** [comment]
Hey Jordan, thank you for reporting this. I can reproduce both issues on Ubuntu 19.04, but not on my main machine (arch) which is gnome-shell 3.32 also. Weird.

I added a small fix to force the indicator update when the windows are grouped, could you confirm that it solves the issue? Thanks!

**Comment by jordanribera** [comment]
It looks like it improved the first issue in some cases. Here are a couple of scenarios I've tried out with the latest from master branch:

- [Favorite vs not](http://spiralpower.net/files/bug__fav_vs_not.webm)
- [Multiple terminals](http://spiralpower.net/files/bug__fav_terminals.webm)
- [Settings dialog](http://spiralpower.net/files/bug__settings.webm)
- [Calculator](http://spiralpower.net/files/bug__calculator.webm)

In the case of the calculator, everything works perfectly now until it is added to favorites. It seems when an app is favorited, its indicator will only update position when windows change focus.

**Comment by charlesg99** [comment]
Hum really strange as your videos show what I see when using the version before the the fix (a9ac4e803b91285e03e8b2bb10b663440b633abb):

![before](https://user-images.githubusercontent.com/33044886/57184353-6b850c80-6e88-11e9-9261-2b8c1e69d680.gif)

But it seems to be working fine when I checkout master/install/restart gnome-shell (bf785c6179b975047333a6bee6f817496e3d7b31):

![after](https://user-images.githubusercontent.com/33044886/57184370-9a9b7e00-6e88-11e9-853c-95b3cedcc31b.gif)

I've tested on both Xorg and Wayland, so I don't think this is the issue. Are you sure you're running the latest master? Thanks!

**Comment by charlesg99** [comment]
Another thought... which workspaces setting are you using? In the tweak tool:
![image](https://user-images.githubusercontent.com/33044886/57184562-2d3d1c80-6e8b-11e9-8d56-65798bf56ac0.png)

I'm seeing similar issues when the applications are grouped and the workspaces are set to span displays (like in the screenshot). I'll look into that next. Thanks!

**Comment by jordanribera** [comment]
Definitely on latest master:
```
$ git rev-parse HEAD

bf785c6179b975047333a6bee6f817496e3d7b31
```

Here also is a dump of dconf (`dconf dump /org/gnome/shell/extensions/dash-to-panel/ > dconf.txt`) for the extension just for good measure: [dconf.txt](https://github.com/home-sweet-gnome/dash-to-panel/files/3145062/dconf.txt)

I am also using workspaces that span displays:
![Screenshot from 2019-05-04 19-40-17](https://user-images.githubusercontent.com/8548090/57187522-0f7cb100-6ea5-11e9-8127-671d7d56a013.png)

**Comment by charlesg99** [comment]
Excellent timing, your last comment appeared while I was writing :grin: 

A new commit that will hopefully fix the indicators on spanned workspaces just got added to master. Could you please pull again and see if that helps? Thanks!

**Comment by jordanribera** [comment]
That fixed it!

**Comment by charlesg99** [comment]
Glad to hear it! Thanks for the feedback!
