### ISSUE TITLE
Vertical bar instead of horizontal [feature request]

### ISSUE THREAD

**Issue by StructByLightning** [home-sweet-gnome/dash-to-panel#639]
My default bar shows up on the left side, and can be placed on left/right by going to the os settings > dock > position on screen. However this option doesn't seem to work with the combined bar. Can you make it so the combined bar can be placed on any of the four sides, either just by dragging it or toggling a setting somewhere?

**Comment by charlesg99** [comment]
Hello StructByLightning! Appreciate your feedback, but you're asking for a long-standing issue (see #3). Please hop over there to follow its progression and to contribute further. Thanks!
