### ISSUE TITLE
top panel icons spacing messed up

### ISSUE THREAD

**Issue by lverissimo** [home-sweet-gnome/dash-to-panel#641]
Hi. My top panel icons get messed up following a reboot or shell restart. 
![2019-05-06_15-57](https://user-images.githubusercontent.com/8387568/57258290-e9494380-7053-11e9-9289-839789248bf6.png)

I can fix it by turning off dash-to-panel and turning back on. 
![2019-05-06_15-58](https://user-images.githubusercontent.com/8387568/57258349-139b0100-7054-11e9-9f9a-a8fbd9ce355e.png)

I am running fedora 30.
GNOME Shell 3.32.1
5.0.11-300.fc30.x86_64
dash-to-panel@jderose9.github.com version: 19

any help is welcome.

**Comment by charlesg99** [comment]
Hello lverissimo, thank you for the feedback! Please try to disable all of your extensions aside from dash to panel, restart gnome-shell and see if you have the same issue. Sounds like a load order/extension incompatibility.

Are you using the Unite extension? If so refer to #625 and #631. 

Thanks!

**Comment by lverissimo** [comment]
Thank you so much for your support. After disabling all extensions and still getting the same behaviour I started to tweak with the fine tunning options. Removed all -1 values (default) to theme, and fixed the issue I had. Thanks again for the support.
