### ISSUE TITLE
GNOME 3.34: Usage of object.actor is deprecated

### ISSUE THREAD

**Issue by alex285** [home-sweet-gnome/dash-to-panel#648]
hello @charlesg99, the time has come again for debugging on the next GNOME release ;)

here's the patches of @3v1n0 already merged and released on 3.33.1:
https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/487

btw there should be a backward compatibility i think, but in cases that freezes Shell and we need to Alt+F2 and "r" ..not sure though is this is actually the patches that make the freeze!

![Screenshot from 2019-05-17 21-03-51](https://user-images.githubusercontent.com/11244308/57947529-cd615f80-78e7-11e9-9b51-cde8ca33b052.png)

**Comment by charlesg99** [comment]
Hello alex285! Finally had time to install Fedora 31 to test against gnome-shell 3.33.2. The deprecation messages were taken care of plus one freeze that happened when opening the show apps button's context menu. Should now work as expected on branch custom-window-preview, as this is where my current focus is. Please let us know if you find more problems on 3.33.x. Thanks!

**Comment by 3v1n0** [comment]
I'm going to prepare a follow-up for this extension related to this change.

But before I'd like https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/559 in as is a mayor change anyways

**Comment by alex285** [comment]
adding that here, instead opening a new 3.34 issue; in 3.33.4 release, we cant enable the extension; it gives:
```
Extensionsystem.connect is not a function
```
here's the relevant change:

https://gitlab.gnome.org/GNOME/gnome-shell/commit/ea177407191c17e6e386e5b36bad2508c8cbcdcb

**Comment by charlesg99** [comment]
Thanks for the heads up Alex! Should now be fixed on master.
