### ISSUE TITLE
[FR] Please to add application spread function/option for modern look

### ISSUE THREAD

**Issue by pyroxar** [home-sweet-gnome/dash-to-panel#649]
I explain everything in this post:
https://github.com/linuxmint/cinnamon/issues/8539

I think that great idea will be if "dash to panel" will have the same option like Ubuntu's unity 7 for multiple windows one application.

**Comment by jderose9** [comment]
Thanks @pyroxar ! This doesn't sound like a bad idea. I'm wondering if we should replace the existing "Toggle single / preview multiple" behavior with a full-screen view or add it as an additional option?

**Comment by charlesg99** [comment]
If I understand correctly, the main issue seems to be that the window previews are too small? Maybe just setting them as big as is comfortable for you would do the trick? 

Of course this isn't exactly the same as the "application spread", but it's a start:

![image](https://user-images.githubusercontent.com/33044886/60636993-a18e3080-9de6-11e9-9e84-8dd404f8edee.png)

**Comment by pyroxar** [comment]
@jderose9 In my opinion: better to replace; Spread application should be default but if option to change it will be available, I will glad.

**Comment by pyroxar** [comment]
@jderose9 can you implement this? It will be very comfortable for many user, i think that. It was great function in unity, ?now when Ubuntu use fork of this extension?, it will great to see this function in the future release of the Ubuntu.

**Comment by pyroxar** [comment]
@charlesg99 see above, sorry for spam.

**Comment by jderose9** [comment]
@pyroxar Ubuntu actually maintains their own branch of `dash-to-dock` (a different extension) so if you are hoping to get this into Ubuntu by way of this extension, you will want to talk to the Ubuntu team instead.

While this sounds like a nice feature to have in dash-to-panel, I can't provide any commitment around it getting completed. If someone else would like to work on it, we will certainly do our best to get a pull request successfully integrated. Thanks!
