### ISSUE TITLE
Active icon hint overlaps with window

### ISSUE THREAD

**Issue by luispabon** [home-sweet-gnome/dash-to-panel#650]
See screenshot (firefox icon)

![image](https://user-images.githubusercontent.com/6388823/57969857-486f5800-7972-11e9-96e6-de74860ce916.png)

**Comment by luispabon** [comment]
More info: this seems to happen only on a hidpi display (4k at scale 2).

**Comment by charlesg99** [comment]
Hello, this is probably a duplicate of #595 #628 #637 #647. Please install the latest development version to resolve the issue until a new version is released to e.g.o. Thanks!
