### ISSUE TITLE
Preview windows don't stay on hover on Ubuntu 18.10

### ISSUE THREAD

**Issue by AlienKevin** [home-sweet-gnome/dash-to-panel#652]
Preview windows don't stay on hover after updating from Ubuntu 18.04 to 18.10. This problem is not very persistent and sometimes the preview on hover works.

![dash_to_panel_cannot_hover_previews](https://user-images.githubusercontent.com/22850071/58186654-529b9a00-7c83-11e9-885f-2f0abc803ec5.gif)

**Comment by charlesg99** [comment]
Hello AlienKevin, sorry for the late reply but the new window previews were under development, hence investigating the "old" ones wasn't a priority. Please install the latest master to try them out! Thanks!

**Comment by AlienKevin** [comment]
I will try it out. Thanks!
