### ISSUE TITLE
Running indicators with isolated monitors

### ISSUE THREAD

**Issue by joshuakb2** [home-sweet-gnome/dash-to-panel#653]
I'm having an issue where running indicators on isolated monitors sometimes appear on the wrong monitor.

**Device details**:
- OS: Ubuntu 18.04 LTS
- Gnome shell version: 3.28.3

**Settings that might be relevant**:
- Position
  - Display panels on all monitors: true
    - Isolate monitors: true
    - Display favorite applications on all monitors: true
- Behavior
  - Show favorite applications: true
  - Isolate workspaces: true
  - Click action: Cycle windows + minimize

Procedure to reproduce:
1. Start from an empty or new workspace.
2. Open a favorite application on the left monitor.
3. Drag it to the right monitor.
4. **Observe the running indicator stays only on the left monitor.**
5. Click on the same application icon on the left monitor.
6. **Observe that a new instance of that application opens on the left monitor (as expected), even though the indicator is wrong.**
7. **Observe that the running indicator is now present on the right monitor as expected.**
8. Close both instances of the application and repeat steps 2 and 3.
9. Click on the favorite application icon on the right monitor (where there is currently no indicator even though there's an instance of the application running on that monitor).
10. **Observe that the application minimizes (as expected), but the running indicators are still wrong on both monitors.**

Here's a screenshot of the bug manifesting on my laptop.

![Screenshot from 2019-05-23 11-57-23](https://user-images.githubusercontent.com/15221090/58272062-36672e00-7d53-11e9-85d2-ab3bd5bb88ef.png)

**Comment by charlesg99** [comment]
Hello Joshua! Thank you for reporting this! Which version of dash to panel are you using? A similar issue #638 was recently reported/fixed and isn't yet released on e.g.o. (currently v19). Could you please [install the latest development version](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github) and see if the issue persists? Thanks!

**Comment by joshuakb2** [comment]
Thanks Charles. I just installed the latest development version and the problem seems to be resolved. I didn't see #638 for some reason when I was looking for similar issues.
