### ISSUE TITLE
Fedora GNOME 3.32: Super hotkeys work only on favourite applications

### ISSUE THREAD

**Issue by GinGin3203** [home-sweet-gnome/dash-to-panel#655]
Hi!

`Super+<num>` hotkeys don't work for non-favourite applications in Fedora GNOME 3.32.

**Comment by charlesg99** [comment]
Hello GinGin3203, did you forget #601 already :P
Your previous issue was on Arch, now it's Fedora... I assume you didn't re install the latest development version of dash to panel?

**Comment by GinGin3203** [comment]
Oof, I did forget to reinstall it from Github... Feeling like a total brainlet now

Thank you for your time and for one of the most useful GNOME extensions :)

**Comment by charlesg99** [comment]
Hey no worries, happens to me all the time! Thanks!
