### ISSUE TITLE
Error loading in gnome 3.32

### ISSUE THREAD

**Issue by arikak** [home-sweet-gnome/dash-to-panel#658]
I just just updated my Pop OS and dash to panel doesn't seem to work on the gnome 3.32 version. 
Any help is highly appreciated. This is my first post as I am fairly new to Linux and Github over all. 
Thank you so much in advance!

**Comment by linuxrx01** [comment]
What is the problem?

**Comment by arikak** [comment]
It works fine. I had to update the extension. My apologies for not realizing this!
