### ISSUE TITLE
[Feature Request] Music visualizer for panel à la pulse for android

### ISSUE THREAD

**Issue by sprince0031** [home-sweet-gnome/dash-to-panel#659]
Hey devs! Great extension and really love it.

I have a _feature request_. It would be great if a music visualizer could be included in the panel similar to the "Pulse" feature in android for the navigation bar as shown below.

![pulse](https://user-images.githubusercontent.com/19924682/58624941-025db100-82ef-11e9-9f31-e888115dde0f.gif)

At present, I can get this look using [cli-visualizer](https://github.com/dpayne/cli-visualizer) which displays the visualizer in the terminal. If I position it behind the panel with proper opacity settings, I get essentially the same thing. But it's such a pain to keep doing it every single time I boot up my laptop. So, I think it would be awesome if this feature could be baked right into the dash-to-panel extension (which is much easier said than done I'm sure!). The gif below shows what I mean.

![vis-feature-req](https://user-images.githubusercontent.com/19924682/58624553-2240a500-82ee-11e9-8341-6095eba75e69.gif)

Once again, great extension and thank you for the amazing work you've put into this.

Cheers!

**Comment by charlesg99** [comment]
Hello, I think this is out of the scope of this extension, especially if you can already get the desired effect. Maybe you should look into creating a script to automate the startup/positioning of cli-visualizer so it isn't a chore each time? Thanks!

**Comment by sprince0031** [comment]
> Hello, I think this is out of the scope of this extension, especially if you can already get the desired effect. Maybe you should look into creating a script to automate the startup/positioning of cli-visualizer so it isn't a chore each time? Thanks!

You're right @charlesg99 . This doesn't improve functionality in any way and is purely aesthetic. I have to admit, this does get pretty old after sometime to the point you stop noticing it as much. I've personally stopped using it actually.  Thank you for your time!

Cheers!
