### ISSUE TITLE
[Feature Request] Show dock on all displays.

### ISSUE THREAD

**Issue by hanabanashiku** [home-sweet-gnome/dash-to-panel#660]
By default, the dock only displays on the primary display. If there are multiple displays, I find it very useful to have the dock on all displays.

**Comment by charlesg99** [comment]
Hello Michael! In [dash to panel](https://github.com/home-sweet-gnome/dash-to-panel/blob/master/schemas/org.gnome.shell.extensions.dash-to-panel.gschema.xml#L478), panels are displayed on all monitors by default. You're probably referring to [dash to dock](https://github.com/micheleg/dash-to-dock/blob/master/schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml#L251) which doesn't display docks on all monitors by default. I suggest you open an issue over there. Thanks!

**Comment by hanabanashiku** [comment]
No, it's definitely dash to panel. Could possibly be a bug then? This was taken on Ubuntu 18.04

![image](https://user-images.githubusercontent.com/20232905/59234115-57d07280-8bb9-11e9-8eee-450c80871618.png)

**Comment by charlesg99** [comment]
Could you please post your current settings (in settings --> About tab --> export)? 

Once your settings are safely exported, maybe you could try resetting dash to panel to its defaults using `dconf reset -f /org/gnome/shell/extensions/dash-to-panel/`. What happens then? Does the panel show up on all monitors?

Thanks!

**Comment by hanabanashiku** [comment]
Sorry for the trouble, it looks like I've gotten it working. The export button wasn't on the tab so I figured maybe I had an old version, and sure enough, it works now. I guess the copy that's on extensions.gnome.org isn't up to date.
