### ISSUE TITLE
get error when installed on Ubuntu 19.04 gnome 3.32.1

### ISSUE THREAD

**Issue by brwright321** [home-sweet-gnome/dash-to-panel#662]
I have used dash-to-panel  for some time.  really like it.  no error messages when installed.  But yesterday (unknown time) it suddenly reported the red error message beside the dash-to-panel on my installed extension list.  I had not installed any other extensions recently (weeks ago), but the red error is there now.  I uninstalled it.  rebooted Ubuntu, opened Gnome extensions up, installed dash-to-panel, & immediately the red error takes over.  I have even did the Alt+r to reset gnome, but nothing changes, the red error is there.  Dash-to-panel seems to be working OK, except now the when you open the config setting, nothing in the "Fine-Tune" works.  You can make any change in "Fine-Tune" but it affects nothing.

**Comment by charlesg99** [comment]
Hello brwright321, could you please elaborate on the "red error message"? What is the actual error message coming from dash to panel (see your logs)? I have an up to date installation of Ubuntu 19.04 and I see no error. Thanks!

**Comment by charlesg99** [comment]
Hello, gonna close this since we have no update and everything seems to work correctly for me on Ubuntu 19.04 (Xorg and Wayland). If you still have problems, please disable every other extensions aside from dash to panel and restart gnome-shell, report back if the issue persists. Thanks!
