### ISSUE TITLE
[Feature Request] Tooltip on window preview

### ISSUE THREAD

**Issue by DragoCubed** [home-sweet-gnome/dash-to-panel#663]
On Windows I can hover over an app to bring up the window preview and then hover over the window preview to view a tooltip of the full title without switching to that app. This happens half a second (approx) after peek.  

If possible and/or if in scope, it would also be neat if hovering over windows in the application overview showed the full window names in their tooltips.

**Comment by jderose9** [comment]
Perhaps the window title could be presented along the top of the display when the window peek occurs?

**Comment by AlbinoGeek** [comment]
Also on Windows, the tooltip of windows sometimes gets "stuck open", "FOREVER", and the only fix is to restart the computer entirely. If you're going to implement the window titles, please don't do so using tooltips. They are huge pains. Unstylable, tiny unreadable fonts, and they "stick open" often.

I am +1 ing the suggestion to show the title above the window peek, as an OPTIONAL setting.
