### ISSUE TITLE
[Feature Request] Quit windows on alt+tab using middle click or X/close button

### ISSUE THREAD

**Issue by DragoCubed** [home-sweet-gnome/dash-to-panel#664]
I'm not sure if this would be allowed here but I'm submitting this issue anyway.

**Comment by charlesg99** [comment]
Hello DragoCubed, I think you'll have more you chance of getting that implemented if you address this issue to the [gnome-shell](https://gitlab.gnome.org/GNOME/gnome-shell/issues) developers. If you're using AlternateTab, that would be over [here](https://gitlab.gnome.org/GNOME/gnome-shell-extensions/issues). Thanks!

**Comment by DragoCubed** [comment]
https://gitlab.gnome.org/GNOME/gnome-shell/issues/23#note_530756 

I said this: 
> I've tried middle clicking, 0 and q.

Someone else said this:
> PS: I'm not sure why you tried middle clicking and <0>, neither are related to this feature (only <q>and )</q>

but the main issue says this:
> The current proposal, as discussed in https://bugzilla.gnome.org/show_bug.cgi?id=620106, involves pressing `Q` while the switcher is focused in either an app or an app's window, which should request closing the selected element.

:( i never have a good experience on gnome gitlab

**Comment by DragoCubed** [comment]
Little unrelated:
I'm going to be driven insane: https://gitlab.gnome.org/GNOME/gnome-shell/issues/1374

I hope they understand that I'm not even a developer and that I'm human too.

**Comment by Poopooracoocoo** [comment]
omg i feel you. gnome devs can be like that.
