### ISSUE TITLE
Feature Request:  NOT show application launch icons

### ISSUE THREAD

**Issue by corrilan** [home-sweet-gnome/dash-to-panel#667]
Hello

I would like to NOT show application launch icons but instead just show the date/time and network, sound, logout menu icons.  So in the screenshot below, I would like to eliminate the launch icons to the left hand side (Chome, Terminal, GIMP):

<img src="https://www.corrilan.com/icons2.png"/>

I am trying to replicate the Ubuntu 16.04 experience of the panel where I was able to see a panel similar to the above across all monitors.

I would still like to see the application icons shown in the normal dash down the left hand side of the screen.

Regards

Jason

**Comment by charlesg99** [comment]
Hello Jason, didn't think that option would be requested one day :) 

I guess there is no harm in it since we already provide the option to show the favorites or not... The option you requested was just added to the master branch, if you want to try it. Thanks!

**Comment by corrilan** [comment]
Hi Charles, thanks for your quick turnaround.  I will give it a go and report back.

**Comment by corrilan** [comment]
Hi Charles,

The running applications are no longer appearing as required.  Problem is the normal Ubuntu dash bar down the left hand side of the screen is also not showing, despite turning on the option "Keep original gnome-shell dash" under the Fine-Tune tab.

Regards

Jason

**Comment by charlesg99** [comment]
I think you're referring to the "Ubuntu Dock", not the dash (the gnome-shell dash is only visible while in the overview). Dash to panel disables the Ubuntu Dock when it loads, and I'm not sure adding an option to keep it is a good idea... 

For now you could just edit `~/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js`. Just replace line 38 with `const UBUNTU_DOCK_UUID = '';` and restart gnome-shell. There may be some conflicts, but it should give you the layout you want.

Thanks!

**Comment by corrilan** [comment]
Hi Charles

Yes that is working for me, thanks.

Regards

Jason
