### ISSUE TITLE
language

### ISSUE THREAD

**Issue by vav4eg** [home-sweet-gnome/dash-to-panel#668]
Good afternoon, please tell me how to switch the language settings from English to Russian? I have everything mine in English.

**Comment by charlesg99** [comment]
Hello, dash to panel uses the same language as the one defined for gnome-shell (in Settings -> Region & Language). If no matching translation is found, dash to panel defaults to English. We only have `ru_RU` as Russian locale, so you would need to set the gnome-shell language to Russian from Russia (I think, didn't test). Hope this helps!

**Comment by vav4eg** [comment]
Thanks for the answer. My system has Russian localization. The Russian language and location Russia is set in the system settings. I assume that after upgrading the kernel or system something has changed and now the extension cannot automatically do it. The problem arose not only from me, but from other guys from my region. Tell me, is it possible to change the language manually or check the correctness of the automatic language change? In the extension folder there is a file with Russian localization.

**Comment by charlesg99** [comment]
Unfortunately, we can't manually change the language via the extension settings. 

So it worked before and now it doesn't? Did it stopped working recently? Is the rest of gnome-shell correctly displayed in Russian? Which gnome-shell version is that? Could you please report the output of `locale -a` on your system? Sorry, many questions :) Thanks!

**Comment by vav4eg** [comment]
Previously, the expansion settings were in Russian, but then at a certain point, the settings suddenly became in English. I don’t know when exactly this happened, but I suppose that this happened after the automatic installation of a system or kernel update. I have the whole gnome-shell in Russian, but the settings for the Dash extension are in English.

**locale -a**
```
C
C.UTF-8
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
en_IL
en_IL.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ.utf8
en_PH.utf8
en_SG.utf8
en_US.utf8
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW.utf8
POSIX
ru_RU.utf8
ru_UA.utf8
```
**gnome-shell --version**
`GNOME Shell 3.28.4`

 ** uname -r**
`Linux vav4eg 4.18.0-21-generic #22~18.04.1-Ubuntu SMP Thu May 16 15:07:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by charlesg99** [comment]
Hello vav4eg, 

I installed Ubuntu 18.04 and I think the issue lies with the tool to install new languages. If I install Russian, it puts `ru` as locale instead of `ru_RU`. For now, to fix the problem, go into `~/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale` and rename the folder `ru_RU` to `ru`, then restart gnome-shell. 

In the meantime I'll try to understand why it happened and probably just fix it by renaming our `ru_RU.po` to `ru.po`.


![image](https://user-images.githubusercontent.com/33044886/60635945-8e796180-9de2-11e9-8e9a-a455ca637094.png)

Thanks!

**Comment by vav4eg** [comment]
Good day! Thank you very much. Your advice helped me change the language. When I renamed the folder, the language changed!)

**Comment by charlesg99** [comment]
Glad it worked! I ended up renaming the `ru_RU.po` file to fix the issue. Thanks!
