### ISSUE TITLE
GNOME 3.34: Wrong arrow position on Calendar

### ISSUE THREAD

**Issue by alex285** [home-sweet-gnome/dash-to-panel#669]
The first thing to notice is the Calendar arrow on the red, which is the actual bug (tested on Fedora Rawhide with GNOME 3.33.3)

Moreover I want to make a suggestion. Following the https://github.com/home-sweet-gnome/dash-to-panel/issues/116 I believe the arrows on yellow should be completely dropped; they don't make any sense in Dash to Panel, no matter if it is on top or bottom, and of course the Calendar itself hasn't any arrow at all 

![Screenshot from 2019-06-25 10-35-01](https://user-images.githubusercontent.com/11244308/60078850-7005cd00-9735-11e9-84cc-f2653edfb53c.png)

**Comment by alex285** [comment]
This is not very good implementation, but considering the panel arrows, what if there were actually grouped with some background color, derived from panel color (lighten/darken) like Chrome OS?

![Screenshot from 2019-06-25 10-35-01-2](https://user-images.githubusercontent.com/11244308/60079674-143c4380-9737-11e9-9586-10ef06521258.png)

**Comment by charlesg99** [comment]
Hey Alex, seems like the arrow position was fixed on 3.33.4. My kind of bug!

As for the grouping background color, not sure which theme you're using but with Arc-Dark it looks like this when I open a menu:

![image](https://user-images.githubusercontent.com/33044886/62393447-34ca9b00-b538-11e9-918f-8cc35652da84.png)

Or do you mean that the background color would always be different, even when there is no opened menu?

**Comment by alex285** [comment]
> As for the grouping background color, not sure which theme you're using but with Arc-Dark it looks like this when I open a menu:

i meant to add some grouping/colored/whatever before a user clicks on it; but anyway that is a different issue (there is #116 anyway), and original issue fixed, so im closing it!!
