### ISSUE TITLE
Panel glitches out after suspend

### ISSUE THREAD

**Issue by arnohovhannisyan** [home-sweet-gnome/dash-to-panel#671]
After suspending or locking the screen, this happens:

![image](https://user-images.githubusercontent.com/25834068/60322641-03870a00-9991-11e9-85be-d6371f478ab7.png)

Same with app menu:

![image](https://user-images.githubusercontent.com/25834068/60322615-f702b180-9990-11e9-8b9f-044517117579.png)

But the rest of the panel seems to be fine:

![image](https://user-images.githubusercontent.com/25834068/60322681-1a2d6100-9991-11e9-984f-cfce79cb8e7f.png)

Additional Info:
* The panel also shows up in GDM. 
* `Alt + F2 -> r` fixes it temporarily until the next suspend.

**Comment by charlesg99** [comment]
Hello arnohovhannisyan!
 
> The panel also shows up in GDM

This is likely another of your extension. Please disable all of your extensions aside from dash to panel, restart gnome shell and see if you have the same problem when locking/unlocking your screen. You can also have a look at your logs using `journalctl /usr/bin/gnome-shell -f -o cat` to find what is the error causing this. 

Thanks!

**Comment by arnohovhannisyan** [comment]
Hi @charlesg99!

> This is likely another of your extension.

It turned out to be the `Extensions Sync` extension. After disabling it, the issue didn't happen anymore. Anyway, thanks for your help!

**Comment by charlesg99** [comment]
Great, glad you got it resolved!
