### ISSUE TITLE
Poor performance when switching workspaces, dragging windows between monitors

### ISSUE THREAD

**Issue by chrisjbillington** [home-sweet-gnome/dash-to-panel#672]
Firstly, thanks for this excellent extension. It's the only way presently on GNOME+wayland to have a traditional window list with ungrouped windows and window titles that allows isolating monitors and workspaces, other than the unthemed/not very featureful/customisable official GNOME window list extension, and I appreciate it a whole lot.

One issue I've been having is performance. There are two cases in which the extension seems to cause stuttering in gnome-shell substantial enough to be a bother.

One is when dragging a window between monitors. Gnome-shell stutters as the centre of the window crosses from one monitor to the other. This is particularly bad on Wayland with its software mouse cursor, since the mouse doesn't 'catch up' after the lag and the drag ends up being less distance than your muscle memory expected. This lag is occurring whilst the extension is animating the disappearance of the window on one monitor and its appearance on the other. The lag is *not* present if one disables isolating monitors. So I suspect it is poor performance whilst doing the animation.

The other lag is when switching workspaces. This one is substantial, almost a full second for me. It does not go away when disabling isolating workspaces in the extension. But it does go away if I revert to the default configuration of the extension. In fact, I'm having a hard time figuring out what setting it depends on. Here is my saved config, if it helps working out what is causing the issue.

I'm on gnome-shell 3.32.2 under Wayland on Arch Linux 

```
[/]
animate-app-switch=false
animate-show-apps=true
animate-window-launch=false
appicon-margin=0
appicon-padding=4
dot-color-1='#5294e2'
dot-color-2='#5294e2'
dot-color-3='#5294e2'
dot-color-4='#5294e2'
dot-color-unfocused-1='#5294e2'
dot-color-unfocused-2='#5294e2'
dot-color-unfocused-3='#5294e2'
dot-color-unfocused-4='#5294e2'
dot-position='BOTTOM'
dot-size=0
dot-style-focused='DASHES'
focus-highlight=true
focus-highlight-color='#555753'
focus-highlight-opacity=50
group-apps=false
group-apps-label-font-color='#eeeeec'
group-apps-label-font-size=13
group-apps-label-font-weight='normal'
group-apps-label-max-width=140
group-apps-underline-unfocused=false
group-apps-use-fixed-width=true
group-apps-use-launchers=true
hot-keys=true
hotkeys-overlay-combo='TEMPORARILY'
isolate-monitors=true
isolate-workspaces=true
location-clock='STATUSLEFT'
middle-click-action='QUIT'
multi-monitors=true
panel-position='BOTTOM'
panel-size=26
secondarymenu-contains-showdetails=false
shift-click-action='MINIMIZE'
shift-middle-click-action='LAUNCH'
show-activities-button=false
show-appmenu=false
show-clock-all-monitors=true
show-favorites=true
show-favorites-all-monitors=true
show-show-apps-button=false
show-showdesktop-button=false
show-status-menu-all-monitors=true
show-window-previews=false
status-icon-padding=-1
stockgs-keep-dash=true
stockgs-panelbtn-click-only=false
trans-gradient-bottom-color='#000000'
trans-gradient-bottom-opacity=0.0
trans-gradient-top-opacity=0.0
trans-panel-opacity=0.80000000000000004
trans-use-custom-bg=true
trans-use-custom-gradient=false
trans-use-custom-opacity=true
tray-padding=4
tray-size=0
```

**Comment by charlesg99** [comment]
Hello chrisjbillington, thank you for the report. 

I can't reliably reproduce this lag... I tried all sorts of dash to panel settings, on many gnome-shell versions (wayland and xorg) and the only way I get a "lag" when moving a window to another monitor is on a VM where I assign a single cpu and slow it down to a crawl. The weird thing is that this lag is present even when the extension is disabled. So far, you're (that I know of) the second person [reporting this](https://github.com/home-sweet-gnome/dash-to-panel/issues/35#issuecomment-428556199), so I'm not sure this is a widespread issue. Same thing goes for the workspace switch (using your settings).

I don't think it is related to the animation, but to be certain, could you try disabling them altogether in the tweaks tool, under the "general" tab and see if that reduces the lag? Do you see the same lag on Xorg?

Thanks!

**Comment by chrisjbillington** [comment]
Thanks for being so thorough trying to reproduce the problem!

I'm sorry to say though that today I cannot reproduce the window dragging problem at all! Sorry because it means you may have wasted your time investigating, though perhaps it is good news too. I wish I'd made a screen recording of it.

A bunch of packages on my computer updated in the last 2 days, I can't see any of them being super relevant, though systemd was  one of them. And I did notice some funky behaviour on my computer yesterday (a Python program was getting an input/output error calling print! That should never happen, but it went away after a reboot...) so perhaps there was something very wrong with my computer on a low level that is now resolved for whatever reason. It is a fairly powerful computer so I don't think I was seeing the same effect as you managed to see in the crippled VirtualBox.

Unfortunately I don't remember whether the problem was present on X as well. If I see the issue again I will comment again here, and will get a screencast of it.

The workspace switching issue is still present however. It seems to depend on how many windows are open and is worse when using two monitors than when using one. Here is a screencast of it, you can see that only one or two frames of animation is present when switching workpsaces:

https://drive.google.com/open?id=1ssK170SdEFH6ox0NzpwEen-W6y6s97-s

I'll try to 'bisect' between the default config and my config to see what it depends on. It is present both in X and Wayland.

**Comment by chrisjbillington** [comment]
OK, I've worked out what settings trigger laggy workspace switching for me. From a default configuration with no other shell extensions running, enabling "isolate workspaces" and "ungroup applications" seems to be what makes it laggy. Even if you then disable "isolate workspaces", it is still laggy until restarting gnome-shell (on xorg) or logging out and in again (on wayland).

**Comment by charlesg99** [comment]
Thank you for the investigation! I could indeed reproduce the laggy workspace switch with the settings you mentioned. Very odd, this seems to be new on 3.32. A fix for it was added to the master branch, could you please pull/install to see if that fixes the issue on your end? Thanks!

**Comment by chrisjbillington** [comment]
Thanks very much, that fix does the trick for me! I'll close this, and will re-open if laggy window dragging shows up again. Thanks again!

**Comment by mweirauch** [comment]
Oh wow. I just upgraded two F29 (3.30) to F30 (3.32) installs recently and I was like... this feels less snappy then on F29. (Running on Wayland HiDPI 200% scaling which is less performant then X.org anyways.)

Then I stumbled upon a 3.32 with most of the 3.34 fixes backported and it felt way better, even to that extend that I'd say it runs better then with X.org. C.f. https://copr.fedorainfracloud.org/coprs/pp3345/gnome-with-patches/

Thanks for the fix. Even a bit better now. Not entirely stutter-free but I have the suspicion that the 200% scale (on a 4k display) has its influence on gnome-shell itself as it's not that noticeable on an unscaled display.

**Comment by charlesg99** [comment]
Glad it helped! I just got back on my work computer this morning (gnome-shell 3.28.3) and the workspace switch lag isn't present (before applying the fix), so my guess is that it was introduced with 3.32. Guess we hit a sensitive gnome-shell + Mutter interaction :)

**Comment by chrisjbillington** [comment]
Unfortunately it seems to me that this issue isn't fixed after all. It seems like the situation is maybe improved on Xorg, but not on Wayland. Though I could be wrong about that. I tried to make a video of what it's looking like now, but the screen recording options on Wayland are limited, and one I did find that worked seemed to introduce such a large performance overhead that it caused almost as much stuttering as the issue I'm trying to demonstrate! But, it looks identical to before - only one or two frames when switching desktops when there are many windows visible.

I do think the patch improved things slightly, but with a modest number of windows things seem to get choppy again, so I think I'll reopen this issue in case people want to discuss more or try to figure it out.  Since it sounds like an issue on gnome-shell 3.32 and possibly improved by upcoming changes in 3.34, more information might come to light as the less bleeding edge distros are updating to 3.32, and in a few months when the more bleeding-edge ones get 3.34.

I am happy to test any patches or to try out any different configurations anyone wants to suggest.

I have a slight suspicion that performance is worse after suspend/resume, but this isn't super substantiated.

**Comment by chrisjbillington** [comment]
I'm just trying out a bunch of the performance improvements that are in unmerged patches in gnome-shell and mutter (via the very helpful [AUR packages](https://aur.archlinux.org/packages/gnome-shell-performance/)), and things are *a lot* snappier. It really can't be understated. So it may be that this issue will be solved by changes in gnome-shell and mutter, and that you shouldn't spend much time trying to address it in dash to panel.

**Comment by charlesg99** [comment]
3.32 brought many performance improvements, but also did slow down some animations. For me the worst one is when clicking on the "Show applications" button, the lag is terrible. This and the workspace switching lag were both reported upstream [[1](https://gitlab.gnome.org/GNOME/gnome-shell/issues/1372), [2](https://gitlab.gnome.org/GNOME/gnome-shell/issues/982)], so, unfortunately, I don't think we'll be able to do much about those for now.

**Comment by chrisjbillington** [comment]
Sounds good! I'll leave the issue open so that others can see it, and I'll close it once an officially released gnome-shell resolves the issue, which I expect it will.

**Comment by charlesg99** [comment]
Hello Chris, with the inclusion of the gnome-shell/mutter performance patches in 3.34, are you comfortable closing this? I also updated to 3.34 and, even if there are still some rough edges, it clearly is an improvement performance wise. Thanks!

**Comment by chrisjbillington** [comment]
Absolutely. I still see a couple of dropped frames when dragging windows between workspaces, but it is very minor, and even that goes away with the use of the remaining unmerged performance patches for mutter.

Thanks!
