### ISSUE TITLE
Translations needed for v20 release

### ISSUE THREAD

**Issue by jderose9** [home-sweet-gnome/dash-to-panel#674]
Hi all! We are looking for updated translations for the v20 release in roughly 1 week. If you are able to help, please submit the updates as a pull request. Thank you so much for pitching in!

@frnogueira (pt_BR), @zeten30 (cs), @franglais125 (es), @LaurentTreguier / @SolarLiner (fr), @elsieholmes (uk), @hosiet (zh_CN), @jonnius (de), @urbalazs / @pappfer (hu), @crayxt (kk), @pkomur / MartinPL (pl), @AlexGluck / @GoodNike (ru), @sicklylife-jp (jp), @oltulu / @TeknoMobil / @daenney (tr), @sbadux (it), @OriginCode (zh_TW)

**Comment by urbalazs** [comment]
#681

**Comment by SolarLiner** [comment]
#683 for French translations (quickly tested by going through all options and verifying they make sense within the context of the extension)

**Comment by vmalta** [comment]
The pt_BR translation was no more updated. Where i can find base file to do the new translation?

**Comment by jderose9** [comment]
@vmalta Check out the Makefile. `make potfile` will generate the pot file,`make mergepo` to merge with existing translations.

**Comment by OriginCode** [comment]
#688

**Comment by OriginCode** [comment]
#692 for zh_TW translation update.

**Comment by charlesg99** [comment]
Thanks!
