### ISSUE TITLE
Ungrouped windows can only be re-ordered as a group

### ISSUE THREAD

**Issue by chrisjbillington** [home-sweet-gnome/dash-to-panel#676]
When "ungroup applications" is enabled, one can drag the entries in the panel for different windows to re-order them.

However, when multiple windows come from the same application, they are stuck together still, and can only be re-ordered as a group. Here is an example:

![reordering](https://user-images.githubusercontent.com/1044087/60759326-77f52500-9ff1-11e9-8376-c282a22453c6.gif)

The two 'files' windows can only be moved together, and the two terminal windows also, such that one cannot create an ordering of [files] [terminal] [files] [terminal].

Ideally, when applications are ungrouped, the windows would be arbitrarily re-orderable regardless of what application they are from.

I suspect that ungrouping the reordering of windows in the way I'm requesting only makes sense however if 'use the favourite icons as application launchers' is enabled in the options for ungrouping applications. So likely the current behaviour should be retained unless 'use the favourite icons as application launchers' is enabled, in which case one has a very traditional panel setup where the running windows are completely separate from the launchers and imposing any grouping on them is no longer necessary.

**Comment by charlesg99** [comment]
Yeah exactly, we decided to allow reordering of the "application groups" and the "application instances" within an "application group". You deduced correctly about the application launchers, as it wouldn't make much sense if we allowed the application instances to be separated while displaying favorites (without them being launchers). 

I'm personally not very inclined to changing this, but let's leave it open and see if it gets upvotes. Thanks!

**Comment by Ben64** [comment]
Just commenting to say I'd really like this as well.

**Comment by radzish** [comment]
This one is probably the last one stopping me to switch to gnome. Are there any technical challenges with implementation of this?

**Comment by isi-floss** [comment]
I would love to see this feature! This is the main point holding me back from using Gnome.

**Comment by timrobinson33** [comment]
I use an extension (called taskbar tweaker) to do this in Windows and find it really useful.

Usually I'm working on several tasks at once: Task one might involve an IDE, a couple of browsers and some terminal windows, task 2 might be a browser and a word document, task 3 is vim, a browser and a terminal window. Ungrouping the windows is essential so I can switch with only one click, but I also want to be able to manually put the ones for each task next to each other. (vertical dock is pretty much essential to work in this way)

I've tried multiple workspaces but that's too much friction.

**Comment by Ben64** [comment]
Yes, I'm still waiting for this option

**Comment by chrisjbillington** [comment]
Hello stale bot, I would like this issue to remain open please and thanks

**Comment by Ben64** [comment]
I wish I knew enough to fix this myself

**Comment by chrisjbillington** [comment]
Hello stale bot, I would like to keep this issue open still, thank you 👍

**Comment by Ben64** [comment]
Yep, still waiting for this.

**Comment by Ben64** [comment]
Is it just me or is this not working? Installed the latest source from git on ubuntu 22.04 and still can't get them to ungroup

**Comment by chrisjbillington** [comment]
FWIW It's working for me on Arch Linux with latest git master.

**Comment by charlesg99** [comment]
@Ben64 The splitting of applications was only possible if the "Use favorite icons as launchers" was selected. Your post had me realize that we could also allow splitting the applications as soon as the favorites aren't displayed on a panel. I just pushed a fix to allow that as well.

**Comment by Ben64** [comment]
Awesome, works great, thanks!
