### ISSUE TITLE
[feature request] greyed-out font/icon for minimised windows

### ISSUE THREAD

**Issue by chrisjbillington** [home-sweet-gnome/dash-to-panel#678]
Once again thanks for this great extension. I'm finally making the switch to Wayland and this extension is the best way I've found to have a traditional taskbar on gnome-shell.

Previously, I was using tint2 (which only works on X), and I had it configured to grey out the taskbar entries for minimised windows. It looked like this:

![tint2](https://user-images.githubusercontent.com/1044087/60759676-2c457a00-9ff7-11e9-8d7d-7c46010f3fb5.png)

With the icons and window titles for the minimised windows (the final two entries) greyed out somewhat.

It would be nice to have this option in dash to panel - it's useful to have an indication in the taskbar of whether a window is minimised or not. Obviously this only makes sense when 'ungroup applications' is enabled.

**Comment by levacic** [comment]
Hey I also wanted this so I hacked it up a bit:

https://github.com/levacic/dash-to-panel/commit/d8b7ec1f63f5bc0a0517e0e9a3cb9f63aaa68471

This works for me although the color used for minimized windows is hardcoded to `#777777` - but feel free to change it.

I'm not really familiar enough yet with the extension's configuration mechanism to actually make it a configurable option - but I might tackle that when I get some time these days and send a PR.

**Comment by charlesg99** [comment]
This was added by @levacic! Thanks!

**Comment by chrisjbillington** [comment]
Thanks so much @levacic !
