### ISSUE TITLE
 Laggy mouse when hovering over taskbar [Wayland]

### ISSUE THREAD

**Issue by mdsitton** [home-sweet-gnome/dash-to-panel#684]
in issue #561 it was thought that the new window preview implementation would fix this. However it does not fix the issue.

So i am opening up a new issue as was mentioned there.

I'm running gnome 3.32.2 on arch Linux, with 2x 4k monitors using the open source radeon driver, as a wayland session.

The lag does not always happen immediately after loading the desktop session.

The only "fix" i've found is to just disable window previews all together.

Another issue i have found similar, is moving windows between monitors can also cause lag when it's trying to snap windows to the edge of the monitor.

edit:
Also there seems to be the same lag when having "Show tooltip on hover" enabled, so disabling both is required to have a lag-less taskbar...

**Comment by jderose9** [comment]
@mdsitton This code hasn't been released yet, so I just wanted to confirm that you are running the latest master branch pulled from github while seeing this issue? Otherwise, we will be making a new release very soon.

**Comment by chrisjbillington** [comment]
I saw this too in gnome 3.32, but it was resolved after I updated to [custom gnome-shell](https://aur.archlinux.org/packages/gnome-shell-performance/) and mutter packages on Arch that backport a number of performance patches currently in development to 3.32. So for what it's worth, I suspect this will cease to be an issue on gnome 3.34, without dash to panel having to fix anything. If it were me I would not bother expend effort fixing it unless 3.32 is on an LTS Ubuntu release or a Debian stable release or something similarly long-lived, or if it shows up in Gnome 3.34, which is to be released a little over a month from now.

**Comment by charlesg99** [comment]
Thanks for the input @chrisjbillington! Yeah I also saw some similar reports on vanilla gnome-shell [[1]](https://bugzilla.gnome.org/show_bug.cgi?id=745032) [[2]](https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1690719) (mouse over the dash icons, top bar, etc.). Seems like a known issue with Mutter+Wayland, and I don't think we can do much about it.

@mdsitton could you please confirm that you're experiencing the issue on v20 (which you installed from github, as it isn't released yet on e.g.o.) like Jason asked a while back?

**Comment by charlesg99** [comment]
A follow up... Not sure which recent update did it, but it's been silky smooth for me on Arch (g-s 3.32.2) since about a week. This is without the AUR packages... so I'm pretty happy about that!

**Comment by chrisjbillington** [comment]
Looks like the Arch packager [decided to include some of the performance patches](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/gnome-shell&id=c481cc36a043b8299f110e8eafe2429c92999445). Nice.

**Comment by mdsitton** [comment]
I'll try updating my system soon. Hopefully those patches will help the situation.

**Comment by charlesg99** [comment]
Closing as it seems to be resolved with the release of gnome-shell 3.34, please see #672. Thanks!
