### ISSUE TITLE
Incompatibility with Invert Window Color

### ISSUE THREAD

**Issue by kevinjohncutler** [home-sweet-gnome/dash-to-panel#686]
Invert Window Color fails to toggle using Super+I when Dash to Panel is enabled. Dash to Dock is compatible. Maybe there is a shortcut conflict? Any windows that I inverted with Dash to Panel _off_ do remain inverted when I turn it on. It's just that I cannot toggle any windows after it is turned on.

**Comment by charlesg99** [comment]
Hello, looks like Invert Window Color also uses <kbd>Super</kbd>+<kbd>i</kbd>. If you're not using it, you could change the conflicting dash to panel shortcut in the intellihide settings: 

![image](https://user-images.githubusercontent.com/33044886/61381023-6f65df80-a878-11e9-8696-4657b58fc27a.png)


Thanks!

**Comment by kevinjohncutler** [comment]
That solved it, thanks!

**Comment by vspinu** [comment]
The shortcut interferes even when the inteli-hide is off. So you would need to activate it first, remove the shortcut, and deactivate again.
