### ISSUE TITLE
Hotkeys always active

### ISSUE THREAD

**Issue by markomarkovic** [home-sweet-gnome/dash-to-panel#687]
_Dash to Panel v19_
The hotkeys are active (you can start apps by using `<super>+num`) even though the *Use hotkeys to activate apps* is deactivated.

When I activate it and set the hotkey prefix to `Super+Alt`, it's not honored, only `Super` is needed still.

**Comment by charlesg99** [comment]
Hi Marko! gnome-shell 3.32 [introduced similar hotkeys](https://gitlab.gnome.org/GNOME/gnome-shell/commit/4590094605774dab4c76d67953cf032616dee089), and we don't deactivate those... Is this the version you're on? 

Also, do you see errors in your logs when enabling/disabling/using hotkeys if you run `journalctl /usr/bin/gnome-shell -f -o cat` beforehand? If you're on 3.32 and are seeing something like `reference to undefined property "_numHotkeys"`, this was fixed on the master branch and should release soon with v20. 

Thanks!

**Comment by markomarkovic** [comment]
It's possible that that's it as I'm on `GNOME Shell 3.32.1`, but I'm not seeing those messages when toggling the hotkeys.

**Comment by jiff88** [comment]
I am kindly voting for release 20 to happen; as i am unable to use my keyboard shortcuts scheme now (i prefer to switch workspaces with `Super+1`, `Super+2`, ...), thanks!

**Comment by jderose9** [comment]
@jiff88 releasing now, just for you ;)

**Comment by jiff88** [comment]
This .. was .. super-kind ..
Next time i develop something for Linux, you'll be my first-class citizen.
Take care.
