### ISSUE TITLE
Touching App Icons on Wayland occasionally freezes system. X functions as it should

### ISSUE THREAD

**Issue by mattdementous** [home-sweet-gnome/dash-to-panel#689]
Touching App Icons on Wayland occasionally freezes system. X functions as it should.
I have a laptop (razer blade 14) with a touch screen. Tapping on app icons when in a wayland session on Pop OS sometimes functions as intended, but other times will initiate a drag response and when this happens, or when it registers it as a double tap, everything but keyboard commands freeze up. No clicking on interface elements or tapping works. I'm able to keyboard launch the terminal and sudo gnome-session-quit or whatever, then press Tab and enter to log out. Logging back in, everything is fine.

**Comment by tom0105** [comment]
I can confirm this issue using Fedora 30 Gnome Version 3.32.2 Wayland session on a Toshiba Portégé X20W convertible. After an initiated drag event on an icon, touchscreen / touchpad inputs are no longer working. After logging out and back in using the keyboard, touch events are registered correctly again.

**Comment by 4ndyZ** [comment]
Same problem here using Fedora 30 Gnome Version 3.32.2 Wayland on a Thinkpad X390 Yoga convertible.
The touchscreen freezes if the drag event happens (no interaction possible). Only solutions is logging out and back in as mentioned before.

**Comment by Be-ing** [comment]
I confirm this bug too, using Fedora 30 with GNOME Shell 3.32.2 and Wayland. Touching the app icons in the dock with this extension disabled works fine. Perhaps his [GNOME Shell bug](https://gitlab.gnome.org/GNOME/gnome-shell/issues/1409) is related?

**Comment by codeMoney095** [comment]
I'm on Manjaro and having the same issue

**Comment by PopeRigby** [comment]
Having the same issue on my Lenovo IdeaPad running Arch Linux. I'm using GNOME Shell 3.36.6 on Wayland.

**Comment by zacchi4k** [comment]
Same issue on Debian Sid with GNOME 3.38.2 on Thinkpad X230T. Pen input isn't affected by this bug

**Comment by dexterdy** [comment]
also having this problem on fedora 33 and gnome 3.38.5. seems to be affecting dash to dock as well somehow

**Comment by lumarel** [comment]
As this got marked as stale...
This problem is still going on in GNOME 40.3.0, tested on fedora 34.
But unfortunately I wasn't able to gather further information myself.

**Comment by 9Lukas5** [comment]
Ok, as the other one's closed as duplicate, this ones fairly old and no one had this tip posted yet and we need some conversation going on for the stale bot I'll add my comment here, too:
https://github.com/home-sweet-gnome/dash-to-panel/issues/1484#issuecomment-1036408669

The taskbar is by default changeable. By right clicking and locking it I'm able to use the app icons by touch perfectly fine. I'm on Gnome 40, so if anyone could verify this workaround , I'd appreciate it 👍🏼

**Comment by HonbraDev** [comment]
@9Lukas5 locking the taskbar solves the freezing issue for me on GNOME 41.5. It's still hard to not move the cursor while touching, but that's a separate issue.
