### ISSUE TITLE
Question: Reset all settings to defaults

### ISSUE THREAD

**Issue by daniel-wtd** [home-sweet-gnome/dash-to-panel#691]
Hey,

thank you for the cool extension. I just have a very brief question, which may b added to the FAQ. Is it possible to reset all settings from dash-to-panel? If yes, how?

Regards,
Daniel

**Comment by charlesg99** [comment]
Running `dconf reset -f /org/gnome/shell/extensions/dash-to-panel/` in a terminal should do the trick! Also added the command to the FAQ section of the readme. Thanks!

**Comment by daniel-wtd** [comment]
awesome, thank you!
