### ISSUE TITLE
Gnome 3.33.4 - panel doesn't load after unlock screen

### ISSUE THREAD

**Issue by bitstrings** [home-sweet-gnome/dash-to-panel#694]
With the latest fix for 3.33.x (i.e.: latest master), the panel works but doesn't reload after unlocking.

I use ALT+F2 to reload gnome-shell to make it work again.

**Comment by charlesg99** [comment]
Thanks for the report, you're absolutely right! Should now be fixed on master.

**Comment by bitstrings** [comment]
Tested and looks good!

Amazing.
