### ISSUE TITLE
Enabling intellihide on window obstruction causes panel not to load on login

### ISSUE THREAD

**Issue by edwinvandeven** [home-sweet-gnome/dash-to-panel#695]
First of all, I love the latest update, thank you so much!

I seem to have found a bug. Enabling the following setting causes the panel to not load on login when certain conditions are met: 
Panel intellihide -> only hide the panel when it's obstructed by windows.
(It doesn't seem to matter which option is chosen under the panel hides from)

The panel loads on login when my laptop is connected to an external monitor, but it sometimes crashes. It doesn't load on login when using the laptop's own screen. A restart using Alt + F2 -> r always bring the panel back. I'm using Pop!_OS 18.04.

Please feel free to ask for any additional information or logs that would be helpful.

**Comment by charlesg99** [comment]
Hello edwinvandeven, thank you for reporting this. We'll need more information as I can't reproduce the issue so far (on gnome-shell 3.28). Since the extension isn't loading, you'll most likely find a corresponding javascript error in your logs. Could you reproduce the issue and then have a look using `journalctl /usr/bin/gnome-shell --since='10 minutes ago'` and report back? Thanks!

**Comment by edwinvandeven** [comment]
Hi Charles, Thank you for the very quick response! 

I reproduced the issue and attached is the log since the last reboot. To double check that it wasn't because of interference by one of the Pop extensions, I tried to reproduce it on a clean Ubuntu 18.04 VM. There it showed the same behavior. 

In the Pop logs I couldn't find anything that looked like a clear loading error. Though there was one error related to dash-to-panel in the Ubuntu logs:
`aug 08 10:13:08 edwin-vbx1804 gnome-shell[1233]: Object .Gjs_DashToPanel-PreviewMenu (0x55a56628cb20), has been already finalized. Impossible to set any property to it.`

I've attached the logs from both systems. As I'm not that knowledgeable about the deeper workings of the gnome shell, I might have missed some important messages in the logs.

[log_ubuntu_1804.txt](https://github.com/home-sweet-gnome/dash-to-panel/files/3480559/log_ubuntu_1804.txt)

[log_popos_1804.txt](https://github.com/home-sweet-gnome/dash-to-panel/files/3480560/log_popos_1804.txt)

**Comment by charlesg99** [comment]
Hi Edwin, thanks for the additional info, I could reproduce the error in your log and a fix for it was just added to the master branch. Could you please check if it resolves the issue?

**Comment by edwinvandeven** [comment]
Hi Charles, thank you, it works as expected now! You're awesome!

**Comment by charlesg99** [comment]
Great! Thanks for the feedback!
