### ISSUE TITLE
Is version 20 still queued on the Gnome extensions website?

### ISSUE THREAD

**Issue by simonbcn** [home-sweet-gnome/dash-to-panel#697]
I find it embarrassing that version 20 published 19 days ago is still not updated on the Gnome extensions website.
Is it a GNOME problem? How long ago did you upload it to the GNOME website?
If it's a Gnome problem, do you know where I can complain about its slowness?

**Comment by jderose9** [comment]
Yes, the GNOME review process is very slow. It has been brought up many times on the mailing lists and reddit without any new process gaining traction. You can see the review queue here:

https://extensions.gnome.org/review

Extensions can override pretty much anything in the desktop environment. It makes sense that they don't want to give the stamp of approval that might be responsible for serious security or performance concerns on a users system. And, I understand the number of volunteers qualified and willing to perform the reviews are fairly limited.

I think generally it's not the end of the world for users to wait to get a shiny new feature, but it is frustrating when a new version of GNOME Shell is released and the existing extensions are not supported. I wish they would build extension approval into their release timeline.

Once there is a feature freeze for a new version of the shell, there's only a few weeks to implement a fix to breaking changes and get that submitted before the final release, and frequently the extensions may not get reviewed for another month or two, leaving a lengthy gap where most extensions are broken. It would be nice to have a milestone on the timeline such as "submit extension for review by X date and we will do our best to get it reviewed by the time of the official release".

**Comment by viggy96** [comment]
Yeah, this is definitely an issue that can be solved with a change in administrative processes, and doesn't involve code at all. Is there any place to provide feedback to GNOME to suggest the change that you're talking about?

**Comment by jderose9** [comment]
The mailing list and IRC are probably good official avenues. There are a number of frequent shell contributors on reddit as well.

https://wiki.gnome.org/Community/GettingInTouch
https://www.reddit.com/r/gnome/

**Comment by charlesg99** [comment]
Seems like v21 got approved on e.g.o. :tada:
