### ISSUE TITLE
Constant high cpu usage on gnome-shell 3.33.90

### ISSUE THREAD

**Issue by bitstrings** [home-sweet-gnome/dash-to-panel#700]
There is constant high cpu usage on gnome-shell 3.33.90.

I have reset settings to default = same.
I have disabled all other extensions = same.

**Comment by charlesg99** [comment]
Hello bitstrings, from my observations on 3.33.90, enabling/disabling Dash to Panel doesn't affect the perceived cpu usage... Are you seeing a notable difference in comparison with vanilla gnome-shell? Thanks!

**Comment by bitstrings** [comment]
I have tested this on 2 different systems. If i enable dash then at least 1 core goes to 80-100%. If i disable favorites and active apps then it returns to normal.

I will do more testing today as I will test on another system.

**Comment by bitstrings** [comment]
Yep, 3rd machine and does the same. All are on Fedora Rawhide and 3.33.90. It's gnome-shell that goes crazy.

**Comment by bitstrings** [comment]
Like I said. If I disable the "Show favorite/Show running" everything goes back to normal.
![image](https://user-images.githubusercontent.com/911165/62955777-a66bda00-bdbf-11e9-957e-c7624861c938.png)

**Comment by chrisjbillington** [comment]
X or wayland?

**Comment by bitstrings** [comment]
X

**Comment by linguohua** [comment]
I have the same problem too, fedora rawhide 32, gnome 3.33.90, in vmware 15.

**Comment by charlesg99** [comment]
I really wish I could reproduce that... Here is what I'm seeing on 3.33.90 and Xorg, the cpu usage remains the same with or without dtp:

![Peek 2019-08-23 10-43](https://user-images.githubusercontent.com/33044886/63601231-09652a00-c593-11e9-8163-32d38ed19ebe.gif)

Thanks!

**Comment by linguohua** [comment]
@charlesg99 Hi, thanks for your reply. My fedora rawhide is on vmware, use wayland:
![image](https://user-images.githubusercontent.com/3434367/63703374-6dba0f00-c85b-11e9-8d80-33e6e49afc84.png)

![image](https://user-images.githubusercontent.com/3434367/63703069-cccb5400-c85a-11e9-9da0-54f8566d4d72.png)

![image](https://user-images.githubusercontent.com/3434367/63703116-e79dc880-c85a-11e9-8fbf-ccc782f576e2.png)

**Comment by charlesg99** [comment]
Closing this as I've been running 3.34 on bare metal for a couple of days now and the cpu usage is normal on both xorg and wayland. Thanks!
