### ISSUE TITLE
Show window previews on hotkey Problem. (Restart Gnome-shell)

### ISSUE THREAD

**Issue by khpark0203** [home-sweet-gnome/dash-to-panel#701]
I use "Show window previews on hotkey" thanks to you.
But I found one problem.

When I use hotkey **(Multiple previews)** , if I don't want to do anything,  I click ESC.

So, Gnome-Shell is restart.
Is this a problem?
My PC OS is Ubuntu 18.04.

Thank you.

**Comment by charlesg99** [comment]
Hello @khpark0203! Thanks for the report, I could reproduce the issue. It looks like a Mutter bug as the same crash occurs on vanilla Ubuntu 18.04, but I can't reproduce it on newer gnome-shell versions. I think the best would be to report the issue to the Ubuntu folks. 

Here is the error logged when it happens:

`kernel: gnome-shell[11638]: segfault at 0 ip 00007f52a5023190 sp 00007fff77760f18 error 4 in libmutter-2.so.0.0.0[7f52a4f76000+158000]`

And here you can see the crash with <kbd>Super</kbd> + <kbd>9</kbd> then <kbd>Esc</kbd>. Quite entertaining to be honest :)

![Peek 2019-08-13 22-16](https://user-images.githubusercontent.com/33044886/62990092-9d5b2700-be18-11e9-8eec-a76350e4cd49.gif)
