### ISSUE TITLE
Scrolling to switch workspace interferes with scrolling to adjust volume

### ISSUE THREAD

**Issue by chrisjbillington** [home-sweet-gnome/dash-to-panel#702]
I'm running dash to panel from master, and it looks like it has recently gained the feature of being able to switch workspace by scrolling on the panel. I was already using the "top panel workspace scroll" extension for this, but having the feature be part of dash to panel is great because it works with the additional panels that dash to panel creates on other monitors. So that's nice.

However, I'm seeing that if I scroll over the volume indicator on the panel, which would normally change the volume, it switches workspaces *and* changes the volume. Ideally it would not switch workspaces, and would only change the volume.

the "top panel workspace scroll" extension doesn't have this problem, so you might want to look at it deals with it, perhaps their approach can be copied for dash to panel.

**Comment by charlesg99** [comment]
Hi Chris, thank you for the report. A fix to ignore the mouse scroll over the volume indicator was added to master, could you confirm that it works for you as well?

**Comment by chrisjbillington** [comment]
The fix works for me! Thanks very much :)

**Comment by molnarszilard** [comment]
Hi, I am having this problem on Gnome 47 with EndeavourOS on kernel 6.11.6.

**Comment by sophiacspr** [comment]
> Hi, I am having this problem on Gnome 47 with EndeavourOS on kernel 6.11.6.
> 
> Edit: Apparently, it behaves well, but the area of the volume icon is very small, and it is very easy to accidentally scroll on other icons. Sorry for the false claim.
> 
> Edit 2: This problem exists but only in a very specific circumstance: I have a laptop, and when I an external mouse it works well. If I use the touchpad for scrolling on the volume icon, it will scroll both the volume and the workspaces. However, this is only the case when scrolling on the built-in display (scrolling on external monitors seems to work ok). And that's not all, if I close the laptop lid and reopen it, then scrolling with the touchpad will work well in all cases. Maybe this is a problem with Gnome, but I am not sure what is happening.

I am havig the exact same issue. Surprisingly, I can even recreate the part with reopening the lid to make it work again. However, for me there isn't even a small area where it works without also triggering the workspace switch.
