### ISSUE TITLE
Panel stops working and reverts to old bar

### ISSUE THREAD

**Issue by kayfay** [home-sweet-gnome/dash-to-panel#704]
I've noticed that another extension activates based on a triggered event (caffine) and then dash-to-panel becomes disabled and reverts to the old dash.

![Error](https://i.imgur.com/Sss1iyS.png)

**Comment by charlesg99** [comment]
Hello kayfay, once the extension becomes disabled, could you please provide the error shown in the looking glass? To do so, press <kbd>ALT</kbd>-<kbd>F2</kbd> then enter the `lg` command + <kbd>Enter</kbd>. In the looking glass window, on the top right you can select "Extensions", then under dash to panel click on "show errors". Thanks!

**Comment by charlesg99** [comment]
Could you also provide more information on your system? I tried to reproduce the issue on gnome-shell 3.32 with the latest e.g.o. version of caffeine without success. Thanks!

**Comment by piconepaolo** [comment]
> Could you also provide more information on your system? I tried to reproduce the issue on gnome-shell 3.32 with the latest e.g.o. version of caffeine without success. Thanks!

To fix the problem with dash-to-panel i have tried with success <kbd>ALT</kbd>-<kbd>F2</kbd> and then 'r' command + <kbd>Enter</kbd>.

**Comment by charlesg99** [comment]
@kayfay Is this still relevant?

**Comment by kayfay** [comment]
An update to dash to panel broke the extension and so the issue isn't available anymore.
