### ISSUE TITLE
Panel looks weird on newest update

### ISSUE THREAD

**Issue by Heatie** [home-sweet-gnome/dash-to-panel#706]
I was using Google Chrome when I took this screenshot, but the same happens with any other app. This happens whether the app is maximized or not. I already tried to change some settings, but i couldn't find anything that could help me change the appearance of the panel.
This is the first time i use GitHub, so forgive me if i wasn't clear enough 

![Schermata del 2019-08-19 11-32-40](https://user-images.githubusercontent.com/54267514/63255032-1de4b200-c275-11e9-8878-06111dae3295.png)

**Comment by charlesg99** [comment]
Hello Heatie, this looks like the fix we did to accommodate the flat-remix theme (see #633). Is this the shell theme you're using? If so, this is [how it should look like](https://drasite.com/flat-remix-gnome) :) 

Please try changing your Shell theme and let us know if that fixes it. Thanks!

**Comment by Heatie** [comment]
> Hello Heatie, this looks like the fix we did to accommodate the flat-remix theme (see #633). Is this the shell theme you're using? If so, this is [how it should look like](https://drasite.com/flat-remix-gnome) :)
> 
> Please try changing your Shell theme and let us know if that fixes it. Thanks!

Ok now everything works fine, except for a 'small' thing. Basically i can't use my desktop. Im not able to see my folders and file, but if i go to /home/desktop they are all there. I attached a pic that shows what happens if i right-click on my desktop. I can only see three options: change wallpaper, monitor settings and settings. I can't see something like 'create new folder' or anything else.
Anyway, thank you for helping me fixing the problem! Now im going to open a new issue on the flat remix github and see if they can help me

![Schermata del 2019-08-19 15-53-39](https://user-images.githubusercontent.com/54267514/63271133-c0169100-c299-11e9-96d2-3803c33bc347.png)

**Comment by charlesg99** [comment]
Desktop icons aren't enabled by default in Gnome... Some distros (like Ubuntu) do enable them though. You probably need to install another extension like [this one](https://extensions.gnome.org/extension/1465/desktop-icons/) (never used it so I can't vouch for it). Thanks!
