### ISSUE TITLE
Scolling on sound icon also switches workspace

### ISSUE THREAD

**Issue by paulalbertdev** [home-sweet-gnome/dash-to-panel#709]
Hi ! 
I upgraded today the extension to the newer version, via https://extensions.gnome.org , and now scolling on sound icon to turn volume up or down also switches workspace...
That's annoying
BTW : I'm on Ubuntu 19.04

**Comment by charlesg99** [comment]
Please see #707. I'll leave it opened until we release a fix to e.g.o., so it will be easier to spot for the next one :)
