### ISSUE TITLE
Menus and popovers theme

### ISSUE THREAD

**Issue by paulalbertdev** [home-sweet-gnome/dash-to-panel#710]
Hi ! 
Don't know if it is by choice, but since I upgraded to latest https://extensions.gnome.org version, 
menus and popovers are lightgrey (almost white) with darkgrey and blue components instead of being dark with bright components like my gtk theme (and like the panel itself) is, and like they were before the upgrade

**Comment by charlesg99** [comment]
Hi! 
A screenshot would go a long way here... Also the name of the theme you are using. 
The window preview elements in the latest version should have nearly identical colors as the panel, and the boxpointers (clock menu, system menu) should be unchanged. Thanks!

**Comment by paulalbertdev** [comment]
![image](https://user-images.githubusercontent.com/22445690/63533006-33bfd480-c50c-11e9-985d-163c3de090a4.png)
Now menu is like this, before it was dark.
I'm using "yaru" theme from this ppa if I remember well : 
> deb http://ppa.launchpad.net/communitheme/ppa/ubuntu bionic main # désactivé pour la mise à niveau vers disco

**Comment by paulalbertdev** [comment]
![image](https://user-images.githubusercontent.com/22445690/63533331-dbd59d80-c50c-11e9-90cc-5127822f338a.png)
All the menus coming from the panel are like this

**Comment by paulalbertdev** [comment]
Dunno if it's the same code as the one you can find on the ppa repository, but sources seem to be here https://github.com/ubuntu/yaru

**Comment by charlesg99** [comment]
Hello Paul, I really don't see how dash to panel could affect the boxpointers background color. What happens if you only disable dash to panel? does the menus become dark again?

Also, I tried our latest version on Ubuntu 19.04 (which comes with Yaru as the default theme) and the menus are dark. Could you provide a screenshot of your Tweak tools appearance settings? Also, which version of Ubuntu is this? Thanks.

**Comment by paulalbertdev** [comment]
Oh, you're right, there must have been a synchronous update of the theme ! Sorry for the "false alarm"
