### ISSUE TITLE
[GNOME 3.34] 9-dots button is missing

### ISSUE THREAD

**Issue by alex285** [home-sweet-gnome/dash-to-panel#712]
hello! the one issue is what you see in the screenshot; thats on Fedora 31 with GNOME 3.33.90, and I don't get any error message

another thing is that if i disable the extension from GNOME Tweaks then it gets on:

```
/org/gnome/shell/disabled-extensions
```
and so we cant enable it again; i dont have idea why thats happening, probably is an upstream issue, but it is a worth to notice b/c it may drive people nuts!! ..at least that happened to me, and also happened with Dash to Dock!!

![Screenshot from 2019-08-20 19-16-25](https://user-images.githubusercontent.com/11244308/63365023-6e483680-c37f-11e9-8423-c29cdefb7b4d.png)

**Comment by charlesg99** [comment]
Hey Alex, thanks for the report, the showapps button should be back now. I also had funtimes with Tweaks not working correctly... ended up having to use gnome-shell-extension-tool to enable it back. Hopefully that'll be fixed before 3.34!

**Comment by alex285** [comment]
i really dont know what to say!! never ever seen such maintainer anywhere! respond to everyone, fixing everything, listen to all suggestions, discussing, and at the same time doing such great work!! the only i can say is THANK YOU!!!

**Comment by charlesg99** [comment]
Thanks for the kind words :) Don't forget that I'm a dtp user too, if it doesn't work, I can't use it either, so best fixing it lol.
