### ISSUE TITLE
disappears after reboot

### ISSUE THREAD

**Issue by vass30** [home-sweet-gnome/dash-to-panel#713]
Ubuntu 18.04.03 - after reboot the bottom panel(gnome 28 v 21) disappears. Turning extention off and then on helps, the dock again visible.
I tried to turn off all other extentions to prevent exposure, but no effect - the panel doesnt visible after reboot. 

PS  Gnome 28 v 19 works fine.

**Comment by charlesg99** [comment]
Hello vass30, a fix for this problem was added to the master branch, could you please [install it](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github) and see if it stops the panel from disappearing on reboot? Thanks!

**Comment by vass30** [comment]
for the first look, all works good.
i rebooted a few times and had any problem - work very well.
Thank you!

ср, 21 авг. 2019 г. в 15:35, Charles Gagnon <notifications@github.com>:

**Comment by charlesg99** [comment]
Thanks for the feedback! We'll soon release an updated version on e.g.o.!
