### ISSUE TITLE
[Feature Request] Style activities button

### ISSUE THREAD

**Issue by wyqydsyq** [home-sweet-gnome/dash-to-panel#716]
I (and presumably many other users) prefer a compact icon for the "Activities" button instead of the full text button.

In the past I've used an extension called `Activities Configurator` to replace the text with an icon, but that extension is pretty stale in comparison to dash-to-panel and conflicts with this extension (if you have Activities Configurator enabled it overrides any dash-to-panel styling for the panel e.g. gradient, I would like to have both an icon for my Activities button *and* a gradient top bar).

I think dash-to-panel should offer options to:
 - Hide or change `Activities` text
 - Show a custom icon on `Activities` button

There is already similar functionality and UI for customizing the Applications icon, why not let us do the same with Activities?
![image](https://user-images.githubusercontent.com/621277/63486230-fa766d00-c4e9-11e9-9066-2e30c299f220.png)

**Comment by charlesg99** [comment]
Thanks for the suggestion, but let's only keep one opened issue for it. Please contribute further in #400.
