### ISSUE TITLE
[Question] Is there a way to disable workspace switch with panel scroll

### ISSUE THREAD

**Issue by danielyzli** [home-sweet-gnome/dash-to-panel#717]
I have another extension (paperwm with modification - switch windows when scrolling panel) performing an action already when scrolling panel so this causes gnome-shell to panic

Gnome shell version: 3.30.2
Dash to panel version: v21 (latest)
OS: Pop OS 18.10

**Comment by charlesg99** [comment]
Hello Daniel, the option to disable the mouse scrolling already is on the master branch and should soon be released on e.g.o. with v22. Thanks!

**Comment by charlesg99** [comment]
v22 has been released :) Hopefully it'll quickly make its way to e.g.o. Thanks!
