### ISSUE TITLE
do not work if turn on autohide

### ISSUE THREAD

**Issue by PaPerseller** [home-sweet-gnome/dash-to-panel#718]
Ubuntu 19.04 with gnome shell 3.32.1. The extension did not work if I turn on autohide since version 20. Turn off autohide or restart the extension will make the panel appear again. I try to remove dash-to-panel extension completely and then reinstall it. But why my settings still be keeping after I remove all files about dash-to-panel?

**Comment by charlesg99** [comment]
Hello PaPerseller! Yes this issue was reported (#713, #714) and is fixed in v22 (which is [on its way](https://extensions.gnome.org/review/11666) to e.g.o.). 

Hopefully @andyholmes can once again do us a huge favor and review it quickly :)

Thanks!

**Comment by charlesg99** [comment]
@andyholmes Thank you so much!!

**Comment by jderose9** [comment]
Yes thank you!!!!

**Comment by andyholmes** [comment]
:sunglasses:

**Comment by PaPerseller** [comment]
Sorry for not noticing this issue was reported. Thanks very much.
