### ISSUE TITLE
dconf write /org/gnome/shell/extensions/dash-to-panel/multi-monitors "'false'" does not work

### ISSUE THREAD

**Issue by lucasmlousada** [home-sweet-gnome/dash-to-panel#720]
I am able to disable it via tweaks>extensions>dash-to-panel configuration>display panel on all monitors

I am able to then enable it running dconf write /org/gnome/shell/extensions/dash-to-panel/multi-monitors "'true'"

I am running Debian 10 Buster

**Comment by charlesg99** [comment]
Hello @lucasmlousada! The `multi-monitors` setting is a boolean, not a string, so your command is off a bit. Use this instead:
`dconf write /org/gnome/shell/extensions/dash-to-panel/multi-monitors false`

Thanks!

**Comment by lucasmlousada** [comment]
Thanks for the prompt response!

**Wonders why "'true'" works...**

**Comment by charlesg99** [comment]
We would need to dive into glib to get the real answer, but my guess is that reading a setting which has a wrong typed value yields its default value instead (speculation level: HIGH).
