### ISSUE TITLE
mouse scroll to switch workspaces should be controlled by dash-to-panel settings 

### ISSUE THREAD

**Issue by fastrizwaan** [home-sweet-gnome/dash-to-panel#722]
The mouse scrolling to switch workspace on panel is useful, but not everyone is interested in using that feature always. It may cause issues like changing volume using mouse scroll inadvertently causes workspace swicthng. There may be other applications or applets which may require scrolling for their proper working. 

kindly create and enable by default 
Switch Workspace on mouse scroll [X]

so that, those who don't want mouse scrolling to switch workspace can disable the feature.

Thank you.

**Comment by charlesg99** [comment]
Hello fastrizwaan, thank you for the suggestion. What version of Dash to Panel are you using? We introduced some settings to disable the scrolling actions on v22, you might want to update. Also, we should soon release v23 which adds another option to let you switch between windows on panel scroll. Thanks!

**Comment by fastrizwaan** [comment]
Thank you, the option was in "Action" tab, I missed it.

And really I appreciate dash-to-panel, can't live without it. Hugs to you for making it! Thanks a million.
