### ISSUE TITLE
[Feature Request] Width option to create a "dock"

### ISSUE THREAD

**Issue by grissius** [home-sweet-gnome/dash-to-panel#726]
I would like to achieve similar UI as seen on Deepin DE: Have only a dock (that does not span over the whole screen width), with all the items I need: pretty much just clock and status icons.
The problem is I cannot use dash to dock, because it only has app icons.

Is it a possible future feature to add optional width, or just option "do not span over 100% width"?
Thanks

**Comment by AlbinoGeek** [comment]
You can update the title to show `[Feature Request]` and/or someone with write access to this repository should mark this with the correct label. I would also be interested in a similar feature, where the **maximum width of the taskbar could be set to a percentage or pixel value**.

**Comment by grissius** [comment]
Thanks @AlbinoGeek

**Comment by jderose9** [comment]
I think this makes sense to have as an option..

**Comment by cdeebs** [comment]
+1

I recently bought an ultrawide monitor (highly recommend btw!) and while I absolutely love the rest of the menu which just works and looks great, having the option to have a lesser width a'la DeepinDE dock would be a real cherry on top!

Example how it currently looks like (3840x1200)
https://imgur.com/XoRgdzK

Deepin reference example
https://arcolinuxd.com/wp-content/uploads/2019/02/acolinuxb-deepin-menu-small-dock.jpg
https://www.youtube.com/watch?v=yrdaiA1pyqk (fast forward through the clip)
https://www.youtube.com/watch?v=bMUet_SYGMI (fast forward through the clip)

**Comment by charlesg99** [comment]
Hi guys, this could be a good candidate to add to the current positioning work. Setting a fixed size (width or height, depending on the panel's orientation) is easy enough, but I'm not sure how to proceed with the variable icons count present in the taskbar. Having a fixed size would make the icons scroll even if there is still available space on the screen, not sure this is ideal. On the other hand, having a dynamic dock size that expands/shrinks with the icons would only work if all panel elements are monitor centered. Please install the `feature-panel-positions` and let me know if you have ideas on the matter. Thanks!

**Comment by matfantinel** [comment]
@charlesg99 I've been running `feature-panel-positions` branch for a while now. I think that it's perfectly valid that, when in "Dock Mode", all elements are automatically changed to "Monitor Center". The panel seems to behave correctly when set this way, and even when there are too many icons, I believe the current behavior of scrolling is also correct.

Current configuration:
![image](https://user-images.githubusercontent.com/24247035/86166203-ca74fe80-baea-11ea-84f4-0f0313c5940f.png)

Current behavior with many icons:
![Screen record from 2020-06-30 16 06 01](https://user-images.githubusercontent.com/24247035/86166774-b4b40900-baeb-11ea-8da4-6898a8e20517.gif)

I think the only tweak it needs is visual to meet this request. As in instead of the panel background taking over the entire width of the screen, it would dynamically wrap around all contents (perhaps a max-width setting could exist; this is how Dash to Dock does it currently). Preferably with rounded corners, if possible 😆

**Comment by antoniomcr96** [comment]
It is possible. CSS class is `#dashtopanelTaskbar`. Set custom background and border radius. 
From settings set custom panel opacity to 0% (it won't affect the Taskbar). Result:
![image](https://user-images.githubusercontent.com/63928525/86969394-0143b800-c16e-11ea-9e05-41aa1db0e4ab.png)
With IntelliHide it will hide when needed

**Comment by matfantinel** [comment]
@antoniomcr96 AWESOME! I had tried fiddling with CSS before but I had a hard time finding out the correct selectors.

This is how mine looks now:
![image](https://user-images.githubusercontent.com/24247035/86971896-608ed180-c148-11ea-8594-b0e42b31c46c.png)

And the CSS I added to my theme's gnome-shell.css file:
```
#panel .show-apps, #dashtopanelTaskbar {
  background: rgba(0, 0, 0, 0.4);
}

#dashtopanelTaskbar {
  border-radius: 0 20px 20px 0;
  padding-right: 12px;
}

#panel .show-apps {
  border-radius: 20px 0 0 20px;
  padding-left: 12px;
}
```

**Comment by charlesg99** [comment]
That looks great!

**Comment by antoniomcr96** [comment]
Tell me if someone manages to set round corners for preview on hover (I tried different classes with no luck) and for the background of icons on hover

**Comment by charlesg99** [comment]
Those selectors should get you started:

```
.dashtopanelMainPanel .show-apps:hover .overview-icon,
#dashtopanelScrollview .app-well-app:hover .dtp-container,
#dashtopanelScrollview .app-well-app:focus .dtp-container,
#preview-menu, 
.preview-header-box,
.preview-container,
.preview-close-btn-container { 
	border-radius: 20px; 
}
```

Thanks!

**Comment by matfantinel** [comment]
@charlesg99 I don't mean to bother, but do you also know the selector for the highlight on selected app?

![image](https://user-images.githubusercontent.com/24247035/87040890-c1112380-c1c7-11ea-85df-28e5c5dcebde.png)

Making it also rounded would give the dock an even better look, as it looks weird when the selected app is in one of the edges. (I added a large padding just for it not to overlap)

**Comment by charlesg99** [comment]
Try `.dtp-container > StWidget`

**Comment by matfantinel** [comment]
Looks absolutely perfect now! Thanks a lot for the help, and for the extension :)

**Comment by antoniomcr96** [comment]
Thanks, it work :100:  ! Not to bother, I tried: `.dashtopanelMainPanel .show-apps .overview-icon {margin: 0; padding: 0}` and `.dashtopanelMainPanel .show-apps {margin: 0; padding: 0}` but it didn't work.
How to make ".show-apps" icon background look similar to application background on hover?
![image](https://user-images.githubusercontent.com/63928525/87093554-a8435500-c23d-11ea-9873-196188ee45cc.png)
I was unable to remove the icon's background margins on hover.
Thanks a lot for all your work!

**Comment by jderose9** [comment]
This has been implemented.

**Comment by samuelrawrs** [comment]
Just wanted to add in case anyone's looking at this and needed a tldr:

simply copy this to the end of your 
`~/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/stylesheet.css`

```
#panel .show-apps, #dashtopanelTaskbar {
  background: rgba(0, 0, 0, 0.5); /* semi-transparent black background */
  border-radius: 10px 10px 10px 10px; /* rounded corners for all four corners */
}

#dashtopanelScrollview .app-well-app .dtp-container > StWidget, /* Base state */
.dashtopanelMainPanel .show-apps .overview-icon { 
  border-radius: 10px; 
}

.dashtopanelMainPanel .show-apps:hover .overview-icon,
#dashtopanelScrollview .app-well-app:hover .dtp-container > StWidget,
#dashtopanelScrollview .app-well-app:focus .dtp-container > StWidget,
#preview-menu, 
.preview-header-box,
.preview-container,
.preview-close-btn-container { 
  border-radius: 10px; /* Keeps the rounded corners on hover/focus */
}
