### ISSUE TITLE
[Feature Request] Allow active applications and favorites to hide, but but not completely. Leave just enough of the bar to show background/taskbar app icons/notifications

### ISSUE THREAD

**Issue by MostHated** [home-sweet-gnome/dash-to-panel#730]
Hey there,
   Amazing job on this panel. It is exactly what I have been hoping to one day have for a long time. The request I have is this, I like to keep my applications menu in the center, and now that I can have the applications on the same bar as the background applications and power menu and all that, it is even better. I do like to have my applications menu hide though, just to save screen real-estate, but at the same time, I don't want to have to do that at the expense of not seeing notifications from my other running background apps. 

If it could be possible to be able to have and use the hiding functionality to perhaps shrink the overall panel, just not completely. Say, make it half size or something, just enough to show the notifications and whatnot, then when you push the mouse against the applications area, it grows again full size so you can click on your active applications, if that makes sense?

Thanks again for all the work you have put into this!
-MH

**Comment by charlesg99** [comment]
Hello MostHated, sounds like a good idea, but could you please elaborate on "notifications from my other running background apps". What does it look like on the taskbar? Thanks!

**Comment by MostHated** [comment]
No problem, here is an example:  

![](https://i.imgur.com/75s3CPT.png)

Nearly all of the icons on the right side of the bar there indicate a notification in some way, be it color change, or displaying a number, etc. So it would be nice if when the taskbar is not in focus that instead of disappearing completely, perhaps it could shrink down to like, 24 or so, so that those icons are still visible or whatever ends up working out best. Then when I want to use the ones in the middle of the image and I push my mouse into them as if you were unhiding it, the middle icons could grow to the normal size, 48 or whatever the default is.

Thanks!
-MH
