### ISSUE TITLE
"Show Application" hovering mouse-over background texture doesn't match the style

### ISSUE THREAD

**Issue by dogmax** [home-sweet-gnome/dash-to-panel#731]
The background texture, when hovering the "Show Applications"-icon, is not the same as the other icons. (Style is set to "Metro" in the picture).

Picture: https://i.imgur.com/Z1LzcxL.png

**Comment by charlesg99** [comment]
Hello dogmax, we are using the installed theme style for the "Show applications" icon, which should be the same as the default GNOME Shell Dash found in the overview. I don't think we should override this icon, as its purpose is different from the application icons. Thanks!

**Comment by dogmax** [comment]
Hello charlesg99 and thanks for answering, but you have misunderstood what I meant. 

I am not talking about the icon itself. I am talking about the background that appears *behind* the icon when the cursor is hovering the icon. 

On the "Show Applications"-icon, the *background* is a grey square with rounded corners. 

Everywhere else the background has unrounded corners.

**Comment by charlesg99** [comment]
Hello, the Show Applications icon now has the same hover effect as the other icons on the master branch. thanks!
