### ISSUE TITLE
How am I able to see my application names like the intellihide shown in screenshot?

### ISSUE THREAD

**Issue by rushercrack** [home-sweet-gnome/dash-to-panel#734]
Hey, I've been looking quite a while for this option, but apparently, it's already a feature in the extension.
As shown here, the application title is directly shown in the panel: https://raw.githubusercontent.com/home-sweet-gnome/dash-to-panel/master/media/design/gif/Intellihide.gif

I'm looking to find a way to enable this, as I failed to do so.
I can't find any options in the extension settings related to this.

Thank you so much.

**Comment by charlesg99** [comment]
Hello, you can see the window titles by enabling the "Ungroup applications" option under the "Behavior" tab of the settings. Thanks!
