### ISSUE TITLE
[Feature request] straight top bar option

### ISSUE THREAD

**Issue by fthx** [home-sweet-gnome/dash-to-panel#736]
Hi Charles,

Could it be possible to add an option to make the topbar straight ? Some incompatibility with another straight topbar extension has appeared...

Ubuntu 19.10, GS 3.34

**Comment by charlesg99** [comment]
Hello fthx, could you please elaborate on what "make the topbar straight" means? Are you talking about the top panel's rounded corners present with the default theme? Also what is the incompatibility you're referring to? Thanks!

**Comment by fthx** [comment]
[NB referring to "hot corner hard to activate" bug : I'm back to DtP 23 from Ubuntu/Debian repos, I can definitely notice it's harder to activate the hot corner than in a native GS ; I do not use any intellihide of the panel.]

Yes, it's about the rounded corners (that do not fit with Thunderbird or Firefox no-title-bar mode, e.g.).

Well, the incompatibility now. History (still Ubuntu 19.10 beta, GS 3.34, Wayland) : 
I was running as usual (without any GS crash, absolutely NO crash) the GNOME session of Ubuntu, with extensions Places (official), Workspaces Indicator (official), Horizontal Workspaces (official) and Straight Top Bar (https://extensions.gnome.org/extension/1265/straight-top-bar/), Transparent Top Bar (https://extensions.gnome.org/extension/1266/transparent-top-bar/).
When I activated DtP, GS became unstable. It crashed and some extensions (including Places and Straight TB) were blacklisted in GS's dconf. It's not the first time I notice DtP crashes GS with my extensions setup. At the moment I do run DtP 23 along with all my extensions but Straight and Transparent, and all seems fine. So -> feature request to have no rounded corners ! :-)

[NB 2 : Maybe you can highlight in DtP description that the combination of DtP and (new) Horizontal Workspaces + Workspaces Indicator (official GS extensions) allows to get a full classical but modern GS layout ?]

**Comment by charlesg99** [comment]
> NB referring to "hot corner hard to activate" bug : I'm back to DtP 23 from Ubuntu/Debian repos, I can definitely notice it's harder to activate the hot corner than in a native GS

Makes sense as the hot corner bug is currently fixed on the `vertical-panel` branch, not v23. Please feel free to try out that branch to help us testing it :)

> It's not the first time I notice DtP crashes GS with my extensions setup

I've looked at the straight-top-bar and transparent-top-bar extension sources and I really don't see how either could conflict with dash to panel (much less how this could crash g-s). Those 2 only remove css classes when enabled and set them back when disabled. If you experience gnome-shell crashes, there definitely is a log entry that will point to its cause, so I think you should try to reproduce the crash and then check at your logs so we can work on the problem (if it is indeed coming from dash to panel).

From what I can see, there is no need for a dedicated option to remove the panel corners, so I'll close this for now. Thanks!

**Comment by fthx** [comment]
Ok but I've already tested the vertical-panel branch here : 
https://github.com/home-sweet-gnome/dash-to-panel/issues/610
Maybe only this experimental version does conflict with some of my extensions. Here Straight Top Bar seems to work ok with v. 23. I'll give another try !

**Comment by fthx** [comment]
Ok, there is definitely a bug running these two extensions : DtP and Straight Top Bar.
I believed at first it was only with vertical-branch DtP, but v. 23 sees that too.
Way to reproduce in Ubuntu : 
- install v. 23 from repository
- install straightTB from gnome extensions website
- logout/login

=> : 
![image](https://user-images.githubusercontent.com/23138504/65376455-59bdcd80-dca0-11e9-9aef-c556e2688020.png)

Running StraightTB along with vertical-branch never makes the TB straight. It is straight running v. 23.

**Comment by fthx** [comment]
Ooooook, sorry for flooding. I *think* that there are two issues : 
- DtP (v. 23 or vertical-branch) causes *sometimes* GS (3.34, Ubuntu) to hang ;
- DtP vertical-branch is not compatible with Straight TB (very 1st proof is that the top bar never becomes straight here).

**Comment by charlesg99** [comment]
> DtP (v. 23 or vertical-branch) causes sometimes GS (3.34, Ubuntu) to hang

Comme je disais plus tôt, c'est clair que si il y a un "hang", il va y avoir un log nous disant ce qui l'a causé. Pourrais-tu stp regarder dans tes logs de gnome-shell (/usr/bin/gnome-shell) pour voir si tu y vois des erreurs relatives à dash to panel? Pour l'instant disons que ce que tu rapportes est assez vague :)

> DtP vertical-branch is not compatible with Straight TB

Oui en effet, sur cette branche nous n'utilisons/modifions plus le panel par défaut de gnome-shell sur le moniteur principal, nous utiliserons désormais l'un de nos panels custom (comme ceux présents sur les moniteurs secondaires). Puisque l'extension straight top bar n'agit que sur le panel par défaut de gnome-shell, ça fait en sorte que les "corners" ne sont plus enlevés (ils ne l'ont jamais été sur les moniteurs secondaires). Honnêtement l'idéal serait que cette extension soit adaptée à nos panels pour pouvoir correctement en retirer les corners.

Merci!

**Comment by fthx** [comment]
Oui bien sûr j'ai regardé les logs mais rien de convaincant à part ce que j'ai posté en screenshot plus haut. En tout cas, rien ne mentionnant DtP.

**Comment by fthx** [comment]
Juste avec DtP vertical-branch activé, puis logout/login, résultat les extensions sont désactivées.

```
22:31:20 gnome-shell: Set a breakpoint on '_pixman_log_error' to debug
22:31:20 gnome-shell: In pixman_region32_init_rect: Invalid rectangle passed
22:31:20 gnome-shell: *** BUG ***
22:31:20 gnome-shell: Set a breakpoint on '_pixman_log_error' to debug
22:31:20 gnome-shell: In pixman_region32_init_rect: Invalid rectangle passed
22:31:20 gnome-shell: *** BUG ***
22:31:20 gnome-shell: libinput error: client bug: timer event4 tap: offset negative (-11ms)
22:31:15 gnome-shell: Set a breakpoint on '_pixman_log_error' to debug
22:31:15 gnome-shell: In pixman_region32_init_rect: Invalid rectangle passed
22:31:15 gnome-shell: *** BUG ***
22:31:15 gnome-shell: Set a breakpoint on '_pixman_log_error' to debug
22:31:15 gnome-shell: In pixman_region32_init_rect: Invalid rectangle passed
22:31:15 gnome-shell: *** BUG ***
22:31:05 dbus-daemon: [session uid=1000 pid=16530] Activating service name='org.gnome.Logs' requested by ':1.20' (uid=1000 pid=16874 comm="/usr/bin/gnome-shell " label="unconfined")
22:31:01 gnome-shell: Connection to xwayland lost
22:31:01 gnome-shell: Connection to xwayland lost
22:31:01 gnome-shell: Registering session with GDM
22:31:01 gnome-shell: GNOME Shell started at Sat Sep 21 2019 22:30:59 GMT+0200 (CEST)
22:31:00 gnome-shell: Failed to CRTC gamma: drmModeCrtcSetGamma on CRTC 48 failed: Permission non accordée
22:31:00 gnome-shell: Failed to CRTC gamma: drmModeCrtcSetGamma on CRTC 48 failed: Permission non accordée
22:31:00 gnome-session-b: DEBUG(+): GsmXSMPClient: Client '0x55f067f0fa80 [gnome-shell 10b481e636b2737fa7156909785960225400000168570069]' received SaveYourselfPhase2Request
22:30:59 gnome-shell: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
22:30:59 dbus-daemon: [session uid=1000 pid=16530] Activating via systemd: service name='org.gnome.evolution.dataserver.Calendar8' unit='evolution-calendar-factory.service' requested by ':1.59' (uid=1000 pid=17124 comm="/usr/lib/gnome-shell/gnome-shell-calendar-server " label="unconfined")
22:30:59 gnome-shell: Extension dash-to-panel@jderose9.github.com already installed in /home/ft/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com. /usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com will not be loaded
22:30:59 gnome-session-b: DEBUG(+): GsmXSMPClient:   Program = 'gnome-shell'
22:30:59 gnome-shell: Telepathy is not available, chat integration will be disabled.
22:30:59 polkitd: Registered Authentication Agent for unix-session:19 (system bus name :1.5644 [/usr/bin/gnome-shell], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale fr_FR.UTF-8)
22:30:59 dbus-daemon: [session uid=1000 pid=16530] Activating via systemd: service name='org.gnome.evolution.dataserver.Sources5' unit='evolution-source-registry.service' requested by ':1.59' (uid=1000 pid=17124 comm="/usr/lib/gnome-shell/gnome-shell-calendar-server " label="unconfined")
22:30:59 gnome-shell: Will monitor session 19
```

**Comment by fthx** [comment]
Après un nouveau logout/login, pas de bug... Oups. Alors je redémarre et zou, re-bug : 
![image](https://user-images.githubusercontent.com/23138504/65379007-89c99880-dcc1-11e9-9e30-850e401d3d42.png)
