### ISSUE TITLE
Scrolling over workspace indicator extension switches workspace twice

### ISSUE THREAD

**Issue by shastry** [home-sweet-gnome/dash-to-panel#737]
Using [ Workspace Indicator](https://extensions.gnome.org/extension/21/workspace-indicator/) with dash to panel.

Scrolling over the workspace indicator switches two workspaces instead of one.

May be an exception can to be added to not scroll over the workspace indicator, so that it can do its thing?

**Comment by charlesg99** [comment]
Hello shastry, thanks for the suggestion! Scrolling over the workspace indicator should now be ignored on branch `vertical-panel`. Please install it by following these [instructions](https://github.com/home-sweet-gnome/dash-to-panel/issues/3#issuecomment-529162697).

**Comment by shastry** [comment]
Works. Thank you!

**Comment by charlesg99** [comment]
Great! Closing as this fix is now on master, thanks!
