### ISSUE TITLE
dash-to-panel disabled in gnome tweaks after update

### ISSUE THREAD

**Issue by MushroomHunting** [home-sweet-gnome/dash-to-panel#740]
Hi,

I recently updated my arch linux (antergos) after a reasonably long while and it seems like dash-to-panel has completely stopped working. It's showing up in Tweaks but has an "!" next to it and the option to turn it on is greyed out with a hover over message of "Error loading extension".

I'm guessing there is some issue with the new gnome because as a separate issue the lock screen is broken requiring a tty login to fix everything.

>> gnome-shell --version
GNOME Shell 3.34.0

any advice would be appreciated!
cheers

**Comment by charlesg99** [comment]
Hello @MushroomHunting, could you please provide the dash to panel version you're using and the error shown in the looking glass? To do so, press <kbd>ALT</kbd>+<kbd>F2</kbd> then enter the "lg" command then <kbd>Enter</kbd>. In the looking glass window, on the top right you can select "Extensions", then under dash to panel click on "show errors". Thanks!

**Comment by MushroomHunting** [comment]
Hi Charles!
thanks for the reply

the error says 
>TypeError: ExtensionSystem.connect is not a function

**Comment by charlesg99** [comment]
Hello, this was resolved a while ago and released with v21... Seems like you're using an older version of dash to panel so please update the extension to resolve the issue. To do so, the easiest is to click on the green arrow next to the on/off switch, here: https://extensions.gnome.org/local/

Thanks!

**Comment by MushroomHunting** [comment]
Hi,
thanks so much; it's working now!

I actually couldn't uninstall it from extensions straight away (no option to uninstall).

Had to go into /usr/share/gnome-shell/extensions (~/.local/share/gnome.... for local installation)
rm -r dash-to-panel....
Alt-F2 then r to restart

then I was able to install it again and it's working again:D
cheers
