### ISSUE TITLE
Favorites/Running Apps Disappears

### ISSUE THREAD

**Issue by tysenmoore-xse** [home-sweet-gnome/dash-to-panel#742]
Running Debian 10 the screen saver kicks in. When I exit the screen saver and enter the desktop the Favorites/Running app icons are no longer shown.  The Dash icon is still shown and many of the other settings are working (Move clock, etc).  It appears to only affect the Favorites/Running apps.  The only way for me to correct the problem is to open the settings and disable/enable showing Favorites/Running apps.

**Comment by charlesg99** [comment]
Hello tysenmoore-xse! Does the same happen if you disable your other extensions and then restart gnome-shell? What version of Dash to Panel are you using? You could also have a look at your logs for related errors. To do so, run `journalctl /usr/bin/gnome-shell -f -o cat` and then reproduce the issue. Thanks!

**Comment by tysenmoore-xse** [comment]
Thanks so much for the quick response.  Also, thanks so much for the suggestion, I should have tried that first.  I removed all other extensions and the problem went away--must be a conflict.  I apologize for any inconvenience.
