### ISSUE TITLE
Slow panel reveal when closing fullscreen window from overview

### ISSUE THREAD

**Issue by xou816** [home-sweet-gnome/dash-to-panel#744]
Extension version: 23
Gnome Shell version: 3.34.0

Intellihide activated, set to dodge windows (not reproduced when not dodging windows)

How to reproduce:
- open a full screen window (panel should be hidden)
- bring up activities overview (using super)
- close the fullscreen window
- exit overview
- attempt to show panel by mousing hover screen edge (not sure if needed)

Result: panel starts appearing, but does so extremely slowly.
Expected: panel appears at normal speed.

Thank you very much for such a great extension!

**Comment by charlesg99** [comment]
Hello Alexandre, thank you for the detailed report! I could reproduce the issue and it should now be fixed on the master branch! Thanks!

**Comment by xou816** [comment]
Thank you for the quick fix! I'll try this asap :)

**Comment by xou816** [comment]
Could not reproduce on master, panel shows up as soon as opening the overview. Thanks again ! :)
