### ISSUE TITLE
[Feature request] Isolate workspaces

### ISSUE THREAD

**Issue by franciscojmarin** [home-sweet-gnome/dash-to-panel#746]
I've been using Dash to panel for like a year now, but recently I've started using workspaces too and I feel like I'm missing something. It would be usefull to isolate workspaces, by that I mean you can only see active windows/applications in each workspace. I open Firefox in workspace 1, switch to workspace 2 and I see no applications running nor windows on the dash.

I've found some alternatives to achieve that (you can ask me if you're interested but I will not promote other extensions here), but that alternatives lack the customization you can achieve with Dash to Panel. It would be usefull to have that feature here so we can have it all, customization and utility.

**Comment by mweirauch** [comment]
The feature is right there in the "Behaviour" tab. Penultimate setting on my git-based master installation. If you can't spot it, please provide the version of the DtP extension you are using.

**Comment by franciscojmarin** [comment]
Omg it is there indeed, was searching in other language, I'm sorry. Can you delete this 'issue' since I'm not finding the option to do it myself. This won't help anybody so I think deleting this is the best option.

Thank you very much.
