### ISSUE TITLE
No signal 'in-fullscreen-changed' on object 'MetaDisplay'

### ISSUE THREAD

**Issue by korelstar** [home-sweet-gnome/dash-to-panel#747]
On Gnome 3.22.2 (Debian 9), the following error appears now when using current `master`:

```
JS LOG: Extension "dash-to-panel@jderose9.github.com" had error: Error: No signal 'in-fullscreen-changed' on object 'MetaDisplay'
```

The extension is not loaded anymore!

Edit:
The issue was introduced with https://github.com/home-sweet-gnome/dash-to-panel/commit/c55230de98d424028ad6f92f06597ca2dd211e07

**Comment by charlesg99** [comment]
Hello korelstar! Yes, seems like this signal was emitted by `screen` on gnome-shell < 3.30. Sorry about that, this should now be fixed on master. Thanks!

**Comment by korelstar** [comment]
Great, thanks! :tada:
