### ISSUE TITLE
[Feature Request] Always hidden panel

### ISSUE THREAD

**Issue by lungtendo** [home-sweet-gnome/dash-to-panel#749]
Hello dev, this is a great plugin and I love using it. It keeps my desktop clean and out of the way.

Recently I've been trying to maintain a distraction-free desktop and I've almost achieved it except for one thing. It would be awesome if there is an option to keep the panel always hidden and show only on SUPER+i or on SUPER (Overview).

Thanks a ton.

**Comment by charlesg99** [comment]
Hello, did you try the intellihide settings? Sounds like that's what you're looking for.

**Comment by lungtendo** [comment]
> Hello, did you try the intellihide settings? Sounds like that's what you're looking for.

@charlesg99 Yes, I am using intellihide. What I would like to have is an option where panel doesn't show up on mouse-over (or whatever it is called). I want the panel to be visible only on dash overview (super key) or through the super+i option which is already available. So, I don't want mouse to trigger the dash as in the intellihide mode. Hope I am clear. Thanks.

**Comment by charlesg99** [comment]
The "required pressure threshold" maximum was raised on the master branch, so setting it all the way up (9990) should give you what you want. For it to take effect, you'll have to set the pressure value, disable intellihide, then enable it back. Thanks!

**Comment by lungtendo** [comment]
@charlesg99 The "required pressure threshold" did the trick, although I can set the value to 1000 max it works. Awesome. Thank you.

Now, there is one more thing bothering me and you could call it nitpicking at this point but may be there is some setting I can turn on or off for this: upon login the panel shows momentarily and hides. Is it possible to make it not show at all upon login?

**Comment by charlesg99** [comment]
Hello, an option to control the delay before hiding the panel on login was added to the master branch. Please [install it](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github) to try it out. Thanks!

**Comment by lungtendo** [comment]
> Hello, an option to control the delay before hiding the panel on login was added to the master branch. Please [install it](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github) to try it out. Thanks!

Thank you so much. It is working. Everything is perfect now.
