### ISSUE TITLE
Provide padding option for app icons

### ISSUE THREAD

**Issue by kelunik** [home-sweet-gnome/dash-to-panel#75]
The padding looks quite fine for the default 48px sized icons, but if I shrink them down to 32px, it doesn't look that good. Would be cool to have a way to customize the padding to be the same as for 48px sized icons.

**Comment by jderose9** [comment]
There's a setting called App Icon Margin which controls this, if I understand properly.

**Comment by kelunik** [comment]
Ah, sorry, yes, that controls the horizontal margin, but I want to customize the vertical padding / margin.

**Comment by jderose9** [comment]
Ah, yeah. The way it works right now is kind of quirky. Basically you can set the panel height larger and it will add more padding until a larger fixed icon size can fit. So you might be able to get a handful of pixels worth of padding if you increase the panel height a little. So for instance 24px and 28px panel heights have the same size icons but at 28 there is more padding. This is basically the logic inherited from the gnome dash.

It would be nice to allow this to be set more explicitly.

**Comment by Minkiu** [comment]
I would love to see this as well, I would like to give it a go and try a commit on this, so reading the other issue about dev, the dev cycle would be:
1. Clone repo
2. Install
3. make changes
4. Whenever I make a code change, I run "make install" to deploy it and then restart gnome shell (Alt F2 -> "r")

Am i right?  

Should I unisntall it first from the Extensions website/Tweak tool?

Thanks!

**Comment by micheleg** [comment]
No need to uninstall the extension first. I can suggest the use of this extension https://extensions.gnome.org/extension/1137/gnome-shell-extension-reloader/  to avoid having to restart the shell completely all the times (also very useful in Wayland where a restart is not possible)

**Comment by jderose9** [comment]
@micheleg Have you figured out a way to attach a debugger?

**Comment by micheleg** [comment]
Nope. I don't even know if it would be feasible as the extension runs in the same thread of the shell and therefore it would block the execution of the window manager. I survive with the logging (global.log) and I inspect the status through looking glass (sometimes I add references to my objects to Main to be able to access the more easily)

**Comment by jderose9** [comment]
@micheleg Thanks very much for the response! I saw this:
https://wiki.gnome.org/Projects/GnomeShell/DebuggingJavaScript

But it looks like you need a 2nd machine to remotely connect to with a separate version of the shell compiled with a server component built into it, and that hasn't been maintained for quite some time. So I was figuring it wasn't even worth the effort of trying to get it working.

**Comment by micheleg** [comment]
Just read this (https://ptomato.wordpress.com/2017/04/28/gjs-whats-next/) today, with some hints for a future GJS debugger implementation.

**Comment by jderose9** [comment]
@micheleg wow, that's awesome! I hope that comes to fruition.Thanks for the link.

**Comment by ilkerhk** [comment]
For the ones who are looking for a temporary workaround :  
I think line 636 in taskbar.js is setting the icon size to the largest possible after subtracting a vertical padding. I tried to change it to: 
        let availSize = Main.panel.actor.get_height() + 4 * scaleFactor  ;

Now the icons are now full without any margins on the top and bottom when I set panel size to 29 or 30, which is what I wanted.  Off course, it would be great if this was adjustable in the settings.

 Thanks all the developers for this nice extension. Keep up with the great work...

**Comment by tranhl** [comment]
As an alternative to @ilkerhk 's workaround, you can simply modify the extension's `stylesheet.css` by adjusting the padding of the following ruleset:

```
#dashtopanelScrollview .app-well-app .overview-icon {
	border-radius: 0;
	padding: 8px; /* Modify this according to preference */
	border: none;
}
```

After you're done modifying the ruleset, restart Gnome and you should be good to go.

For example, this is what I'm currently using:

```
#dashtopanelScrollview .app-well-app .overview-icon {
	border-radius: 0;
	padding: 12px;
	border: none;
}
```

**Comment by charlesg99** [comment]
A new setting to fine tune the icons padding was added on branch "appicons-padding". If anybody could try it to help with the tests, that would be great. Thanks!

**Comment by charlesg99** [comment]
The new setting has been merged to master. Thanks!
