### ISSUE TITLE
Option to change Activities text to an emoji.   Feature is coded and tested.

### ISSUE THREAD

**Issue by nls1729** [home-sweet-gnome/dash-to-panel#751]
A user of my extension, Activities Configurator, wanted to use my extension with Dash to Panel to remove the Activities button text and add an icon to use less space.  My extension does not play well with Dash to Panel.  I added an option to Dash to Panel to change the Activities text to an emoji. Please see the following link: 

https://nls1729.github.io/dash_happy/dash_happy.html

If you think the feature would be  useful for your users I will fork and issue a pull request.

Thanks for you consideration.
Norman

**Comment by charlesg99** [comment]
Hello Norman, that looks cool so far! Of course a merge request would be appreciated, we can go on from there if you want. I think it would be nice to have uniform "Show Applications" and "Show Activities" icon options. Thanks!
