### ISSUE TITLE
Icons disappear after horizontal scroll on icons

### ISSUE THREAD

**Issue by leebickmtu** [home-sweet-gnome/dash-to-panel#752]
These are the mouse scroll wheel behaviors I am observing. The 4th one is the error case.

1. When vertical or horizontal scrolling with mouse on an empty section of the dash, workspaces are switched.
2. When vertical scrolling with mouse over non-running application icon, nothing happens.
3. When vertical scrolling with mouse over running application icon, focus is switched between windows of that application.
4. When horizontal scrolling with mouse over running or non-running application icon, all the application icons disappear.

In that 4th case, the only way I could get the icons back was to disable/re-enable the extension.

I am running v23 (981ffc17612696046fb5cba95d2ae97d0868f60d). Confirmed this with 2 different mice just in case one had an odd horizontal scroll event.

**Comment by leebickmtu** [comment]
After triggering this behavior, the whole Gnome shell becomes very laggy as well.

**Comment by leebickmtu** [comment]
Just to be sure & thorough I pulled newest (7fd7a1f06354b47cb73ec4c6c76bc9acce957a92) and confirmed the bug is present there as well.

**Comment by leebickmtu** [comment]
Looks a little similar to #528, except I'm doing the horizontal scroll on the dash icons instead of the window preview. I can't replicate #528 but seemed similar in the way it manifests (blank window preview for him, blank icon section for me).

And since it came up in that issue, when I say horizontal scroll I mean a mouse that has a tilting scroll wheel for left/right scroll.

**Comment by charlesg99** [comment]
Hello Korbin, thank you for the report. I can't reproduce this on g-s 3.34 or 3.32 with the latest master (xorg or wayland). When I plug in a mouse having side scrolling buttons, I can scroll text and web pages just fine, but can't reproduce either this issue or #528. Did you configure your mouse in any way? What gnome-shell version are you on? Could you share your dtp settings? Thanks!

**Comment by leebickmtu** [comment]
Gnome 3.34.0
No custom mouse settings
Only occurs on wayland session (xorg is fine)

[dtp-settings.txt](https://github.com/home-sweet-gnome/dash-to-panel/files/3684403/dtp-settings.txt)

**Comment by leebickmtu** [comment]
Tried resetting all DtP settings with
`dconf reset -f /org/gnome/shell/extensions/dash-to-panel/`

Still get the bug, so doesn't seem linked any settings I had changed.

**Comment by charlesg99** [comment]
Thanks to leebickmtu!
