### ISSUE TITLE
DtP re-enables a disabled activities hot corner again

### ISSUE THREAD

**Issue by dmoebius** [home-sweet-gnome/dash-to-panel#753]
Gnome 3.34 with most recent version of DtP installed via extensions.gnome.org

The Tweak tool > Top Bar has the option to disable the "Activities Overview Hot Corner". If you disable it while DtP is enabled, it will work as expected, but as soon as you restart the shell or lock/unlock the screen, or disable and re-enable DtP the Hot Corner will be enabled again (even if the option is still disabled in the Tweak tool).

This is exactly the same issue as #407, which has been closed 1½ years ago. But it seems that this issue has re-appeared.

See also this SO discussion, where other users have the same problem:
https://askubuntu.com/questions/1033739/activities-corner-keeps-re-enabling-itself/1149223

**Comment by charlesg99** [comment]
Hello dmoebius, thank you for bringing this up. This is indeed a [newly introduced](https://github.com/GNOME/gnome-shell/commit/dbb71f0dfcb9a92e3988b98aea5bf106edd61bec) setting for gnome-shell 3.34. #407 was relative to a setting specific to Ubuntu, so the outcome is the same but they're in fact distinct issues. 

A check to respect the new gnome-shell setting on 3.34 was added to the master branch, please install it to confirm that it solves the issue on your system. Thanks!

**Comment by dmoebius** [comment]
Sorry for the delay.
I tested with recent `master`; it works. 
Thanks for fixing this so fast! :)
