### ISSUE TITLE
Menu misplacement when rightclicking an application

### ISSUE THREAD

**Issue by axelrindle** [home-sweet-gnome/dash-to-panel#754]
When I have an application opened and rightclick on it's icon in the panel, the menu gets stuck at the top left corner on the screen and can only be removed by disabling the extension. See the screenshot below.

![Bildschirmfoto von 2019-10-02 21-23-05](https://user-images.githubusercontent.com/7105632/66075613-4cd09200-e55c-11e9-9cc8-b2c6f1641369.png)

Some version information:

```
$ uname -a
Linux devpc 5.0.0-29-generic #31~18.04.1-Ubuntu SMP Thu Sep 12 18:29:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
```
Dash-to-Panel
Version: 23
```

**Comment by charlesg99** [comment]
Hello axelrindle, I've never seen this issue on Ubuntu 18.04. What theme is this? Is it a X.org or a Wayland session? Could you try disabling all of your extensions aside from dash to panel, restart gnome-shell and see if the issue persists? If it does, please run `journalctl /usr/bin/gnome-shell -f -o cat`, reproduce the error and check if you can see relevant errors in the log. Thanks!

**Comment by axelrindle** [comment]
@charlesg99 I will try your suggestion and report back.

- The theme is called **Ant-Dracula** ([found here](https://www.gnome-look.org/p/1099856/))
- I'm using a **X.org** session.

**Comment by axelrindle** [comment]
@charlesg99 Restarting the gnome-shell did not fix the issue, the following error occured:

```
JS ERROR: TypeError: menuItem.actor is undefined
taskbarSecondaryMenu<._redisplay@/home/axel/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:1338:25
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
popup@resource:///org/gnome/shell/ui/appDisplay.js:1975:9
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
taskbarAppIcon<.popupMenu@/home/axel/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:554:9
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_onButtonPress@resource:///org/gnome/shell/ui/appDisplay.js:1702:13
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
```

**Comment by charlesg99** [comment]
Seems like there is an unexpected item in the secondary menu, not sure yet where that comes from.

Did you disable your other extensions before restarting gnome-shell? Could you share your settings (from the "About" tab in the settings)? Do you have the "Application Menu" enabled in the Tweaks tool ("Top Bar" section)? Does the issue happen with every icon?

Thanks!

**Comment by axelrindle** [comment]
### Did you disable your other extensions before restarting gnome-shell?
Yes. Just tried it again and with no other extension enabled, it seems like the problem does not occur. If it helps, here a list of all my enabled extensions:

```
$ gsettings get org.gnome.shell enabled-extensions | sed "s/'/\"/g" | jq 'sort'
[
  "arc-menu@linxgem33.com",
  "caffeine@patapon.info",
  "clipboard-indicator@tudmotu.com",
  "dash-to-panel@jderose9.github.com",
  "extensions-sync@elhan.io",
  "gnome-shell-screenshot@ttll.de",
  "gravatar@jr.rlabs.io",
  "noannoyance@sindex.com",
  "openweather-extension@jenslody.de",
  "user-theme@gnome-shell-extensions.gcampax.github.com"
]
```

### Could you share your settings (from the "About" tab in the settings)?
```
[/]
shift-click-action='MINIMIZE'
shift-middle-click-action='LAUNCH'
show-show-apps-button=false
hotkeys-overlay-combo='TEMPORARILY'
show-activities-button=false
dot-style-unfocused='DASHES'
middle-click-action='LAUNCH'
show-appmenu=false
```

### Do you have the "Application Menu" enabled in the Tweaks tool ("Top Bar" section)?
Yes.

### Does the issue happen with every icon?
No, mostly just with one icon. But it seems to be random with which one.

**Comment by charlesg99** [comment]
Ok sounds like an incompatibility with one of your other extensions. That would be helpful if you could re-enable them one at a time and try to reproduce the issue after each one (restart gnome-shell each time to be sure), that way you could pinpoint which one is causing it (and fix it). It's got to be one of those, as I'm using the other ones:

```
  "caffeine@patapon.info",
  "clipboard-indicator@tudmotu.com",
  "extensions-sync@elhan.io",
  "gnome-shell-screenshot@ttll.de",
  "gravatar@jr.rlabs.io",
  "noannoyance@sindex.com",
```

Thanks!

**Comment by axelrindle** [comment]
Got it! It must be incompatible with `extensions-sync@elhan.io`. After enabling this extension and restarting the gnome-shell, the issue occured again.

**Comment by charlesg99** [comment]
Thank you for that, I could reproduce the issue. A fix for it was added to our master branch, but it seems like it was also [fixed](https://github.com/oae/gnome-shell-extensions-sync/commit/b68b4c246806e418ea7924cf4501d0afd4293ae2#diff-14ef994fa167d355bdaf9b44add54b87) by the `extension-sync` developer. The problem was that, on your current version, extension-sync is adding `Array.prototype.diff`, which isn't ideal for compatibility.

Could you [install](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github) our latest development version to confirm that it fixes the issue?

Thanks!

**Comment by axelrindle** [comment]
The issue does no longer occur after I installed the latest development version. Thank you for your help :+1:
