### ISSUE TITLE
Call for translators for v24

### ISSUE THREAD

**Issue by jderose9** [home-sweet-gnome/dash-to-panel#756]
Hey all! If you are able to update the translations for the upcoming v24 in the next week, it would be very much appreciated. Thanks as always!

@frnogueira (pt_BR), @zeten30 (cs), @franglais125 (es), @LaurentTreguier / @SolarLiner (fr), @elsieholmes (uk), @hosiet (zh_CN), @jonnius / @linuxr01 (de), @urbalazs / @pappfer (hu), @crayxt (kk), @pkomur / @MartinPL / @alex4401 (pl), @AlexGluck / @GoodNike / @rjapolov (ru), @sicklylife-jp (jp), @oltulu / @TeknoMobil / @daenney (tr), @sbadux (it), @OriginCode / @pan93412 (zh_TW)

**Comment by charlesg99** [comment]
I'm so sorry guys, I made a booboo and forgot to include a new file where there are 3-4 more strings to translate :flushed: It this isn't too much to ask, could you please pull master again and regenerate the po files? Thanks!

**Comment by zeten30** [comment]
NP - https://github.com/home-sweet-gnome/dash-to-panel/pull/763/commits

**Comment by alex4401** [comment]
Absolutely not a problem - #757 updated.

**Comment by sicklylife-jp** [comment]
With pleasure.
https://github.com/home-sweet-gnome/dash-to-panel/pull/762/commits/447bd5c4bf42d74ddf999e6f91a10b4ae50bf0af

**Comment by urbalazs** [comment]
Hungarian translation is updated with squashed commit.

**Comment by TeknoMobil** [comment]
Turkish translation updated according to new version

**Comment by hosiet** [comment]
#758 `zh_CN` translation has been updated to reflect the new changes.

**Comment by GoodNike** [comment]
#779 russian has been updated.

**Comment by jderose9** [comment]
Ok, v24 is out! Thanks so much (as always!) for the effort getting these updated.
