### ISSUE TITLE
Breaks hotcorners

### ISSUE THREAD

**Issue by sgpthomas** [home-sweet-gnome/dash-to-panel#760]
I'm running Dash to Panel from master and the activities hot corner doesn't work. Is there a way to get hotcorners working with Dash to Panel?

**Comment by charlesg99** [comment]
Hello Samuel, the activities hot corner works just fine for me. What version of gnome-shell is that? Is it on Ubuntu? We recently added support for the native 3.34 gnome-shell setting letting the user disable the hot corner (see Tweaks --> Top Bar --> Activities Overview Hot Corner). Is this option enabled on your system? Thanks!

**Comment by sgpthomas** [comment]
I'm running Gnome 3.34 on Fedora 31 beta. I also made sure that the Tweaks --> Top Bar --> Hot Corner setting was enabled. I made sure that Dash to Panel is indeed the source of the problem by disabling it and checking whether the hot corner worked. It works when Dash to Panel is disabled. Furthermore I tried using the Custom Corners extension to set hotcorners which also didn't seem to work. I'm running from master.

Let me know if you need more details.

**Comment by charlesg99** [comment]
Is it on Wayland? I'm on 3.34 on X.org and it works correctly, weird. Are you seeing errors in your log maybe? Run `journalctl /usr/bin/gnome-shell -f -o cat` to have a look when you're trying to activate the hot corner. Thanks!

**Comment by sgpthomas** [comment]
Yes, I'm on Wayland. I'm not seeing anything when I try a hotcorner, but this printed out right away when I checked the journal:
```
clutter_actor_remove_child: assertion 'CLUTTER_IS_ACTOR (self)' failed
clutter_actor_remove_child: assertion 'CLUTTER_IS_ACTOR (self)' failed
clutter_actor_remove_child: assertion 'CLUTTER_IS_ACTOR (self)' failed
clutter_actor_remove_child: assertion 'CLUTTER_IS_ACTOR (self)' failed
clutter_actor_remove_child: assertion 'CLUTTER_IS_ACTOR (self)' failed
libinput error: client bug: timer event6 debounce short: offset negative (-4ms)
clutter_actor_remove_child: assertion 'CLUTTER_IS_ACTOR (self)' failed
clutter_actor_remove_child: assertion 'CLUTTER_IS_ACTOR (self)' failed
libinput error: client bug: timer event6 debounce short: offset negative (-2ms)
libinput error: client bug: timer event6 debounce short: offset negative (-6ms)
```
I also checked the journal without Dash to Panel enabled and still didn't see anything.

**Comment by charlesg99** [comment]
I could reproduce the issue on a Wayland machine and this should now be fixed on master. Thanks!

**Comment by sgpthomas** [comment]
Thanks! It's working for me now :)

**Comment by charlesg99** [comment]
Great, thanks for reporting back!
