### ISSUE TITLE
Occassionally creates invisible mouse barriers on wayland

### ISSUE THREAD

**Issue by sgpthomas** [home-sweet-gnome/dash-to-panel#764]
After a little bit of use on a freshly booted system, Dash to Panel seems to create these invisible barriers that I can't move my mouse through. I've tried to capture this in the gif

![weird-mouse-barrier](https://user-images.githubusercontent.com/3752122/66313194-f8247280-e8df-11e9-9258-a2a79dd2d672.gif)

I haven't found a reliable method to reproduce this unfortunately, but this seems to happen to me after about 30 mins of use. I don't really know what other information to provide that might be relevant. Let me know how I can help.

Oh, also rebooting or logging in and out causes these to go away.

**Comment by charlesg99** [comment]
Hello Samuel, is this on a virtual machine? I also noticed something similar on 3.34 running in virtualbox, but it happens even with vanilla gnome-shell. If not, could you try to reproduce this under Xorg? Do you have a multi-monitor setup?

I can't think of why that could happen... The only "barriers" that we create are set during the panel initialization or panelbox allocation (which doesn't change). Thanks!

**Comment by sgpthomas** [comment]
It's not a virtual box, I'm using a multi-monitor setup but it hasn't happened all day today. I'll keep an eye out though and try to see if I can figure out how to reproduce it,

**Comment by charlesg99** [comment]
Great, keep us posted!

**Comment by sgpthomas** [comment]
Well, I haven't been seeing this anymore so I will close the issue. The one thing that I noticed that changed and might explain why I don't see this anymore is that my mouse no longer gets stuck against the top left corner.

**Comment by sgpthomas** [comment]
Unfortunately the issue came back. However, I did figure out how to reproduce it.
 - Laptop connected to external display with the external display configured so that it is logically above the laptop display. I think it's important that some part of the laptop display doesn't have the external display above. In other words, there is some edge of the top of the laptop display where when you push the mouse against it, it stays on the laptop, rather than going up to the external display. Hopefully the image below will make this more clear. 
- Log out and back in (just to make sure we have a fresh slate)
- unplug external monitor
- there should be a barrier on the laptop display. The X pos of the barrier is about the same as the barrier that existed between the monitors, but the Y pos is shifted down to about the middle of the display.

![image](https://user-images.githubusercontent.com/3752122/67639061-b45ed080-f8c1-11e9-94a2-e7a8b60f4eb2.png)

I tried this same thing without Dash to Panel enabled and the barrier was not created, so it does seem to be caused by Dash to Panel somehow.

**Comment by charlesg99** [comment]
Hi, what gnome-shell version is that? Following your steps, I can't reproduce the issue on 3.28 (Wayland). Thanks!

**Comment by sgpthomas** [comment]
I'm on Gnome 3.34.1 on Fedora 31.

**Comment by charlesg99** [comment]
Do you still see this problem? Are you now on 3.36?

**Comment by sgpthomas** [comment]
nope, don't see the problem anymore
