### ISSUE TITLE
Auto sideways scroll if icons fills up the space on the panel not working in gnome 3.34

### ISSUE THREAD

**Issue by tnilzon** [home-sweet-gnome/dash-to-panel#770]
If there are more favorites icons then there is room on the panel, the row of icons used to auto scroll sideways when hovering the mouse pointer on the left or right end in order to show icons that are hidden. This is not the case in gnome 3.34, the icon row does not scroll, and hidden icons remain hidden.

**Comment by charlesg99** [comment]
Thanks for bringing this up tnilzon! Should now be fixed on master!

**Comment by tnilzon** [comment]
Grate, many thanks!
