### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by blazessdd** [home-sweet-gnome/dash-to-panel#774]
Please add the option to center the clock.
The extension is perfect no bugs so far, but the clock position really bugs me

**Comment by charlesg99** [comment]
Hello, the clock can already be centered, please set the following positioning options:

![image](https://user-images.githubusercontent.com/33044886/66720112-a17ad500-edc6-11e9-9a09-03027b46b2d6.png)

Thanks!
