### ISSUE TITLE
Any Mouse = Left Click ?

### ISSUE THREAD

**Issue by AlbinoGeek** [home-sweet-gnome/dash-to-panel#775]
Apparently, any mouse click except "Right" will trigger the "Left" action.

E.g: Wheeling my mouse up/down, pressing back, forward, or middle-click opens the application under my cursor, just as if I had left-clicked.

Is this intentional? Can I turn it off?

---

Left - Open Application
Right - Application Menu
Middle - Open Application (New Instance)
**Wheel Up - Same as Left
Wheel Down - Same as Left
Back (M4) - Same as Left
Forward (M5) - Same as Left**

**Comment by AlbinoGeek** [comment]
When referring to an "Application", I mean running applications such as those shown in this screenshot.

![Screenshot from 2019-10-13 13-13-03](https://user-images.githubusercontent.com/1910461/66721820-50191880-edbb-11e9-9c4b-e91c1034f103.png)

**Comment by charlesg99** [comment]
Hello AlbinoGeek, you can customize the left click, middle click and wheel actions under the "Action" tab of the extension settings. 

What you're saying about the Back and Forward buttons is suspicious (we don't handle those), but on my end these buttons do nothing if I press them while the mouse cursor is over an application icon (tested on gnome-shell 3.34, Xorg and Wayland). Did you configure them somehow? What version of gnome-shell are you using? Thanks!

**Comment by AlbinoGeek** [comment]
![image](https://user-images.githubusercontent.com/1910461/66785113-1d415400-ee91-11e9-828e-a62353488363.png)

Thank you for showing me this.

I must ask, however, using the "Scroll Action" -- this does not Cycle Windows, but that may be due to "Window Grouping" being disabled in my configuration. Is it true this only "cycles windows", or "does nothing"?

The back and forward button functionality seem to be different all around Gnome, it's probably not your fault at all. I am using Wayland with gnome-shell 3.32.2 (what is "Latest" for Fedora 30 Workstation.) I have no idea if Xorg is still involved, as `/var/log/X*` files do not exist, there is no log to tell me that Xorg-server ever even started. However, the package `xorg-x11-server-Xorg-1.20.5-7.fc30.x86_64` exists/comes with the system.

On normal panels, back and forward do nothing.
On the word "Applications" -> functions like **Left Click**
On the Places icon -> Does nothing
On Quick Launch icons -> Does nothing
On running application icons -> functions like **Left Click**

On System Tray Icons...
Any Click (1,2,3,4,5) -> Left Click (shows context menu)

The same goes for system menus (all along the right side of the pane.)

![image](https://user-images.githubusercontent.com/1910461/66785519-55956200-ee92-11e9-8c2a-cfbbf965d159.png)

---

As per Wayland, many versions were found... not sure which is relevant.

```
$ rpm -qa | grep wayland
libwayland-cursor-1.17.0-1.fc30.i686
libwayland-cursor-1.17.0-1.fc30.x86_64
xorg-x11-server-Xwayland-1.20.5-7.fc30.x86_64
gnome-session-wayland-session-3.32.0-1.fc30.x86_64
libwayland-server-1.17.0-1.fc30.x86_64
libwayland-egl-1.17.0-1.fc30.x86_64
libwayland-client-1.17.0-1.fc30.i686
libwayland-server-1.17.0-1.fc30.i686
wayland-devel-1.17.0-1.fc30.x86_64
egl-wayland-1.1.4-1.fc30.x86_64
libwayland-egl-1.17.0-1.fc30.i686
libwayland-client-1.17.0-1.fc30.x86_64
wayland-protocols-devel-1.17-2.fc30.noarch
egl-wayland-1.1.4-1.fc30.i686
qt5-qtwayland-5.12.5-1.fc30.x86_64
```

**Comment by charlesg99** [comment]
> I must ask, however, using the "Scroll Action" -- this does not Cycle Windows, but that may be due to "Window Grouping" being disabled in my configuration. Is it true this only "cycles windows", or "does nothing"?

Yes exactly. We cycle the windows "associated" with the icon, so when the applications are ungrouped, there is only one window per icon. Cycling over a single window icon results in bringing that window to the front and giving it focus (same as the left click option "Cycle through windows"). Maybe we could add another option that would "Cycle application windows"?

For now, If you want to cycle all windows, you could set "Cycle windows" for the "Scroll panel action". Thanks!

**Comment by AlbinoGeek** [comment]
Thank you!
