### ISSUE TITLE
Keyboard Shortcut for cycle all windows

### ISSUE THREAD

**Issue by ngmariusz** [home-sweet-gnome/dash-to-panel#776]
CURRENT
- You can cycle all windows with mouse scrolling panel

- You can cycle group of windows with keyboard shortcut (super+[group_nr])

EXPECTED

- You can cycle all windows with mouse scrolling panel

- You can cycle group of windows with keyboard shortcut (super+[group_nr])

- You can cycle all windows with keyboard shortcut (super+tab)    **<-- new**

**also** 

it would play nicely with current gnome windows switcher 

(

people trying to find solution 

eg: https://superuser.com/questions/394376/how-to-prevent-gnome-shells-alttab-from-grouping-windows-from-similar-apps/860001

to be able to have both keybindings

- cycle windows in all workspace AND

- cycle windows in only current workspace 

what is currently not easily available as there is OR option

/org/gnome/shell/window-switcher/current-workspace-only

)

**also** 

with /org/gnome/shell/window-switcher (or app-switcher) (default: alt+tab) there is currently no immediate feedback in panel (panel highlights after actual switch); contrary (super+[group_nr]) has immediate feedback and it is great. we would like to have it during simple super+tab  

**also** 

this feature request could be considered as idea to simplify UX ; 

A (switching window scenario)

currently: you must  think first group -> then window;  

after:  just super+tab as you are good

B (switching to previous  -> perhaps most used switching window scenario )

currently: you must  think group  

after: just super+tab once

**Comment by ngmariusz** [comment]
Perhaps we just need another so called "click action"

**Comment by charlesg99** [comment]
Hello Mariusz, lets continue in #1053, as I don't think overriding the super+tab shortcut is a good idea. Thanks!
