### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by CoryOwens** [home-sweet-gnome/dash-to-panel#777]
When attempting to install via extensions.gnome.org and the Chrome add-on, the following error is output to the console: 

    Uncaught (in promise) GDBus.Error:org.gnome.Shell.LoadExtensionError: Error: Failed to parse metadata.json: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

Attempted reinstalling the Chrome addon and updating Chrome, but the issue persists.

**Comment by charlesg99** [comment]
Hello, seems like the e.g.o. installation didn't work correctly, could you try deleting `~/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com` and try again? If all else fails, you could try [installing from Github](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github). Thanks!

**Comment by CoryOwens** [comment]
> could you try deleting ~/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com and try again?

That did the trick. Thanks!
