### ISSUE TITLE
TypeError: ExtensionSystem.connect is not a function on GNOME 3.34.1

### ISSUE THREAD

**Issue by divad** [home-sweet-gnome/dash-to-panel#778]
On GNOME 3.34.1 on arch linux (latest) the extension results in an error. The error log is:

```
JS ERROR: Extension dash-to-panel@jderose9.github.com: TypeError: ExtensionSystem.connect is not a function
                                           enable@/home/drb/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:52:31
                                           _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:131:13
                                           loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:263:21
                                           callback@resource:///org/gnome/shell/ui/extensionDownloader.js:232:17
                                           gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:99:13
```

This happens on the version installed from gnome extensions, and from master on github.

**Comment by divad** [comment]
Strangely, Alt+F2, entering 'r' to restart, fixes it - until I next login :(

**Comment by charlesg99** [comment]
Hello David, does this also happen if you disable all of your other extensions and restart gnome-shell? Also, before the error in your log, do you see other js errors? I'm also on Arch with 3.34.1 and I can't reproduce this. Thanks!

**Comment by Drumso** [comment]
I have the same issue, on Ubuntu 19.10. Just default extensions installed: dash-to-dock (Ubuntu dock, disabled), Ubuntu appIndicators and Desktop Icons.

**Comment by charlesg99** [comment]
Hello, please disable all of your other extensions and restart gnome-shell. I just installed Ubuntu 19.10 and can't reproduce this with v23 or the current master. Thanks!

**Comment by charlesg99** [comment]
Seems related, please look at this: https://github.com/home-sweet-gnome/dash-to-panel/issues/740#issuecomment-533927770

**Comment by divad** [comment]
It works when I disable others and then login normally, very odd. Thanks!

**Comment by charlesg99** [comment]
Yes that happens quite often when another extension encounters an error while disabling itself before locking the screen. If you look at your logs, try to find the first JS error that occurs when locking your screen, that should be the relevant error and point to the faulty extension on 19.10 (probably needs an update). Thanks for the feedback!
