### ISSUE TITLE
Seems broken in 19.10 (Error loading extension)

### ISSUE THREAD

**Issue by jurosh** [home-sweet-gnome/dash-to-panel#781]
Seems that there is problem on the latest Ubuntu 19.10, it just says `Error loading extension`

![image](https://user-images.githubusercontent.com/1630137/67422556-060e0f00-f5d3-11e9-9d1a-055d68a00224.png)

**Comment by charlesg99** [comment]
Hello, could you please provide the dash to panel version you're using and the error shown in the looking glass? To do so, press <kbd>ALT</kbd>+<kbd>F2</kbd> then enter the "lg" command then <kbd>Enter</kbd>. In the looking glass window, on the top right you can select "Extensions", then under dash to panel click on "show errors". I did some tests on Ubuntu 19.10 and it works correctly on my end.

Thanks!

**Comment by jurosh** [comment]
Thanks very much!

First, sorry I didn't checked first, but I was running version `19` which doesn't have support of gnome `3.34.1`. Now trying latest version `23` and it works perfectly.
