### ISSUE TITLE
Window / Activies Overview Not Working  In Fedora 31 (GNOME 3.34).

### ISSUE THREAD

**Issue by jsgrant** [home-sweet-gnome/dash-to-panel#785]
Seemingly running into the same issue as ' samcompton ' on extensions.gnome.org -- where the Window Overview is blank and am unable to exit it without forcing a Gnome-Shell restart. I am able to do a Win-A to get into the application overview; But am too unable to exit it without a Gnome-Shell restart.

Below is a screenshot that 'should' display 5 workspaces , and an active Firefox window. 
![Screenshot from 2019-10-26 02-22-18](https://user-images.githubusercontent.com/52618678/67616017-3b645980-f799-11e9-9be2-4225b4c86959.png)

**Comment by charlesg99** [comment]
Hello jsgrant, thank you for the report! Do you see error messages in your logs when this happens (you can check by running `journalctl /usr/bin/gnome-shell -f -o cat` before reproducing the issue)? What version of dash to panel is this? Do you have other installed extensions? Thanks!

**Comment by jsgrant** [comment]
Hm, I slept on it; And remembered I had the following copr repo enabled 'https://copr.fedorainfracloud.org/coprs/pp3345/gnome-with-patches/' before I ran the system-updater to get Fedora 31 (And still present afterwards) ; This seems to be the source of the problem after running a gnome-shell and mutter 'downgrade' (reverting back to upstream). Restarted the machine, re-enabled dash-to-panel and everything is now working as expected! So I think this might more fall into user-error territory. :^)

For the sake of posterity; I was trying both the 3.34-23 and head / upstream built versions of dash-to-panel on gnome-shell 3.34.1-201 and mutter 3.34.1-403. These are, as the copr name implies -- fairly modified, with a lot of the appeal being many of the performance improvements from more current releases get pushed there. This is also a pretty popular repo, with a reported 1500 users... so can see this being a relatively common issue in a few weeks, as more people upgrade their distro to F31.

I use a bunch of extensions, but was sure to turn everything else off before testing; I have now reproduced the error by re-enabling the copr repo and 'dnf uprade gnome-shell mutter", rebooting, re-logging in as a given user, and re-enabling dash-to-panel with the copr modified mutter & gnome-shell; The following is a log of the given journalctl readout before and after dash-to-panel (in a xorg based session):

> Will monitor session 2
Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
Failed to CRTC gamma: drmModeCrtcSetGamma on CRTC 48 failed: Permission denied
Failed to CRTC gamma: drmModeCrtcSetGamma on CRTC 48 failed: Permission denied
STACK_OP_ADD: window 0x1a00001 already in stack
STACK_OP_ADD: window 0x1a00001 already in stack
GNOME Shell started at Sat Oct 26 2019 14:38:00 GMT-0500 (CDT)
Registering session with GDM
Connection to xwayland lost
Usage of object.actor is deprecated for EmojiPager
get@resource:///org/gnome/shell/ui/environment.js:249:29
EmojiSelection@resource:///org/gnome/shell/ui/keyboard.js:890:9
_setupKeyboard@resource:///org/gnome/shell/ui/keyboard.js:1188:32
_syncEnabled@resource:///org/gnome/shell/ui/keyboard.js:1138:13
Keyboard/<@resource:///org/gnome/shell/ui/keyboard.js:1091:21

Then when enabled, there is no-input in the journal; But (and not sure if this is even useful), when I have to force-restart the shell -- like 'alt-f2 r' the following gets spewed out.

> Window manager warning: META_CURRENT_TIME used to choose focus window; focus window may not be correct.
> JS ERROR: TypeError: actor.get_meta_window(...) is null
_destroyWindowDone@resource:///org/gnome/shell/ui/windowManager.js:1594:26
onStopped@resource:///org/gnome/shell/ui/windowManager.js:1564:34
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:72:13
_easeActor/<@resource:///org/gnome/shell/ui/environment.js:131:56
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:221:9
>
> JS ERROR: TypeError: actor.get_meta_window(...) is null
_destroyWindowDone@resource:///org/gnome/shell/ui/windowManager.js:1594:26
onStopped@resource:///org/gnome/shell/ui/windowManager.js:1564:34
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:72:13
_easeActor/<@resource:///org/gnome/shell/ui/environment.js:131:56
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:221:9
>
> JS ERROR: TypeError: actor.get_meta_window(...) is null
_destroyWindowDone@resource:///org/gnome/shell/ui/windowManager.js:1594:26
onStopped@resource:///org/gnome/shell/ui/windowManager.js:1564:34
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:72:13
_easeActor/<@resource:///org/gnome/shell/ui/environment.js:131:56
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:221:9
>
> Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
Will monitor session 2
current session already has an ibus-daemon.
ibus_bus_hello: assertion 'ibus_bus_is_connected (bus)' failed
Error while sending AddMatch() message: The connection is closed
ibus_bus_call_async: assertion 'ibus_bus_is_connected (bus)' failed
ibus_bus_call_async: assertion 'ibus_bus_is_connected (bus)' failed
Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
GNOME Shell started at Sat Oct 26

If I missed anything, and/or you have anything else I should try to report on; Please let me know. But I'm going to make sure to leave a comment on extensions.gnome.org for those effected now.

**Comment by charlesg99** [comment]
Glad you got it working! Just wondering, when using the copr repo, does the overview works correctly without dash to panel? I don't see any errors related to the extension in your logs. Thanks!

**Comment by jsgrant** [comment]
Yup, overview works as expected without dash-to-panel enabled (with the given copr repo); Find it pretty odd though. I even tested some other extensions I thought would cover the same space of "not supposed to be effecting overview, but is visible in it", like workspace-to-dock and dash-to-dock and found no issues there. 

If you think of anything else I should check, will be glad to; But yeah, a bit more confused than I was before that it JUST seems to be effecting dash-to-panel.

**Comment by jderose9** [comment]
I was able to reproduce this in a VM. It looks like the specific issue was caused by:
https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/605

These lines were removed in workspacesView.js:
````
view.connect('scroll-event', this._onScrollEvent.bind(this));
            if (i == this._primaryIndex) {
                this._scrollAdjustment = view.scrollAdjustment;
                this._scrollAdjustment.connect('notify::value',
                                               this._scrollValueChanged.bind(this));
            }

````

This COPR is patching in open merge requests, and they don't all seem to be compatible with the newest gnome-shell itself as it's throwing all sort of other errors unrelated to dash-to-panel. I would not recommend using it in general. 

I made a small fix in the master branch, if you'd like to give it a try. I don't think that we can reasonably maintain compatibility with this copr package going forward, but at least those using it currently won't get trapped in a broken overview.

**Comment by jsgrant** [comment]
Confirmed that Master now works via 'gnome-with-paches'; Completely agree that it's not a reasonable to expect compatibility if the Copr is grabbing 'that new' of patches. I always assumed it was from the latest stable or at-least beta -- but never bothered to check.

It's still relevant to note; And I'll repeat it again to highlight the fact that it is a pretty popular repo in Fedora and if this continues to be a problem in future releases, maybe it would be worth adding a note under 'Compatibility' in the README? I don't know, just spit-balling.

**Comment by jsgrant** [comment]
Closing for now; Still think it's probably a good-idea to casually mention  somewhere the possible copr incompatibilities going forwards -- but as-is, good enough / working solution.
