### ISSUE TITLE
GNOME running indicators have been reveresed from bottom to top in latest update

### ISSUE THREAD

**Issue by Scotty-Trees** [home-sweet-gnome/dash-to-panel#787]
In the newest version (v25), the running indicator position for GNOME things like the date/time/open weather/WiFi, Bluetooth, sound icons has moved from the bottom of the panel to the top of the panel. I can change application icons indicator (i.e. Firefox, Files, etc.) positions from top to bottom, but not the GNOME ones like I listed above. Is this a bug or can this be fixed? I much preferred when all indicators where on the bottom as it keep things looking consistent throughout the panel. 

Below is a quick screenshot to show what I am referring to. Applications that are opened, have an indicator under them, but the app drawer for example puts the indicator at the top (the blue line which is part of my Plata theme). It is the same way when you click on the clock or the system tray in GNOME. Hope this can be looked at or possibly fixed. Other than that this extension is very amazing and I appreciate all the work and effort that has gone into this!

If you need more info feel free to ask!

https://i.imgur.com/5HSubIG.png

**Comment by charlesg99** [comment]
Hello Scotty-Trees, thanks for bringing that up! Yes indeed, looks like I screwed up the css compatibility with the vertical panel, sorry about that :(

This should now be fixed on the master branch, could you please [install it](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github) and confirm that it works for you as well? Thanks!

**Comment by Scotty-Trees** [comment]
Thanks for the super quick reply. When I try to install the master branch using git clone, I get an error. Hopefully I did it correctly, but I used git clone to get dash-to-panel into my home directory, then i moved it to the gnome extensions folder where all the other extensions are replacing the old dash to panel extensions (don't worry I backed up the original of course), and when I reload the shell with ALT+F2+R, when I go into Gnome Tweaks to enable the extension, I get the following error:

The settings of extension dash-to-panel@jderose9.github.com had an error:
```
GLib.FileError: Failed to open file “/home/scott/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/schemas/gschemas.compiled”: open() failed: No such file or directory
```

Stack trace:
```
getSettings@/home/scott/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/convenience.js:75:24
_init@/home/scott/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/prefs.js:160:26
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_Base.prototype._construct@resource:///org/gnome/gjs/modules/_legacy.js:18:16
newClass@resource:///org/gnome/gjs/modules/_legacy.js:114:32
buildPrefsWidget@/home/scott/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/prefs.js:2027:20
_showPrefs@resource:///org/gnome/shell/extensionPrefs/main.js:57:22
_extensionsLoaded@resource:///org/gnome/shell/extensionPrefs/main.js:320:13
_scanExtensions/<@resource:///org/gnome/shell/extensionPrefs/main.js:298:13
asyncCallback@resource:///org/gnome/gjs/modules/overrides/Gio.js:132:13
main@resource:///org/gnome/shell/extensionPrefs/main.js:707:5
@<main>:1:43
```

**Comment by charlesg99** [comment]
> then i moved it to the gnome extensions folder where all the other extensions are replacing the old dash to panel extensions

That is why :) You need to `git clone` (as you did), then `cd` into the new folder (in your case `/home/scott/dash-to-panel`), then run `make install`. Finally, restart gnome-shell.

Running `make install` will create the missing `gschemas.compiled` file and replace the dash-to-panel installation in `/home/scott/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com`

Thanks!

**Comment by Scotty-Trees** [comment]
Thanks for your instructions, that did it! So with the git clone correctly installed this time and gnome-shell restarted, the new dash-to-panel extension loaded up and now the indicators show up on the bottom just like before! Thank you very much for the super quick fix and happy to have helped out. I would now say this issue is fixed, and I look forward to using this extension for a long time! Thanks again, you guys are the best!

**Comment by charlesg99** [comment]
Great, glad you got it working! It looks much better indeed!
