### ISSUE TITLE
[Regression] Padding change when mouse hovers over items

### ISSUE THREAD

**Issue by a1291762** [home-sweet-gnome/dash-to-panel#789]
I had been running v23 under Gnome 3.28 (Ubuntu 18.04).
I have 2 monitors with the panel on the top of both of them.
There seems to be a main screen (with the system tray) and a secondary screen.
Today I was prompted to update (to v25) and noticed some odd padding behaviour going on.

My main monitor seems to have had a bunch of padding removed from favourite icons.
eg. (v23 on the left, v25 on the right)
![v23_main](https://user-images.githubusercontent.com/327162/67734554-18fa6680-fa4d-11e9-962d-578132dab79e.png) vs ![v25_main](https://user-images.githubusercontent.com/327162/67734319-793cd880-fa4c-11e9-9c11-ef68a528cd9a.png)

My secondary monitor has not had the padding removed, but when mousing over some elements, they lose their padding. The elements affected seems to be inconsistent from one run to another. So far I've seen the thunderbird icon, the firefox icon and an app window icon do it.
eg. (v25 on the left, v25 with a mouse-hovered firefox icon on the right)
![v25](https://user-images.githubusercontent.com/327162/67734374-a12c3c00-fa4c-11e9-903d-a466ef18093b.png) vs ![v25_compressed](https://user-images.githubusercontent.com/327162/67734378-a4272c80-fa4c-11e9-980f-9bb643d51b73.png)

**Comment by charlesg99** [comment]
Did you restart gnome-shell after updating to v25? I'm running v25 on Ubuntu 18.04 (multi-monitors) and the padding doesn't change between v23 and v25. Thanks!

**Comment by a1291762** [comment]
I updated via https://extensions.gnome.org/local/ (firefox extension).
Apparently that does not do a full gnome-shell restart, because after explicitly restarting gnome shell (r) the padding appears to be normal again.
