### ISSUE TITLE
Setting "Panel screen position" to "Left" causes panel to be placed in the bottom

### ISSUE THREAD

**Issue by aravindhp** [home-sweet-gnome/dash-to-panel#792]
I am running `Dash to panel` v25 on Fedora 30 (Gnome) with two monitors. An ultra-wide 34" in landscape mode and a 27" in portrait mode. If I try to change the `Panel screen position` to `Left` or `Right` causes the panel to placed in the bottom instead of left or right.

**Comment by charlesg99** [comment]
Hello, did you restart gnome-shell following the v25 update? Thanks!

**Comment by aravindhp** [comment]
Restarting gnome-shell fixed the problem. Thank you!
