### ISSUE TITLE
Panel hiding when hovering over app menu

### ISSUE THREAD

**Issue by Thalos12** [home-sweet-gnome/dash-to-panel#795]
I noticed a strange behaviour since the last update of the extension.

After I open the menu of an app on the panel, as soon as I get out of the area of the latter it hides, but the menu stays open. Afterwards, as I hover on one of the entries of the menu, it shifts down, as if it had to reconnect with the now hidden panel.

I have a short video which shows this happening: [https://streamable.com/jrx5y](https://streamable.com/jrx5y)

**Comment by charlesg99** [comment]
Hello, I can't reproduce this so far, could you please try to disable your other extensions, restart gnome-shell then try again? Also, what gnome-shell version are you using? Thanks!

**Comment by Thalos12** [comment]
Hi, thanks for your reply. My `gnome-shell` version is `GNOME Shell 3.28.4`.

I tried the following:

- Disabled all extensions, restarted gnome-shell (`Alt-F2` then `r`), enabled only dash to panel: I still have the problem.

- Disabled `dash-to-panel`, removed it, restarted gnome-shell, then reinstalled the extension: the problem is still there.

If you have anything else you want me to try just tell me, I'll do it asap.

**Comment by charlesg99** [comment]
Ha yes thank you, I could reproduce the issue on 3.28. It should now be fixed on the master branch, could you please confirm that?

**Comment by Thalos12** [comment]
Following the instructions [here](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation) I installed the version from master and *it works*!
Thanks a lot for your time!
