### ISSUE TITLE
[Feature Request] Cycle all monitor windows in Scroll icon action (=scroll panel action)

### ISSUE THREAD

**Issue by alespg** [home-sweet-gnome/dash-to-panel#796]
Hi!
i love the new scroll actions, it is very fast and easy to use, but the behaviour is not exactly what i expected.
i use dash to panel with the applications ungrouped, so in the Scroll icon action the only option Cycle windows is not very useful, because it only cycle among the same group apps.
i expected in this situation to do the same that the Scroll panel action, cycle among all the windows of the isolated monitor.
now i have the Icon action disabled and every time i have to look for the free panel space to cycle. it still works fine, but it is not as useful as if i could scroll anywhere

**Comment by charlesg99** [comment]
Hello alespg, thank you for the suggestion! A new option was added to the available scroll icon actions. Now, selecting "Same as panel" should do just that and use the action selected for the panel. Could you please [install the latest development version](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github) and see if that works for you? Thanks!

**Comment by alespg** [comment]
hi! i have pulled last changes and the option "same as panel" is not working as expected yet.

i mean, it does the same as panel -> cycle windows, but it cycles windows as the old "cycle windows" option in the "Scroll icon action", it cycles only the same app instances.

thank you very much for having my suggestion into consideration and the great support, i am here to help you in anything into my capabilities

**Comment by charlesg99** [comment]
Hello, I'm not sure how you're getting that result... Did you correctly restart gnome-shell after installing the last version? I just tested on gnome-shell 3.34 and 3.28 and this is what I get:

![Peek 2019-11-08 08-33](https://user-images.githubusercontent.com/33044886/68480478-ea298080-0202-11ea-96bc-a1481cd6d41a.gif)

Is it working as expected for the "Switch workspace" panel action? 

Also, please know that the "Cycle windows" panel action only affects windows associated with the panel over which you are scrolling, so, say you only have one window on your primary monitor and one window on your secondary monitor (and you have isolated panels on each monitor), scrolling over a panel won't switch between both windows as they don't "belong" to the same panel. Hope this is clear :)

Thanks!

**Comment by alespg** [comment]
Oh, my bad, I did not restart the gnome-shell, just the extension. Too bad I can't test it again til Monday, it looks great!

**Comment by alespg** [comment]
tested, it works perfectly, thank you!!

**Comment by charlesg99** [comment]
Great!
