### ISSUE TITLE
[Feature Request] Add the option to invert the order of the elements of the (vertical) panel.

### ISSUE THREAD

**Issue by kingthorne** [home-sweet-gnome/dash-to-panel#797]
First of all, I want to thank everyone that makes this extension possible: it literary makes GNOME usable for me.
I've started using it in vertical mode and because I'm so used to Windows 10 workflow and having the taskbar on the bottom I always try to find the icons there, on the botton of the screen. For this reason I would like to ask if you can add the option to invert the icons and the rest of the elements of the panel. Some pics to show what I mean:

Current layout:

![dashtopanel-vertical](https://user-images.githubusercontent.com/57360543/68131361-36cc3d80-ff1d-11e9-821a-923c68db1d13.png)
Desired:

![dash-to-panel-inverted](https://user-images.githubusercontent.com/57360543/68131474-7004ad80-ff1d-11e9-97ca-e1ddeaae8841.png)
If this turns out something non trivial to implement, I'd like to be pointed on the right direction to be able to learn and contribute to this project on my own. Thanks again.

**Comment by charlesg99** [comment]
Hello, this is now possible, please install the latest master branch. Thanks!
