### ISSUE TITLE
DtP v. 25 breaks moving an app to a folder

### ISSUE THREAD

**Issue by fthx** [home-sweet-gnome/dash-to-panel#799]
Hi Charles,

Just gave a try to v. 25 (didn't use DtP since some time), I noticed using DtP does not allow me to move an app to an existing folder in GS apps overview.
Deactivate DtP allows it again.

Ubuntu 20.04 dev (roughly similar to 19.10 at the moment), GS 3.34, GNOME Wayland session

Errors in logs *maybe* :-) related :

![image](https://user-images.githubusercontent.com/23138504/68159400-00f57c00-ff52-11e9-981a-46d9baf05108.png)

![image](https://user-images.githubusercontent.com/23138504/68159449-14a0e280-ff52-11e9-8ba1-0294042ad8d4.png)

**Comment by charlesg99** [comment]
Hello fthx! Could you please provide more information maybe? I tried reproducing your issue with v25 and the current master on Ubuntu 19.10 (Xorg and Wayland) without success. Did you try with your other extensions disabled?

The only thing I noticed that could be related was that you can't add an application icon to a folder if the screen resolution is very small (not sure why). i.e. in the following, I couldn't add an application to the "Utilities" folder, but I could when the screen resolution allowed a larger grid:

![image](https://user-images.githubusercontent.com/33044886/68173023-993a3380-ff47-11e9-9843-ed6f6f639953.png)

Could this be related? Having a panel larger than the default gnome-shell top bar might explain this. 

Thanks!

**Comment by fthx** [comment]
I've just checked again, I can confirm the bug and the "dragMonitor" error message, which seems related. My resolution is FHD.

Here are my settings : 


[/]
animate-app-switch=false
animate-show-apps=false
animate-window-launch=false
appicon-margin=1
appicon-padding=2
click-action='CYCLE-MIN'
dot-color-1='#ffffff'
dot-color-2='#ffffff'
dot-color-3='#ffffff'
dot-color-4='#ffffff'
dot-color-dominant=false
dot-color-override=true
dot-color-unfocused-1='#5294e2'
dot-color-unfocused-2='#5294e2'
dot-color-unfocused-3='#5294e2'
dot-color-unfocused-4='#5294e2'
dot-position='TOP'
dot-size=2
dot-style-focused='SEGMENTED'
dot-style-unfocused='SEGMENTED'
enter-peek-mode-timeout=400
focus-highlight=true
focus-highlight-color='#ffffff'
focus-highlight-dominant=false
focus-highlight-opacity=25
group-apps=true
group-apps-label-font-color='#dddddd'
group-apps-label-max-width=350
group-apps-underline-unfocused=true
group-apps-use-fixed-width=true
group-apps-use-launchers=true
hot-keys=false
hotkeys-overlay-combo='TEMPORARILY'
intellihide=false
intellihide-animation-time=200
intellihide-behaviour='FOCUSED_WINDOWS'
intellihide-close-delay=400
intellihide-hide-from-windows=false
intellihide-key-toggle=['<Super>i']
intellihide-key-toggle-text='<Super>i'
intellihide-only-secondary=false
intellihide-pressure-threshold=200
intellihide-pressure-time=1000
intellihide-show-in-fullscreen=false
intellihide-use-pressure=false
isolate-workspaces=true
location-clock='BUTTONSLEFT'
middle-click-action='LAUNCH'
minimize-shift=false
multi-monitors=false
overlay-timeout=1000
panel-position='TOP'
panel-size=26
peek-mode=false
peek-mode-opacity=30
preview-custom-opacity=25
preview-middle-click-close=false
preview-use-custom-opacity=false
scroll-icon-action='NOTHING'
scroll-panel-action='NOTHING'
shift-click-action='MINIMIZE'
shift-middle-click-action='LAUNCH'
show-activities-button=false
show-appmenu=false
show-apps-icon-file=''
show-apps-icon-side-padding=2
show-show-apps-button=true
show-showdesktop-button=true
show-showdesktop-hover=false
show-tooltip=false
show-window-previews=false
show-window-previews-timeout=500
showdesktop-button-width=16
stockgs-keep-dash=false
taskbar-locked=false
taskbar-position='LEFTPANEL_FIXEDCENTER'
trans-bg-color='#d3d7cf'
trans-dynamic-behavior='FOCUSED_WINDOWS'
trans-gradient-bottom-color='#ffffff'
trans-gradient-bottom-opacity=0.20000000000000001
trans-gradient-top-opacity=0.80000000000000004
trans-panel-opacity=0.70000000000000007
trans-use-custom-bg=false
trans-use-custom-gradient=false
trans-use-custom-opacity=true
trans-use-dynamic-opacity=false
tray-size=0
window-preview-animation-time=150
window-preview-fixed-x=false
window-preview-fixed-y=false
window-preview-height=281
window-preview-padding=4
window-preview-show-title=false
window-preview-size=640
window-preview-title-font-color='#dddddd'
window-preview-width=500

**Comment by charlesg99** [comment]
Hi fthx, I tried again with your resolution and your settings on Ubuntu 19.10 and still can't reproduce the issue. Also tried on gnome-shell 3.35.1, works as expected there as well. Have you encountered this problem on a distribution other that Ubuntu 20.04? Thanks!

**Comment by fthx** [comment]
No I do use only Ub 20.04 dev.

I tested again, without any other extension enabled : I can drag an app outside an app folder but I cannot drag an app inside.

Ubuntu 20.04 do have some updated GS+Mutter from 19.10 with some git pickings, but I don't know if it's related.
