### ISSUE TITLE
Change Panel Color

### ISSUE THREAD

**Issue by e-Captain** [home-sweet-gnome/dash-to-panel#800]
Hello,

 How can i change the color of the panel? I have already modified some usr/share/themes/<files>.css but nothing happened. I can see difference only when i apply high contrast theme. Is there a .css file i can modify to change the colors?

Thank you in advance!

**Comment by charlesg99** [comment]
Hello e-Captain, you can change the color in the extension settings:

![image](https://user-images.githubusercontent.com/33044886/68313129-18338700-0082-11ea-835e-18ac2703a3d1.png)

Thanks!

**Comment by e-Captain** [comment]
Hello again and thank you for your reply,

In the settings of my dash to dock i can't find this.
But i managed to change the colors by doing this:
sudo gedit /usr/share/gnome-shell/theme/ubuntu.css
and then found the line /* panel color */
and changed this:
background-gradient-start: #<insert_your_color_code_here>
background-gradient-end: #<insert_your_color_code_here>
and it worked!!

**Comment by charlesg99** [comment]
You're probably looking for [dash to dock](https://github.com/micheleg/dash-to-dock) then :)
