### ISSUE TITLE
Dash to Panel doesn't use custom OBS icon, and I can't add obs in the favorites.

### ISSUE THREAD

**Issue by flakesrc** [home-sweet-gnome/dash-to-panel#802]
Expected Behavior: Display the icon according to the theme applied, the same icon that appears in the Arc Menu. And also being able to bookmark the program, but that doesn't appear in the options, I only have the option to quit the program.

Current Behavior: https://vimeo.com/371516392

**Comment by charlesg99** [comment]
Hello flakesrc, could you disable Dash to Panel and verify if the correct icon is displayed on the gnome-shell dash in the overview?

We don't select which icon is to be displayed, so this is most likely an OBS configuration problem. Please see #393 for more information. Thanks!

**Comment by flakesrc** [comment]
hmmm, the problem seems to be with gnome, look at this: https://imgur.com/a/Eu9PEub

**Comment by charlesg99** [comment]
Yeah though so... How did you install OBS? I suspect that the installation didn't provide a proper desktop file (to correctly associate the application wmclass).

Do you have an `obs.desktop` (or something like it... not sure if this is the correct name...) file in `/usr/share/applications` or `~/.local/share/applications`? If so, can you find a line starting with `StartupWMClass` in there? Thanks!

**Comment by flakesrc** [comment]
```applications $ ls | grep obs
com.obsproject.Studio.desktop
```

**Comment by flakesrc** [comment]
com.obsproject.Studio.desktop
com.obsproject.Studio.desktop
file `com.obsproject.Studio.desktop`
```[Desktop Entry]
Version=1.0
Name=OBS Studio
GenericName=Streaming/Recording Software
GenericName[fr]=Logiciel d'enregistrement/diffusion
Comment=Free and Open Source Streaming/Recording Software
Comment[fr]=Logiciel libre d'enregistrement et de diffusion sur Internet
Comment[ru]=Бесплатная программа с открытым кодом для записи/трансляции видео
Exec=obs
Icon=com.obsproject.Studio
Terminal=false
Type=Application
Categories=AudioVideo;Recorder;
StartupNotify=true```

Icon theme:
```Zafiro $ ls apps/scalable | grep obs
com.obsproject.Studio.svg
com.uploadedlobster.peek.svg
obs.svg
```

**Comment by charlesg99** [comment]
In your .desktop file, could you try adding the line `StartupWMClass=obs`, then restart gnome-shell? Thanks!

**Comment by flakesrc** [comment]
Oh, I had a lot of work figuring it out, but I did it and it just worked
Thx for attention

**Comment by charlesg99** [comment]
Glad you got it working!
