### ISSUE TITLE
Fail to change the resolution of display when using vertical panel.

### ISSUE THREAD

**Issue by kevinhwang91** [home-sweet-gnome/dash-to-panel#803]
Gnome shell always restarts when changing the resolution by using a vertical panel.

Only to turn off the dash-to-panel makes it fine.

**Comment by charlesg99** [comment]
Hello kevinhwang91, thank you for the report! I could reproduce the issue and it should now be fixed on the master branch, could you please confirm that?

**Comment by kevinhwang91** [comment]
It works!  So efficient.
