### ISSUE TITLE
File dialog causes an exception

### ISSUE THREAD

**Issue by matheo** [home-sweet-gnome/dash-to-panel#804]
When I enable this extension and I try to download a file, gnome gets restarted (probably because of an exception) and I just figured out that I can download files properly disabling this extension.

This happened multiple times while selecting files or trying to use the file dialog for Google Chrome mostly, but also for other applications.

I've seen this behavior since Ubuntu 19.10-beta.

**Comment by charlesg99** [comment]
Hello matheo, please provide more information about the issue (dash-to-panel version, gnome-shell version, list of other installed extensions, steps to reproduce, error log of the crash). I just tested on Ubuntu 19.10 and I can download files just fine with Chrome and Firefox using the file dialog. Thanks!
