### ISSUE TITLE
Dynamic Panel Text Color and Thumbnail Padding

### ISSUE THREAD

**Issue by alex285** [home-sweet-gnome/dash-to-panel#805]
I don't know how to describe that on title, it is a three-parts UX issue that everything is relating.

**First** is the problem that the text is unreadable on light background (#727) so if we could had a dynamic text coloring depending the contrast it would be great
![text-bug](https://user-images.githubusercontent.com/11244308/68532613-39b59c80-0328-11ea-83e0-e51ed0504c76.png)

**Second** on thumbnails header, we can change the color, but I think it would be better to have a dynamic font coloring (same as the above), so we won't need to change that every time we change panel color (which is a more often action); and also there should be a single color selection for both Panel and Thumbnail windows

![text-bug-2](https://user-images.githubusercontent.com/11244308/68532618-4afea900-0328-11ea-9209-7aee8be2dfad.png)

**Third** is the padding on thumbnails, and most specifically the top and bottom that look bad both on transparent panels and colored. At least optionally, padding should only affect neighbor windows, and not bottom and top (or first left and last right)

![text-bug-3](https://user-images.githubusercontent.com/11244308/68532656-da0bc100-0328-11ea-8653-d37f60074b49.png)

I uploaded a YouTube with those issues, because it feels easier to explain them on a video: https://youtu.be/ooO9JXEjGKE?t=28

**Comment by Jarel1337** [comment]
On the first, isn't it more elegant to always have the font be dynamically white or black?

**Comment by alex285** [comment]
> On the first, isn't it more elegant to always have the font be dynamically white or black?

Personally I agree, but if others have requests for custom colors? I'm never against of any additional even extreme option, but DtP Preferences window is starting to get hard to use :/
