### ISSUE TITLE
Auto hide panel issues after unlocking user account

### ISSUE THREAD

**Issue by calotam** [home-sweet-gnome/dash-to-panel#808]
If you select auto hide panel, after unlocking the account, panel paints over all the windows in the screen, resizing all windows that overload in the panel. Please, can you fix it?

**Comment by charlesg99** [comment]
Hello calotam, you could try settings this delay to 0:

![image](https://user-images.githubusercontent.com/33044886/68611302-d5115380-0487-11ea-97cb-f2ebb12a704f.png)

Thanks!

**Comment by calotam** [comment]
Ok, it works as you say. Thanks!!!
