### ISSUE TITLE
Misaligned Right Panel

### ISSUE THREAD

**Issue by Utkarsh1367** [home-sweet-gnome/dash-to-panel#809]
In the recent Release (V25) It seems that the right panel is a bit misaligned. It seems out of place when the windows are maximized. I am using Ubuntu 19.10.
![Screenshot from 2019-11-12 12-45-44](https://user-images.githubusercontent.com/26401278/68635026-64cc0600-054b-11ea-9356-5293cb7a4c60.png)

**Comment by charlesg99** [comment]
Hello Utkarsh1367, what extension are you using to display the tray icons? Do you see the same problem if you disable the tray icons extension and restart gnome-shell? Seems like the VLC icon isn't scaling correctly, which expands the height of the right box. Thanks!

**Comment by Utkarsh1367** [comment]
Thanks for pointing this out.

**Comment by Utkarsh1367** [comment]
I was not using any tray icon extension. It was just the default system tray icon from the VLC. After disabling it the problem was solved. 
Yet this happens whenever there is an application running which has a default tray icon. This problem rises again when i try to customize the top bar windows button option in the Unite extension (the three windows buttons).
It seems that instead of changing the size of the icon to fit the Top Bar, Dash to panel changes the alignment. 
It may not be the problem of Dash to panel but just wanted to point it out.
Thanks

**Comment by charlesg99** [comment]
Ha yes your second screenshot makes a lot more sense now that we can see the Unite buttons. Unite has know compatibility issues with dash to panel, please refer to #631 and #625. Thanks!
