### ISSUE TITLE
Dash to Panel blocks Top Panel Workplace Scroll

### ISSUE THREAD

**Issue by AbuMaia** [home-sweet-gnome/dash-to-panel#811]
Some recent change to DtP has made TPWS unusable on Ubuntu 18.04.3 LTS, Gnome 3.28.2. This wouldn't be much of a problem, since DtP has its own top-panel scroll option, but it does not have the option to turn off the workspace indicator, nor does it offer wrap-around scrolling.

**Comment by jderose9** [comment]
Hi @AbuMaia ! The latest version (v26) of dash to panel offers a “Pass through” option for the panel scroll behavior. Can you see if this resolves your issue?

**Comment by charlesg99** [comment]
Hi! I believe this is another side effect of using a custom panel on the primary monitor (as #790). Since it introduced more issues than anticipated, I think I'll backtrack on this change and try to find another way to adjust the display when using a vertical panel on the primary monitor.

**Comment by jderose9** [comment]
@charlesg99 ah I missed that..

**Comment by AbuMaia** [comment]
@jderose9 I'm using v26, and I don't see this "pass through" option anywhere in the settings. Under "customize scroll panel behavior" is only one setting for delay in milliseconds.

**Comment by AbuMaia** [comment]
I've reverted back to v23 for now. Hopefully this will be fixed soon.

**Comment by charlesg99** [comment]
Hello AbuMaia, this should now be fixed on the master branch if you want to give it a try. Thanks!

**Comment by AbuMaia** [comment]
Hey Charles, that works now. Thank you. :)

**Comment by charlesg99** [comment]
Great! Thanks for the feedback!
