### ISSUE TITLE
v26 left-panel indicators "squish" on hover and clock is now left justified rather than centered

### ISSUE THREAD

**Issue by coreyhuinker** [home-sweet-gnome/dash-to-panel#812]
Upgrading from v25 to v26, I see that the clock, which previously had good spacing and the digits were all centered is now left-justified. Centered is preferred, right justification would be acceptable, but left justification makes the time no longer look like a time.

When hovering on any of the indicators, the spacing changes, which is then restored when you cease hovering.

Reverting to v25 seems to fix the issue.

**Comment by charlesg99** [comment]
Hello, please restart gnome-shell following v26 installation. If it persists, try disabling every extension aside from dash to panel, then restart gnome-shell. I see no such thing on v26:

![Peek 2019-11-17 10-20](https://user-images.githubusercontent.com/33044886/69009527-e9d86600-0923-11ea-92df-cd3ceba03f86.gif)

Thanks!

**Comment by coreyhuinker** [comment]
That worked. 

I re-upgraded, then re-started via `ALT+F2, 'r'`and both issues (scrunching and weird justification on the time display) both went away.
