### ISSUE TITLE
[Feature Request] only show focused window without 'highlight' and 'underline'

### ISSUE THREAD

**Issue by tuberry** [home-sweet-gnome/dash-to-panel#814]
It will look like original panel but with extended features.
Original:
![image](https://user-images.githubusercontent.com/17917040/69079745-9fff9500-0a75-11ea-823a-4a9adeb941d7.png)
d2p with ungroup apps on:
![image](https://user-images.githubusercontent.com/17917040/69079820-c7566200-0a75-11ea-93de-0440afc79ac5.png)
Maybe other launched apps only show icon. Thanks.

**Comment by jderose9** [comment]
I'm sorry, I'm having trouble understanding what behavior you are looking for. Do you simply want to remove the highlight and underline from the active application? Or do you only want to show the currently active window (and if so, why use this extension?)

**Comment by tuberry** [comment]
Never mind. I just think that's a bit wired when there is only one window. Thanks for your reply.
