### ISSUE TITLE
Dash to Panel cover full screen app exiting lock screen

### ISSUE THREAD

**Issue by andreabravetti** [home-sweet-gnome/dash-to-panel#817]
Dash to Panel cover any full screen app exiting lock screen.

You need to exit full screen and then maximize the app again to hide the panel.

What I except is that if the panel is not visible when the screen become locked it should be not visible when I unlock the screen.

Tested with:
- Dash to Panel v 25
- one and two monitors
- Gnome shell 3.32.2 (RHEL 8.1) and 3.34.1 (Fedora 31)

**Comment by charlesg99** [comment]
Hello andreabravetti! Could you add a screenshot of your intellihide settings? When you come back from the lock screen, does the panel over your full screen app hides after a short delay? Seems to be working correctly for me on 3.34 (when I get back from the lock screen, the panel is there but it hides after the set delay). Thanks!

**Comment by andreabravetti** [comment]
Intellihide is disabled:

![Screenshot from 2019-11-20 00-19-44](https://user-images.githubusercontent.com/1644091/69195338-a3555800-0b2b-11ea-899e-59d290678ad6.png)

**Comment by andreabravetti** [comment]
I don't use Intellihide, I like an always on panel.

The problemi is: If I have a maximized window and the panel is not visible before the lock screen I should have the same thing when I unlock the screen.

The problem may be worst if some application have the only way to unmaximize it on a button that become unusable because under the panel. Well, you can usually use a key combination to unmaximize any app but not everyone use keys.

**Comment by charlesg99** [comment]
Ha sorry I didn't understand correctly, I can see what you mean now. I just added a small fix for this on the master branch, could you please [install it](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github) and confirm that it solves the issue on your system? Thanks!

**Comment by andreabravetti** [comment]
Installed from the master branch but it does not resolve the issue

**Comment by charlesg99** [comment]
Indeed... it only works if the full screen app is on the primary monitor, strange. I'll dig deeper a bit.

**Comment by charlesg99** [comment]
Alright, should be good now. Could you please pull/install/restart gnome-shell again to see if it works on your end? Thanks!

**Comment by andreabravetti** [comment]
it works! thank you!

**Comment by andreabravetti** [comment]
Should I close now or it will be closed at release time?

**Comment by charlesg99** [comment]
Great! Yes we can close the issue now (we keep them relative to the master branch). Thanks for the feedback!
