### ISSUE TITLE
Can not come back workspace after enter the applications page

### ISSUE THREAD

**Issue by zd5043039119** [home-sweet-gnome/dash-to-panel#818]
Fedora 31
Gnome 3.34.1
Dash to panel v2.6

Once I activate Dash To Panel, then I enter the application list page through press the win button or move mouse to the top left of my screen, then i cannot return to the workspace. The only thing i can do is reboot!

**Comment by charlesg99** [comment]
Hello Ethan, could you elaborate on why you think this is caused by dash to panel? Did you restart gnome-shell after installing? Do you see errors in your log files? I can't reproduce that. Thanks!

**Comment by zd5043039119** [comment]
Hello Charles, when i disable dash to panel, it goes smoothly,  and 
i think the gnome-shell have been already restarted because i can only reboot the computer to go into  the normal workspace. Also i tried uninstall and reinstall dash to panel 4-5 times, and each time it makes the applications page locked.
And could you tell me which log file should i monitor, thanks

**Comment by bkoropoff** [comment]
@charlesg99 I have the same issue here after upgrading to Fedora 31.

**Comment by bkoropoff** [comment]
Here are the logs that seem relevant:

gnome-shell[236955]: JS ERROR: TypeError: this._scrollAdjustment is undefined
                                              WorkspacesView<@resource:///org/gnome/shell/ui/workspacesView.js:89:1
                                              _newUpdateWorkspacesViews@/home/bkoropoff/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:404:24
                                              show@resource:///org/gnome/shell/ui/workspacesView.js:599:9
                                              show@resource:///org/gnome/shell/ui/viewSelector.js:268:9
                                              _animateVisible@resource:///org/gnome/shell/ui/overview.js:532:9
                                              show@resource:///org/gnome/shell/ui/overview.js:518:9
                                              toggle@resource:///org/gnome/shell/ui/overview.js:639:13
                                              _initializeUI/<@resource:///org/gnome/shell/ui/main.js:208:13

**Comment by charlesg99** [comment]
Ha I see thanks! You're probably using the COPR "gnome-with-patches", which contains unmerged pull requests... The issue should be fixed in the latest master, please refer to #785 for more information. Thanks!

**Comment by zd5043039119** [comment]
Thanks, glad to know how to solve it
