### ISSUE TITLE
Top Gap Bug in v25 and v26

### ISSUE THREAD

**Issue by smujaddid** [home-sweet-gnome/dash-to-panel#820]
I'm using Ubuntu 18.04.3 with Gnome Shell 3.28, and when I updated Dash To Panel to v25 or v26, my workspace area are slightly moved to bottom leaving a gap on the top and moved bottom panel outside screen area. I can move my cursor to that area, but not any application window because it will try to maximize normally.

This bug is not present in the v23. It run just fine. So, for now I will not update to v25/v26 until I can fix this.
I appreciate any helps. Thanks.

![Screenshot from 2019-11-21 09-53-35](https://user-images.githubusercontent.com/2330941/69300130-f1aa4a00-0c44-11ea-9da6-95d847b43d1a.png)

**Comment by charlesg99** [comment]
Hello smujaddid! Thank you for bringing that up. I recently noticed this issue with the flat-remix theme and it is currently fixed on the master branch. Could you please [install it](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github) and let us know if that solves the issue on your system? Thanks!

**Comment by smujaddid** [comment]
@charlesg99 You are right. It has issue with flat-remix-dark shell theme I'm currently using.
I just tried the master branch and it is working as intended (fixed).
Thank you!
