### ISSUE TITLE
when setting panel in center, 9-dots button could align left?

### ISSUE THREAD

**Issue by alex285** [home-sweet-gnome/dash-to-panel#822]
such an option would be nice, and perhaps should be default, because it makes more sense to have the favorites separated from the 9-dots, plus the left space doesnt look "deserted"

![Screenshot from 2019-11-22 00-34-49](https://user-images.githubusercontent.com/11244308/69382647-45a64480-0cc0-11ea-93da-6aabd91afd27.png)

**Comment by charlesg99** [comment]
Hey Alex! Thanks for the suggestion! I agree it would be nice, but it already was proposed in #150. I'd like to think of a way that would solve all of the positioning feature requests we currently have, while making it easy to work with. Nothing so far :)

**Comment by charlesg99** [comment]
Hey! I've started working on the positioning of the taskbar elements and I think I have a solution that will allow a very fine-grained configuration. The only problem that I foresee is the loss of some of the current user settings (only the taskbar and clock positions). Upon updating, users would need to re-position the panel elements. I personally don't think it is a big roadblock, but I'd like to have some input about this. I might be a bit late as I'm almost done with it though :) Here is what I have so far for the settings:
 
![image](https://user-images.githubusercontent.com/33044886/81604329-bab82400-939d-11ea-9259-1738c580a480.png)

This will allow a configuration per monitor and I've removed the clock and the system menu from the panel boxes to allow their individual placements.

@jderose9 Any thoughts? 

Thanks!

**Comment by jderose9** [comment]
@charlesg99 Dude, you are amazing! :1st_place_medal: Overall looks great to me, and nice idea to fit the gears buttons in too.

Do you think there would be any roadblock to mapping the user's old old settings to a set of new settings so they don't lose them?

Personally I think it would be helpful if there was a way to maintain one configuration across monitors - that might be more common than having different configurations per monitor. (A checkbox might be best, or alternately a "Copy to all monitors" button)

I'm confused about how the Left/center/right box are ordered along with the other items which are essentially their contents. Is it that the items below the "box" are within that box?

**Comment by charlesg99** [comment]
Glad you like it! Yeah I thought about doing a small "migration" of the current settings to the new ones and ended up keeping it for last (if it isn't too complicated :) Worst case scenario the user has to reposition the panel elements once after the update (the default positions will remain the same). 

I agree with the monitors sync, I'll add a checkbox for it! As for the boxes, I've removed the activities button, clock and the system menu from their parent and placed them directly in the panel, so they can now be positioned independently. Thanks!

**Comment by charlesg99** [comment]
Alright, the new positioning options are on the `feature-panel-positions` branch! Please try it out, seems stable for me so far! Thanks!

**Comment by alex285** [comment]
@charlesg99 "for Canada!!" https://youtu.be/Y_KapA4j3FU?t=28 :))

**Comment by hotroof** [comment]
I hope @charlesg99 is filthy rich.  And if he's not, he should be.  
@charlesg99 just FYI.... You are a Rockstar.  Thank you, thank you, thank you!
How can I give you money?

**Comment by charlesg99** [comment]
Thanks for the kind words! Glad it's useful!

**Comment by Simon-L** [comment]
Loving it, great!
Wouldn't it make sense for the favorites to be separated from the taskbar? To be honest I misunderstood this issue and thought that's what the branch was about.
The idea is that the favorites being favs, you often end up with the task bar icon AND the favorite next to each other and can be confusing, if they were to move away it wouldn't be as much.

**Comment by charlesg99** [comment]
The `feature-panel-positions` branch was merged, please install the latest master and let us know if you find issues with the new functionalities. Thanks!
