### ISSUE TITLE
Panel intellihide require pressure works only for bottom placement

### ISSUE THREAD

**Issue by high1** [home-sweet-gnome/dash-to-panel#824]
Intellihide pressure required option works only if dash-to-panel is placed on the bottom of the screen. Tested left and top placement, the panel appears immediately when the mouse is near the screen edge.
Compiled manually c9eb2b383a0d38f880c0cf39d3bf97e314a8e383.

**Comment by charlesg99** [comment]
Hello, I'm not sure what is going on yet, since I can't reliably reproduce the issue. It did happen to me once or twice while testing it, but most of the time the pressure works fine for the top and left positions. If you can find a combination of factors making it 100% reproducible, I would appreciate it. I'll keep looking on my end too. Thanks!

**Comment by high1** [comment]
Sorry for the late reply, it's not working for me 100% percent of the time. Arch up to date install,  Wayland, started manually without GDM.

**Comment by YLivay** [comment]
Hello, this happens on a (relatively) fresh installation of Fedora 31 as well. Is there any log or trace I can fetch to help diagnose this? Dash to Panel is amazing, if I can help resolve a hard to reproduce issue im more than happy to help :)

**Comment by charlesg99** [comment]
Hello YLivay! Thank you for the offer! Logs and trace aren't really the issue at this point, what would be helpful is a clear way to consistently reproduce the issue (steps, system info, versions, etc.). E.g. I just spent some time trying to reproduce the issue using dash to panel latest master on gnome-shell 3.34.2, to no avail. Thanks!

**Comment by high1** [comment]
My hunch is that running Gnome on Wayland could be the culprit here... Have you tested that?

**Comment by high1** [comment]
This started working properly on one of Gnome 3.34 minor releases, and works on 3.36. Tested all the possible positions. Thanks!

**Comment by charlesg99** [comment]
Glad to hear it!
