### ISSUE TITLE
wrong floating bar position

### ISSUE THREAD

**Issue by ebiagi** [home-sweet-gnome/dash-to-panel#826]
gnome 3.34.1
dash to panel version 26
the bar position is wrong placed both in the top or down position.
The only correctly displayed theme is flat remix gnome fullpanel

tried with 
flat gnome remix
ant
adapta

Thank you!

![Schermata del 2019-11-25 21-14-15](https://user-images.githubusercontent.com/58190975/69576710-2adc1480-0fcd-11ea-9f9b-7e946e6ac555.png)

**Comment by charlesg99** [comment]
Hello ebiagi, this was recently fixed, please refer to #820. Thanks!
