### ISSUE TITLE
Theming enhancement

### ISSUE THREAD

**Issue by DDoubleU** [home-sweet-gnome/dash-to-panel#827]
Hi,

In the past I've used Docky/Plank in combination with a theme (ImmUnity) which didn't "enclose" the icons entirely, instead they "popped out" of the panel halfway (I've attached an image to demonstrate this behaviour). All themes for dash-to-panel I've encountered seem to include the icons entirely. Is it possible to achieve the same behaviour as seen in the screenshot?

Thank in advance!

![plank](https://user-images.githubusercontent.com/21154541/69612931-f69a3f80-1030-11ea-9682-7d0e3e8c8596.png)

**Comment by charlesg99** [comment]
Hello, let's keep the "icons bigger than the panel" discussion in #733. Thanks!
