### ISSUE TITLE
Wrong grouping when Slack is running

### ISSUE THREAD

**Issue by zazy** [home-sweet-gnome/dash-to-panel#828]
When I have Slack running, all Google Chrome running instances ar grouped under the Slack Icon even if I quit Slack. I have attached an image where there is a browser instance (the one I'm submitting this issue), a WhatsApp instance (It is an "app like" running Chrome instance of web.whatsapp.com), a Google Chrome DevTools window and a Slack window and all are grouped under the same icon. All instances had been launched from a Dash to Dock panel.
Ubuntu 18.04 LTS

![Schermata da 2019-11-30 17-41-51](https://user-images.githubusercontent.com/10668286/69903475-fa63f400-1399-11ea-84f6-04de6c41031c.png)

**Comment by charlesg99** [comment]
Hello zazy, sounds like a StartupWMClass problem (i.e. #802). Do you see the same problem on the default gnome-shell dash (in the overview) after disabling dash-to-panel? How did you install Slack? Thanks!

**Comment by charlesg99** [comment]
Hello zazy, did you get a chance to play with the StartupWMClass?

**Comment by zazy** [comment]
Hello @charlesg99 sorry for not returning on this but for some reason Github did not notified me about your reply. I reported this bug to Slack team too and turned out it is a known issue with the snap package of slack. Installing Slack without snap solved the issue. 
Sorry again.
