### ISSUE TITLE
Incorrectly shows a 'GS Connect' icon on the panel

### ISSUE THREAD

**Issue by jasiralavi** [home-sweet-gnome/dash-to-panel#829]
Hi — I'm on Ubuntu 19.10 and I use GS Connect, Dash to Panel, User Themes and a few other extensions.
 
Recently I noticed that whenever GS Connect starts an icon of an inactive device (from the list of devices available on GS Connect) shows up in the panel. This happens irrespective of whether it is set to show in the 'Panel' or  'User Menu' (GS Connect settings > Display Mode). If I open the extension's settings and toggle the 'Display mode', the icon disappears.

This icon appears in addition to the connected device icon, that is if I have a connected device while starting up GS Connect. The connected devices appear correctly as per the 'Display mode' setting described above.

This doesn't happen when the Dash to Panel extension is disabled.

I reported this in the GS Connect extension's github page. However, this is what they had to say:

> dash-to-panel is changing the visibility of PanelButtons, so this isn't an issue we can fix in GSConnect unfortunately.

Issue link: https://github.com/andyholmes/gnome-shell-extension-gsconnect/issues/725
(Screenshots shared in this page might help)

**Comment by ferdnyc** [comment]
Just for clarity's sake, that quote should be:
> Sounds like dash-to-panel is changing the visibility of PanelButtons, so this isn't an issue we can fix in GSConnect unfortunately.

We haven't looked at dash-to-panel at all, other than what was reported in the linked issue, so any statements about what it is or isn't doing are educated guesses at best.

**Comment by charlesg99** [comment]
Thanks guys, yes this is another issue related to using our custom panel on the primary monitor. I'll update the issue when that change is reverted.

**Comment by charlesg99** [comment]
Hello jasiralavi, sorry about the delay, but I finally got time to work on the issue. Could you please try the master branch and see if the icon now behaves correctly? Thanks!
