### ISSUE TITLE
Crash on wake from sleep

### ISSUE THREAD

**Issue by jkidd-be** [home-sweet-gnome/dash-to-panel#830]
Finally got around to testing the crash, log below. I updated to v26 with the same issue occurring

clutter_input_device_get_mapping_mode: assertion
'clutter_input_device_get_device_type (device) == CLUTTER_TABLET_DEVICE'
failed
clutter_input_device_get_mapping_mode: assertion
'clutter_input_device_get_device_type (device) == CLUTTER_TABLET_DEVICE'
failed
GNOME Shell started at Fri Nov 15 2019 12:23:22 GMT-0500 (EST)
Fontconfig warning: "/etc/fonts/fonts.conf", line 86: unknown element
"blank"
Window manager warning: last_focus_time (1291707993) is greater than
comparison timestamp (1291707961).  This most likely represents a buggy
client sending inaccurate timestamps in messages such as
_NET_ACTIVE_WINDOW.  Trying to work around...
JS LOG: loading user theme:
/Volumes/vfx-san/home352/jkidd/.themes/Adapta-LightBlue-Nokto-Eta/gnome-shell/gnome-shell.css
Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be
found.
JS LOG: loading user theme:
/Volumes/vfx-san/home352/jkidd/.themes/Adapta-Amber-Nokto-Eta/gnome-shell/gnome-shell.css
Window manager warning: last_focus_time (1292387012) is greater than
comparison timestamp (1292386998).  This most likely represents a buggy
client sending inaccurate timestamps in messages such as
_NET_ACTIVE_WINDOW.  Trying to work around...
Window manager warning: last_focus_time (1292463575) is greater than
comparison timestamp (1292463560).  This most likely represents a buggy
client sending inaccurate timestamps in messages such as
_NET_ACTIVE_WINDOW.  Trying to work around...
clutter_actor_set_child_below_sibling: assertion 'sibling->priv->parent ==
self' failed
JS WARNING:
[/Volumes/vfx-san/home352/jkidd/.local/share/gnome-shell/extensions/
workspace-grid@mathematical.coffee.gmail.com/extension.js 456]: assignment
to undeclared variable _workspaceSwitcherPopup
JS LOG: [System monitor] applet disable
JS LOG: loading user theme:
/Volumes/vfx-san/home352/jkidd/.themes/Adapta-Amber-Nokto-Eta/gnome-shell/gnome-shell.css
JS LOG: [System monitor] applet enabling
JS LOG: error reading: /sys/devices/virtual/thermal/thermal_zone0/temp
JS LOG: [System monitor] applet enabling done
^Nclutter_actor_set_child_below_sibling: assertion 'sibling->priv->parent
== self' failed
JS LOG: [System monitor] applet disable
JS ERROR: TypeError: Style is null
Pie<._draw@
/Volumes/vfx-san/home352/jkidd/.local/share/gnome-shell/extensions/
system-monitor@paradoxxx.zero.gmail.com/extension.js:616
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
BoxPointer<._allocate@resource:///org/gnome/shell/ui/boxpointer.js:231
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
LayoutManager<._init/<@resource:///org/gnome/shell/ui/layout.js:207

clutter_input_device_get_mapping_mode: assertion
'clutter_input_device_get_device_type (device) == CLUTTER_TABLET_DEVICE'
failed
clutter_input_device_get_mapping_mode: assertion
'clutter_input_device_get_device_type (device) == CLUTTER_TABLET_DEVICE'
failed
clutter_input_device_get_mapping_mode: assertion
'clutter_input_device_get_device_type (device) == CLUTTER_TABLET_DEVICE'
failed
clutter_input_device_get_mapping_mode: assertion
'clutter_input_device_get_device_type (device) == CLUTTER_TABLET_DEVICE'
failed
clutter_input_device_get_mapping_mode: assertion
'clutter_input_device_get_device_type (device) == CLUTTER_TABLET_DEVICE'
failed
clutter_input_device_get_mapping_mode: assertion
'clutter_input_device_get_device_type (device) == CLUTTER_TABLET_DEVICE'
failed
clutter_input_device_get_mapping_mode: assertion
'clutter_input_device_get_device_type (device) == CLUTTER_TABLET_DEVICE'
failed
clutter_input_device_get_mapping_mode: assertion
'clutter_input_device_get_device_type (device) == CLUTTER_TABLET_DEVICE'
failed
clutter_input_device_get_mapping_mode: assertion
'clutter_input_device_get_device_type (device) == CLUTTER_TABLET_DEVICE'
failed
clutter_input_device_get_mapping_mode: assertion
'clutter_input_device_get_device_type (device) == CLUTTER_TABLET_DEVICE'
failed
clutter_input_device_get_mapping_mode: assertion
'clutter_input_device_get_device_type (device) == CLUTTER_TABLET_DEVICE'
failed
clutter_input_device_get_mapping_mode: assertion
'clutter_input_device_get_device_type (device) == CLUTTER_TABLET_DEVICE'
failed
clutter_input_device_get_mapping_mode: assertion
'clutter_input_device_get_device_type (device) == CLUTTER_TABLET_DEVICE'
failed
clutter_input_device_get_mapping_mode: assertion
'clutter_input_device_get_device_type (device) == CLUTTER_TABLET_DEVICE'
failed
JS WARNING: [/usr/share/gnome-shell/extensions/
apps-menu@gnome-shell-extensions.gcampax.github.com/extension.js 367]:
octal literals and octal escape sequences are deprecated
JS WARNING: [/usr/share/gnome-shell/extensions/
apps-menu@gnome-shell-extensions.gcampax.github.com/extension.js 367]:
octal literals and octal escape sequences are deprecated
JS WARNING: [/usr/share/gnome-shell/extensions/
apps-menu@gnome-shell-extensions.gcampax.github.com/extension.js 367]:
octal literals and octal escape sequences are deprecated
JS LOG: loading user theme:
/Volumes/vfx-san/home352/jkidd/.themes/Adapta-Amber-Nokto-Eta/gnome-shell/gnome-shell.css
JS ERROR: Exception in callback for signal: updated: Error: Type name
Gjs_DashToPanel-PreviewMenu is already registered
GObjectMeta<._construct
@resource:///org/gnome/gjs/modules/overrides/GObject.js:145
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
Class.prototype._construct/newClass
@resource:///org/gnome/gjs/modules/lang.js:213
Class@resource:///org/gnome/gjs/modules/lang.js:161
defineClass@
/Volumes/vfx-san/home352/jkidd/.local/share/gnome-shell/extensions/
dash-to-panel@jderose9.github.com/utils.js:53
@/Volumes/vfx-san/home352/jkidd/.local/share/gnome-shell/extensions/
dash-to-panel@jderose9.github.com/windowPreview.js:648
@/Volumes/vfx-san/home352/jkidd/.local/share/gnome-shell/extensions/
dash-to-panel@jderose9.github.com/taskbar.js:48
@/Volumes/vfx-san/home352/jkidd/.local/share/gnome-shell/extensions/
dash-to-panel@jderose9.github.com/panel.js:36
@/Volumes/vfx-san/home352/jkidd/.local/share/gnome-shell/extensions/
dash-to-panel@jderose9.github.com/panelManager.js:32
@/Volumes/vfx-san/home352/jkidd/.local/share/gnome-shell/extensions/
dash-to-panel@jderose9.github.com/extension.js:35
initExtension@resource:///org/gnome/shell/ui/extensionSystem.js:221
enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:110
enableAllExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:345
enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:344
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:372
_emit@resource:///org/gnome/gjs/modules/signals.js:124
SessionMode<._sync@resource:///org/gnome/shell/ui/sessionMode.js:205
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
SessionMode<.popMode@resource:///org/gnome/shell/ui/sessionMode.js:174
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
ScreenShield<._continueDeactivate
@resource:///org/gnome/shell/ui/screenShield.js:1210
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
ScreenShield<.deactivate/<@resource:///org/gnome/shell/ui/screenShield.js:1195
AuthPrompt<.finish@resource:///org/gnome/shell/gdm/authPrompt.js:585
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
UnlockDialog<.finish@resource:///org/gnome/shell/ui/unlockDialog.js:147
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
ScreenShield<.deactivate@resource:///org/gnome/shell/ui/screenShield.js:1194
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
ScreenShield<._init/</<@resource:///org/gnome/shell/ui/screenShield.js:541
_emit@resource:///org/gnome/gjs/modules/signals.js:124
_convertToNativeSignal
@resource:///org/gnome/gjs/modules/overrides/Gio.js:129

JS ERROR: TypeError: Style is null
Pie<._draw@
/Volumes/vfx-san/home352/jkidd/.local/share/gnome-shell/extensions/
system-monitor@paradoxxx.zero.gmail.com/extension.js:616
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
BoxPointer<._allocate@resource:///org/gnome/shell/ui/boxpointer.js:231
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
LayoutManager<._init/<@resource:///org/gnome/shell/ui/layout.js:207

_Originally posted by @jkidd-be in https://github.com/home-sweet-gnome/dash-to-panel/issues/765#issuecomment-554693742_

**Comment by charlesg99** [comment]
Hello jkidd-be! Does the same happen if you disable your other extensions and then restart gnome-shell? I see no dash-to-panel related crash in your log. Thanks!

**Comment by jkidd-be** [comment]
I tried disabling everything but dash but it will still crash.

**Comment by jderose9** [comment]
@jkidd-be It looks to me that the system-monitor extension is causing the issue. Could you post an updated log with the other extensions disabled?

**Comment by jkidd-be** [comment]
I will try without the system monitor, I also updated to v26. 

Will let you know in a day or two. 

Thanks
