### ISSUE TITLE
"Move to current Workspace" Shortcut

### ISSUE THREAD

**Issue by sojusnik** [home-sweet-gnome/dash-to-panel#831]
Would be handy, if we could get a configurable mouse shortcut (f.i all combinations with shift + middle and left click, like in the "actions" tab in the settings) to move a window in the preview to the current workspace.

Other than that, this extension is so thought out I'm not getting tired of thanking you!

**Comment by charlesg99** [comment]
Hello sojusnik! We already have a similar functionality using the contextual menu of the window preview (see #654 for more information). Do you think we also need a dedicated click action? Thanks!

**Comment by sojusnik** [comment]
Hey @charlesg99 :)
I'm aware of the contextual menu, but a click action would improve the workflow significantly. I would prefer to use "shift+left click" to move a window to the current workspace.

**Comment by sojusnik** [comment]
Still thinking that a dedicated click action would be handy.

What about adding the click action settings (the one where you can define the actions of shift+click, middle click, shift+middle click) to the preview settings instead of "Middle click on the preview to close the window" and let the user decide how those click actions should behave?
