### ISSUE TITLE
All Gnome panels drawn underneath maximized app after exiting full screen in FF, VLC

### ISSUE THREAD

**Issue by danvim** [home-sweet-gnome/dash-to-panel#832]
I am just a Gnome extension user, not a developer, so I might not be using the correct terms or I might not mean completely what I write, but based on what I see, I can summarize the following:

### Expected

Exiting full screen in FF should not affect panel draw order.

### Actual

Exiting full screen in FF with Dash to Panel enabled would have FF drawn over all Gnome panels.

### Reproduction

1. Open FF71 in maximized mode
2. Enter full screen in an HTML5 video
3. Exit full screen
4. Attempt to use any Gnome panels:
    - iBus IME selection panel cannot be displayed over FF
    - Cannot bring up hidden Dash to Panel by mouse cursor nor Hotkey, since Panel is drawn underneath FF.
    - Other apps are drawn correctly in order, just FF is on top of everything.
    - Restarting FF would fix the issue.

### What I am Using

- Dash to Panel 26
- Firefox 71

**Normal View of my IME selection panel.** I cannot capture the problematic view, since when I press Ctrl+Shift+Prtsc, the IME selection panel is drawn over FF normally for the screen capture. Just imagine the black box missing.

![image](https://user-images.githubusercontent.com/5255292/70741693-d8ce1980-1d56-11ea-8d81-de284260161f.png)

As a way around this, I am currently using Super to see all activities or Alt+Tab for switching between apps. Restarting FF helps redraw everything on the screen in the correct order. I do this if I want to use my IME on my browser.

---

EDIT:

List of my extensions:

- Dash to Panel
- Docker integration (adds tray)
- Noannoyance (filters notification)
- User themes

I am able to replicate the behavior in VLC.  https://github.com/home-sweet-gnome/dash-to-panel/issues/832#issuecomment-565718419

I have tried restarting the computer in between trials to test behavior after fresh logins.

---

Love the extension BTW.

**Comment by danvim** [comment]
After some Gnome extension isolation testing, enabling and disabling various extensions, I cannot replicate my problem. So I'm closing my issue until I can find a way to reproduce my problem.

**Comment by danvim** [comment]
I found that by enabling both Unite and Dash to Panel, restarting the system and following the above steps would generate that behavior.

I am not sure if I should even reopen this issue, since the problem was generated by using 2 possibly incompatible extensions to start with. I use Unite to hide the maximized window decoration.

**Comment by danvim** [comment]
I am able to replicate my problem with VLC by entering and exiting full screen. My IME selection window is hidden when I type in a search box in VLC when maximized

**Comment by danvim** [comment]
@jderose9 Thanks for your time reading my issue. I'm still a looking for a detailed way to replicate the problem from a fresh login, but I can only do it passively when I use my computer. So far, FF and VLC may generate the error. I think all apps that can go into full screen may potentially experience this problem.

**Comment by charlesg99** [comment]
Gonna close this and I encourage you to open the issue to the [Mutter's maintainer](https://gitlab.gnome.org/GNOME/mutter/-/issues), if you get to reproduce this reliably. Thanks!
