### ISSUE TITLE
Launch by number should be default

### ISSUE THREAD

**Issue by dandv** [home-sweet-gnome/dash-to-panel#835]
I've just installed the extension, primarily to move the clock out of the center, and found that my [favorite Super+0..9 shortcuts](https://askubuntu.com/questions/813262/which-desktop-environments-allow-switching-among-windows-with-supernumbers) no longer worked.

I [figured out later](https://github.com/home-sweet-gnome/dash-to-panel/pull/833) for to re-enable them, but to preserve compatibility with GNOME, these shortctus should not be disabled in the first place.

**Comment by charlesg99** [comment]
> and found that my favorite Super+0..9 shortcuts **no longer worked**

Hello dandv, could you elaborate on that? We (hopefully) don't disable other existing hotkeys, if any (there are similar shortcuts since gnome-shell 3.32). Thanks!

**Comment by dandv** [comment]
Right after I installed the extension, pressing GNOME's default Super+0..9 shortcuts did nothing.

My guess is that the extension has them off by default, so upon installation, it also disables them to match the "off" setting.

**Comment by charlesg99** [comment]
Hello Dan, as I said, the extension doesn't disable the gnome-shell shortcuts, unless the hotkeys are enabled. We also re-enable the gnome-shell shortcuts if the hotkeys are disabled. Not sure how you ended up in this situation when installing, but it was unintended.

What gnome-shell version are you on? Can you reproduce the issue? If you disable the extension hotkeys, then restart gnome-shell, are gnome-shell shortcuts working correctly?

Thanks!

**Comment by charlesg99** [comment]
Closing for now, we can reopen if need be. Thanks!
