### ISSUE TITLE
Extension is incompatible with gnome shell 3.35.2

### ISSUE THREAD

**Issue by wolfgangwuerfl** [home-sweet-gnome/dash-to-panel#836]
Since a last emerge on my gentoo system,  with updated gnome-shell to version 3.35.2, the extionsion is broken.

For example:
Dez 15 08:29:58 gentoo gnome-shell[7304]: Usage of object.actor is deprecated for PanelCorner
                                          get@resource:///org/gnome/shell/ui/environment.js:269:29
                                          _init@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panel.js:140:13
                                          _createPanel@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:286:21
                                          enable@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:74:29
                                          _enable@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:94:5
                                          enable@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:62:5
                                          _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:148:13
                                          loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:277:21
                                          _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:487:13
                                          collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
                                          _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:466:9
                                          _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:496:13
                                          _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:527:13
                                          init@resource:///org/gnome/shell/ui/extensionSystem.js:48:9
                                          _initializeUI@resource:///org/gnome/shell/ui/main.js:242:5
                                          start@resource:///org/gnome/shell/ui/main.js:138:5
                                          @<main>:1:31
Dez 15 08:29:58 gentoo gnome-shell[7304]: Usage of object.actor is deprecated for PanelCorner
                                          get@resource:///org/gnome/shell/ui/environment.js:269:29
                                          _init@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panel.js:143:13
                                          _createPanel@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:286:21
                                          enable@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:74:29
                                          _enable@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:94:5
                                          enable@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:62:5
                                          _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:148:13
                                          loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:277:21
                                          _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:487:13
                                          collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
                                          _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:466:9
                                          _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:496:13
                                          _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:527:13
                                          init@resource:///org/gnome/shell/ui/extensionSystem.js:48:9
                                          _initializeUI@resource:///org/gnome/shell/ui/main.js:242:5
                                          start@resource:///org/gnome/shell/ui/main.js:138:5
                                          @<main>:1:31
Dez 15 08:29:58 gentoo gnome-shell[7304]: Usage of indicator.indicators is deprecated for Indicator
                                          get indicators@resource:///org/gnome/shell/ui/panelMenu.js:213:25
                                          enable@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panel.js:208:13
                                          _createPanel@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:290:9
                                          enable@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:74:29
                                          _enable@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:94:5
                                          enable@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:62:5
                                          _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:148:13
                                          loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:277:21
                                          _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:487:13
                                          collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
                                          _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:466:9
                                          _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:496:13

**Comment by charlesg99** [comment]
Hello wolfgangwuerfl, thanks for bringing that up. I tried 3.35.2 and made some adjustments on the master branch. Let us know if that works for you and if find more issues before 3.36 hits.

**Comment by alex285** [comment]
all working here!!

**Comment by wolfgangwuerfl** [comment]
Thanks @charlesg99 - Works fine now!! Great work, thank you very much!

**Comment by charlesg99** [comment]
My pleasure, thanks for the feedback!
