### ISSUE TITLE
Visual artifact when moving to browser workspace with keyboard shortcut

### ISSUE THREAD

**Issue by fregonics** [home-sweet-gnome/dash-to-panel#840]
![bug-dash-to-panel](https://user-images.githubusercontent.com/19842670/71426148-5a417800-2684-11ea-9633-22ec371ea59c.gif)

### When i go to the workspace that has the browser with the keyboard shortcut the indicator of what workspace i am blinks before disappearing.

I didn't see this happening with anybody else, but consistently happens in my setup, on master, and even on the past release.

**My setup:**
Fedora 31
Gnome 3.34.2
*I don't have any other extension active

**How to reproduce**
I don't understand exactly how it works, or exact ways to trigger it, but usually watching youtube for more then 30 seconds make it start happening, but its not the only way to trigger it.
*It only happens when intelihide is set on

**Other Information:**

-  I used dash to panel from the branch of the vertical panel on fedora 30 (gnome 3.32) and this didnt happen.
-  Closing firefox and openning it again makes it stop happening until its triggered again
-  When its triggered, intelihide stops working on trigger workspace (as shown)
-  The position of the workspace doesn't matter

UPDATE: I noticed i can't reproduce it in Wayland

**Comment by charlesg99** [comment]
Hello fregonics, thank you for the report! I spent some time trying to reproduce the issue, without success (gnome 3.34.2, xorg). Can you see errors in your log when this happens (`journalctl /usr/bin/gnome-shell`)? Please stay up to date with the master branch and try to keep an eye open to pinpoint the triggering factor. Thanks!

**Comment by lungtendo** [comment]
I would like to report that this happens to me usually on Firefox window running Ubuntu 18.04 and Gnome 3.28. I will try to capture some screens and share it here the next time.

**Comment by fregonics** [comment]
Hi. I started a new Gnome session and executed the following steps

- [x]  Opened Firefox
- [x]  Opened Gnome-terminal in another window
- [x]  Played a video on youtube for 30 seconds on full screen with firefox
- [x]  Moved to the workspace to the bottom
- [x]  Moved back again to the workspace on the top
- [x]  The bug happened

Here is the result from journalctl 
dez 31 15:30:59 smith gnome-shell[14915]: GNOME Shell started at Tue Dec 31 2019 15:30:53 GMT-0300 (-03)
dez 31 15:30:59 smith gnome-shell[14915]: Registering session with GDM
dez 31 15:31:38 smith gnome-shell[14915]: Invalid result meta returned from search provider firefox.desktop
dez 31 15:31:38 smith gnome-shell[14915]: Invalid result meta returned from search provider firefox.desktop
dez 31 15:31:38 smith gnome-shell[14915]: Invalid result meta returned from search provider firefox.desktop
dez 31 15:31:46 smith gnome-shell[14915]: Invalid result meta returned from search provider firefox.desktop
dez 31 15:31:46 smith gnome-shell[14915]: Invalid result meta returned from search provider firefox.desktop
dez 31 15:31:47 smith org.gnome.Terminal.desktop[14915]: # _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
dez 31 15:31:47 smith org.gnome.Terminal.desktop[14915]: # Theme parsing error: gtk.css:1446:32: Expected ')' at end of 'image'
dez 31 15:31:47 smith org.gnome.Terminal.desktop[14915]: # Theme parsing error: gtk.css:1446:33: Expected semicolon
dez 31 15:31:47 smith org.gnome.Terminal.desktop[14915]: # _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
dez 31 15:31:47 smith org.gnome.Terminal.desktop[14915]: # watch_fast: "/org/gnome/terminal/legacy/" (establishing: 0, active: 0)
dez 31 15:31:47 smith org.gnome.Terminal.desktop[14915]: # unwatch_fast: "/org/gnome/terminal/legacy/" (active: 0, establishing: 1)
dez 31 15:31:47 smith org.gnome.Terminal.desktop[14915]: # watch_established: "/org/gnome/terminal/legacy/" (establishing: 0)
dez 31 15:33:33 smith gnome-shell[14915]: Invalid result meta returned from search provider firefox.desktop
dez 31 15:33:33 smith org.gnome.Terminal.desktop[14915]: # _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
dez 31 15:33:33 smith gnome-shell[14915]: Invalid result meta returned from search provider firefox.desktop
dez 31 15:33:33 smith org.gnome.Terminal.desktop[14915]: # Theme parsing error: gtk.css:1446:32: Expected ')' at end of 'image'
dez 31 15:33:33 smith org.gnome.Terminal.desktop[14915]: # Theme parsing error: gtk.css:1446:33: Expected semicolon
dez 31 15:33:34 smith org.gnome.Terminal.desktop[14915]: # _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
dez 31 15:33:34 smith org.gnome.Terminal.desktop[14915]: # watch_fast: "/org/gnome/terminal/legacy/" (establishing: 0, active: 0)
dez 31 15:33:34 smith org.gnome.Terminal.desktop[14915]: # unwatch_fast: "/org/gnome/terminal/legacy/" (active: 0, establishing: 1)
dez 31 15:33:34 smith org.gnome.Terminal.desktop[14915]: # watch_established: "/org/gnome/terminal/legacy/" (establishing: 0)

**Comment by charlesg99** [comment]
Thanks fregonics, I got it to reproduce with your steps (had to switch workspaces while the firefox video is in fullscreen). The same glitch [happens on the default gnome-shell desktop](https://imgur.com/a/qDMCVL1) for me though, so it looks more like a mutter/firefox bug than a dash to panel one.

**Comment by charlesg99** [comment]
Seems related: https://gitlab.gnome.org/GNOME/gnome-shell/issues/2071

**Comment by fregonics** [comment]
Yep. I do not know how gnome works but it really seems to be related in some way.
I'll try to compile gnome-shell and report there if it still happens on master.

Thank you for the help!
