### ISSUE TITLE
[Feature Request] Create a second panel, keep original top panel

### ISSUE THREAD

**Issue by ipsingh06** [home-sweet-gnome/dash-to-panel#842]
Would it be possible to add an option to create a second panel and keep the original top panel as is. I would love to use Dash To Panel as a replacement for Window List, which doesn't allow controlling the placement of the panel or reordering the icons.

Thanks.

**Comment by jderose9** [comment]
Hi @ipsingh06 ! This was already requested as #457. I would recommend commenting there/subscribing to that issue for updates. Thanks!
