### ISSUE TITLE
Show date for left/right panel

### ISSUE THREAD

**Issue by ipsingh06** [home-sweet-gnome/dash-to-panel#843]
Hi,

The date disappears when left or right panel position is chosen. Is there an option to bring it back?

Thanks!

Top: ![d2p_date_2](https://user-images.githubusercontent.com/12875506/71742946-17b43400-2e18-11ea-95bd-36a67b974bf5.png)
Left: ![d2p_date_1](https://user-images.githubusercontent.com/12875506/71742936-1420ad00-2e18-11ea-8c5b-c1b6f4d014ef.png)

**Comment by charlesg99** [comment]
Hello ipsingh06! 

Yes by default we are removing the date part of the clock when the panel is vertical and there currently is no option to bring it back. I played around with it to keep the date when it fits horizontally:
![image](https://user-images.githubusercontent.com/33044886/71772634-fa688e00-2f1b-11ea-840f-c8c3b52f68df.png)

What I wonder now is if we should stack the date on top of the time if it fits: 
![image](https://user-images.githubusercontent.com/33044886/71772646-26840f00-2f1c-11ea-8b13-24b85cad3b59.png)

And keep the current behavior when the panel is small:
![image](https://user-images.githubusercontent.com/33044886/71772652-74991280-2f1c-11ea-8b20-f4c345c1c28c.png)

This would be a "breaking change", so we would need to add an option for it I'm afraid. 

@jderose9 Any thoughts?

**Comment by jderose9** [comment]
@charlesg99 I like the stacking - but are we able to determine if the date could fit always or not? Showing the date on "Jan 9" but then not on "Jan 10" (because it is wider) doesn't sound great. I guess  if we added as an option we could just leave it up to the user to turn it on/off?

**Comment by charlesg99** [comment]
@jderose9 Good point. At the moment it is dynamically determined when setting the clock's text... So, as you say, there is no guarantee that the date would always show up. If we only needed to support one language, it would be reasonable to check against its widest possible date (instead of the current date), but I don't think it is a viable option with all of the available locales. Hmmm...

**Comment by jderose9** [comment]
@charlesg99 What do you think about having a simple toggle for whether the date should be shown? We could have separate settings dynamically displayed in the UI for horizontal and vertical mode, so the user's preference for each would be retained (defaulted on in horizontal and off in vertical)?

**Comment by charlesg99** [comment]
Yes that would work for the settings, but even then, won't we have the same problem as you mentioned with a panel width that could fit "Jan 9" and not "Jan 10"? Also, do you have a suggestion on where we should put in this new setting? (I'm running low on ideas about where to cram in new ones :joy:)

Something like this could work for more clock options, but this isn't really associated to the clock's location...
 
![image](https://user-images.githubusercontent.com/33044886/71946759-bfbf5980-3198-11ea-9350-af6b23abf26c.png)

Thanks!

**Comment by charlesg99** [comment]
I added the dynamic date on the vertical panel, without a setting. I think it makes sense and, in retrospect, I should've set it this way initially... I would say let's add a setting only if existing users don't like it. What do you think?

**Comment by jderose9** [comment]
@charlesg99 Sounds good to me. Yes, the number of config settings is a bit frustrating, especially when it comes to trying to test meaningful permutations.
