### ISSUE TITLE
Conext Menu of "applications" icon contains hard links to applications

### ISSUE THREAD

**Issue by daniel-wtd** [home-sweet-gnome/dash-to-panel#847]
Hi,

thank you so much for this extension, it's a must have for me.

When using (right click / context click) on the applications menu, you can choose from some "short links". For now, these seem to be fixed and if an application is not present, the link will be broken. This can happen for different applications like:

- gnome-terminal, if some other terminal is used
- gnome-logs, if it is not installed
- system monitor, if gnome-usage is used

I recommend, to either make them configurable or at least selectable.

thank you again for your time and effort. :)

**Comment by charlesg99** [comment]
Hello daniel-wtd! Good idea, I never thought of it since we are linking to applications that (normally) come with a default gnome installation, but it is true that nothing is stopping users to uninstall those. I'll look into adding a way to customize the context menu entries. Thanks!

**Comment by charlesg99** [comment]
Thanks to @tper0700 who completed this! 

Until it is added to the FAQ, please see https://github.com/home-sweet-gnome/dash-to-panel/pull/947#discussion_r411088529 for how to configure the entries using dconf.
