### ISSUE TITLE
Request: Windows 7-style text-only previews

### ISSUE THREAD

**Issue by madmadman** [home-sweet-gnome/dash-to-panel#848]
![windows7](https://user-images.githubusercontent.com/11094850/72221806-d0622d80-3512-11ea-9f9a-e135f434fb2f.png)
I like it like this more than graphical previews.

**Comment by boyfer** [comment]
This option already exist as part of the contextual menu. I don't remember how this works on Windows, is it hover?

![image](https://user-images.githubusercontent.com/1026457/89100715-46d56700-d434-11ea-8ca4-b3380dc8383c.png)
