### ISSUE TITLE
Gnome extension "Volume Scroll" not working on Dash to Panel

### ISSUE THREAD

**Issue by nooncat** [home-sweet-gnome/dash-to-panel#849]
Gnome extension "Volume Scroll" not working on Dash to Panel.
Please, make it working with Dash to Panel or implement same behavior in Dash to Panel.

**Comment by charlesg99** [comment]
Hello nooncat, please install the laster master, the Volume Scroll extension should work properly. Please see #811 for more information. Thanks!

**Comment by nooncat** [comment]
Hi! After installing DtP from master Volume Scroll extension is working properly. 
Is it possible to add “Pass through” behavior for application icons?

**Comment by nooncat** [comment]
@charlesg99 ?

**Comment by charlesg99** [comment]
Hello nooncat, did you look at the options? There already is a pass through:

![image](https://user-images.githubusercontent.com/33044886/72832954-ceefde00-3c53-11ea-89f1-4b037e7efb1d.png)

Thanks!

**Comment by nooncat** [comment]
Hi, charlesg99. Thanks for answering
Yes a tried these options. No luck :(
Same options like on screenshots not working

**Comment by charlesg99** [comment]
Ha sorry I misunderstood what you meant. Unfortunately we can't dynamically detect listeners attached to the panel by other extensions, so I added the option to change the volume to dash to panel. Could you try it by [installing](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github) the latest master branch? You'll have to disable the Volume Scroll extension though, otherwise you'll trigger the action twice. Thanks!

**Comment by nooncat** [comment]
Charlesg99, thanks for implementing this feature! It work good.
But this feature have some problem with imwheel utility(i use it for increasing scroll speed)
Without imwheel volume adjusting on panel work same as on volume icon.
But with imwheel it start lagging. In same time adjusting volume on volume icon work good and scroll speed is increasing by imwheel.
Can you advise something, please.
Thank you!

**Comment by charlesg99** [comment]
Hello nooncat, I added a fix to ignore the scroll timeout when the delay is set to 0. I haven't tested it, but this is my best guess... Could you pull/install/restart and see if that helps? Thanks!

**Comment by nooncat** [comment]
Hi, charlesg99
Now it works perfect!
You are the best! Thank you!
