### ISSUE TITLE
Error: Expected type interface for Argument 'file' but got type 'undefined'

### ISSUE THREAD

**Issue by alex285** [home-sweet-gnome/dash-to-panel#850]
on GNOME 3.35.3 (actually master, but that error was happening on 3.35.3 release too)
```
JS ERROR: Extension dash-to-panel@jderose9.github.com: Error: Expected type interface for Argument 'file' but got type 'undefined'
_enable@/home/me/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:74:9
enable@/home/me/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:62:5
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:148:13
_onEnabledExtensionsChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:412:13
```

**Comment by alex285** [comment]
now i opened the issue, i actually looked on the code and noticed it checks for Ubuntu Dock, that i had installed but disabled, so i removed the Ubuntu Dock, the extension loads now, however it crashes when we open the overview

```
Usage of object.actor is deprecated for PanelCorner
get@resource:///org/gnome/shell/ui/environment.js:269:29
destroy@/home/me/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/transparency.js:62:13
disable@/home/me/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panel.js:431:13
disable/<@/home/me/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:236:13
disable@/home/me/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:223:9
disable@/home/me/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:116:5
_callExtensionDisable@resource:///org/gnome/shell/ui/extensionSystem.js:95:13
_onEnabledExtensionsChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:420:13
_onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:417:9

```

**Comment by charlesg99** [comment]
Hey alex285! I added a fix to master for the PanelCorner warning, but how did you get gnome 3.53.3 on Ubuntu? I'd like to install that to reproduce the file issue. Thanks!

**Comment by alex285** [comment]
hello @charlesg99! i didn't use Ubuntu, i used Fedora and: https://github.com/micheleg/dash-to-dock/tree/ubuntu-dock; btw i didn't tried yet your patch so i leave it open, i will check later (gonna work anyway!) thank you!!

**Comment by alex285** [comment]
a new error, but just to remind you im running GNOME Shell from master (not the 3.35.3 in Fedora)
```
JS ERROR: TypeError: this._scrollAdjustment is undefined
_init@resource:///org/gnome/shell/ui/workspacesView.js:86:1
_newUpdateWorkspacesViews@/home/me/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:449:24
show@resource:///org/gnome/shell/ui/workspacesView.js:587:9
show@resource:///org/gnome/shell/ui/viewSelector.js:276:9
_animateVisible@resource:///org/gnome/shell/ui/overview.js:574:9
show@resource:///org/gnome/shell/ui/overview.js:560:9
toggle@resource:///org/gnome/shell/ui/overview.js:683:13
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:208:13
```
and when you're entering overview it freezes on that screen

![Screenshot from 2020-01-18 00-21-37](https://user-images.githubusercontent.com/11244308/72650439-36bed400-3989-11ea-8c8c-a8ea26e37384.png)

**Comment by charlesg99** [comment]
Hey Alex, I tried to update my Rawhide installation twice to 3.35.90 but ended with a broken system both times :( 

Do you have any pointers on how to get a 3.35.90 install working? Thanks!

**Comment by alex285** [comment]
i wanted to update you because there are more issues than this, but i thought to wait for you to try on Rawhide and 3.35.90; im not sure about whats crashing, but try to skip GDM, and start GNOME with "startx" from TTY

**Comment by charlesg99** [comment]
Hey Alex, finally got a Rawhide image that installed correctly. I could reproduce the issue you mentionned (`this._scrollAdjustment is undefined`) and pushed some adjustments for 3.35.90. Could you please try it and let us know if you find other issues? Thanks!

**Comment by charlesg99** [comment]
I tried installing the ubuntu-dock from the dash-to-dock repo, but I can't get it to enable correctly on 3.35.90 (I get a `TypeError: appIconPrototype._onLeaveEvent is undefined` error). 

After trying to enable ubuntu-dock, I can reproduce the `Expected type interface for Argument 'file' but got type 'undefined'` error, but I think it's because ubuntu-dock can't enable correctly and its stylesheet isn't loaded.

Did you observe something different? Thanks!

**Comment by alex285** [comment]
hello, all working fine now on DtP and thanks!! DtD isn't loading anymore, so i guess they need to port it on 3.36!! im closing this, and open a new issue if i find something! thanks again!!

**Comment by jgrocha** [comment]
Same error here. Not sure if is the same.
```
abr 03 10:34:57 zoe gnome-shell[11153]: JS ERROR: Extension dash-to-panel@jderose9.github.com: Error: Expected type interface for Argument 'file' but got type 'undefined'
                                        _enable@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:75:9
                                        enable@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:63:5
```

I've removed `ubuntu-dock` extension, but does not help.
```bash
sudo apt remove gnome-shell-extension-ubuntu-dock
```
Should I open a new issue?

I'm using Ubuntu 19.10, GNOME Shell 3.34.3

**Comment by jderose9** [comment]
@jgrocha what version of dash to panel are you running? (It can be found in the Settings, About tab)

**Comment by jgrocha** [comment]
@jderose9 Dash-to-Panel version: 33

**Comment by jgrocha** [comment]
Meanwhile I've reinstalled everything and it works again. Let's keep this issue closed. Thank you for the feedback @jderose9
