### ISSUE TITLE
Running app indicator is sometimes missing after launch

### ISSUE THREAD

**Issue by fthx** [home-sweet-gnome/dash-to-panel#851]
Hi Charles,

_Ubuntu 20.04 dev, GS 3.34.3, Wayland, DtP 26 or git_

Way to reproduce : 

1) Click on the DtP's appgrid icon
2) Launch e.g. Gnome Logs (or an app not present in taskbar/favbar)
3) 
![image](https://user-images.githubusercontent.com/23138504/72661465-b5902d00-39da-11ea-9324-929167bc2476.png)
or
![image](https://user-images.githubusercontent.com/23138504/72661428-33a00400-39da-11ea-86b5-0de9fe8b5de1.png)

**Comment by jderose9** [comment]
I was able to reproduce this with 20.04 (using Wayland only) when launching apps from the Overview.

Possibly related - while trying to reproduce this I noticed that in 19.10+, the ubuntu dock no longer disables cleanly.

**Comment by jderose9** [comment]
Also happening on 19.10 _in Wayland_.

**Comment by jderose9** [comment]
This should be fixed on master. 

@charlesg99 You mind to review it and make sure you don't see any negative side effects? The app icon repaint event wasn't firing on Wayland when the application was opened from the overview, until the icon was clicked, for whatever reason.

**Comment by charlesg99** [comment]
@jderose9 Looks good to me!

**Comment by davidmartos96** [comment]
I am experiencing this problem with some apps but with X, not Wayland.
Some apps: Sublime Merge and Tilix

Opensuse Tumbleweed - Gnome 3.36
