### ISSUE TITLE
Display work area not taken in other monitors

### ISSUE THREAD

**Issue by Richy91** [home-sweet-gnome/dash-to-panel#852]
I don't know if this is really an issue, but i am developing a program which gets monitor work area and i noticed that on one monitor panels allocated space on monitor is not detected!

I have a laptop and connected external display! On laptop if i get monitor work area then panels size is detected, but not on second display! If i switch external display as primary then nothing changes! Still not detected! That happens even if i chose to show panel on primary (primary being external display)

function used:
gdk_monitor_get_workarea (GdkMonitor *monitor, GdkRectangle *workarea);

External display:
 Monitor geometry = 1920 and 1080
 Monitor work_area = 1920 and 1080

Laptop:
 Monitor geometry = 1366 and 768
 Monitor work_area = 1366 and 720

This clearly does not affect user experience. I just don't know the solution how to work around this issue, because my app, when launched, goes under the panel on external display, but not on the laptop display!

**Comment by charlesg99** [comment]
Hello Richy91! Are you using the intellihide feature by chance? There is an option to hide the panels on the secondary monitors only, so this could be an explanation.

If not, which version of gnome-shell are you running? Haven't tried using GDK, but gnome-shell seems to correctly detect both panels on my system (they have a height of 34px): 

![image](https://user-images.githubusercontent.com/33044886/72693220-e321c700-3afd-11ea-9f62-20f900798abb.png)

Thanks!

**Comment by Richy91** [comment]
No I am not using intellihide. I think it is related to GDK. I found this issue: https://gitlab.gnome.org/GNOME/gtk/issues/1086
If i place monitors on side, then panel is detected on both, but if i place them vertically, then panel is not detected on top monitor (primary or not) It is detected only on bottom monitor!

Anyway i found a workaround for this and since it is gtk/gdk related issue not detecting then this can be closed!
