### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Richy91** [home-sweet-gnome/dash-to-panel#853]
I noticed, that with enabled dash-to-panel and changing multi monitor composition in control-center and pressing apply gnome-shell memory consumption grows. If you do it multiple times, then shell memory usage is pretty high!
I tested this without dash-to-panel extension and memory did not increase after switching composition multiple times! This leads me to believe that this could be dash-to-panel issue!

I am using latest master version!
shell version 3.34.2

**Comment by charlesg99** [comment]
Hello Richy91, we recently closed a similar issue #959, could you try to reproduce this using the master branch? From my testing on 3.36, the leak was resolved. Thanks!
