### ISSUE TITLE
[Feature request] Shortcut to cycle windows

### ISSUE THREAD

**Issue by alespg** [home-sweet-gnome/dash-to-panel#854]
Hi,
First, i have seen your las commit and i like very much the feature, i currently change volume with "mouse button 8" + wheel, using easystroke, so i like that feature very much :) 
i love how dash to panel is evolving to fulfill all my needs in just one extension.

Now, i have a doubt, or a request, because i like how cycle windows works in dash to panel, it is just the way i want: isolating monitors and workspaces and i have not found any extension to replicate that behaviour, so it would be nice to do it from dash to panel.

My final idea is to use "mouse right click" + wheel to cycle windows (the way browsers do to move among tabs), using easystroke, but for that, i need a shortcut to simulate, is there already in dash to panel? if not, there it is my request :)

**Comment by chrisjbillington** [comment]
There's the "scroll icon action" = "Cycle windows" option, but this only cycles windows of the same app.
It would be nice if either:

* were two options "Cycle application windows" and "Cycle all windows", or
* scrolling cycled between all windows and not just windows of the same application if "ungroup applications" is set.

**Comment by alespg** [comment]
> There's the "scroll icon action" = "Cycle windows" option, but this only cycles windows of the same app.
> It would be nice if either:
> 
> * were two options "Cycle application windows" and "Cycle all windows", or
> * scrolling cycled between all windows and not just windows of the same application if "ungroup applications" is set.

it already works like that, i asked for it in [this cycle windows request](https://github.com/home-sweet-gnome/dash-to-panel/issues/796) and @charlesg99  delivered.

so, for me, the cycle windows works perfectly, better than any other extensions i have tried, thats why i ask for a shortcut, i want to use as my cycle windows default.

maybe you are not using the latest version of dash-to-panel?

**Comment by chrisjbillington** [comment]
Ah, I see. I am using the latest git master of dash to panel, but I have:

* scroll panel action: switch workspace
* scroll icon action: switch windows

And it looks like the "scroll icon action" switch windows option only applies to windows of that application.

When I set the "scroll panel action" to switch windows, I get switching between all windows. 

I assume this is intended. I'll probably just set  scroll panel action = switch windows and map my extra mouse buttons to switch workspaces instead.

**Comment by alespg** [comment]
i use 
* scroll panel action: switch windows
* scroll icon action: same as panel

so anywhere i scroll, it switches among all windows of the monitor and workspace.

i understand you want to switch between all windows on icons and workspaces on the panel and you are right, it is not possible right now

**Comment by chrisjbillington** [comment]
The issue still exists and I'm still interested in the feature!

No obligation to implement it of course, but I'm replying to keep it open.
