### ISSUE TITLE
Right click on an empty Panel space around Apps and open a menu

### ISSUE THREAD

**Issue by BoQsc** [home-sweet-gnome/dash-to-panel#856]
Most of the time there is plenty unused space on the panel.

![Screenshot from 2020-01-24 16-47-58](https://user-images.githubusercontent.com/21064622/73078436-d5d45600-3eca-11ea-91d7-fd0d848a3b36.png)

It would be great that Right-clicking on that area would bring up some kind of menu that would let to choose similar settings to that of 9 dots icon.

![Screenshot from 2020-01-24 16-47-58](https://user-images.githubusercontent.com/21064622/73078697-627f1400-3ecb-11ea-83e3-1818488fc0e4.png)

**Comment by charlesg99** [comment]
Hello BoQsc, thank you for the suggestion! I always thought it would be a nice addition as well. The feature was added on the master branch if you want to give it a try. Thanks!

**Comment by BoQsc** [comment]
It works as expected Charles. I tested the master branch changes. 
### My futher recommendations: 
**Remove entries** 
- Power options
- Event logs
- System
- Device Management
- Disk Management

### The reason for removal of these entries: 

- The popup menu **looks unaesthetic on a smaller Laptop screens**, starting with **15.6" inches**.
   - Takes large portion of the screen
- The entries I suggest to remove can be accessed through **9 dots icon**.
- Accessing these entries through **9 dots icon** looks aesthetic on a smaller Laptop screens.

**Comment by charlesg99** [comment]
Hello BoQsc! Thank you for the recommendations, the entries you mentioned were remove from the context menu when opening it by right clicking on the panel (they'll still be available when right clicking on the showapps button). Thanks!

**Comment by BoQsc** [comment]
For now, it is great. I'm having some feeling that it still needs some improvement.  
However, I have nothing clear to say on exactly what needs an improvement.  
I will close this issue for now, since everything is done as expected in the original issue above.
