### ISSUE TITLE
Hidden panel block the top area of second monitor in upper - bellow position

### ISSUE THREAD

**Issue by ruathudo** [home-sweet-gnome/dash-to-panel#858]
I have laptop and external monitor setup like this:

![image](https://user-images.githubusercontent.com/3640787/73578935-a05ed800-4489-11ea-9ac1-7fd9e6b934ac.png)

When I'm setting in "Panel Intelligent" hide on **All windows** or hide on **Maximized windows**, The hidden panel of upper screen will block the bellow screen's top area. It is invisible and overlay the windows bar, which I can' select or move the windows.
To overcome temporary, I need to set  "focused windows" option. Is there anyway to fix that issue? Thank you!

**Comment by charlesg99** [comment]
Hello ruathudo, thank you for reporting this. This issue was fixed on the current master branch, could you [install it](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github) and see if that helps?

**Comment by ruathudo** [comment]
Hi @charlesg99 , This issue has been fixed on your update. Thank for the great work.

**Comment by charlesg99** [comment]
Great, glad it works for you! Thanks!
