### ISSUE TITLE
Option to only show application icons on the window where they are opened

### ISSUE THREAD

**Issue by Derkades** [home-sweet-gnome/dash-to-panel#859]
Instead of showing all applications on all screens

**Comment by charlesg99** [comment]
> on the window where they are opened

Hello, what do you mean by that? You mean on the monitor? If so I think you didn't look very long in the settings :P as we have settings to isolate by monitor and by workspace. Assuming you're referring to monitors:

![image](https://user-images.githubusercontent.com/33044886/73760926-10948480-473c-11ea-9eaf-ee44ec872d35.png)

![image](https://user-images.githubusercontent.com/33044886/73760950-1be7b000-473c-11ea-8b4b-f1661578a9b7.png)

Thanks!

**Comment by Derkades** [comment]
Yeah you're right, I must've missed it while looking through all the menus. It's working now, thanks for the fast response
