### ISSUE TITLE
Clock override extension not working correctly on a vertical panel

### ISSUE THREAD

**Issue by eduardoxfurtado** [home-sweet-gnome/dash-to-panel#863]
I'm not sure if this is a bug in the extension "[Clock override](https://github.com/stuartlangridge/gnome-shell-clock-override)" or in dash to panel.

When using the extension "dash to panel" setting the "Panel screen position" to "left" or "right" to have a vertical panel, the formatting symbols %n to jump a line or %F to draw the ISO date are not working. These symbols are set on the "Clock override" extension.

All the symbols seem to be ignored, besides a single %S to show the seconds.

After disabling and enabling "Clock override" the correctly formatted string appears for a brief moment. Basically until a new second redraws the clock and only the time is shown.

I would like to be able to use "%H:%M:%S%n%F" and that they are shown center-aligned on a vertical panel.

My guess is that "dash to panel" might change the rendering of the clock when the panel is vertical, so Clock override might not be working correctly because of that.

**Comment by eduardoxfurtado** [comment]
After investigating the code of both Clock override and Dash to panel, I believe Clock override doesn't take into consideration that the rendering of the panel's clock change when it's vertical.

So I guess the fix would be a new feature for Clock override, to make the override count when the panel is in vertical mode?

Or maybe dash to panel should not have the final word on the clock formatting?

Or maybe the functionality of formatting the clock string should be present in dash to panel?

**Comment by eduardoxfurtado** [comment]
So, after digging more, my proposed solution is to change Dash to panel to check if "Clock override" is enabled, on the function that formats the clock:

```
    _formatVerticalClock: function() {
    	**_// don't format the clock if the extension Clock override is doing it already:
    	if (something like Main.panel.clockOverride)
    		return;_**

        let time = this.statusArea.dateMenu._clock.clock;
        let clockText = this.statusArea.dateMenu._clockDisplay.clutter_text;
        
        clockText.set_text(time);
        clockText.get_allocation_box();

        if (clockText.get_layout().is_ellipsized()) {
            let timeParts = time.split('∶');

            if (!this._clockFormat) {
                this._clockFormat = Me.desktopSettings.get_string('clock-format');
            }

            if (this._clockFormat == '12h') {
                timeParts.push.apply(timeParts, timeParts.pop().split(' '));
            }

            clockText.set_text(timeParts.join('\n<span size="xx-small">‧‧</span>\n').trim());
            clockText.set_use_markup(true);
        }
    },
```

However I don't know how to write that bit of the code (how to check if another extension is enabled), but my guess is that the Main object might have a variable with this value?

**Comment by jderose9** [comment]
Hi @eduardoxfurtado !

You can see an example of checking for an existing extension here:
https://github.com/home-sweet-gnome/dash-to-panel/blob/dd795a7ae2b080a014117a95b534bc2b65791aef/extension.js#L66-L70

Also, you would need to re-verify each time another extension gets enabled, in case it gets enabled after dash-to-panel:
https://github.com/home-sweet-gnome/dash-to-panel/blob/dd795a7ae2b080a014117a95b534bc2b65791aef/extension.js#L52-L56

That said, the reason the clock is reformatted in vertical mode is to handle the less horizontal real estate available in that orientation. I'm not familiar with Clock Override, but if you are able to get something usable in vertical mode with it, we can merge your exclusion in. Please let me know how it goes, and screenshots would be great as well. Thanks!

**Comment by eduardoxfurtado** [comment]
OK, I'll put my time into this after Wednesday, for Now I can't anymore!

**Comment by zfc9d3f** [comment]
is anyone working on this? it was working perfectly before. 
I don't even know why i chose to upgrade when it was working fine for me. 

now the clock can't render properly 

https://i.imgur.com/Lt5yOYu.png

**Comment by benneti** [comment]
actually it does also not work on a secondary panel in horizontal mode.
On the primary monitor I get the expected behavior 
![Screenshot from 2020-11-24 08-53-52](https://user-images.githubusercontent.com/11725645/100064370-bd0e3700-2e32-11eb-8769-e105cc25519d.png)
while on the secondary it uses the default value
![Screenshot from 2020-11-24 08-54-00](https://user-images.githubusercontent.com/11725645/100064374-be3f6400-2e32-11eb-9f86-e567b66c563c.png)
