### ISSUE TITLE
Intellihide obstructs other window

### ISSUE THREAD

**Issue by BjornPijnacker** [home-sweet-gnome/dash-to-panel#864]
**Bug description**

My workstation is setup with two monitors above each other, with the top monitor as the main monitor. The top monitor thus displays my dash-to-panel panel. When intellihide is turned for maximized windows and a window is maximized on the top display, the bottom display has a small row on the top where clicks are not registered to the application that might be there.

**Steps to reproduce**

1. Have a setup with two (equal resolution) monitors; one positioned above the other with the top one set as main monitor. Have the panel on the bottom of the window
2. Have intellihide configured to hide when a window is maximized
3. Maximize any application on the top (main) display to hide the panel
4. A strip of equal height to the panel is now obstructed from registering clicks on the top of the bottom display

**Comment by charlesg99** [comment]
Hello BjornPijnacker, thank you for your report! This issue is already fixed on the master branch, could you please [try it](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github)? Also, see #858 for more details. Thanks!

**Comment by BjornPijnacker** [comment]
> Hello BjornPijnacker, thank you for your report! This issue is already fixed on the master branch, could you please [try it](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github)? Also, see #858 for more details. Thanks!

This indeed fixes the issue. Closing
