### ISSUE TITLE
Panel size is broken

### ISSUE THREAD

**Issue by StructByLightning** [home-sweet-gnome/dash-to-panel#865]
*Expected behavior:*
Increasing the Panel Size option past 48px should increase the icon size and grow the panel width appropriately so the newly enlarged icons can be fully displayed. 

*Actual behavior:*
Increasing the Panel Size option correctly increases the icon size, but the panel remains stuck at 48px wide. Icons overflow the panel and are cut off.

*Reproduction:*
1. Open the Dash to Panel settings
2. Go to the Style tab
3. Drag the Panel Size slider past 48px

*Screenshots:*
Here's an example at 48px, where everything looks right:
![image](https://user-images.githubusercontent.com/32056364/74474526-8abeba80-4e5a-11ea-96ec-7fbdaac59c70.png)

Here's another example at 24px, with the panel shrinking correctly:
![image](https://user-images.githubusercontent.com/32056364/74474641-c2c5fd80-4e5a-11ea-975a-c7f78ac4712d.png)

But if you go past 48px, the icons get cut off:
![image](https://user-images.githubusercontent.com/32056364/74474548-98744000-4e5a-11ea-984d-a4cc64e6b2f7.png)

*OS:*
Ubuntu 18.04.3

**Comment by charlesg99** [comment]
Hello StructByLightning, this is working fine for me on ubuntu 18.04, could you try the latest master? I seem to recall an issue like that, maybe it wasn't fixed before we released v26.

![dtp_18 04](https://user-images.githubusercontent.com/33044886/74480976-e3ed1500-4e7f-11ea-8377-cb71d4968639.png)

Thanks!

**Comment by StructByLightning** [comment]
Installing the latest version worked. Interestingly enough, I installed through the gnome extensions site on my laptop (also ubuntu 18) and it worked fine. I'm not sure what was going on, but it seems to be fixed. Thank you for the quick response and of course for the awesome extension.
