### ISSUE TITLE
Wayland Finger-Touch not showing opened windows

### ISSUE THREAD

**Issue by MisterPresident** [home-sweet-gnome/dash-to-panel#866]
Hy, 
I am having issues with my Gnome on Arch Linux. Everything is up to date:

> gnome-desktop 1:3.34.2-1
> wayland 1.18.0-1
> libinput 1.15.1-1

**Using the stylus & normal mouse:** I can click and therefore open applications from the panel. --> Everything is working like expected
**Using the touchscreen with a finger:** The Places and Applications button are working fine. However, when i want to click on e.g. the Thunderbird icon, it light's up like i am keeping the left mouse button but the window doesn't move forward.

Does anyone know how to trace this bug down or what leads to this misbehavior?

Thanks

**Comment by charlesg99** [comment]
Hello MisterPresident! Is this on a Wayland session? Seems like touch is behaving better on xorg, could you try it? Also, see #689 and #298; does it sounds like a duplicate of those issues? Thanks!

**Comment by MisterPresident** [comment]
Hello, yes it is on a Wayland session. Xorg is working without any issues.
I am definitely not freezing like #689 I do not have to kill my session or logout.
Also #298 doesn't seem to be the same. 

Launching my favorites is working as supposed to. The only problem is when i want to activate a running application. This is only possible with a ugly workaround: Long touch on an running application icon, the context menu (like on a right click) is opened and then i can select the window name.

**Comment by MisterPresident** [comment]
After some further testing, I also got freezes. Seems to be #689. Sorry for making a duplicate but it doesn't freeze all times.
