### ISSUE TITLE
Let users drag and drop into individual preview windows

### ISSUE THREAD

**Issue by BoQsc** [home-sweet-gnome/dash-to-panel#867]
### Current behaviour
It can be seen that right now **dragging and dropping into Dash to Panel is opening Gnome Activities Overview**. Where you can further locate the window where you would like to drag and drop.

![Screencast-from-2020-02-15-13_53_21](https://user-images.githubusercontent.com/21064622/74587482-985f7600-4ffb-11ea-9f9f-ac4ec1c1a0d3.gif)

### Alternative Behaviour
While it is not a bad experience at all, I just though that giving people an **alternative option to
Drag and Drop directly into Dash To Panel preview windows** would be more straightforward.  

Note: I do not mean to **drop directly into preview windows**, rather the **expanded windows and their parts** that show up after hovering over the preview windows.

![hahahah](https://user-images.githubusercontent.com/21064622/74588028-d3fd3e80-5001-11ea-97ed-5693c1ffee62.png)

**Comment by jderose9** [comment]
Thanks @BoQsc! I'm not necessarily opposed to this, but I'm not clear on how you are envisioning the details to work. If you currently drag and drop over anywhere in the panel, the overview opens. Are you suggesting that if they then moved over to be hovering over an application icon, the overview would close and the preview would open instead?

**Comment by BoQsc** [comment]
> Thanks @BoQsc! I'm not necessarily opposed to this, but I'm not clear on how you are envisioning the details to work. 
>
> If you currently drag and drop over anywhere in the panel, the overview opens.
>
> Are you suggesting that if they then moved over to be 
> * hovering over an application icon, 
> * the overview would close and the preview would open instead?

I think you understood correctly: 
* pick a desktop icon, drag it over an application icon
* while hovering over an application icon
* instead of gnome overview:
  * show the application's preview
* Drop into application's preview.

![unnamed](https://user-images.githubusercontent.com/21064622/76152601-fa2a7180-60c9-11ea-9929-3eae841acabc.gif)

**Comment by jderose9** [comment]
So, I attempted that a couple of years ago and wasn't able to do it without upstream changes, as you can read here:
https://github.com/home-sweet-gnome/dash-to-panel/issues/46#issuecomment-283208983

But, since @charlesg99 reworked the preview windows a few months ago, I think we may no longer be a slave to the grab handler that was eating all of the event information. It's definitely worth revisiting.

**Comment by Thieum4** [comment]
I would love to see this setting happening. 
To me it is also a matter of performances (as generating the Gnome Activities Overview can be a sluggish on my laptop) and usability (quicker to hover on your app of interest to drop your file than look around in the overview).

**Comment by jeisoncp** [comment]
Leave the mouse over the panel doesn't works to me. I have to side over it:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/7952798/98245735-21cf2380-1f50-11eb-8bca-bc3c3065f7f6.gif)

**Comment by Filbuntu** [comment]
I would still be excited to get this feature back to Ubuntu! Thanks to anyone who could work on this!

**Comment by meliodas1107** [comment]
Will it 

> So, I attempted that a couple of years ago and wasn't able to do it without upstream changes, as you can read here:
> [#46 (comment)](https://github.com/home-sweet-gnome/dash-to-panel/issues/46#issuecomment-283208983)
> 
> But, since @charlesg99 reworked the preview windows a few months ago, I think we may no longer be a slave to the grab handler that was eating all of the event information. It's definitely worth revisiting.

Will it be possible now ? with gtk4 ?I'm not really knowledgeable about this. But I would love to see this feature working.

**Comment by Filbuntu** [comment]
Is there any hope for this? @jderose9?
