### ISSUE TITLE
Activities and Date are visible on lock screen (GNOME 3.36)

### ISSUE THREAD

**Issue by alex285** [home-sweet-gnome/dash-to-panel#868]
**tested on:** gnome-shell-3.35.91-1.fc33

**without Dash to Panel** the top bar on lock shows only the indicators on right:
![default](https://user-images.githubusercontent.com/11244308/74727384-c2a67300-5249-11ea-90b5-ebcc5b4bc252.png)

**with Dash to Panel enabled** we also get activities and date:
![dtp](https://user-images.githubusercontent.com/11244308/74727450-d9e56080-5249-11ea-8ce9-655b38945495.png)

**Comment by charlesg99** [comment]
Thanks alex285! Any idea when this new lock screen is going live on Rawhide? Maybe it's time I look into how to run gnome/mutter from master. Any links or tips?

**Comment by alex285** [comment]
it is already on Rawhide:  `gnome-shell-3.35.91-1.fc33` but sometimes the packages have some delay to get into the repos so you can grub them directly from koji (i think i re-share that)

```
[koji]
name=Koji $basearch
baseurl=https://kojipkgs.fedoraproject.org/repos/rawhide/latest/$basearch/
enabled=1
#metadata_expire=60m
gpgcheck=0
```

**Comment by jgillich** [comment]
Does the settings window (right click on panel -> dash to panel settings) open up for you guys? Not sure if there's another 3.36 issue here or if its something on my end. I installed from master and did a pref reset beforehand.

**Comment by alex285** [comment]
@jgillich that was a bug on Shell and happens to all extensions, but it is fixed on master; but on master DtP it is again broken.. argh :/

**Comment by alex285** [comment]
@charlesg99 3.35.92 is now available on Rawhide (at least on Koji) if you want to test!!

**Comment by charlesg99** [comment]
Hey alex285, now it should be working on 3.35.92. I still have to check for the lock screen though. Thanks!

**Comment by jderose9** [comment]
Looks like there was a race condition with the lock screen activation hiding the activities/clock and the extension disable restoring them to their original state. Maybe it's always been there and the new login UI/animation changes just caused it to show up now.

Can you test my change out?

Looks like the 3.36 release is coming up in a few days (March 11) so I'd like to get in the e.g.o. review queue asap. Everything good on your end for a release, @charlesg99?

**Comment by charlesg99** [comment]
Hey Jason! Crazy timing, I was about to push a fix for this as well :) Yours is simpler and it works on my end :tada:

All good for the next release!

**Comment by jderose9** [comment]
Guess I was wrong about 3.36 release date. It was just released :)

**Comment by charlesg99** [comment]
Huh! Guess they've decided to tag it earlier than [expected](https://wiki.gnome.org/ThreePointThirtyfive)!

**Comment by jderose9** [comment]
Thanks so much for the speedy review, @andyholmes!
