### ISSUE TITLE
A suggestion to add Gnome Extensions Preferences to the context menu of Show Applications

### ISSUE THREAD

**Issue by BoQsc** [home-sweet-gnome/dash-to-panel#869]
## Introduction to the issue-suggestion
Everything on this issue is related to this portion of the dash to panel extension and it's really nothing more than a suggestion.
![jskdlf](https://user-images.githubusercontent.com/21064622/74779164-a801e780-52a5-11ea-93c6-915d5cff3c1f.png)

Show Applications context menu that can be opened by right-clicking Show Applications' icon,   contains:
- Power options
- Event logs 
- System
- Device Management
- Disk Management

and similar environment administration tools. 

## The suggestion itself - add Gnome Extensions entry somewhere near other administration tools in the context menu

I keep wondering if it would be a good idea to bring in **Gnome Extensions Preferences entry**, somewhere in the context menu of Show Applications by the name of
* **Gnome Extensions**
   * Or the other name I suggest: **Shell Extensions**

It is easily accessible by using terminal,  
just write into the terminal: `gnome-shell-extension-prefs`  

and the GUI of Gnome Extensions Preferences will show up:
it is an application to manage Gnome Extensions and their preferences.

![image](https://user-images.githubusercontent.com/21064622/74778706-cadfcc00-52a4-11ea-896a-cc44e4697632.png)

**Comment by jderose9** [comment]
Hi @BoQsc !

![image](https://user-images.githubusercontent.com/2118702/74845431-060de980-52fd-11ea-8276-c368e7ab1ee2.png)

I've added this to `master` branch. Let me know what you think!

**Comment by BoQsc** [comment]
For now, it is great. Well, I couldn't make it better. Thank you.
