### ISSUE TITLE
[Feature request] Close a maximized window by pressing rightmost and topmost pixel

### ISSUE THREAD

**Issue by maxloh** [home-sweet-gnome/dash-to-panel#870]
Hi. Can you add a option to let user close a maximized window by pressing rightmost and topmost pixel of it, just like what we get in the Windows ecosystem?

It would makes it much more easy to close a maximized window in a UI/UX perspective, according to the Fitts' Law.

> It turns out that computer monitors add a very interesting twist to Fitts’s model of target selection, because they have something called “edges.” ... Because a pointing device can only go so far in any direction, targets at the edge of the screen technically have infinite target widths as illustrated below.
>
> ![image](https://user-images.githubusercontent.com/35831069/74971694-7894db80-545b-11ea-94a3-b67e0ac31c5c.png)
> 
> ![image](https://user-images.githubusercontent.com/35831069/75019932-b847db80-54cc-11ea-8677-af55d25f2002.png)
>
> from [Visualizing Fitts’s Law](http://particletree.com/features/visualizing-fittss-law/)

This behavior has been implemented in Linux version of Chrome, but not in native gtk applications like Nautilus file manager and system monitor.

If you are interested , here are some more references of the Fitts' Law:

- [Why is the Close button in the upper right corner?
](https://devblogs.microsoft.com/oldnewthing/20120522-00/?p=7563)

- [Fitts' Law and Infinite Width
](https://blog.codinghorror.com/fitts-law-and-infinite-width/)

**Comment by charlesg99** [comment]
Hello, I personally don't think this should be a part of dash to panel... @jderose9 please close this one if you agree. Thanks!

**Comment by jderose9** [comment]
@charlesg99 I was thinking the same thing. I agree with the OP, but in general I don't think adjustments to the window titles belong in this extension if they aren't somehow related to panel interaction.

@maxloh This seems to be a GTK specific issue, as non-GTK applications work as you describe. Here's an open issue I found: https://gitlab.gnome.org/GNOME/gtk/issues/583
