### ISSUE TITLE
Generating pot file 

### ISSUE THREAD

**Issue by frnogueira** [home-sweet-gnome/dash-to-panel#872]
Something wrong on generating the pot file! He only have 105 strings to translate...
So many strings are missing!

**Comment by charlesg99** [comment]
Hello frnogueira! Could you tell us how you generated the pot files? I tried with `make potfile && make mergepo` and I get this pt_BR.po file:

![image](https://user-images.githubusercontent.com/33044886/75067326-bffe8480-54ba-11ea-8004-c3a8e03dbd0d.png)

Seems correct to me. Thanks!

**Comment by frnogueira** [comment]
Hi charlesg99!
So... 
1. xgettext -k_ -kN_ -o po/dash-to-panel.pot --package-name "Dash To Panel" prefs.js
2. intltool-extract --type=gettext/glade Settings.ui
3. xgettext -k_ -kN_ --join-existing -o po/dash-to-panel.pot Settings.ui.h
And update the po file with pot file.
Result:  po file with 269 strings (total)

Now, with your command, i have one po file with 298 strings.

Thank you Charles! ;)
