### ISSUE TITLE
Stopped to work on Ubuntu

### ISSUE THREAD

**Issue by MickaelTH** [home-sweet-gnome/dash-to-panel#873]
Hi,

Just to report that Dash To Panel was working fine last week on Ubuntu 19.10 and now all of the sudden it stopped.

I tried to remove and reinstall several times, reboot computer, etc., but nothing is happening I still have the standard Ubuntu Dock appearing.

Any idea where to check logs to investigate what is going on?

Ubuntu 19.10
Dash To Panel 26

Thanks

**Comment by jderose9** [comment]
Sorry to hear you are having a problem, @MickaelTH.

You can have the logs output to your console as they occur with:
```
journalctl /usr/bin/gnome-shell -o cat -f
```

Or view them from the past using something like:
```
journalctl /usr/bin/gnome-shell -o cat -S "5 minutes ago"
```

I did just try v26 with a fully updated 19.10 and didn't have any issue with dash-to-panel, but I do see the chrome-gnome-shell package does seem to be throwing errors (with any extension) when trying to install/uninstall extensions through a browser.

**Comment by MickaelTH** [comment]
@jderose9 I found the culprit.

False alarm then, nothing wrong with Dash To Panel, as usual issue on client side.

For anyone else, or to my future self, make sure to activate the extension when downloading **GNOME Tweaks** as per the ss below:

![Screenshot from 2020-02-27 16-14-40](https://user-images.githubusercontent.com/26375917/75429904-1bc68300-597d-11ea-9a15-1b6f39db9e27.png)

Thanks for you time!
