### ISSUE TITLE
intellihide: keyboard shortcut to reveal and hold - move into 'action' menu [feature request]

### ISSUE THREAD

**Issue by bjohas** [home-sweet-gnome/dash-to-panel#874]
Hello,

Love dash-to-panel - thank you so much!

I've got intellihide turned on, with "keyboard shortcut to reveal and hold". The behaviour I would like would be either 
- keyboard shortcut to reveal and hold FOR 2 SECONDS (and then hide)
or
- keyboard shortcut to reveal and hold until next keyboard/mouse event (such as an application switch or click).

I often open the panel to look at the time and then just carry on. It would be nice if the panel closes automatically. If I want to use the panel, 2 seconds is plenty for me to get there.

**Comment by charlesg99** [comment]
Hello bjohas, you can do just that by enabling the hotkeys (under the Action tabs in the settings) and pressing <kbd>Super</kbd>+<kbd>q</kbd>. We use this to display the hotkey numbers for 2 seconds, but this also reveals the panel if it is hidden. Thanks!

**Comment by bjohas** [comment]
Ah yes, indeed - thank you so much!

**Comment by bjohas** [comment]
Hi @charlesg99,

After some more use, I've got the following suggestion/observation.

While the keyboard shortcut is there, it's in the 'advanced menu', and technically it's 'show the overlay', meaning the 'number overlay'. If I set the 'number overlay' option to 'never', the shortcut also stops working.

My proposal/request would be to move the shortcut into the 'action' menu itself, and call it ''Shortcut to show the panel for 2 secs" (or move it into the intellihide options, next to the 'keyboard shortcut to reveal...'). Then it's possible to disable the advanced options (and therefore the number overlay) while still being able to use the shortcut to show the panel. 

As far as I can see the functionality it currently has would not be affected: If the user wants the number overlay that can be enabled, and then the action should be as it currently is.

What do you think?
