### ISSUE TITLE
[Birth] Baby task bar is born

### ISSUE THREAD

**Issue by fthx** [home-sweet-gnome/dash-to-panel#876]
Hi everyone,

Happy to present the **little** sister of Dash to Panel :
https://extensions.gnome.org/review/14201
https://extensions.gnome.org/review/download/14201.shell-extension.zip
132 lines of code, it's not that much compared to DtP... It's obviously designed to be very light.

If anyone has the time to review the code, it would be nice. Not for extension validation, just to be sure the code is clean and does use the minimal system resources.

**Comment by charlesg99** [comment]
Hello fthx, looks like a good minimalist approach! Good luck with it!
