### ISSUE TITLE
Full-screen (F11) - weird interaction between Chrome / dash-to-panel / large text (bug?)

### ISSUE THREAD

**Issue by bjohas** [home-sweet-gnome/dash-to-panel#877]
Hello all,

this is a weird one. With dash-to-panel enabled and accessibility enabled (and set to large text), Chrome full-screen goes wrong. Instead of going full screen, the window goes full-screen as if on a smaller screen: the full-screen window you get sits in the top-left corner and is about 2/3rds or the linear dimensions of the normal screen size.

If I turn off dash-to-panel, full screen works fine. If I turn off accessibility, full-screen works fine. However, with both of them together, I get the above weird behaviour. (Chrome 80.0.3987.122)

It doesn't seem to affect applications other than Chrome. For example Chromium and e.g. Terminal are not affected.

I've recently started using dash-to-panel, so I don't know whether this is just with a recent Chrome/dash-to-panel combo or whether it affected older versions too?

Some observations:
- Without dash-to-panel and without large text, the F11 makes Chrome go full-screen immediately;
- Without dash-to-panel but with large text, the F11 makes Chrome go to the 2/3rds position (as above), and then the window expands.
- With dash-to-panel and with large text, when I do F11, I get the 2/3rds position (as described), but then if I use ctrl-minus and ctrl-0, the window expands to full screen.

**Comment by jderose9** [comment]
Hi @bjohas!

I tried this on Ubuntu 18.04 and 19.10 with Chrome version 80.0.3987.132 (Official Build) (64-bit) and _Large Text_ under _Universal Access_ enabled. I did not experience this issue.

Which distro are you seeing this on?

**Comment by bjohas** [comment]
Hi @jderose9,

Thank you. I've done some more testing, and I believe this is a chrome issue. 

If I use this:
```
gsettings set org.gnome.desktop.interface text-scaling-factor X
```
Then
- For X=1 to 2, the Chrome font size doesn't change, but full screen is immediate.
- For X>2 (e.g. X=2.00001) I get the weird behaviour ("F11 makes Chrome go to the 2/3rds position, and then the window expands.")
- Chrome doesn't respond to fractional changes in X otherwise, e.g. X=1.25 and X=1.3 give the same magnification.

Now:
- I retried the issue initially, and got the same 'stuck window' behaviour as above.
- However, having turned all extensions on/off (whcih didn't make a different) and then tried a wide range of settings for text-scaling-factors, I now cannot reproduice the 'stuck window'. I still see the two-stage expansion (as described above) but the 'stuck window' behaviour seems to be gone.

I'd be grateful if you wree able to how `gsettings set org.gnome.desktop.interface text-scaling-factor X` behaves for you, and then I'll file a bug against chrome.

Many thanks!

**Comment by bjohas** [comment]
Update: After some further use of chrome, the 'stuck window' aspect is also back (reliably).

**Comment by jderose9** [comment]
I tried `gsettings set org.gnome.desktop.interface text-scaling-factor 2.00001` and Chrome still goes full screen as expected under both Xorg and Wayland.

**Comment by charlesg99** [comment]
> I tried gsettings set org.gnome.desktop.interface text-scaling-factor 2.00001 and Chrome still goes full screen as expected under both Xorg and Wayland.

Same here, let's close for now.
