### ISSUE TITLE
JS errors after new Focal Fossa update.

### ISSUE THREAD

**Issue by mhatso** [home-sweet-gnome/dash-to-panel#878]
Using latest **DtP 26.1** _(most up to date on apt)_ with **Gnome 3.35.91** on **Ubuntu 20.04 Focal Fossa**.

The system was updated today and now Dash-To-Panel no longer works properly due to a couple of script errors. I tried re-installing the extension just in-case it was an update problem but to no avail. Thanks for this great plug-in. 
```
JS ERROR: Extension dash-to-panel@jderose9.github.com: Error: second argument to Lang.bind() must be a function, not undefined
bind@resource:///org/gnome/gjs/modules/lang.js:75:15
_init@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:1593:43
C@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/utils.js line 76 > eval:1:52
_init@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/taskbar.js:195:37
C@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/utils.js line 76 > eval:1:52
enable@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panel.js:260:24
_createPanel@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:290:9
enable@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:74:29
_enable@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:94:5
enable@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:62:5
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:161:13
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:312:21
_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:545:13
collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:520:9
_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:554:13
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:585:13
init@resource:///org/gnome/shell/ui/extensionSystem.js:55:9
_initializeUI@resource:///org/gnome/shell/ui/main.js:245:5
start@resource:///org/gnome/shell/ui/main.js:141:5
@<main>:1:31
```
```
Usage of indicator.indicators is deprecated for Indicator
get indicators@resource:///org/gnome/shell/ui/panelMenu.js:213:25
enable@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panel.js:208:13
_createPanel@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:290:9
enable@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:74:29
_enable@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:94:5
enable@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:62:5
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:161:13
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:312:21
_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:545:13
collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:520:9
_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:554:13
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:585:13
init@resource:///org/gnome/shell/ui/extensionSystem.js:55:9
_initializeUI@resource:///org/gnome/shell/ui/main.js:245:5
start@resource:///org/gnome/shell/ui/main.js:141:5
@<main>:1:31
```
```
JS WARNING: [/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/appIcons.js 1080]: unreachable code after return statement
loading user theme: /usr/share/themes/Yaru-dark/gnome-shell/gnome-shell.css
```

**Comment by paride** [comment]
This does indeed happen; the version of the package is **26-1**, i.e. the first packaging iteration of upstream version 26 of dash-to-panel.

This is likely to affect Debian too, but Gnome 3.35.91 is only available in the experimental suite for the moment.

**Comment by mhatso** [comment]
Many thanks for confirming this error with me. It is also rather frustrating that the extension stays in an _unstable_ and _half-working_ state with no way to disable it in the Gnome user interface as the extension manager reports it as **ERROR** with the visible state automatically set to **disabled**. The panel resets to default Gnome behaviour when I manually erase `/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com` in which gnome-shell assumes the extension is removed after restarting with **ALT+F2** and running the **r** command to restart the shell. One would also assume that _apt_ will eventually restore the files when the extension is upgraded. Of course, this separate issue is probably a _gnome-shell_ issue though but I thought I would just mention this here too incase people don't know how to deal with this extension pretty much trapped in limbo with no visible way to remove it.

**Comment by kleinHeiti** [comment]
Hello, everybody,

the error also occurs if the extension is installed via 
extensions.gnome.org.

I also use Ubuntu 20.04 with current Gnome 3.35.91 (update was 
installed yesterday, I think).

Am Di, Mär 3, 2020 at 05:13 schrieb mhatso <notifications@github.com>:

**Comment by charlesg99** [comment]
Please try the latest master, should be working now. Thanks!

**Comment by kleinHeiti** [comment]
the command "make install" causes this text (sorry only German)

fatal: Kein Git-Repository (oder irgendein Elternverzeichnis bis zum 
Einhängepunkt /)
Stoppe bei Dateisystemgrenze (GIT_DISCOVERY_ACROSS_FILESYSTEM nicht 
gesetzt).
fatal: Kein Git-Repository (oder irgendein Elternverzeichnis bis zum 
Einhängepunkt /)
Stoppe bei Dateisystemgrenze (GIT_DISCOVERY_ACROSS_FILESYSTEM nicht 
gesetzt).
msgfmt -c po/hu.po -o po/hu.mo
make: msgfmt: Kommando nicht gefunden
make: *** [Makefile:54: po/hu.mo] Fehler 127


Am Di, Mär 3, 2020 at 06:41 schrieb Charles Gagnon 
<notifications@github.com>:

**Comment by charlesg99** [comment]
Hello kleinHeiti, you probably need to install the `gettext` package as I believe it isn't installed by default on Ubuntu. Thanks!

**Comment by kleinHeiti** [comment]
Hello,

the extension seems to install now.:

fatal: Kein Git-Repository (oder irgendein Elternverzeichnis bis zum 
Einhängepunkt /)
Stoppe bei Dateisystemgrenze (GIT_DISCOVERY_ACROSS_FILESYSTEM nicht 
gesetzt).
fatal: Kein Git-Repository (oder irgendein Elternverzeichnis bis zum 
Einhängepunkt /)
Stoppe bei Dateisystemgrenze (GIT_DISCOVERY_ACROSS_FILESYSTEM nicht 
gesetzt).
rm -fR ./_build
mkdir -p _build
cp extension.js stylesheet.css metadata.json COPYING README.md 
appIcons.js convenience.js panel.js panelManager.js proximity.js 
intellihide.js progress.js panelStyle.js overview.js taskbar.js 
transparency.js windowPreview.js prefs.js update.js utils.js 
Settings.ui _build
mkdir -p _build/img
cd img ; cp highlight_stacked_bg.svg highlight_stacked_bg_2.svg 
highlight_stacked_bg_3.svg ../_build/img/
mkdir -p _build/schemas
cp schemas/*.xml _build/schemas/
cp schemas/gschemas.compiled _build/schemas/
mkdir -p _build/locale
for l in po/uk.mo po/hu.mo po/zh_CN.mo po/ja.mo po/pl.mo po/it.mo 
po/de.mo po/fr.mo po/ru.mo po/kk.mo po/zh_TW.mo po/tr.mo po/es.mo 
po/cs.mo po/pt_BR.mo ; do \
	lf=_build/locale/`basename $l .mo`; \
	mkdir -p $lf; \
	mkdir -p $lf/LC_MESSAGES; \
	cp $l $lf/LC_MESSAGES/dash-to-panel.mo; \
done;
rm -rf 
/root/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com
mkdir -p 
/root/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com
cp -r ./_build/* 
/root/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/
rm -fR _build
echo done
done

But it is not activated and cannot be activated via the tweak-tool... 
even after reboot:



Am Di, Mär 3, 2020 at 07:02 schrieb Charles Gagnon 
<notifications@github.com>:

**Comment by kleinHeiti** [comment]
It's me again.

I have found my mistake. Tried to run the install with "sudo". Without 
"sudo" everything works fine. The extension itself is now running fine 
again.
Thanks for the quick help!

Am Di, Mär 3, 2020 at 07:02 schrieb Charles Gagnon 
<notifications@github.com>:

**Comment by kleinHeiti** [comment]
And again it's me.

I was a little hasty. the expansion itself is running again. But I can 
no longer access the extension settings. This is not possible with a 
right click on the application menu or via tweaktool.
When opening the extension settings via tweaktool only an empty window 
opens. Unfortunately there is no reaction at all when right clicking on 
the application menu...

Am Di, Mär 3, 2020 at 16:33 schrieb Christian Heitjan 
<heitjan@gmx.net>:

**Comment by mhatso** [comment]
The new update fixed the errors but I am having the same issue suddenly with no extension preferences loading for me, not just DtP. Even with DtP not installed it happens too so I think something changed on the Gnome shell too recently. I found this bug on Gnome which is related but it has been closed. [https://gitlab.gnome.org/GNOME/gnome-shell/issues/2240](https://gitlab.gnome.org/GNOME/gnome-shell/issues/2240). Your guess is as good as mine.

**Comment by charlesg99** [comment]
It is working fine on Fedora Rawhide 3.35.92, but the bug you mentioned about the extension preferences was also present on 3.35.91 before the update. What is the output of `gnome-shell --version` on your system? My guess is that Ubuntu 20.04 isn't yet updated to 3.35.92. Thanks!

**Comment by kleinHeiti** [comment]
The gnome-shell version is 3.35.91

**Comment by mhatso** [comment]
Same version. Makes sense really. We just need to wait for Focal repositories to catch up with .92 and everything should be okay hopefully.

**Comment by P-IH** [comment]
Installed gettext and the development version on Focal Fossa with Gnome 3.35.91.
Works fine with the old settings.

**Comment by fcole90** [comment]
I had the same issue. I now installed the extension from source and it's working perfectly. Thanks :heavy_check_mark:

**Comment by mhatso** [comment]
Just attaching these related bugs with broken preferences for reference:
[https://gitlab.gnome.org/GNOME/gnome-shell/issues/2317](https://gitlab.gnome.org/GNOME/gnome-shell/issues/2317)
[https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1866146](https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1866146)

**Comment by BoQsc** [comment]
Installed **dash to panel** from the **master branch** on the latest *pending* daily build of Ubuntu.
http://cdimage.ubuntu.com/daily-live/pending/
> Description:	Ubuntu Focal Fossa (development branch)
> Release:	20.04

**Everything works as expected** and remember to install `gettext` as Charles mentioned.
`sudo apt-get install -y gettext`

**Comment by BoQsc** [comment]
# Fully automated installation of the Dash to Panel Extension from development branch (master)
 for **Ubuntu 19.10 and above**.

I present to you multiple ways to download the extension via git and without git.
There is no actual difference between them, both work correctly.

## This script is tested many times and completely stable
I Installed **dash to panel** from the **master branch** on the latest pending daily build of Ubuntu.
http://cdimage.ubuntu.com/daily-live/pending/
> Description: Ubuntu Focal Fossa (development branch)
Release: 20.04

**Works perfectly even on Ubuntu live cd.**

## How to use

- Simply copy and paste one of the script below into a .sh file,  
- mark it as executable   
- and launch with bash  


### In this version the master is downloaded by git
```
#!/bin/bash
sudo apt install git
git clone https://github.com/home-sweet-gnome/dash-to-panel.git
cd dash-to-panel/

sudo apt-get install gettext -y;
sudo apt install make -y;

make install
gnome-extensions enable "dash-to-panel@jderose9.github.com"
busctl --user call org.gnome.Shell /org/gnome/Shell org.gnome.Shell Eval s 'Meta.restart("Restarting…")';

```

### Alternate way without installing git and using GET command
```
#!/bin/bash
GET "github.com/home-sweet-gnome/dash-to-panel/archive/master.zip" > "dash-to-panel-master.zip";
unzip "dash-to-panel-master.zip";
cd "dash-to-panel-master/";

sudo apt-get install gettext -y;
sudo apt install make -y;

make install
gnome-extensions enable "dash-to-panel@jderose9.github.com"
busctl --user call org.gnome.Shell /org/gnome/Shell org.gnome.Shell Eval s 'Meta.restart("Restarting…")';
```

**Comment by jderose9** [comment]
Sounds like we are in good shape so I will close this one for now.

@BoQsc If you feel like tweaking your script so it can run multiple times without folder name collisions, we can add it to the Wiki.

**Comment by BoQsc** [comment]
## Download and Install Dash to Panel from master branch @jderose9 
Notice: gnome-extensions tool is only introduced in Ubuntu 19.10 
Notice: **gnome-shell-extension-tool** can be used in older versions than Ubuntu 19.10
Warning: this script is not made for **gnome-shell-extension-tool** 

### Behaviour
- Creates randomly named folder `$RANDOM-dash-to-panel` in `/tmp/` directory
  * > /tmp | Temporary files (see also /var/tmp). Often not preserved between system reboots, and may be severely size restricted.
- Switches Current Directory to `/tmp/$RANDOM-dash-to-panel` folder
- Installs `git` repository tool using APT Package Manager 
- Use `git clone` to download dash-to-panel source code to <code>/tmp/<b>$RANDOM-dash-to-panel</b>/dash-to-panel/</code> folder
- Switches Current Directory to <code>/tmp/<b>$RANDOM-dash-to-panel</b>/dash-to-panel/</code>
- Installs `gettext` repository tool using APT Package Manager 
- Installs `make` repository tool using APT Package Manager 
- use `make install` to install extension
- use `gnome-extensions enable` to enable the extension
- use `busctl --user call` to send a bus call to Gnome Shell to reload itself.
```
#!/bin/bash
#-- Create Temporary Folder ------------------------------------
declare folder_name="$RANDOM-dash-to-panel";
declare folder_path="/tmp/$folder_name"

mkdir "$folder_path";
cd "$folder_path";

#-- Download Source Code ------------------------------------
sudo apt install git -y;
git clone "https://github.com/home-sweet-gnome/dash-to-panel.git";
cd "dash-to-panel/";

#-- Install Dependencies  ------------------------------------
sudo apt-get install gettext -y;
sudo apt install make -y;

#-- Install Extension ------------------------------------
make install;
gnome-extensions enable "dash-to-panel@jderose9.github.com";
busctl --user call "org.gnome.Shell" "/org/gnome/Shell" "org.gnome.Shell" "Eval" "s" 'Meta.restart("Restarting…")';


#-- Remove Temporary Folder ------------------------------------
rm -rf "$folder_path";
```

**Comment by BoQsc** [comment]
@jderose9 If you feel like this script could be useful and included in the documentation, I would be glad to see it included.

I might consider making a support for older Ubuntu versions than 19.10 if asked, shouldn't be hard, however it needs to be tested.

**Comment by jderose9** [comment]
Thanks @BoQsc ! I added you to the README credits and your script to the Wiki. If you want to work on a < 19.10 version, I can include that too - totally up to you.

**Comment by BoQsc** [comment]
The script has been updated to support older Gnome versions.
The script is now tested on Ubuntu 18.04.4 LTS | GNOME Shell 3.28.4
Works as expected and flawlessly.
![image](https://user-images.githubusercontent.com/21064622/76159561-dbec6200-6119-11ea-9338-68374ca47504.png)
