### ISSUE TITLE
"Isolate workspaces" interferes with "Keep original gnome-shell dash" (launch behavior)

### ISSUE THREAD

**Issue by smichel17** [home-sweet-gnome/dash-to-panel#880]
**Steps to reproduce:**

- Enable both "Keep original gnome-shell dash (overview)" and "Isolate workspaces"
- Open a terminal window on workspace 1
- Switch to workspace 2
- Open the overview and click on the terminal icon in the dash

**Expected behavior:** Workspace 1 is activated and existing terminal window is focused
**Actual behavior:** New terminal window is launched on workspace 2

**Notes:**
- It does not have to be a terminal window. Firefox, Nautilus (Files), and many other applications work fine to reproduce this. However, there are some applications (Gnome tweaks, Geary, etc) that you can't open multiple windows of at once.
- You do need to be on a different workspace than the open window. If you stay on the original workspace (1, here), the dash works correctly.

Thank you for a great extension :)

**Comment by smichel17** [comment]
I changed this locally for myself, but in the process I discovered that this functionality is probably intentional (it is applied explicitly to the overview, not as a side affect of being applied to the panel).

Later when I want to spend more time, I will think more and propose a design change.
In the meantime, if anyone else wants to disable it, modify [line 151 in overview.js](https://github.com/home-sweet-gnome/dash-to-panel/blob/32410a7e4178d871d6c799ad9da71d3614bdb9e9/overview.js#L151):
```
let windows = this.get_windows().filter(w => w.get_workspace().index() == activeWorkspace.index());
```
And remove the filter by workspace
```
let windows = this.get_windows();
```

**Comment by jderose9** [comment]
@smichel17 Glad you got it patched in a way that works for you!

It is intentional that the "Isolated Workspaces" setting will isolate the panel as well as overview elements so I think it makes sense that the dash appearing there would be isolated as well. This is consistent with the behavior of other extensions such as Dash-to-Dock and Isolated Workspaces.

Since we haven't gotten any other feedback (yet) that the existing behavior isn't intuitive, I think it's probably best to leave it as-is for now.

**Comment by smichel17** [comment]
For functionality, I'm happy with my workaround/patch. Since it's just one line it's no burden on me to maintain it like this, so I'm happy to do that instead of trying to convince you to upstream it.

I do have one suggestion. I think my confusion came from the wording of "Keep original gnome-shell dash". With "original", I assumed the functionality would be the same, too. I think something like "Show dash on overview" might be more clear.

Anyway, your call; I'm happy with the status quo :)

**Comment by smichel17** [comment]
For anyone who comes across this in the future, I've made a fork with a [`no-isolate-overview` branch](https://github.com/smichel17/dash-to-panel/tree/no-isolate-overview) with just this patch. It'll be maintained for as long as I use it; no guarantees about timeliness of updates.

**Comment by new-creation7** [comment]
Greetings,
Maybe the following function is more useful while the 'Isolate workspaces' is turned ON :

- If an app's icon is clicked from the GNOME Dash, Switch focus to the workspace where the existing window already resides.
- If the icon is clicked from the Panel (made by the extension), open a new window.

Currently, if the 'Dash to Panel' Extension Settings window is opened on another workspace, Overview dash does show the icon, but clicking on it does nothing. Isn't that more intuitive to focus the existing window?
