### ISSUE TITLE
Mostrar aplicaciones

### ISSUE THREAD

**Issue by josebaROD** [home-sweet-gnome/dash-to-panel#881]
Buenas, quisiera hacer una propuesta para una proxima version de la aplicación de dash-to-panel

Dentro del foro de manjaro, realice una consulta con respecto a la fonfiguracion del boton MOSTRAR APLICACION, y al parecer no tiene una opcion similar con el mismo funcionanmiento que el MOSTRAR APLICACION de dash-to-dock, donde uno tiene la opcion de poner al comienzo del dock.

En dash-to-panel no existe la forma de poner al principio el boton mostrar aplicacion

Les adjunto el link del forum, donde incluyo una imagen de lo que pretendia

[https://forum.manjaro.org/t/configuracion-desklets-calender/127050/4](url)

gracias, muy buena la extension. Use en todas las distro linux que instale.

Saludos

**Comment by charlesg99** [comment]
Hi, this is a duplicate of #150 and #822, please contribute further over there. Thanks!
