### ISSUE TITLE
Error: second argument to Lang.bind() must be a function, not undefined.

### ISSUE THREAD

**Issue by Mr-Pyro** [home-sweet-gnome/dash-to-panel#882]
Ubuntu: 19.10,
gnome: 3.35.91

**Comment by charlesg99** [comment]
Hello, please next time have a look at the existing issues first... e.g. #878 #868. Thanks!

**Comment by Mr-Pyro** [comment]
my bad did not see that one because it is marked as closed even though the issue is still present.
