### ISSUE TITLE
[Feature Request] Remove the number next to the preview title

### ISSUE THREAD

**Issue by raulcraveiro** [home-sweet-gnome/dash-to-panel#883]
Hey guys! Is there a way to remove that number 1 between the app logo and the title? This confuses me all the time because It looks like I have a notification for the app.

![image](https://user-images.githubusercontent.com/5623492/76156067-b472a680-60d3-11ea-9078-4e82e0966561.png)

**Comment by charlesg99** [comment]
Hello, there is no way to remove it aside from Isolating workspaces (as this number indicates on which workspace the window currently is). Thanks!

**Comment by raulcraveiro** [comment]
@charlesg99 How can I do this? On my gnome-tweaks is checked for only 1 workspace, since I don't use the workspace feature.

**Comment by charlesg99** [comment]
Look for the "Isolate Workspaces" option under the "Behavior" tab of the settings dialog. Thanks!

**Comment by raulcraveiro** [comment]
It worked! Thank you :)
