### ISSUE TITLE
left and right panel position broken on gnome 3.36

### ISSUE THREAD

**Issue by Henry78** [home-sweet-gnome/dash-to-panel#884]
dash-to-panel doesn't work on Gnome 3.36 when configured to be places left or right (top or bottom works fine). Panel is broken, it stays on top or bottom and i get a load of errors. Simple measures like logging out and back in don't help.

Errors:
[dash-to-panel_error-when-right-on-3.36.txt](https://github.com/home-sweet-gnome/dash-to-panel/files/4303833/dash-to-panel_error-when-right-on-3.36.txt)

Broken panel (left/top corner of the screen):
![Screenshot from 2020-03-08 21-40-08](https://user-images.githubusercontent.com/1314735/76170785-8483db80-6185-11ea-8586-8c4c490d51f7.png)

**Comment by jderose9** [comment]
Hi @Henry78! Are you using v29 which was released today? That would be the first version with 3.36 support.

**Comment by Henry78** [comment]
No, still was on v26. Upgraded today, left/right issue is gone.
Thanks to all of the devs for the great work!
