### ISSUE TITLE
Syntax errors on Debian 9

### ISSUE THREAD

**Issue by jansvoboda11** [home-sweet-gnome/dash-to-panel#885]
After installing both the `v29` release and the current `master` branch, the extension fails to load on Debian 9 with GNOME 3.22.2. Running `journalctl /usr/bin/gnome-shell` shows a couple of JS syntax errors:
```
JS ERROR: Exception in callback for signal: extension-found: SyntaxError: syntax error @ /home/jsvoboda2/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panel.js:570
JS ERROR: Exception in callback for signal: extension-found: SyntaxError: missing : after property id @ /home/jsvoboda2/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/progress.js:107
```
This prevents the extension from loading.

**Comment by charlesg99** [comment]
Thanks jansvoboda11! Sorry about that, the tests on those old gnome-shell versions are a bit neglected.
