### ISSUE TITLE
Favorites bar got small icons

### ISSUE THREAD

**Issue by LeoKesler** [home-sweet-gnome/dash-to-panel#887]
Hi,
I have an issue after 3.36 gnome and Dash v29.
After update, the favorites bar have small icons and sometimes no icons. 
I have the same issue using any theme, including default Adwaita.
But if I disable Dash to Panel, the favorites bar works correctly, with big icons.
I tested with all extensions disabled and the issue only happens when Dash to panel is enabled.
I am using Arch, fully updated. Gnome 3.36.  1080p. 

![Favorites-Dash_to_Panel_Issue](https://user-images.githubusercontent.com/5854679/76247157-dd06b780-621d-11ea-9355-86651a79bc31.jpg)
![Favorites-OK](https://user-images.githubusercontent.com/5854679/76247162-de37e480-621d-11ea-9285-f3e3ae49d74c.jpg)

**Comment by charlesg99** [comment]
Hello, thank you for the report, I could reproduce it on 3.36. This should be fixed on the master branch, could you confirm that it works for you as well?

@jderose9 I ended up using the default icon size in the overview for this. The only impact (that I can see) is that dragging an icon from the overview icongrid to the panel won't have the same size as the ones in the panel. Let me know if this is acceptable, I personally think it is fine as it also stops modifying the original dash icon size.

**Comment by jderose9** [comment]
@charlesg99 I think that's fine for now. We can circle back later if it becomes an issue. Thank you!

**Comment by LeoKesler** [comment]
Yes, I confirm it is fixed now.
Thank you very much.
I will close this bug report.
