### ISSUE TITLE
Wrong taskbat icon size on Ubuntu 20.04

### ISSUE THREAD

**Issue by BentHaase** [home-sweet-gnome/dash-to-panel#891]
When using this extension (commit 7fcf299e8329c673aad91dfa8755444779568f63) on `Ubuntu 20.04 `(development branch) with GNOME Shell 3.35.91, some taskbar icons have the wrong size (especially Nextcloud and JetBrains Toolbox).

This is how it looks (X session, no scaling):

![wrong_icon_size](https://user-images.githubusercontent.com/5788982/76365126-cf892480-6326-11ea-87e6-c2f0a69c2e8b.png)

Additionally [Ubuntu appindicators](https://extensions.gnome.org/extension/1301/ubuntu-appindicators/) extension was also installed.

**Comment by charlesg99** [comment]
Gonna close this as well as now that 3.36 is released, we won't address its beta issues. Thanks!
