### ISSUE TITLE
Extension settings not opening on Ubuntu 20.04

### ISSUE THREAD

**Issue by BentHaase** [home-sweet-gnome/dash-to-panel#892]
When using this extension (commit 7fcf299) on Ubuntu 20.04 (development branch) with GNOME Shell 3.35.91 the extension settings do not open. 

Tested with `gnome-tweak-tool` ('Extensions' tab) and right click on `dash-to-panel` bar -> 'Dash to Panel Settings'.

No error is shown.

**Comment by charlesg99** [comment]
Hello, here is a bit of reading #878 #868, #882 :)
Thanks!
