### ISSUE TITLE
Error after upgrading to Gnome Shell 3.36 in Arch.

### ISSUE THREAD

**Issue by calvo225** [home-sweet-gnome/dash-to-panel#893]
After upgrading to Gnome Shell 3.36, dash-to-panel stops working, however the extension configuration window is still accessible.

**Comment by charlesg99** [comment]
Hello, what version of dash to panel is that? Please make sure you have v29 installed as it is the first one that provides 3.36 support. I'm on Arch with gnome-shell 3.36 and I see no error. Thanks!

**Comment by calvo225** [comment]
Dash-to-panel v29. Once updated gnome-shell to version 3.36, dash-to-panel stopped working. I have another problem after updating gnome-shell, the icons of the applications in the grid have disappeared and maybe the problem does not come from dash-to-panel but from gnome-shell or some of its dependencies. 

Thanks!!!

**Comment by high1** [comment]
The extension is working properly here, also Arch 3.36, Wayland session.

**Comment by charlesg99** [comment]
@calvo225, did you restart your system following the 3.36 upgrade? Anything else specific with your installation? Thanks!

**Comment by calvo225** [comment]
Hi @charlesg99. Yes of course. I've restarted the computer several times. The only thing remarkable is that I use Xorg instead of Wayland due to the incompatibility with Nvidia. In the next few days I will reinstall Arch because here in Spain it will happen as in Italy and next week we may start quarantine without leaving the house for a couple of weeks due to the coronavirus, so I will have free time to do so. I'll answer if I still have problems or not once I reinstall the system.

Thank you very much.

**Comment by high1** [comment]
Maybe create another user first, log in and check if the issues are still present?

**Comment by calvo225** [comment]
Oh my god! Sometimes I'm stupid (or maybe always)... How could this not have occurred to me before? Of course, with a new user it works correctly. This thread can be closed/removed. Sorry, no problem with this.

Thank you very much.
