### ISSUE TITLE
Keeps moving to top of screen, even though configured for bottom

### ISSUE THREAD

**Issue by rlipscombe** [home-sweet-gnome/dash-to-panel#895]
I just upgraded from v26 to v29, and the instance on my primary monitor keeps moving itself to the top of the screen, even though it's configured to appear at the bottom. Moving it to one of the sides and then back to the bottom fixes it temporarily, then it moves back to the top again.

Maximizing and then restoring a window (or playing and then quitting a full-screen game) seems to trigger this consistently.

It doesn't do this on my secondary monitor.

Ubuntu 18.04.3, Gnome 3.28.

**Comment by Impendeo** [comment]
Had same issue.

Found that when the extension "hide top bar" was disabled the configured bottom location of the panel no longer jumped to top.

Did not do this prior to updating Dash to Panel.

**Comment by charlesg99** [comment]
Hello! Makes sense that it is a conflict with another extension, as I never encountered this before. Also be aware that dash to panel provides a similar hiding mechanism as "hide top bar". Going to close this for now and if we get to a point where the issue can be reproduced with only dash to panel enabled, we can re open. Thanks!
