### ISSUE TITLE
Option 'Ungroup applications' not refreshing on switching workspace

### ISSUE THREAD

**Issue by JeroenBos** [home-sweet-gnome/dash-to-panel#897]
I have turned on both options `Isolate Workspaces` and `Ungroup applications`, but they function not well together.

When I switch workspace, I expect the ungrouped applications to refresh: to reflect the applications in the workspace I switched to, however that is not the case. It does update when you open or close an application in that workspace. 

Ubuntu 18.04, Dash-to-panel in case it matters. 
I have only one monitor, so it's not related to https://github.com/home-sweet-gnome/dash-to-panel/issues/496.

**Comment by JeroenBos** [comment]
Never mind. When I built from source code it works, so it's probably already fixed.

**Comment by charlesg99** [comment]
Thanks! Yes it also works fine for me on Ubuntu 18.04.
