### ISSUE TITLE
Number overlay graphically broken

### ISSUE THREAD

**Issue by Gabik21** [home-sweet-gnome/dash-to-panel#898]
I just installed a fresh copy of Arch with GNOME 3.36 on Wayland and dash-to-panel via AUR.
For some reason the number overlay is broken for me. I used your extension on Ubuntu previously and the number overlay looked correctly.
![image](https://user-images.githubusercontent.com/22858790/76690754-b7294a80-6643-11ea-96ff-26b8edc13bf0.png)
Here is an image of a website showing off how it looks normally:
![image](https://149366088.v2.pressablecdn.com/wp-content/uploads/2017/07/dash-to-dock-thing-750x172.jpg)

**Comment by charlesg99** [comment]
Thank you for the report, Yes for some reason Clutter doesn't behave as it used to on 3.36. I'll probably have some time later/tomorrow to fix it. Gonna close this one as it's a duplicate as #896. Thanks!
