### ISSUE TITLE
Respect wm buttons layout in window preview

### ISSUE THREAD

**Issue by shibotto** [home-sweet-gnome/dash-to-panel#90]
Hi, thank you very much for you work, this extension is great!

Having the buttons in the titlebar on the left, I think it is a bit confusing right now. GNOME Shell's overview does it correctly:
![schermata del 2017-03-14 11-25-34](https://cloud.githubusercontent.com/assets/3816409/23896988/cc9af95c-08ab-11e7-9b80-eb88c83c7d0b.png)

dash-to-panel defaults to the right:
![schermata del 2017-03-14 11-25-55](https://cloud.githubusercontent.com/assets/3816409/23897040/fb267882-08ab-11e7-9e2b-99c1e9f8293e.png)

It's just a little bit annoying, so if it is not trivial to fix this please don't bother :D

**Comment by charlesg99** [comment]
Hello shibotto, a fix for this was added to master, thanks for the report!

**Comment by shibotto** [comment]
Thank you very much, I'll try this as soon as possible :D
