### ISSUE TITLE
Dash-to-Panel on 3.36 Epiphany/Gnome Web opens 2 windows when in Favorites

### ISSUE THREAD

**Issue by emulti** [home-sweet-gnome/dash-to-panel#900]
Gnome 3.36 Arch Linux x86_64
When Dash-to-Panel is installed and Epiphany is added to 'Favourites' to pin it to the panel, launching from the top bar opens two Epiphany windows, one with restored tabs, one with no page loaded.
It's almost as if 'New Window' is being called by mistake.

If Epiphany is not in favourites, only one window opens when launched by 'Super' key.
Similarly, if it is in favourites, only one window opens if it is launched by 'Super' key. 

It's only when launched from the top panel in DTP that a second browser window is opened.

**Comment by charlesg99** [comment]
Hello emulti, did a quick search and found this: https://www.reddit.com/r/gnome/comments/fltfqw/epiphany_opening_a_new_window_every_time_its/. What is the behavior on vanilla gnome-shell, does is work properly? Thanks!

**Comment by emulti** [comment]
It's the same issue, but only when Epiphany is added to 'Favorites' and launched from the top panel in Dash-to-Panel.

DTP enabled: 
- in Favorites, click icon in panel, extra window opens in addition to saved tabs
- not in Favorites, launched by typing 'Web' in overview, only saved tabs open

DTP disabled (vanilla gnome-shell):
- In Favourites, launched from Dash icon: only saved tabs open
- not in Favourites, launched by typing 'Web', only saved tabs open

Behaviour is the same on two different machines, and only seems appear when using Dash-to-Panel to launch an Epiphany 'Favourite'.

**Comment by emulti** [comment]
It may or may not be related, but on both machines the 'right click' menu on the panel stopped working (after latest Arch updates). 
On right-click of the panel a small blank area is displayed below the nine-dot menu, which can only be cleared by restarting gnome-shell.

**Comment by charlesg99** [comment]
Hello emulti, yes the right click issue is a new breaking change introduced in the latest Arch update, please see #902. 

@jderose9 I'm thinking we'll have to tag another release for this unfortunately. Poor timing, but it's a pretty serious annoyance for those using these menus (like me :).

**Comment by charlesg99** [comment]
I've opened [an issue](https://gitlab.gnome.org/GNOME/epiphany/-/issues/1152) on the Epiphany repo, let's wait and see before adding some code to dash to panel just to workaround this. Thanks!

**Comment by charlesg99** [comment]
Epiphany fixed the issue.
