### ISSUE TITLE
Counter badge size not very good

### ISSUE THREAD

**Issue by fakhamatia** [home-sweet-gnome/dash-to-panel#901]
![Screenshot from 2020-03-19 01-23-44](https://user-images.githubusercontent.com/20030910/77011200-908b4c80-6980-11ea-9e0d-29ad4e00d56c.png)

Not very good than the Telegram own counter

![Screenshot from 2020-03-19 01-24-25](https://user-images.githubusercontent.com/20030910/77011277-bdd7fa80-6980-11ea-9a79-6c26266af51c.png)

Dash to Panel v30
Ubuntu 19.10
Resolution 3840*2160

**Comment by charlesg99** [comment]
Hello fakhamatia, please restart gnome-shell following the v30 update. The badge was moved to the left of the icon in v30, it should look like this (also on gnome-shell 3.34):

![image](https://user-images.githubusercontent.com/33044886/77014174-1343e580-6948-11ea-8401-2a90cabdb512.png)

Thanks!

**Comment by fakhamatia** [comment]
![Screenshot from 2020-03-19 02-18-31](https://user-images.githubusercontent.com/20030910/77014686-1fe82e00-6988-11ea-834f-514f2431b0fe.png)

Yes its fix
But after shell restart Telegram icon its disappear 
It's there, but with no icon

![Screenshot from 2020-03-19 02-18-43](https://user-images.githubusercontent.com/20030910/77014692-224a8800-6988-11ea-8a57-b98b25538679.png)

**Comment by charlesg99** [comment]
Hello, just to be sure, the missing Telegram icon you mentioned is from the tray, not the panel, right? Thanks!

**Comment by fakhamatia** [comment]
Yes I think so

**Comment by joe733** [comment]
![Screenshot from 2021-07-19 13-49-18](https://user-images.githubusercontent.com/38415384/126127061-f1df61c7-0995-4329-9558-b50e25a57c65.png)

Hi, the badge on telegram looks blatantly proud.. :) Is it possible to tweak badge size, shape color and font? (Is it a WIP, or should I open a new issue?)

**Comment by goodwin74** [comment]
> ![Screenshot from 2021-07-19 13-49-18](https://user-images.githubusercontent.com/38415384/126127061-f1df61c7-0995-4329-9558-b50e25a57c65.png)
> 
> Hi, the badge on telegram looks blatantly proud.. :) Is it possible to tweak badge position, size, shape, color and font? (Is it a WIP, or should I open a new issue?)
> 
> And oh, it sometime goes to `...`
> 
> ![Screenshot from 2021-07-19 14-33-27](https://user-images.githubusercontent.com/38415384/126163689-e8bf53aa-e2cd-4c13-9e07-df657dbf227c.png)

Yes, I would also like to be able to adjust the font size in the counter (badge). Now it looks very big and not beautiful. Will there be such an opportunity or is it already available?
