### ISSUE TITLE
Failing Make File

### ISSUE THREAD

**Issue by santiagocarod** [home-sweet-gnome/dash-to-panel#903]
When I downloaded the latest git repository and executed:
 `make install`

It says :

`glib-compile-schemas ./schemas/`
`msgfmt -c po/de.po -o po/de.mo`
`make: msgfmt: Command not found`
`make: *** [Makefile:58: po/de.mo] Error 127`

I think is a simple mistake to fix but i don't know much about makefile yet to fix it!

Thank you!

**Comment by charlesg99** [comment]
Hello, you need to install gettext beforehand: `sudo apt install gettext`. Thanks!
