### ISSUE TITLE
Panel Intellihide does not allow updating the contents of the fullscreen window

### ISSUE THREAD

**Issue by Doaxan** [home-sweet-gnome/dash-to-panel#904]
After upgrading to version 30, I noticed a strange behavior: when the "Panel Intellihide" option is turned on and the panel is located at the bottom, switching tabs in full-screen firefox does not redraw the window and old content is displayed. Observed only in full screen mode, wayland, gnome 3.36.

**Comment by Doaxan** [comment]
I tried to record a video using the shortcut shift + control + alt + l and the bug disappeared! After disabling screen recording, it appears again ...

**Comment by charlesg99** [comment]
Hello Doaxan! I can't reproduce the issue so far, does it also happen on xorg on your machine? Thanks!

**Comment by Doaxan** [comment]
No, only in wayland. In general, work under Wayland is buggy, but this is not dash-to-panel issue.

**Comment by BartoszBartniczak** [comment]
I have noticed this same behaviour on x11. I think this is the issue for the newest version. I cannot minimalize programs using window buttons, program view freezes. After minimalizing by clicking on the panel, I can perform all the actions, but only for visible windows.

**Comment by BartoszBartniczak** [comment]
After reinstalling plugin, everything started to work fine. I think the problem appeared between 30 and 31 version.
