### ISSUE TITLE
Applications Menu - Apps hidden to the right edge after lock/unlock screen 

### ISSUE THREAD

**Issue by seliwia** [home-sweet-gnome/dash-to-panel#905]
Any time lock/unlock screen, applications dashboard have an unexpected behavior. 
Tested with default themes, and removed any extra gnome extension.
Issue fixed on gnome r or disable/enable dash to panel, even if I change a theme.
https://streamable.com/o3xa6

**Comment by seliwia** [comment]
Update: issue appears only if I set panel position left or right.

**Comment by jderose9** [comment]
@seliwia Can you provide your linux distro, version of gnome-shell, and version of dash-to-panel?

**Comment by seliwia** [comment]
@jderose9 Yup my bad, distro: arch/5.5.10, gnome-shell 3.36, dash-to-panel -v 31

**Comment by charlesg99** [comment]
Hello, thank you for the report, I could reproduce the issue. Probably a 3.36 optimization that messed up the size of the panelbox on the primary monitor. A fix for it was added to the master branch, could you please [install it](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation) to see if that helps?

**Comment by seliwia** [comment]
@charlesg99 You rock, thanks for quick fix. Works fine now.

**Comment by jderose9** [comment]
@charlesg99 was this new today? do we need another release?

**Comment by charlesg99** [comment]
@jderose9 Couldn't say since when as I don't use the vertical position myself. In addition to this one, today I also noticed/fixed another issue with the new icongrid while opening the overview on multiple monitors of different resolutions using the showapps button. The spring animation was glitching pretty bad... although it didn't crash or prevented functionality, but was still annoying. Up to you for another release, hopefully the 3.36 surprises are coming to an end :)

**Comment by seliwia** [comment]
@charlesg99 Ehm, excuse me Sir. A tiny one, fonts have some glitch. :P 
I don't know if video demonstrate helps you, https://streamable.com/aiap0 (default icons, theme etc, doesn't seem to have an impact.)

**Comment by charlesg99** [comment]
@seliwia Yes thank you I could reproduce the label distortion on 3.36. It should now be fixed on master!

**Comment by aaronrancsik** [comment]
Hello, the update just arrived, but with Super+A shortcut I can reproduce it in v35 :)
    Open 'Show Application' on non primary monitor.
    Than press Super+A (this open it on primary monitor)
    The glitch is back
