### ISSUE TITLE
intellihide was stucked by some fullscreen or maxmized windows

### ISSUE THREAD

**Issue by colben** [home-sweet-gnome/dash-to-panel#906]
**Describe the bug**
When "intellihide" turned on, the hidden panel does not appear under some full screen applications, like gnome-terminal and vmware workstation.

**Linux distribution and version**
Arch

**GNOME Shell version**
3.36.0

**Dash-to-Panel version**
31

**Where was Dash-to-Panel installed from?**
Arch package manager, pamcan.

**Screenshots / Video captures**
Here is my intellihide config
![2020-03-23_09-50](https://user-images.githubusercontent.com/7829126/77272594-8eacea80-6cec-11ea-8734-583e68349959.png)

**Additional Info**
It works normally at the beginning, and after the vmware workstation opened with maxmized window for a few hours, the panel appearance was stucked.

**Comment by charlesg99** [comment]
Hello, not much we can do here unless you can find a way to reliably replicate the issue. Gonna leave this opened for now. Thanks!

**Comment by pkoutsovasilis** [comment]
Hello, initially I would like to say thank you for this amazing extension! I don't know if this is the same issue with the one reported in this issue but I did notice some hiccups, when panel Intellihide is enabled, for a dual-monitor setup. More specifically, when one app is at fullscreen on one monitor and a window, on the other monitor, get the focus (attached) the panel on the other monitor becomes visible. I did try this on a single monitor setup and this effect is not present.

Ubuntu 19.10
GNOME Shell 3.34.3

![Screenshot from 2020-03-30 00-51-28](https://user-images.githubusercontent.com/12166023/77861929-cb16a400-7220-11ea-87a8-3fae89fbb1d1.png)

**Comment by charlesg99** [comment]
Hello pkoutsovasilis! How did you configure your intellihide? What you're seeing is normal if you chose to hide the panel from the "Focused window" (as your fullscreen app isn't the focused window). Could you set it to "All windows" instead?

**Comment by pkoutsovasilis** [comment]
@charlesg99 thank you for the immediate response. I never thought of actually having a look at the Intellihide setting (I wasn't even aware that they do actually exist). My bad then, I am sorry and your proposal actually "solves" the behavior reported in my previous post.

**Comment by R8bert** [comment]
what are you using for teams ?:)))
