### ISSUE TITLE
Arc Menu seems to centre all icons (lots of space)

### ISSUE THREAD

**Issue by CRCinAU** [home-sweet-gnome/dash-to-panel#907]
**Describe the bug**
Just upgraded to Fedora 32 Beta, and noticed that there is a huge space between the Arc Menu icon and the rest of the icons:

![image](https://user-images.githubusercontent.com/3992884/77279968-38a16c80-6d17-11ea-92ca-c8a21d9ba2a8.png)

When bringing up the Arc Menu:
![image](https://user-images.githubusercontent.com/3992884/77280096-8d44e780-6d17-11ea-9ca6-f2fbe2a9a141.png)

**Linux distribution and version**
Fedora 32 Beta

**GNOME Shell version**
```
# gnome-shell --version
GNOME Shell 3.36.0
```

**Dash-to-Panel version**
31

**Where was Dash-to-Panel installed from?**
Gnome Extensions via Firefox

**Comment by charlesg99** [comment]
Hello, seems like the issue was fixed by the Arc-Menu team. See https://gitlab.com/LinxGem33/Arc-Menu/-/issues/239 and https://gitlab.com/LinxGem33/Arc-Menu/-/issues/243 for more info. Going to close this as it isn't related to dash to panel. Thanks!
