### ISSUE TITLE
Can not reorder apps in taskbar

### ISSUE THREAD

**Issue by xakraz** [home-sweet-gnome/dash-to-panel#908]
**Describe the bug**

I was able to reorder the tasks' icons in the task bar.
For a few weeks now, can remember exactly when, it doesn't work anymore.

I have waited at least 2 updates from `dash-to-panel` extension before deciding to open an issue.

**Linux distribution and version**

```
OS: Manjaro Linux x86_64 (19.0.2)
DE: GNOME 3.34.4 
WM: Mutter 
Theme: Adwaita [GTK2/3] 
Icons: Adwaita [GTK2/3] 
```

**GNOME Shell version**

```
$ gnome-shell --version
GNOME Shell 3.34.4
```

**Dash-to-Panel version**

`31`

**Where was Dash-to-Panel installed from?**

The GNOME extensions website

**Screenshots / Video captures**

**Additional Info**

**Comment by charlesg99** [comment]
Hello, I can't reproduce this on 3.34 using dtp v31 (xorg and wayland), can you tell us more about your system? Does it also happens when you disable every other extensions and then restart gnome-shell? Do you see errors in your logs? Thanks!

![Peek 2020-03-23 14-34](https://user-images.githubusercontent.com/33044886/77351215-dabf5580-6d13-11ea-83e3-efc0afe58b54.gif)

**Comment by jderose9** [comment]
@xakraz Can you also verify that you don't have "Lock taskbar" chosen in the right-click menu?

![Screenshot from 2020-03-23 16-54-35](https://user-images.githubusercontent.com/2118702/77362500-655d8000-6d27-11ea-8548-4c2c44f8f3d5.png)

**Comment by xakraz** [comment]
Hi @charlesg99 and @jderose9 !

Thank you for your support :)

So I the task bar seems unlocked:
![Screenshot from 2020-03-24 10-18-16](https://user-images.githubusercontent.com/1590399/77411431-ba97a100-6dbc-11ea-8564-92c15fc3dc6d.png)

But I still can not move the icons of the tasks (I have disabled "show favorites" and this is with other extentions enabled)
![test](https://user-images.githubusercontent.com/1590399/77411483-ce430780-6dbc-11ea-8496-503f1c3e580e.gif)

Here are the options configured for DashToPanel
![Screenshot_20200324_104800](https://user-images.githubusercontent.com/1590399/77411881-6640f100-6dbd-11ea-8885-b66aedf13be5.png)
![Screenshot_20200324_104831](https://user-images.githubusercontent.com/1590399/77411883-66d98780-6dbd-11ea-9d3a-927a9fb1b84a.png)
![Screenshot_20200324_104844](https://user-images.githubusercontent.com/1590399/77411886-66d98780-6dbd-11ea-817b-43a8a4df0e35.png)
![Screenshot_20200324_104853](https://user-images.githubusercontent.com/1590399/77411887-67721e00-6dbd-11ea-8362-244087b52d16.png)

**Comment by xakraz** [comment]
Ok, it seems there is an issue with other extensions... but I was not able to identify which one or what is causing this more specificaly :disappointed: 

* When I have disabled all extensions except _DashToPanel_, it works ...
* When I enable back each extension I need, one by one, checking the reordering, it works
* Now, every extensions I need are enabled back and it works ..

I am really sorry :sweat_smile: 
Before opening this issue, I have tried several things to see if something was on my side:
* reload Gnome-shell, 
* logout / loging
* Reboot
* Update

But same results. It seems there is a race condition somewhere.

What can I do to help more ?

**Comment by xakraz** [comment]
Update !

I have 2 notices to share:

1 - The extension causing an issue seems to be _WorkspaceToDock_
2 - However, when _UserTheme_ is activated and the NON default theme is used ... it works

With no theme:
![no_theme](https://user-images.githubusercontent.com/1590399/77451200-a7082c80-6df4-11ea-9002-94ea14938b64.gif)

With a theme:
![with_theme](https://user-images.githubusercontent.com/1590399/77451314-c7d08200-6df4-11ea-8215-83f9d871cc83.gif)

**Comment by charlesg99** [comment]
Thanks for the feedback! I suggest you open an issue on the WorkspaceToDock repository, although I fear it isn't actively developed anymore.
