### ISSUE TITLE
Enhancement: rearrange panel items / different layouts

### ISSUE THREAD

**Issue by nebrelbug** [home-sweet-gnome/dash-to-panel#909]
**Describe the idea or feature you'd like**
I've disabled apps in the panel, so it looks like this: 

![Gnome-top-bar](https://user-images.githubusercontent.com/25597854/77337750-ee0bfa00-6cee-11ea-9c96-ebd2f8ff69d3.png)

Could we add ways to rearrange top panel items? For example, I'd love to put the date in the middle of the screen, and keep battery/network/volume in the right. 

None of the existing layouts allow you (as far as I can tell) to change the position of the clock/power indicators.

**Additional context**
Ideally this extension would also allow https://github.com/corecoding/Vitals to change its position correctly (I'd like it to be on the left), but that's probably a separate isuse.

**Comment by charlesg99** [comment]
Hello, please have a look at our readme's [customization gif](https://raw.githubusercontent.com/home-sweet-gnome/dash-to-panel/master/media/design/gif/customizable.gif)... As you can see, the clock can be set to the middle while the aggregate menu stays to the right. The settings for these setups can be found [here](https://github.com/home-sweet-gnome/dash-to-panel/tree/master/media/sources/D2P_import%20settings). Thanks!

**Comment by nebrelbug** [comment]
@charlesg99 thanks for the tip! I'll put my other questions in a separate issue.
