### ISSUE TITLE
New config option to display window previews in LRU order

### ISSUE THREAD

**Issue by smithfred** [home-sweet-gnome/dash-to-panel#91]
Just saw the fix for #53 in v7, thanks!

The previews should also be in LRU order. I'm not sure what the ordering is now?

This will also match the Alt-Tab preview order (when pausing with Alt held or using Alt-` on an application with multiple windows).

**Comment by jderose9** [comment]
They currently match the Windows behavior which is to keep them stable based on the order they were open. I believe KDE behaves in the same way. I don't visually inspect the preview contents each time I switch windows by clicking on them so the order stability is important. If your workflow makes you feel strongly about it, I suppose it could be configurable.

**Comment by smithfred** [comment]
It does :) A configuration option at least would be great.

Use case: several Firefox windows open (for logically differentiating between web browsing tasks), and some other applications as well. For example, two recently-opened Firefox windows in use; enough other FF windows that the preview overflows and scrolls.

To switch back to one of the two "in use" Firefox windows using the previews requires scrolling to the right every time (according to your description since they were opened "last"?)

With LRU sorting, they would appear first and second consistently - i.e. not scrolled off-screen.

With something like Firefox by the way, the "first" and "last" windows etc. can be determined by the browser's session restore behaviour, which seems to show the most recently-used window last, regardless of its original age, making this a PITA since my "main" Firefox window seems to be always scrolled off to the right.

Also, it would make it obvious which window would be shown when clicking on the launcher - always the first previewed window.

**Comment by jderose9** [comment]
By opened I meant that it is based on when the application process began rather than the last time the window was focused.

I'm curious about your scrolling issue though... Are you running at a narrow resolution or is the preview popup drawn too narrow? Ideally for usability purposes I would hope to get at least 3-4 previews visible before scrolling because the scrolling is definitely a drag..

Anyway, I think a config setting makes sense here.

**Comment by smithfred** [comment]
So how are they ordered currently with multiple windows in the same process?

I get 5 windows at 1920 pixels. But I have 12 Firefox windows open at the moment. OK, so I have a problem ;) But it's not an impossible scenario by any means.

Another option would be to grow the preview container vertically to a certain point before resorting to scrolling. But that could be annoying too maybe, especially with accidental hovers.
