### ISSUE TITLE
Error on installation via gnomeextensions.org on manjaro gnome 3.36

### ISSUE THREAD

**Issue by ccwky11** [home-sweet-gnome/dash-to-panel#910]
**Describe the bug**
Upon attempting to install via the gnome extensions website, there is an error as reported by the website. after using timeshift to restore to prior to gnome 3.36 update, dash to panel is functional once more, upon a second upgrade to gnome 3.36 Dash to panel fails to install again

**Linux distribution and version**
Manjaro 19.02
**GNOME Shell version**
3.36.0

**Dash-to-Panel version**
Version 31

**Where was Dash-to-Panel installed from?**
Gnome Extension website

**Screenshots / Video captures**
![image](https://user-images.githubusercontent.com/62629038/77490046-c6f51b80-6e07-11ea-86d7-4db64173844a.png)

**Comment by jderose9** [comment]
@ccwky11 
Please provide the error text. You can get this by pressing `Alt-F2` then typing `lg`. Go to the top right "Extensions" tab, find "Dash to Panel" in the list and then press "Show Errors".

I think there is a possibility that you simply need to restart gnome / reboot. Manjaro provides dash-to-panel as a system extension. When you install from extensions.gnome.org, it installs to your local user folder instead of the system folder. The next time gnome shell reloads, it will skip loading the system version of the extension when it sees the local version.

Also, you may have better luck with simply removing the extensions.gnome.org version and updating the system package of dash-to-panel via the Manjaro updater / pacman, as I assume you are pointed to the testing or unstable repo to get 3.36, and the packages should be pretty up to date.

**Comment by ccwky11** [comment]
Actually, this is the stable update that dropped as of today. I have tried both rebooting and removing the version from the gnome extensions website and using the version on pacman to no avail, the error that i have found was 
"TypeError: Object 0x2aa7aa0bbd20 is not a subclass of GObject_Object, it's a Object." 
Thank you for your assistance in this matter, i hope this helps.

**Comment by jderose9** [comment]
@ccwky11 I don't see this issue on Manjaro with the latest stable. v29 loads and then I can install v31 from extensions.gnome.org on top of it without issue.

Can you give us the gnome-shell log output from when the extension attempts to enable?

You can get it by opening a terminal and typing `journalctl /usr/bin/gnome-shell -f -o cat`
... then attempt to enable the extension.

**Comment by yasn77** [comment]
@jderose9 Here is my log output...

```
JS ERROR: Extension dash-to-panel@jderose9.github.com: ImportError: No JS module 'extension' found in search path
_callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:374:13
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:308:27
callback@resource:///org/gnome/shell/ui/extensionDownloader.js:204:39
gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:97:13
```

**Comment by jderose9** [comment]
Are you guys able to install any other extensions from extensions.gnome.org succesfully?

**Comment by yasn77** [comment]
> Are you guys able to install any other extensions from extensions.gnome.org succesfully?

I have similar error with 'dash to dock' and 'cast to tv'. dash to dock have a branch that has a fix (I haven't tried it myself yet) -> https://github.com/micheleg/dash-to-dock/issues/1130#issuecomment-602181078

**Comment by ccwky11** [comment]
@jderose9  I am able to install extensions from others yes, my log out put is:
`Ignoring excess values in shadow definition
An active wireless connection, in infrastructure mode, involves no access point?
Usage of object.actor is deprecated for NotificationBanner
get@resource:///org/gnome/shell/ui/environment.js:285:29
extensionShowNotification@/home/ccwky12/.local/share/gnome-shell/extensions/panel-osd@berend.de.schouwer.gmail.com/extension.js:241:9
_updateState@resource:///org/gnome/shell/ui/messageTray.js:1316:26
_onNotificationShow@resource:///org/gnome/shell/ui/messageTray.js:1178:14
showNotification@resource:///org/gnome/shell/ui/messageTray.js:862:18
addNotification@/home/ccwky12/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/shell/notification.js:263:18
AddNotificationAsync@resource:///org/gnome/shell/ui/notificationDaemon.js:815:16
_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:371:35
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:404:34

Usage of object.actor is deprecated for MessageTray
get@resource:///org/gnome/shell/ui/environment.js:285:29
extensionShowNotification@/home/ccwky12/.local/share/gnome-shell/extensions/panel-osd@berend.de.schouwer.gmail.com/extension.js:253:9
_updateState@resource:///org/gnome/shell/ui/messageTray.js:1316:26
_onNotificationShow@resource:///org/gnome/shell/ui/messageTray.js:1178:14
showNotification@resource:///org/gnome/shell/ui/messageTray.js:862:18
addNotification@/home/ccwky12/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/shell/notification.js:263:18
AddNotificationAsync@resource:///org/gnome/shell/ui/notificationDaemon.js:815:16
_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:371:35
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:404:34

Ignoring length property that isn't a number at line 1413, col 24
Ignoring length property that isn't a number at line 1413, col 24
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring length property that isn't a number at line 1413, col 24
JS ERROR: Extension dash-to-panel@jderose9.github.com: TypeError: Object 0x64e19f3ac60 is not a subclass of GObject_Object, it's a Object
_init/GObject.Object._classInit@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:448:27
registerClass@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:94:22
defineClass@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/utils.js:102:21
@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:97:28
@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panel.js:35:18
@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/intellihide.js:32:15
@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/overview.js:24:21
@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:31:18
@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:35:22
_callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:374:13
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:308:27
callback@resource:///org/gnome/shell/ui/extensionDownloader.js:204:39
gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:97:13

JS ERROR: Extension dash-to-panel@jderose9.github.com: TypeError: Object 0x64e19f3ac60 is not a subclass of GObject_Object, it's a Object
_init/GObject.Object._classInit@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:448:27
registerClass@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:94:22
defineClass@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/utils.js:102:21
@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:97:28
@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panel.js:35:18
@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/intellihide.js:32:15
@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/overview.js:24:21
@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:31:18
@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:35:22
_callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:374:13
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:308:27
callback@resource:///org/gnome/shell/ui/extensionDownloader.js:204:39
gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:97:13
`
strangely enough my dash to dock seems to work though gnome 3.36 is not supported technically, but one other extension I have is not working, that being the volume mixer in this link: https://extensions.gnome.org/extension/858/volume-mixer/

**Comment by jderose9** [comment]
It seems like you may be having separate issues. However, I can't reproduce either of them. I installed 19.02 fresh from the desktop ISO from the manjaro site, and then used the "Software Updater" UI to bring the system up-to-date (including gnome shell 3.36.0). After installing the firefox add-on for extensions.gnome.org, I had no issue installing/enabling and using v31 of dash-to-panel.

@yasn77 You seem to be failing much earlier in the initialization process. I'm curious if you can get ANY extensions installing and working? It seems like gnome-shell isn't able to find or access the entry point of the extension on disk. Maybe you could provide the output of `ls -la ~/.local/share/gnome-shell/extensions/dash-to-panel\@jderose9.github.com` ?

@ccwky11 If you are up for it, I coul give you a new utils.js file to replace in your local extension installation folder which will spit out more log info so we can try to figure out what's going on. Maybe @charlesg99 has some ideas though?

**Comment by ccwky11** [comment]
@jderose9  I would love to try that, Dash to panel makes me much more productive and I kinda hate gnome without it lol.
 
I can continually restore via timeshift to gnome 3.34 and I can use dash to panel without fail there but once I upgrade within the text only interface as manjaro recommends, I can no longer install or utilize either version of Dash To Panel, I wonder if it may not be a full gnome 3.36 update or something as I can use Dash to Dock which doesn't technically support 3.36, however, on that page there are other reports of some people getting it to work on 3.36 I am just speculating.

 I've also tried totally deleting Dash To Panel from my system and it still doesn't  work when I then reinstall, yet other extensions seem to work fine in this manner.

**Comment by yasn77** [comment]
> 
> @yasn77 You seem to be failing much earlier in the initialization process. I'm curious if you can get ANY extensions installing and working? It seems like gnome-shell isn't able to find or access the entry point of the extension on disk. Maybe you could provide the output of `ls -la ~/.local/share/gnome-shell/extensions/dash-to-panel\@jderose9.github.com` ?
> 

Other extensions work, except for the other two mentioned in https://github.com/home-sweet-gnome/dash-to-panel/issues/910#issuecomment-603943553

Interestingly, after multiple restarts and adding/removing I have a different error message:

```JS ERROR: Extension dash-to-panel@jderose9.github.com: TypeError: Object 0x2dcc0c0dbe0 is not a subclass of GObject_Object, it's a Object
                                                 _init/GObject.Object._classInit@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:448:27
                                                 registerClass@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:94:22
                                                 defineClass@/home/yasser/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/utils.js:102:21
                                                 @/home/yasser/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:106:28
                                                 @/home/yasser/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panel.js:35:18
                                                 @/home/yasser/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/intellihide.js:32:15
                                                 @/home/yasser/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/overview.js:24:21
                                                 @/home/yasser/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:31:18
                                                 @/home/yasser/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:35:22
                                                 _callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:374:13
                                                 loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:308:27
                                                 callback@resource:///org/gnome/shell/ui/extensionDownloader.js:204:39
                                                 gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:97:1```

**Comment by jderose9** [comment]
@ccwky11 You could try to force refresh your package list and make sure everything is up-to-date. I don't use pacman much but I think something like this should be what you need: `sudo pacman-mirrors --fasttrack && sudo pacman -Syyu`

You could also try to install directly from github (though this seems less likely to be the issue based on the error message)
```
sudo pacman -S base-devel
cd ~/Downloads
git clone https://github.com/home-sweet-gnome/dash-to-panel.git
cd dash-to-panel
make install
```
Then restart Gnome: `Alt-F2` then enter command `r`.

**Comment by yasn77** [comment]
@jderose9 I think mine might have been a local issue... I am running Arch and I reinstalled `gjs` package and now it works :/

Thanks for your help anyways.

**Comment by jderose9** [comment]
@yasn77 Awesome!

@ccwky11 can you also give output version of gjs? `pacman -Qi gjs`

**Comment by ccwky11** [comment]
@jderose9  Actually, your last suggestion to install from git fixed it! Thank you so much. but in case there's another problem that I can't see, is there anything wrong with this output: 

Name            : gjs
Version         : 2:1.64.0-1
Description     : Javascript Bindings for GNOME
Architecture    : x86_64
URL             : https://wiki.gnome.org/Projects/Gjs
Licenses        : GPL
Groups          : None
Provides        : libgjs.so=0-64
Depends On      : cairo  gobject-introspection-runtime  js68  dconf  readline
                  libreadline.so=8-64
Optional Deps   : None
Required By     : gnome-characters  gnome-shell  gnome-weather  sushi
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 1017.71 KiB
Packager        : Jan Alexander Steffens (heftig) <jan.steffens@gmail.com>
Build Date      : Sun 08 Mar 2020 01:35:22 AM CST
Install Date    : Wed 25 Mar 2020 02:15:39 PM CDT
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature

**Comment by ccwky11** [comment]
@jderose9  I think I had some kind of fundamental problem with GNOME because prior to this I had an (I thought) unrelated bug where gnome shell search was never completing but your suggestion fixed both, thank you again!

**Comment by jderose9** [comment]
@ccwky11 Cool! Did you also run the pacman commands first?

**Comment by ccwky11** [comment]
@jderose9 I did but I think that most (if not all) of them were reinstalling instead of installing for the first time.

**Comment by jderose9** [comment]
@ccwky11 I'm guessing that solved it, similar to @ yasn.. maybe an old package that had incorrect dependency chain and didn't get upgraded... something along those lines. Glad it's working now!

**Comment by charlesg99** [comment]
Great news! Hopefully not too much people on Manjaro get this problem!

**Comment by RazvanSt** [comment]
Thank you. Managed to fix the issue using the steps listed here.

**Comment by jderose9** [comment]
If anyone else has this issue, if they could get the version of their gjs package (`pacman -Q gjs`) before attempting to re-install it, that would be great. Thank you!

**Comment by felixoi** [comment]
Tried to reinstall the `gjs` package and did force update and install pacman packages but nothing of it works :( I have actually the same problems as @ccwky11 had. Gnome search is not completing for me too. So I'm not sure what this issue is related to.

**Comment by yasn77** [comment]
> Gnome search is not completing for me too. So I'm not sure what this issue is related to.

If you are using Appfolder extension, try disable it. That has a known issue with search and better gnome versions.

**Comment by felixoi** [comment]
Disabling AppFolders also fixes Dash to Panel for me!
