### ISSUE TITLE
Override theming if using custom Show Application icon

### ISSUE THREAD

**Issue by ariflukito** [home-sweet-gnome/dash-to-panel#911]
Dash-to-panel should override theming if using a custom Show Application icon. Otherwise there's an unwanted background colour depending on the theme. Below example is using arc dark shell theme.
![image](https://user-images.githubusercontent.com/5508660/77502319-a0d68680-6eae-11ea-9a28-9f07e8f8e0c2.png)
![image](https://user-images.githubusercontent.com/5508660/77502459-0dea1c00-6eaf-11ea-9ba8-57db83487a44.png)

Thank you.

**Comment by charlesg99** [comment]
Hello, yeah I also noticed that with the new jnsh/arc-theme on 3.36. Not sure we should add a setting for it though, as it should be easy to modify with css. @jderose9 what do you think?

**Comment by jderose9** [comment]
Hmmm.... so this is only a specific theme which has assigned a background color to that specific icon container?

**Comment by charlesg99** [comment]
Well I can't say for every theme out there, but yes this is what the Arc theme does. Not sure if this deserves a setting though. Guess we could put it in the showapps options dialog, so it wouldn't contribute too much to our settings bloat. Thanks!

**Comment by ariflukito** [comment]
This also happens on default Adwaita theme. This is on clicked state.

![image](https://user-images.githubusercontent.com/5508660/77864350-c202f280-7273-11ea-9e8d-8be359dc5647.png)

**Comment by jderose9** [comment]
@charlesg99 Can we just override the theme’s value for that container, if a custom background color is chosen in the settings? Are you worried that there will be cases where the theme would still look best with the themes background color applied even when the panel background is overridden?

**Comment by charlesg99** [comment]
Yes we could override the background color for that specific container, but at that point I'm only trying to minimize the addition of new settings :) Would you add the color/opacity options or just force it to transparent?

**Comment by ariflukito** [comment]
I think if you follow the application launcher styling it would be good enough. No need to add more settings.

**Comment by charlesg99** [comment]
A fix for this is now on master, thanks to @tper0700!
