### ISSUE TITLE
Extension fails to load on Manjaro (Gnome 3.36)

### ISSUE THREAD

**Issue by felixoi** [home-sweet-gnome/dash-to-panel#914]
**Describe the bug**
Extension fails to load.

**Linux distribution and version**
Manjaro 19.02

**GNOME Shell version**
GNOME Shell 3.36.0

**Dash-to-Panel version**
Version 31 (also tried directly from git)

**Where was Dash-to-Panel installed from?**
Tried package manager, extensions and git

**Additional Info**
I'd like to give you more info but I don't know where the logs are.

**Comment by charlesg99** [comment]
Hello felixoi! Please have a look at #910. Thanks!
