### ISSUE TITLE
Taskbar icons no longer vertically centered

### ISSUE THREAD

**Issue by rootd** [home-sweet-gnome/dash-to-panel#915]
**Describe the bug**
After updating to Gnome 3.36, my taskbar icons are no longer vertically centered. I tried disabling all other extensions and restarting Gnome, which didn't fix it.
![bug1](https://user-images.githubusercontent.com/1213925/77829708-26af3780-7124-11ea-9107-1781a493704f.png)

After switching the bar position to top, I noticed this overhang towards the bottom. This would explain why the icons no longer seem to be centered on the bottom.

![bug2](https://user-images.githubusercontent.com/1213925/77829732-52322200-7124-11ea-83f5-f0afb5bc6588.png)

**Linux distribution and version**
Manjaro with kernel 5.5.13

**GNOME Shell version**
GNOME Shell 3.36.0

**Dash-to-Panel version**
Version 31

**Where was Dash-to-Panel installed from?**
I tried both the lastest version available on GNOME extensions website, as well as installing directly from Github.

**Comment by charlesg99** [comment]
Hello, what theme are you using? Also, you said that this happens without other enabled extensions? Are you sure of that? Normally this is the result of another extension with a widget on the panel setting a fixed size, while having the panel smaller than said size. Thanks!

**Comment by rootd** [comment]
Hello,
I was using Arc Dark theme, which turnt out to be the problem (especially the Arc Dark shell theme). The theme is no longer maintenanced so I don't think it will be updated to support Gnome 3.36. I switched back to good old Adwaita and everything is fine again. Sorry for bringing up this issue!

**Comment by charlesg99** [comment]
Yes I'm using the Arc theme as well and was sad to see its support ends with 3.36. Good news though, a fork has been created/updated and it is working great for me so far on 3.36, have a look: https://github.com/jnsh/arc-theme. It's in the AUR and an easy install. Thanks!
