### ISSUE TITLE
Persistant "Show Applications" tooltip, empty tooltip at corners of screen.

### ISSUE THREAD

**Issue by keeblebrox** [home-sweet-gnome/dash-to-panel#916]
**Describe the bug**
Steps to Reproduce

1. Enable dash-to-panel extension
2. Right-click in gap area indicated in screenshot

Tooltips that appear persist until GNOME Shell restarts, or until dash-to-panel is disabled-reenabled. I haven't found any way to interact with them directly.

**Linux distribution and version**
Manjaro Kyria 19.0.2

**GNOME Shell version**
GNOME Shell 3.36.0

**Dash-to-Panel version**
v29 (Manjaro package version v29+8+gbd32412-1)

**Where was Dash-to-Panel installed from?**
Pre-installed with distribution's version of GNOME Shell.

**Screenshots / Video captures**
![Before, where to click to trigger tooltip.](https://user-images.githubusercontent.com/1428389/77834399-e0090f80-711a-11ea-913c-5ec241b81398.png)
![After, tooltips that persist until dash-to-panel is disabled-reenabled.](https://user-images.githubusercontent.com/1428389/77834412-fc0cb100-711a-11ea-86c2-9bf62bf0c385.png)

**Additional Information**
[Exported dash-to-panel settings](https://github.com/home-sweet-gnome/dash-to-panel/files/4397960/dash-to-panel-settings.txt)

**Comment by charlesg99** [comment]
Hello keeblebrox, please update the extension to [v31](https://github.com/home-sweet-gnome/dash-to-panel/releases/tag/v31) and see #902. Thanks!
