### ISSUE TITLE
Failes to load

### ISSUE THREAD

**Issue by joecksma** [home-sweet-gnome/dash-to-panel#918]
**Describe the bug**
Dash-to-Panel failes to load, be it with my settings or the default ones. The output of journalctl is provided below.

**Linux distribution and version**
 Manjaro 19.02

**GNOME Shell version**
3.36.0

**Dash-to-Panel version**
31

**Where was Dash-to-Panel installed from?**
- package-manager
- after it stopped working I installed it from git directly - but it resulted in the same bug.

**Additional Info**

##### sudo journalctl /usr/bin/gnome-shell | grep dash-to-panel

```
Mär 29 12:33:25 host gnome-shell[1568]: JS ERROR: Extension dash-to-panel@jderose9.github.com: TypeError: Object 0x19d907baf220 is not a subclass of GObject_Object, it's a Object                                     
    defineClass@/usr/share/gnome-shell/extensions/dash-to- 
    panel@jderose9.github.com/utils.js:102:21 @/usr/share/gnome-shell/extensions/dash-to- 
    panel@jderose9.github.com/appIcons.js:97:28
    @/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panel.js:35:18
    @/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/intellihide.js:32:15
    @/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/overview.js:24:21
    @/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:31:18
    @/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:35:22
```

**Comment by charlesg99** [comment]
Hello joecksma, please see #910 for this Manjaro issue. Thanks!
