### ISSUE TITLE
Applicatinons go flying into the abiss if I have the panel on the left or right side.

### ISSUE THREAD

**Issue by paulwin1** [home-sweet-gnome/dash-to-panel#920]
https://www.reddit.com/r/gnome/comments/frnmb3/so_this_keeps_happening_after_the_machine_goes_to/

Posted this issue on reddit so you should probably see it there.

**Comment by charlesg99** [comment]
Hello paulwin1! Yes that's a new issue that came with 3.36 and it is fixed on our master branch, but not yet released on e.g.o. Could you [install from github](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github) if possible? Please see #905 for more info. 

@jderose9 We should probably release a new version, as more and more people are gonna face this one I'm afraid.

**Comment by jderose9** [comment]
@charlesg99 Will do so ASAP.

**Comment by coreyhuinker** [comment]
I'm also experiencing this. I have installed from git-source and if I see the issue again I will reply to this thread.

**Comment by charlesg99** [comment]
@coreyhuinker Thanks for searching existing issues before opening a new one :)

**Comment by coreyhuinker** [comment]
@charlesg99 - I had no words to describe what it did, then I spotted this "abyss" ticket and figured it had to be the same thing.

**Comment by paulwin1** [comment]
Thanks guys. Using the Latest release of Manjaro and it seems to be fixed NICE
