### ISSUE TITLE
Panel blocks dropdown menu of Pycharm

### ISSUE THREAD

**Issue by ptoews** [home-sweet-gnome/dash-to-panel#922]
**Describe the bug**
Pycharm opens a dropdown menu which I cannot interact with in the area of the panel. 

**Linux distribution and version**
Ubuntu 18.04 LTS

**GNOME Shell version**
3.28.4

**Dash-to-Panel version**
31

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
![image](https://user-images.githubusercontent.com/1062119/77921483-1d4ada00-72a0-11ea-83d1-dd7a47f1de2c.png)
This is the area where it still works, as the hand-symbol indicates. When I click here, the dropdown entry is selected.

![image](https://user-images.githubusercontent.com/1062119/77921566-3b183f00-72a0-11ea-9a02-2b14f2cc15fb.png)
This is the area where it doesn't work, note the different mouse pointer symbol. Clicking here results in no effect at all.

**Comment by charlesg99** [comment]
Hello ptoews, thank you for the report! Normally all Clutter elements are drawn over the windows, so this looks like a normal behavior. In this case the panel is transparent, but what does it look like if you set the panel with an opaque color? Does the Pycharm drop down appears over the panel? Did you encounter this with other applications? (I'm too poor for jetbrains products, so I can't test with them :) Thanks!

**Comment by ptoews** [comment]
Hi charles, the behavior is exactly the same after setting "Panel background opacity" to 100%:
![image](https://user-images.githubusercontent.com/1062119/78041221-b812e980-7370-11ea-8c64-6b4b5ca30edb.png)
I haven't experienced this anywhere else as far as I remember. PyCharm Community Edition (which I'm using) is free and open source by the way and I highly recommend it ;)

**Comment by charlesg99** [comment]
> PyCharm Community Edition (which I'm using) is free and open source by the way and I highly recommend it ;)

Cool I'll install it later and see if I can figure out a way to workaround this. I wonder which toolkit Pycharm is using to draw its context menu. I'm pretty sure the same would happen over other gnome-shell elements. Thanks!

**Comment by charlesg99** [comment]
Hello ptoews, I did install Pycharm and I believe it is an issue with the toolkit it is using (swingx). I did some tests and any visual element under the context menu prevented its usage. Here is an example with the "Window list" extension.

![Peek 2020-05-02 20-10](https://user-images.githubusercontent.com/33044886/80895363-1275d180-8cb2-11ea-99f7-ff845e9e82c3.gif)

I think you should report the issue to JetBrains. Thanks!

**Comment by ptoews** [comment]
Thanks a lot for your time investigating this issue. I just opened an issue for pycharm, linked for reference: https://youtrack.jetbrains.com/issue/PY-42198
