### ISSUE TITLE
Application overview persists

### ISSUE THREAD

**Issue by IF-Adin** [home-sweet-gnome/dash-to-panel#923]
**Describe the bug**
The application overview/grid persists, even when installing gno-menu or arc-menu. Is there any way to get rid of it?

**Linux distribution and version**
Ubuntu 19.10

**GNOME Shell version**
GNOME Shell 3.34.3

**Dash-to-Panel version**
31

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
![Bildschirmfoto von 2020-03-30 21-43-51](https://user-images.githubusercontent.com/11959695/77954892-a1688600-72cf-11ea-9eb4-7f83a3346a03.png)

**Comment by charlesg99** [comment]
Hello, just disable the Show applications icon option.

![image](https://user-images.githubusercontent.com/33044886/77967739-bdf6c500-72b3-11ea-8913-6306f3774f5b.png)
