### ISSUE TITLE
'Show Application' after open, icons realign, if I have different resolution monitors + VIDEO PROOF

### ISSUE THREAD

**Issue by aaronrancsik** [home-sweet-gnome/dash-to-panel#924]
**Describe the bug**
After Gnome 3.36 update:
'Open Application' application icons do a realign glitch. 
If open 'Show Application' on a monitor with different resolution than a monitor opened 'Show Application'  before, the icon grid make a realign to the different resolution.

**Linux distribution and version**
Manjaro

**GNOME Shell version**
GNOME Shell 3.36.0

**Dash-to-Panel version**
31

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
https://youtu.be/aY3vlVcmX9M

**Comment by charlesg99** [comment]
Hello aaronrancsik, thank you for reporting it. This issue is already fixed on master if you want to install the extension from github. It isn't released yet on e.g.o., but should be soon. Please see https://github.com/home-sweet-gnome/dash-to-panel/issues/905#issuecomment-602298882 for more information. Thanks!

**Comment by aaronrancsik** [comment]
Hello,
Super! 
Thanks for your works!

**Comment by aaronrancsik** [comment]
Hello, the update just arrived, but with Super+A shortcut I can reproduce it  :) 
1. Open 'Show Application' on non primary monitor.
2. Than press Super+A (this open it on primary monitor)
3. The glitch is back  
Thanks for your work guys!

**Comment by charlesg99** [comment]
Hey aaronrancsik, yes thank you, I can see the issue when using Super+A (didn't even know about that shortcut :) after opening the overview with the show applications button of a secondary monitor having a different resolution. I'll try to fix this soon, but I would say that it isn't a show stopper for now. Let's aim to fix this one for the Ubuntu 20.04 release (April 23). Thanks!

**Comment by charlesg99** [comment]
Hello again aaronrancsik! I had a bit of time to look into this, I realize now that my initial approach wasn't great, as I only accounted for the opening of the grid using our show applications button. I added some tweaks to the master branch, which should globally fix the problem. Please try it and let us know if that works for you! Thanks!

**Comment by aaronrancsik** [comment]
Ok, thanks, I'm on it, and feedback soon :)

**Comment by aaronrancsik** [comment]
Work like a champ! :)
