### ISSUE TITLE
Dynamic workspaces randomly stop work

### ISSUE THREAD

**Issue by AnachronyX** [home-sweet-gnome/dash-to-panel#925]
Dynamic workspaces randomly stop work when Dash to Panel extension is enabled. No new workspaces are automaticaly generated, old empty workspaces stay open, even if they should be automaticaly deleted. For e.g. Gnome session ended with three or four active workspaces, but with only one app window on the first one. It looks like it doesn't occur in vanilla Gnome.

Manjaro Linux 19.0.4, updated.

GNOME Shell 3.36.0

Dash-to-Panel version ver. 31 installed from the GNOME extensions website.

https://imgur.com/pN7ofpF

**Comment by charlesg99** [comment]
Hello AnachronyX, dynamic workspaces are working fine here on 3.36. We had a bunch of issues with Manjaro, did read #910? Thanks!

**Comment by AnachronyX** [comment]
Hello, it looks like this issue is caused by Auto Move Windows extension, which I initially disabled, but after last system update it was enabled again. You can  close or delete this bug report. Thanks for your time.

**Comment by charlesg99** [comment]
Glad you got it working!
