### ISSUE TITLE
vertical mode: Overview squashed

### ISSUE THREAD

**Issue by Henry78** [home-sweet-gnome/dash-to-panel#927]
**Describe the bug**
If running vertical mode after locking/unlocking the screen (maybe other events), the overview is vertically squashed. The whole overview is squashed (to the left if I configure dash-to-panel to the right). Squashed so intense, its basically unsuable, here the overview takes the right most ~ 20% of the screen.
This is resolved by turning of and on "ungroup applications".

**Linux distribution and version**
Arch

**GNOME Shell version**
GNOME Shell 3.36.1

**Dash-to-Panel version**
Dash-to-Panel version: 31

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
https://pasteboard.co/J1WioAD.jpg
https://pasteboard.co/J1WiCOC.jpg

**Comment by charlesg99** [comment]
Hello Henry78, please see #905 and #920 (still opened until the fix reaches e.g.o.). Thanks!

**Comment by Henry78** [comment]
Sorry. Did a search, but didn't find these issues.
