### ISSUE TITLE
Can't customize the all apps icon

### ISSUE THREAD

**Issue by enzosanchezewe** [home-sweet-gnome/dash-to-panel#929]
I need to move the "all apps" icon to the left, but i want the icons on the middle
![Screenshot from 2020-04-02 16-17-12](https://user-images.githubusercontent.com/62959641/78292469-75324c80-74fd-11ea-9c52-66f9d418fa24.png)

**Comment by charlesg99** [comment]
Hello enzosanchezewe, we already have 2 opened issues (#822, #150) about this, so gonna close this. Thanks!

**Comment by enzosanchezewe** [comment]
hi charlesg99 i read those issues, but no one told how to solve the problem
