### ISSUE TITLE
Add a shutdown button to the panel

### ISSUE THREAD

**Issue by mohegan** [home-sweet-gnome/dash-to-panel#931]
**Describe the idea or feature you'd like**
A shutdown button directly on the panel can be more easy to shutdown the computer (1 click instead of 3 to show the shutdown window). You can look this extension for example : [https://extensions.gnome.org/extension/1056/gnome-shutdown-button/](url)

**Is your feature request related to a problem? Please describe.**
/

**Additional context**
/
![Capture d’écran de 2020-04-02 23-15-25](https://user-images.githubusercontent.com/635456/78301057-d3c8ec00-7538-11ea-8b35-4e014f019092.png)

**Comment by jderose9** [comment]
Thanks @mohegan! I'm open to incorporating this as an option if @charlesg99 is, but I'd like to build out a better configuration interface for assigning order to the components first, so you can properly place everything.

**Comment by charlesg99** [comment]
Well I guess I'm not shutting down my computer as often as you guys :) I mean, the 3.36 extra click tickles me a little and I sure don't understand that gnome-shell "design" decision, but I only have to suffer through it once a day. 

I'm not opposed to the idea, but as Jason said, I think we first need to figure out a way to easily organize panel items (mostly how to present the settings). Thanks!

**Comment by mohegan** [comment]
So, I have modified a little the panel.js file (in dash-to-gnome) to add the power off button. It is not very elegant but it does the trick. Maybe, it can help :
```
--- panel.js.origin	2020-04-04 00:37:19.664587000 +0200
+++ panel.js	2020-04-04 01:02:25.175636720 +0200
@@ -75,6 +75,7 @@
 const T5 = 'trackerFocusAppTimeout';
 const T6 = 'scrollPanelDelayTimeout';
 
+
 function getPosition() {
     let position = Me.settings.get_string('panel-position');
     
@@ -1015,6 +1016,26 @@
             if(this._showDesktopButton)
                 return;
 
+	    // Ajout perso
+	    this._buttonShutdown = new St.Bin({
+                style_class: 'panel-button',
+                reactive: true,
+                can_focus: true,
+                x_fill: true,
+                y_fill: false,
+                track_hover: true
+            });
+            let icon = new St.Icon({
+                icon_name: 'system-shutdown-symbolic',
+                style_class: 'system-status-icon'
+            });
+
+            this._buttonShutdown.set_child(icon);
+            this._buttonShutdown.connect('button-press-event', this._startGnomePrefs);
+            this._rightBox.insert_child_at_index(this._buttonShutdown, this._rightBox.get_children().length);
+	    // Fin ajout perso
+
+
             this._showDesktopButton = new St.Bin({ style_class: 'showdesktop-button',
                             reactive: true,
                             can_focus: true,
@@ -1053,6 +1074,12 @@
             if(!this._showDesktopButton)
                 return;
 
+            // Ajout perso
+            this._rightBox.remove_child(this._buttonShutdown);
+            this._buttonShutdown.destroy();
+            this._buttonShutdown = null;
+            // Fin ajout perso
+
             this._rightBox.remove_child(this._showDesktopButton);
             this._showDesktopButton.destroy();
             this._showDesktopButton = null;
@@ -1084,6 +1111,15 @@
         });
     },
 
+    // Ajout Perso
+    _startGnomePrefs: function() {
+        let s = GLib.spawn_command_line_async('env GDK_BACKEND=x11 gnome-session-quit --power-off');
+        if(s == false) {
+            Main.notify("Couldn't start gnome-session-quit.");
+        }
+    },
+    // Fin Ajout Perso
+
     _onShowDesktopButtonPress: function() {
         let label = 'trackerFocusApp';
```

**Comment by kowalski7cc** [comment]
Is a shutdown button so necessary? I mean, GNOME's power off button is not that hidden

**Comment by mohegan** [comment]
It's not essential but it is much simpler. Three clicks to show the shutdown menu in the normal way is a lot.

**Comment by charlesg99** [comment]
I would personally prefer if this was resolved by gnome-shell itself, so maybe show some interest over there as well: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2657. Thanks!
