### ISSUE TITLE
Add reset default all settings

### ISSUE THREAD

**Issue by haunt98** [home-sweet-gnome/dash-to-panel#932]
**Describe the idea or feature you'd like**
Currently, dash to panel has reset default on some places: setting in show applications icon, ...
But I want it to reset default to all settings not only one.

**Is your feature request related to a problem? Please describe.**
Because when I mod, tweak something and if didn't work. I want to revert all settings to the default.

**Comment by charlesg99** [comment]
Hello haunt98, please have a look to our [FAQ section](https://github.com/home-sweet-gnome/dash-to-panel#faq), the command to reset all the settings is there. Thanks!

**Comment by haunt98** [comment]
Thank you, I miss out the FAQ
