### ISSUE TITLE
Peek won't go away

### ISSUE THREAD

**Issue by lnicola** [home-sweet-gnome/dash-to-panel#933]
**Describe the bug**
After upgrading to v33, peek doesn't go away (might be intermittent, I can't log out right now), switching and starting programs doesn't work any more, and the right-click menu is mispositioned and drawn incorrectly.

**Linux distribution and version**
Arch Linux

**GNOME Shell version**
3.36.1

**Dash-to-Panel version**
33

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**

![image](https://user-images.githubusercontent.com/308347/78354229-2bf10400-75b4-11ea-8ba4-41e34048d23a.png)

![image](https://user-images.githubusercontent.com/308347/78354259-39a68980-75b4-11ea-9583-cac0d1a4a3cf.png)

![image](https://user-images.githubusercontent.com/308347/78354438-8722f680-75b4-11ea-9acb-3bcdc04a364b.png)

**Additional Info**
Toggling peek in settings does not fix it. I'm too scared to disable the extension (Wayland). There's also an opacity issue with the settings window (last screenshot above). Closing the programs does not hide the window preview. Disabling the extension leaves the preview around for a couple of settings, then the shell crashes.

**Comment by charlesg99** [comment]
Hello, thank you for notifying us, this indeed happens on wayland. Seems like wayland is trying to animate a "gnome-shell" window that isn't on x11 and that special window doesn't have a MetaSurfaceActor to animate :( No idea what that "gnome-shell" window is supposed to be. Anyway a fix for it has been added to master, if you want to install it until we can get a fix released. My bad, sorry about this!

@jderose9 I guess we'll have to keep up our "daily release" tradition, as this is a crippling bug for wayland users who use peek.

**Comment by lnicola** [comment]
Thanks for the fast fix. I'm afraid I'm not too familiar with the way Gnome extensions are built, so I'll probably try the new release when it gets approved on the Gnome site.

**Comment by RutgerMoons** [comment]
It goes away for me when I switch workspaces.

**Comment by lnicola** [comment]
I tried that (scrolled on the panel), didn't work.

**Comment by RutgerMoons** [comment]
I use the keyboard shortcuts, since the panel is not responsive anymore. For me it's ctrl + alt + arrow key.

**Comment by RutgerMoons** [comment]
My workaround is not complete.

I get this bug when I peek a window for around 2 seconds or more. The preview stays visible at the top. It doesn't matter if I click it or not.

I work around by pressing the windows key. (The overlay is still present). Then switch workspace (ctrl + alt + arrow Down). There is no overlay on the second workspace.

I then go back to the previous workspace (ctrl + alt + arrow Up) and choose an active window.
Result: overlay is gone. Hope this helps you.

**Comment by charlesg99** [comment]
Hello guys, sorry about this! Until we can release another version on e.g.o., as a temporary solution you could switch to an X11 session or [install the extension from github](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github). Thanks!

**Comment by jderose9** [comment]
@charlesg99 Do you think we are still good to go on a new release?

**Comment by charlesg99** [comment]
@jderose9 Yeah, it's gonna be a [pathetic one](https://github.com/home-sweet-gnome/dash-to-panel/commit/b4601dbea2d4319aa3932d5d09394193a7d81386) :man_facepalming:, but I think the wayland issue needs to be fixed asap. Thanks!

**Comment by earth4s** [comment]
I found that Disabling "Enable window peaking" let me use peek without issue. Might be a good stop gap solution.
![section](https://user-images.githubusercontent.com/9957002/78510543-795ba580-775b-11ea-9ade-65eeecaa6c43.png)

**Comment by lnicola** [comment]
@earth4s 

> I found that Disabling "Enable window peaking" let me use peek without issue. Might be a good stop gap solution.

That didn't do anything for me, but sure, it's worth a try.

In the meanwhile the updated version (actually versions) got published. I didn't see the issue in a quick test (although it was a bit hard to reproduce), but I'll close this. Thanks again @charlesg99 for the fix.

**Comment by orditeck** [comment]
I updated to v35 from GNOME Extensions website and still experience this issue on Pop!OS 19.10. I disabled Window peaking for now.

**Comment by charlesg99** [comment]
Hello orditeck, gnome 3.34 (Pop!Os 19.10) shouldn't be affected by these changes, but it also is the only version where we can't animate the windows opacity. Is this what you're seeing? I just tested on 3.34 (xorg and wayland) and peek works as expected (minus the opacity animations).

Also, make sure to restart gnome-shell following an extension update, as it can't entirely reload the new extension. Thanks!

**Comment by orditeck** [comment]
When I put my mouse over a window, I see a small preview of that window.
If I leave my cursor on that preview, I see a peek view of that window. 
All the other windows are hidden and the only window I see is the one I'm "peeking".

My issue is that when I move my mouse, all my windows come back but the window I've peeked is still visible, kinda statically printed there, even if it was minimized before.

As suggested by @RutgerMoons, switching to another workspace and coming back does hide the window.

Sorry if it's not clear, I'm new to all this. I can record my screen if it'd help.

**Comment by charlesg99** [comment]
@orditeck Hmm strange, I just tried on 3.34.1 (Fedora 31, wayland and xorg) and 3.34.3 (a fresh PopOs 19.10, xorg), and I can't reproduce what you're describing. Does it happen with every application or only specific ones?

![Peek 2020-04-08 23-10](https://user-images.githubusercontent.com/33044886/78854024-54cb2c00-79ee-11ea-8d55-2fb8c7c6f9ec.gif)

Thanks!
