### ISSUE TITLE
Extension Setting can't be opened in Ubuntu 20.04 Beta

### ISSUE THREAD

**Issue by NachiketUN** [home-sweet-gnome/dash-to-panel#936]
**Describe the bug**
Extension Setting is not accessible from Gnome-Tweaks. On using the right click option on the panel to open settings, no window is opened.

"execution of gnome shell extensions prefs failed: command not found" I get this as a notification if I try to access the settings

**Linux distribution and version**
Ubuntu 20.04

**GNOME Shell version**
3.36.0

**Dash-to-Panel version**
Installed the latest version using the script provided in wiki.

**Where was Dash-to-Panel installed from?**
Installed it from the master branch of this git repo.

**Additional Info**
I have checked other issues similar to this, but the solutions provided there did not fix the issue.

**Comment by charlesg99** [comment]
Hello NachiketUN, starting with 3.36 I think its preferable to use the new Extensions app. Also, you say that the settings dialog doesn't open when using the context menu (right click) of the panel? I had to modify the command we use for that with 3.36, but it is working fine for me, although there currently is [a bug](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2562#note_757943) (will be fixed soon) that makes the opened dialog have no icon in the taskbar. Thanks!

**Comment by kleinHeiti** [comment]
Hello together,

as I remember the extentons app isn't installed by default.
 If you install the  gnome-shell-extension-prefs package by hand you should get the prefs dialogue again.


 
  
  
 
 Am 04.04.20, 14:53 schrieb Charles Gagnon <notifications@github.com>:

   
  Hello NachiketUN, starting with 3.36 I think its preferable to use the new Extensions app. Also, you say that the settings dialog doesn't open when using the context menu (right click) of the panel? I had to modify the command we use for that with 3.36, but it is working fine for me, although there currently is a bug (will be fixed soon) that makes the opened dialog have no icon in the taskbar. Thanks!

**Comment by jderose9** [comment]
Yeah all extension prefs are hosed up on 20.04 because they stopped including gnome-shell-extension-prefs in the base install. I’m hoping they will resolve it before release. For now I believe you can just install that package manually as @kleinHeiti stated.

**Comment by charlesg99** [comment]
So... now on Ubuntu 20.04, the new 3.36 Extensions app isn't installed and they removed gnome-shell-extension-prefs? [Neat!](https://img.memecdn.com/neat_o_1813397.jpg)

**Comment by kowalski7cc** [comment]
It happened also on Fedora that Extensions app got removed, but I got it back with 3.36.1

**Comment by Lucapz** [comment]
https://www.omgubuntu.co.uk/2020/03/distros-vs-desktops-gnome-os
https://www.omgubuntu.co.uk/2018/10/on-gtk-themes-broken

Sorry to sidetrack the thread and i'm sure it has nothing to do with this issue but i thought the above links might have been of interest as apparently the Gnome Devs dislike having their vanilla desktop modified.

**Comment by jderose9** [comment]
I've opened an issue here:
https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1870830

I'm hoping they will reconsider the prioritization as it is causing an error in a fresh installation of Ubuntu.

**Comment by charlesg99** [comment]
Good, hopefully it's gonna be fixed before their release. One thing though, now 20.04 is on gnome-shell 3.36.0, but by the time they release they might be on gnome-shell 3.36.1. I mention this because, starting with 3.36.1, `gnome-shell-extension-prefs` doesn't work anymore, it gives

`(gnome-shell-extension-prefs:18193): GLib-GIO-CRITICAL **: 11:00:58.898: This application can not open files.`

I made a change to dtp to use the new `gnome-extensions` CLI starting with 3.36.1, so if Ubuntu ends up shipping with 3.36.1, this is the application we'll need (as @kowalski7cc said, maybe it'll be added back, like in Fedora). Thanks!

**Comment by jderose9** [comment]
@charlesg99 Interesting, I didn't realize this. Does gnome-extensions contain the user interface elements as well?

**Comment by charlesg99** [comment]
@jderose9 Yeah it's an interesting app, the only missing feature to replace the e.g.o. website would be a search and install feature. It also has a cool functionality, it automatically downloads extension updates and install them on the next login, so no messed up upgrades!

![image](https://user-images.githubusercontent.com/33044886/78720661-15b8b000-78f4-11ea-8ffa-6275a2e759a7.png)

**Comment by smcv** [comment]
> `This application can not open files`

As far as I can tell from GNOME Shell's upstream commit history, the preferred way to launch extension preferences in sufficiently recent versions is to call `imports.misc.extensionUtils.openPrefs()`, which was added by [gnome-shell!1163](https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1163). The version in Ubuntu 20.04 doesn't have that function available yet, but Debian experimental does.

To support older GNOME versions, fall back to the `spawn` call if `imports.misc.extensionUtils` doesn't have an `openPrefs` method.

Sample code: https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/pull/203

Downstream distribution developers might try to patch back in the ability to pass an extension UUID as a command-line option to `gnome-shell-extension-prefs` like in GNOME 3.34; but if they do, it will probably only be for 3.36, and it will be necessary to call `openPrefs()` in 3.38.

(Context: I don't use this extension myself, but I'm going through GNOME Shell extensions that are packaged in Debian and making sure there are issues open to adapt them to this upstream change.)

**Comment by jderose9** [comment]
@smcv Thank you for the clarity - it’s very much appreciated!

**Comment by charlesg99** [comment]
Hey guys, I just installed ubuntu 20.04 and they're now on 3.36.1 with gnome-extensions installed by default. They even fixed the [missing icon](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2562), so all is well I think. Thanks!

**Comment by smcv** [comment]
> Downstream distribution developers might try to patch back in the ability to pass an extension UUID as a command-line option to gnome-shell-extension-prefs like in GNOME 3.34; but if they do, it will probably only be for 3.36, and it will be necessary to call openPrefs() in 3.38.

I patched this back in for Debian, and Ubuntu picked up that change; but it's [a temporary hack/workaround](https://salsa.debian.org/gnome-team/gnome-shell/-/blob/debian/master/debian/patches/extensions-app-Add-back-minimal-compatibility-with-older-.patch), is Debian-specific, and is not long-term supportable (seriously, look at the patch - I want to get rid of it as soon as possible). This will not work with the upstream version of GNOME Shell.

For full compatibility with GNOME Shell 3.36.1, it is still necessary to do something like Tudmotu/gnome-shell-extension-clipboard-indicator#203.

**Comment by charlesg99** [comment]
Hello Simon, thank you for your input. I understand that gnome-shell added a new js convenience way to open the preferences (extensionUtils.openPrefs()), but on a fully up-to-date Arch, this isn't yet available and gnome-shell-extensions-prefs has been broken for at least 10 days.

![image](https://user-images.githubusercontent.com/33044886/79045500-776d6880-7bd9-11ea-9fe9-d820c84ba778.png)

We needed another way to fix it 526f3b23d5702def69bc9677f0f917a94a88f320. As you can see, we're now opening the preferences using the new **gnome-extensions** cli instead of gnome-shell-extensions-prefs. Are you saying that this new cli is going to be removed? Thanks!

**Comment by smcv** [comment]
I don't know what the plan is for that new CLI, or whether extensions are meant to be able to use it. All I know is that in versions where `openPrefs` *is* available, it is what the upstream maintainers of GNOME Shell now recommend for extensions to use.
