### ISSUE TITLE
Favorite Applications disapear when restarted

### ISSUE THREAD

**Issue by robzombie91** [home-sweet-gnome/dash-to-panel#937]
**Describe the bug**
1. Install dash-to-panel
2. Go to dash-to-panel settings
2. Go to behaviors tab
3. Have favorite applications toggled
4. Restart
5. Applications are not on the bar until either the position of the bar is switched or show favorite applications is toggled

**Linux distribution and version**
Arch 5.6.2

**GNOME Shell version**
Gnome Shell 3.36.1

**Dash-to-Panel version**
Version 34: github compiled on April 4 at 6:00pm est

**Where was Dash-to-Panel installed from?**
Compiled from github

**Comment by charlesg99** [comment]
Hello robzombie91, could you tell us more about your system? Is is a xorg or a wayland session? Could you disable every other extensions, then restart to see if you notice the same issue? I can't replicate this and don't remember seeing something like this. I'm also on arch with gnome 3.36.1 and dtp v34. Thanks!

**Comment by robzombie91** [comment]
It was a conflict between dash-to-dock and remove dash. It's fixed now
