### ISSUE TITLE
Panel gets blocked after unlocking

### ISSUE THREAD

**Issue by srinivasakartheek** [home-sweet-gnome/dash-to-panel#938]
**Describe the bug**
After unlocking the system, dash to panel gets blocked and only truncated view is shown. After restarting the gnome everything comes to normal however

**Linux distribution and version**
Ubuntu 18.04

**GNOME Shell version**
GNOME Shell 3.28.4

**Dash-to-Panel version**
v34

**Where was Dash-to-Panel installed from?**
Installed version 33 from GNOME extensions website and updated to 34 from github

**Screenshots / Video captures**
- Before locking
![before-lock](https://user-images.githubusercontent.com/50820829/78470211-40b0d180-7745-11ea-8c83-b9325419dd7a.png)
- After unlocking
![after-unlock](https://user-images.githubusercontent.com/50820829/78470214-47d7df80-7745-11ea-965a-56d8bbd159c7.png)

**Comment by charlesg99** [comment]
Hello, I'm on Ubuntu 18.04 as well and I don't see this issue. Normally when we have issues saying that "restarting the gnome everything comes to normal", it usually is an incompatibility with another extension. Could you disable every other extensions, restart gnome-shell and then try again to see if the issue persists? If it does, could you check your logs and look for dash to panel errors? Thanks!

**Comment by charlesg99** [comment]
Also, could you try the latest master, I just made a change that could fix this as well... Thanks!

**Comment by srinivasakartheek** [comment]
I guess the problem was with Ubuntu-Dock extension. I disabled it and don't see this problem anymore. Thanks @charlesg99
