### ISSUE TITLE
false French traduction

### ISSUE THREAD

**Issue by mohegan** [home-sweet-gnome/dash-to-panel#939]
**Describe the bug**
A french traduction isn't correct in fr.po:

#: Settings.ui.h:212
msgid ""
"Tray Item Padding\n"
"(-1 = theme default)"
msgstr ""
"**Taille des éléments de la barre d'état**\n"
"(-1 = par défaut)"

In fact, **Taille des éléments de la barre d'état** should be **Marge des éléments de la barre d'état**.

**Linux distribution and version**
All

**GNOME Shell version**
All

**Dash-to-Panel version**
v34

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
If applicable, add screenshots or a link to a video capture to help explain your problem.

**Additional Info**
[fr.po.txt](https://github.com/home-sweet-gnome/dash-to-panel/files/4433895/fr.po.txt)

**Comment by charlesg99** [comment]
Oui en effet! Ça me semble être une bonne opportunité pour un premier pull request :) Merci!

**Comment by charlesg99** [comment]
I went ahead and added you proposed modification as we're about to release a new version. Thanks!

**Comment by mohegan** [comment]
Thanks !
