### ISSUE TITLE
Can't move desktop icons near Dock

### ISSUE THREAD

**Issue by Keb0ir** [home-sweet-gnome/dash-to-panel#940]
I can't move desktop icons near the Dock. There are about 400 pixel near the dock that are not usable for me. I cannot move icons near it. Especially annoying if the dock is at the Top of the screen. If I turn on Auto hide this dead space disappears.

Ubuntu 19.10
Gnome Shell 3.34.3
Dash to Panel Version. 33 installed from Gnome Extensions
I use Nemo to draw my Desktop Icons and they are only shown on my main screen. Which is a 4k Screen. 

Here is screen grab illustrating my problem.
https://nextcloud.averylongipaddress.de/s/BLosxH7RgSC4egX

**Comment by charlesg99** [comment]
Hello Keb0ir, seems like it's the space of the window preview clipping container. Normally this area shouldn't affect other elements and inputs, but apparently Nemo isn't detecting it as such (maybe it doesn't use gnome-shell methods to do so). Is putting your desktop icons in that area the only action that you can't do? Thanks!

**Comment by Keb0ir** [comment]
I just noticed the right click menu will also be moved upwards/downwards if click in the "dead space". Windows behave completely normal. 
I also wanted to see what happens on my other screens because they are Full HD. They don't have that Problem. I can move icons as close to the dock as I want there. Thanks!
