### ISSUE TITLE
An option to keep pinned favourites clustered at the start of the panel.

### ISSUE THREAD

**Issue by GlacierFox** [home-sweet-gnome/dash-to-panel#942]
An option to cluster pinned favourites to a specific point on the panel and have them stay there when apps are launched, perhaps open all apps to the right of them. Currently, when opening a pinned app, the app opens in the midst of these icons and separates them over the bar and looks a bit messy when the 'ungroup applicaction' option is enabled.
Of course it works fine for users who don't use this expanded tab view like me bit the option would be nice.

![Screenshot from 2020-04-06 13-03-32](https://user-images.githubusercontent.com/9074086/78556555-16274d00-7807-11ea-893a-6be03ec27f18.png)

Thanks.

**Comment by charlesg99** [comment]
Hello GlacierFox, I think what you're asking for already exists:

![image](https://user-images.githubusercontent.com/33044886/78561622-0f3c1280-77e6-11ea-9187-0c1e14c827a0.png)

Thanks!

**Comment by GlacierFox** [comment]
> Hello GlacierFox, I think what you're asking for already exists:
> 
> ![image](https://user-images.githubusercontent.com/33044886/78561622-0f3c1280-77e6-11ea-9187-0c1e14c827a0.png)
> 
> Thanks!

You are right. Embarassed I didn't realize the option was already there. Apologies and thank you!
