### ISSUE TITLE
Translate into spanish right mouse button options

### ISSUE THREAD

**Issue by calotam** [home-sweet-gnome/dash-to-panel#943]
Please, can you translate into spanish next items? Thanks.
- Power options -> Energía
- Event logs -> Registros
- System -> Acerca de
- Device Management -> Pantallas
- Disk Management -> Discos
- Terminal -> Terminal
- System Monitor -> Monitor del sistema
- Files -> Carpeta personal
- Extensions -> Extensiones
- Settings -> Configuración
- Unlock taskbar -> Desbloquear barra de tareas
- Opciones de Dash to Panel -> Opciones de Dash to Panel

**Comment by charlesg99** [comment]
Hello calotam, would you be interested in translating our Spanish text? Our last Spanish translation goes back to 2017, so it is far from up to date. If you'd like I could help you getting started. Thanks!

**Comment by calotam** [comment]
Thanks! Let me know about labels you need to translate into spanish. I can tell you english labels not translated into spanish:

* Position -> Posición
- Left -> Izquierda
- Right -> Derecha
- Top, with plugin icons collapsed to bottom -> Arriba, con iconos contraídos
- Top, with fixed center plugin icons -> Arriba, con iconos fijos centrados
- Top, with floating center plugin icons -> Arriba, con iconos flotantes centrados
- Center, fix in the middle of monitor -> Centrado, fijo en mitad del monitor
- Center, floating between top and bottom elements -> Centrado, flotando entre los elementos superiores e inferiores
- Display the main panel on -> Mostrar el panel principal sobre
- Display panels on all monitors -> Mostrar los paneles en todos los monitores
- Default -> Por defecto
- Top of plugin icons -> Parte superior de los iconos
- Bottom of plugin incos -> Parte inferior de los iconos
- Top of system indicators -> Parte superior de los indicadores del sistema
- Bottom of system indicators -> Parte inferior de los indicadores del sistema
- Top of taskbar -> Parte superior de la barra de tareas
- Bottom of taskbar -> Parte inferior de la barra de tareas
- Multi-monitor options -> Opciones multi-monitor
- Isolate monitors -> Aislar monitores
- Display favorite applications on all monitors -> Mostrar aplicaciones favoritas en todos los monitores
- Display the clock on all monitors -> Mostrar el reloj en todos los monitores
- Display the status menu on all monitors -> Mostrar el menú de estado en todos los monitores
- Require presure at the edge of the screen to reveval the panel -> Requiere presión en el borde de la pantalla para revelar el panel
- Only hide secondary panels (requires multi-monitors option) -> Sólo esconder los paneles secundarios (requiere de opción multi-monitor)
- Keyboard shorcut to reveval and hold the panel -> Atajo de teclado para revelar y sostener el panel
- Delay before enabling intellihide on start (ms) -> Retraso antes de habilitar ocultación inteligente al comienzo (ms)

* Style -> Estilo
- Override panel theme background color -> Cambiar el color de fondo del tema del panel
- Override panel theme background opacity -> Cambiar la opacidad de fondo del tema del panel
- Panel background opacity -> Opacidad del fondo del panel
- Dynamic background opacity -> Opacidad dinámica del fondo
- The panel background opacity is affected by -> La opacidad del fondo del panel está afectada por
- Change opacity when a window gets closer than (px) -> Cambiar la opacidad cuando una ventana se aproxima (px)
- Change opacity to (%) -> Cambiar la opacidad a (%)
- Opacity change animation duration (ms) -> Duración de la animación de cambio de opacidad

* Comportamiento
- Show running applications -> Mostrar aplicaciones activas
- Show applications icon style padding (px) -> Mostrar relleno de estilo de icono de aplicaciones
- Show desktop bottom heigh (px) -> Mostrar la altura inferior del escritorio
- Reveval the desktop when hovering the Show Desktop button -> Mostrar el escritorio al pasar el ratón sobre el botón Mostrar Escritorio
- Delay before revealing when hovering the Show Desktop button (ms) -> Retraso cuando se pasa el botón Mostrar Escritorio antes de mostrar (ms)
- Fade duration (ms) -> Duración al desvanecer

(here i stop, in other moment i will continue with 'Comportamiento' --> 'mostrar vista rápida de ventanas al pasar el ratón'

**Comment by charlesg99** [comment]
Great, although, could you please do your translations in [this file](https://github.com/home-sweet-gnome/dash-to-panel/files/4452236/es.zip)? You might want to edit the file with a po editor (there are many, I use the Gnome one called "Translation Editor" and it works well). Thanks!

**Comment by calotam** [comment]
Hello, i continue with translations into spanish

* Comportamiento' --> 'mostrar vista rápida de ventanas al pasar el ratón'
- Time (ms) before hiding (100 is default) -> Tiempo (ms) antes de ocultar (100 por defecto)
- Immediate on application icon click -> Inmediatamente al pulsar el icono de aplicación
- Animation time (ms) -> Tiempo de animación (ms)
- Middle click on the preview to close the window -> Pulsación en botón intermedio de la vista previa para cerrar la ventana
- Window previews preferred size (px) -> Tamaño preferido de la vista previa de ventana (px)
- Window previews aspect ratio X (width) -> Relación de aspecto X de la vista previa de ventana (ancho)
- Window previews aspect ratio Y (heigh) -> Relación de aspecto Y de la vista previa de ventana (alto)
- Window previews padding (px) -> Relleno de la vista previa de ventana (px)
- Use custom opacity for the previews background -> Usar opacidad personalizada para el fondo de las vistas previas
- Close button and header position -> Botón de cierre y posición del encabezado
- Display window preview headers -> Mostrar encabezados de la vista previa de venana
- Font size (px) of the preview titles -> Tamaño de fuente (px) de los títulos de la vista previa
- Font weight of the preview titels -> Ancho de fuente de los títulos de la vista previa
- inherit from theme -> heredado del tema
- normal
- más fino
- en negrita
- más en negrita
- Font color of the preview titles -> Color de la fuente de los títulos de la vista previa
- Font weight of applications titles -> Ancho de fuente de los títulos de las aplicaciones

* Action -> Acción
- Toggle simple / Preview multiple -> Alternar simple / Vista previa múltiple
- Alternar ventanas
- Lanzar ventanas
- Do nothing -> No hacer nada
- Switch workspace -> Cambiar espacio de trabajo
- Cycle windows -> Ventanas cíclicas
- Change volume -> Cambiar volumen
- Show window previews on hotkey -> Mostrar vista previa de ventanas en tecla de acceso directo
- Hotkeys are activated with -> Teclas de acceso director activadas con
- Select which keyboard number keys are used to activate the hotkeys -> Selecciona qué teclas numéricas se usan para activar las teclas de acceso directo
- Number row -> Fila numérica
- Number keypad -> Teclado numérico
- Both -> Ambos

* Retoques
- Keep original gnome-shell dash (overview) -> Conservar el dash original de gnome-shell (vista principal)
- Activate panel menu buttons (e.g. date menu) on click only -> Activar los botones del menú del panel (p.e. menú de fecha) sólo al pulsar
- Force Activities hot corner on primary monitor -> Forzar las actividades de la esquina 'caliente' en el monitor principal

* Acerca de
- Export and import settings -> Exportar e importar configuración
- Use the buttons below to create a settings file from your current preferences that can be imported on a different machine. -> Usa los botones de abajo para crear un archivo de configuración de tus preferencias actuales que se pueda importar a otra máquina.
- Export to file -> Exportar a fichero
- Import from file -> Importar de fichero
- Updates -> Actualizaciones
- This allows you to update the extension directly from the GitHub respository. -> Te permite actualizar la extensión directamente del repositorio de GitHub.
- Be aware, these official Dash to Panel releases might not be reviewed yet on extensions.gnome.org! Read more -> ¡Sé consciente de que estas versiones oficiales de 'Dash to Panel' podrían no estar todavía revisadas en extensions.gnome.org! Leer más
- Periodically check for updates -> Comprobar periódicamente actualizaciones.
- Check now -> Comprobar ahora


Thats all!!!!!

In other moment, i will put this translations into your example file.

**Comment by calotam** [comment]
Hi! Here you are the file translated into spanish.
[es_translated.zip](https://github.com/home-sweet-gnome/dash-to-panel/files/4454965/es_translated.zip)

**Comment by charlesg99** [comment]
Hey calotam, thank you! I added your translation to the master branch!

**Comment by calotam** [comment]
Thanks to you!

**Comment by calotam** [comment]
I receive a new update of 'DashToPanel', but I cant see the spanish translations.
