### ISSUE TITLE
Information Update from the - ArcMenu Team

### ISSUE THREAD

**Issue by LinxGem33** [home-sweet-gnome/dash-to-panel#944]
Hi 

Just a quick update we have setup a mirror repository here on GitHub for issue support and code contributions etc to make it easier for our users and developers to collaborate on different platforms our mirror repository is located here : https://github.com/LinxGem33/gnome-shell-extension-arcmenu

Please feel free to close this issue once read :)

Kind regards - **LinxGem33**

**Comment by charlesg99** [comment]
Thanks Andy, got it!

**Comment by jderose9** [comment]
Awesome, thanks for the heads up!
