### ISSUE TITLE
Keyboard Layout Indicator pointing "down"

### ISSUE THREAD

**Issue by speltriao** [home-sweet-gnome/dash-to-panel#945]
-Ubuntu 20.04 LTS - Everything updated (gnome-shell-extension-prefs installed manually)
-Dash to panel installed from source

When adding more than one keyboard layout, Gnome top panel receives an option to switch between them. There's a small down arrow besides the current language. 
In dash to panel set on the bottom of the screen, this small arrow should point "up", not "down", as the menu to change layouts will appear at the top of the panel.
![bug](https://user-images.githubusercontent.com/38846168/78629198-b8c5e700-786c-11ea-8ecc-74cd1a260009.png)
![bug2](https://user-images.githubusercontent.com/38846168/78629199-b9f71400-786c-11ea-8e3a-aaab5ede38e5.png)

**Comment by charlesg99** [comment]
Hello speltriao! Yes thank you I could reproduce the issue, it is now fixed on the master branch. Thanks!
