### ISSUE TITLE
Custom icon theme for apps in the panel

### ISSUE THREAD

**Issue by Amathadius** [home-sweet-gnome/dash-to-panel#948]
When the panel is small, the gnome-theme application icons don't look great. It might be nice to be able to choose a more suitable icon theme or to choose a dark version of the theme to contrast with the panel.

![image](https://user-images.githubusercontent.com/9408075/78786742-468df900-7977-11ea-80f0-8a27e6868f7f.png)

**Comment by jderose9** [comment]
@Amathadius If I understand what you are asking for properly, you will want to do this via Gnome Tweaks.

**Comment by Amathadius** [comment]
I meant a theme (or variant) of icons just for the panel. Or at least, for the taskbar.

**Comment by charlesg99** [comment]
Hello Amathadius, unfortunately, I don't think this is our responsibility to provide custom icons. Best thing you could do is ask the icon creators to provide better scalable icons (although most of them already use the svg format). I use the Flat-remix icons and they scale down quite well I find.

@jderose9 I would close this.
