### ISSUE TITLE
Tweener can be replace by Clutter Animations

### ISSUE THREAD

**Issue by MartinPL** [home-sweet-gnome/dash-to-panel#949]
There is potential to drop Tweener. Shell and Dash to Dock did that.

**Comment by charlesg99** [comment]
> Shell and Dash to Dock did that

Shell and Dash to Dock do not seem to care about backward compatibility :)

Of course it would be possible to support both animation methods in our codebase, but I don't see the point of introducing that added complexity. Having a "smoother" animation method retrofitted could have been beneficial on older gnome-shell versions where all animations felt kinda choppy. Now, I find, on gnome-shell 3.34+ where Ease was made available, other performance improvements made Tweener more than adequate for us. I'm sure we would be hard pressed seeing a difference between Tweener and Ease for _our_ animations on 3.36. Perhaps Shell moving to Ease did improve a bit that damn spring animation though, but not enough yet :)

@jderose9 Your thoughts?

**Comment by AndrewZaech** [comment]
Hi @charlesg99, 

Looks like GNOME will be dropping Tweener.js very soon on 3.36

https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1200

**Comment by jderose9** [comment]
Looks like that's only been merged to master which is currently marked as 3.37.0, so I think we are good for right now but will need to update before the 3.38 release.

**Comment by charlesg99** [comment]
Yeah I was glad as well to see that 3.36 was branched. Phew! Thanks for the heads up Andrew!

**Comment by AndrewZaech** [comment]
> Looks like that's only been merged to master which is currently marked as 3.37.0, so I think we are good for right now but will need to update before the 3.38 release.

Oops didn't notice that. Heads up for 3.38 then 😄

**Comment by charlesg99** [comment]
Hey guys, since this is inevitable, I added to master the use of Clutter animations on gnome-shell versions >= 3.34. Seems to be working well so far. Thanks!
