### ISSUE TITLE
Distorted 'tray icons' on panel

### ISSUE THREAD

**Issue by Tamas-Toth-ebola** [home-sweet-gnome/dash-to-panel#951]
**Describe the bug**
Dear Dev(s)!

I like very much your fantastic extension so firstly I want to thanks for it!

But sadly I have some problems with the layout as how you can see on the attached screenie there are distorted icons on the panel. The problematic icons are just the normal application icons what I mentioned as 'tray icons'. All the Gnome Shell extension icon are fine.

![Screenshot from 2020-04-10 15-12-14](https://user-images.githubusercontent.com/25765137/78993514-20ff1c00-7b3e-11ea-87fd-2e01efee993a.png)

Could you please solve it and use them in 16x16px containers as all standard Gnome Shell panel icons? If they could aligned really in size (maybe with custom settings for just the normal application icons) for the extension icons without distortion would be perfect!

The screenshot from a 4k monitor with double pixel density, while the settings of the Dash to Panel is the following:

Panel is vertical on right side of screen.

Panel size: 50px
App Icon Margin: 0px
App Icon Padding: 13px

Tray Item Padding: 8px
Status Icon Padding: 4px
LeftBox Padding: -1px

Lot of thanks for your efforts in advance!

**Linux distribution and version**
Ubuntu 20.04 beta (Official)

**GNOME Shell version**
GNOME Shell 3.36.1

**Dash-to-Panel version**
version: 35 (Latest from extensions.gnome.org)

**Where was Dash-to-Panel installed from?**
extensions.gnome.org

**Screenshots / Video captures**
Already attached.

**Additional Info**
Already detailed.

**Comment by charlesg99** [comment]
Hello Tamas-Toth-ebola! Thank you for the report, I could reproduce the issue on Ubuntu 20.04. Looks like their tray -icons extension (ubuntu-appindicators@ubuntu.com) has a rendering issue when the panel is set to a size that is larger than 48px. I've looked into their code and they are forcing the icon's height to 16px. Not sure why they do so, but it is causing the scaling issue. If I remove this height assignment (appIndicator.js:302), I get the desired result. 

![image](https://user-images.githubusercontent.com/33044886/79013848-987d7d00-7b37-11ea-8147-d1c6d420bccf.png)

I've tried different settings with the default gnome-shell's panel and different scaling factors, but can't see any difference with the icons without this height assignment, so it might be worth it to bring the issue to the Ubuntu folks. 

Thanks!

**Comment by Tamas-Toth-ebola** [comment]
Thank you very much for your fast response. Tomorrow will try without that forced 16px height. Thanks again!

**Comment by Tamas-Toth-ebola** [comment]
@charlesg99 you are absolutely right!!!

Thanks for your investigation. If I'm comment out that icon height definition line the result is as fine as you can see on the following screenshot.

![Screenshot from 2020-04-11 10-45-46](https://user-images.githubusercontent.com/25765137/79039509-01213400-7be2-11ea-9d7d-aa059f1ad60e.png)

I really do not want to mix multiple thoughts into one but as question I throw 2 relevant:

1. The AppIndicator handled icons (I mean not directly own Gnome Shell extension icons as we talked in the subject (Chrome, Steam, etc.)) in vertical panel open their menus below the icon (aligned to the corner) and not near the icon where is a little bit uncomfortable to move the pointer onto their options. Is it also the problem of the AppIndicator extension itself and not belong to Dash to Panel? (You can see on my screenshot.)
2. There are padding/margin differences between the icons. Basically AppIndicators icons have lot more spaces between each other as standalone Gnome Shell extensions, but sadly the standalone Gnome Shell extension panel icons also not seems to use homogeneous paddings. Do you have some tips where and how could I investigate it to help on the problem? 

Thanks for your help in advance!

_(The problem of the main subject, the fixed height thingie. Need I report to 'Ubuntu"s team' or maybe do you made it already?)_

**Comment by charlesg99** [comment]
Thanks for the feedback! I opened an issue on the appindicator's repo, hopefully they can fix it before the Ubuntu 20.04 release. 

As for your other questions,

1. I'm not sure how the position of those menus is calculated. We're using what is provided by gnome-shell, so not much we can do here aside from overriding those calculations. Seems to be working fine most of the time, although it might change with the theme you're using (not sure):
![image](https://user-images.githubusercontent.com/33044886/79048767-5f9fdf80-7bed-11ea-9141-1215bd2482d2.png)

2. You could try playing with the settings found under the "Fine-Tune" tab, see if you can get a better result. We aren't responsible for setting other extensions padding/margin though.
![image](https://user-images.githubusercontent.com/33044886/79048663-9cb7a200-7bec-11ea-9ce8-bf67e5062bd2.png)

Thanks!

**Comment by Tamas-Toth-ebola** [comment]
Hi @charlesg99 !

From one aspect I would like to thanks again for you investigation on this earlier situation. The result was more then fine for me.

But now I just would like to inform you about my other question about the heterogen paddings/margins. In the last some days I had an idea what I verified and the result had confirmed my idea. The differences between paddings/margins caused by the different panel icon/button handling of the corresponding extension. Some of them use one `hbox` parent container for the icon itself in case if there is no any requirement for it while some others use the icon as direct object on the panel.

I do not know yet if there is any official guidance or policy for them but it's absolutely sure that developers use the 2 methods on a totally random basis. There are some requirement for the `hbox` in case of extra arrow or so, but usually not this is the situation while the extension use `hbox` container also.

I just would like to inform about it you as the small simple and ugly background of why the extension icons in the practice could not be really nice.

Thanks again for your efforts and have a nice further day!

**Comment by timrichardson** [comment]
I am using pop!os. It offers the Ubuntu app indicator, and still in June there is the problem of distorted icons. Another solution is to  disable the Ubuntu extension and use a gnome extension Tray Icons.

**Comment by priyankkasera** [comment]
![Files_Panle](https://user-images.githubusercontent.com/13149535/95049394-4cd31700-0707-11eb-9180-3c5d67adb711.png)

Can anyone help me to rearrange this file panel. Thanks in advance

**Comment by priyankkasera** [comment]
![Files_Panle](https://user-images.githubusercontent.com/13149535/95049654-ce2aa980-0707-11eb-937c-63cea0f338f9.png)

Can anyone help me to rearrange this file panel. Thanks in advance

**Comment by mansoorahmedmemon** [comment]
Hover over the margin and your cursor will then you can then click and drag to adjust.
