### ISSUE TITLE
Use of action "new-window" to launch application

### ISSUE THREAD

**Issue by hmasmoudi** [home-sweet-gnome/dash-to-panel#952]
**Describe the bug**
Example: Epiphany opening a new window every time it's launched. 

**Linux distribution and version**
Custom OS: SyphaxOS.

**GNOME Shell version**
3.36.1

**Dash-to-Panel version**
_commit=14d3dc78fb4b08aa2f530bfc04839f5e4f7266e9

**Where was Dash-to-Panel installed from?**
Package Manager

**Additional Info**
AppIcon.js uses by default the "new-window" action to launch application..

this.app.launch(0, -1, false); can be used if no windows already opened.

**Comment by hmasmoudi** [comment]
Attached a proposed patch.

[appIcons.patch.txt](https://github.com/home-sweet-gnome/dash-to-panel/files/4465100/appIcons.patch.txt)

**Comment by charlesg99** [comment]
Hello hmasmoudi, thank you for reporting this issue but I'll close it because it is a duplicate of #900.
