### ISSUE TITLE
App favourites in the panel not saving

### ISSUE THREAD

**Issue by RobinOpletal** [home-sweet-gnome/dash-to-panel#954]
**Describe the bug**
Dash to Panel is not saving favorite apps on the panel on app close = can't reliably always use the same keys (Super+1,2,3...) to open favorite apps

**Linux distribution and version**
Arch latest

**GNOME Shell version**
GNOME Shell 3.36.1

**Dash-to-Panel version**
Latest

**Where was Dash-to-Panel installed from?**
Extension website

**Comment by charlesg99** [comment]
Hello RobinOpletal, could you provide more information about what happens? Normally the favorite applications are always in the same order as you set them (same as on the vanilla gnome-shell dash). If you're referring to applications that aren't in your favorites, you are right, we don't persist their order and we only open them chronologically. Thanks!

**Comment by charlesg99** [comment]
Gonna close this for now, we can reopen if you let us know of a way to replicate the issue. Thanks!
