### ISSUE TITLE
Preferences windows with weird lateral border

### ISSUE THREAD

**Issue by dasnoopy** [home-sweet-gnome/dash-to-panel#958]
Hi,  not a real bug report,  just an aesthetic suggestion :

in version35 (not checked in previous version) the  preferences window has some borders on the left and right side ..

![dtp](https://user-images.githubusercontent.com/296922/79144303-0b4c5980-7dbf-11ea-91ce-2e44a3b5e4d9.png)

Don't known if this it's by design .. Btw I did a quick mockup removing  that borders : it looks better, imo and I'm wondering if could be feasible  for your consider to remove that in future.
 
![dtp](https://user-images.githubusercontent.com/296922/79145132-6894da80-7dc0-11ea-803f-12d57e054abf.png)

- Archlinux 64 bit
- gnome 3.36.1 & gtk3 3.24.18
- gtk3 Adwaita default theme

thanks and best regards

**Comment by charlesg99** [comment]
Yeah, not sure why adwaita decided to draw its tabs like this, but I agree this looks weird on the latest version. With the arc theme it looks like this, which is fine in my opinion:

![image](https://user-images.githubusercontent.com/33044886/79641285-879ac000-8164-11ea-8e19-76c233b56606.png)

**Comment by dasnoopy** [comment]
..  ah ok, so lateral borders  is just padding  between window border and Adwaita notebook border : at the  borders are part of background window, i guess.

in fact, e.g. this is the dash to dock preferences window and border are visibile all around the notebook:
![Screenshot-19042020_0655](https://user-images.githubusercontent.com/296922/79680008-1bbf6280-820b-11ea-9a71-4740acbdeb10.png)

And for what it's worth, I prefer the version without that padding :grin: 

thanks

**Comment by charlesg99** [comment]
Yeah I agree, the side margins were removed on the master branch if you want to have a look:

![image](https://user-images.githubusercontent.com/33044886/79694410-10d1f580-823e-11ea-832d-834cd5c1f2d2.png)

Thanks!

**Comment by dasnoopy** [comment]
.. just to confirm that it is fine also here ...

Thanks a lot 
Andrea
