### ISSUE TITLE
Margin/Padding is too small on right click menu

### ISSUE THREAD

**Issue by danjjl** [home-sweet-gnome/dash-to-panel#960]
The spacing between the label `Open Windows` and the title of the open windows is too tight using the [Qogir](https://github.com/vinceliuice/Qogir-theme) shell theme.

![Screenshot-spacing](https://user-images.githubusercontent.com/747240/79213006-c0772400-7e48-11ea-94e5-9ac92c42c0df.png)

This issue is less visible using the Yaru shell theme.

**Linux distribution and version**
Ubuntu 20.04

**GNOME Shell version**
3.36.1

**Dash-to-Panel version**
v35

**Where was Dash-to-Panel installed from?**
The GNOME extensions website.

**Comment by danjjl** [comment]
Should this issue be reported here or on the Qogir issue tracker?

**Comment by charlesg99** [comment]
Hello danjjl, yes please bring this up to the Qogir team as we don't modify the styling of those context menus. It looks like they didn't update for 3.36 (I saw the same problem with the Arc theme before they updated). Thanks!
