### ISSUE TITLE
Margin issue in GNOME 3.35.91

### ISSUE THREAD

**Issue by Baytars** [home-sweet-gnome/dash-to-panel#962]
**Bug Description**
I came across the same issue as [this](https://github.com/biji/simplenetspeed/issues/16). And some tray icons, like those of Qt programs, say, [Trojan-Qt5](https://github.com/TheWanderingCoel/Trojan-Qt5), scale and spread all over their respective available spaces, and look distorted as mentioned in #951.

**Linux distribution and version**
Manjaro Linux 19.0.2

**GNOME Shell version**
3.36.1

**Dash-to-Panel version**
31

**Where was Dash-to-Panel installed from?**
pamac-gtk

**Screenshots / Video captures**
![](https://user-images.githubusercontent.com/12626208/76314775-6e992680-62fd-11ea-8703-66cbcd4e32c1.png)
![](https://user-images.githubusercontent.com/25765137/78993514-20ff1c00-7b3e-11ea-87fd-2e01efee993a.png)

**Comment by charlesg99** [comment]
Hello Baytars! Thank you for submitting this, although both issues are duplicate and they're both issues with other extensions. I would also suggest that you update to gnome-shell 3.36.1 and dash to panel v35. Thanks!

**Comment by Baytars** [comment]
Very well. The tray icon distortion issue has been fixed. It may be up to simple-net-speed to adapt to gnome shell changes.
