### ISSUE TITLE
Main panel on all monitors

### ISSUE THREAD

**Issue by VSMent** [home-sweet-gnome/dash-to-panel#965]
When enabled by default main panel sits on primary monitor. Some times I need to check selected language and other extensions, but they are only on main panel (somewhere at `Main.panel._rightBox`).

Is it possible to have same main panel on both monitors?

**Comment by charlesg99** [comment]
Hello, please have a look at #794. Thanks!

**Comment by VSMent** [comment]
Thank you for fast reply.
