### ISSUE TITLE
Activating AppMenu will not hide the menu when lock screen is triggered

### ISSUE THREAD

**Issue by steve-todorov** [home-sweet-gnome/dash-to-panel#967]
**Describe the bug**
Activating `Behavior -> Show AppMenu button` does not hide the application menu when the lock screen is triggered (i.e. `winKey + L` to lock or via gnome menu). This means you can close the last focused app from the lock screen by clicking on the menu and going to `Quit`. :) 

**Linux distribution and version**
Ubuntu 20.04

**GNOME Shell version**
3.36.1

**Dash-to-Panel version**
35

**Where was Dash-to-Panel installed from?**
extensions.gnome.org

**Screenshots / Video captures**
![FJIMG_20200424_232105](https://user-images.githubusercontent.com/2303663/80253953-ef7c6980-8682-11ea-8a9c-ea60a4925a6c.jpg)

**Comment by charlesg99** [comment]
Hello steve-todorov, I can't reproduce this so far, are you using other extensions that could interfere here? Thanks!

**Comment by charlesg99** [comment]
Nevermind I can now reproduce it. Somehow this doesn't happen on Arch having the same gnome-shell version as Ubuntu. I'll look into it later, thanks!

**Comment by charlesg99** [comment]
Alright, seems like it was the same issue as #868, but for the app menu. It should now be fixed on the master branch, could you please confirm? Thanks!

**Comment by steve-todorov** [comment]
Hi @charlesg99 - thanks for fixing it so fast! Latest master (`b420ef5`) fixes it for me! I'll be closing this :)
