### ISSUE TITLE
Isolate Workspaces interferes with Firefox multiple profiles feature

### ISSUE THREAD

**Issue by blargh-sys** [home-sweet-gnome/dash-to-panel#968]
**Describe the bug**
With Isolate Workspaces turned on, it is impossible to launch multiple instances of Firefox with different profiles from GNOME overview or application list. Attempting to do so only opens another window for the already running instance of Firefox.

**Steps to reproduce**
1. In Firefox create two profiles, say, ProfileA and ProfileB.
2. In ~/.local/share/applications/ create .desktop files with Exec fields pointing to appropriate profiles, like `Exec=firefox -P ProfileA %u`.
3. Launch one profile.
4. Turn Isolate Workspaces on.
5. Attempt to launch the other profile from overview or application list.

**Linux distribution and version**
Ubuntu 20.04

**GNOME Shell version**
3.36.1

**Dash-to-Panel version**
35

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Additional info**
No problem launching separate profiles with Isolate Workspaces turned off. I am also able to run multiple instances of Firefox with different profiles from terminal and alternative launchers such as rofi or jgmenu with Isolate Workspaces on.

**Comment by charlesg99** [comment]
Hello blargh-sys, I just tried to reproduce that and it works just fine on my end, so there must be something wrong in your .desktop files. Make sure to also add the -P switch with the desired profile to the Exec commands found under the available actions (new-window and new-private-window). Thanks!

**Comment by blargh-sys** [comment]
Yeah, it was a missing -P switch somewhere under the available actions. Sorry for wasting your time. What stumped me, though, was that things such as rofi worked as expected the whole time. Anyway, thanks!
