### ISSUE TITLE
"Show Applications" running indicators broken

### ISSUE THREAD

**Issue by speltriao** [home-sweet-gnome/dash-to-panel#969]
**Describe the bug**
Without dash-to-panel enabled, when opening the "Show applications", the running indicators are positioned correctly. But when using this extension, they all look out of the place, and make hard to read the application name.

**Linux distribution and version**
Ubuntu 20.04 LTS - Updated
**GNOME Shell version**
GNOME Shell 3.36.1

**Dash-to-Panel version**
Version 36 (installed from source)

**Screenshots / Video captures**
![without_panel](https://user-images.githubusercontent.com/38846168/80296570-d7741b00-8752-11ea-9c58-db13395525db.png)
![with_panel](https://user-images.githubusercontent.com/38846168/80296571-d8a54800-8752-11ea-98b4-08b3fb2acd08.png)
*See for example, Firefox, Files, Google Chrome and Rhythmbox names*

**Additional Info**
This bug *may* be related to https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2234

**Comment by kleinHeiti** [comment]
Hi,

This effect can also be observed when you move over the symbols. The
marker is also moved upwards (see attached pictures)
>

**Comment by charlesg99** [comment]
Hello, what resolution are you using? Do you see the same problem if you set the panel to the left side of the screen? To me this is clearly the same as bug reported to gnome-shell. I tried with a resolution of 1366x768 and I get the same result when the extension is disabled.

With dash to panel:
![image](https://user-images.githubusercontent.com/33044886/80308990-095f9e80-87a0-11ea-8730-b8b70d39cb76.png)

Without dash to panel:
![image](https://user-images.githubusercontent.com/33044886/80309030-3744e300-87a0-11ea-897b-bdb7ff464565.png)

Thanks!

**Comment by speltriao** [comment]
Yes, I'm using 1366x768 resolution as well. 
Ah, I see why I wasn't getting this bug  without dash-to-panel. 

I've disabled the "Frequent" view, and without the "Frequent" view the app indicators works.
With the default "frequent" view enabled, is broken with or without this extension, so this is a mainstream bug. 

Small detailed that I haven't noticed before. 

![Screenshot from 2020-04-26 14-03-53](https://user-images.githubusercontent.com/38846168/80314335-599e2700-87c7-11ea-9cc9-efee989181bd.png)
![Screenshot from 2020-04-26 14-07-55](https://user-images.githubusercontent.com/38846168/80314337-5acf5400-87c7-11ea-87c5-5007f5202f6c.png)
