### ISSUE TITLE
Hiding dropdown icon

### ISSUE THREAD

**Issue by b00f** [home-sweet-gnome/dash-to-panel#970]
It will be great if we can remove Dropdown small arrow next to the icons. This extension has done this job before:
https://extensions.gnome.org/extension/800/remove-dropdown-arrows/

**Comment by charlesg99** [comment]
Hello b00f, this was brought up before and we won't hide those arrows for now, we only adjust their orientation according to the panel's position. As you pointed, other extensions already do that and installing different themes is also an option to remove them. Thanks!
