### ISSUE TITLE
Add removeable disk icon on desktop (Ubuntu 20.04)

### ISSUE THREAD

**Issue by wakjoko** [home-sweet-gnome/dash-to-panel#971]
**Describe the idea or feature you'd like**
Add removeable disk icon on desktop so we can open the drive directly without opening files first and should be able to safely remove the drive using the desktop icon.

**Is your feature request related to a problem? Please describe.**
On Ubuntu 18 i can see the drive icon on plugging in the drive but not on Ubuntu 20.04. So i'm not sure if this is a bug or it is intended change.

**Comment by charlesg99** [comment]
Hello wakjoko, I'm sorry but we aren't providing desktop icons. I know that the way Ubuntu adds desktop icons changed between Ubuntu 18.04 and 20.04, so that could explain the difference. The extension used in 20.04 is "desktop-icons@soriano". Thanks!

**Comment by wakjoko** [comment]
Thanks for your response @charlesg99 , have a nice day!
