### ISSUE TITLE
the extension doesn't use the preferred theme for pop-ups

### ISSUE THREAD

**Issue by Mohsen-eng74** [home-sweet-gnome/dash-to-panel#972]
**Describe the idea or feature you'd like**
it would be great to support system-wide theme settings in the extension. I'm newbie to the GNU/Linux world, if I missed something please correct it.

**Is your feature request related to a problem? Please describe.**
whenever I enable dash to panel extension, it doesn't care about the preferred system theme. I enabled the Yaru Dark theme but pop-ups are still shown in the light theme which is not my choice. see the attachment.

**Additional context**
Distributor ID: Ubuntu
Description: Ubuntu 20.04 LTS
Release: 20.04
Codename: focal
GNOME Shell 3.36.1
https://i.imgur.com/k2dDSH1.png

**Comment by jderose9** [comment]
Hi @Mohsen-eng74 ! We don't set the color of this popup. This is defined by your Shell theme. This is different than the application theme. Make sure you have the Shell theme set also to Yaru dark:

![image](https://user-images.githubusercontent.com/2118702/80368153-45efd080-885a-11ea-9cb9-f81f95b91cbb.png)

**Comment by charlesg99** [comment]
Hello! Yes this is kinda weird that Ubuntu didn't include the User theme extension by default. Right now, on a brand new install, setting the dark theme under preferences has no effect on the shell popup.

![image](https://user-images.githubusercontent.com/33044886/80371182-7be38380-885f-11ea-87cc-98e8bdba7cdb.png)

Not sure if this is intended, but it might be a good idea to report this on the [Yaru theme repo](https://github.com/ubuntu/yaru/issues). Closing as this isn't an issue with dash to panel. Thanks!

**Comment by kleinHeiti** [comment]
Hi,

have a look at this website... Maybe IT resolves your problem
   https://www.omgubuntu.co.uk/2020/04/enable-full-dark-mode-in-ubuntu-20-04

Klein Heiti

**Comment by Mohsen-eng74** [comment]
@jderose9 @charlesg99 @kleinHeiti 
Thank you, as noted‌ above the problem was due to my misconfiguration. now, it looks perfect.
