### ISSUE TITLE
Running indicators from focused applications aren't being removed when focusing on another application.

### ISSUE THREAD

**Issue by blipk** [home-sweet-gnome/dash-to-panel#975]
**Describe the bug**
The running indicators from focused applications aren't being removed when focusing on another application.

**Linux distribution and version**
Fedora 32, Gnome-Shell 3.36.1, d2p 37 from Gnome extension website

**Screenshots**
![Screenshot from 2020-04-29 15-55-50](https://user-images.githubusercontent.com/45532845/80564939-9588f480-8a32-11ea-8de2-1fa464301b5b.png)
![Screenshot-20200429155603-672x950](https://user-images.githubusercontent.com/45532845/80564906-7ee29d80-8a32-11ea-8561-46702c281057.png)

**Comment by charlesg99** [comment]
Hello, yes this is because there is a mix between a wide and non-wide indicator style... According to our code this is normal, maybe @jderose9 can confirm? Wide indicators are SEGMENTED, CILIORA METRO and SOLID. Thanks!

**Comment by blipk** [comment]
This was not happening on the previous version.

Why would it be normal behaviour to show the focused indicator on an unfocused app?
-------- Original Message --------

**Comment by charlesg99** [comment]
Sorry about that, yes you are correct, I misdiagnosed the problem :sweat_smile: This was caused by the transition from Tweener to Clutter animations and it should now be fixed on the master branch. Could you please install it to confirm that it solves the issue on your machine as well? Thanks!

**Comment by blipk** [comment]
Perfect! Thank you.
