### ISSUE TITLE
How to get badges on icons ?

### ISSUE THREAD

**Issue by prigal** [home-sweet-gnome/dash-to-panel#977]
Hello, I'm probably missing something here, but can't find how to get badges for notification count on icons. I was waiting for them and recently ugpraded to ubuntu 20.04 / gnome 3.36 / kernel 5.6.7 and latest dashtopanel (37) because I read that it will only work with latest gnome but nothing.

Thank you :)

**Comment by charlesg99** [comment]
Hello, unfortunately the badges aren't widely used by applications, please see https://github.com/home-sweet-gnome/dash-to-panel/issues/98#issuecomment-578467584 for more information. On my end I only see the badges with Thunderbird and Pidgin. I also see the progress bar on long Nautilus operations, but that's it :( Thanks!

**Comment by prigal** [comment]
Ok, I understand. Thanks.
