### ISSUE TITLE
Epiphany launched twice

### ISSUE THREAD

**Issue by amivaleo** [home-sweet-gnome/dash-to-panel#978]
Hi!

Yesterday I upgraded my Fedora 31 to Fedora 32. So now I have gnome-shell 3.36.1 and epiphany 3.36.1. My dash-to-panel version is 37.

Epiphany is one of the applications sticked in the favourites. Whenever I click on its icon to open it, it launches two istances altogether.

It only happens with epiphany. I tried to unstick and then stick it again, but the issue remains. I also tried to re-install the extension: same result.

This issue does not affect the vanilla gnome shell dash.

Any idea on why this happens...?

**Comment by charlesg99** [comment]
Hello, thank you for bringing this up, please see #900.

**Comment by amivaleo** [comment]
Apologies for not checking first. I gave it for granted that it was related to dash to panel. Sorry. :|

I'll wait for the update of epiphany that fixes this, don't want to try the workaround suggested in reddit.

Thank you!
