### ISSUE TITLE
Window Peeking and Virtual Desktops [Bug]

### ISSUE THREAD

**Issue by cwh1te** [home-sweet-gnome/dash-to-panel#979]
**Describe the bug**
When using virtual desktops with window peeking enabled, previewing a window causes all windows from all virtual desktops to render on the current desktop. Switching virtual desktops corrects the issue until another window is previewed. Disabling window peeking prevents the issue from occurring.

**Linux distribution and version**
Manjaro 20.0

**GNOME Shell version**
3.36.1

**Dash-to-Panel version**
37

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Comment by charlesg99** [comment]
Hello cwh1te, thank you for the report. Yes with today's gnome-shell update, it seems the underlying issue that caused #928 was fixed, but now our workaround for it is causing this new issue. I also noticed that the workspace change is animating during peek, which is unintended (looks like it also was broken with 3.36). A fix for those was added to the master branch if you want to try it. Thanks!
