### ISSUE TITLE
Dynamic transparency and switching to empty workspace

### ISSUE THREAD

**Issue by vantu5z** [home-sweet-gnome/dash-to-panel#980]
If set the dynamic transparency option and maximize window (or move it closely to panel) then panel become untransparent.
And if you open Overview and switch to empty workspace then panel stay untransparent but it shouldn't. If you open some new window after then transparency will correct.

Arch
GNOME Shell 3.36.2
Dash-to-Panel version 37
Installed from the GNOME extensions website

**Comment by charlesg99** [comment]
Hello vantu5z, thank you for reporting this, I could reproduce the issue. Seems like gnome-shell isn't emitting the `switch-workspace` signal when changing workspace while in the overview. A fix for it was added to the master branch, could you install it and confirm that solves the issue? Thanks!

**Comment by vantu5z** [comment]
Yes, git version resolve issue. Thank you!

**Comment by charlesg99** [comment]
Thanks for the feedback!
