### ISSUE TITLE
Session crashes when lock screen is activated

### ISSUE THREAD

**Issue by aryklein** [home-sweet-gnome/dash-to-panel#981]
Every time I lock the screen with dash-to-panel extension extension enabled, my session closes, and it goes back to the login screen (GDM)

In the logs I can see:

```
systemd-coredump[6337]: Process 5603 (gnome-shell) of user 1000 dumped core.
```

If I disable this extension, everything works fine.

**Linux distribution and version**
Archlinux (updated)

**GNOME Shell version**
GNOME Shell 3.36.2

**Dash-to-Panel version**
Version 37

**Where was Dash-to-Panel installed from?**
From tte GNOME extensions website

**Comment by charlesg99** [comment]
Thanks, this is a regression in 3.36.2, see #976.

**Comment by aryklein** [comment]
Thanks, sorry I didn't see this issue.
