### ISSUE TITLE
Spurious animation when moving windows between monitors and other actions

### ISSUE THREAD

**Issue by chrisjbillington** [home-sweet-gnome/dash-to-panel#982]
**Describe the bug**

When using dash to panel as a traditional taskbar, such that items come and go as windows are created and destroyed or are moved between monitors (when "isolate monitors" is set), existing items in the taskbar animate a little bit, wiggling a few pixels.

I think this might have performance implications. I notice that there seem to be dropped frames (subjective, I could be wrong) when dragging windows from one monitor to another when using dash to panel with "isolate monitors", whereas moving windows between monitors seems smoother when monitors are not isolated. So I suspect that this extra unneeded animation might be contributing to this (though there is other animation). This seems to be independent of whether gnome-shell's global animations toggle is enabled, so if this is a real effect and not just in my mind, the performance blip must be due to extra work dash to panel is doing prior to those animations rather than the animating itself.

Here is a screencast. Although it looks like in the screencast the items are only wiggling about half the time, I see them wiggling all the time. The recording is at half the frame rate of my monitor so this is probably aliasing missing the frames where the items have moved. This means that the wiggles are occurring at close to the monitor refresh rate, which I guess could hint at their cause.

![Peek 2020-04-30 14-28](https://user-images.githubusercontent.com/1044087/80745932-0b529600-8aef-11ea-9b7e-b25b179e33c6.gif)

**Linux distribution and version**
Arch Linux, fully updated

**GNOME Shell version**
3.36.2, but this issue has occurred since at least as far back as 3.34.

**Dash-to-Panel version**
Git master, but this behaviour has been present for a long time.

**Where was Dash-to-Panel installed from?**
The AUR [gnome-shell-extension-dash-to-panel-git](https://aur.archlinux.org/packages/gnome-shell-extension-dash-to-panel-git) package

**Comment by charlesg99** [comment]
Hello Chris, thank you for the report. Yes this is something that has always bothered me as well. I've looked into it and couldn't find the half pixel values in the allocation chain that are probably causing this wiggling during animations. Instead I came up with a nasty fix to solve this, but I can only make it work when using a fixed width for the application titles. Could you please install the master branch to test it out?

At this point I'm wondering if we shouldn't just remove the option and always have fixed width labels (with adjustable width). Pretty sure this isn't used much... Or we can leave the option, even if there is some icon wiggling with the dynamically sized labels. Any thoughts? Thanks!

**Comment by chrisjbillington** [comment]
Well, I use fixed-width labels and don't think I would have any reason to want varialble width (harder to visually scan through a list of irregular-sized things, and less visually appealing), but wouldn't want to speak for anyone else.

Current master fixes wiggling for me! There are still dropped frames when dragging windows between monitors with isolated monitors, but this isn't necessarily dash to panel's fault given gnome-shell's own animations cause dropped frames as well.
