### ISSUE TITLE
Pending spanish translations

### ISSUE THREAD

**Issue by calotam** [home-sweet-gnome/dash-to-panel#983]
Hi! I installed last update and I could see new spanish translations, but there are pending translations: (this translations are found in the file I submitted to you)

Power Options -> Energía
System monitor -> Monitor del sistema
![Captura de pantalla de 2020-05-01 09-45-41](https://user-images.githubusercontent.com/57635310/80791409-d8ada980-8b91-11ea-8bc2-6e05d6442a4a.png)

Isolate monitors -> Aislar monitores
Display favorite applications on all monitors -> Mostrar aplicaciones favoritas en todos los monitores
![Captura de pantalla de 2020-05-01 09-47-15](https://user-images.githubusercontent.com/57635310/80791517-275b4380-8b92-11ea-9766-b7ede7bc9a30.png)

Indicator size (px)
Indicator color - Icon Dominant
![Captura de pantalla de 2020-05-01 09-48-29](https://user-images.githubusercontent.com/57635310/80791625-891bad80-8b92-11ea-9a23-f56ced865242.png)

Require pressure at the edge of the sreen to reveal the panel
Delay before enabling intellihide on start (ms)
![Captura de pantalla de 2020-05-01 09-47-41](https://user-images.githubusercontent.com/57635310/80791561-51146a80-8b92-11ea-8fc4-4a2ed295dd27.png)

Show running applications
Show tooltip on hover
![Captura de pantalla de 2020-05-01 09-49-28](https://user-images.githubusercontent.com/57635310/80791656-9f296e00-8b92-11ea-93a2-433fba0f1b5f.png)

Show Applications icon side padding (px)
![Captura de pantalla de 2020-05-01 09-49-39](https://user-images.githubusercontent.com/57635310/80791715-c5e7a480-8b92-11ea-8796-a569c32847e3.png)

Time before hiding (100 is default)
Immediate on application icon click
Animation time (ms)
Middle click on the preview to close window
Window previews aspect ratio X (width)
Window previews aspect ratio Y (height)
Window previews padding (px)
Display window previews headers
Font size (px) of the preview titles
Font weight of the preview titles
Font color of the preview titles
![Captura de pantalla de 2020-05-01 09-50-05](https://user-images.githubusercontent.com/57635310/80791798-1232e480-8b93-11ea-9fbe-704b986e2fb7.png)

Show Desktop button height (px)
![Captura de pantalla de 2020-05-01 09-49-50](https://user-images.githubusercontent.com/57635310/80791776-fcbdba80-8b92-11ea-90f7-f087aa127b79.png)

Font weight of application titles
![Captura de pantalla de 2020-05-01 09-50-28](https://user-images.githubusercontent.com/57635310/80791880-50c89f00-8b93-11ea-9d89-68669f8ba0ec.png)

Scroll icon action
Cycle windows
![Captura de pantalla de 2020-05-01 09-51-26](https://user-images.githubusercontent.com/57635310/80791928-676ef600-8b93-11ea-814e-e7e38e17ed60.png)

Show window previews on hotkey
Hotkeys are activated with
![Captura de pantalla de 2020-05-01 09-51-45](https://user-images.githubusercontent.com/57635310/80791958-7fdf1080-8b93-11ea-8581-57a592366492.png)

**Comment by charlesg99** [comment]
Thank you for letting us know calotam! Yes, sorry about that, I thought you used a po editor to complete the translation file you sent us and didn't double check. The missing translations you mentioned were still marked as "fuzzy", that's why they weren't considered when creating the mo files. It is now fixed on the master branch. Thanks!

**Comment by calotam** [comment]
Ok, thanks to you!
