### ISSUE TITLE
cannot install on Centos 7

### ISSUE THREAD

**Issue by siddbudd** [home-sweet-gnome/dash-to-panel#985]
**Describe the bug**
I tried installing via https://extensions.gnome.org/extension/1160/dash-to-panel/ and since that failed I also tried compiling from source, and compiling (make install) worked, but under Tweaks / Extensions it still shows the error symbol and cannot be enabled. 

**Linux distribution and version**
Centos 7.8.2003
Kernel: 3.10.0-1127.el7.x86_64

**GNOME Shell version**
GNOME Shell 3.28.3

**Dash-to-Panel version**
37 from GitHub

**Where was Dash-to-Panel installed from?**
1st try: The GNOME extensions website
2nd try:  directly from github

**Screenshots / Video captures**
![GNOME Tweaks_001](https://user-images.githubusercontent.com/7005706/80860904-88237280-8c9d-11ea-945d-7d14e3d34933.png)

**Additional Info**

**Comment by charlesg99** [comment]
Hello siddbudd, please provide the error shown in the looking glass. To do so, press <kbd>ALT</kbd>+<kbd>F2</kbd> then enter the "lg" command then <kbd> Enter</kbd>. In the looking glass window, on the top right you can select "Extensions", then under dash to panel click on "show errors". I just tried on gnome-shell 3.28 and it works correctly on my end.

Thanks!

**Comment by siddbudd** [comment]
Hi Charles, thanks for checking and trying to reproduce the error on your end. The error says:
`TypeError: Main.overview.viewSelector is undefined`
`TypeError: panelManager is undefined`

Probably needless to say, all other gnome extensions I tried work just fine. Only this one I could not install, the most important one. Gnome without Dash to Panel is almost unusable for me and I don't even know a good alternative.

![Workspace 1_003](https://user-images.githubusercontent.com/7005706/80865322-28d45b00-8cbb-11ea-8b45-d1ad86c1fc2e.png)

**Comment by charlesg99** [comment]
Hello, looks like the activation/installation didn't work properly. What I would first try is to disable all other extensions, restart gnome-shell, then try to activate Dash to panel. If this works, then enable your other extensions one at a time and restart gnome-shell with every newly activated extension to figure out the source of the problem. Thanks!

**Comment by siddbudd** [comment]
I removed each and every extension and then installed only Dash-to-panel, it still shows one error, namely that 
`TypeError: Main.overview.viewSelector is undefined`

Is it normal that I don't even have an Activities button in the top left? (Sorry, this is the first time I am back to Gnome 3.28.) Reason I ask: I did a quick search for viewSelector.js and found that it is related to the Activities view, which I don't have and I am not sure if that is normal. Thanks again for trying to help me.  

![Workspace 1_004](https://user-images.githubusercontent.com/7005706/80893692-2a2b7500-8d07-11ea-9600-71a138e591e0.png)

**Comment by charlesg99** [comment]
Going back in the looking glass, what is the output if you enter `imports.ui.main.overview.viewSelector` in the bottom text box and press Enter?

**Comment by siddbudd** [comment]
`r(0) = undefined`

**Comment by charlesg99** [comment]
Hmm I think you are using the "GNOME classic" session, it it possible? You need to be in a "GNOME" session for it to work. To switch session you need to log out and select "GNOME" when clicking the [little cogwheel icon](https://forums.centos.org/download/file.php?id=1724&sid=7d0366467e4dcec085e31e8268a4c8d4).

**Comment by siddbudd** [comment]
Thanks for the tips and sorry for taking your time (this was after all not a bug of this extension). Before reading your comment I simple reinstalled Gnome Desktop including GDM, now everything works just fine. I could install Dash-to-panel and it is working great.
