### ISSUE TITLE
dash-to-panel install error this._overview is undefined

### ISSUE THREAD

**Issue by taotoxht** [home-sweet-gnome/dash-to-panel#986]
**Describe the bug**
with  alt +f2 then input lg ，show error:  this._overview is undefined

**Linux distribution and version**
Ubuntu 20.04(just upgrde from 18.04)

**GNOME Shell version**
3.36.1

**Dash-to-Panel version**
37

**Where was Dash-to-Panel installed from?**
install from  source .and  Meet the same problem from the https://extensions.gnome.org/local/

**Screenshots / Video captures**
If applicable, add screenshots or a link to a video capture to help explain your problem.
![image](https://user-images.githubusercontent.com/16130118/80867510-0e07e380-8cc7-11ea-8021-be3e4b973de3.png)

**Comment by charlesg99** [comment]
Hello taotoxht, looks like the activation/installation didn't work properly. What I would first try is to disable all other extensions, restart gnome-shell, then try to activate Dash to panel. If this works, then enable your other extensions one at a time and restart gnome-shell with every newly activated extension to figure out the source of the problem. Thanks!
