### ISSUE TITLE
Fedora 32: Gnome 3.36: Wayland: Using 'Desktop Icons NG (DING)' resume from suspend to memoty issue

### ISSUE THREAD

**Issue by calotam** [home-sweet-gnome/dash-to-panel#988]
After resume from suspend in Wayland gnome session, now I have a new icon about 'Desktop Icons NG (DING). I don't know if it a issue of this extension or not. I put an issue in other extension.

In Xorg gnome session is working all ok.

![Captura de pantalla de 2020-05-03 11-09-49](https://user-images.githubusercontent.com/57635310/80910363-375c5a00-8d2f-11ea-9a4e-061e70690153.png)

**Comment by calotam** [comment]
Sorry, forget the issue. There is another issue opened in 'Desktop Icons NG (DING)'.

**Comment by charlesg99** [comment]
Yeah, looks like that extra wayland "desktop" window used to draw the icons on. Thanks!
