### ISSUE TITLE
Games in fullscreen mode

### ISSUE THREAD

**Issue by Durlyn** [home-sweet-gnome/dash-to-panel#989]
**Describe the bug**
when I launch games in full screen mode, for example ETS2, the title bar of the window remains.
if i disable dash-to-panel, then the window title bar disappears.

**Linux distribution and version**
Fedora 31, Fedora 32

**GNOME Shell version**
GNOME Shell 3.36.1

**Dash-to-Panel version**
version 37

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
![Screen_ETS2](https://user-images.githubusercontent.com/874902/80913573-41418580-8d4e-11ea-9496-88a7f5543f8d.png)

**Additional Info**

**Comment by charlesg99** [comment]
Hello, does this only happen with games? Can you reproduce the issue with other types of fullscreen window? Thanks!

**Comment by Durlyn** [comment]
Only games. RDP-client, terminal window runs normally
