### ISSUE TITLE
Conditional UnGroup Application

### ISSUE THREAD

**Issue by jay0x** [home-sweet-gnome/dash-to-panel#990]
Hello there!

I would love to have an option to expand applications selectively. I don't need to have all application expanded. There are no reason to expand (and show text) if only one window is launched. For example, Thunderbird or some messengers have only one window and don't need to have a text, small icon is just fine. But if I have 3 virtual machines running I need to be able to click on the one I need right away, and I need a text to know witch one is witch.

As I see two options how it can be done. Show text if there is more than one window or to have a list of apps to ungroup.

**Comment by koniroman** [comment]
Please take a look at my proposal:
https://github.com/home-sweet-gnome/dash-to-panel/issues/1024

It is somehow related to this. In case of Pidgin the window picture would suffice (unless many contacts use the same avatar), but for many apps the window icon is the same and thus a window text would allow to differentiate them. 
So IMO it is a good idea to have an option for the text next to icon.
