### ISSUE TITLE
Where are the rounded corners?

### ISSUE THREAD

**Issue by amivaleo** [home-sweet-gnome/dash-to-panel#991]
Hi!

I'm using the latest available version of this extension on the gnome extension website, on gnome-shell 3.36.2.

Am I lost in the settings or the rounded corners can't be shown if this extension is used?

![Schermata da 2020-05-03 16-58-37](https://user-images.githubusercontent.com/24316547/80917470-5d015780-8d5f-11ea-9f9a-2ac24bd41173.png)

**Comment by charlesg99** [comment]
Hello amivaleo, thank you for the report! This is unintended, I always forget those corners when testing  :facepalm: (I'm using the arc-dark theme, which has no corners). This is now fixed on the master branch, could you please install it and confirm that the corners are there? Thanks!

**Comment by amivaleo** [comment]
Now they are back.

But another thing needs some fixing (sorry 😄️):

![Schermata da 2020-05-03 19-58-23](https://user-images.githubusercontent.com/24316547/80921796-d22d5680-8d78-11ea-9cec-b72fd68007d7.png)

When Actvities or the the system-menu buttons are clicked, the blu underline follows the curvature of the corners.
I know this is just a very tiny thing. Can you fix it if it doesn't require too much effort?

**Comment by charlesg99** [comment]
Ha yes I remembered why we removed it initially, it is causing graphical glitches unless the system menu is at the far right or the panel (stock gnome-shell). I added it back on the master branch so it should now work in that situation only (like in your screenshot). Could you please pull/install again? Thanks!

**Comment by amivaleo** [comment]
Now it works fine in my specific case. I see it wouldn't for those users who put the clock at the end of the panel: in that case, the blu underline below the clock doesn't follow the curvature. 😄

I truly understand why you chose to get rid of this. :)

**Comment by charlesg99** [comment]
Thanks for the feedback, yeah the following is what happens with the date menu on the right:

![image](https://user-images.githubusercontent.com/33044886/80970530-4ef81900-8de9-11ea-87a2-5ac44be56772.png)

Or with the "Show desktop" button:

![image](https://user-images.githubusercontent.com/33044886/80970610-6cc57e00-8de9-11ea-8e56-4c68103270f8.png)

This is mostly a reminder for myself of why I removed it for elements other than the system menu :)
