### ISSUE TITLE
Color settings not working properly.

### ISSUE THREAD

**Issue by wildcard-f8** [home-sweet-gnome/dash-to-panel#992]
The extension doesn't apply the style color settings I set when I start up. I have to turn it off and back on for it to work. Sometimes, after exiting a full-screen app or game, I come back to the desktop and the extension's style color settings are just plain black and I have to turn it off and on to return to what I set.

This started happening when I updated from Ubuntu 18.04 to 20.04

Ubuntu 20.04

GNOME Shell 3.36.1

Dash-to-Panel version 37

I installed it from the software center back in 18.04

**Comment by charlesg99** [comment]
Hello, please provide a way to reproduce the issue, I've never seen this happening so far. Try disabling your other extensions as well. Thanks!

**Comment by wildcard-f8** [comment]
Hi, thanks for getting back to me. I'm not sure how I can provide a way to reproduce the issue. I just power-up my laptop and it starts off without the gradient setting. I can turn off the 'override panel theme gradient' setting from the extension and turn if back on and it goes into my desired setting. Later on, say when I play a full-screen game, the gradient is gone again. I look at the settings and it's still turned on, so I either turn the settings off and on again or turn the extension off and on again.

**Comment by charlesg99** [comment]
> I just power-up my laptop and it starts off without the gradient setting

So, to reproduce you set the gradient, then restart and the gradient isn't applied, correct? If so, I can't reproduce that. What other extensions do you have installed? Could you try disabling them all, leaving only dash to panel, then restart? Thanks!

**Comment by wildcard-f8** [comment]
OK, I tried starting up with only the dash-to-panel extension turned on and it seems to have worked.

The other extensions I have are:
- Activities Configurator
- Bluetooth Quick Connect
- Coverflow Alt-Tab
- GSConnect
- Sound Input & Output Device Chooser
- User Themes

The User Themes extension is causing some sort of conflict maybe?

**Comment by charlesg99** [comment]
I don't think User Themes is causing the issue, I'm using it too and have no such problem with Arc-theme. What theme are you using? Maybe loading an unsupported theme causes the issue? I would just re enable the extensions one at a time and restart after each, this way you'll know for sure which one is causing the issue. Thanks!

**Comment by wildcard-f8** [comment]
I'm using yaru-dark. But I checked them out one by one as you suggested and it seems that it's the Activities Configurator was the one causing the problem. I got rid of it and and seems to be fine now. Thanks a bunch!

**Comment by charlesg99** [comment]
Glad it's working now!
