### ISSUE TITLE
Icon disappears

### ISSUE THREAD

**Issue by jay0x** [home-sweet-gnome/dash-to-panel#993]
Icon disappears from time to time when minimizing/maximizing a window.

I know JS, but never did a gnome extension. If anyone helps me to start with debugging I can try to fix the issue myself. For now I don't even know where to start.

Ubuntu 20.04
GNOME Shell 3.36.1
Dash-to-Panel version 37
The GNOME extensions website

![vokoscreenNG-2020-05-04-14-34-20](https://user-images.githubusercontent.com/64734486/80962023-e58dff80-8e14-11ea-8cef-5b5eb25d3461.gif)

**Comment by charlesg99** [comment]
Hello, do you have a way to reliably reproduce this? I've never encountered that... Thanks!

**Comment by jay0x** [comment]
Not reliably, but It happens to me every day. Some times I need to minimize/maximize 5 times to get an icon back.

**Comment by jderose9** [comment]
@jay0x I haven't seen this issue either, but this might be helpful in getting started with debugging:

https://github.com/home-sweet-gnome/dash-to-panel/issues/58#issuecomment-277588428

Let me know if you have any questions.

**Comment by charlesg99** [comment]
Please let us know if you find the incompatibility or a way to reproduce this on a vanilla gnome-shell installation. Let's close this for now, thanks!

**Comment by Char-Aznable** [comment]
I have a similar issue but only with the "Show Applications" icon, which is customized by the User Themes extension. It used to show up correctly in the panel until the latest update where the icon becomes invisible. But if I disable this Dash-to-panel extension then the icon shows up in the dash

**Comment by charlesg99** [comment]
Hello Char-Aznable, thank you for looking at existing issues. For the Show Applications button, does it also disappears with the default gnome-shell theme set in Tweaks?

**Comment by Char-Aznable** [comment]
@charlesg99 In the default shell theme and a few other custom themes, it shows up as a grid of dots
