### ISSUE TITLE
Wrong message counter

### ISSUE THREAD

**Issue by jay0x** [home-sweet-gnome/dash-to-panel#994]
Two instances of Telegram client are running. It shows correct message count in tray, but wrong count in the panel.

Ubuntu 20.04
GNOME Shell 3.36.1
Dash-to-Panel version 37
The GNOME extensions website

![Untitled](https://user-images.githubusercontent.com/64734486/81053296-85a75f80-8ecd-11ea-99e6-d82de2b9399a.png)

**Comment by charlesg99** [comment]
Hello, how are you launching the 2 Telegram instances? The counters are using the unity Launcher API which provides the count per .desktop file. Unless you have 2 .desktop files, both icons will receive 2 count notifications and only display the latest one (in your case it looks like it was 29). Thanks!

**Comment by jay0x** [comment]
Yes, there are two Telegram instances. And NO, Unity Launcher combines them. In this case it will show "49".

**Comment by charlesg99** [comment]
Did you get a chance to try launching your 2 telegram instances using different .desktop files? Thanks!
