### ISSUE TITLE
Power, sound and other extension logo not showing up.

### ISSUE THREAD

**Issue by Oymate** [home-sweet-gnome/dash-to-panel#995]
**Describe the bug**
The part containing network connection and power off option is not showing up properly. It can not be seen when I hover over them or click them. When I turn the extension off it still is like this. But after hovering over them they got correct.[Picture](https://imgur.com/a/ADyxUAV).

**Linux distribution and version**
Pop!_OS 20.04 Non-LTS

**GNOME Shell version**
GNOME Shell 3.36.1

**Dash-to-Panel version**
37
**Where was Dash-to-Panel installed from?**
The GNOME extensions website.

**Screenshots / Video captures**
[Screenshot at the right part.
](https://imgur.com/a/ADyxUAV)**Additional Info**

**Comment by charlesg99** [comment]
Hello, v37 seems to work fine for me on Pop!_OS 20.04, do you have other installed extensions?

![image](https://user-images.githubusercontent.com/33044886/81197253-0f1e6680-8f8e-11ea-89c1-686db31ce058.png)

Thanks!

**Comment by Oymate** [comment]
Yes, I do indeed have other extension installed.(I have been using dock instead of panel after this issue started. Before that I used the dock extension but the update brock mine.
Here are a few screenshot of all the extensions I use.
![Screenshot from 2020-05-07 12-45-49](https://user-images.githubusercontent.com/50857856/81263382-64777800-9061-11ea-9747-33622511fd2e.png)
![Screenshot from 2020-05-07 12-45-55](https://user-images.githubusercontent.com/50857856/81263390-66d9d200-9061-11ea-9bf6-ec9f350f5467.png)
![Screenshot from 2020-05-07 12-45-59](https://user-images.githubusercontent.com/50857856/81263392-67726880-9061-11ea-8015-1995eade4c33.png)
Also I seem to be not able to update should I reinstall?
![image](https://user-images.githubusercontent.com/50857856/81263513-9b4d8e00-9061-11ea-8630-61124fed16d4.png)

**Comment by jderose9** [comment]
@Oymate We aren't aware of others having this issue, so you will need to disable all of the other extensions and then enable them one-by-one to see which one is conflicting.

**Comment by Oymate** [comment]
Ok, I will reply tomorrow.

**Comment by Oymate** [comment]
@jderose9 I have tried and even uninstalled some software. But, it only showed "Do not disturb bell correctly.
![image](https://user-images.githubusercontent.com/50857856/82729193-5ab76b00-9d17-11ea-9efc-108f63fdfa43.png)

**Comment by charlesg99** [comment]
Hello Oymate, here are the extensions that I have enabled (pretty much Pop!_OS default). Please try to set yours like this as well, then **restart gnome-shell** and see if the issue presists. Thanks!

![image](https://user-images.githubusercontent.com/33044886/82734287-152f7980-9ce8-11ea-8a7d-be6c2d55338e.png)

**Comment by Oymate** [comment]
Still no luck :(
Even restarted with changed settings.
![image](https://user-images.githubusercontent.com/50857856/82754969-6e83cf80-9df2-11ea-9b41-7c834fdc2bb1.png)
![image](https://user-images.githubusercontent.com/50857856/82754976-7d6a8200-9df2-11ea-89bc-e5627ed09013.png)
![image](https://user-images.githubusercontent.com/50857856/82754983-88bdad80-9df2-11ea-993e-541a7865747d.png)

**Comment by Oymate** [comment]
Should I give any config file or check the icon folder?

**Comment by Oymate** [comment]
Could this issue be an extension of [this one](https://github.com/home-sweet-gnome/dash-to-panel/issues/998#issue-614970980)?
https://github.com/home-sweet-gnome/dash-to-panel/issues/998#issue-614970980

**Comment by charlesg99** [comment]
Omg I almost hope this isn't only this, but what is the value of your "Tray Font Size" slider under the Fine-Tune tab of the settings dialog?

![image](https://user-images.githubusercontent.com/33044886/82850670-4c11b500-9ecb-11ea-95fa-58e1d7c02431.png)

**Comment by Oymate** [comment]
It is.
http://www.quickmeme.com/img/80/80cc0f4c808f3d976d72ee71d6527f49820f016c977145327776238a22e33957.jpg
Thanks for supporting me for so long though.

**Comment by charlesg99** [comment]
Lol I was almost sure I would see Picard when clicking your meme link, and there he was :) Glad it's resolved!
