### ISSUE TITLE
Black screen after Gnome's wake up

### ISSUE THREAD

**Issue by Amathadius** [home-sweet-gnome/dash-to-panel#996]
**Describe the bug**
Gnome goes to sleep normally (now), but when I wake it up, it's the total black screen with only my cursor still moving.

**Linux distribution and version**
Archlinux

**GNOME Shell version**
GNOME Shell 3.36.2

**Dash-to-Panel version**
37.r22.g0dd48e0-1

**Where was Dash-to-Panel installed from?**
aur/gnome-shell-extension-dash-to-panel-git

**Screenshots / Video captures**
If applicable, add screenshots or a link to a video capture to help explain your problem.

**Additional Info**

**Comment by antnieszka** [comment]
I have something similar on openSUSE Thumbleweed. In my case "lock" does nothing, the UI just restarts.

**GNOME Shell version**
GNOME Shell 3.36.2

Installed from: https://extensions.gnome.org/extension/1160/dash-to-panel/
version 37

**Comment by charlesg99** [comment]
Hello, sounds a lot like #976... There is still a related issue opened about this on the gnome-shell repo: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2757. Not sure at which exact version of gnome-shell openSUSE is currently at. Thanks!

**Comment by charlesg99** [comment]
Also related it seems, a black screen on unlock is reported here : https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2685

**Comment by jderose9** [comment]
Closing at it seems like this is unrelated to dash-to-panel and just need to wait for a fix from upstream.
