### ISSUE TITLE
Icons in sys tray are invisible even if actually present.

### ISSUE THREAD

**Issue by Mangus78** [home-sweet-gnome/dash-to-panel#998]
**Describe the bug**
After upgrading to Ubuntu 20.04, when placing the panel vertically, either on left or right side, tray icons of minimized apps like dropbox, skype or steam are not visible, even if they're there. If I click on the apparently blank space, the contex menu of everey single apps appears. Look at the attached screenshot for an example with dropbox.
There are no problem whatsoever if I place the panel orizzontally at top or bottom, and I can correctly see every icons.

**Linux distribution and version**
Ubuntu 20.04

**GNOME Shell version**
3.36.1

**Dash-to-Panel version**
37

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
![immagine](https://user-images.githubusercontent.com/7537334/81446370-0c349900-917b-11ea-870d-922571a471f4.png)

**Additional Info**

**Comment by elucidsoft** [comment]
+1

**Comment by charlesg99** [comment]
Hello, yes this seems to happen when changing the "Status icon padding" in the "Fine-Tune" tab of the settings. This is pretty much the same issue as #951, as modifying the ubuntu-appindicators@ubuntu.com extension fixes the problem:

![image](https://user-images.githubusercontent.com/33044886/82277195-452bf500-9955-11ea-810d-5dcefcc91e32.png)

I've already opened an issue for this on the ubuntu-appindicators repository (https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/227), but didn't get much interest so far :(

Thanks!

**Comment by charlesg99** [comment]
Gonna close this for now, please voice your concern to the app-indicator developers in the issue I opened over there or install another tray icons extensions, like [Tray Icons: Reloaded](https://extensions.gnome.org/extension/2890/tray-icons-reloaded/). Thanks!
