### ISSUE TITLE
Bottom panel interferes with swipe up gesture for onscreen keyboard

### ISSUE THREAD

**Issue by esjarc** [home-sweet-gnome/dash-to-panel#999]
**Describe the idea or feature you'd like**
I'd like to see an option to disable the "drag to unmaximise" gesture/functionality that comes with the (default and Dash to Panel) GNOME panel.

**Is your feature request related to a problem? Please describe.**
If Dash to Panel is set to display on the bottom of the screen, the currently focused and maximised window gets unmaximised when you swipe up from the bottom of the screen to access the onscreen keyboard. You can also experience this behaviour when dragging from an empty spot on the panel with your mouse. In general this "drag to unmaximise" feature seems to only make sense when the panel is set to be displayed on the top (as your titlebar is always on the top).

**Comment by jderose9** [comment]
@esjarc The only place I am aware you can drag to unmaximize is in the window title bar, and I don't see any conflict with the on-screen keyboard. Is this what you are referring to?

**Comment by esjarc** [comment]
@jderose9 I've created a video to illustrate the unmaximise behaviour: https://www.youtube.com/watch?v=ZLYRDAjZk5s

Extensions: Dash to Panel + gnome-shell-extension-appindicator

You can drag to unmaximise from empty spots on the panel. This creates an issue when the panel is set to the bottom of the screen (see video), as swiping up from empty panel areas brings up the keyboard _and_ unmaximises the active window at the same time. Swiping up from the pinned favourite apps doesn't unmaxmise the window.

**Comment by l3nn4rt** [comment]
This is really annoying, and it's not related to onscreen keyboard (which, probably, can be activated by some gesture from the bottom screen edge on touchscreen devices).

By default, dragging down the top panel with a maximized window does behave as if the window decoration was being dragged (un-maximizng the window) and may be useful for someone.

But it becomes totally useless and buggy when the panel is placed at the bottom of the screen. Dragging up the panel will un-maximize the window and bind the pointer to the window decoration, which means you cannot drag the window vertically.

IMHO, the panel drag-handler should be disabled when the panel is at the bottom of the screen.

**Comment by Mario100000** [comment]
The swipe-up gesture to invoke the on-screen keyboard fails in two scenarios, both seemingly due to overlapping gesture interpretation.

    When a window icon is located at the center of the bottom panel, the gesture fails due to the icon's hover interpretation.

    When a window is present in the path of the gesture, the gesture fails due to the window's gesture interpretation.

As a result, I can't use the virtual keyboard on my tablet without keeping the central panel free of icons and maintaining a sufficient distance between windows and the bottom of the screen.
